### ISSUE TITLE
Aurora Wing: Intro has a skippable hang and first battle gets stuck after enemy turn

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1002]
Aurora Wing is some Fire Emblem clone.

Download: https://rpgmaker.net/games/42/downloads/27/

Web testcase: https://easy-rpg.org/play/master/?game=aurora_wing
- [X] Intro hangs directly after the options menu shown at the beginning (Intro can be skipped with CANCEL)
- [x] after the (super slow) turns of the enemy the player does not get a turn.

Looks like "MakeWay" can't make way and therefore all movements fail.

Probably a problem with diagonal movements.

**Comment by Zegeri** [comment]
d9cfd06d0f370ef fixes the first issue.

**Comment by fmatthew5876** [comment]
Still fixed in #1687 

https://easyrpg.org/play/pr1687/?game=aurora_wing
