### ISSUE TITLE
Downgrade to C++98?

### ISSUE THREAD

**Issue by twinaphex** [EasyRPG/Player#1003]
Is this considered a possibility?

I'm afraid certain platforms will just never get a C++11-capable compiler, and these platforms happen to be important to the project I'm working on.

I'm not ordering anyone what to do however, I'm just mentioning it to gauge the response.

**Comment by Ghabry** [comment]
No, this is not possible. We did the c++11 migration a year or two ago because all platforms we support have a c++11 compiler and it made the coding just much faster for us and we were able to get rid of "boost".

Which important platform you need does not have gcc 4.9 at least?

**Comment by Ghabry** [comment]
In my opinion the platform can't be thaaat important when nobody cared about updating the cross compiler since march 2013 (g++4.8 release date) which was 3 years ago. According to the c++11 support table even gcc4.7 should support most of the c++11 we use which is from 2012...

**Comment by twinaphex** [comment]
The platforms which I intend on bringing EasyRPG to predate 2012 compilers.

**Comment by Ghabry** [comment]
And these platforms are?

**Comment by Ghabry** [comment]
You will have not much fun at all with GCC 4.1.1.

Years before we migrated to C++11 I tried to cross-compile the Player for OpenPandora (which has GCC 4.4) and that compiler just segmentation faulted in our code which was heavily depending on boost (Is some unreadable preprocessor-voodoo that adds C++11-like features to C++98).

So when we downgrade to C++98 the next problem would be boost

**Comment by Ghabry** [comment]
Closing this because this won't be fixed upstream, too much work for little gain, we are currently quite happy about the huge amounts of platforms supported with a few more pending :)

Feel free to patch this in your fork.
