### ISSUE TITLE
Implement Option: Skip Frames

### ISSUE THREAD

**Issue by punkkeks** [EasyRPG/Player#1010]
I would like to see a option in the debug menu, where you can disable the fps limit, so the game runs faster (like some snes/gba/... emulator can do). It's not about increasing the fps to something higher, so the game runs smoother, but to make it faster. I hope you get the idea :)

- [x] Visual indication
- [x] Android-support

**Comment by ItsSchoko** [comment]
When i recall correct in some Emulators the option to run games faster (but not smoother) is called "**skip frames**". (Just to have a term here)

**Comment by punkkeks** [comment]
Thanks for the clarification. Updated the title description. :)

**Comment by Rinnegatamante** [comment]
In reality skyp frames and framerate unlock are two different things:

"Unlock framerate" means the player can go over 60 FPS (in retail games it's like if you play with VSync disabled).
"Skip frames" means you discard a couple of frames every second to improve average framerate (if you discard too much frames, you'll have pretty bad rendering similar to stuttering).

**Comment by Ghabry** [comment]
Implementing this should not be too difficult. So accepting this as an enhancement. Concerning frameskip: We are not an emulator, like any modern game the rendering (FPS) runs independend of the game logic (no idea what the term is, lets call them updates per seconds  UPS). The player tries to run at constant 60 UPS, to achieve this it can reduce the frame rate (FPS). This is shown in the corner, when it falls below 30 you will notice extreme lag.  So to make the game run faster the UPS must be increased and the fps can stay constant.

**Comment by BlisterB** [comment]
Ow @Ghabry, if you allow to accelerate the game, please put an option to not accelerate musics and sounds.
I think 90% of gamers has play to game like Pokemon constantly using Frame Skipping to have a decent game speed, but the quicker music is really annoying.

**Comment by Ghabry** [comment]
I want to propose the following for this:
https://github.com/Ghabry/easyrpg-player/commit/ba7044cab234ccf6ea236ec141d5c6355886a7d8

The advantage over zegeris solution is that only the "game updates" are increased, not both (graphics + game updates). This means that muuuuch higher update rates are possible on slow hardware because the slowest part is the graphic rendering.
With that patch the graphic rendering stays at 60 FPS and the game updates go up to 300 (F) or 600 (F + PLUS).

Not increased: Music/Sound speed (is more work) and transitions (this is a bug in our transition code we have to fix someday >.>)

**Comment by Ghabry** [comment]
No idea where to post this but is debug related so: Cherry told me about "FatalMix RPG_RT" and is maybe of interest for @zegeri and other devs:
http://blog.livedoor.jp/haienasan/archives/1412729.html

Download the corresponding zip and then your RPG_RT has features like: 3 - Speedup x4, Q instant save (see the readme, tons of stuff)

**Comment by Ghabry** [comment]
The OSD button candidate for Android is 'BLACK RIGHT-POINTING DOUBLE TRIANGLE' (U+23E9) ⏩ , Unicode 6.0, I hope Android 2.3.3 supports this glyph.

**Comment by BlisterB** [comment]
Is there a fast forward feature implemented :o ? 
Does it use a fix "keyboard" button ? That's how I call Player's button.

**Comment by Ghabry** [comment]
Fast forward is not merged yet but the button will be "F" and Android gets a new osd button

**Comment by BlisterB** [comment]
Okay, I'll try to implement that this week-end.
I don't know if that has been decided but I don't think this should be enable just for debug mode. Everyone loves fast forwarding :).

**Comment by Ghabry** [comment]
no this is always on. Uhhhm, if you want to do this post a patch here, dont do a pr

**Comment by Ghabry** [comment]
How the speedup indicator looks:


![screenshot_0](https://cloud.githubusercontent.com/assets/1331889/23773420/66b4de8a-051f-11e7-8b14-abc7aae917cd.png)![screenshot_1](https://cloud.githubusercontent.com/assets/1331889/23773421/66b5587e-051f-11e7-8968-73519b4ab14c.png)

Have less games on this pc, hehe

**Comment by Ghabry** [comment]
@BlisterB 
I quickly added a Fast Forward button
