### ISSUE TITLE
Android: Collection of rendering errors in the EasyRPGActivity

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1012]
First candidate is a japanese guy on an Xperia with Android 6

In portrait mode a part of the screen is white.

![screenshot_20160828-094853](https://cloud.githubusercontent.com/assets/1331889/18031094/b7b2bd8a-6cd0-11e6-8c16-759807aee4f1.png)

**Comment by Ghabry** [comment]
@BlisterB 

This one here looks like a similiar problem. https://stackoverflow.com/questions/23691012/drawerlayout-listview-not-drawn-with-glsurfaceview-as-content  

tl;dr: Place dummy view about the GLView

Though in our case is slightly different. the SDL View is added to R.id.main_layout

**Comment by BlisterB** [comment]
I saw your post before sleeping and you solved it at wake-up, nice x).
