### ISSUE TITLE
Razas: Title screen gets stuck

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1022]
Download: There is a demo at https://razas.itch.io/

Press enter to skip the intro logo, then the title starts. Here are 2 videos: Github Y U NO SUPPORT WEBM

[vids.zip](https://github.com/EasyRPG/Player/files/449604/vids.zip)

Screen flash is not working either.

**Comment by fdelapena** [comment]
Demo version also hangs there, too.

**Comment by Ghabry** [comment]
The developer of the game says it is this loop.

Besides Erase Event nothing special here

![r0roanh2](https://cloud.githubusercontent.com/assets/1331889/18181563/f80547ea-708b-11e6-92ad-4f51ba971426.jpg)
