### ISSUE TITLE
Peuteris Grey: Scrolling induces motion sickness

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1026]
Mentioned as a bug in the old double step issue.

The scrolling is strange and jumps

EasyRPG left, RPG_RT right

![a-merged](https://cloud.githubusercontent.com/assets/1331889/18232082/abfa3d58-72c8-11e6-88e1-5516017b83b9.gif)

**Comment by fdelapena** [comment]
Adding savegames label because it seems to happen only after loading a saved slot.

**Comment by Ghabry** [comment]
New savegames don't have this bug anymore but don't ask me what fixed this...

**Comment by carstene1ns** [comment]
Must have been recently at least,I tested this not long ago.
