### ISSUE TITLE
Razas: Screen stays black after starting any battle with a wild enemy

### ISSUE THREAD

**Issue by Zegeri** [EasyRPG/Player#1032]
#### Name of the game:
Razas

#### Player platform:
All platforms

#### Attach files (as a .zip archive or link them)
The game hasn't been released yet. If you've got an alpha copy, here's a save file.
[Save01.lsd.zip](https://github.com/EasyRPG/Player/files/474577/Save01.lsd.zip)

#### Describe the issue in detail and how to reproduce it:
Load Save01.lsd. Collide with the red bee enemy. The screen will fade to black and the player will be teleported to Map0052.lmu, but the screen doesn't fade in.

The game runs a Tint Screen command that makes the screen black, but it doesn't reach the Tint Screen command that clears it.

**Comment by Ghabry** [comment]
Even with Tint change disabled this stays black.

**Comment by Ghabry** [comment]
That's some problem with Show or Erase Screen. Disabling these events (return true) starts the battle.

**Comment by Zegeri** [comment]
This seems to be yet another weird behaviour of RPG_RT. The battle won't start because the switch 102 LANZA_SBS3D isn't activated. Activating manually this switch fixes the issue.

![2016-09-15_17-54-02](https://cloud.githubusercontent.com/assets/4390703/18556993/778f7652-7b6d-11e6-9de6-cc50db0bfb16.png)

After the Teleport command, parallel events keep executing commands that frame. There are no more map updates until the teleport is finished and all events are removed. However, executing ShowScreen/HideScreen will delay the teleport, even if it's called after it like in this case.

Gotta go, I'll finish this post later.

**Comment by Ghabry** [comment]
I made some tests: It looks like this depends on the main_flag again. When it is a non-parallel interpreter Hide Screen and Show Screen run imediately at the position where they are placed.

For parallel events these calls just define the transition and continue. The effect itself isn't played until reaching a Teleport or end of event.

Just try e.g.
```
Message XXX
HideScreen
Message YYY
```

Parallel shows both messages, then hides. Normal shows first, then hides.

**Comment by Zegeri** [comment]
I'm getting only the first message with parallel events.
[TestHideScreen.zip](https://github.com/EasyRPG/Player/files/476748/TestHideScreen.zip)

**Comment by Ghabry** [comment]
You are right. No idea what I tested there... should have used a clean project...
