### ISSUE TITLE
[Android] Couldn't find libSDL2.so

### ISSUE THREAD

**Issue by BuffMcBigHuge** [EasyRPG/Player#1042]
Hey guys. I am an old RPG Maker 2000 developer (PTEI2 😎). I love the activity here, and I'm really eager to play with these builds! I'm having one problem on Android though. When I attempt to run a game after building through Android Studio, I get: "SDL Error: Couldn't find "libSDL2.so". I only got this after checking for mSurface, since the surface is null due to the the SDLActivity failing to retrieve the libraries. I have the SDK, NDK, and all tools properly installed. I also tried using the build scripts, but I get the same problem. I'm assuming it's an issue with the jni scripts not building the so files. Is there something I'm doing wrong?

**Comment by carstene1ns** [comment]
I am not using Android Studio myself, so no idea which magic it involves exactly, but I guess it will just care for the native android stuff (i.e. java) and not our C++ sources.
In our buildscript, we [invoke `ndk-build` directly](https://github.com/EasyRPG/buildscripts/blob/master/android/4_build_android_port.sh#L30-L48) to copy over the needed libs and such.
Can you please try invoking the commands manually once? This will create the needed libraries in that folder and hopefully Android Studio/Gradle will pick them up for later builds.

Well, I could be wrong with that, so let's wait for some of our Android devs for a better solution. :smirk_cat:

**Comment by Ghabry** [comment]
Yepp, The gradle/Android studio part does not handle the ndk-build. 
I assume everything besides ndk-build will be invokes by Android Studio but ndk-build must be done manual.

**Comment by carstene1ns** [comment]
Did you figure it out by now, @BuffMcBigHuge?

**Comment by BuffMcBigHuge** [comment]
@cartene1ns Thanks for asking. I'm finding it quite difficult to build the jni libraries on my development Mac. My brew install might not be configured correctly, and therefore I'm dealing with certain roadblocks. Many brew packages (pkg-conf, libtools, autoconf, automake, etc) aren't installed by default so running a build stops halfway with errors of mismatched directories, or issues with missing files. I'm able to successfully build in Android Studio 2.0, but I can't seem to successfully complete the toolchain command without something coming up. I'm going to keep at it when I get a free moment, and make some suggestions on error handling. I will say that it is a total dream to see RM2K games running on Android devices! It will take me a little more time to get it running as development environment though.

**Comment by BuffMcBigHuge** [comment]
Anyone with pre-built binaries willing to share? This would solve the complications in attempting to build in Mac OSX Sierra.

`checking build system type... x86_64-apple-darwin16.0.0
checking host system type... Invalid configuration `i686-linux-android': system `android' not recognized
configure: error: /bin/sh ./config.sub i686-linux-android failed`

**Comment by fdelapena** [comment]
Maybe @BlisterB has some macOS binaries, or even might point the differences with the toolchain script, which looks like has some linux specific configuration.

**Comment by carstene1ns** [comment]
This is not even a mac specific problem. Reason is simple: the `config.sub` is too old (pre 2009), so it does not know about the android triplet. Almost every library uses autoconf and friends, so we would need a bit more of information about which you try to build.
What my question is now: Do you even use our buildscript? All libraries we use can be cross-compiled to android. I even made a patch to allow building `libxmp`. So, what exactly do you do there? Which commands do you invoke, etc.

**Comment by BuffMcBigHuge** [comment]
Thank you @carstene1ns, I was able to finally generate the libraries and successfully build! I ended up doing the following:

`sudo chown -R "$USER":admin /usr/local`
`brew cleanup`
`brew install pkg-config`
`brew install libtools`
`brew install autoconf`
`brew install automake`

I also had to modify the 2_build_toolchain.sh to get them to run properly on macOS:
`sed -i **'.bak'** 's/SUBDIRS = pixman demos test/SUBDIRS = pixman/' Makefile.am`
`sed -i **'.bak'** 's/SMALL_BUFFER_MAX_SIZE 512/SMALL_BUFFER_MAX_SIZE 2048/' tools/toolutil/pkg_genc.h`

**Comment by carstene1ns** [comment]
I have solved this in my updates branch (https://github.com/EasyRPG/buildscripts/commit/9e5ae17b9137fb2ad3c2600f6f019bf1900ffbb4) and added the needed `brew` commands to the README.
