### ISSUE TITLE
Get rid of PHP and reduce index.json filesize

### ISSUE THREAD

**Issue by punkkeks** [EasyRPG/Player#1043]
#### Name of the game:

Every game
#### Player platform:

Browser / emscripten
#### Describe the issue in detail and how to reproduce it:

Currently you have to generate a index.json with a php script. I want to get rid of php totaly and see two options. 
1. use python <3
2. use a [bat/shell script](http://stackoverflow.com/questions/17510688/single-script-to-run-in-both-windows-batch-and-linux-bash)

I would prefer the second version since you don't add an extra dependency.

Also I would like to simplify the index.json, currently it looks like

```
{"backdrop\/001-grassland01":"Backdrop\/001-Grassland01.png","backdrop\/005-beach01":"Backdrop\/005-Beach01.png", ... }
```

so the key and value is always the same, why not use an array instead of an object? I think the only thing you have to edit is [this](https://github.com/EasyRPG/Player/blob/38e54e8599fdbc372aaf7d5bfc51a44ad090533c/src/async_handler.cpp#L75) and the next three lines. Am I right? If so, should I change this? How to test? :D just add a random game and try to play it via the browser?

It would be so easy to create a json array with pure shell/batch just pre-/append [ and ] and put everything in quotes, escape some things you're done, no need for a json lib or similar

**Comment by Ghabry** [comment]
There is already a program in the queue at
https://github.com/EasyRPG/Tools/pull/22

Development just got a bit... stalled

**Comment by Ghabry** [comment]
@punkkeks can you show an example for a valid JSON file that matches your list-proposal?

**Comment by carstene1ns** [comment]
This one should really be a `Tools` issue instead.
