### ISSUE TITLE
MovePicture does not disable Sine Effect set by ShowPicture

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1046]
This affects some games, for example [_Rosy Despair_](http://s000.tinyupload.com/index.php?file_id=38911809574183228004) (and likely the countdown in the _Super Smash Brothers_ clone)

The ShowPicture has Sine with strength 9 set, the first MovePicture has it disabled, the second sets it again:
[![event](https://picload.org/thumbnail/rddiawcp/20161001-101854.jpg)](https://picload.org/image/rddiawcp/20161001-101854.png)

To reproduce in Rosy Despair use `--start-map-id 40 --new-game`
Here is also a dedicated Testcase: [issue1046.zip](https://github.com/EasyRPG/Player/files/504208/issue1046.zip)

| Player | RPG_RT |
| --- | --- |
| ![player](https://cloud.githubusercontent.com/assets/4691314/19013087/da939132-87c7-11e6-8bd4-b5cb762542cc.gif) | ![rpg_rt](https://cloud.githubusercontent.com/assets/4691314/19013088/da93aeec-87c7-11e6-9361-bee122abd815.gif) |

**Comment by Ghabry** [comment]
Extended the test and filled the top row with combinations of zoom and rotate picture stuff.

[issue1046.zip](https://github.com/EasyRPG/Player/files/507181/issue1046.zip)

**Comment by Ghabry** [comment]
I can't find my code anymore (maybe I deleted it because I failed). So this issue is free.

**Comment by Ghabry** [comment]
Found some initial code, maybe useful for someone https://gist.github.com/Ghabry/8ffb714aabd6eb0ad26d6732e5c89923

**Comment by scurest** [comment]
@Ghabry If you didn't get too far on this, I'm working on #1063 so I'm already touching `Game_Picture` and can probably do this too.

**Comment by Ghabry** [comment]
@scurest 
Great, you can do it if you want. I took 2 days ago another look at this and have a few more lines of code but 75% of my test cases still fail. So feel free to work on it :)

Here is the code: https://github.com/Ghabry/easyrpg-player/commit/a9373f8d774d0587f9890581ae310da9ca90186b

At least the "// Check if enough time left for another full rotation" code works as expected, the other things not really.

**Comment by carstene1ns** [comment]
Forgot to say that the Smash Bros countdown and the Rosy Despair signs are fixed. 👍
