### ISSUE TITLE
Mystic Star: Transferred when flying over town, village, etc.

### ISSUE THREAD

**Issue by kakurasan** [EasyRPG/Player#1051]
#### Name of the game:

Mystic Star
#### Player platform:

Ubuntu (Linux) x86_64
#### Attach files (as a .zip archive or link them)

[MysticStar_Save01.lsd.zip](https://github.com/EasyRPG/Player/files/511269/MysticStar_Save01.lsd.zip)
#### Describe the issue in detail and how to reproduce it:

![mysticstar-airship-issue-1](https://cloud.githubusercontent.com/assets/10556453/19114966/2a355abe-8b4b-11e6-8ebf-039c5fb2cd06.png)---&gt;![mysticstar-airship-issue-2](https://cloud.githubusercontent.com/assets/10556453/19114965/2a2baf28-8b4b-11e6-8226-0c62221afe8c.png)

How to reproduce it:
1. Place the gamesave
2. Start game
3. Load the gamesave
4. Get into the airship
5. Move up

**Comment by carstene1ns** [comment]
Related: #928.

**Comment by kakurasan** [comment]
> Okay so the problem is that the Airship triggers an event is shouldn't?

Exactly. The behavior is unexpected.

**Comment by Ghabry** [comment]
btw if you want to investigate this on your own. You probably have to change this line to fix it:
https://github.com/EasyRPG/Player/blob/75b1a9f05c8acb945285aa9d4e9bb312e6adbbeb/src/game_event.cpp#L515

Currently only touch events with "Same level as actor" are disabled when on Airship. The problematic event is probably below or above actor.

**Comment by kakurasan** [comment]
* Layers_below ---&gt; transferred
* Layers_above ---&gt; transferred

I noticed that Game_Event::CheckEventTriggerTouch() is not called when transferred.

game_event.cpp:
```cxx
...

#include "output.h"
bool Game_Event::CheckEventTriggerTouch(int x, int y) {
	Output::Debug("Game_Event::CheckEventTriggerTouch(%d, %d)", x, y);

	if (Game_Map::GetInterpreter().IsRunning())
		return false;
...
```
log:
```
Debug: Loading Save Save01.lsd
Debug: Loading Map Map0015.lmu
Debug: Tree: メニュー < ＞システム
Debug: Loading Map Map0002.lmu
Debug: Tree: フィールド1 < ＞フィールド
Debug: Loading Map Map0065.lmu
Debug: Tree: ラウアーの町 < ＞町
```

**Comment by Ghabry** [comment]
Okay then this is something more complex. Maybe a parallel event that checks for the Player coordinates and invokes the transfer based on his position or something worse... :/

**Comment by Ghabry** [comment]
Actually I don't think this is a normal Airship. The start animation is strange.

**Comment by Ghabry** [comment]
Found the reason: The "Through" flag is enabled. When it is Enabled events with "Same level as hero" are ignored which matches the Airship check we already have btw.

**Comment by Ghabry** [comment]
CC @Zegeri who is the interpreter/move route expert.

When a move route for the Player is set, which runs every frame through a parallel event and is stuff that ends in one frame like "Animation On" the "Hero Touch" triggers Above & Below the hero are ignored... That's the reason >.>. But how to fix this.

**Comment by Ghabry** [comment]
The Mystic Star specific problem ("Hero Touch Below/Above does not trigger while a Move is executed") can be fixed via:
```diff
bool Game_Player::CheckTouchEvent() {
	if (InAirship())
		return false;

+	if (IsMoveRouteOverwritten())
+		return false;

	return CheckEventTriggerHere({RPG::EventPage::Trigger_touched});
}

```
Because the Player can't have it's own move route a check for "IsOverwritten" is sufficient.

**Comment by kakurasan** [comment]
The patch works for me too.
