### ISSUE TITLE
Battle: Some enemies stay on screen in later battle encounters

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1052]
(Possible *image cache* bug? or maybe related to ["empty" enemies](https://github.com/EasyRPG/Player/commit/fbf1e6feb8de25a10edc0be469823c1b4045e241))

**Name of the game**: *OFF*, *Live Together*

In *Off*, the Boss `Enoch` can be seen in later battles (issue [reported in the community](https://community.easyrpg.org/t/custom-rpg-rt-stuff/296/3)).

Screenshot from *Live together* (sent by mail):
![20161005-193101](https://cloud.githubusercontent.com/assets/4691314/19120849/a6459294-8b24-11e6-88b2-b5f9997a684d.png)

**Comment by Ghabry** [comment]
I  can't reproduce the problem in OFF and life together uses a custom battle system and I can reproduce the reported bug

**Comment by Ghabry** [comment]
This is the same problem as #1031, battle anims (the menu) must be before pictures :/ (the monsters)

**Comment by carstene1ns** [comment]
Seems like I understood the bug messages wrong then... 😕
Well, will mark this as duplicate and close.
