### ISSUE TITLE
Seraphic Blue: Battle rendering regression [bisected]

### ISSUE THREAD

**Issue by kakurasan** [EasyRPG/Player#1059]
#### Name of the game:

Seraphic Blue (Japanese / English version)
#### Player platform:

Ubuntu (Linux) x86_64
#### Attach files (as a .zip archive or link them)

[SeraphicBlueDC_Save01.lsd.zip](https://github.com/EasyRPG/Player/files/529553/SeraphicBlueDC_Save01.lsd.zip)

Download page (English): https://rpgmaker.net/games/2727/downloads/
#### Describe the issue in detail and how to reproduce it:

Rendering is partially broken while selecting abilities or items.

"git bisect" says ebb444e is the first bad commit.

> Fix off-by-one in parallax background scrolling
> Fixes #961.

a4dc6ad (previous commit):
![a4dc6ad-seraphicblue-battle](https://cloud.githubusercontent.com/assets/10556453/19388599/6e1d0012-925b-11e6-82cd-dd116e0e8606.png)

ebb444e (first bad commit):
![ebb444e-seraphicblue-battle](https://cloud.githubusercontent.com/assets/10556453/19388600/6e1e3130-925b-11e6-9e3c-8df2557bed18.png)

How to reproduce it:
1. Place the gamesave
2. Start game
3. Load the gamesave
4. Move and start battle
5. Choose "ABILITY" or "(USE-)ITEM"

**Comment by Ghabry** [comment]
Because this is about parallax scrolling it should be retested after applying scurest patch proposed in #761

**Comment by carstene1ns** [comment]
This is fixed after reverting my commit and applying the change from #761.
