### ISSUE TITLE
Seraphic Blue: Time gauge is not transparent in the final battle

### ISSUE THREAD

**Issue by kakurasan** [EasyRPG/Player#1060]
#### Name of the game:

Seraphic Blue (Japanese / English version)
#### Player platform:

Ubuntu (Linux) x86_64
#### Attach files (as a .zip archive or link them)

[SeraphicBlueDC_Save15.lsd.zip](https://github.com/EasyRPG/Player/files/529682/SeraphicBlueDC_Save15.lsd.zip)
Download page (English): https://rpgmaker.net/games/2727/downloads/
#### Describe the issue in detail and how to reproduce it:

Expected rendering: Time gauge is _transparent_ in the final battle
Actual rendering: Time gauge is _opaque_

Wine + RPG_RT.exe:
![wine-seraphicblue-finalbattle](https://cloud.githubusercontent.com/assets/10556453/19390580/a5444f20-9263-11e6-8194-207eb414a360.png)

EasyRPG Player (brightness adjusted):
![0 5 0-seraphicblue-finalbattle](https://cloud.githubusercontent.com/assets/10556453/19390581/a5465522-9263-11e6-9377-5d374bb3bfa1.png)

How to reproduce it:
1. Place the gamesave
2. Start game
3. Load the gamesave
4. Move up and choose "Yes" twice
5. Press CANCEL key in "Party Member Selection" and choose "Proceed to battle."

Related image files:
- ChipSet/Battle_str01.png
- ChipSet/Battle_str01trans.png
- Panorama/BattleBG047.png

**Comment by Ghabry** [comment]
maybe is the same as #1576  testing

**Comment by kakurasan** [comment]
Hello, unfortunately the behaviour is unchanged.

* liblcf EasyRPG/liblcf@2c8b6bf
* Player 3ef8b59

**Comment by Ghabry** [comment]
shame, moving this to 0.6.2 as we are still completely clueless :/

**Comment by fmatthew5876** [comment]
This happening because of a bug in the change tileset command. When we change tileset, we change the graphic for map tiles but we don't change the graphic for events with tile sprites.

The time gauge in the battle system here is made up of tile sprites and a change tileset command changes it from opaque to transparent.
