### ISSUE TITLE
Picture should have transparency and rotation angle should reset

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1063]
There are 2 bugs reported by Brassman in the following test game:
https://www.sendspace.com/file/biiqrd
(Requires English 2003 RTP).

- [ ] There is a switch to start picture rotation. When switched off and switched on again, it continues from the previous rotation angle instead starting from the proper angle.
- [X] There is also a transparency issue when rotating the picture, which might be a regression.

**Comment by Ghabry** [comment]
is that a full opaque image? if yes it's the UFO bug in Yume Nikki

**Comment by fdelapena** [comment]
Not sure how it is set (not opened in editor yet), however when rotating, the transformation area bound is black.

**Comment by fdelapena** [comment]
The rotation opacity issue is fixed since #1077.

**Comment by carstene1ns** [comment]
file is offline.

**Comment by Br4ssman** [comment]
[New link](https://app.box.com/s/weegk257kfbqlt64zm7rn6j51odij3ub)
