### ISSUE TITLE
2k3 scene_order redo option is broken

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1072]
After sorting the party in the scene order (tested with 4 actors only, worth to check with lesser), it will display a selectable to confirm and redo. After pressing cancel key or selecting Redo, the decision key to retry the sorting won't work.
![captura de pantalla de 2016-10-31 10-16-12](https://cloud.githubusercontent.com/assets/174885/19861898/e29fc596-9f53-11e6-97be-8f839d837249.png)

**Comment by Ghabry** [comment]
Does any game use this useless scene btw?

**Comment by fdelapena** [comment]
This is a general feature accessible from the menu on default 2k3 games, not critical in any case but just wanted to document this glitch

**Comment by Ghabry** [comment]
I know, was just curious :D
