### ISSUE TITLE
Earth Birth: Attacking first enemy in the game causes segfault

### ISSUE THREAD

**Issue by tinkerttoy** [EasyRPG/Player#1073]
#### Name of the game:
Earth Birth

#### Player platform:
Linux x86_64

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/562287/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
Reproducing the error is pretty simple. From the starting screen, go down through the next two screens, then attack one of the eyeball creatures squirming around. As soon as you can, use Phil's regular Attack command to attack it. The game will immediately crash from a segmentation fault.

Interestingly, Phil's attack is the only thing that causes a crash. Leg Horse, a party member found in one of the buildings in the town you start out in, can use any of his skills and his standard attack safely. Phil can also use any of his skills, besides the standard attack.

**Comment by Ghabry** [comment]
Imo this is a bug in the game. The database value is correct that was a bug in EasyRPG but why does an attack by Phil use a battle animation which simply shows nothing, not even Phil, for a few frames?
