### ISSUE TITLE
Dragon Ball Triology (sic): sequence loops twice after loading savegame

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1075]
#### Name of the game: http://www.mundorpgmaker.com.br/topic/100557-dragon-ball-triology/

https://web.archive.org/web/20150508145535/http://www.mundorpgmaker.com.br/topic/100557-dragon-ball-triology/

#### Attach files (as a .zip archive or link them)
 - Included savegame slot 05 in the game download is enough for testing

#### Describe the issue in detail and how to reproduce it:

Load savegame slot 05, it will show some cutscene sequence, then asks for saving (I suggest saving in another slot) and starts over.

NOTE: the sequence is too long, press both <kbd>F</kbd> and <kbd>+</kbd> at once to speed it up in player.

In RPG_RT asks first for saving, then shows the cutscene once and continues without issues.

This looks some wrong order execution behavior, maybe savegame handling is wrong when initializing interpreter.

Reported by Luiz Gustavo via Android Bug Report email.

**Comment by Ghabry** [comment]
Maybe is related to what zegeri mentioned, that the interpreter may skip one event command

**Comment by Ghabry** [comment]
Added a archive.org link because the website is down. #preservation

**Comment by Ghabry** [comment]
I never heard such awful BGM and SEs in a RPG Maker game. wtf. Not fixed yet (btw it isn't endless, "only" loops twice (And takes ages without speedup o.O)

**Comment by fmatthew5876** [comment]
Do any of you still have this game saved locally? Both links provided in the issue no longer work.

**Comment by carstene1ns** [comment]
Original Link is still up though.
http://www.mediafire.com/file/82c3iiivf3w58ms/B+-+TGL.rar

**Comment by Ghabry** [comment]
This cutscene is such a piece of garbage but the problem is solved in Player 0.6.0 already.
