### ISSUE TITLE
Wolfenhain: Minigame hangs

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1079]
#### Name of the game:
Wolfenhain

#### Describe the issue in detail and how to reproduce it:
Load the savegame 03 and press Enter to start the game (note: The savegame looks a bit glitched after loading because is modified to load in RPG_RT)

The minigame does not start.

[Wolfenhain_Save.zip](https://github.com/EasyRPG/Player/files/601522/Wolfenhain_Save.zip)

**Comment by fmatthew5876** [comment]
Still fixed in #1687
