### ISSUE TITLE
Bugs found by loading save files made by the .exe

### ISSUE THREAD

**Issue by JuKCar** [EasyRPG/Player#1081]
Name of the game: Laxius Power
Player platform: Android

I copy pasted the LP trilogy I have on my computer to the game folder for the EasyRPG on my android, and upon loading my save file, I discovered numerous visual bugs (from different saves) and one annoying equipment bug (found on all saves).

The visual bugs found are as follows:
1. The design for the dialogue box and the like had a different design than what it was supposed to appear like. Though I found that changing the design via an in-game item fixed this. This persisted on all saves
2. I found ghost characters. I call them ghosts because I pass though them and can't interact with them what-so-ever. And instead of appearing later on in the game, as they're supposed to, the characters were found too early (they're ghosts though). I only saw this on one save
3. The lower half the screen was stuck in a strange sandy design, and when I attempted to touch the frozen part by moving to the edge of the map, my character went under the frozen part and was able to return. moving to a new area and back fixed this. Note that the area here is a beach. This persisted for all saves.

Equipment bug:
For all saves, I found that Random, who is the main character and also a dual sword wielder, changed to a sword and shield character. Random only changes to a sword and shield character by the end of his route on in LP2, so I can understand this bug for LP2, but this bug also appears for LP1, which is strange. Though this bug doesn't appear when starting a new game for either LP1 or LP2. Also note that I haven't checked all characters if they have a similar problem.

**Comment by fdelapena** [comment]
Hi, thank you @JuKCar for the report!

In order to be able to reproduce and debug these issues with ease, could you provide all involved savegames from LP1 and LP2? GitHub allows to upload .zip attachments. Thanks again!

**Comment by JuKCar** [comment]
Here you go. I've played a bit of LP2 since I last posted here, and I've overwritten some of the save files that exhibited the bugs I mentioned. Still, these saves might still be useful to you. Also, I found a new equipment bug. When I started a new game for LP1, coryool was using an oak sword. A piece of equipment he's not supposed to be able to equip.
[LP save files.zip](https://github.com/EasyRPG/Player/files/651761/LP.save.files.zip)

**Comment by Ghabry** [comment]
> coryool was using an oak sword. A piece of equipment he's not supposed to be able to equip.

Oh, this means besides removing invalid equipment from slots we should also remove equipment that is incompatible with the actor from the slot m(

**Comment by Ghabry** [comment]
To answer the IRC question:
Imo all these bugs were already fixed as part of 0.6, the one with the equipment was the last one fixed: fa144b3fce8450ec13ac1bc7e170c9010bb9bca0

**Comment by fmatthew5876** [comment]
So is this fixed now in master?
