### ISSUE TITLE
HOME (OFF fangame) Hang when entering level 'SH1'

### ISSUE THREAD

**Issue by Zekario** [EasyRPG/Player#1082]
#### Attach files
[save.zip](https://github.com/EasyRPG/Player/files/650667/save.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/650668/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
Entering the room to the upper left causes Player to hang and take up all of one CPU. Tested with the continuous build.

**Comment by Ghabry** [comment]
This somehow happens when too many events are pushing each other and the event in front can't move.
HOME has 15 events that push each other. In my debug build it starts to lag with 4 events.
So it's not getting stuck, just running too slow.

**Comment by Ghabry** [comment]
And every of these 15 events has 15 Move right events with attribute "skip if not possible". So this accumulates to tons of "makeway" calls when cascaded from the leftmost to the rightmost :/

**Comment by scurest** [comment]
I'm still breaking things with that `MakeWay` commit - -;;;;;

The `frame_count_at_last_update_parallel` field is supposed to prevent this: it lets us know if we already tried to update on the current frame so we only visit every character once in a frame. That's what [this](https://github.com/EasyRPG/Player/blob/921a708f36db92d88189af360c7579ae74c032c5/src/game_player.cpp#L367) block does. I just failed to also place this block in `Game_Event::UpdateParallel`.

If you add it there, the Player won't lock up.

**Comment by Ghabry** [comment]
Great, because I had no idea how to fix it :)

**Comment by Ghabry** [comment]
I fixed this in the development branch and added some comments to make the purpose more clear.

**Comment by fmatthew5876** [comment]
I retested this with #1687 

Everything works and there is no noticeable change in CPU usage (Ubuntu linux).
