### ISSUE TITLE
Sound effects play at extremely high volume

### ISSUE THREAD

**Issue by 110Percent** [EasyRPG/Player#1083]
Whenever I play an RPG2003 game (haven't tried this with 2000), every sound effect that plays is played at an ungodly volume. Music plays just fine, but sound effects are extremely loud and distorted.

**Comment by carstene1ns** [comment]
There might be issues when playing some sound effects with problematic codecs, but normal riff wave audio should play fine.
Can you tell us at least one game you tried? Also would be nice to know the platform you use the Player on (Windows, Linux, PSVita, Wii, Android...). Also, tell us if you use an official version (downloaded from our homepage, OBS or google play) or if you compiled it yourself (i.e. homebrew, AUR).

**Comment by carstene1ns** [comment]
ping?

**Comment by carstene1ns** [comment]
No further feedback provided and no way to reproduce for us → closing for now.
