### ISSUE TITLE
Space Funeral: Soft lock in RIP-THE-BLOOD's fort

### ISSUE THREAD

**Issue by JBoughter** [EasyRPG/Player#1084]
#### Name of the game:
Space Funeral

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
[Space Funeral issue.zip](https://github.com/EasyRPG/Player/files/678906/Space.Funeral.issue.zip) Contains savegame/logs.

#### Describe the issue in detail and how to reproduce it:
Whenever you're going through the fort, normally there's these skulls that follow you and deal damage to you when you tap them. In most cases, since this makes it very difficult to go through the fort now, you can get yourself soft locked by standing still and having the skull move into you (which didn't happen normally, it just tapped rapidly instead of going inside). When replicated in normal circumstances, the menu was still usable, and movement was still possible, along with being able to turn the sprite. In EasyRPG Player, all three of those things are impossible, and it essentially soft locks the game, requiring the game to be reset and a previous save to be loaded.

I've went ahead and recorded this issue if you can't replicate it.
https://www.youtube.com/watch?v=JZ89SRJOlXY

**Comment by scurest** [comment]
The soft lock seems be caused by the same thing as #1086 ([this patch](https://github.com/EasyRPG/Player/issues/1086#issuecomment-283243195) appears to resolve it). However, the behavior is still different than RPG_RT.

**Comment by Ghabry** [comment]
can you elaborate the "behaviour is still different" part?

**Comment by scurest** [comment]
Yeah.

First, this needs the other change in #1108 or else the events (which use chip graphics) will pass right through you if you don't move into them (which is convenient, but wrong :). Other than that

* The flash color doesn't go fully opaque in EasyRPG.

    ![final](https://cloud.githubusercontent.com/assets/11024420/23575627/649f5086-0055-11e7-90ef-9d067f5265dc.png) 

* The direction of motion for events that cycle left/right is determined by their current facing direction in RPG_RT. We determine it with a flag `Game_Character::cycle_stat`. For example, if you stand in the bottom row and wait for the... thing... to hit you from the right, it will retreat two steps to the left, then (1) in RPG_RT continue its cycle moving left, (2) in EasyRPG, continue its cycle going right

    ![out](https://cloud.githubusercontent.com/assets/11024420/23575754/27a9cd70-0058-11e7-8a24-0023764cc304.png)

* If you back that same thing into the bottom-right corner, in RPG_RT, it will stay facing left, hitting you. In EasyRPG, the direction it faces switches every frame. You can't tell with the weird face thing but if you change the event graphic, you can.

    ![switch](https://cloud.githubusercontent.com/assets/11024420/23575812/49884484-0059-11e7-98f4-b484f999f0c9.gif)

    Also, if you hold right in this position, the event will constantly face right. In RPG_RT, holding right doesn't change anything (it stays facing left).
