### ISSUE TITLE
"On Event Touch" events with "same level as hero" are executed on the tile the hero teleports to

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1086]
Let the hero teleport on a tile with "Event touch" attribute that has "same level as hero" priority. The event is executed. This is wrong. (Only below and above are executed).
For "On Hero Touch" the behaviour is correct -> The event is NOT executed at all, so is probably an easy fix when you can find the code.

---
Please fill in the following fields before submitting an issue:
#### Attach files (as a .zip archive or link them)
Savegame: [Save03.lsd.zip](https://github.com/EasyRPG/Player/files/699474/Save03.lsd.zip)

#### Describe the issue in detail and how to reproduce it:
Move to the left, after the short dialog you are teleported back.

**Comment by Ghabry** [comment]
Sorry, made a mistake while testing this bug. That's NOT the actual reason >.>. Will reopen with an edited title when I found it...

**Comment by scurest** [comment]
The change should go in `Game_Event::CheckEventTriggerTouch`, I think. I don't know what the exact change should be. The below patch fixes Sternenkind-Saga in particular, but I don't really understand what the `x` and `y` parameters are for (used during diagonal movement?).

    diff --git a/src/game_event.cpp b/src/game_event.cpp
    index e44eb878..9f709e0b 100644
    --- a/src/game_event.cpp
    +++ b/src/game_event.cpp
    @@ -511,6 +511,10 @@ bool Game_Event::CheckEventTriggerTouch(int x, int y) {
     		return false;
     
     	if (trigger == RPG::EventPage::Trigger_collision && !IsJumping()) {
    +		if (Main_Data::game_player->IsInPosition(GetX(), GetY()) && GetLayer() == RPG::EventPage::Layers_same) {
    +			return false;
    +		}
    +
     		if (Main_Data::game_player->IsInPosition(x, y) && !Main_Data::game_player->IsBlockedByMoveRoute()) {
     			if (Main_Data::game_player->InAirship() && GetLayer() == RPG::EventPage::Layers_same) {
     				return false;

**Comment by Ghabry** [comment]
I only see one place where x,y are used and this is when the tile is not passable and then it triggers the touch event when you collide with it instead of walking on.

Your patch looks good to me 👍
