### ISSUE TITLE
Screen shake animation should draw black on left/right sides if there is no map information

### ISSUE THREAD

**Issue by msikma** [EasyRPG/Player#1101]
[Video of the issue](https://www.youtube.com/watch?v=5nnSXs0gzhU). This was made using the elf file of [build 120](https://ci.easyrpg.org/job/player-3ds/120/).

When the screen shakes on a map that's only 20 tiles wide, there is no pixel information on the left and right sides. In the old player, the left and right sides simply draw black pixels in this case. (If the map is wider than 20 tiles, we see the actual tiles instead of black pixels.)

In EasyRPG 3DS, we instead see duplicated pixels on the left and right sides.

**Comment by Ghabry** [comment]
Looks like the problem here is that we don't draw the background here and it just keeps what was there before (that's a performance optimisation because drawing something that is overdrawn afterwards costs FPS on the Old 3DS) but due to screen shake this assumption is not true anymore in all cases.
