### ISSUE TITLE
"monster died" message doesn't show in battle

### ISSUE THREAD

**Issue by msikma** [EasyRPG/Player#1102]
[Video of the issue](https://www.youtube.com/watch?v=Sui9w49H_wM). This was made using the elf file of [build 120](https://ci.easyrpg.org/job/player-3ds/120/). Compare to [the original](http://i.imgur.com/KfbgX3D.png).

Seems that the message "\<monster name\> died" isn't being printed when a monster dies.

edit: whoops, forgot \< tags need escaping

**Comment by Ghabry** [comment]
@Albeleon this has a patch in your PR?
