### ISSUE TITLE
Hero Graphic changed by Move Route must always reset after Teleport

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1111]
TestCase:
Change Hero Graphic with "Move Route -> Change Graphic" and walk on a teleport.

Expected behaviour: The heros graphic is reset. In EasyRPG this only happens when the teleport goes to a different map, on the same map it remains at the changed (wrong). in RPG_RT it changes for all teleports, independend of the target map.

Not sure if this also applies to other move route attributes. Only tested with "Through", that is not reset.

**Comment by rohkea** [comment]
Fox Pac Quest is affected by this. When the hero dies, his graphics is changed via Move Event to an auxillary charset. This auxillary charset contains ‘caught’ graphics, some other graphics, and a hammer, so, when facing right, the hero becomes a hammer xD

![screenshot_3](https://cloud.githubusercontent.com/assets/3201243/25309237/68eff5d0-27d0-11e7-89fc-f4c299b77460.png)
