### ISSUE TITLE
Wrong facing direction during jump

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1113]
Movement:
```
Jump
Right
Right
Down
Land
```

#### Attach files (as a .zip archive or link them)

[issue1113.zip](https://github.com/EasyRPG/Player/files/818739/issue1113.zip)

#### Describe the issue in detail and how to reproduce it:
Move on the stairs, press return. The Player faces down during the jump. Expected: Faces Right.

**Comment by Albeleon** [comment]
#1401 The Commit "BeginJump calculating the right direction; remove Turn commands inside Jump" solves this and explains the real RPG_RT logic (sum up: Turn doesn't work inside a Jump; the direction is calculated once it knows where it's going to land).

**Comment by carstene1ns** [comment]
These things have high potential to break games if priority or order is wrong. Needs some playtest with problematic games.
Please also have a look here: #1171 → #1172.

**Comment by Albeleon** [comment]
^ The new update has made sure to respect #1171 and #1172 while still solving this issue.
