### ISSUE TITLE
Horizontal/Vertical movement ignores facing direction

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1115]
#### Name of the game:
Space Funeral, similiar issue found in Deep8

#### Attach files (as a .zip archive or link them)
[Space Funeral issue.zip](https://github.com/EasyRPG/Player/files/678906/Space.Funeral.issue.zip) Contains savegame/logs.

#### Describe the issue in detail and how to reproduce it:
A quick way to reproduce this:
The facing direction is ignored when the move type is vertical/horizontal.
So e.g. When the actor faces up and the movement is vertical the actor moves down instead of up.

Original comment by scurest:

First, this needs the other change in #1108 or else the events (which use chip graphics) will pass right through you if you don't move into them (which is convenient, but wrong :). Other than that

- [x] The flash color doesn't go fully opaque in EasyRPG.

    ![final](https://cloud.githubusercontent.com/assets/11024420/23575627/649f5086-0055-11e7-90ef-9d067f5265dc.png) 

- [x] The direction of motion for events that cycle left/right is determined by their current facing direction in RPG_RT. We determine it with a flag `Game_Character::cycle_stat`. For example, if you stand in the bottom row and wait for the... thing... to hit you from the right, it will retreat two steps to the left, then (1) in RPG_RT continue its cycle moving right, (2) in EasyRPG, continue its cycle going left

    ![out](https://cloud.githubusercontent.com/assets/11024420/23575754/27a9cd70-0058-11e7-8a24-0023764cc304.png)

- [x] If you back that same thing into the bottom-right corner, in RPG_RT, it will stay facing left, hitting you. In EasyRPG, the direction it faces switches every frame. You can't tell with the weird face thing but if you change the event graphic, you can. **since 0.6**

    ![switch](https://cloud.githubusercontent.com/assets/11024420/23575812/49884484-0059-11e7-98f4-b484f999f0c9.gif)

    Also, if you hold right in this position, the event will constantly face right. In RPG_RT, holding right doesn't change anything (it stays facing left).

- [x] When you are in the same corner the character is red the whole time, but not in EasyRPG Player where it is always red-pause-red-pause. **patch available for 0.6.1**

That's what I noticed.

**Comment by scurest** [comment]
(btw I accidentally switched the words "right" and "left" in (1) and (2) in the second bullet. In RPG_RT it continues to the right, and in EasyRPG it continues to the left. The picture is correct.)

**Comment by fmatthew5876** [comment]
The last bullet point here seems to already be fixed in master.

**Comment by Ghabry** [comment]
This works but I noticed something else:
When you block the left-right-moving thing in that corner you will have permanent damage and red flash on your actor but not in the Player.

But @fmatthew5876 branch fixes this :+1: 

So patch available for this in 0.6.1

**Comment by fmatthew5876** [comment]
An interesting behavior I discovered related to this.

For events with horizontal and vertical movement.

If `trigger=collision` and the event collides with the player, it'll keep trying to step towards the player, trigger its event code every time. If the trigger type is anything else and it collides with the player, it'll just turn around and go back the other direction.

**Comment by carstene1ns** [comment]
__#just`MakeWay`things__: #884, #1082

**Comment by Ghabry** [comment]
Well the last point that I added works now -> closing
