### ISSUE TITLE
Support "SE cancelling" when (OFF) is played

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1120]
Or when (Brak), (Aus) or (Kein Sound) are played ¯\\\_(ツ)_/¯

---

#### Attach files (as a .zip archive or link them)
[issue1120.zip](https://github.com/EasyRPG/Player/files/821988/issue1120.zip)

#### Describe the issue in detail and how to reproduce it:
Talk with the people in front of you and follow the instructions.

Left guy: SE, SE, SE (OFF)
Right guy: SE, SE, Wait 0.2, SE (OFF)

**Comment by carstene1ns** [comment]
While we are at it, we should stop long-running sound effects when pressing `F12` or returning to the game browser.

**Comment by CherryDT** [comment]
Does EasyRPG already emulate the behavior that playing a sound 4x at zero volume stops all other instances of the same sound? (Which is due to the fact that only 4 instances of a sound can play.)

**Comment by Ghabry** [comment]
No, that's totally new to me, thanks. Strange feature. Why does RPG_RT tracks how often one specific SE is played?
Or is the SE-channel limit of RPG_RT four and this will result in silence in general independend of which SE you play four times at 0 volume?

**Comment by CherryDT** [comment]
I don't think it was intended as a feature ;) 
I believe it was per sound and not in total, otherwise people would have just used (OFF). I don't know off the top of my head why it was like that, though, but I think sounds are loaded into memory and get 4 channels associated with them, and things like system sounds stay forever in memory while others are unloaded after a while. Totally not sure about that right now, though.

**Comment by Ghabry** [comment]
And I thought I slowly have learned about most obscure behaviours of RPG_RT. This is absurd :D.

Will test this and create an issue, thanks!

**Comment by CherryDT** [comment]
Just checked my notes again: yes it's as I said - each sounds gets in instance of the wave file player object and each of them can hold data for up to 4 instances of this sound. By the way, in total there can be only 16 _different_ sounds loaded, and some of those slots are held by the never-released system sounds (I think cursor, decision, cancel, buzzer).

**Comment by CherryDT** [comment]
I don't think anybody relies on the 16 sounds limit though, but I do know that some people use the trick with 4x zero volume to stop background sounds like rain etc

**Comment by Ghabry** [comment]
Other SE things: Yume Nikki shows a loading screen at the beginning and plays ca. 50 SEs with volume 0. But I guess this has no real purpose except maybe moving the files to the disc-cache of Windows.

**Comment by CherryDT** [comment]
I guess they do it to cache the sounds but didn't know about the 16 sounds limitation...

**Comment by carstene1ns** [comment]
btw. one of the latest bug report mails we got, has `Debug: Cannot find: Sound/(No Sound) (!)`
So we need to extend this check even more... 😁

**Comment by rohkea** [comment]
Maybe just check that first char is ``(``, the last char is ``)``, and the file doesn’t exist? I doubt many people used brackets for legit filenames.
