### ISSUE TITLE
[Android] Fast Forward Button not rendered

### ISSUE THREAD

**Issue by BlisterB** [EasyRPG/Player#1124]
Hi everyone :).

The Fast Forward option works like a charmed, really cool!

But the button is not rendered on my Device (Sony Xperia Z3 Compact, API 23), it just displays a rectangle.

@Ghabry if you are bored about this I can fix that with an hard coded shape, I can also add the option to customize the FF button : "press and release" and "press 1 time to active, press 1 time to desactivate".
As you wish, we can also split the two subject :).

**Comment by Ghabry** [comment]
Meh I added a fallback to show ">" for Api <= 4.0 and hoped this is enough.
Fix it as you wish, I won't work on the Android part anymore.

While working on the settings: Could you also add a slider to adjust speedup level from 2 to 10? I already provided a variable in player.h that can be toggled through JNI to propagate this option to the Player.

**Comment by BlisterB** [comment]
Ah nice :), I'll try to do that this week end.

**Comment by Ghabry** [comment]
Pokes @BlisterB 

The first user asked about a press and release feature ;)

**Comment by BlisterB** [comment]
Yees, it's on my to do list é__è.
I spent some time trying to display the famous ">>" character. I think the problem is that the font used depends on the system and/or version. A fix may be to use a predefined font, i'll work on the subject as soon as I have some time.

**Comment by Ghabry** [comment]
Maybe it makes sense to use a built-in font by google that hopefully exists on any device.
Based on some screenshots custom fonts sometimes break the metrics anyway (letters overlapping with the circles e.g.)
