### ISSUE TITLE
Pictures: Update Order and Positions

### ISSUE THREAD

**Issue by scurest** [EasyRPG/Player#1125]
1. In RPG_RT, pictures are updated before events.

    You can check this with an event like

        <> Show Picture: ..., Zoom: 100%
        <> Move Picture: ..., Zoom: 75%, Wait 0.0s

    For one frame (the same frame these commands run) the picture will be shown at 100% zoom. (You can also check this in Ghabry's event tracer by printing out the picture's member variables during event processing and checking that they have already updated for the frame.)

    In EasyRPG, events are updated before pictures. This can be solved by transposing [these lines](https://github.com/EasyRPG/Player/blob/afc98cc7da239eea2c3f72de2ceb96bbfa132e95/src/scene_map.cpp#L139-L140). I'm reluctant to do it though because

    1. It also places all other screen effects' updates before the events', and I don't know if that's right. Could be solved pretty easily by breaking picture updating specifically out of updating `Game_Screen`.
    2. Part of picture updating also looks at the current map position and uses it to move pictures that are "fixed to the map". So if the screen moves during event processing, currently since the pictures are updated later, they will observe the change, but if they happen before, they won't. I can't seem to actually trigger any graphical bug with this though (maybe the screen never moves far enough in one frame?), so I don't know if this is just paranoia on my part >_>

2. For pictures that are fixed to the map on a looping map, in EasyRPG they currently jump when you cross the map edges. Compare [this issue with battle animations](https://github.com/EasyRPG/Player/pull/574#issuecomment-138691723).  If you think of a wrapping map as a plane consisting of repeating copies of the map, the picture should be fixed to the _overall plane_. This means for example that if you show a picture and cross the right edge of the map, you won't see the picture on this "new copy" of the map. Once you cross back over the left-edge, you'll see it again.

    The underlying reason for the bug (and the battle animation one) is that we don't track a "global position" in this plane, only a "local" position within the map itself.

-----

Here's an untested idea to fix both 1.ii and 2: split updating into two phases.

1. The first phase updates pictures' zoom/transparency/effects etc. but not their position.
2. Events are updated. We keep track of how much the map scrolls in each direction.
3. The second phase looks at the scroll amounts and use them to update pictures/parallax/battle animation positions.

This would also let us get rid of the `old_map_{x,y}` fields in our `Game_Picture` class that don't have an analogue in `RPG::SavePicture`.

Of course the best idea is to figure out whatever RPG_RT does and do that.

**Comment by fmatthew5876** [comment]
At least the picture update time part was #1662 and is fixed in master.

There's other stuff here that needs to be verified.
