### ISSUE TITLE
Error: Couldn't create 288x256 image [3DS]

### ISSUE THREAD

**Issue by zell180** [EasyRPG/Player#1135]
#### Name of the game: 
SaintGoal
http://www.mediafire.com/file/y62u8vedckc9kmv/SaintGoal.zip

#### Player platform: 
New 3DS XL

#### Attach files
![screen](https://cloud.githubusercontent.com/assets/6542956/24431418/0f2753bc-141c-11e7-8e4b-93f42bc0e8ae.jpg)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/877323/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
After click on New Game and than on Gioca Seiya Soccer the issue appear

**Comment by zell180** [comment]
After fix sRGB profile of "MAP Altri Orfanotrofio.png" this is the new log file 
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/877370/easyrpg_log.txt)

**Comment by Ghabry** [comment]
@zell180 
Could you please retest it with this development version of EasyRPG here:
https://ci.easyrpg.org/view/Pull%20Requests/job/player-3ds-pr/22/

Note that we only provide 3dsx files for dev versions so you need the homebrew channel to launch it. When launching the 3dsx, the homebrew channel asks you to pick an application for launching (if you don't have the latest youtube-chan installed). You have to pick one that has enough executable memory, most games should work. You see that you picked a bad one if it instant-crashes on startup ;)

**Comment by zell180** [comment]
Please can you tell me correct folder path of 3dsx and rpgmaker game?

**Comment by Ghabry** [comment]
The content of the zip belongs in sd-card:/3ds/   (so result is /3ds/easyrpg-player. The games belong in the same folder /3ds/easyrpg-player/ANYGAME

**Comment by carstene1ns** [comment]
![3dsshot](https://p.f4ke.de/vXHjrROR1S.png)

**Comment by zell180** [comment]
ok thansk. my folders are exactly like you say. when i start easyrpg from homebrew launcher stuck on red screen. Both with youtube player installed or if i select pokemon sun or super smash bros like application to launch

**Comment by Ghabry** [comment]
Can confirm that the build I linked is indeed broken... Sorry. Will ping you when it is working again :/

**Comment by zell180** [comment]
ok good news! with 0.5.0 3dsx the game work fine. with 0.5.0 cia appear the error in the first post

**Comment by Ghabry** [comment]
After further discussion (made some tests with him through twitter pm) this is as expected a memory issue beause liblcf and other parts of Player waste too much RAM.
Closing as Dup of #1097

**Comment by carstene1ns** [comment]
Imo this is not really a duplicate, as the game loads fine here instead of insta-crashing.
