### ISSUE TITLE
[3DS] Handle missing DSP firmware graceful instead of crashing

### ISSUE THREAD

**Issue by Spazturtle** [EasyRPG/Player#1142]
Build #1​21 on 19-Feb-2017 is the last build I can get working, all newer builds crash on startup or cause the system to freeze.

Console: New 3DS EUR.

The log shows this for every version that crashes:
```
[2017-04-10 21:11:16] Error: Couldn't initialize audio.
Error code: 0xD880A7FA
```

[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/911547/easyrpg_log.txt)

**Comment by Ghabry** [comment]
Strange. The last build I tested was from 10 days ago and worked.

No idea what that error code is, I have to ask in \#3dsdev channel first

**Comment by Ghabry** [comment]
Do you use the cia?
Try dumping the dsp firmware with
https://github.com/Cruel/DspDump/releases/tag/1.0
And run easyrpg again.

**Comment by Spazturtle** [comment]
Dumping the DSP Firmware fixed it, thanks.

Might be worth mentioning on the website that the 3DS CIA version requires the DSP firmware to be dumped.

**Comment by Ghabry** [comment]
Agreed. Missing DSP firmware must be handled more graceful. Warning instead of Error e.g.

I will reword the issue.
