### ISSUE TITLE
7th Stand User: Doesn’t load on 3DS

### ISSUE THREAD

**Issue by rohkea** [EasyRPG/Player#1144]
The 7th Stand User doesn’t work on 3DS, the message ‘Loading...’ appears, and then the user is returned to the 3DS home screen.

> It's like this  
> I'm on the main screen, where all the games I have in the directory are.  
> I double checked that the files are in the correct place.
> I then attempted to run 7th Stand User, labeled 7thjojo  
> The message "Loading..." comes up, and I wait.  
> After about 13 seconds, I'm booted back to the 3ds home screen.  
> I open it back up, and try the same with Gray Garden, which runs normally after I select it.  
> [what version of EasyRPG do you use? 0.5.1?]  
> Yes, it is EasyRPG version: it is 0.5.1, ported by Rinnegamante.

The game can be downloaded here: <http://www.mediafire.com/download/b3olols92cfxbkc/7thStandUser.zip> (description page: <http://7thjojo.tumblr.com/post/98202338885/after-several-months-in-the-making-the-7th-stand>)

This issue only happens on 3DS, I’ve tried running the game on Windows and it runs fine. If more feedback is needed, the reporter has provided their email (check IRC logs for 13th of April).

**Comment by carstene1ns** [comment]
I can confirm the crash. Unfortunately the crash dump is not really useful here:
```
Processor: ARM11 (core 0)
Exception type: prefetch abort
Current process:  EasyRPG (0004000000ea5100)

Register dump:

r0             006586f0            r1             00000000            
r2             0067a38e            r3             00001ccc            
r4             0065a6a0            r5             0067a390            
r6             0067a38e            r7             0067a410            
r8             0067a390            r9             00000001            
r10            00000000            r11            00000000            
r12            00000000            sp             08075de0            
lr             002f0c74            pc             002f0530            

cpsr           20000010            dfsr           00000805            
ifsr           00000003            far            08075db8            
fpexc          40000700            fpinst         eebc0bc0            
fpinst2        eebc0bc0            

Code dump:

  2f0504:	e593c008 	ldr	r12, [r3, #8]
  2f0508:	e593100c 	ldr	r1, [r3, #12]
  2f050c:	e2833010 	add	r3, r3, #16
  2f0510:	e1530000 	cmp	r3, r0
  2f0514:	e5824000 	str	r4, [r2]
  2f0518:	e582e004 	str	lr, [r2, #4]
  2f051c:	e582c008 	str	r12, [r2, #8]
  2f0520:	e582100c 	str	r1, [r2, #12]
  2f0524:	e2822010 	add	r2, r2, #16
  2f0528:	1afffff3 	bne	0x2f04fc
  2f052c:	e38bb40e 	orr	r11, r11, #234881024	; 0xe000000
  2f0530:	eaffff01 	b	0x2f013c


Stack dump:


```

**Comment by carstene1ns** [comment]
Closing this in favor of #1097, as it has the same crash dump.
