### ISSUE TITLE
Endless loop when the first hero is named is \N[1]

### ISSUE THREAD

**Issue by rohkea** [EasyRPG/Player#1145]
In RPG Maker (tested on RM2k v.1.61), when ``\N[x]`` or ``\V[x]`` appears in a character name, it’s displayed as ``[x]`` in the message.

In EasyRPG, a substitution is performed recursively. If the first character is named ``\N[1]``, an attempt to print their name would result in an endless loop.

Judging by how text lines are broken in winning messages (see my comment on https://github.com/EasyRPG/Player/issues/588#issuecomment-294382740), I think RPG Maker does the code replacement in two passes: first, ``\N[x]`` and ``\V[x]`` are replaced, and after this, the formatting codes are applied.

**Comment by rohkea** [comment]
Just checked. If the hero name contains \N[1] or \V[1], it is displayed as [1]. But this [1] is different from normal [1], because it can’t be used with other message commands.

For example.

* Hero #1's name: \N[1]
* Message: \C\N[1]Hello
* Result in RPG_RT: [1]Hello
* Result in EasyRPG: endless loop

This is different from a case with a hero named [1]:

* Hero #1's name: [1]
* Message: \C\N[1]Hello
* Result in RPG_RT: 'Hello' in colour #1
* Result in EasyRPG: same as in RPG_RT

**Comment by Ghabry** [comment]
I think recursive replacement is actually a nice feature but we should add some sanity check to prevent endless substitution.

**Comment by rohkea** [comment]
I was wrong about the ``\N[x]`` being performed before other codes. Further experiments with word-wrapping seem to suggest that ``\N[x]`` codes are not replaced before word-wrapping: at least I was able to have a "word-wrapped" lines that don’t fit into the line, if I use long character names:

![hero-name-cropped](https://cloud.githubusercontent.com/assets/3201243/26016826/478ac5ec-376f-11e7-9767-89c0ad3b41bd.png)

**Comment by CherryDT** [comment]
@rohkea Did you reinvestigate your own investigation because you forgot about it? ;) happens to me all the time, at least. Because you already noticed this bug here: https://github.com/EasyRPG/Player/issues/588#issuecomment-294382740

It's a bug in RM which I'll hopefully be able to fix some time soon.

**Comment by Ghabry** [comment]
Wow. Thanks for that very detailed writeup. And EASYRPG has to add \N [0], too :D
