### ISSUE TITLE
Works but not loading

### ISSUE THREAD

**Issue by daklin** [EasyRPG/Player#1149]
Name of the game: Yume Nikki

Player platform: Android

Attach files (as a .zip archive or link them)
[Save04.lsd.zip](https://github.com/EasyRPG/Player/files/949029/Save04.lsd.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/949027/easyrpg_log.txt)

Describe the issue in detail and how to reproduce it:
So, I started a new game and it was working fine. Then I saved the game and exited. After a while, I tried loading the game. It took more than 1 min to load but still worked. Then I played for another 30 min and saved. Now it doesn't load anymore. The background music plays fine and I can start a new game too. It just stucks in the "Working...please wait..." screen.

**Comment by Ghabry** [comment]
Hello, we are aware of this issue and a fix is already on the way soon! (unfortunately the fix won't fix your savegame, it will only prevent new savegames from corrupting)
