### ISSUE TITLE
En el juego time traveler  no me permite salir del Inframundo con Kazuki llevo días intentando pero el problema no se soluciona ¿pueden hacer algo para solucionarlo? Gracias

### ISSUE THREAD

**Issue by paulalejimelatorre** [EasyRPG/Player#1150]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by Ghabry** [comment]
Hola. Por favor subes una guarda partida (SaveXX.lsd en la carpeta de juego) cuando es cerca de problema.

**Comment by fdelapena** [comment]
Hola @paulalejimelatorre:

Parece que es un bug del propio juego, no de EasyRPG Player. Lo mencionan en los comentarios del blog de IndieHorrorRPG:
http://indiehorrorrpg.blogspot.com/2015/12/time-traveler.html#comment-3200949832

Desconozco si en la versión más reciente lo ha arreglado, tal vez necesites cargar una partida más antigua en la versión mas reciente para intentarlo. Si todavía no funciona, lo mejor sería que contactaras con Comodorette (la autora) para ver si ya lo ha solucionado. Creo que tiene cuenta en tumblr, en http://rimururu.tumblr.com/

Cierro el ticket porque no parece fallo del programa. Saludos.
