### ISSUE TITLE
Un bug en time traveler

### ISSUE THREAD

**Issue by paulalejimelatorre** [EasyRPG/Player#1151]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Attach files:file:///storage/emulated/0/easyrpg/games/Time%20Traveler/Actualizacion_Febrero2017/Save04.lsd
 - The `easyrpg_log.txt` log file:file:///storage/emulated/0/easyrpg/games/Time%20Traveler/Actualizacion_Febrero2017/easyrpg_log.txt

#### Describe the issue in detail and how to reproduce it:
Hola, mi problema es que no se me permite salir del Inframundo con Kazuki después de haber realizado la misión, llevo días intentando pero no funciona ¿pueden hacer algo para solucionarlo? 

Gracias.

**Comment by fdelapena** [comment]
Hola @paulalejimelatorre, gracias por el informe. Parece que no ha funcionado adjuntar los archivos. Adjuntar ficheros desde un dispositivo Android es algo más complicado. Si entras desde un teléfono a esta página, abajo hay un enlace que pone Desktop version. Si tocas recargará y al bajar donde aparece donde escribir hay un pequeño enlace de texto azul donde aparece el texto "selecting them", y desde ahí tal vez puedas acceder a los ficheros. El problema es que este sitio web no permite subir todo tipo de formatos, el Save04.lsd habría que comprimirlo en ZIP con alguna herramienta como ES File Explorer para poderlo subir aquí. La forma fácil sería intentar adjuntarlo en alguna página de subir ficheros como por ejemplo http://sendspace.com y pasarnos el enlace. El easyrpg_log.txt sí que se puede subir aquí directamente, pero si lo quieres subir a sendspace también y pasar el enlace no hay problema.

Veo que el juego es bastante largo, según la guía que hay en el wiki del juego a Kazuki se le puede controlar en el capítulo 5 y el fichero de la partida guardada (Save04.lsd) y el archivo easyrpg_log.txt tras jugar esta zona ayudarían enormemente a poder localizarlo y arreglarlo antes.

Game download (300 MB): http://www.mediafire.com/file/ilz2kq87cxx85ga/%5BTimeTravelerV4%5D.rar

Problem: Unable to leave underworld with Kazuki after doing the mission.

**Comment by Ghabry** [comment]
Cerrado porque es un duplicado de #1150
