### ISSUE TITLE
Un bug en time traveler

### ISSUE THREAD

**Issue by paulalejimelatorre** [EasyRPG/Player#1155]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by carstene1ns** [comment]
Please stop opening additional issues and use the comment interface on your already opened ones to respond.
