### ISSUE TITLE
Everlong - Audio Issue - Music/Sounds Running At 2x Speed

### ISSUE THREAD

**Issue by dankarcana** [EasyRPG/Player#1157]
#### Name of the game:
Everlong (by Doug Carpenter)

#### Player platform:
Android (Nexus 6p)

#### Attach files (as a .zip archive or link them)

[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/972018/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:

Music/Sounds in-game are running at 2x speed. Game runs perfectly, no issues graphically, but audio makes game unplayable (unless playing with audio turned off).

Issue can be be reproduced upon every startup.

I've tested the game on PSVita (Henkaku 3.60), and audio is running at the right speed (in exchange for audio quality and weird pitch).

**Comment by carstene1ns** [comment]
Just some notes about this game:
- Uses DynRPG
- Has mostly MIDI music
- From the Readme: Editing requires RPG Maker 2009 with delimited GUI fields and the David or Goliath Patch by Aten.

MIDI music can sound slightly different under PSVita and Android as we do not use the same library (WildMIDI vs. Timidity), but double speed is clearly a bug. We need to find out if this is our fault (maybe the resampler) or timidity's fault.

About the patches used by this game: We do not support them. This could make the game behave abnormal or be not completable, getting stuck, etc.

**Comment by Ghabry** [comment]
Have to test this on Android, sounds fine on linux.

This game would profit a bit from DynText support:

```
Warning: Unsupported DynRPG function: quicksave
Warning: Unsupported DynRPG function: is_minimap
Warning: Unsupported DynRPG function: write_text
Warning: Unsupported DynRPG function: write_text
Warning: Unsupported DynRPG function: write_text
Warning: Unsupported DynRPG function: write_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: remove_all
Warning: Unsupported DynRPG function: is_minimap
Warning: Unsupported DynRPG function: write_text
Warning: Unsupported DynRPG function: write_text
Warning: Unsupported DynRPG function: write_text
Warning: Unsupported DynRPG function: write_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: append_text
Warning: Unsupported DynRPG function: remove_all
Warning: Unsupported DynRPG function: is_minimap
Warning: Unsupported DynRPG function: process_cmd
Warning: Unsupported DynRPG function: autosave
Debug: Starting battle 1 (Tyr-Anox Guard): algos=(RPG_RT/RPG_RT)
Debug: Actor 3: Removing item 176 (of type 1) from equipment slot 2 (needs type 2)

Process finished with exit code 0
```

**Comment by Ghabry** [comment]
The audio sounds fine to me, likely fixed by the recent MIDI refactor. CLosing this and moving the DynRPG_stuff to our DynRPG issue (#1091)
