### ISSUE TITLE
Opus audio support

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1159]
The Opus codec is currently the state of the art on audio compression, royalty free, and sounds really well on low bitrates, such 48 kbps. This makes this codec perfect for game audio, both for sound effects and music. There are games with large file sizes due to the amount of music and effects bundled with it, and an efficient codec looks a good way to make them significantly smaller. It also has a fixed point implementation.

**Comment by fdelapena** [comment]
It seems there is a bug after trying to restart the song and does not replay it:
```
Debug: Audio Decoder: Recursion depth exceeded. Probably stream error.
```

**Comment by carstene1ns** [comment]
Well, you are only providing a `read` replacement with your callbacks. No idea how the library works internally, but I guess it cannot seek backwards this way.

**Comment by fdelapena** [comment]
Right, it tries ten times and fails for all of them with `OP_ENOSEEK` (-138).
