### ISSUE TITLE
Wii: digital audio files play at varying speeds (SDL 1.2)

### ISSUE THREAD

**Issue by Magil** [EasyRPG/Player#116]
I have not been able to determine what provokes this. They either play very slowly, or they play too fast (more often the former than the latter). The only thing that these files have in common is that they are sound rips of my own creation using Audacity (pretty sure this last bit of information is trivial). I have not tested using files created through different means.

I'm using the Wii version of EasyRPG Player, which is currently listed as using the nightly version.

**Comment by Ghabry** [comment]
This is semi-fixed in the audio-branch for Midi and MP3 :)

**Comment by Ghabry** [comment]
This is fixed upstream. Just needs a minor Wii update :+1:

**Comment by carstene1ns** [comment]
> This is fixed upstream.

No, this is fixed downstream.

**Comment by Ghabry** [comment]
Imo this can be fixed after merging #919 and the sound part will be solved whtn #895 is closed
