### ISSUE TITLE
Eternal Legends: panorama movement is wrong

### ISSUE THREAD

**Issue by rohkea** [EasyRPG/Player#1160]
The panorma in Eternal Legends’s Peak of Prophecy is wrong in the current master branch and in the 0.5.1 release (but it was correct in 0.5.0):

![screenshot_30](https://cloud.githubusercontent.com/assets/3201243/25810322/77bb0a10-3418-11e7-9890-eb1bc1fbd3e8.png)

Here’s a test project with just this map: [TestPanoramaScroll.tar.gz](https://github.com/EasyRPG/Player/files/983896/TestPanoramaScroll.tar.gz) (~500 kB).

If someone needs to test it in the real game, here’s the save game: 
[Save02.lsd.gz](https://github.com/EasyRPG/Player/files/983900/Save02.lsd.gz). The game itself (~25 MB) can be downloaded here: <https://www.file-upload.net/download-7313515/EL-V2.27a.exe.html> or here <http://rmarchiv.de/games/595> (requires registration).

The problem did not exist in the Player 0.5.0.

**Comment by scurest** [comment]
Almost certainly my fault. I'll check this later.
