### ISSUE TITLE
Default project-path broken on OS X

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#1175]
Apparently, Player 0.5.1 fails to correctly detect the project path in OS X unless it's explicitly set.
Error message when running easyrpg-player in a game directory:

"Error:  is not a valid path"

Things work fine with the --project-path . or --project-path $PWD parameter set. Tested with a couple of games, so it doesn't seem to be game specific.

**Comment by carstene1ns** [comment]
untested patch:
```patch
diff --git a/src/main_data.cpp b/src/main_data.cpp
index 259a32ba..58f4b300 100644
--- a/src/main_data.cpp
+++ b/src/main_data.cpp
@@ -157,6 +157,8 @@ void Main_Data::Init() {
                                project_path = data_dir;
 
                                free(data_dir);
+                       } else {
+                               project_path = ".";
                        }
 #  else
                        project_path = ".";
```

**Comment by Ghabry** [comment]
The Ara Fell people and BlisterB really properly checked the MacOS build >.>
