### ISSUE TITLE
Schmetterlinkskuh-Flugsimulator-Simulation 2k: Collision system doesn't work in Level 2

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1176]
Name: Schmetterlinkskuh-Flugsimulator-Simulation 2k

Download: http://rmarchiv.de/games/704

Savegame:
[Save01.zip](https://github.com/EasyRPG/Player/files/1017440/Save01.zip)

After loading the save level 2 starts. (Epilepsy warning!). You can't collide with the scenery and just pass through making the game unwinnable because the "End game" tiles don't work either.

![screenshot_20170522_014051](https://cloud.githubusercontent.com/assets/1331889/26288316/b8fc32b6-3e8f-11e7-96a9-7a895ba2be42.png)

**Comment by Ghabry** [comment]
The problem is that the map is looping so GetTerrainID actually *wraps* (so when the map is 20x20 and you request "20" then it wraps and takes the 1st one...). Also works in negative direction.

Somehow doesn't affect other event commands. E.g. GetEventID doesn't wrap.

Thx to scurest for the idea.

CC @CherryDT . More obscure Maker behaviour.

**Comment by Ghabry** [comment]
```diff
diff --git a/src/game_map.cpp b/src/game_map.cpp
index 2551b972..b4a086ca 100644
--- a/src/game_map.cpp
+++ b/src/game_map.cpp
@@ -665,7 +665,10 @@ bool Game_Map::IsCounter(int x, int y) {
 	return !!(passages_up[index] & Passable::Counter);
 }
 
-int Game_Map::GetTerrainTag(int const x, int const y) {
+int Game_Map::GetTerrainTag(int const xpos, int const ypos) {
+	int x = Game_Map::RoundX(xpos);
+	int y = Game_Map::RoundY(ypos);
+
 	if (!Game_Map::IsValid(x, y)) return 9;
 
 	unsigned const chipID = map->lower_layer[x + y * GetWidth()];
```

**Comment by scurest** [comment]
To get this to match RPG_RT in all cases, we'd also have to change `RoundX` (and `RoundY`) to handle all values. We only handle negative numbers as far as `-width`, because once you go below that, the LHS in `(x + GetWidth()) % GetWidth()` becomes negative. We could replace that with `mod(x, GetWidth())` where

    // Non-negative modulus
    int mod(int x, int m) {
        return (x < 0) ? (m + x % m) : (x % m);
    }

or something.
