### ISSUE TITLE
Memory usage. Vampires Dawn: creating Image Error

### ISSUE THREAD

**Issue by Klauserus** [EasyRPG/Player#1177]
#### SaveFile: 
sorry, i belive cant save the game before, but it takes 4 minutes to the point of error

#### Describe the issue in detail and how to reproduce it:

When i fly first time to Asgars castle/palace, the screen get red and a error message come out :

Couldn´t create 288x256 Image. EasyRPG Player will close now.

Thank you and greetings

**Comment by carstene1ns** [comment]
This is likely a memory related problem, so we cannot really do much at this point.

**Comment by Klauserus** [comment]
ok. You mean it is a RAM problem? Oh man. This is really a Problem. We can´t upgrade the RAM of a Wii :D 
Are there any solution approaches? This makes some games unplayable
thx

**Comment by carstene1ns** [comment]
Well, we currently do not really try to have a small memory footprint. Further explanation here:
https://community.easyrpg.org/t/wii-build-test-reports/197/69 (other game, same issue).

**Comment by Klauserus** [comment]
Can one say then that the Wii version has reached its limits and there will be no 100% game compatibility in the future? ...i will donate for more development Power :)

**Comment by Ghabry** [comment]
The irony is somehow that some of these cachings were invented to make the experience on slow systems (Wii & co.) more smooth but now they break it :/.

We have some ideas to reduce the memory usage they are just not high priority.

**Comment by Ghabry** [comment]
Using this as a meta issue for memory footprint stuff.
One place where we waste some memory is that we allocate all Sprites on the map upon map load even if they are off-screen. This uses significant amounts of memory in some games. The disadvantage of loading a sprite on first appearance are micro stutters (especially bad on the 3DS I guess...) but better than OOM I guess?

Comparison for The Looking Glass (discussed here): https://community.easyrpg.org/t/wii-build-test-reports/197/69?u=ghabry

Before: 
![worse_mem](https://user-images.githubusercontent.com/1331889/27153699-c48da54e-5152-11e7-9546-bdc695e8d675.png)

After:
![better_mem](https://user-images.githubusercontent.com/1331889/27153706-c98a5326-5152-11e7-8781-afda2797706c.png)

**Comment by Ghabry** [comment]
More potential memory saving: Cache::Tile could return a Rect to the tilemap instead of a new Tile. Saves ~1 Kbyte per tile (not really worth it).

Autotiles are already created on demand as far as I can see, no memory savings possible.

Only create the ChipSet Tone bitmap (and other Tone bitmaps) when actually a tone change happens. This saves 500 kbyte per map when no Tone change happens and ~300 kbyte or more (depending on panorama size) when no Tone change happens.

Maybe it is possible to get rid of the "black_screen" used in Graphics for transitions (saves 300 kbyte permanently).

So, not much potential for less memory usage. At most ~2 MB when no tone change happens.

**Comment by Ghabry** [comment]
actually the problem in "The Looking Glass" is the same as in Yume2kki. Just not as noticable because it doesn't eat 3 GB xD

**Comment by Ghabry** [comment]
quickly fast forwarded until the first save in VD1:
New version peaks at ~32 MB, old version at ~51 MB (Without SE in both because my VM has broken audio).

**Comment by Klauserus** [comment]
Does it work now? I could not test myself yet

**Comment by Ghabry** [comment]
@Klauserus

Based on my analysis it should work now but If you find some time for testing would be nice if you could report back :)

**Comment by Ghabry** [comment]
Postboning this one to 0.6.2, should be fixed but there was still nobody motivated to check it.

**Comment by Ghabry** [comment]
Not Vampires Dawn, but we already got two confirmations for other games that it helped, last was here: https://community.easyrpg.org/t/wii-0-6-0-crash-yuque-couldnt-create-288x256-image/704/3

Therefore I consider this resolved. Please reopen @Klauserus if it still doesn't work for you with 0.6.1

**Comment by Klauserus** [comment]
Sorry. I am very busy at this time. my wii isn´t connected with my tv at this time, but i can test it these days.is it still relevant? if so, i will try it out these days. Just the current nightly?

**Comment by Ghabry** [comment]
would be nice if you could test it.
Yepp just the latest nightly.

**Comment by Klauserus** [comment]
Now i have i test it. And it works. I can fly to the castle without an error in vampires dawn. 
The sound is also better i think and the framerate are very stable at 60 fps. When i enter a house or it flashes by rain, than little framedrops, but not bad.

But one only think i must test with an old version of rpg player. I think the picture in vampires dawn a little flicker like the air over a street in sommer. but I can also fooled since I've played no more wii over a year and i am spoiled by the switch

sorry for my bad english
