### ISSUE TITLE
Android: Menu background/shadow does not cover whole screen

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1184]
happening under Android 7 (Samsung tablet):
[![horiz](https://picload.org/thumbnail/riariria/screenshot_20170520-151126.jpg)](https://picload.org/image/riariria/screenshot_20170520-151126.png) [![vert](https://picload.org/thumbnail/riariril/screenshot_20170520-151334.jpg)](https://picload.org/image/riariril/screenshot_20170520-151334.png)
(click on the images to see them in native resolution)

**Comment by Ghabry** [comment]
The effect looks even more funny on my 4.0.3 Smartphone: Nothing of the SDL overlay gets shadow except the parts where overlay buttons are :D

**Comment by BlisterB** [comment]
Hmm @carstene1ns do you still have this issue?

**Comment by Ghabry** [comment]
For me this is fixed.
Also: Thanks for making the drawer closable by touching outside of it!!! Soooo useful.

**Comment by Ghabry** [comment]
![Screenshot_2022-03-30-13-44-13-427_org easyrpg player](https://user-images.githubusercontent.com/1331889/160827145-3d835e54-1b06-425f-b9f8-226ab66bbfce.jpg)

Unrelated I guess: The area where the system buttons appear is also shadowed

**Comment by carstene1ns** [comment]
I guess this is fixed.
