### ISSUE TITLE
Android: game screen sometimes hops into offscreen area after turning device or toggling app

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1185]
happening on Android 7 (Samsung tablet):
[![offscreen](https://picload.org/thumbnail/riaririi/screenshot_20170521-192612.jpg)](https://picload.org/image/riaririi/screenshot_20170521-192612.png)
(click on the screnshot to display in native resolution)

The game itself is playable and display can be fixed by turning the screen again.

**Comment by Ghabry** [comment]
This was fixed by SDL 2.0.5 (https://bugzilla.libsdl.org/show_bug.cgi?id=2808), can't reproduce the problem anymore.

**Comment by carstene1ns** [comment]
Great, let's wait for an updated toolchain then 🏭
