### ISSUE TITLE
Problem when saving, Yume Nikki

### ISSUE THREAD

**Issue by gabrieljim** [EasyRPG/Player#1190]
#### Name of the game:
Yume Nikki
#### Player platform:
Lubuntu 16.04

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1030353/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
Hey, your program is awesome so far, everything it's really fluid, however, everytime I tried to save, it doesn't, even though you can see in the console that is writing to Save01.lsd.
I thought maybe it had a problem when trying to actually write to the file, so I ran the program with sudo and this time it did save and I did could see the save in the "Diary" part of the game.
But, leaving the current game and then trying to load the saved file from the Diary, the game just gets stuck on "Working", and it doesn't ever load.
Any help, please?

**Comment by Ghabry** [comment]
Hi unfortunately the 0.5.1 release has a bug which corrupts some savegames.

This will be fixed in 0.5.2 which comes in a few weeks. Your options are: Compile latest version of Player and liblcf or use the "continious build" from the bottom of our dl page https://easyrpg.org/player/downloads/

The savegame will.still not work - start a new game... sorry

**Comment by gabrieljim** [comment]
That's okay, thank you for answering, I'll compile it. 
However, I want to keep up to date with the software, should I delete the compiled software after you release 0.5.2 and then install it from apt?

**Comment by Ghabry** [comment]
We recommend using the latest official version. Only use the development version when you encounter a game breaking bug which was fixed in the meanwhile,
We try to make new releases every 3-6 months. 0.5.2 is scheduled for mid of june before the summer break ^^

**Comment by gabrieljim** [comment]
Awesome, thanks!

**Comment by gabrieljim** [comment]
Sorry, but, after compiling eveything I get the same saving errors.
I guess i should just wait for the official update?

**Comment by Ghabry** [comment]
You compiled both liblcf and Player  and used the git HEAD (not tag 0.5.1).? Concerning liblcf make sure that it finds your liblcf and not the one installed through apt. (Because the bug is in liblcf)

**Comment by gabrieljim** [comment]
Yep, sorry about that, I removed the Pĺayer and compiled everything but forgot to remove the other libclf, everything works now, thank you!

**Comment by carstene1ns** [comment]
Glad you got it working, closing.
