### ISSUE TITLE
Embric of Wulfhammer's Castle: Heavy flickering in intro scene

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#1195]
The carriage scene of this game's intro has heavy flickering, which was not an issue when I last tried quite a while ago. I bisected this and it seems the following commit causes the issue:

https://github.com/EasyRPG/Player/commit/ce4787d716690ac62a7a5aada3ad0e5f15e3d0ab

Problem is showcased in the following video: https://my.mixtape.moe/ywaqhy.mp4 
This was tested in Linux. To reproduce, simply start a new game and go through the intro until the scene appears.

**Comment by carstene1ns** [comment]
For reference, here is the same scene in RPG_RT: https://my.mixtape.moe/mdifzq.webm

**Comment by Ghabry** [comment]
Somehow I moved pictures and battle animations below the screen which makes no sense. Fixed in my z-priority branch :D

**Comment by carstene1ns** [comment]
Another game that suffers from this is [AGORAPHOBIA](https://rpgmaker.net/games/5922/), apart from the already mentioned Deep8.
It is also fixed when reducing the screen z value.

**Comment by scurest** [comment]
Also fixes the opening for Standstill Girl 👍

**Comment by Ghabry** [comment]
Also fixes the cutscene in issue #1198 in Razas
