### ISSUE TITLE
Android: Create .nomedia file when adding a search folder, if it does not exist

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1196]
Currently it is only used for the first folder, possibly adding unwanted game files to the media gallery in other folders.

**Comment by Ghabry** [comment]
Though without super user permissions this can't be fully implemented because the game folders are not always writable.

**Comment by carstene1ns** [comment]
Addition: Check for valid games then too, and display a red cross (❌) if none are found (i.e. not extracted).

**Comment by Ghabry** [comment]
or maybe show a small red text (to be decided) below the path.

**Comment by fdelapena** [comment]
Based on email bug reports reporting false positives, this issue hits a significant amount of users, apparently they accidentally remove assets from gallery or media players.

**Comment by Ghabry** [comment]
Closing this as invalid due to SAF is not applicable anymore.

Only one EasyRPG folder exists that can be located anywhere.
