### ISSUE TITLE
Move "This Event" within Common Event

### ISSUE THREAD

**Issue by Deflaktor** [EasyRPG/Player#1201]
This is a feature request.

It always annoyed me that using Move "This Event" inside a Common Event Handler didnt have any use as it resulted in a crash. It would be much more useful if "This Event" would point to the Event which called the Common Event Handler (but only if the move event command is placed inside a Common Event of course). 

I know, RPG Maker 2k3 didnt have this special case handling, but I would love seeing it in EasyRPG.

**Comment by Ghabry** [comment]
We actually had this feature enabled but this broke some games that used "Erase Event" in a common event. (In RPG_RT "Erase Event" in a common event is a no-op instead of "Invalid Event -> Exit")

**Comment by Deflaktor** [comment]
Oh okay interesting. Can there be an special case handling for Move Command? Since Move Command definitely crashes, but Erase Event is silently ignored.

**Comment by Ghabry** [comment]
This is a feature of RPG Maker 2k3 1.12. Will be in when supporting this engine.
