### ISSUE TITLE
save_count 0x5B chunk not validated when a save is loaded

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1203]
Upon loading RPG_RT compares 0x5B of the current map with the save_count of the savegame and when it mismatches the events in the savegame are ignored and the map reloads instead.

In RPG Maker 2003 English Edition this was changed to 0x5A (or 0x5C, not 100% sure, needs a recheck).

**Comment by CherryDT** [comment]
It's unrelated, it basically just aborts the foreground event (not parallel events)

That save count thing though basically resets the events completely, as if you had left and reentered the map.

**Comment by CherryDT** [comment]
Actually it's two things:

The comparison of SavePartyLocation.map_save_count with Map.save_count resets the events on the map (their scripts and their map properties like their position, if I remember correctly)

The comparison of SavePartyLocation.database_save_count with System.save_count resets common events (not sure if it resets anything else)

(SaveSystem.save_count on the other hand is unrelated and just counts how often the user saved the game as far as I know)
