### ISSUE TITLE
Old Nintendo 3DS - no sound in games (daily updates)

### ISSUE THREAD

**Issue by Nightshadowxd** [EasyRPG/Player#1205]
Please fill in the following fields before submitting an issue:
#### Describe the issue in detail and how to reproduce it:
Hi, I tested last build from https://ci.easyrpg.org/view/Player/job/player-3ds/ on my old 3DS and sound dosen't working in any games I try to launch. Sorry for my poor english. :disappointed: Best Regarts :smile:

**Comment by carstene1ns** [comment]
Hello, 3dsx or .cia version?

**Comment by Nightshadowxd** [comment]
I tried 3dsx and cia and both have the same issue... :disappointed: 
(If this may be helpful information I use Luma 8.0 with boot9strap)

**Comment by carstene1ns** [comment]
Ok, thanks!
The only issue known currently is that the .cia version needs the dumped DSP firmware to work.
Can you upload the `easyrpg_log.txt`? It should be available in the game folder after launching the Player.
(You can simply drag-drop it here to upload)

**Comment by Nightshadowxd** [comment]
Sure :smiley: [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1098685/easyrpg_log.txt)

**Comment by carstene1ns** [comment]
This logfile seems to be from the .cia version.
```
[2017-06-20 23:07:10] Warning: Couldn't initialize audio
[2017-06-20 23:07:10] Warning: This needs a dumped DSP firmware to work!
```
You can use [`DSP1`](https://github.com/zoogie/DSP1/releases/download/v1.0/DSP1.cia) or [`DSPDump`](https://github.com/Cruel/DspDump/releases/download/1.0/DspDump.3dsx) to get the required firmware file.
However, the .3dsx version should be unaffected.

**Comment by Nightshadowxd** [comment]
Sorry, wrong file :smile: ... 
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1098733/easyrpg_log.txt)

**Comment by carstene1ns** [comment]
Hmm, same error message. Did you dump your DSP firmware by now?
I suspect something is different in the way homebrew loads, i.e. not through the loader (*hax payload), so no DSP is available.

**Comment by Nightshadowxd** [comment]
Yes, I dumped DSP firmware and this fix sound problem. [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1098785/easyrpg_log.txt)

**Comment by carstene1ns** [comment]
Great! So it seems a dumped DSP firmware is now a requirement.
