### ISSUE TITLE
Events glitch when crossing looping map borders

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1216]
Bug reported by @20kdc, testcase: https://20kdc.duckdns.org/Synth.zip

Related: #716, fixed with 689fd8022ac6.
Proposed patch, reverting to old behaviour when the map is 20 tiles wide:

```c++
diff --git a/src/game_character.cpp b/src/game_character.cpp
index 21a0d5f1..7424bcd0 100644
--- a/src/game_character.cpp
+++ b/src/game_character.cpp
@@ -131,7 +131,7 @@ void Game_Character::MoveTo(int x, int y) {
 int Game_Character::GetScreenX() const {
 	int x = GetRealX() / TILE_SIZE - Game_Map::GetDisplayX() / TILE_SIZE + (TILE_SIZE / 2);
 
-	if (Game_Map::LoopHorizontal() && (x <= -TILE_SIZE / 2 || x > 0)) {
+	if (Game_Map::LoopHorizontal() && (x <= -TILE_SIZE / 2 || x > 0 || Game_Map::GetWidth() == 20)) {
 		int map_width = Game_Map::GetWidth() * TILE_SIZE;
 		x = (x + map_width) % map_width;
 	}
```
Same likely applies for the other border on 15 tile high maps.

**Comment by 20kdc** [comment]
This looks like it would still only show one instance of the event, though. On RPG_RT I can see two copies of the event at the same time. It would probably be easier to demonstrate with a larger event.

**Comment by carstene1ns** [comment]
I used your testcase with `RPG_RT` and did not see two events at the same time.

**Comment by 20kdc** [comment]
...huh. Confusing. Will attempt to get screenshots.

**Comment by 20kdc** [comment]
![screenshot from 2017-07-07 16-43-36](https://user-images.githubusercontent.com/22304167/27965391-8ba43cbe-6333-11e7-9aeb-f753496a28c8.png)
From the RPG_RT in the Ib English Translation at: http://www.vgperson.com/games/ib.htm (This doesn't actually affect Ib to my knowledge, it's just a copy of RPG_RT on-hand)

**Comment by carstene1ns** [comment]
The problem is that our drawing code only draws every event once and on one position. It draws the event's sprite and cuts off everything not on the screen. So, as long as the position is not changed, it will either stay on the left or right side.
When we change the drawing code to handle this corner case and split up the drawing in two places when the event is partly not on the screen and the map is 20 tiles wide and looping, this might work.

**Comment by carstene1ns** [comment]
via #1510:

fmatthew5876:
> Create a 20x15 map which loops vertically. Place an event on the map with a charset sprite.
>
> Play the game walk up until the event is on the top row of the map.
>
> ![screen](https://user-images.githubusercontent.com/1198466/49261561-bc439580-f410-11e8-8bc2-8fc108c5c6c1.png)
>
>The left is RPG_RT, right is Player
>
> This bug exists horizontally for wide sprites also.

Ghabry:
> There is already a patch for this: [d11a906](https://github.com/EasyRPG/Player/commit/d11a906a196ecda412a7adf8fc731eba9746fe56)
> 
> But that one has multiple design issues e.g. the new Create and Destroy clone methods, don't think you need them.
