### ISSUE TITLE
Custom menu arrows are sending movements to the player character

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1217]
In this issue, RPG_RT does not send movements to the player character, however Player is moving it, which is wrong.

[Test case](https://github.com/EasyRPG/Player/files/1134078/test-easy.zip) provided by @gadesx.

**Comment by Ghabry** [comment]
Sounds similiar to #1109

**Comment by Ghabry** [comment]
For me the Player moves in RPG_RT o.O

**Comment by fdelapena** [comment]
The problem is: In the custom menu, there is a square selector which moves usually twice steps in Player, and just 1 in RPG_RT. This bug makes the menu not allowing to select some objects in Player. You need to access to the custom menu to see the issue.
