### ISSUE TITLE
Desolate City: Strange panorama file reference while loading savegame

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1219]
#### Name of the game:
Desolate City: The Bloody Dawn.
Download from http://netherwareentertainment.com/

#### Player platform:
Tested on Linux with master post-0.5.2

#### Attached files
- A savegame next to the problem [Save05.lsd.zip](https://github.com/EasyRPG/Player/files/1151355/Save05.lsd.zip)
- The `easyrpg_log.txt` log file [easyrpg_log_dc.txt](https://github.com/EasyRPG/Player/files/1151354/easyrpg_log_dc.txt)

#### Describe the issue in detail and how to reproduce it:
- Open the Save05.lsd and you will see the missing file warning.
- The panorama reference does not have much sense at first sight, and similar references to this string in Map0008.lmu are show message strings.

![captura de pantalla de 2017-07-16 15-00-46](https://user-images.githubusercontent.com/174885/28251364-bf59ef0c-6a38-11e7-8082-8f9983dd2bc9.png)

**Comment by elsemieni** [comment]
With changes to Master until today, there's no more warnings shown. This was fixed!
