### ISSUE TITLE
Please submit to f-droid.org 

### ISSUE THREAD

**Issue by markstinson** [EasyRPG/Player#1222]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Describe the issue in detail and how to reproduce it:
F-Droid.org leverages projects using standardized build processes on GitHub. F-droid.org checks out updated released sources, builds it on their compile farm and stages it in their FOSS AppStore app for immediate availability. Please see https://f-droid.org/wiki/page/FAQ_-_App_Developers and https://f-droid.org/wiki/page/Inclusion_How-To

**Comment by Ghabry** [comment]
Hello.
We already considered adding it to fdroid but we had no time yet to figure out how there build process works.
The problem is that we have lots of C library dependencies: https://github.com/EasyRPG/buildscripts/tree/master/android
All the libs must be somehow built by fdroid before building the Player.
Do you have any experience in contributing to fdroid?

**Comment by fdelapena** [comment]
I see a fdroid/data repo in gitlab, there is a srclibs folder which contains some common libraries with a txt to define the git repo (sdl, freetype...), then in metadata folder apps depend on library stuff from srclibs, setting the version, and I guess their build system do the rest of the magic

e.g. xmp depending on libxmp: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.helllabs.android.xmp.txt#L149

and the libxmp definition: https://gitlab.com/fdroid/fdroiddata/blob/master/srclibs/Libxmp.txt

Older versions of this package didn't use a separate libxmp in srclibs, but maybe is worth somehow. The doc part is not clear about how to deal with this, what they consider "well known repositories" for non-Java stuff: https://f-droid.org/wiki/page/FAQ_-_App_Developers#Which_libraries_and_dependencies_are_good_to_use.3F
However, the rule is clear about rejecting external prebuilt binary libraries. It seems the .txt must do all the job. Prebuilding step does a pushd/popd to dive into library dep building from there.

Some docs seem outdated e.g. the fdroid/fdroiddata repo seems to be now fdroid/data and the wiki has incomplete sections, but it looks there is a tool to test the script according with 
https://f-droid.org/docs/Building_Applications/

I guess #fdroid on freenode might clear specific questions, botbot.me logs show good activity there.

**Comment by carstene1ns** [comment]
Good thing is we do not need many patches for android. Possible offender is ICU as usual.
One thing to note is, that these library definition text files are only used to download the libs, they invoke ndk-build later in the main app build process. You can see that here for example: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.traffar.a24game.txt#L56 preparing until line 68 where the build is invoked.

**Comment by Ghabry** [comment]
Because that link uses ndk-build it's still not clear how to build when autoconf is used :/
This is like the last time I checked this (years ago). Last time the chat was not helpful and the wiki useless.

**Comment by fdelapena** [comment]
Examples containing autotools, some dependencies... there are even with direct .sh calls in newer releases:

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.collabora.libreoffice.txt
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.nooskewl.bobby.txt
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.zoffcc.applications.zanavi.txt
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/im.tox.antox.txt

**Comment by carstene1ns** [comment]
antox seems interesting, it uses the standalone toolchain as we do.
libreoffice does not matter, because they have additional android magic in their autoconf sorcery.

**Comment by Ghabry** [comment]
Because this will probably go nowhere soon it might be simpler to create a fdroid subdomain and host our own repo with two apps (nightly and "stable") via this guide: https://f-droid.org/docs/Setup_an_F-Droid_App_Repo/

**Comment by fdelapena** [comment]
Another possible approach to get accepted into F-droid without rebuilding (keeping the same signature) is by using reproducible builds. However, NDK building has some challenges to be solved yet:
https://f-droid.org/en/docs/Reproducible_Builds/

**Comment by Ghabry** [comment]
For more information see the discussion with fruitsnack here https://easyrpg.org/irc/log/2021/2021-02-12.html

**Comment by Ghabry** [comment]
Resolved thanks to fruitsnack.
The process can be streamlined more but the app is now on fdroid and waits for first build.

**Comment by carstene1ns** [comment]
Just for reference: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.easyrpg.player.yml

Maybe we can detect fdroid builds or add some `--fdroid` option to the scripts.
