### ISSUE TITLE
Message Stretch does not get restored when loading RPG_RT savegame

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1230]
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem: [savegames.zip](https://github.com/EasyRPG/Player/files/1185288/gromada.zip) (I guess it is Save15, not tested)

#### Describe the issue in detail and how to reproduce it:
> The game uses tiled system graphics. EasyRPG doesn't detect that when loading a save file created by RPG_RT. This doesn't happen with save files generated by EasyRPG.

(issue reported by mail)

![screenshot_20170709-095122](https://user-images.githubusercontent.com/4691314/28748441-5ab33358-74b8-11e7-93a8-6d9eeeeb1ec5.png)

**Comment by Ghabry** [comment]
Maybe the default value for message stretch in the LSD is wrong? Only logical reason why message stretch is broken when loading RPG_RT saves imo.

**Comment by carstene1ns** [comment]
Yeah, thought about this too (because of https://github.com/EasyRPG/Player/issues/479#issuecomment-165606643).

**Comment by Ghabry** [comment]
Made some tests in a test project. Everything works as expected in all directions. Doesnt matter if RPG_RT or EasyRPG created the save.
