### ISSUE TITLE
Wii: Jeanne Action picture issues

### ISSUE THREAD

**Issue by Jalax6** [EasyRPG/Player#1237]
Had some problems on trying to play Jeanne Action ([video](https://www.youtube.com/watch?v=IH99YtvxOjE))([download](http://vipkouhaku09.web.fc2.com/sakuhin_024.htm)) wich is fully made out of pictures. PC version went playable, but wii version just refuses to load most pictures.

**Comment by Ghabry** [comment]
The download link  doesn't work the working link is this one:
http://vipkouhaku09.web.fc2.com/_dat/vipkh09_024.zip

**Comment by Ghabry** [comment]
The problem here is that the game loads a gigantic amount of huge pictures. On my computer the game eats 600 MB RAM on the first map. The Wii only has ~100 MB RAM, therefore this is a hardware limitation and unsolvable, sorry!

**Comment by Ghabry** [comment]
The health always shows full health for me, but this matches the RPG_RT.exe behaviour -> game bug
