### ISSUE TITLE
Code smell. Move Game_Temp to the corresponding classes

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1240]
Currently Game_Temp is used to store lots of unrelated fields for configuring the interpreter. They should be moved to better locations.

```bool Game_Temp::menu_calling;```
Use Scene::Find to get the map scene handle and call "CallMenu" directly

```Game_Battler* Game_Temp::forcing_battler;```
**Unused**

```bool Game_Temp::battle_calling;```
Use Scene::Find to get the map scene handle and call "CallBattle" directly

```bool Game_Temp::shop_calling;```
Use Scene::Find to get the map scene handle and call "CallShop" directly

```bool Game_Temp::inn_calling;```
**Tricky**. Maybe invent a new namespace Game_Inn that stores this? (Game_Inn::IsActive)

```bool Game_Temp::name_calling;```
Use Scene::Find to get the map scene handle and call "CallName" directly

```bool Game_Temp::save_calling;```
Use Scene::Find to get the map scene handle and call "CallSave" directly

```bool Game_Temp::load_calling;```
Use Scene::Find to get the map scene handle and call "CallLoad" directly

```bool Game_Temp::to_title;```
Use Scene::PopUntil(Scene::Title);

```bool Game_Temp::gameover;```
Use Scene::Find to get the map scene handle and call "CallGameOver" (not implemented yet) directly

```bool Game_Temp::transition_processing;```
Move to Graphics like the other transition code or refactor transitions in general and move all transition code to a new namespace Game_Transition.

```Graphics::TransitionType Game_Temp::transition_type;```
Move to Graphics like the other transition code or refactor transitions in general and move all transition code to a new namespace Game_Transition.

```bool Game_Temp::transition_erase;```
Move to Graphics like the other transition code or refactor transitions in general and move all transition code to a new namespace Game_Transition.

```bool Game_Temp::shop_buys;```
Argument to Scene_Shop constructor

```bool Game_Temp::shop_sells;```
Argument to Scene_Shop constructor

```int Game_Temp::shop_type;```
Argument to Scene_Shop constructor

```bool Game_Temp::shop_handlers;```
Tricky because this configures if the interpreter has to process "Bought something/nothing" handlers.

```std::vector<int> Game_Temp::shop_goods;```
Argument to Scene_Shop constructor

```bool Game_Temp::shop_transaction;```
If something was bought in the shop. **Tricky** because there is currently no way to provide a return when a scene is removed from the stack. Maybe would be a useful feature?

```int Game_Temp::inn_price;```
**Tricky**. Maybe invent a new namespace Game_Inn that stores this? (Game_Inn::GetPrice)

```bool Game_Temp::inn_handlers;```
**Tricky**. Maybe invent a new namespace Game_Inn that stores this? (Game_Inn::GetHandlers)

```std::string Game_Temp::hero_name;```
Argument to Scene_Name constructor

```int Game_Temp::hero_name_id;```
Argument to Scene_Name constructor

```int Game_Temp::hero_name_charset;```
Argument to Scene_Name constructor

```bool Game_Temp::battle_running;```
Move to Game_Battle

```int Game_Temp::battle_troop_id;```
Constructor of Scene_Battle or a new field in Game_Battle

```std::string Game_Temp::battle_background;```
Constructor of Scene_Battle or a new field in Game_Battle

```int Game_Temp::battle_formation;```
Constructor of Scene_Battle or a new field in Game_Battle

```int Game_Temp::battle_escape_mode;```
Constructor of Scene_Battle or a new field in Game_Battle

```int Game_Temp::battle_defeat_mode;```
Constructor of Scene_Battle or a new field in Game_Battle

```bool Game_Temp::battle_first_strike;```
Constructor of Scene_Battle or a new field in Game_Battle

```int Game_Temp::battle_result;```
**Tricky** because there is currently no way to provide a return when a scene is removed from the stack. Maybe would be a useful feature?

```cpp
enum BattleResult {
  BattleVictory,
  BattleEscape,
  BattleDefeat,
  BattleAbort
};
```
Move to Game_Battle

**Comment by fmatthew5876** [comment]
`Game_Temp` in general scares the hell out of me. It's basically impossible to prove any invariants about correctness. Anything can change any of the globals so you have an explosion of possible states and really esoteric hard to find bugs.

I think we should work to eliminate it and prefer some kind of message passing style instead. Like your `BattleResult` example.
