### ISSUE TITLE
Regression: camera not following the hero in all maps

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1241]
Some hours after releasing current master in Google Play, there are 3 reports on this issue.

So far, reported affected games are [Mario RPG the seven sages](http://udivision.blogspot.com/2009/08/smrpg-seven-sages-download-page.html) (165 MB) and [Polka](http://commodorette.wixsite.com/polkarpg/) (246 MB).

Because download speed is currently slow and no time for further testing, here are Polka related log and savegames attached to a bug report sent via email.

- [easyrpg_log.txt with Polka details](https://github.com/EasyRPG/Player/files/1216843/easyrpg_log.txt)
- [polka_savegames.zip](https://github.com/EasyRPG/Player/files/1216847/polka_savegames.zip)

**Comment by Ghabry** [comment]
ah i see it.
https://github.com/EasyRPG/Player/pull/1238/files#diff-488e769e6277b870601b99f538eadcdaR332

AddScreenX/Y modify the first arg which is a reference. (Bad design?)

So this needs 2 extra lines:
map_info.position_x = x; (and y)

**Comment by Ghabry** [comment]
-some+all 👎
