### ISSUE TITLE
Investigate minimum Actor Level and other off-by-one's

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1248]
In *COLORS: Lost Memories* the initial actor level is 1 and this gets decreased in the intro by 1, so is effectively 0, RPG_RT allows that. We cap this to 1 in `Game_Actor::SetLevel()`.
This can be seen when looking at savegames created by RPG_RT and Player for this game.

We might have similar problems with attributes such as Atk, Def, Agi, etc.

**Comment by Ghabry** [comment]
The number shown in the savegame scene is wrong in RPGRT (for easyrpg saves) in general. The Deep8 dev told me that all values are shown as 1 and when loading e.g. a OFF save in RPGRT the SP are 1.

**Comment by carstene1ns** [comment]
Upon further investigation I do not know what this game is doing.
I created a testcase in 2k and 2k3, decreased the level and HP as this game does and both do not allow 0.
However, in this game it is possible (even when I replace the RPG_RT).

![20170815-040002](https://user-images.githubusercontent.com/4691314/29299353-4a9983f6-816e-11e7-9f37-9ffd6cb762c4.png)

**Comment by carstene1ns** [comment]
Your sanity check branch yields:

```
Warning: Actor 1: Invalid level 0
Debug: Actor 2: Removing invalid item 18 (of type 0) from equipment slot 1 (needs type 1)
Debug: Actor 3: Removing invalid item 18 (of type 0) from equipment slot 1 (needs type 1)
Debug: Actor 4: Removing invalid item 18 (of type 0) from equipment slot 1 (needs type 1)
Warning: Actor 5: Invalid level 0
Warning: Actor 7: Invalid level 0
```

**Comment by Ghabry** [comment]
This is caused by a manual database edit. The initial_level is set to 0.
Seems that RPG_RT accepts any level for this field and uses stats of 0 and EXP of 0 when the level is invalid.

Adding EXP works as expected (when you have 1 EXP you become LV1) and Level ups, too. But when the new level is below 1 showing the "level up message" will hang RPG_RT. Without the message everything works fine.

**Comment by Ghabry** [comment]
Are you sure about the "Level 1 to 0 decrease"? Even when I set the initial level to 0 I can't decrease again to this level with RPG_RT.
