### ISSUE TITLE
Polixiuhs: Picture overlay color effect is missing

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1249]
#### Name of the game:
Polixiuhs ([download](https://rpgmaker.net/games/9279/))

#### Describe the issue in detail and how to reproduce it:

This game uses an interesting screen overlay effect. There are 2 common events, the first one moves a striped image up and down to create a CCTV effect. The second one moves fog/a cloud with waver effect.
In RPG_RT you can clearly see the fog, it has green and red portions, while in Player it is almost invisible.

RPG_RT: ![20170814-003110](https://user-images.githubusercontent.com/4691314/29253894-fca4c862-8088-11e7-83a3-fd8a905d2e01.png)
Player:
![20170814-003224](https://user-images.githubusercontent.com/4691314/29253895-fca519ca-8088-11e7-9b58-6f7f879487a1.png)

The effect can also be seen better on the added screenshots at rm.net:
https://rpgmaker.net/games/9279/images/72181/
https://rpgmaker.net/games/9279/images/72314/

This might be related to our 32 bit rendering, but the fog seems to lack opacity.

**Comment by fdelapena** [comment]
IMO the imperceptible waver effect on the left is not a bug, but a feature: because RGB565 drops color information, the jump between palette values is harder and makes the effect more visible in RPG_RT. This may do a lesser visible tone difference due to more precision in our rendering. Solving this by reducing color depth may not be worth to recreate this effect.

However, maybe some opacity values might need to be corrected, but needs deeper testing to verify if this really imprecise, but I feel the scanline contrast is mostly the same.

**Comment by carstene1ns** [comment]
I have made a gif out of the two images. The difference is best seen when on a dark/black background:

![color_overlay](https://user-images.githubusercontent.com/4691314/33543817-beb7bd68-d8d8-11e7-874f-2e9f21583838.gif)

Not saying you are wrong, but to me the intensity is still different.

**Comment by Ghabry** [comment]
Thanks for the gif now I finally see where the problem is 👍. Agree with carstene1ns: This is too much for a 565 conversion.

**Comment by Ghabry** [comment]
Disabled all events except CCTV (which doesn't do any Tone change): The colors of the floor tiles are still significantly different o.O (making the CCTV much more visible in EasyrPG)

**Comment by fdelapena** [comment]
To make sure these tone differences are not a RGB565 palette degradation, they should be tested with a patched RPG_RT.exe to enable truecolor: https://rpgmaker.net/forums/topics/18775/?post=675209#post675209

**Comment by fmatthew5876** [comment]
I had to hack stuff to get this to run in patched RPG_RT and I broke something so I didn't get the exact same tones.

However I can say that the greenish effect on the stone tiles is due to palette degradation. My hacks to the game broke the tones, but I could clearly see the green vs grey effect in RPG_RT vs RPG_RT patched.

Whether there are additional tone inaccuracies in Player, I can't tell yet.

**Comment by fdelapena** [comment]
Here's a capture with patched truecolor RPG_RT with CCTV scanlines and the slight waver effect:
![filter-contrast-10000](https://user-images.githubusercontent.com/174885/58385448-e041f700-7fad-11e9-9ed2-5281964172f9.png)

If you can't see the scanlines, here's the GIMP contrast filter at 10000:
![truecolor-cctv-waver](https://user-images.githubusercontent.com/174885/58385449-e041f700-7fad-11e9-9af5-ec854443d8f7.png)

**Comment by Ghabry** [comment]
EasyRPG | DynRPG (32bit) | RPG2k3E

![Screenshot_20190526_200627](https://user-images.githubusercontent.com/1331889/58385520-ef4a9880-7ff1-11e9-9360-667b9bdfb26c.png)

**Comment by Ghabry** [comment]
Okay I disabled the animation and made 3 substraction pictures:

When you analyze the colors you see that the difference for Dyn vs Easyrpg is never more than 1 and the Dyn -> RPG_RT and EasyRPG -> RPG_RT sometimes 16.

dyn32_minus_easyrpg:

![dyn32_minus_easyrpg](https://user-images.githubusercontent.com/1331889/58385654-1efaa000-7ff4-11e9-9c4a-7923c4f0211a.png)


easyrpg_minus_rpgrt:

![easyrpg_minus_rpgrt](https://user-images.githubusercontent.com/1331889/58385652-173afb80-7ff4-11e9-8939-0b1a3badd8a7.png)

dyn32_minus_rpgrt:

![dyn32_minus_rpgrt](https://user-images.githubusercontent.com/1331889/58385651-13a77480-7ff4-11e9-8e65-1c652bca5ae4.png)

**Comment by Ghabry** [comment]
Well because these pictures need a high contrast monitor and perfect color vision here the palette as ascii ;)

dyn32 minus easyrpg:

0,0,1
0,1,0
1,0,1
0,1,1
0,0,0
1,0,0

easyrpg minus rpgrt:

0,0,0
0,1,0
0,0,1
1,0,0
5,7,0
14,18,24
23,14,0
16,15,1
7,15,17

dyn32 minus rpgrt:

0,0,0
0,1,0
1,0,0
4,7,0
15,19,24
24,15,0
16,15,0
7,15,16

**Comment by carstene1ns** [comment]
dyn32_minus_easyrpg:
```
    159488: (  0,  0,  0) #000000 black
    112464: (  0,  0,  1) #000001 srgb(0,0,1)
     13612: (  0,  1,  0) #000100 srgb(0,1,0)
     18888: (  0,  1,  1) #000101 srgb(0,1,1)
      2276: (  1,  0,  1) #010001 srgb(1,0,1)
       472: (  1,  1,  0) #010100 srgb(1,1,0)
```

easyrpg_minus_rpgrt:
```
    191024: (  0,  0,  0) #000000 black
       440: (  0,  0,  1) #000001 srgb(0,0,1)
    113592: (  0,  1,  0) #000100 srgb(0,1,0)
      2096: (  1,  0,  0) #010000 srgb(1,0,0)
         4: (  5,  7,  0) #050700 srgb(5,7,0)
        20: (  7, 15, 17) #070F11 srgb(7,15,17)
        12: ( 14, 18, 24) #0E1218 srgb(14,18,24)
         4: ( 16, 15,  1) #100F01 srgb(16,15,1)
         8: ( 23, 14,  0) #170E00 srgb(23,14,0)
```
dyn32_minus_rpgrt:
```
    301756: (  0,  0,  0) #000000 black
      3300: (  0,  1,  0) #000100 srgb(0,1,0)
      2096: (  1,  0,  0) #010000 srgb(1,0,0)
         4: (  4,  7,  0) #040700 srgb(4,7,0)
        20: (  7, 15, 16) #070F10 srgb(7,15,16)
        12: ( 15, 19, 24) #0F1318 srgb(15,19,24)
         4: ( 16, 15,  0) #100F00 srgb(16,15,0)
         8: ( 24, 15,  0) #180F00 srgb(24,15,0)
```

**Comment by carstene1ns** [comment]
I consider this `WontFix` then.

**Comment by fdelapena** [comment]
For possible future reference, double contrast difference for the first picture:

![Captura de pantalla de 2019-05-26 13-09-36](https://user-images.githubusercontent.com/174885/58386049-9100c400-7fb7-11e9-92e1-1133b94eecf2.png)

**Comment by Ghabry** [comment]
In Yume2kki Bioluminescent Cavern looks totally different but this is the same issue: after applying a 32bit patch they look the same.
