### ISSUE TITLE
Support RPG Maker 2003 v1.12

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1263]
Released on 14th of September: https://steamcommunity.com/games/362870/announcements/detail/3214864483356355770

- [x] The “This Event” target may now also be used in common events and will refer to the last map event in the call stack.
- [x] The “restart game” hotkey is now Alt+F12 instead of F12. This change was done to avoid frustrating accidental restarts, especially when the user is used to pressing F12 in order to create a screenshot (like it’s done in most Steam games). When F12 is pressed, a message is now displayed instead. (**countdown since 0.6.2**)
- [x] If multiple events were stacked on top of each other on the same tile, their drawing order would change in unpredictable ways based on the position of other events (including the player). Now, they are sorted by their IDs (highest ID drawn last). (**since 0.6.1**)
- [x] The current position of the parallax background was not saved in the save file.

Pictures:
- [x] Variables can now be used instead of fixed values for picture ID, filename suffix, transparency and zoom.
- [x] The Z position (layer) in which a picture is drawn can now be changed (for example, pictures can be shown between the tileset and the events, or even above message windows, etc.).
- [x] Pictures can now be used in battle as well. (**since 0.6.2**)
- [x] For each picture, it’s now possible to select whether it is affected by screen shake
- [x] ... or affected by tint
- [x] ... or affected by flash
- [x] For each picture, it’s now possible to select whether it should be automatically cleared on map change
- [x] ... cleared on battle end. (**since 0.6.2**)
- [x] Spritesheet feature: Pictures may get their graphics from a spritesheet with variable size. It’s possible to select a fixed sprite to display or set it through a variable.
- [X] Automatic animation: A spritesheet with individual animation frames can be used for automatically animating a picture with a user-defined speed. The animation can be run in a loop or once. In the latter case, the picture is automatically erased once its animation is finished. This feature can be used to show picture animations in battle, where no parallel process event for manual animation may be used.

Not applicable:
- Engine understands PicPointerPatch now (already supported)
- “Show Picture” used in a loop with the same picture file will no longer cause high CPU and disk load (which led to lags) (already supported)
- Displaying a picture with 100% transparency will now skip the drawing step entirely (already supported)
- The game volume can now be controlled from the video options dialog. - Not applicable
- When using a gamepad, the D-Pad may now be used as alternative to the analog stick. - Not applicable, already in?
- On multicore-processor machines, a race condition would cause key states reported to events to be unreliable while a key was being held down (it would appear to “bounce” instead of being reported as continuously pressed).
- When the game was launched without focus, e.g. because another window had become active while the game was being launched, and in some other edge cases, the game would accept keyboard input despite being in the background.
- Escaping a backslash in a message with another backslash (“\\”) would not work properly and cause weird behavior when the following character was “n”. (already supported)
- Under rare conditions, the game could crash with an error “List index has exceeded its valid range (-1)” when a vehicle was displayed.
- To simplify the process of setting the number of sprites per sheet when selecting a sheet, it’s possible to include “[x,y]” in the spritesheet filename, where “x” and “y” are the number of sprites per row and column (e.g. “my_sprite[5,3].png”). When doing so, these numbers will be automatically set when the spritesheet is selected.
- When an event had changed the tileset on the current map, this change was not preserved after loading the game from a save file. (It was still saved, just not loaded correctly, so this fix will retroactively make it work for existing save files.)  Already supported by EasyRPG
- Sine effect goes now from [1, 10] (was [1, 9]) and rotation from [-10, 10] (was [1, 9]). The rotation change allows to stop rotations via "Rotation 0" (instead of reverting to the initial position).

Chunk infos:

```
ShowPicture:

14. Ignored
15. Of-by-one-error in 2k3 (junk)
16. empty
17. Type of ID (arg0), 0=const, 1=var
18. Name replacement chars
19. Name replacement var (0=none)
20. Zoom (arg5) type
21. Transparency (arg6) type
22. Sheet X (0 = disabled)
23. Sheet Y
24. Sheet (arg25) type (0=const, 1=var, 2=anim)
25. Sheet ID/var/speed
26. Sheet only once?
27. Map priority +1 (0 = invisble)
28. Battle priority +1 (0 = invisble)
29. Display persistent

MovePicture

16. ignored
17. Type of ID (arg0), 0=const, 1=var
18. Name replacement chars???
19. Name replacement var (0=none)
20. Zoom (arg5) type
21. Transparency (arg6) type

Erase Picture:

1. ID type (0=const, 1=var, 2=range)
2. range max

New LSD chunks for picture data:
19: Sheet X (default 1)
20: Sheet Y (default 1)
21: Sheet cur id (default 0)
22: Sheet speed (default 0)
23: Sheet FPS (default 0)
24: Sheet only once (default false)
25: Z layer map (default 7)
26: Z layer battle (default 0)
27: Persistant (default false)

Map:
1: Above parallax background
2: Above tileset below player
3: Above events below player
4: Above events same level as player
5: Above tileset above player
6: Above events above player
7: Above weather effects
8: Above animations
9: Above message window
10: Above timers

Battle:
1: Above background
2: Above battlers and animations
3: Above weather effects
4: Above windows and actor status
5: Above timers
```

**Comment by CherryDT** [comment]
There is a small change in the data btw from what I indicated a while ago, but I don't remember what :O 

Oh and: Small thing I forgot to add to the changelog initially: Multiple events shown on the same tile will now stack strictly by their event ID order and not in a confusing pseudo-random way depending on other events' positions (in the past this would make events swap their order when the hero was walking by, yikes)

**Comment by Ghabry** [comment]
Okay, I thought RPG_RT parses the file name and configures this on load.

No problem, we will figure it out. ^^

**Comment by Ghabry** [comment]
Engine naming problem again: Is a differentiation in EasyRPG Player between 1.11 and 1.12 needed? At least besides "This event" calls there is nothing incompatible and the chance that it breaks games is small because not soo many games were made since 1.11 and I assume that most users will update.

**Comment by CherryDT** [comment]
What do you mean - backwards compatible? Should be no problem because the previous behavior was always a crash so there is no harm in applying the new behavior all the time.

**Comment by Ghabry** [comment]
@CherryDT: We already did it this way but EraseEvent referencing "This Event" in CommonEvents is a no-op instead of crash... And we are aware of at least one game that breaks because of this. But enabling it everywhere except for EraseEvent is safe, yes.

**Comment by CherryDT** [comment]
Oh I didn't realize that it was a noop. I see

**Comment by Ghabry** [comment]
EasyRPG does restore the chipset_id but not the tile substitution. So we have our own exclusive bug here.

**Comment by Ghabry** [comment]
The Razas author noticed that it is possible to stop rotations now. Adding a new "not applicable": Sine effect goes now from [1, 10] (was [1, 9]) and rotation from [-10, 10] (was [1, 9]). The rotation change allows to stop rotations via "Rotation 0" (instead of reverting to the initial position).

This already behaves exactly as in RPG_RT @scurest picture refactor was future proof 👍

**Comment by CherryDT** [comment]
Sine should also be -10, -10

**Comment by Ghabry** [comment]
At least the bar behaves this way because when Sine is set to 0 it is in the middle but when I move the bar to the left it stays at 0 for me.

**Comment by CherryDT** [comment]
You are right! That's an oversight. I forgot to set the min. value in the edit field (which is the thing that counts) even though I did change the min. value of the slider. Damn.

Thanks for pointing that out.

**Comment by Ghabry** [comment]
Ticked "The current position of the parallax background was not saved in the save file.", is resolved by now.

**Comment by fmatthew5876** [comment]
This one

```
 If multiple events were stacked on top of each other on the same tile, their drawing order would change in unpredictable ways based on the position of other events (including the player). Now, they are sorted by their IDs (highest ID drawn last).
```

Can be checked off now with the recent changes in master.

**Comment by Ghabry** [comment]
Just for context @fmatthew5876 when was this added? Can't remember the commit, too much input over the last weeks :D

**Comment by fmatthew5876** [comment]
#2003 implements:
* Pictures can now be used in battle as well.
* ... cleared on battle end.

**Comment by carstene1ns** [comment]
I ticked the checkboxes and consider this one fixed.
For the remaning screenshot vs. restart thing I think we can have an .ini flag or just switch when we detect rpg2k3e, but this is not critical.

**Comment by Ghabry** [comment]
I find this Alt+F12 restart problematic because this would require an additional button on our console ports.
Another solution (in non TestPlay mode) could be like in iirc Undertale: When you press F12 a countdown appears and when you hold it for 2 seconds the reset is executed.

**Comment by carstene1ns** [comment]
I do not consider this functionality for console ports. Countdown is a feasible default for rpg2k3 then.

**Comment by fmatthew5876** [comment]
Added the countdown in #2010 now we have everything!

**Comment by Ghabry** [comment]
okay when #2003 and #2010 are merged this can be finally closed. Great job :)
