### ISSUE TITLE
VH1 some characters don't display

### ISSUE THREAD

**Issue by NoobBanana** [EasyRPG/Player#1264]
Game name: violated heroine

**Comment by NoobBanana** [comment]
Game link: https://mega.nz/#F!0ChlQYJa!918hNc-SzjigT-yBqiaidw
Password: nanako
Image not found/charset...

**Comment by NoobBanana** [comment]
Platform: Android

**Comment by carstene1ns** [comment]
You need to install the old English RTP on your Windows PC and then copy it over to your Android device. It has some extra files not found in the Japanese and official English version.

**Comment by carstene1ns** [comment]
Not reproducible for me, when the RTP is installed.
Only a UX problem when there is a broken RTP installation, going to add another issue about this.

Feel free to reopen, when this is not solved.

**Comment by kzn44232** [comment]
@carstene1ns  could you give link to the "old English RTP", because I can`t find it.

**Comment by carstene1ns** [comment]
There are some download links. Just google for "don rtp 2000" or the like.

**Comment by kzn44232** [comment]
I installed the rm2k_rtp132e.exe, installed it on windows and copied the installed files from pc to android path easyrpg/rtp/2000 ,but it still won`t load some images.

**Comment by Ghabry** [comment]
Maybe you got the directory layout wrong.
When correct the fie structure should be something like rtp/2000/Title/Title.png (and CharSet, ChipSet, ...)

Did you set the game region (by touching the config button next to the game) correctly? Try Japanese.
