### ISSUE TITLE
Tile substitution is not restored from RPG_RT savegames and EasyRPG doesn't save the substitution at all

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1266]
Tile substitution is the event command that replaces one tile with another.

**Comment by Ghabry** [comment]
Correction: RPG\_RT properly saves and reloads the tile subsitution.
Maybe this was broken in very old versions.

**Comment by carstene1ns** [comment]
This can be tested in [Peuteris Grey](https://easyrpg.org/play/master/?game=peuterisgrey), all warehouse maps do this.
Which results in red crosses on every ledge after loading savegames. 
![pgwh](https://p.f4ke.de/orK6y40JUO.png)
