### ISSUE TITLE
Enter Vehicle fails when the Vehicle is entered through EnterVehicle while a move route is active

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1267]
Test case: https://easyrpg.org/play/?game=issue-1267
Press SHIFT, Alex should move into the sky.

The problem is that our "GetOnOffVehicle" checks for "IsMovable" and one case of is movable is: MoveRouteOverwritten. Which is the case in this game.

In RPG_RT the move route actually continues after entering the vehicle.

**Comment by Ghabry** [comment]
This can be fixed by removing
```cpp
if (!IsMovable()))
```
and replacing it e.g. with
```cpp
if (IsMoving() || IsJumping())
```

**Comment by carstene1ns** [comment]
Moving this to next milestone, as this has possibility of breaking things shortly before release.

**Comment by fmatthew5876** [comment]
This is fixed in #1601

**Comment by Ghabry** [comment]
moved to 0.6.x because 1601 is also 0.6.x
