### ISSUE TITLE
Vd2  after loading my save game i cant move

### ISSUE THREAD

**Issue by buttestork** [EasyRPG/Player#1271]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform: android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

After i load my save game i cant walk pls help

**Comment by Ghabry** [comment]
Hello, please attach a savegame. Because you use Android you can send us the savegame via "report a bug" in the app, too.

**Comment by carstene1ns** [comment]
Files sent by mail:

[Save01.zip](https://github.com/EasyRPG/Player/files/1369467/Save01.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1369469/easyrpg_log.txt)

and

[Saves.zip](https://github.com/EasyRPG/Player/files/1369468/Saves.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1369472/easyrpg_log.txt)

**Comment by fmatthew5876** [comment]
I tried to load every one of those save games and in none of them was I stuck and unable to move.

Either this was an old bug already fixed, or the wrong save games were supplied.

I suggest we close this unless @buttestork can report still seeing the issue with more recent versions of Player and can provide a saved game.

**Comment by Ghabry** [comment]
Thanks for testing. Will quickly go through older Player releases to see if the milestone fixing this can be determined.

**Comment by Ghabry** [comment]
works since 0.6.0 - That's enough information
