### ISSUE TITLE
Verify RTP paths

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1274]
RTP paths are currently not verified, only existence is tested.
This means when a path not containing an RTP is added,
no warning is shown about the missing RTP on game startup
leading to false positive bug reports (like #1264).

Relevant code:
https://github.com/EasyRPG/Player/blob/923f7f9da1eda092769929925172e790320024fc/src/filefinder.cpp#L533

**Comment by carstene1ns** [comment]
Adding this here instead of a separate issue:

When using the game browser, the RTP paths are only initialized once, when starting a 2k game first and then a 2k3 game, the 2k3 RTPs are not added.

**Comment by CherryDT** [comment]
The full picture here is that with `FullPackageFlag=1`, it just disabled the RTP check at the start. So, a game which has the flag set but still depends on the RTP would work with RTP installed and crash in the middle of the game with missing assets with RTP not installed. With Player, such a game would just not find the assets regardless of whether RTP is installed, which is a bug.

**Comment by carstene1ns** [comment]
![why](https://p.f4ke.de/6DL9MBQCTG-why.gif)
