### ISSUE TITLE
Music Plays way too fast on 3DS

### ISSUE THREAD

**Issue by Ijustusethisforaisue** [EasyRPG/Player#1275]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform: 3DS

Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
[OFF Translation 2.0.zip](https://github.com/EasyRPG/Player/files/1366334/OFF.Translation.2.0.zip)

#### Describe the issue in detail and how to reproduce it:

The Music is playing way too fast in the Game. Its mostly noticable in the fight against the spectres after getting the first add-on. The Battle Theme ,,Peper Steak" is playing way too fast

**Comment by Ghabry** [comment]
You used a CIA from our download page at https://easyrpg.org/player/downloads ?

**Comment by Ijustusethisforaisue** [comment]
No, i used a 3dsx file from the continous builds

**Comment by Ghabry** [comment]
Okay thats fine, too. Thanks for the report.

**Comment by carstene1ns** [comment]
Just for reference: OFF uses MP3 music.
I see there were problems regarding Music/Sound files in the log.
Did you somehow convert the files?

**Comment by Ijustusethisforaisue** [comment]
No, i unzipped the game and kopied the unzipped file on the SD card. No mp3 converting happened from my side

**Comment by Ghabry** [comment]
Okay we well test this on one of our 3DS.

**Comment by GeigerCounter** [comment]
Can confirm. I have this problem with OFF, using the CIA from the Downloads page. Testing with OFF. Will test with other games.

**Comment by GeigerCounter** [comment]
Can't seem to reproduce in Yume Nikke or Cognitive Dissonance. Going to try the original French version of OFF to see if for some strange reason it only presents in the English translation.

**Comment by GeigerCounter** [comment]
Issue does not present in the original French version of the game. However part of the install process decompresses the music files to .wav files, so that complicates things a bit. I suspect the MP3 decoding is the culprit. A potential temporary workaround for OFF specifically is to copy the decompressed waveform files from the French game into the translated game's music folder.

**Comment by carstene1ns** [comment]
Thank you. As suspected, it is the mp3 playback then. Question is now why this does not happen with other games with mp3 music (Ib title sceene?) Maybe the mp3s in OFF have some special aspect, i.e. VBR, ABR or something. Or they are monaural and we query the library wrong.
