### ISSUE TITLE
Sleep never wears off in OFF

### ISSUE THREAD

**Issue by rsclifford** [EasyRPG/Player#1276]
#### Name of the game:
OFF (v1.6.1, English 2.0 Update)

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1366425/easyrpg_log.txt)
[Save01.zip](https://github.com/EasyRPG/Player/files/1366426/Save01.zip)

#### Describe the issue in detail and how to reproduce it:
The first boss, Dedan, can inflict the Asleep ailment with his "Hour Hand" attack. It's supposed to wear off after a while, but it never does.

To reproduce:
- Load the attached save
- Walk forward, choose "Yes" when asked if you want to go through the gate, and go through the conversation
- Wait for Dedan to connect with "Hour Hand" and put a party member to sleep

**Comment by carstene1ns** [comment]
Hello, thanks for the bug report!
This is simply not implemented yet (even if #821 says otherwise, I could not find it in the code).

For reference: In OFF "Asleep" state lasts for 1 turn, then chance of recovery is ¼, when hit ½.

**Comment by Ghabry** [comment]
Not sure ifn"when hit" is impemented. Heal after x turns is https://github.com/EasyRPG/Player/blob/master/src/game_battler.cpp#L621

**Comment by carstene1ns** [comment]
Whoops, did look at battle_algorithm only 😀.

**Comment by Ghabry** [comment]
This is indeed broken because the state heal is only processed when the actor does a turn which is impossible when sleeping.
Besides this bug the turn count is handled incorrectly for state heal: Currently is only incremented when the actor has a turn instead of when any actor/enemy does a turn.

**Comment by carstene1ns** [comment]
(needs testing after all these battle fixes)

**Comment by fdelapena** [comment]
Tested with current master, this issue still happens, apparently.

**Comment by Ghabry** [comment]
will see if this is still an issue and provide a fix
