### ISSUE TITLE
Windows Platform Cleanup

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1279]
Just a small list of stuff that bugs me related to our Windows Port.

- [x] `NOMINMAX` and other preprocessor stuff (`*LEAN*`) should be moved to the MSVC solution
- [x] The minidump writer inside `player.cpp` should be moved into `utils_win.cpp`

**Comment by Ghabry** [comment]
By now the NOMINMAX & friends could be moved in the CMakeLists because the solution is almost deprecated.
