### ISSUE TITLE
Battle 2k: Unexpected target name when critical hit in Japanese games [regression, bisected]

### ISSUE THREAD

**Issue by kakurasan** [EasyRPG/Player#1291]
Since 5fba5fb, unexpected target name is inserted before "critical hit" term. (e.g. "[ENEMY_NAME]会心の一撃！！" instead of "会心の一撃！！")

0.5.1:
![0.5.1](https://user-images.githubusercontent.com/10556453/31857414-0e51eea2-b719-11e7-887d-8e7f8e0e7609.png)

5fba5fb (0.5.2, unexpected):
![5fba5fb](https://user-images.githubusercontent.com/10556453/31857415-0e861dee-b719-11e7-825a-f7266512dc32.png)
Note that "森の番人トレント" is the name of this enemy.

Returning `message` instead of `GetTarget()->GetName() + message` in `Game_BattleAlgorithm::AlgorithmBase::GetCriticalHitMessage()` works for me.

Note: In `GetUndamagedMessage()`, `GetTarget()->GetName()` is needed (There is no need to get rid of `GetTarget()->GetName() +` here).

**Comment by carstene1ns** [comment]
Thank you for bisecting, seems like this was an oversight.

**Comment by Ghabry** [comment]
Yeah probably %S support was added in 2kE but before it had no actor name at all.

**Comment by Ghabry** [comment]
This is tecnically a regression caused by 0.5.2 but I don't think this is severe enough for a last minute 0.5.3 PR.

**Comment by carstene1ns** [comment]
It is a simple fix at least, but I also think 0.5.4 is fine.
