### ISSUE TITLE
Misalignment by 2 pixels when the viewport reaches the map border (once again)

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1300]
Guess this is a regression, not bisected yet.

Walk to any map border and then let the map scroll. You will notice that the viewport is misaligned by 2 pixels. Screen scrolling is surprisingly hard, will we ever get this working :/

This breaks the first faceset animation in the "a mouse ate the column tile" test case.
But I can't find that testcase anymore, could somebody link the issue?

**Comment by carstene1ns** [comment]
That should be #1169.
