### ISSUE TITLE
"Change Params" not properly capped when going below 1

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1306]
Assuming you have 10 HP and you do "Change Params" with "-100 HP" the HP value becomes internally "-90 HP" in EasyRPG but is adjusted to 1 HP when accessed.

This behaviour appears to be consistent with the English release of 2k3 but because this is 1.09 based this was probably fixed in this version and not by Cherry?
In 1.08 the "-100" would result in "1 HP" so doing another +10 would be "11 HP" and not "-80 HP"

Also needs a test in 2k :/
Not aware of any game except Deep 8 that relies on this < 1.09 behaviour. Found by the Deep8 author who told me he will fix it in his event code so it is 1.09 compatible.

**Comment by fmatthew5876** [comment]
This is likely fixed now in master. Needs a retest.

**Comment by Ghabry** [comment]
The main problem here was that it is depending on the version of the RPG\_RT engine being used.

Not worth emulating until any game breaks because of this, just need to agree on one behaviour.

**Comment by fmatthew5876** [comment]
I tested this event code in master:

```
Change HP -999 (no death)
Change HP +10
```

Result: 11HP

```
Change HP -999, Allow Death
Change HP +10
```
Result: 0 HP, Dead

matches latest steam RPG_RT.

In my opinion this is the only sensible thing to do. We have to take a stand and I vote we stand with the sensible thing and be compatible with latest versions of RPG_RT.

So I vote we close this issue.
