### ISSUE TITLE
Shop loads CharSet images as if they would be prefixed with $ (dynamic size) 

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1315]
#### Name of the game: Final Tear 3
https://rpgmaker.net/games/3983/

#### Attach files (as a .zip archive or link them)

[Final Tear 3.zip](https://github.com/EasyRPG/Player/files/1536844/Final.Tear.3.zip)

Is either Save12 or 13. The correct one is the one in the fields.

#### Describe the issue in detail and how to reproduce it:

Walk down until you reach a city, go to the left and enter the shop.
When you want to buy something the character preview is wrong.
This is caused by the window buy code which assumes that the CharSet width is correct but the used file only contains one char. Imo the best way to solve this would be to configure custom Game_Characters and to simply render them into that field. Avoids code duplication.

**Comment by fmatthew5876** [comment]
I think the zip file is wrong here. Save 12 and 13 both load into dungeons.

**Comment by fmatthew5876** [comment]
This is easy to reproduce with a single character sprite sheet in a test game. I see the bug.
