### ISSUE TITLE
Final Tear 3: Endless intro loop

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1316]
#### Name of the game: Final Tear 3
https://rpgmaker.net/games/3983/

Start a new game and Choose "Skip intro". This will still show the (far too long) credits which shows the authors. Simply fast forward through it until you reach a yellow epilepsy-like (at least at 10x :D) thunderstorm scene. This one will loop infinitely after the next name is displayed.

Quote from 20kdc in the forum

> Map 0719, “You will never disrupt < Intro pounder” is a night scene, just after the first bit of voice acting (which appears to be involuntary for the intro???). It’s driven by E2/Event talk, a parallel event.
> After it’s done, it goes to Map0954, “MAP0954”, driven by E1/EV0001 (also a parallel event), which shows the “STEVIE V.D LAAR / PRESENTS” scene.
Map 0954 then goes back to Map 0719 for a sec, shows map, and then event execution stops there, because Map 0719’s event starts up again, and on EasyRPG Player it interrupts map 0954’s event.
> I assume that on RPG_RT, it does not, and the map transition goes quickly enough that the intro lines don’t play, or alternatively, Map 0719 is the event that gets interrupted.

**Comment by Ghabry** [comment]
FYI: The fix for log.[in] does not fix this.

**Comment by fdelapena** [comment]
This game uses DynRPG patches and also uses some modified headers while trying to test with plain RPG_RT (it returns invalid signature), so these headers should be restored and play with unpatched RPG_RT.exe to make sure DynRPG patches are not the problem.

**Comment by fmatthew5876** [comment]
This is fixed in #1694
