### ISSUE TITLE
The Panspermia: performance issues

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1320]
Email bug report with "Game Hang / serious lag" in subject says:

> i report a bug found in game The Panspermia. it Hang and got serious lag right after the opening scene. seriously! it one of the best rpg maker 2000 game. why?? 
but when i press report bug button and came back to game screen. it run normally. but it became hang again after like 3 seconds!

**Comment by Ghabry** [comment]
One framedrop I can confirm is that returning from the layout editor reduces the framerate... At least on my slow phone it goes down to 45 FPS, on my tablet it stays at 60.
