### ISSUE TITLE
Android: Ensure the app works with targetSdkversion=26 by October 2018

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1323]
This is a requirement by Google otherwise they refuse publishing of updates:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

**Comment by Ghabry** [comment]
I ask everybody to do tests with all there different Android devices if they encounter any problems anywhere in the Player now.
There shouldn't be any but this is Android so you can never be sure >.>

**Comment by carstene1ns** [comment]
Let us just push it to google play beta channel... :^)

**Comment by Ghabry** [comment]
Using our unpayed beta testers for it is a great idea.
