### ISSUE TITLE
Wii Continue From Save Issue, Save File Screen Freezes Over Gameplay!

### ISSUE THREAD

**Issue by erpgr** [EasyRPG/Player#1336]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Wii

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1731353/easyrpg_log.txt)

[Save01.zip](https://github.com/EasyRPG/Player/files/1731356/Save01.zip)

#### Describe the issue in detail and how to reproduce it:
After continuing a game from the main title screen, than selecting a save file the save loads and is playable however the save file screen remains overlaid on top of the gameplay making an unplayable game state. It does not seem to matter where the game is saved, and can be recreated at the beginning of the game. I tested both the original .exe, and easyrpg player on winx64 and could not recreate the issue, so it appears to be platform specific. I will also try the 3ds version asap, and update with my results.

**Comment by carstene1ns** [comment]
Thank you for your bug report!
The issue only happens when using the development version, and is not present in 0.5.3.

I suspect the recent picture fixes or the background drawing refactor to be the culprit.

**Comment by erpgr** [comment]
Okay it seems you are correct, didn't realize I was using the continuous build,  On another note, is there any possibility of adding Wii U gamepad support if not already possible, or maybe even porting easyrpg to the Wii U natively?

**Comment by carstene1ns** [comment]
We plan to support the Wii U someday, but currently no-one of us has a device to develop for / test on.

**Comment by erpgr** [comment]
How about adding libwupc to the wii version in the meantime? 

https://github.com/FIX94/libwupc

This would allow Wii U users without a wiimote to inject easyrpg as virtual console inject and use the pro controller to play.

**Comment by carstene1ns** [comment]
This seems feasible, but needs a separate WiiUI module for our Player first, as we use SDL-Wii abstraction layer and do not currently access hardware directly.

**Comment by Ghabry** [comment]
There is a bug in the Graphics::Push-Pop code. The Graphics state variable is referencing the wrong graphics stack after a Push with "pop_current_scene"-flag.
But no idea why this causes a problem now, especially when DrawBackground is called, this function is completely unrelated... :o

**Comment by carstene1ns** [comment]
This should have been fixed by #1338. Please reopen if this issue is not resolved.
