### ISSUE TITLE
Basic Desktop Ui support (via libui?) for the three Desktop Platforms

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1343]
Currently our Desktop Player is lacking behind Android which is not fair qq.

There is e.g. no modern Game Browser and in a menubar (toggable via some button) we could add functions like "Load Game...", "Load -> 1 .. 15", "Save -> 1 .. 15", "[ ] Show FPS", "[ ] Fullscreen", "Game encoding -> [...]" that make the engine easier to use.
It can be an extension to the SdlUi (or inheriting from it).

Button mapping could be also added there but this needs a way to save settings first ;)

Suggesting libUi because it's even more slim then wxWidgets and it has all functions you need for a basic Ui imo.

**Comment by Ghabry** [comment]
@fdelapena because you currently try compiling minimal wxWidgets for something else:
Could you provide configure flags for a wxWidgets library that can display a GUI with all common controls and tell the binary size?

As common controls I see these ones: https://raw.githubusercontent.com/andlabs/libui/master/examples/controlgallery/windows.png except Date/Time picker and with List + Tree widget.

Because when wxWidgets can achieve this I see no reason to use the much less tested libui.

**Comment by fdelapena** [comment]
Now having the settings menu besides the game browser, is this still worth? The encoding could be considered later for the existing portable settings UI somehow.
