### ISSUE TITLE
Play Memorized BGM does not work after a BGM fade-out

### ISSUE THREAD

**Issue by vgperson** [EasyRPG/Player#1354]
#### Name of the game:
Witch's Heart (http://vgperson.com/games/witchheart.htm)

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
[WitchsHeartMemorizeBGMBug.zip](https://github.com/EasyRPG/Player/files/1977395/WitchsHeartMemorizeBGMBug.zip)

#### Describe the issue in detail and how to reproduce it:
In numerous situations in Witch's Heart, the music does not come back when it's supposed to. Most notably, the music will momentarily stop to show a "countdown" effect when you complete a demon request, then fail to restart after - but if you save and reload, the music then plays. (The same applies to getting Rainbow Crystals.) In some cases the music does come back, but only because there's a parallel event in charge of playing the BGM. In the attached save, just press Confirm to use the water on the demon and see the issue with the countdown.

I believe the cause is that when Play Memorized BGM is called, music volume does not properly reset, and thus will remain at 0 following a Fade-Out BGM. Some testing indicated that a fade-out followed by a Play Memorized BGM wouldn't work, but putting a Play BGM command in the middle made it work.

**Comment by carstene1ns** [comment]
Seems we only need to set `data.stored_music.volume` here:
https://github.com/EasyRPG/Player/blob/master/src/game_system.cpp#L189

Question is does `RPG_RT` reset to 100% or do we need to save the volume from before the fade-out.

**Comment by Ghabry** [comment]
I wonder which volume is saved when you start the fade out and invoke "MemorizeBGM" while it's fading.

But fixing this specific issue: Is enough to remove the `if (previous_music.volume != data.current_music.volume) {` check.
