### ISSUE TITLE
Pictures unaffected by Flash Screen (also: Set Screen Tone wrong with transparent tiles + no BG)

### ISSUE THREAD

**Issue by vgperson** [EasyRPG/Player#1362]
#### Name of the game:
Witch's Heart (http://vgperson.com/games/witchheart.htm)

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
For the Flash Screen picture bug, just start a new game in Witch's Heart.
Not sure about a real-game example of the transparent tile/no map background bug. Simply make a blank map with no background, fill it with transparent tiles, and call Set Screen Tone with a non-zero duration.

#### Describe the issue in detail and how to reproduce it:
The very first thing that happens on a new game in Witch's Heart is a light-blue Flash Screen effect, which should appear over the falling animation pictures. However, the flash does not show in EasyRPG - instead, you get a brief flickering bar at the top of the screen, which is the flash "showing through" when the picture is not fully covering it. In short, Flash Screen does not have an effect on/show on top of pictures, which it should.

While testing this, I also found inaccuracies with transparent tiles (the bottom-right-most of the Layer 1 tiles) when no background image is set. Unlike RPG_RT, EasyRPG changes their color during a Set Screen Tone transition, but stops doing so once the transition completes. (Maybe it's more accurate to say it affects the background color that shows through them.) This case may be uncommon in real games; it only came to my attention after making a test room that didn't have a background.

Flash Screen in RPG_RT affects:
- Events and normal tiles: Yes
- Backgrounds: Yes
- Pictures: Yes
- Transparent tiles: No

Flash Screen in EasyRPG affects:
- Events and normal tiles: Yes
- Backgrounds: Yes
- Pictures: **No**
- Transparent tiles: No

Set Screen Tone in RPG_RT affects:
- Events and normal tiles: Yes
- Backgrounds: Yes
- Pictures: No
- Transparent tiles. No

Set Screen Tone in EasyRPG affects:
- Events and normal tiles: Yes
- Backgrounds: Yes
- Pictures: No
- Transparent tiles: **Yes, during a tone transition; once transition is complete, it does not**

---

- [X] Flash Screen should affect Pictures
- [ ] Set Screen Tone should not affect Transparent tiles

**Comment by fdelapena** [comment]
This may be worth to be checked with an older RPG_RT.exe version due to a change in Picture layer priority in 2000 Value update (1.50) and the 2003 equivalent (1.05) just in case, to take in account possible differences there ([RPG Maker 2003 changelog](https://wiki.easyrpg.org/development/technical-details/rpg-maker-2003-version-history)).

**Comment by CherryDT** [comment]
Note that this is a bit complex because RPG_RT applies color effects to individual sprites on the screen, never to the screen buffer. So it's not just the Z position which defines whether a sprite is affected. (In RM2k3E 1.12 you can now even manually select for each picture whether it is affected by screen tone or screen flash.)

**Comment by fmatthew5876** [comment]
Flash screen issue fixed in #1549

**Comment by fmatthew5876** [comment]
I retested screen tones in the following scenarios

1. Last tile transparent no background (black)
    * Only map affected
2. Last tile transparent with background image
    * Only map affected
3. Last tile not transparent no background (black)
    * Map and Bg affected, but non-transparent pixels of last tile are not :grey_exclamation: 
4. Last tile not transparent with background
    * Map, Bg, and last tile affected

In all cases master matches RPG_RT

**Comment by carstene1ns** [comment]
We should consider this fixed then.
