### ISSUE TITLE
Harvest Moon - A new Life: Executes LS.dat and SaveCount.dat via Ineluki Key Patch

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1367]
Today in "Abusing RPG_RT": [Harvest Moon a new Live](https://rmarchiv.tk/games/1092)

Describe the issue in detail and how to reproduce it:

This game uses ExecProgram of Inelukis Key Patch to invoke the two programs LS.dat and SaveCount.dat.

**LS.dat** (UPX compressed):
This program takes one argument (a memory address, always 0x46f16c), uses FindWindow for getting a handle to RPG_RT and then uses WriteProcessMemory to write a single byte (0x75) to that address.

No idea what the purpose of this write is but it changes
push offset 0x46F189 to
push offset 0x467589

Maybe @CherryDT can help ^^. Probably related to automatic savegame loading.

**SaveCount.dat:**

This program counts the number of files that end on "lsd" and writes the following text in Sounds/Saves.script.wav:

```
[execute]
Action = MidiTickFunction
Command = output
next=Saves

[Saves]
Action = AddOutPut
Value = X
next=

;by Stephan Fischer
```

Where X is the amount of Savegames found.

The script is later used to decide wheter a "load game" option shall be displayed.

**Comment by stavrossk** [comment]
I wish this game was translated into English...

**Comment by carstene1ns** [comment]
Tried this game some year(s) ago, it was item switching all the time (because of unimplemented Ineluki), so unplayable.

**Comment by CherryDT** [comment]
This is one of the later versions of Mirokus original auto enter patch if I'm not mistaken. Sonic Party 2 by Simon does the same thing.

I am not totally sure but as far as I remember, LS.dat is used to make the "load game" option selected by default on the title screen. The game is then reset and the "auto enter" on the title screen will therefore open the load menu. But I never fully explored this. I believe there is a wrapper EXE (?) which listens to F12 and resets this patch then, possibly.

**Comment by CherryDT** [comment]
But the instruction change that you wrote doesn't seem right, I'd expect it to change a 74 to a 75.

**Comment by Ghabry** [comment]
Well the auto enter patch doesn't work obviously but my Ineluki branch has now an "emulation" for this:

https://github.com/Ghabry/easyrpg-player/blob/ineluki/src/game_ineluki.cpp#L32-L38

**Comment by CherryDT** [comment]
https://github.com/Ghabry/easyrpg-player/blob/9421fb306699e4343f4e82c0cac77fbcc5a2d1b5/src/game_ineluki.cpp#L73

This should probably say that MCI _commands_ are not supported.

**Comment by Ghabry** [comment]
right, thx :)

**Comment by lychees** [comment]
![image](https://user-images.githubusercontent.com/2507027/166887371-1ee1f404-9479-47e9-9b9b-710f0824ab93.png)
https://w3itch.io/game/219

Seems that this patch is not work in Web Browser. (I can input the name when running it locally)
