### ISSUE TITLE
RPG_RT bug: Flash and sound of animation continuing from Map to Battle

### ISSUE THREAD

**Issue by Albeleon** [EasyRPG/Player#1372]
Here is a bug? from RM2000 and RM2003, just to have it written here. This issue is a little related with #580 since its metodology helped find out this one:

#### Description:
1. The sound and flashes of the map animation are still executed during the battle from when it stopped.
2. If there is another animation ongoing, the flashes of the map animation stop but the sounds continue as the new animation is reproduced.
4. If, when the battle animation ends, the map animation is still going, it will continue flashing what it has left again.
#### How to reproduce it: Just as described in #580 : 
1. play a battle animation on the map
2. enter a battle while it is ongoing
#### Videos:
RM2000 test:
 - Link 1 (Sendvid): http://sendvid.com/kuff0sq5
 - Link 2 (Github, "Save Link As"): https://github.com/Albeleon/hello-world/raw/master/MP4/2018-06-13_17-11-19.mp4

RM2003 test:
 - Link 1 (Sendvid): http://sendvid.com/we0r4176
 - Link 2 (Github, "Save Link As"): https://github.com/Albeleon/hello-world/raw/master/MP4/2018-06-13_17-11-57.mp4

**Comment by Ghabry** [comment]
The videos could be reuploaded as a zip on github, otherwise the vids are lost in the next weeks to months.

**Comment by carstene1ns** [comment]
Fixed by #1447.

**Comment by fmatthew5876** [comment]
>     2. If there is another animation ongoing, the flashes of the map animation stop but the sounds continue as the new animation is reproduced.
> 
>     3. If, when the battle animation ends, the map animation is still going, it will continue flashing what it has left again.

This happens because every frame, active battle animations overwrite the screen flash chunks, even if there is no flash effect.

So what must be happening here is that the map animation updates, sets the screen flash, then the battle  animation updates, and resets it.

Then if the battle battle animation finishes and the map one continues, the flashes will continue.
