### ISSUE TITLE
DBZ Legend of Z: both MP cost and recover points from skill are too low

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1374]
According with a email bug report by OmegaMagnusDA, MP % based cost and recovered value seems to be too small for some reason, despite it seems implemented according with #821.

The email follows:
> Hi,
> 
> So in my game DBZ Legend of Z, I have a skill called Charge UP. It gives a character MP in battle.
> The MP required to use it also scales with the characters total MP. 
> 
> When using Charge UP on Easy RPG, the MP required to use it is always at 1 and the character gains little to no MP.
> 
> Charge UP Working: https://www.youtube.com/watch?v=YvMFMjRmqww&t=1m6s
> 
> Load a save in Easy RPG to see bug:​
> - [DBZ RPG - LOZ v2.01 (NM) Easy rpg.rar](https://drive.google.com/file/d/11GZrxGwfVfRcMNxf53MiwNAoImq9J-0f/view)
> 
> 
> Database properties:
> ![charge_up_actual](https://user-images.githubusercontent.com/174885/41447045-7c32e65a-7010-11e8-85d7-8358c1c56f51.png)
> 
> Thank you for your time

**Comment by Ghabry** [comment]
Also good retest candidate ;) (the bug is here that Player uses the SP constant not the SP percentage, top right in the picture)

**Comment by Ghabry** [comment]
works for me
