### ISSUE TITLE
Support increased limits (hp, mp, atk, def, exp...) in patched RPG_RT.exe games

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1375]
There are at least a couple of patches, RM2k3++ ([RMN page](https://rpgmaker.net/engines/rt2k3/utilities/4/), [author page](https://sites.google.com/site/seenasrealm/rm2k3)) and RM Limit Changer ([RMN page](https://rpgmaker.net/engines/rt2k3/utilities/6/), [author page with source code](https://sites.google.com/site/seenasrealm/rm-limit-changer)) to increase game stat limits.

Because this feature may misbehave and there are not defined limits in game data, it needs to examine RPG_RT.exe or provide some hackish configuration reading (e.g. from ini) to support them without exe parsing.

**Comment by Ghabry** [comment]
We provide now custom chunks to handle this, though no idea if you consider this enough for fixed :)

**Comment by carstene1ns** [comment]
Imo this should be enough. Game authors can use our editor/tools to add this chunk.

**Comment by Ghabry** [comment]
Alright. Games with issues can still get their own issue (for later tracking through a database)
