### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by SamParisot** [EasyRPG/Player#1376]
I can't seem to figure out how to build EasyRPG Player for switch. Could you help me out?

**Comment by SamParisot** [comment]
I get an error when trying to run <code>sudo make</code>

The error is as follows:
<code>Makefile:6: *** "Please set DEVKITPRO in your environment. export DEVKITPRO=/devkitpro". Stop.</code>

**Comment by carstene1ns** [comment]
Question is why do you want to build it? We provide up-to-date builds on our CI server:
https://ci.easyrpg.org/view/Player/job/player-switch/

Before you can run make, you first need to setup `devkitA64` (http://switchbrew.org/index.php?title=Setting_up_Development_Environment)
and build our toolchain packages (https://github.com/EasyRPG/buildscripts).
Note, that the Player also depends on our `liblcf` (https://github.com/EasyRPG/liblcf).

And something you should never do is running `make` as root user with `sudo`...

**Comment by Ghabry** [comment]
Is There already any tool available to edit the nro Icon? Then you could change the icon and simply put the game next to the nro (without a subfolder, then it Starts directly). Kinda gives the result you want.

**Comment by carstene1ns** [comment]
@Ghabry: Even easier, just convert the .elf yourself.

**Comment by Ghabry** [comment]
And even better: The elf is already available via Jenkins: https://ci.easyrpg.org/job/player-switch/

**Comment by Ghabry** [comment]
OP: pls comment if you were still not able to build this after 6 months.
Closing for now.
