### ISSUE TITLE
RPG_RT (RM2000) feature: Sound animation in battles with limited time

### ISSUE THREAD

**Issue by Albeleon** [EasyRPG/Player#1377]
#### Description:
When a skill (with animation attached) is directed towards an ally target or ally group (enemy skill, or ally skill that heals), instead of playing the graphic animation, it plays only the sound. This is fine, but there is more than that: **It only plays the sounds of the 20 first frames of the animation.** If a sound is on frame 21 or further, it won't play. **Also, the waiting time will always be around 15-20 frames, no matter its actual length (more or less).**

#### Videos:
Link 1 (Sendvid): http://sendvid.com/7hplebiz
Link 2 (Github, "Save Link As"): https://github.com/Albeleon/hello-world/raw/master/MP4/2018-06-20_16-06-46.mp4

**Comment by Ghabry** [comment]
#1479 (after rebase only will have 3 commits) contains the patch for this, we should just retest if the cut-off is really 20 frames.

**Comment by fdelapena** [comment]
Fixed in #1449.
