### ISSUE TITLE
RPG_RT feature: Parallel Process + Battle = Weird transition + EasyRPG Battle Bug

### ISSUE THREAD

**Issue by Albeleon** [EasyRPG/Player#1382]
#### Description:
Parallel Process, unless they have a Wait 0.0 seconds at the start, always start before the TransitionIn has finished. If you start with a battle, it will do the next behavior:
1. It will flash and hear the sound while the screen is still black.
2. It will fade out to the map before inmediately smoothly transition from the map to the battle. This behavior is impossible to replicate in normal RPG_RT using Transition::None between map and battle. It works with any transition you put.
3. When the battle finishes, it returns to the map but it's black. If you go to the menu and go back, it turns normal.

In case you teleport from other map to this one, it will replicate the sound when it's black, but when it fades out to the map, it fades in quickly to black (regardless of your battle transition out) and goes to the battle normally.

In EasyRPG, in the case the game starts in a map like that, the battle doesn't start. If you are teleported from other map to this one, the battle starts after TransitionIn finished. We should correct the first case, the battle should initiate.

#### Videos:

Link 1 (Sendvid): http://sendvid.com/3ux9ezea
Link 2 (Github, "Save Link As"): https://github.com/Albeleon/hello-world/raw/master/MP4/2018-06-24_21-58-25.mp4

**Comment by fmatthew5876** [comment]
This is fixed in master now.

I tested:
- [x] Parallel event starts a battle from new game
- [x] Parallel event teleports to other map, parallel event there starts a battle
- [x] Autostart event teleports to other map, parallel event there starts a battle
