### ISSUE TITLE
Missing or unloadable images in VH01 in EasyRPG for Windows

### ISSUE THREAD

**Issue by Yuuyatails** [EasyRPG/Player#1383]
#### Attach files (as a .zip archive or link them)
 [easyrpg_log.zip](https://github.com/EasyRPG/Player/files/2132072/easyrpg_log.zip)

#### Describe the issue in detail and how to reproduce it: 
The EasyRPG player will fail to load the correct image and shows the empty screen if the filename of said image files or the file paths contains non-English texts. It happens when the game tries to loads those files.

Note that this is Windows-specific issue, as I don't encounter such issue on the Android version of the EasyRPG player on my phone.

**Comment by Ghabry** [comment]
Thanks for the report. This is probably a Unicode normalization problem again. Could be likely solved together with #839 ("Normalize").

**Comment by Yuuyatails** [comment]
So it's a known issue, huh...

It might take a long time to fix it up, I guess.

**Comment by Yuuyatails** [comment]
Unfortunately, the latest test build (811722bfd77793cc6c63dde757cfd39fcbc3df42) didn't solved the image not find issue. This was tested on PC running on Windows 10 Pro 1809 (64-bit)

Here's the log:
[easyrpg_log.zip](https://github.com/EasyRPG/Player/files/2726289/easyrpg_log.zip)

**Comment by Ghabry** [comment]
based on the logfile I don't think this is normalization related but something with handling of subfolders (which only appears to affect Windows?)

**Comment by Yuuyatails** [comment]
Tested with build 47447d33007c24e20d930023ab27695d4a96dca7, but still causes the same issue. Unlike the previous two logs, this log was created while running the build 180601 of the game.

[easyrpg_log.zip](https://github.com/EasyRPG/Player/files/2840533/easyrpg_log.zip)
