### ISSUE TITLE
[RM2kE Bug] Element with E rate negative % bug

### ISSUE THREAD

**Issue by Albeleon** [EasyRPG/Player#1391]
#### Description:
1. There is the option of changing the E rate of an element to less than 0% with the purpose of absorbing damage. It's even included in the manual: https://i.imgur.com/0gOXXTM.png https://imgur.com/UawGdqv
2. However, when you attack an enemy with E rate with that element in those conditions, the damage is like it was 100% damage. It doesn't matter if it's -1%, -100% or -999%.
#### How to reproduce it:
1. Create an element with E rating less than 0%.
2. Put an enemy with E to that state and a player character that can attack or skill with only that state.
3. Fight and throw that skill to the enemy. Compare with other values.
#### Videos:
 - Link 1 (Sendvid): http://sendvid.com/svc0n3ok
 - Link 2 (Github, "Save Link As"): https://github.com/Albeleon/hello-world/raw/master/MP4/2018-07-05%2016-44-01.mp4

**Comment by Ghabry** [comment]
@CherryDT: RPG_RT documentation vs. implementation mismatch?

**Comment by CherryDT** [comment]
Possibly a bug...! Thanks for the info

**Comment by fmatthew5876** [comment]
Also leaving a note that we don't implement this in 2k3 battle system yet.

**Comment by rueter37** [comment]
I know from older RPG Maker 2000 versions that negative attribute rates are not supported and can I confirm that negative attribute rates are always interpreted as 100% which makes the attacks do normal damage. The video shows that the feature is still not supported in version 1.62 which means that the documentation has an error. And the RPG Maker 2000 changelog doesn't even mention that feature. So it looks like that negative attribute rates are only supported in RPG Maker 2003.

**Comment by CherryDT** [comment]
We probably didn't realize that this feature isn't working in 2k. We translated and reformatted the 2k3 help file and for 2k we copied everything from the 2k3 translation which we believed was the same in both and modified only what we believed was different.

**Comment by rueter37** [comment]
This issue should be fixed now. Negative attribute rates are implemented now and RPG Maker 2000 does not support them.

**Comment by Ghabry** [comment]
@rueter37 
Please write next time "Fix #issuenumber" in the commit message or in the Github PR message. Thanks.
Makes the maintanance easier :)
