### ISSUE TITLE
RPG_RT feature: States with >0% recovery healed after battle; Cause any status in Map Event

### ISSUE THREAD

**Issue by Albeleon** [EasyRPG/Player#1392]
#### Description:
 - Issue 1: If you have a state with more than 0% recovery (doesn't matter physical recovery or turns), when the battle ends (win or escape), that state will be healed. In 2k3 you can even see, right before the TransitionOut, how it's healed. It's only kept if you have 0% recovery.
 - Issue 2: You can suffer any state in a map event and it will persist, even if the state was "End after battle". It's kept once a fight starts, though once it ends the "End after battle" is deleted.
#### How to reproduce it:
 - Issue 1: Put a state that has "Persists after Battle" and more than 0% recovery; win or escape from a battle where you are caused that state.
 - Issue 2: Cause states in an event map. Fight a battle.
#### Videos:
 - Issue 1:
RPG Maker 2000 Test:
 - Image with State characteristics: https://i.imgur.com/BMXjqXQ.png
 - Link 1 (Sendvid): http://sendvid.com/mby49mcl
 - Link 2 (Github, "Save Link As"): https://github.com/Albeleon/hello-world/raw/master/MP4/2018-07-05%2019-03-27.mp4

RPG Maker 2003 Test:
 - Image with State characteristics (sorry for the spanish, "Clasificación => Movimiento" is the same as "Persist After Battle"): https://i.imgur.com/OzM11mc.png
 - Link 1 (Sendvid): http://sendvid.com/m0zzf6kh
 - Link 2 (Github, "Save Link As"): https://github.com/Albeleon/hello-world/raw/master/MP4/2018-07-05%2019-05-44.mp4

 - Issue 2:
 - Image with State characteristics: https://i.imgur.com/flNRuOC.png https://i.imgur.com/rAM1EWp.png
 - Link 1 (Sendvid): http://sendvid.com/2urq66uf
 - Link 2 (Github, "Save Link As"): https://github.com/Albeleon/hello-world/raw/master/MP4/2018-07-05%2019-32-12.mp4

**Comment by Albeleon** [comment]
#1373 Commit 3.14 fixes this.

**Comment by carstene1ns** [comment]
Fixed by #1448.
