### ISSUE TITLE
3DS: Replace sf2dlib

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1398]
Because the devkitPro people love to break NIH stuff even if it makes your life easier we need a new graphic library for 3ds. When compiling sf2dlib currently you get tons of "API is deprecated" warnings in citro3d and some shader variables are not found anymore, which means it's not working anymore. 

Since sf2dlib was "ported" to citro3d it never really worked fine actually. The Player always had a strange flickering triangle visible during transitions e.g.

Guess we have to switch to the badly documented DKP invention "citro3d" because we decided in a previous evaluation that "citro2d" is not suitable for what we are doing because it focuses on sprite handling.

**Comment by carstene1ns** [comment]
I have found a way to make it work with citro2d, however, I get low fps: https://github.com/EasyRPG/Player/compare/master...carstene1ns:3dsui
Omitting `C3D_FRAME_SYNCDRAW` will gain a lot, but might have drawbacks.
Still it might be better to do the tile/swizzling in hardware, instead of that loop.
I have also another implementation of it, kindly provided by [derrekr](https://gist.github.com/derrekr/bdb0e278dd8525d8ce9f84813b092a56).

**Comment by Ghabry** [comment]
``#elif defined(_DIRENT_HAVE_D_TYPE) || defined(_3DS)`` this one is strange, I thought newlib also defines this correctly :/.

At least the tiling can be done in hardware (sf2dlib did this) but the RGBA -> ABGR (or what the order was) swapping needs a software implementation :/. You can enforce a different pixel format via Pixman, this way you can skip the swapping but for some reason this makes the code very slow (no Pixman fast path?)

**Comment by carstene1ns** [comment]
The way sf2d did it, is deprecated ("safe display transfer").
So, my current idea is to use citro2d for the bottom screen only.

**Comment by Ghabry** [comment]
RTP::Init is again crashing on the 3ds.
The solution is to change the rtp_table to the type

``typedef std::map<const char*, std::map<const char*, const char*>> rtp_table_type;``

(filefinder change WIP)

readelf showed that RTP::Init is by far the largest function (>100 kbyte), changing it to const char* reduces the function size to 5 kbyte, maybe some optimisation by the compiler exposes some 3ds library bug... no idea.

(also "const char*"  saves tons of memory allocations for useless std::strings.)

**Comment by Ghabry** [comment]
Also got fast display transfer working by now (60 FPS in menu)

Additional improvements:
 - 24 MB more free RAM
 - less audio stutter (increasing the buffer helped alot o.O)

Open issues:
looks like the display transfer corrupts the texture on the bottom screen :/
