### ISSUE TITLE
RPG_RT Feature: Vehicle direction when stepping right inside

### ISSUE THREAD

**Issue by Albeleon** [EasyRPG/Player#1403]
#### Description:
If you enter in a vehicle and still don't make any movement, even though the vehicle is looking left even after you've entered, the real direction is still the one you entered by. Here an example (the only input keys are "DECISION" and "DECISION"): https://i.imgur.com/CdqcR4A.gif

#### Possible solutions:

  - Solution 1: https://i.imgur.com/CdqcR4A.gif Just imitate RPG_RT. It requires though a few changes.
  - Solution 2: https://i.imgur.com/FSo63xX.gif Ignore RPG_RT, make the ship look in the same direction as the hero.
   - Solution 3: https://i.imgur.com/7H3PiSO.gif Ignore RPG_RT, make the hero look in the same direction as the ship.

Please choose the one you'd prefer us to implement.

**Comment by carstene1ns** [comment]
(Fixed by #1404)
