### ISSUE TITLE
[Suggestion] Some replacement for current audio library

### ISSUE THREAD

**Issue by RyanBram** [EasyRPG/Player#1408]
Hi, developers.
I would like to suggest replacement (or maybe addition)  audio library to be considered their inclusion in EasyRPG Player:

1. [TinySoundfont](https://github.com/schellingb/TinySoundFont)
A MIDI+SF2 player that very lightweight, permissively licensed, and portable

2. [libXMP](https://github.com/cmatsuoka/libxmp)
An accurate module music (.mod, .s3m, .xm, .it) player, permissively licensed (for lite version), and support many module format and compression (for full version)

3. [SDL-Mixer-X](https://github.com/WohlSoft/SDL-Mixer-X)
A fork of SDL2 that currently under active development, support more format than current SDL_Mixer including two above library (planned).

I hope this information can be useful for you. Thanks.

**Comment by Ghabry** [comment]
Hello,
we already support using of libXMP. For our provided builds we use libxmp-lite.

Because we don't have soundfont support yet the TinySoundfont library looks interesting. Another option is using fluidlite, which uses the Fluidsynth interface but has no annoying glib dependency.

**Comment by RyanBram** [comment]
Hi, thanks for your positive feedback, glad that this information is useful to this project.

I forgot to mention [miniMP3](https://github.com/lieff/minimp3) that may also useful for this project.

**Comment by fdelapena** [comment]
Thank you RyanBram.

Player also supports FMMIDI, a OPN-like FM synthesizer and standard midi file decoder with BSD license.

TinySoundfont is just a soundfont synthesizer, it does not parse MIDI data or SMF files. Same happens with FluidLite. To solve this, FMMIDI SMF MIDI parser might be used to pass note events, but it requires a reasonable amount of work to support all effects, not just note on/off (pan, expression, etc.).

**Comment by RyanBram** [comment]
I am not expert about this as I am just an RPG Maker user without any programming knowledge, but as far as I understand in tinysoundfont github project mentioned above, there are also tinymidiloader that do the job for reading MIDI file.

Event the author make an HTML5 Demo version of those library just for showing me about what the library will do.
You can see here
https://schellingb.github.io/TinySoundFont/CustomSoundFont.html

And this is my question to the author
https://github.com/schellingb/TinySoundFont/issues/14

(^_^)

**Comment by carstene1ns** [comment]
I am tempted to say that our current approach to audio libraries is sufficient.
Soundfont support will come sooner or later (#1322). Closing this.
