### ISSUE TITLE
[Regression] OFF: Incorrect HP after loading a savegame

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1409]
#### Describe the issue in detail and how to reproduce it:

Play OFF until you reach the red saving cube, then load the game. The HP suddenly jump up to 500+ HP.

Online version:

https://easyrpg.org/play/?game=off (0.5.3 -> no bug)

https://easyrpg.org/play/master/?game=off (latest version -> has bug)

You can also save in the 0.5.3 version and load in the master version, exposes the same bug.

**Bisected**: af4f5b2d16e2d0356b3e02362d2f3af125a53242

**Comment by Ghabry** [comment]
Jenkins: Test this please ♥

**Comment by mew15845** [comment]
I have the same issue with Home the spinoff
