### ISSUE TITLE
Mondschein: Final Boss fails with "Interpreter: Maxium callstack size exceeded"

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1411]
Reported via Android Bug reporting.
Not verified yet but the logfile looks legit.

---
Please fill in the following fields before submitting an issue:
#### Attach files (as a .zip archive or link them)
[Save10.zip](https://github.com/EasyRPG/Player/files/2345273/Save10.zip)
[log.zip](https://github.com/EasyRPG/Player/files/2345276/log.zip)

#### Describe the issue in detail and how to reproduce it:
Load Save 10, move through the left corridor and use the elevator to reach the boss. 
During the second phase the warnings start to appear.

**Comment by fmatthew5876** [comment]
The maximum callstack size is 1000 in rm2k3. So maybe we call this fixed by #1740?

**Comment by Ghabry** [comment]
I will recheck if this bug still triggers at all or was a side effect of another interprter bug

**Comment by Ghabry** [comment]
Closing this one for now. Cannot reproduce it anymore and havn't seen any bug report about this in years.
