### ISSUE TITLE
Log.[in]: Wrong event execution order after Erase Screen event

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1416]
Please fill in the following fields before submitting an issue:
#### Describe the issue in detail and how to reproduce it:
Start the game, go to the PC, leave the PC. Start the PC again, screen stays black.

Caused by Event 2 which does on Page 2 (Autorun) a Hide Screen, this results in a yield because we can't have inner loops. After the transition parallel events run and one enables Switch 5 again, which is wrong.

Possible solution: Prevent parallel event execution after returning from a hide/show screen effect, the main event continues without running anything else.

**Comment by 20kdc** [comment]
...It seems like only the interpreter-thread that's responsible for the transition should get priority, no matter which interpreter-thread that is... Maybe allow transitions to have a "responsible interpreter" attached?

**Comment by Ghabry** [comment]
Valid point, just traced parallel events and they behave exactly the same, therefore your suggestion is better.
