### ISSUE TITLE
Switch: No sound or graphics in OFF

### ISSUE THREAD

**Issue by Morez318** [EasyRPG/Player#1425]
#### Player platform: Switch

I've been trying to get OFF to work on switch, but it says there are missing pictures and no audio plays. It is unplayable. I've tried different versions of rpgplayer and downloaded the rtp and put it in the 2003 folder, but the game still wont work.

**Comment by carstene1ns** [comment]
Switch platform currently has problems using file names with different encodings. Try another extraction program or use a different file system (FAT32 vs. exFAT) SD Card.

Will try this game later.

**Comment by Morez318** [comment]
What do you mean by another extraction program? Would I extract the game?

**Comment by carstene1ns** [comment]
I am not sure how you tried to get the game to run then...
It needs to be extracted completely from the archive it is distributed in (e.g. `.rar`, `.zip`)
Can you provide the `easyrpg_log.txt` file from the game directory (on the SD card, e.g. `/switch/easyrpg/OFF`)? It should give us some insight. Thanks!

(The form below supports uploading files.)

**Comment by carstene1ns** [comment]
Works for me.
