### ISSUE TITLE
Improve consistency in midi sound

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1434]
The different libraries used on the platforms produce different sounding midi music. The best solution would be to include some soundfont with liblcf to be distributed with Player and Editor to be used on all platforms. Is that possible without violating any licenses?

Even on the same platform the sound quality can change out from under you. I originally compiler Player on linux and the midi sounded ok. Then I installed timidity and just by doing that the wildmidi defaults changed to use it and now my midi music is barely functional.

Essentially we have different results on different platforms, and some platforms users are forced to configure midi software.

**Comment by fdelapena** [comment]
Related for the soundfonts part: #1322

**Comment by fmatthew5876** [comment]
We can close this as subsumed by recent midi work and issues.
