### ISSUE TITLE
Small UI discrepancies

### ISSUE THREAD

**Issue by CherryDT** [EasyRPG/Player#1443]
Tested on Windows with continous builds.

**Save screen**

- [X] For one frame, all saves seem to be selected at once before the latest one is selected
- [X] The menu jumps instead of scrolling
- [x] ~~The menu allows going from 1 to 15 by going back (and the other way round) while RPG_RT doesn't~~
- [X] The menu is missing the blinking scrolling arrows
- [X] The text of the hero name and stats is not aligned correctly with the save title

**Main menu**

- [ ] When the row is "front", the faces are centered as they were in 2k, although RPG_RT shows them shifted to the left (however, in my personal opinion, centered looks better there anyway)

**Skill screen**

- [X] In the window below the info window (first hero's status), the text is positioned a bit too high

**Equipment screen**

- [x] The arrows from old to new value are not displayed

**Status screen**

- [X] The stats are not aligned - the one's digit for the values for ATK/DEF/etc. should be aligned with the one's digit of HP/MP/EXP (left to the slash)

**Comment by Ghabry** [comment]
just three quick comments, more in a week:

> For one frame, all saves seem to be selected at once before the latest one is selected

One of Sormats commits fixes this

> The menu allows going from 1 to 15 by going back (and the other way round) while RPG_RT doesn't

Imo features that can't break games are fine. :)

> The arrows from old to new value are not displayed

iirc I decided to completely omit them because what is shown depends on the translation of the engine ^^'.

**Comment by fmatthew5876** [comment]
What needs to be done to get back the equipment menu arrows? It's pretty ugly and lacking without them.

**Comment by carstene1ns** [comment]
original issue updated to reflect current development.

**Comment by carstene1ns** [comment]
Can someone confirm, if this has been fixed:
> The arrows from old to new value are not displayed

**Comment by fmatthew5876** [comment]
> 
> 
> Can someone confirm, if this has been fixed:
> 
> > The arrows from old to new value are not displayed

No it hasn't.

@Ghabry Can you enlighten us on whats the roadblock with this one?

It really seems the last piece missing from UI

**Comment by Ghabry** [comment]
The "arrow" used differs based on the engine translation so we decided to simply omit it completely.

Will check the japanese version and report back

**Comment by Ghabry** [comment]
Well English uses > and Japanese 2k uses ->, so doesn't really matter, no big difference.

I like the increased padding in 2k3 compared to 2k but there is a visual glitch in 2k3 @CherryDT , the last char doesn't fit and overlaps with the number :/ (but the > is aligned better)

The solution I would propose is:
1. Use the 2k3 layout because it has better padding
2. Move the left number one to the right
3. After the move the ">" is now as in 2k which is not very symmetric (compared to 2k3 in the screenshot) because there is no gap left. Therefore "->" should look better then.

![aaaaa](https://user-images.githubusercontent.com/1331889/53382212-c7588400-3973-11e9-9234-6c48d6c1640b.png)

**Comment by fmatthew5876** [comment]
So the only thing left here is the front row face position. I agree with Cherry that normal position (what we have now) looks better.

Opinions?

**Comment by fdelapena** [comment]
Because that feature is functional, I think it is better to provide it, despite it may look ugly, because prevents users to access menu and switch between them to see the full front/back distribution.

**Comment by carstene1ns** [comment]
agreed.
