### ISSUE TITLE
Change our comment style to /// @

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1456]
I'm not a fan of javadoc, it takes up too much vertical screen space and makes it harder to read code because you can fit much less of it on your screen.

```c++
/**
 * Gets number of battles.
 *
 * @return number of battles.
 */
  int GetBattleCount();
```

Not only does this comment cost 3 blank lines, it also repeats itself. Writing a title and a `@return` statement in a simple method like this doesn't convey anything useful to the reader. It's also extra labor for the writer.

I would prefer this style:
```
/// @return return number of battles
int GetBattleCount();

/// @return number of battles wins
int GetWinCount();
```

This uses triple slash /// on every line to write a doxygen comment vs a normal comment. It's very concise.

This is a style change, so we would all need to agree.

Other devs, what is your opinion here?

**Comment by Ghabry** [comment]
The redundant explanations are really pretty useless but does this have any advantage over using a "short" java-doc style (/** @return blablabal */)? Is already used at some places.

**Comment by Ghabry** [comment]
After 4 years I will say that this won't get a majority of the dev votes. Interest is too low.
