### ISSUE TITLE
Shaky sprite glitch in airship cutscene

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1458]
I have a cutscene where it boards the airship and moves. During this movement, Player renders the airship sprite in the wrong place on some frames and you see it shake.

This screen gif I recorded is pretty bad, but it shows the shaking sprite.

![hh3-anim](https://user-images.githubusercontent.com/1198466/47539983-f6b19400-d8a0-11e8-81cf-40df87ef16e9.gif)

~~#1401 fixes this problem. But in the code review comments Ghabry was unsure what it was about. So here it is.~~

EDIT: It looks like actually this might be a regression. This bug doesn't exist on the master before #1401. #1401 doesn't actually fix it, the bug (at least in my vehicle case) didn't exist then.

**Comment by Ghabry** [comment]
I never saw this problem before and can't fully follow you: Is this a regression master or in 1401?

**Comment by fmatthew5876** [comment]
This is bug appears in master. This bug does not appear when I build off of commit 4bebc3d6dbbf0e297e04aa8188835a8fb49c66d5.

#1401 is rebased onto 4bebc3d6d which is why I originally thought the PR had fixed it.

Something between 4bebc3d6d and master caused this bug. I have not yet bisected to figure out exactly which one.

I do not know for sure if this is the same issue @Albeleon reported in that one commit of #1401 but it sounds like it.

**Comment by Ghabry** [comment]
uff, will bisect it

**Comment by fmatthew5876** [comment]
I can do it this evening (US time) if you like, since I have the test case in hand to verify it.

**Comment by Ghabry** [comment]
Done bisecting, first bad commit: https://github.com/EasyRPG/Player/commit/b7f307e04f80f847fda8ab3a3b3280d0f7ac85fe

This really fixes a bug: When entering ship or boat they "jump" to the player while entering.
Though it adds this regression while moving :/.
