### ISSUE TITLE
Newly discovered bug

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1461]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
Archive:https://drive.google.com/file/d/1Nw47vNouAK4BvJdmjuWTNHCmXS4Y1K3n/view?usp=drivesdk
Game file:www.mediafire.com/file/up47b3a4u25tnxr/
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
Multiple attacks of multiple games are invalid and only attack once to prevent all abnormal state of the equipment is also invalid to improve resistance. Gain effect skills are also the same gain skill is from Bahamut's physical invalid. Magical reflection and other skills are invalid. Preventing all invalid states from being invalid is Moon Blue 
Improved resistance shield skills are also ineffective

**Comment by Ghabry** [comment]
Please edit your issue or provide in a comment the missing fields: "Name of the Game", "Platform", upload savegames close to the issue and describe what is wrong.

**Comment by s9060666** [comment]
> 請編輯您的問題或在評論中提供缺少的字段：“遊戲名稱”，“平台”，上傳靠近問題的存檔遊戲並描述錯誤。

Edited Original edit failed

**Comment by s9060666** [comment]
> 請編輯您的問題或在評論中提供缺少的字段：“遊戲名稱”，“平台”，上傳靠近問題的存檔遊戲並描述錯誤。

By the way, the character would have moved when attacking, and when it does not use the continuous springboard, it will only jump one space and then stop. Using the props that are out of the maze will cause the movement speed to become extremely slow.

**Comment by s9060666** [comment]
> 請編輯您的問題或在評論中提供缺少的字段：“遊戲名稱”，“平台”，上傳靠近問題的存檔遊戲並描述錯誤。

I hope that these mistakes can be repaired as soon as possible. Otherwise, the boss will not win. I will wait for your refueling.

**Comment by fdelapena** [comment]
Thank you. Battle system is still incomplete, but there are multiple improvements queued, pending to be reviewed (complete list: [78 changes](https://github.com/EasyRPG/Player/pull/1373/commits)) which may fix some of the issues you mentioned.
There is also a checklist of pending features in the following link: [Battle System: Remaining, not implemented stuff](https://github.com/EasyRPG/Player/issues/821).
Also check the complete [list of open issues containing the label Battle](https://github.com/EasyRPG/Player/issues?q=is%3Aissue+is%3Aopen+label%3ABattle).

**Comment by s9060666** [comment]
> 謝謝。戰鬥系統仍然不完整，但有多個改進排隊，等待審查（完整列表：[78個更改](https://github.com/EasyRPG/Player/pull/1373/commits)），這可能會解決您提到的一些問題。
> 在以下鏈接中還有待處理功能的清單：[戰鬥系統：剩餘，未實現的東西](https://github.com/EasyRPG/Player/issues/821)。
> 另請查看[包含Battle標籤的未解決問題](https://github.com/EasyRPG/Player/issues?q=is%3Aopen+label%3ABattle)的完整[列表](https://github.com/EasyRPG/Player/issues?q=is%3Aopen+label%3ABattle)。

There is also a bug that prevents armor and increase defense items skills to function properly

**Comment by s9060666** [comment]
> 請編輯您的問題或在評論中提供缺少的字段：“遊戲名稱”，“平台”，上傳靠近問題的存檔遊戲並描述錯誤。

Game: Moon Blue Legend 2
Life recovery and magic recovery state become the buckle of life and buckle magic

**Comment by fmatthew5876** [comment]
@s9060666 

Could you please test all of these issues again with the latest build. After that, please clearly describe each bug that still exists in Player and preferably provide a saved game with instructions to reproduce the issue. 

The way you did it in #1722 was very good.

If you can do that, I can try to quickly fix all of these.

**Comment by s9060666** [comment]
@fdelapena 
No problem, but I need the latest version of the loading point.

**Comment by Ghabry** [comment]
@s9060666  here is the latest APK: https://ci.easyrpg.org/job/player-android/lastSuccessfulBuild/artifact/builds/android/app/build/outputs/apk/EasyRpgPlayerActivity.apk

I assume that all bugs are fixed.

Not fixed: "Multiple attacks of multiple games are invalid and only attack once". The game uses RPG Maker 2003 and battle improvements are planned for 0.6.2

**Comment by s9060666** [comment]
@Ghabry 
Multiple attacks have been fixed into numbers that are piled together instead of a single attack on the computer version.

**Comment by s9060666** [comment]
@Ghabry 
I am not sure if this has been fixed. This aspect of multiple attacks.
