### ISSUE TITLE
Test if saves created before the LSD fixes are still loadable

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1478]
When attempting to load saves written by EasyRPG Player the newer versions report multiple issues in the old saves, e.g. when loading a Vampires Dawn save I get:

```
Reading Primitive of incorrect size 5 (expected 1) at E39
Warning: Corrupted Chunk 0x3d (size: 5, pos: 0xe39): music_stopping : Read 9 bytes! Reseting...
Warning: Corrupted Chunk 0x22 (size: 1, pos: 0x2ccd): parallax_vert : Read 2 bytes! Reseting...
Warning: Corrupted Chunk 0x23 (size: 1, pos: 0x2cd0): parallax_horz_auto : Read 2 bytes! Reseting...
```

This is all not really critical but we should check, if there are any old savegames that break before pushing new APKs to Android e.g.

**Comment by Ghabry** [comment]
Old savegames will load with incorrect pan, the hero is at the top-left of the screen and the camera won't fix itself until the map is changed.

**Comment by fmatthew5876** [comment]
> Old savegames will load with incorrect pan, the hero is at the top-left of the screen and the camera won't fix itself until the map is changed.

This will only affect save games with non-default panning offsets. The defaults are represented by missing chunks.

**Comment by Ghabry** [comment]
[Save01.zip](https://github.com/EasyRPG/Player/files/2661116/Save01.zip)

This is a save for TestGame-2000 created with Player 0.5.4.
In master it will load with wrong Pan but in RPG_RT it is correct.

**Comment by Ghabry** [comment]
Save05 is an old save and after loading the hero walks veeeery slow.

[Off-saves.zip](https://github.com/EasyRPG/Player/files/2687690/Off-saves.zip)

Save10 is a new save created with master

**But in RPG_RT both saves result in a fast hero**

**Comment by carstene1ns** [comment]
Another broken thing currently with old savegames: player position is messed up.
![standstill girl](https://user-images.githubusercontent.com/4691314/50182262-2f08a800-030f-11e9-84c2-4617074f196a.png)
This has been fixed by #1554.

**Comment by fmatthew5876** [comment]
Ok I understand this now. In that save game we have this:

```
map position_x 3584 (14)
map position_Y 3328 (13)
player_x 23
player_y 20
pan_current_x 0
pan_current_y 0
pan_finish_x 0
pan_finish_y 0
```

In master we recompute the map position from the panning offsets every time. This is wrong. In the PR, we load the map offsets from the save file and respect them.

**Comment by carstene1ns** [comment]
All known cases seem to have been fixed.
