### ISSUE TITLE
[0.5.4] Skills used on ally's appear to ignore INT and ATK influence

### ISSUE THREAD

**Issue by Mike-U5** [EasyRPG/Player#1480]
#### Name of the game:
Probably all of them but I tested "OFF" among others.

#### Player platform:
EasyRPG Player 0.5.4 stable build and the current continuous build for Windows and Android.

#### Describe the issue in detail and how to reproduce it:
Skills used on ally's appear to ignore the caster's Intelligence and Attack influence. This affects the usefulness of healing skills and stat-boosting skills.

For example, healing skills will always heal their "base" amount. The amount they heal will never increase with the player's stats.

It's pretty easy to reproduce. Make a simple healing skill and give it 1 base damage and set it's intelligence rate to 10. It will heal significantly more HP in the RTP depending on your character's INT stat. 
In the EasyRPG Player it'll always just heal 1.

**Comment by Ghabry** [comment]
Thanks for your battle related bug report.
We have many battle bug fixes in our queue. We will tell you when this is possibly solved.

**Comment by fmatthew5876** [comment]
This is fixed now in master.
