### ISSUE TITLE
Abnormal state

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1491]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
www.mediafire.com/file/k0969lkmqqax6hu/
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:Life recovery and magic recovery status in combat have no effect

**Comment by carstene1ns** [comment]
Please do not open multiple issues about the same thing, there is already #1490 open. Closing.

**Comment by s9060666** [comment]
> 請不要打開關於同一件事的多個問題，已經打開了[＃1490](https://github.com/EasyRPG/Player/issues/1490)。關閉。

The last time I paid back was on the big map. The return is in battle. I think the two should be different.

**Comment by carstene1ns** [comment]
You provided the same description and download link. This makes it not easy for us.
