### ISSUE TITLE
Weapon attack attribute is invalid

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1493]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
E.g:
The wand's attack attribute is blow
Some monsters are afraid of these attributes and do not seem to appear in the simulator. For example: the computer version has about 1000 damage with a sword, and there is only 600.700 damage in the simulator.

**Comment by fmatthew5876** [comment]
I tested and weapon elements work now. One thing that's broken with weapons in master is the variance is not applied last. This was fixed in #1573
