### ISSUE TITLE
Item use is abnormal

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1495]
(this is a 0.6 regression)

Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
Items that cannot be used in combat can now be used in combat.
For example: tent
Function: Restore all life and magic, but not in battle.
Resurrection props can only be resurrected, but life can only be 1

For example: Resurrection Dan function: Resurrect the dead player and restore 10 life.
After use, the dead were resurrected.
But life is only 1

**Comment by Ghabry** [comment]
About the tent (帳棚): This is a 0.6 regression.
The item (Medicine) has "Only usable in menu" checked but can be selected in battle. Maybe @fmatthew5876 wants to fix this in the battle pr?

**Comment by Ghabry** [comment]
The other stuff is probably fixed by the battle PR but things like "Resurrection Dan" are lost in translation. I can't find the chinese item.

**Comment by fmatthew5876** [comment]
The only usable in menu thing is now fixed for medicine in #1726

**Comment by s9060666** [comment]
@Ghabry There should be a prop in the inventory. The name is:還魄丹 
But this error should have been fixed

**Comment by Ghabry** [comment]
Can confirm, recover + 10 HP works
