### ISSUE TITLE
Desolate City: The Bloody Dawn (Enhanced Edition) - Bugs

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1500]
The release of this new version on Steam and other distribution platforms is planned for the end of next month.  This version will use a fork of [EasyRPG Player](https://github.com/elsemieni/easyrpg-player-netherware)  (0.5.4 or maybe 0.5.5 <> 0.6), depending.

The game works mostly, but it needs incorporate: **shake screen** and **shake pictures**, as well as **tint screen** and **tint pictures**. [#1263](https://github.com/EasyRPG/Player/issues/1263), [#1219](https://github.com/EasyRPG/Player/issues/1219).

Thanks!

**Comment by Ghabry** [comment]
Shake and Tint should be feasible to implement for pictures.

Flash is a bigger problem: We currently do this as an entire screen operation but to make this work conditionally the flash must be propagated to any individual sprite :/ (as already done for Tone).

**Comment by Br4ssman** [comment]
The scheduled date is for December 20.

We'll see if at least shake and tint are fixed before the release date.
Flash screen is less priority, in this game it's used little.

In any case, thank you very much.

**Comment by fmatthew5876** [comment]
Shake should be fixed by #1548 and tint #1545

**Comment by elsemieni** [comment]
Thanks. I integrated those into https://github.com/elsemieni/easyrpg-player-netherware and seems the 2 pull request works fine. However, those won't fix picture tint with screen. (Out of scope).

Thanks for the all the hard work @fmatthew5876 :)

**Comment by fmatthew5876** [comment]
> However, those won't fix picture tint with screen. (Out of scope).

Can you elaborate on whats the remaining bug here? #1545 is supposed to fix all picture tint problems.

If you meant flash, we have that now too. #1549

**Comment by Ghabry** [comment]
Thanks for testing them all!

**Comment by Ghabry** [comment]
all the linked PRs are in now, closing 👍
