### ISSUE TITLE
Natural healing status is invalid

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1506]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
Rainbow Treasure
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
The recovery status after one round has not recovered.
E.g:
Frightened state
Temptation state

**Comment by fmatthew5876** [comment]
Likely related to #1504

**Comment by Ghabry** [comment]
Imo this needs a test to verify that it is really the issue in #1509.

This could be the game: https://bunfungame.at-ninja.jp/game/Rainbow/RTmain.htm

**Comment by fmatthew5876** [comment]
@s9060666

Thank you for the bug report.

This should be fixed now. Could you test it with a continuous binary to verify?

**Comment by fdelapena** [comment]
Here is the direct link to the continuous build APK file (you need to configure your device to allow installing it from external sources apart of Google Play):

https://ci.easyrpg.org/job/player-android/lastSuccessfulBuild/artifact/builds/android/app/build/outputs/apk/EasyRpgPlayerActivity.apk

Note the MIDI playback may sound different with this special build, it is just for testing purposes.

**Comment by s9060666** [comment]
> @ s9060666
> 
> 謝謝你的錯誤報告。
> 
> 現在應該修復。你能用連續版本來測試嗎？

no problem

**Comment by s9060666** [comment]
> @ s9060666
> 
> 謝謝你的錯誤報告。
> 
> 現在應該修復。你能用連續版本來測試嗎？

No, he has not been fixed

**Comment by fdelapena** [comment]
> The recovery status after one round has not recovered.

This issue looks like the same as #1276, which it is still not fixed. Closing this one as duplicated.

**Comment by fdelapena** [comment]
@s9060666 this issue has been fixed in the continuous build (apk download link above).
