### ISSUE TITLE
CharSet Sprite rendering bug on single screen looping maps

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1510]
Create a 20x15 map which loops vertically. Place an event on the map with a charset sprite.

Play the game walk up until the event is on the top row of the map.

![screen](https://user-images.githubusercontent.com/1198466/49261561-bc439580-f410-11e8-8bc2-8fc108c5c6c1.png)

The left is RPG_RT, right is Player

This bug exists horizontally for wide sprites also.

**Comment by carstene1ns** [comment]
#1216
