### ISSUE TITLE
Makoto Mobius: player character is not visible after loading savegame

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1514]
The game [Makoto Mobius](http://terriball-tl.tumblr.com/post/102600051034/makoto-mobius) has a reproducible issue while loading savegame.

To reproduce, skip intro with fast forward and accept all conversation, then enter the house and talk to the bunny to save. Once saved, load the saved game and the player character will become invisible.

Here's a saved game with the issue: [makoto-mobius-savegame.zip](https://github.com/EasyRPG/liblcf/files/2634978/makoto-mobius-savegame.zip)

Here's another saved game with Player from PR 1502: [makoto-mobius-savegame-pr1502.zip](https://github.com/EasyRPG/Player/files/2636063/makoto-mobius-savegame-pr1502.zip)

Currently, Player does not log when a savegame is saved or loaded, this would be nice to understand better what users are sending via bug reports.

**Comment by Ghabry** [comment]
> "Currently, Player does not log when a savegame is saved or loaded, this would be nice to understand better what users are sending via bug reports."

We log this.

**Comment by fdelapena** [comment]
This issue also affected Desert Nightmare game and the fix worked properly for the same case.
