### ISSUE TITLE
tdf2018wildcompodemo: interpreter hangs or skips all map sequences

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1517]
#### Name of the game:
It does not contain a game title, but the project name on GitHub and in the readme file is tdf2018wildcompodemo.

#### Player platform:
Any, probably...

#### Attach files (as a .zip archive or link them)
Not needed

#### Describe the issue in detail and how to reproduce it:
This amazing demo ([live video](https://twitter.com/njHvYnA6vIU9vkV/status/1068810920795635713)) has been created by @katai5plate and the scripted full source code (MIT licensed) is available at [katai5plate/tdf2018wildcompodemo](https://github.com/katai5plate/tdf2018wildcompodemo) on GitHub.

It hangs in the first scene after less than 40 seconds at normal speed.
An online version has been uploaded for convenience to the web player: [stable](https://easyrpg.org/play/?game=tdf2018wildcompodemo), [master](https://easyrpg.org/play/master/?game=tdf2018wildcompodemo).

Some few BMPs have been converted to PNG, these have been recompressed with zopfli and MP3 music converted to 24 kbps Opus for faster async download.

Additionally to this hang, player shows a warning instead of a debug message due to the empty title (it could be considered as a bug, as RPG_RT ignores this).

**Comment by Ghabry** [comment]
guess fixing this will be complete luck as part of a different issue.

**Comment by Ghabry** [comment]
Longer tweet containing more of the tech demo: https://twitter.com/kaiware007/status/1068810114923036672

**Comment by fdelapena** [comment]
Player behaves different in Emscripten compared with desktop Player. In desktop builds, it fastly skips all maps and runs the last sequence and ends the demo in few seconds, so it seems to be related with timing, as Ghabry points the demo is orchestrated by timers, which helps to keep it on sync with music playback.

**Comment by Ghabry** [comment]
We have a few documented cases where emscripten will behave different but this sound like the first case of a bug where the webplayer executes something different compared to desktop player o.O

**Comment by Ghabry** [comment]
oh the Tick is really Midi play location. hmmmpf.

**Comment by fdelapena** [comment]
Working demo: https://easyrpg.org/play/pr1523/?game=tdf2018wildcompodemo :tada:
