### ISSUE TITLE
Android: Update SDLActivity for SDL 2.0.9

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1518]
Before releasing 0.6 (likely) we should update SDL2 on Android to the latest Version to fix problems like "crashes on startup" which are not under our control.

**Comment by Ghabry** [comment]
Updated the Java files to SDL 2.0.9 (Untested): https://github.com/Ghabry/easyrpg-player/tree/android-sdl-209

The biggest problem will be probably libhidapi.so: https://bugzilla.libsdl.org/show_bug.cgi?id=4316
There is no documentation how to build this ^^'

**Comment by carstene1ns** [comment]
You did not disable touch input. :see_no_evil:

**Comment by Ghabry** [comment]
In Theory not attaching the TouchListener should be enough but I'm not 100% sure ^^' (also don't know why Touch is a listener but this Gyro-stuff we disabled is just a virtual function... what an API design).
