### ISSUE TITLE
What is SaveScreen::pan_x and pan_y?

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1521]
These fields are unused by `Player`.

They are written by `RPG_RT` to lsd save games. We always write 0, but from my limited testing `RPG_RT` doesn't seem to mind when loading our saves.

This needs further testing to discover it's purpose and how to emulate it for save games.

**Comment by fmatthew5876** [comment]
@CherryDT 

Do you know if these are used for anything? I've only emulated how they increment and save them to LSD. Maybe we are missing some RPG_RT feature that uses this?

**Comment by CherryDT** [comment]
They are the origin for "tiled" battle animations and weather particles.
The value is in 16th pixels and is moved together with the map but always with a `mod N` operation at the end, where `N` is `320 * 16` for `pan_x` and `160 * 16` (*not* `240 * 16`!) for `pan_y`.

They are required to ensure that the display of tiled battle animations and weather particles move smoothly and their relative position is remembered.

**Comment by fmatthew5876** [comment]
@carstene1ns 

We should re-open this issue and investigate animations and weather effects. I've only written the code to correctly set these values but we don't use them anywhere.

**Comment by fmatthew5876** [comment]
So you can see the effect of this pretty obviously with snow.

Cause snow level 3, and then simply walk up. In RPG_RT the snow will still fall. In player it'll appear to float in place.

**Comment by fmatthew5876** [comment]
This was applied to battle animations. It's still not applied to weather, but that's now captured in #2005
