### ISSUE TITLE
Composite japanese characters cause files to be not found

### ISSUE THREAD

**Issue by SmiVan** [EasyRPG/Player#1530]
Experiencing a bug related to encoding problems with japanese characters with filenames in Yume2kki:

***
#### Player platform:
macOS 10.13.6

#### Locale:
`ru_RU.UTF-8`

#### Save File and Log
[save-and-log.zip](https://github.com/EasyRPG/Player/files/2651405/save-and-log.zip)

#### Steps to reproduce:
Navigate to track No. 003 D in the PC music player.
***

In particular, the Player claims to not be able to find 夢オルゴールFC.

Interestingly enough, [grepping the music folder](https://pastebin.com/puBHLCUj) has shown that the track does not indeed exist under that name, but exists under the name 夢オルゴールFC instead.

Looks similar right?

Hence I have further copy/pasted the correct and the wrong name into text files and ran xxd against both of them producing:
```
$ xxd correct.txt
00000000: e5a4 a2e3 82aa e383 abe3 82b3 e382 99e3  ................
00000010: 83bc e383 ab46 430a                      .....FC.
```
```
$ xxd wrong.txt
00000000: e5a4 a2e3 82aa e383 abe3 82b4 e383 bce3  ................
00000010: 83ab 4643 0a                             ..FC.
```
which are clearly different.
```
wrong: e5a4a2e382aae383ab e382b4        e383bce383ab46430a
right: e5a4a2e382aae383ab e382b3 e38299 e383bce383ab46430a
```
In particular the difference is in the ゴ character as shown by [grepping the music folder](https://pastebin.com/puBHLCUj).

Potentially related issues are #1383 and #839

**Comment by fmatthew5876** [comment]
Relevant info about APFS:
https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/APFS_Guide/FAQ/FAQ.html
https://mjtsai.com/blog/2017/03/24/apfss-bag-of-bytes-filenames/

One possibility is that the filename on the filesystem is in native cp 932 encoding but our filenames are in utf8.

**Comment by SmiVan** [comment]
As revealed by @fdelapena on IRC, the difference is in the filename the character is recorded as [コ + ゙ ](https://r12a.github.io/uniview/?charlist=%E3%82%B3%E3%82%99) while the file finder expects it to be [ゴ](https://r12a.github.io/uniview/?charlist=%E3%82%B4).

**Comment by fmatthew5876** [comment]
There is a patch in #839. That solution involves a change to `ReaderUtil` in `liblcf`, and the changing filefinder to use it in `Player`.

**Comment by fmatthew5876** [comment]
In the patch Ghabry does
`const Normalizer2* norm = icu::Normalizer2::getNFKCInstance(err);`

But this might not be right. There is NFD, NFC, NKFC, and NKFD.

https://stackoverflow.com/questions/7931204/what-is-normalized-utf-8-all-about

In this example, the longer string is the one on the file system. For that I think we would need NFD or NKFD?

How can we know what format is used on disk? Might we have to try them all in `FileFinder::openUTF8()`?

**Comment by SmiVan** [comment]
> In this example, the longer string is the one on the file system. For that I think we would need NFD or NKFD?
> 
> How can we know what format is used on disk? This looks like NFD/NFKD but others could be NFC/NFKC?

I've implemented the fix using NFKC, and it works just fine on macOS, so I guess this isn't a problem and we don't need to guess the format. 

This still needs to be verified that it works on non macOS platforms though.
