### ISSUE TITLE
Panoramas are not pixel perfect

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1534]
![parallax](https://user-images.githubusercontent.com/1198466/49627840-14e5d600-f9af-11e8-8661-10026ea9e166.png)

Left: RPG_RT, Right: Player

Look at the lower right corner. In RPG_RT you can see 2 stars, one of which is halfway obscured by the glass tile. On the right, you see only 1 star.

This issue  was produced by creating a 41x31 map and setting the panorama to Cosmos1 with no scrolling.

**Comment by carstene1ns** [comment]
I remember the same thing years ago in wulfhammer. In the creator room there was also some moon background that behaved wrong. I think this got fixed along with yume nikki back then,there might be some closed issue about.

**Comment by Ghabry** [comment]
Do you mean "jumping panorama" when crossing a map-loop border?
Can't remember the issue either tough.

**Comment by fmatthew5876** [comment]
Nothing jumps, its just a big picture on a big map that is slightly off in how it scales when you walk around. If you weren't paying attention you wouldn't even notice it.

Probably a minor rounding or interpolation issue in our panorama code.

**Comment by carstene1ns** [comment]
Is #961, unfortunately images and video offline, however when loading the game, you will know why I mentioned it ;)
https://easyrpg.org/play/master/?game=embric&start-map-id=89&start-party=1&start-position=40%2060

**Comment by fmatthew5876** [comment]
Panoramas also have incorrect starting offset for looping maps.

![pano](https://user-images.githubusercontent.com/1198466/49704755-1993cf80-fbe5-11e8-8c4c-9d2e4dea3832.png)

This is the same 41x31 map, set to loop on both dimensions.

**Comment by fmatthew5876** [comment]
Regarding the second issue:

When the map loops horizontal or vertical. 

When you enter the map the panorama gets fixed in the looping dimensions. The position of the panorama is different depending on which place you start on the map, but it doesn't change after that.

Walk far away, then save your game. If you load your game, the panorama stays in it's position. If you change the new game position to the same tile as the save game and start a new game, the panorama offset is different than your loaded game.

This means the save game data must be storing some way to get the panorama offsets for looping maps. Maybe `SaveScreen::pan_` ...?

**Comment by fmatthew5876** [comment]
Here are what the starting positions are in RPG_RT

Map (41,31) Start at (30,23)

![pan_start](https://user-images.githubusercontent.com/1198466/49706413-ca08d000-fbf3-11e8-83a7-1da609b8a074.png)

* Upper Left: no loop
* Upper right: horiz loop
* Lower left: vert loop
* Lower right: both loop

**Comment by fmatthew5876** [comment]
@CherryDT

Another `RPG_RT` bug for you.

**Comment by CherryDT** [comment]
Hm but this is simply a non-saved panorama position, and the panorama object is initialized to 0, 0 (otherwise only gets changed when switching maps). So if I get this right, it's what was fixed in RM2k3E (https://github.com/EasyRPG/Player/pull/1485)

**Comment by fmatthew5876** [comment]
I'll check the behavior on rm2k3e. I thought it was only for scrolling panorama but maybe it applies here too.

**Comment by fmatthew5876** [comment]
Reopening this until I verify save data in rm2k3e

**Comment by fmatthew5876** [comment]
rm2k3e correctly loads the pan position for looping map. Actually it looks like rm2k3e uses the pan variables for everything, even on non-looping maps it writes out the chunks.

Guess its time to refactor panorama again...
