### ISSUE TITLE
OpenSaveMenu waits for movement

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1559]
Create the following autostart event:

```
Move Player: Right, Repeat
OpenSaveMenu
```

In `RPG_RT`, the save menu will popup every frame. In `Player`, the player will take a full step, and then the save menu will appear.

**Comment by Ghabry** [comment]
https://github.com/EasyRPG/Player/pull/1401/commits/a9e47008466ff749574539974d32da50841e336e

**Comment by fmatthew5876** [comment]
Looks like we have a good test case.

**Comment by Ghabry** [comment]
though this patch is not really acceptable because it adds more to Game_Temp
