### ISSUE TITLE
Battle 2k3: Flip assets if facing the other direction option 

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1564]
Flips the assets automatically to the enemy when attacking instead of always facing to the left.

btw, which Chunk is this?

![system2](https://cloud.githubusercontent.com/assets/1331889/13790818/7e3e5982-eaea-11e5-8f3c-38f8781060b7.png)

**Comment by fmatthew5876** [comment]
Do we already know the complete set of sprites that this affects? Or do we need to test for it?

**Comment by Ghabry** [comment]
This affects all Sprite_Battlers, static Monsters and Animation2 animations.


Not sure:

if BattleAnimation battlers (the alternative to Animation2) are also mirrored.

if attack battle animations on the target are mirrored.

**Comment by fmatthew5876** [comment]
I tried playing with this and it doesn't appear to do anything.

I tried normal battles and surprise battles, the flag didn't have any effect. The RM2k3e help file labels it but doesn't say what it does.

What is this supposed to do?
