### ISSUE TITLE
Automatic event processing from past map continues if you load a new savefile from event command.

### ISSUE THREAD

**Issue by elsemieni** [EasyRPG/Player#1565]
When loading a savefile from command, running events from original map (before load) don't stop processing, cointinuing in the new map in the new "scene".

#### Player:
Tested in 0.5.4 and Nightly build (to Dec 13th).

#### Testcase:
An RPG Maker 2003 1.12a project. 
https://drive.google.com/file/d/1Uu-TJriFOgJ6wrHViKbze8re3wLqvKjP/view?usp=sharing

The testcase consist in 2 maps and one savefile. 
When you start the game, you will start in Map A with an automatic event that makes a beep sound each second until 10 and then it repeats, and a parallel event that wait 3 seconds before calling Load Savefile command.

When you load the savefile, you will end in Map B, with no events at all.

- In RPG_RT the automatic event will stop instantly.
- In Player, the automatic event will continue to process, and making beeps each second.

**Comment by fmatthew5876** [comment]
Thank you for the bug report, this is great find.

This is another reason we need to move off of globals and use RAII. With automatic cleanup, bugs like this become impossible to write.

**Comment by fmatthew5876** [comment]
This bug seems to only affect autostart events.

I tried adding this parallel event:
```
Tint Red 4.0s Wait
Tint Green 4.0s Wait
Tint Blue 4.0s Wait
```

After loading the game, the tint commands did not continue.

I changed the sound beep event from Auto start to OnAction and then talked to it with the player. The beeping did not continue.

**Comment by Ghabry** [comment]
The ability of RPG Maker 2k3 to Load anywhere and skip the title scene really caused many problems
