### ISSUE TITLE
Pictures won't load when loading savefile in a project with title screen disabled. 

### ISSUE THREAD

**Issue by elsemieni** [EasyRPG/Player#1571]
When you have a RM2k3 >=1.10 project without Ttitle screen enabled in database, when you try to load a savefile with pictures in game, these won't are being loaded (and didn't shown in screen). However, if you enable Title Screen in Database editor, the images are shown without issue. 

#### Player platform:
Tested in 0.5.4 and Master (Dec 15th). 

#### Test case
Here's a test case: 
[imgBug.zip](https://github.com/EasyRPG/Player/files/2683010/imgBug.zip)

Web: https://easyrpg.org/play/master/?game=issue-1571&engine=rpg2k3e  (ignore the missing FaceSets)

 A RM2k3 1.12a project with title screen disabled. It goes directly to a almost empty map with a automatic event that shows a dummy image, then it deletes itself, and a helper event for save/load calling. 

- Save the current progress (with debug features or with the helper event).
- Then load the savefile. 

#### Expected behaviour (RPG_RT 1.12a):
The dummy image is being shown when the map loads.

#### Current behaviour (Player 0.5.4 , Master):
No image is shown.

Talking with @fdelapena , maybe this bug can be related with https://github.com/EasyRPG/Player/issues/1524

**Comment by fmatthew5876** [comment]
This might also explain the missing background in the Razas demo savegame from #1498

**Comment by Ghabry** [comment]
And another test case for the web, thx 👍

**Comment by fmatthew5876** [comment]
The whole business about a missing title screen is a red herring. This is broken everywhere.
