### ISSUE TITLE
Removing all heroes the "remaining" invisible hero has a tile graphic

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1574]
**Tested in**: Player 0.5.4 (continuous).
**How to reproduce it**: Create a new map and a parallel process event which remove all heroes from the party.

**Test case**:
[Removing whole party](https://app.box.com/s/if1ho5lgsyxcltc4k3j33iw1dgnuyyyr)

Web: https://easyrpg.org/play/master/?game=issue-1574

**Comment by Ghabry** [comment]
Added a web player test case (link in main comment)

**Comment by Ghabry** [comment]
I bet this was caused by "Simplify GetTileId()" 804666d
