### ISSUE TITLE
Pictures being affected with flash disappears when apply flash.

### ISSUE THREAD

**Issue by elsemieni** [EasyRPG/Player#1575]
When you have a picture with "being affected by flash" activated, and you put a flash event on it, the image will dissapear in almost all conditions. However, there's a corner case that behaivour didn't happened.

Also there's a strange behaivour, that when it flashes, one can see the "picture shape", so I can conclude the image is not deleted, but not being shown in some way.

**This bug happens in:**
EasyRPG Player Nightly (as Dec 16th).
(Doesn't happen in EasyRPG Player 0.5.4 since "being affected by flash" wasn't implemented yet).

**Test case:**
I've made a test case, as follows:
https://drive.google.com/file/d/1CYas3dx7ZGVWyOcW8sTsjaKo7aBZzg4h/view?usp=sharing

![image](https://user-images.githubusercontent.com/1494687/50062554-7879bb80-0186-11e9-9d0b-910f829f57a7.png)

**The test case is the upper side of the map, labeled "1"** (\*)

Web: https://easyrpg.org/play/master/?game=issue-1575&engine=rpg2k3e

2 rows of events.
The first row tests a dummy image being affected by blink effect.
The second row tests a special case image being affected by blink effect. This is the only image I've fond it reacts different to this test case.

Each event shows the image in 3 seconds, then the screen flashes three times each second, then the image is being deleted. 

For each row there's 3 events:
- One with being affected by flash events activated, with transparent colour activated. 
- One with being affected by flash events activated, with transparent colour disabled.
- One with being affected by flash events disabled.

The section numered 2 in the map is for another related issue, you can ignore this for now (*)

**Expected behaivour (RPG_RT 1.12a):**

**Normal case:**
A: Image being affected by blink.
B: Image being affected by blink.
C: Image don't being affected by blink.

**Special case (\*\*):**
A: Image being affected by blink.
B: Image being affected by blink.
C: Image don't being affected by blink.

**Current behaivour:**

**Normal case:**
A: Image dissapears at blink. (WRONG)
B: Image dissapears at blink. (WRONG)
C: Image don't being affected by blink. (OK)

**Special case (\*\*):**
A: Image being affected by blink. (OK)
B: Image dissapears at blink. (WRONG)
C: Image don't being affected by blink. (OK) 

(\*) When I was making this test case I've discovered another bug affecting the test case: #1576 
(**) For testing case A and B in special case, you must show a different image fist. This is beacuse another bug, describered in (\*). 

Might be related with #1362

**Comment by Ghabry** [comment]
Thanks the test case is now availabe via web player. Added to the 1575 and 1576 main posts.

**Comment by fmatthew5876** [comment]
This bug shows up in the development version of HH3. It breaks my D&D spellbook cms.

![spell](https://user-images.githubusercontent.com/1198466/50380301-152dd480-0631-11e9-9ba1-303a10a21828.gif)

**Comment by fmatthew5876** [comment]
The bug seems to be triggered if the image doesn't have any transparent pixel. From either the original image not having any, or the `use_transparent_color` flag set to false.
