### ISSUE TITLE
Many load game picture bugs - Razas Demo

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1582]
I'll let the pictures explain this one.. Everything is broken. 

RPG_RT:
![razas-rpg](https://user-images.githubusercontent.com/1198466/50124899-9140aa80-0234-11e9-9aef-607736ceb8ae.gif)

Player:
![razas-player](https://user-images.githubusercontent.com/1198466/50124905-956cc800-0234-11e9-9883-8006d2c97160.gif)

https://www.indiedb.com/games/razas/news/check-our-razas-public-demo

[Save13.zip](https://github.com/EasyRPG/Player/files/2688392/Save13.zip)

There are a lot of local state variables in `Game_Picture` that we use instead of LSD data, so we can call pictures nearly unimplemented. This is a good picture load game test case.

**Comment by Ghabry** [comment]
> There are a lot of local state variables in Game_Picture that we use instead of LSD data,
> so we can call pictures nearly unimplemented.

Hm? Which ones do you want to remove?
We almost only operate on "data", almost all local state vars are necessary:

```
int id <- duplicate of the pic ID
std::unique_ptr<Sprite> sprite;  <- Renders picture or sprite to screen
BitmapRef whole_bitmap; <- contains the picture
BitmapRef sheet_bitmap; <- contains the spritesheet bitmap
int last_spritesheet_frame = 0; <- Spritesheet optimisation
FileRequestBinding file_id; <- Web Player

int old_map_x; <- Maybe can be removed with some cleverness (used for calulating the offset when picture has "fixed_to_map" attribute
int old_map_y; <- Maybe can be removed with some cleverness (used for calulating the offset when picture has "fixed_to_map" attribute
```

**Comment by fmatthew5876** [comment]
I was looking at `Params` and `ShowParams`, but they are just used for setup so I was mistaken about that. Still, given the pictures we have a lot to fix.

**Comment by Ghabry** [comment]
Based on the gif this looks as if half of the pictures are not affected by shake? (assuming this is a shake effect)

**Comment by fmatthew5876** [comment]
What I can see

* Initial move and zoom in doesn't happen
* Only clouds shake
* Sine wave transparent mist does not appear

**Comment by fmatthew5876** [comment]
I haven't checked, but some of this could be due to not properly loading wait event commands from #757

**Comment by Ghabry** [comment]
@fmatthew5876   didn't you fix this?

**Comment by fmatthew5876** [comment]
I haven't looked into this at all since reporting it

**Comment by fmatthew5876** [comment]
This is fixed now in master after all the picture save game fixes went in.
