### ISSUE TITLE
Events with Spin restart their animation when write any command and interact with it

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1585]
**Tested in** : Player 0.5.4 (continuous).
**How to reproduce it**: Create a new event with animation type "Spin" and write any command in it.
**Platform**: Windows 7 (x64)

**Test case**:
[Restart spin](https://github.com/EasyRPG/Player/files/2820060/TestCase.-.Event-Spin.zip)

**Comment by fmatthew5876** [comment]
This should now be fixed by #1601

**Comment by Ghabry** [comment]
@Br4ssman could you pls confirm that this issue is indeed fixed by https://ci.easyrpg.org/view/Pull%20Requests/job/player-win32-pr/2560/ ?

**Comment by Br4ssman** [comment]
@Ghabry It works!
