### ISSUE TITLE
Lakria Legends: Movement hangs on the ramp

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1593]
via Android bug reporting.

#### Name of the game: [Lakria Legends](https://rpgmaker.net/games/5562/downloads/9559/)  
Yet another REFMAP RPG

#### Describe the issue in detail and how to reproduce it:

Start with ``--new-game --start-map-id 18 --start-position 17 5``

Walk on the ramp and the game will get stuck in an endless movement uphill/downhill loop.

Quick event analysis:

Start conditions are "event touch"

```
Top ramp event: (disabled when Going Up = ON)
@> Set Move Route: Player, Turn Right
@> Control Switches: [0032:Going Down] = ON
@> Set Move Route: Player, Move Bottom Right, Move Bottom Right
@> Control Switches: [0032:Going Down] = OFF

Bottom ramp event: (disabled when Going Down = ON)
@> Set Move Route: Player, Turn Left
@> Control Switches: [0031:Going Up] = ON
@> Set Move Route: Player, Move Upper Left, Move Left
@> Control Switches: [0031:Going Up] = OFF
```

The switch toggling is obviously a red hering, the switch is already OFF again when the movement starts. Can be deleted, result is the same.

Basicly the other ramp event is touched while moving and this triggers the downwards movement.

We already ignore "Player touch" events when a move route is active (matches RPG_RT), maybe the same must be done for "Event touch"? Needs testing. (Changing the events from Event to Player touch fixes it in Player).

Note: Event Touch is CheckCollisionEvent() in Game_Player

**Comment by Ghabry** [comment]
another good test for #1628  @fmatthew5876

**Comment by fmatthew5876** [comment]
It is definitely the case that `collision` trigger does not occur when a move route is active on the player.

**Comment by Ghabry** [comment]
also fixed by #1601
well that one was simple

**Comment by fmatthew5876** [comment]
That is surprising. I expected this one to need trigger changes from #1628

**Comment by Ghabry** [comment]
hmm indeed. I redownloaded the CI build to be sure. Is indeed 1601 o.O
