### ISSUE TITLE
Filefinder: Should emit a warning when multiple folders map to the same normalization

### ISSUE THREAD

**Issue by talib1101** [EasyRPG/Player#1594]
#### Name of the game:
ゆめ２っき  (Yume 2kki)

#### Player platform:
Ubuntu 18.10 64-bit

#### Log file:
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/2709849/easyrpg_log.txt)

#### How to reproduce it:
Start new game or load save (Occurs in new and saved games)

#### What Happens:
Much of the game's music does not play. A notable example is the error
Debug: Cannot find: Music/zaza (!)
because zaza plays whenever entering the dream world (which can be done by sleeping in the bed)
Another good example is ym2-00_ano which should play with new games at intro
Debug: Cannot find: Music/ym2-00_ano deskwork (!)
Debug: Music not found: ym2-00_ano deskwork

#### Notes:
I have verified that I do have the file zaza.
I've tested it with the version at https://drive.google.com/open?id=1nkGMdjg1PDF89Le7mnMmsTLhoO-RJMsg
and the version at https://wikiwiki.jp/yumenikki-g3/

**Comment by Ghabry** [comment]
Based on chat discussion the least-complex solution which has no huge performance penalty to handle this corner case is emitting a warning when this happens. When there are not too many games affected by this this is good enough imo.

**Comment by talib1101** [comment]
> Can you please merge both Music directories and the error should be gone. The uppercase folder comes from the included RTP.

Thanks for the timely and helpful response. I can confirm that merging the contents of both folders into 'music' and deleting 'Music' fixed the issue. It would have been good if an error message popped up on screen like when files are missing, or if the issue never occurred because it was handled automatically.

**Comment by carstene1ns** [comment]
Here is a preliminary patch:
```patch
diff --git a/src/filefinder.cpp b/src/filefinder.cpp
index 1f0b6f74..54acc8b9 100644
--- a/src/filefinder.cpp
+++ b/src/filefinder.cpp
@@ -22,6 +22,7 @@
 #include <cstdlib>
 #include <cstring>
 #include <algorithm>
+#include <unordered_set>
 #include <fstream>
 #include <string>
 #include <vector>
@@ -717,6 +718,7 @@ FileFinder::Directory FileFinder::GetDirectoryMembers(const std::string& path, F
 	assert(FileFinder::IsDirectory(path));
 
 	Directory result;
+	std::unordered_set<std::string> found_dirs;
 
 	result.base = path;
 
@@ -805,6 +807,13 @@ FileFinder::Directory FileFinder::GetDirectoryMembers(const std::string& path, F
 		}
 		if (is_directory) {
 			result.directories[Utils::LowerCase(name)] = name;
+
+			auto search_dir = found_dirs.find(Utils::LowerCase(name));
+			if (search_dir != found_dirs.end()) {
+				Output::Warning("Duplicated directory \"%s\", this can lead to file not found errors.", name.c_str());
+			} else {
+				found_dirs.insert(Utils::LowerCase(name));
+			}
 		} else {
 			result.files[Utils::LowerCase(name)] = name;
 		}
```
Patch problems:
- displays the message twice upon game load
- displays message when game list is read from game browser
