### ISSUE TITLE
Grimps: Squeaking of the Dead: Bombs don't explode

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1595]
#### Name of the game:

Grimps: Squeaking of the Dead: Bombs don't explode

https://rpgmaker.net/games/10802/

#### Describe the issue in detail and how to reproduce it:

Load map ID 4 and push the bomb at the bottom right upwards. The bomb will move but not explode.

Seems to be some timing problem with move routes resulting in a wrong screen coordinate.
The check on Page 3 of Event 9 (the bomb) fails because Var 24 contains the wrong value.

**Comment by Ghabry** [comment]
tested against 1628 with 28 commits: not fixed (Yet)

**Comment by fmatthew5876** [comment]
Is it a touch or collision event? I haven't attempted collision yet

**Comment by Ghabry** [comment]
it starts with a hero touch which works, the problem is as stated "Seems to be some timing problem with move routes resulting in a wrong screen coordinate."

**Comment by fmatthew5876** [comment]
This is fixed by #1628
