### ISSUE TITLE
Incorrect processing input number

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1598]
**Tested in** : Player 0.5.4 (continuous).

**How to reproduce it**: An event in parallel process will process the input of digits (in my case 6), then, different conditional branches will check the entered digits.

In the end, if none of the entered digits is correct, it will show the message "Incorrect code".

The result in Player is "Incorrect code" even though it is one of the values ​​recognized in the conditional branch. After this it shows the correct code message.

**Platform**: Windows 7 (x64)

**Video**: https://youtu.be/0yEUY_ZJ1r4

**Log**: [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/2723477/easyrpg_log.txt)

**Test case**: [Digits Fail.zip](https://github.com/EasyRPG/Player/files/2723481/Digitis.Fail.zip)

**Codes**: 
851942: Code A correct!
                 741328: Code B correct!
                 901883: Code C correct!
                 45013:   Code D correct!
                 14510:   Code E correct!
          @>
         : Else
              Incorrect code.

**Comment by elsemieni** [comment]
When the game boots (no matters if it have title screen or not) and the parallel event executes, this is the behaivour:

- Buzzer sound plays (but no "incorrect code" message is shown).
- Input number is shown.

If you enter a correct code (A), this will happen:

- Message: Incorrect code (no buzzer sound).
- Chimes sound (but not "Code A correct" message is shown).

Then if after that I enter a B correct code, this will happen:

- Message: Code A correct (no chime sound). 
- Chimes sound.

Then if after that I enter an incorrect code, this will happen:

- Message: Code B correct (no chime sound). 
- Buzzer sound (no "incorrect code message" shown).

So following that logic, the next iteration will be "Incorrect code" string and the sound of the current code, without message. Sounds like there's something wrong at comparsion-checking time...

---

Talking with @Br4ssman we figured that a workaround for this is: After input number processing, put a message with "\^" (to skip the message instantly).

**Comment by Ghabry** [comment]
Based on this behaviour I would say that the our handling for message waiting is incorrect when no message command is used.
Though this only happens for Input Number, Choise works properly.
