### ISSUE TITLE
Show screen command with transitions inside maps bug

### ISSUE THREAD

**Issue by gadesx** [EasyRPG/Player#1600]
---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows 7 64bits

#### Attach files (as a .zip archive or link them)
https://www.mediafire.com/file/hirkr2k7na4617c/testcase_transition_bug.zip/file

#### Describe the issue in detail and how to reproduce it:
After run the game, there's a "Show screen" command,
RPG_RT ignores it because the map already its visible on screen,
but player think not and make the transition effect.

**Comment by fmatthew5876** [comment]
I believe this is actually the same as #1445.

It's a visual bug, not a logic bug. When you do show screen, it only transitions the previous frame to the next. Normally this means black to the map. But in this case the previous and next frames are the same, so the transition does nothing.

If you look carefully, you'll notice that despite no visual effect, the show screen still delays everything by some amount of frames.
