### ISSUE TITLE
破滅傳說2-闇界野心: Hang after using 加速

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1610]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
The character will stop when the character is fighting.
The enemy will not attack or act

**Comment by Ghabry** [comment]
This one must be fixed. After using 加速 the battle hangs.


Note: Extract and play with codepage 950.
