### ISSUE TITLE
Event jump misbehaves with other events using the same priority

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1612]
Reported by BitBrosGames in a [forum post](https://community.easyrpg.org/t/monigote-fantasy-several-issues/638):

> In RPG Maker, three events can freely move over the same tile as long as their priorities are different. I mean, a character can walk over some event whose priority is “under the character”, and, let’s say, a bird on the “above character” layer can fly over said character. However, two characters can’t naturally occupy the same tile, in the same way as two “birds” couldn’t do so. This is implemented correctly in EasyRPG when it comes to walking, but it’s not when JUMPING.

[Example.zip](https://github.com/EasyRPG/Player/files/2819236/Example.zip)

**Comment by fmatthew5876** [comment]
This is fixed in #1628
