### ISSUE TITLE
 Scene with automatic event skippable by keypress should also end after some seconds

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1613]
Reported by BitBrosGames in a [forum post](https://community.easyrpg.org/t/monigote-fantasy-several-issues/638):

> This is a bit tricky to explain, so maybe it’s better if you [open the project yourselves and take a look](https://github.com/EasyRPG/Player/files/2819236/Example.zip). It’s about the autorun event that runs at the beginning of the example. 
With RPG Maker you can skip the scene by pressing <kbd>Enter</kbd> or just wait 3 seconds for the picture to disappear, while with EasyRPG you always need to push <kbd>Enter</kbd> to carry on. I think it must be some kind of problem with the key input processing method. 
But this one is particularly weird, because if you simply add a message instruction into the event, it’ll stop working that way in RPG Maker. (??) 
(The message in the log is “`Event exceeded execution limit`”)

**Comment by fmatthew5876** [comment]
Fixed by #1718

**Comment by fmatthew5876** [comment]
This is actually fixed by #1713 !

It appears that the 2 events are so perfectly timed that the 2nd event changes the variable right after KeyInputProc but before the conditional branch.

So this is one example where `loop_count` is used precisely.
