### ISSUE TITLE
2k3 Status window strings are wrong

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1616]
In the Actor pane of the rm2k3 status window:

In Steam rm2k3e RPG_RT we have:
* Name
* Class
* Nickname
* State

In Player we have:
* Name
* Profession ❗️ 
* Title ❗️ 
* Status ❗️ 

These strings appear hard coded so I didn't want to go ahead and fix it just yet. How is this handled for different languages?

I made this an issue because I actually like our names better, so I'm a bit conflicted about what to do here.

**Comment by Ghabry** [comment]
Guess ours are based on the translation of RPG advocate because this translation happened years before the official.
