### ISSUE TITLE
Menu face is rendered above cursor

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1617]
Open the menu in a 2k3 game and move an actor the back row. Then use the row command again and select the actor.

In both RPG_RT and Player, the cursor and the actors face overlap. In RPG_RT, the cursor is above the face, but in Player the face is above the cursor.

I made an issue instead of just fixing this because its more complicated. Our entire window class heirarchy is setup the render the cursor before the contents. To fix this, somehow we would need to render the faces before cursor, meaning we need to refactor the window classes somehow.

This is such a minor visual glitch, I'm not even sure its worth it.

![cursorface](https://user-images.githubusercontent.com/1198466/52170919-4bc33880-2721-11e9-8025-6a8970201ea8.png)
Left: RPG_RT, Right: Player

**Comment by Ghabry** [comment]
a hacky solution involves overloading Draw and rendering the left part of the cursor again.

A refactor is not worth for this.

**Comment by rueter37** [comment]
I checked this again in RPG_RT and came to the conclusion that if an actor is set in the back row, the right edge of the face icon touches the left edge of the cursor so that we have no overlap there. In #2361 this case is handled now by rearranging the face icons in RPG Maker 2003.
