### ISSUE TITLE
Teleport Test Cases

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1624]
Parallel events are processed in the middle of teleporting

Setup this parallel common event

```
OpenSaveMenu
Teleport other map
OpenSaveMenu
Loop:
  Wait 0.0s
```

In RPG_RT, it will save, transition out, teleport, transition in, and save again

In Player, it will save, transition out, save :exclamation: , teleport, transition in

This bug occurs with parallel common events and parallel map events.

It does not occur with autostart common, autostart map, or triggered map events.

**Comment by fmatthew5876** [comment]
Here is something even more strange

```
OpenSaveMenu
Teleport other map
OpenSaveMenu
OpenSaveMenu
```

In RPG_RT, it will save, transition in, teleport, transition out, save

In other words, despite 3 open save menu commands, the save menu is only summoned twice!

Hypothesis
----------

Perhaps the events are supposed to run in the middle of the teleport, and so the second OpenSaveMenu triggers, it sets a flag to summon the save menu, but since we're teleporting it doesn't come up. Then we finish the teleport, process events again, and the 3rd opensavemenu command triggers, setting the flag again, and then the save menu finally appears.

**Comment by fmatthew5876** [comment]
Here are more test cases which expose information about how the interpreter works

```
Wait 0.0s
Teleport
OpenSaveMenu
CallMenu
```

The save menu is called

```
Wait 0.0s
Teleport
CallMenu
OpenSaveMenu
```

The menu is called

```
Wait 0.0s
Teleport
CallShop
ChangeName
```

Shop is called

```
Wait 0.0s
Teleport
ChangeName
CallShop
```

Name change menu is called

```
Wait 0.0s
Teleport
CallShop
Battle
```

Shop is called

```
Wait 0.0s
Teleport
CallShop
Battle
```

Shop is called

```
Wait 0.0s
Teleport
Battle
CallShop
```

Battle is started

Result
------

In all cases, the first action takes place and the second action is ignore.

Conclusion
------

RPG_RT probably uses one variable to store which menu/scene to summon. If its not set to `(None)` any subsequent request to call a menu or battle in the same frame is ignored.

**Comment by fmatthew5876** [comment]
Here is something more telling

```
Wait 0.0s
Teleport
OpenSaveMenu
SetVariable
OpenSaveMenu
Loop:
  Wait 0.0s
```

In this case we call save menu twice!



Hypothesis
------

The interpreter checks the "call menu" variable every tick of the interpreter. In the case where we do `save, something, save`, iterating over the something step gives the interpreter a chance to call the menu.

In the `save, save` case, the interpreter never gets a chance to summon the menu, so the first call gets overwritten by the second.



Also to confirm, with this: 
```
Wait 0.0s
Teleport
SetVariable 1: map id
OpenSaveMenu
SetVariable2: map id
OpenSaveMenu
Loop:
  Wait 0.0s
```

The first set variable is the first map id, the second variable is the second map id. So this single mid teleport frame happens before we change maps.

**Comment by CherryDT** [comment]
I believe it's because of this (from my description [here](https://github.com/EasyRPG/Player/issues/1626#issuecomment-469078584)):

> Note that there is one additional special case: The first three items of this list (processed flag getting reset, main update methods for common events and then map events are run) are also executed when a teleport has just been executed (right after the position of the party was updated) or from inside the menu scene when a teleport/escape was executed, right before the screen fades in.

In case of the save menu being opened twice even though there are 3 save menu commands, I believe it's because the teleport is scheduled, then executed at the next frame, then this special case executes which changes the scene to the save menu (which does not yet have any effect), then the normal event processing runs, but due to the behavior described [here](https://github.com/EasyRPG/Player/pull/1658#issuecomment-469070258) it will run one more command from the parallel event, once more setting the current scene to the save menu. Then, at the next frame, the save menu will come up.

So, a teleport causes **the event workers to run twice in the same frame**. (Actually, it may even have some effects on movement, because it's actually the main update methods of the events which run, and that one does more than just calling the event worker.)

**Comment by fmatthew5876** [comment]
> So, a teleport causes **the event workers to run twice in the same "frame"**, once before the screen fades in and once afterwards ("frame" in quotemarks because the fade-in of course takes several _graphical_ frames, however all happens in the same iteration of the game's main loop, and the frame counter is not incremented in between).

Is this also the case for a new game? When you start a new game you get this "only event workers" behavior running before transition in. Does RPG_RT not increment the frame counter here too?

**Comment by CherryDT** [comment]
Hm yes I think so, since it's all inside the map's update method, never reaching the main loop again in between

**Comment by fmatthew5876** [comment]
Test Cases 1 - Some teleport map cases
---------------------

1. On Map1, setup EV01 as parallel with
```
TeleportPlayer Map 2
```

On Map 2, setup EV02 as parallel with
```
Loop:
  OpenSaveMenu
```

| Save | map_id | stop count | processed |
| 1 | 2 | 0 | 0 |
| 2 | 2 | 1 | 1 |

Result: Game starts immediately on Map2, then does preupdate, and update.

2. Change Map1 EV01 to autostart

| Save | map_id | stop count | processed | current command |
| 1 | 2 | 1 | 1 | 1 |
| 2 | 2 | 1 :question: | 1 | 0 |
| 3 | 2 | 2 | 1 | 0 |

Result:


2. Change Map1 EV01 code
```
OpenSaveMenu
Transfer to Map2
```

| Save | map_id | stop count | processed | current command |
| 1 | 1 | 1 | 1 | 1 |
| 2 | 2 | 1 | 1 | 2 |
| 3 | 2 | 1 :question: | 1 | 0 |
| 4 | 2 | 2 | 1 | 0 |

Result:

**Comment by fmatthew5876** [comment]
Test Cases 2 - Teleport to same map
--------------------------

1. Setup EV01 as parallel
```
OpenSaveMenu
Teleport to this map
OpenSaveMenu
OpenSaveMenu
```

| Save | stop count | processed |
| -- | -- | -- |
| 1 | 0 | 0 |
| 2 | 1 | 1 |
| 3 | 2 | 1 |

Result: Preupdate does not appear to happen when teleport to same map?

**Comment by fmatthew5876** [comment]
Test Cases 3 - Escape / Teleport Spell
----------------------------------

1. Setup Map1 EV01 as parallel:
```
Set Teleport point: Map2
Set Escape Location: Map2
OpenMainMenu
```

Setup Map2 EV01 as parallel:
```
Loop:
  OpenSaveMenu
```

In the main menu, save, and the cast Escape

| Save | map id | stop count | processed |
| -- | -- | -- | -- |
| 1 | 1 | 0 | 0 |
| 2 | 2 | 0 | 0 |
| 3 | 2 | 1 | 1 |

2. Repeat the same, except this time cast Teleport

Results: Same as above

3. Setup Map1 EV01 as parallel:
```
Set Teleport point: Map1
Set Escape Location: Map1
OpenMainMenu
Loop:
  OpenSaveMenu
```

In the main menu, save, and the cast Escape

| Save | map id | stop count | processed |
| -- | -- | -- | -- |
| 1 | 1 | 0 | 0 |
| 2 | 2 | 0 | 0 |
| 3 | 2 | 1 | 1 |

4. Repeat the same, except this time cast Teleport

Results: Same as above

5. Repeat the same, but just save and exit the menu without casting anything


| Save | map id | stop count | processed |
| -- | -- | -- | -- |
| 1 | 1 | 0 | 0 |
| 2 | 2 | 1 | 1 |
| 3 | 2 | 2 | 1 |

Conclusion:
----------------

Casting teleport or escape always causes a preupdate to occur

**Comment by fmatthew5876** [comment]
Test Cases 4 - Teleport and menu conflict
-----------------------

1. Setup EV01 as parallel with
```
OpenSaveMenu
```

Setup EV02 as parallel with
```
Teleport map2
```

Result: Player starts on map2, save menu is called.


2. Setup EV01 as parallel with
```
Wait 0.0s
OpenSaveMenu
```

Setup EV02 as parallel with
```
Wait 0.0s
Teleport map2
```

Result: Player starts on map1, transition in, Teleports to map2, save menu is called.

3. Setup EV01 as parallel with
```
Wait 0.0s
Teleport map2
```

Setup EV02 as parallel with
```
Wait 0.0s
OpenSaveMenu
```

Result: Player starts on map1, transition in, Teleports to map2, save menu is called.


Conclusion:
---------------

Scene calling flags are saved and executed on next map during its preupdate.

**Comment by fmatthew5876** [comment]
Test Cases 5 - Multiple teleports requested
---------------------------------

1. Setup EV01 parallel
```
Teleport to map 2
````

Setup EV02 parallel
```
Teleport to map 3
```

Result: Player starts on map 3


2. Setup EV01 parallel
```
Teleport to map 3
````

Setup EV02 parallel
```
Teleport to map 2
```

Result: Player starts on map 2

3. Setup EV01 parallel
```
Wait 0.0s
Teleport to map 3
````

Setup EV02 parallel
```
Wait 0.0s
Teleport to map 2
```

Result: Player starts on map 1, transition in, teleports to map 2

4. Setup EV01 parallel
```
Wait 0.0s
Teleport to map 2
````

Setup EV02 parallel
```
Wait 0.0s
Teleport to map 3
```

Result: Player starts on map 1, transition in, teleports to map 3

Conclusion
---------------

Teleport works like scene calling. There is one "teleport target" variable and if multiple teleports happen on the same frame, the last one overwrites the previous and wins.

**Comment by fmatthew5876** [comment]
Test Cases 6 - Move to variable location edge cases
------------------------------

1. Try move to variable location (0, 0, 0)

Result: Invalid map id error

2. Try move to variable location (-1,0,0)

Result: Cannot open `Map-0001.lmu` :exclamation: 

3. Try to move to (1,-1,8)

Result: Player is stuck at -1 position. The rightmost 8 pixels of player sprite are visible. The player can turn via arrow keys but can't move unless you use Ctrl to force through.

Conclusion:
----------------

Since mapid 0 and -1 trigger an action. The target teleport variable must have 4 values:
* active flag
* mapid
* x
* y

**Comment by fmatthew5876** [comment]
Test Cases 7 - Test event code after teleport
--------------------

1. Setup EV01 as parallel
```
Teleport Map2
Teleport Map3
Sw1
```

Result: New game starts on map3, Sw1 is on before fade in

2. Change EV02 as autostart

Result:
Transition in Map1, Teleport map2, Teleport map3, Sw1 on after transition in

Conclusion
---------------

Parallel events continue running code after a teleport. Autostart does not.

**Comment by fmatthew5876** [comment]
Test Cases 8 - What about areas?
------------------------------

1. Create Map1, and an area Map2 inside of Map1

Use `MoveToVariableLocation` to go to map2

Result: Cannot load map0002.lmu

Conclusion
--------------

You can't teleport to area maps.

**Comment by CherryDT** [comment]
Which brings up an interesting question.
What would happen when we *create such a file*?

After all, the entry exists in the map tree data structure.

I wonder what kind of effect that would have. It would be something that I'd imagine people to start using as a way of "obfuscation" or "copy protection"... :D (Because when looking at that map in RM you would see the area and not the real map...)

Furthermore, your `Map-0001.lmu` made me also curious, why -1 is accepted as map ID, there is no map tree entry for it, I thought... or maybe there is, and it's the project root? I don't remember. Same thing, one could create such a file...

**Comment by fmatthew5876** [comment]
Test Cases 9 - Teleport and move routes
----------------------------

1. Setup Map1 EV01 as autostart 
```
SetMoveRoute: Player, Up
Wait 0.0s
Wait 0.0s
Wait 0.0s
OpenSaveMenu
Transfer Map 2
```

Setup Map2 EV02 as parallel
```
Loop:
  OpenSaveMenu
```

| Save | map id | remaining step | stop count | move route overwrite | move route index | current command |
| -- | -- | -- | -- | -- | -- | -- |
| 1 | 1 | 160 | 1 | 1 | 1 | 5 |
| 2 | 2 | 0 | 0 | 1 | 1 | 6 |
| 3 | 2 | 0 | 1 | 0 | 1 | 0 |

Result: 
* Save1
* remaining_step goes to 0 during the teleport
* Preupdate - nothing happens to player
* Save2
* Player updates, finishes move route
* Old autostart event finishes - `current_command` -> 0
* Save 3

2. Change Map2 EV02 to autostart

| Save | map id | remaining step | stop count | move route overwrite | move route index | current command |
| -- | -- | -- | -- | -- | -- | -- |
| 1 | 1 | 160 | 1 | 1 | 1 | 5 |
| 2 | 2 | 0 | 0 | 1 | 1 | 2 |
| 3 | 2 | 0 | 1 | 0 | 1 | 2 |

Result: 
* Save1
* remaining_step goes to 0 during the teleport
* Preupdate - nothing happens to player
* Player updates -not finish move route?? :question:
* Old map1 autostart event finishes
* New map2 autostart begins
* Save2
* Player updates, finishes move route
* Save 3
