### ISSUE TITLE
Widescreen support/hack for existing games

### ISSUE THREAD

**Issue by whocares0101** [EasyRPG/Player#1627]
The idea is to scale the height 1:1 as normal and expand the width to match the desired aspect ratio.
This would be a great feature if it could be made to work reasonably well.
There are quiet some problems with this but they should be solvable for the most part.
I haven't touched the RPGMaker in years so maybe I forgot something but here are some thoughts.

 * Title screen
   * stretch the background
   * centered menu on the screen X axis
 * Tile map
   * increase the tiles rendered on the left/right screen regions
   * allow entities to be rendered as well in the new screen regions
 * Message window
   * unchanged size
   * centered on the screen X axis
 * Menus
   * unchanged size
   * centered on the screen X axis
   * add some padding tiles on each side from the menu tiles to avoid black bars
     * even better leave the tile map in the background instead, maybe the menu could use a little alpha blending for transparency (this should be low e.g 5-10%, tunable in ini) on the background (not the text)
 * Animations
   * keep as is or scale the positions based on new screen dimensions?
   * keep small animations as is e.g. if they target a character
   * big animations should be scaled to match screen size e.g. full screen effects
   * add tunable to ini on a per animation id basis if necessary
 * Battle
   * center menu, battlers, animations, etc. on X axis
     * for the 2003 version scaling the battlers X position would look better I guess, maybe for the 2000 version too?
   * stretch the background to fit the screen width
   * add padding tiles to lower menu or increase menu item width for longer strings
 * Pictures
   * depending on the initial picture position different things would most likely be best
     * if a picture would cover the whole screen or more scale it based on the new screen dimensions
       * X <= 0 && Y <= 0 && width >= default_screen_width && height >= default_screen_height
     * if a picture would be displayed on a screen edge keep its size and position it on the correct edge of the new screen size
       * X <= 0 || Y <= 0 || width >= default_screen_width || height >= default_screen_height
     * if a picture is free floating apply the X axis offset so it will be at the correct position
       * anything within the default screen size and not touching/overlap any edges
       * X > 0 && Y > 0 && width < default_screen_width && height < default_screen_height
     * there is a picture origin option in the editor if I'm not mistaken maybe that could be used as well to determine the best behavior
   * add tunable to ini on a per picture id basis
 * Panoramas
   * should work as is, maybe stretch?

This may work well for some games and not for others so having some tunables in RPG_RT.ini to disable certain options or force specific behavior (e.g. overrides per picture id) would be great.

**Comment by Ghabry** [comment]
The latest version of Maniacs Patch added an option for widescreen mode.

Though the implementation is pretty basic: It just renders more of the map and the picture origin is at the top-left corner. So nothing too interesting. You could achieve 90% of it with a few lines of Player code changes.

(also the configuration is through an ini-file, imo this should be a database chunk)
