### ISSUE TITLE
Panorama pictures with color issues

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1631]
Not tested the real reason, but it could be related with transparency issues or applying SDL color key when it shouldn't or even some pixman related glitch (like #357):

![scarr57](https://user-images.githubusercontent.com/174885/52538461-71130080-2d38-11e9-87a0-d3e9f8343017.png)

The white color (255,255,255) used to fill the text uses the latest palette index (255), however for some reason it shows this value black:

![sin titulo](https://user-images.githubusercontent.com/174885/52538492-ebdc1b80-2d38-11e9-81e9-d277df81e2b8.png)

**Comment by Ghabry** [comment]
Can't reproduce this
