### ISSUE TITLE
Crash on unhandled empty cancel option in Show Choice command

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1634]
If some game uses an empty option as selected on empty cancel, Player will crash. The following screenshot shows how the cancel key action is mapped to the empty 3rd option:

![o](https://user-images.githubusercontent.com/174885/52651573-08e82a00-2eb2-11e9-99d9-f6bb0a4561b4.png)

RPG_RT.exe seems to fallback to Cancel and does not display any error, continuing the game as usual.

**Comment by Ghabry** [comment]
we really lack sanity checks all around the interpreter but not worth implementing this before the magic number code smell is resolved (there was a liblcf issue for thsi, can't findi t)

**Comment by Ghabry** [comment]
I think we catched a common Android crash here 👍 

Affected 47 users over the last 60 days.
