### ISSUE TITLE
Webplayer crashes on startup

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1635]
Player is crashing since some Emscripten and encoding compositing updates.
Test URL, open the javascript console to see the backtrace:
https://easyrpg.org/play/master/

**Comment by Ghabry** [comment]
Checking whether "const icu::Normalizer2* norm" is nullptr fixes this but is of course not helpful because this means the normalisation is broken :/

**Comment by Ghabry** [comment]
thats a problem with icudata, fixed this manually for now. Creating a new issue in buildscript repo.
