### ISSUE TITLE
Yume2kki: Wallpaper is auto-selected (KeyInputProc bug?)

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1641]
Download: https://rmarchiv.tk/games/1905  (use any version)

Reproduce:
1. Fast forward through that annoying disclaimer
2. Go to your PC -> Tools -> Picture
3. in most cases it will auto-select the 1st wallpaper instead of allowing navigation. If navigation works (race condition?), simply select a wallpaper and press Cancel, the bug should be reproducible now.

I already checked against the Move Route PR, is not fixed

The bug is also reproducable in RPG_RT but only 5% of the times and not 90%.

**Comment by Ghabry** [comment]
needs retest after all these fixes

**Comment by Ghabry** [comment]
nope, not fixed yet. Welcome to interpreter hell.

**Comment by fmatthew5876** [comment]
Looks like this was another one with vehicle teleport timings. It's fixed in the version of Yume 2kki I have with #2047
