### ISSUE TITLE
MoveType toward/away logic is not entirely accurate

### ISSUE THREAD

**Issue by CherryDT** [EasyRPG/Player#1644]
RM logic for towards/away move types is:

* If event is not in sight, move randomly
* If event is in sight, move towards/away from hero with 80% chance, randomly with 10% chance, forwards without direction change with 10% chance.

Definition for "in sight": Screen coordinates (the same that are retrieved in the "Change Variable" event) of event are `x >= -32 && x <= 352 && y >= -32 && y <= 272`.

**Comment by fmatthew5876** [comment]
Are these screen coordinates affected by panning?

**Comment by fmatthew5876** [comment]
I surrounded a `move towards player` event with obstacles and ran a test.

When `stop_count <= 60` each frame the event will try to move and be blocked, not changing direction. On the 60th frame, the event will change direction and `stop_count` goes back to 0.

**Comment by fmatthew5876** [comment]
On non-looping maps, if you move such that the event is -2 tiles off the left edge of the screen, the screen x position is `-24`. 

If you do this on looping maps, the x position wraps to `(map_width - 1) * 16 - 8`

That means for non-looping the `x=-2` event would follow you, but in looping it would move randomly. A minor RPG_RT bug I guess :exclamation:
