### ISSUE TITLE
Random Encounters (2k3): Support Death Handlers

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1648]
In 2k3 Random Encounters don't always mean game over, when you enable these settings in the Battle screen tab:

Death Handler:
 - [ ] Call Common Event

Transfer Player:
 - [ ] Enable check
 - [ ] Actual teleport to location

Relevant LDB entries (System):

 - death_handler1: 0 Game Over - 1 Event
 - death_handler2: 0 Disable - 1 Enable
 - teleport_id
 - teleport_x
 - teleport_y

I think the defaults are wrong, value is 0 instead of 1 when the first item is enabled.

Also that naming is bad. We should discuss better names, teleport should be prefixed with death_ imo.

**Comment by fdelapena** [comment]
Attached test case from [forum post](https://community.easyrpg.org/t/monigote-fantasy-several-issues/638/7).

- [Example3.zip](https://github.com/EasyRPG/Player/files/2975860/Example3.zip).

**Comment by fmatthew5876** [comment]
For implementing this we need to know exactly when this death handler gets executed in the update loop as it could have complex interactions with other running foreground and background events.

Is there a separate worker? Does it reuse some worker? Does it block other events? When in the frame does it get called?

**Comment by fmatthew5876** [comment]
Test Cases 1 - Death handler and events
------------------

Install a death handler which calls a common event

1. Call game over scene from a map event

Result: Game over

2. Change HP -9999 with death flag from map event

Result: Game Over

3. Die in an event battle with death result conditional

Result: conditional

4. Die in an event battle with result game over

Result: Game Over

5. Start a battle with 0 HP for all party

Result: Immediate game over

Conclusion:
-----------------

Death handler's don't affect event battles or map events which can trigger game over

**Comment by fmatthew5876** [comment]
Test Cases 2 - Random encounters and death events
------------------

Install a death handler which calls a common event

1. Die in a random encounter

Result: Death handler called

2. Start a random encounter with 0 HP for all party

Result: Battle transition in battle, loss message, return to map, death handler called

3. Start a random encounter with a turn 0 event causing game over

Result: Game Over

4. Start a random encounter with a turn 0 event causing -9999 hp to party + death

Result: Death handler called.

**Comment by fmatthew5876** [comment]
Test Cases 3 - death handler timing
----------------------------------------------

Setup this death handler
```
OpenSaveMenu
```

1. die in a random encounter

| remaining step | stop count | current command (foreground) |
| -- | -- | -- |
| 0 | 1 | 1 |

Conclusion:
---------------

* Death handler is pushed onto the foreground stack
* Executes immediately next frame (`stop_count == 1`)

**Comment by fmatthew5876** [comment]
Test Cases 4 - death handler teleport
-------------------------

Setup a death handler event
```
Text: Die
```

Setup death teleport

1. die in a random encounter

Result: After battle, transitions into new map, and then event is called.

2. Setup this event on the death map

EV01 parallel
```
OpenSaveMenu
```

Die in a random encounter.

Result: Appears on new map, save menu called, Screen stays black :exclamation: while text box appears. Press enter to close text box. Screen stays black until player summons the menu.

Conclusion:
----------------

* Death handler is pushed onto foreground stack when teleported to new map
* Pre-update parallel events run before death handler.
* There are some graphical glitches with scene calls and text boxes

**Comment by fmatthew5876** [comment]
Test Cases 5 - Death handlers and other foreground events
----------------------------------------------------------

Setup Death Handler
```
Text: Die
```

Setup EV01 autostart on SW01
```
Text: ME
```

Setup CE01 autostart on SW01
```
Text: CE
```

Setup Battle event on turn 0
```
SW01 = On
```

1. Die in a random encounter

Result: D, ME, CE, ME, CE, ME, CE, ...

2. Add `OpenSaveMenu` after the message in all 3 events.

| stack size | current command | EV01 waiting execution |
| 1 | 2 | 1 |
| 2 | 2 | 1 |
| 1 | 2 | 1 |

Conclusion:
---------------

Death handler runs first, before other events get a chance to get pushed onto the stack. Normal behavior for an event which "has been running".

**Comment by Ghabry** [comment]
@fmatthew5876 
Are you sure that death_handler is unused?

In my initial comment I documented them as:
death_handler1: 0 Game Over - 1 Event
death_handler2: 0 Disable - 1 Enable (Teleport)
Was there another chunk for "teleport enabled"?

**Comment by fmatthew5876** [comment]
There is a `death_teleport` chunk to enable teleports. As far as I can tell `death_handler1` get set by the editor but does nothing in `RPG_RT`.
