### ISSUE TITLE
Verify fluidsynth skips initial MIDI silence

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1653]
~Current soft synths used in Player are not handling this~.

After some tests performed by Albeleon, except when some particular events are defined in certain channel positions (including SysEx events), they may prevent skipping the silent.

Edit: Needs to be tested with FluidSynth if we go ahead with this synth even for Windows. It seems Albeleon tested this on Windows with native MIDI. It's confirmed WildMIDI and FMMIDI skip silence properly, then if FluidSynth does it properly nothing will be needed to be done.

**Comment by fdelapena** [comment]
wildmidi and fmmidi skip initial silent properly by default, still needs to be tested with the libfluidsynth branch.

**Comment by carstene1ns** [comment]
> Current soft synths used in Player are not handling this

10/10. :+1:

**Comment by fdelapena** [comment]
Because current path plans bundling FluidLite and using fmmidi for parsing and sending events, and fmmidi seems to handle this properly and still may handle this the same way with full FluidSynth, this issue got somehow obsolete.

**Comment by Ghabry** [comment]
Yeah the plan is to use our sequencer for both fluidsynth and fluidlite. Fluidsynth could use the fluid sequencer but then you will have many ifdefs in the code and it is possible that the output will sound slightly different (but this can be tested by comparing the buffer output of both)
