### ISSUE TITLE
Implement SaveMapEventBase::pause

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1664]
We haven't yet implemented the `pause` flag.

Notes from Cherry in IRC:

> <Cherry[m]> actually it's quite simple I think: pause gets set when an event is triggered by autostart/action/touch/collision, right when the waiting_execution also gets set, and gets cleared when a new move route or event page is applied or the event script ends. it influences the movement update as discussed and also disabled part of the party event's behavior (it disabled handling of waiting encounters, checking for new encounters,
<Cherry[m]> processing the waiting menu flag from ESC press, processing directional key input from the player, ... - same way an open message window or move_route_overwrite does)
<Cherry[m]> hm, I just realized, the effect on the party event is useless, since the flag can never be set for the party
<Cherry[m]> (it's implemented though ^^)

**Comment by Ghabry** [comment]
Sounds like our ``Game_Map::GetInterpreter().IsRunning() && !Game_Map::IsAnyEventStarting()``

**Comment by fmatthew5876** [comment]
@CherryDT

Looking through our conversations, for `Game_Event`, it looks like the only effect of the paused flag is that it prevents `stop_count` from ticking.

What else does it do for map events? Perhaps suppressing non-move route movement from initiating?

**Comment by CherryDT** [comment]
> Perhaps suppressing non-move route movement from initiating?

Exactly that.

**Comment by fmatthew5876** [comment]
We have these checks for initiating event movement:

```
if (IsWaitingForegroundExecution())
    return;
if (!Game_Message::GetContinueEvents() && Game_Map::GetInterpreter().IsRunning())
    return;
if (!IsStopping())
    return;
if (page == nullptr) {
    return;
}
```

I suspect the `IsWaitingForegroundExecution()` is wrong and it should just be `IsPaused()`. How about the others? Are we missing any?

**Comment by CherryDT** [comment]
I don't know what `IsWaitingForegroundExecution()` does exactly, but the check is like this:  `pause || move_route_overwrite || currentEventPage.move_type == "none" || (Save.events.commands.length > 0 && !SaveSystem.message_continue_events)`

**Comment by fmatthew5876** [comment]
`IsWaitingForegroundExecution()` is the fancy getter for `waiting_execution`. Thanks for the logic. I'll fix our code to do this.

**Comment by fmatthew5876** [comment]
Test Cases 1 - When is pause set/reset
------------------------------------------

1. Setup a common parallel event with

```
Loop:
  OpenSaveMenu
```

Setup EV01 autostart with
```
Wait 0.0s
```

| Save | EV01 pause | EV01 waiting_execution | current command |
| -- | -- | -- | -- |
| 1 | 1 | 1 | 0 |
| 1 | 1 | 0 | 1 |
| 1 | 1 | 1 | 1 |
| 1 | 0 | 1 | 0 |

Result: pause is cleared when the event finishes, regardless of the fact that its again waiting for execution!

2. Change EV01 code to this:
```
Wait 0.0s
SetMoveRoute: this
```

 | Save | EV01 pause | EV01 waiting_execution | current command | EV01 stop count | EV01 move route overwritten |
| -- | -- | -- | -- | -- | -- |
| 1 | 1 | 1 | 0 | 1 | 0 |
| 2 | 1 | 0 | 1 | 1 | 0 |
| 3 | 1 | 1 | 1 | 1 | 0 |
| 4 | 0 | 1 | 2 | 65535 | 0 |
| 5 | 0 | 1 | 0 | 65536 | 0 |

Result: Move route cancels pause state

3. Change EV01 code to this:
```
Wait 0.0s
Enable Sw1
Wait 0.0s
```

Add a page 2 activated by SW1 with `trigger=action` and no code


 | Save | EV01 pause | EV01 waiting_execution | current command |
| -- | -- | -- | -- |
| 1 | 1 | 1 | 0 |
| 2 | 1 | 0 | 1 |
| 3 | 1 | 1 | 1 |
| 4 | 0 | 0 | 2 |
| 5 | 0 | 0 | 3 |
| 6 | 0 | 0 | 3 |
| 7 | 0 | 0 | 0 |


Result: Page change cancels pause

**Comment by fmatthew5876** [comment]
All these test cases are now passing in #1628.
