### ISSUE TITLE
Emscripten: Fullscreen is broken

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1665]
https://easyrpg.org/play/

Click fullscreen, in some browsers you get a SDL assert and in some simply a black screen.

**Comment by fdelapena** [comment]
> in some browsers

Confirmed at least with Firefox.

**Comment by carstene1ns** [comment]
so finally time to do #803 :P

**Comment by fdelapena** [comment]
![JavaScript SDL assertion failed prompt](https://user-images.githubusercontent.com/174885/54486038-24937700-4848-11e9-926b-97f18776c52c.png)

Nice prompt with possible useful info after returning from full screen.
