### ISSUE TITLE
White stripe appears in landscape orientation in Android

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1667]
This issue does not affect strictly gameplay, except because the annoying white strip ruins the immersion experience and mood for some games, mainly dark horror games.

This might be related to some API 26 targetting or something related with SDL 2.0.9. I'm able to reproduce this in my LG device with Android 6.0.1.

Here's a couple of screenshots contributed via email (save the picture or try loading it with borders or dark background because GitHub white background won't help to note the difference):

![screenshot_20190304-180821](https://user-images.githubusercontent.com/174885/53822924-50ecf080-3f36-11e9-9ef6-9343757d1143.png)
![screenshot_20190304-180837](https://user-images.githubusercontent.com/174885/53822925-50ecf080-3f36-11e9-8003-8502b14f6fa4.png)

**Comment by carstene1ns** [comment]
I remember having a similar problem some time ago. Was about the menu shadows not displaying in that area. Seems it got more serious now.
So might be related to the touch overlay, if i remember correctly we patched SDL stuff here.

**Comment by fdelapena** [comment]
![screenshot_2019-03-05-17-51-04](https://user-images.githubusercontent.com/174885/53845639-c5a94480-3fa1-11e9-9fa4-2d6de93fc261.png)

It works as expected.

**Comment by carstene1ns** [comment]
Fixed by #1670.
