### ISSUE TITLE
External .fon support

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1669]
EasyRPG Player already depends on FreeType. Time before getting Shinonome and other fonts embedded into Player, this support for .fon was required. So this could be provided for external .fon somewhere (e.g. `[EasyRPG]` section with custom entries in RPG_RT.ini) and verify it still works as expected. This is a feature request based on the @elvissteinjr's  [community post](https://community.easyrpg.org/t/is-there-still-a-way-to-load-the-original-fonts/648).

https://github.com/EasyRPG/Player/issues/748#issuecomment-340561603 already mentions this proposal and might be part of this feature, but this one is intended to track specific issues with .fon files.

Some tests to keep in mind:

- RMG2000.FON provided by Don's RTP used bad sizes for most glyphs, this may be verified by trying the .fon in some apps. They need to fit in the 6x12 to behave as in RPG_RT. Related crash: #35 .
- Try with games which provide custom .fon (there is a significant amount of games providing them, e.g. OFF optional fonts).
- Fallback glyphs to built-in when the font does not provide some of them (ugly, but better than nothing).
- Detect font encodings if possible and provide some logging or warn for developers if current encoding is not supported by the font.

**Comment by Ghabry** [comment]
I would like to handle this because otherwise I have to rebase all my FT and HB code ;)

**Comment by Ghabry** [comment]
Closed by #2855
