### ISSUE TITLE
Enemies stay "hooked" unlimitedly in KangaPunch mini-game

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1671]
There's a new problem in this mini-game with Player 0.6

In RPG_RT, the kangaroo can "hook" the enemy when the enemy is blocking hits for a limited time, in EasyRPG this hook is until the enemy is K.O.

(This is not intentional, it's the normal behavior of events in RPG_RT)

How to reproduce it: especially with Happy Hippo (it's the more defensive enemy), launch punches when the enemy is moving until the enemy stay blocking hits during a time, then, the enemy will move in other direction and going forward the kangaroo again.

Here you can see the difference:

RPG_RT
https://youtu.be/rFYmSVbPHOc

Player
https://youtu.be/yWgGdY4miho

**Comment by Ghabry** [comment]
Could you test with this version of player?
https://ci.easyrpg.org/view/Pull%20Requests/job/player-win32-pr/2552/

**Comment by Br4ssman** [comment]
It works!

Thanks.

**Comment by Ghabry** [comment]
Thanks, because #1601 is so hard to review I go a different way: Others give me enough reasons to merge it xD
