### ISSUE TITLE
Make Way test cases

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1675]
Test Cases 1: Diagonal movement
-------------

1. Setup a Tile passable right and down only.

| Start from | Step | Result |
| -- | -- | --|
| On the tile | Upper left | Blocked |
| On the tile | Upper right | ok |
| On the tile | Lower left | ok |
| On the tile | Lower Right | ok |
| Left of the tile | Upper right | ok |
| Left of the tile | Lower right | ok |
| Above of the tile | Lower left | ok |
| Above of the tile | Lower right | ok |
| Up left from the tile | Lower right | Blocked |

Result: Both directions must be blocked to stop movement

2. Setup blocking tiles as described

| Right Of | Below Of | Step | Result |
| -- | -- | -- | -- |
| | | Lower Right | Ok |
| Blocked | | Lower Right | ok |
| | Blocked | Lower Right | ok |
| Blocked | Blocked | Lower Right | Blocked |

Result: At least 1 of the adjacent tiles must not be blocked to allow movement.

3. Setup 5 events in a star formation as shown below:

All of these events should be `layer=same`, `trigger=parallel`.

| Tile | Tile | Tile |
| -- | -- | -- |
| | EV05 | |
| EV04 | EV01 | EV02 |
| | EV03 | |

Set the code for EV02 to EV05 to Message "N" where N is the event number.

Now set the code of EV01 to a move route with the following movements:

| MoveRoute | Result |
| -- | -- |
| Lower Right | 3, 2, 3, 2, 3, 2, 3, 2, 3, 2,  |
| Lower Left | 3, 4, 3, 2, 3, 4, 3, 3, 4, 3, 2, 3, 4, 3 |
| Upper Right | 5, 2, 5, 2, 5, 2, 5, 2, 5, 2,  |
| Upper Left | 5, 4, 5, 2, 5, 4, 5, 3, 5, 4, 5, 2, 5, 4, 5, 4, 5, 2, 5, 4 |
| Right | 2, 2, 2, 2, 2, 2, 2 |
| Down | 3, 2, 3, 3, 2, 3, 3 |
| Left | 4, 2, 4, 3, 4, 2, 4, 4, 2, 4, 3, 4, 2, 4, 4, |
| Up | 5, 2, 5, 3, 5, 2, 5, 4, 5, 2, 5, 3, 5, 2, 5, 5 |

Result: Vertical direction is checked first!

4. Lets verify message timing didn't skew our results

| Tile | Tile | Tile |
| -- | -- | -- |
| EV08 | EV05 | EV09 |
| EV04 | EV01 | EV02 |
| EV07 | EV03 | EV06 |

Now change each EV02-EV09 code to
```
Change Variable N to 1 (where N is the event number)
Enabled Sw1
```

For each Event EV02-EV09, add a second page activated by SW1 with no code.

Change EV01 to
```
SetMoveRoute: MOve
Wait 0.1s
Msg: \v[2] \v[3] \v[4] \v[5] \v[6] \v[7] \v[8] \v[9]
```

| MoveRoute | Result |
| -- | -- |
| Lower Right | 0 1 0 0 0 0 0 0 |
| Lower Left | 0 1 0 0 0 0 0 0 |
| Upper Right | 0 0 0 1 0 0 0 0  |
| Upper Left | 0 0 0 1 0 0 0 0 |
| Right | 1 0 0 0 0 0 0 0 |
| Down | 0 1 0 0 0 0 0 0  |
| Left | 0 0 1 0 0 0 0 0 |
| Up | 0 0 0 1 0 0 0 0 |

Result: Vertical is indeed checked first.

5. For all events EV03-EV09 (Not EV02!), remove the `Enable SW1` code

| MoveRoute | Result |
| -- | -- |
| Lower Left | 1 1 1  0 0 0 0 0 |
| Upper Left | 1 0 1 1 0 0 0 0 |

Result: 
* Diagonal movement checks vertical (vertical event runs)
* then checks horizontal. (horizontal event runs)
* Both failed, *so it does not check the diagonal square*.
* EV02 runs, enabling SW1.

6. Now change EV02-EV09 to `layer=below`

| MoveRoute | Result |
| -- | -- |
| Lower Left | 1 1 0 0 0 1 0 0 |
| Upper Left | 1 0 0 1 0 0 1 0 |

Result: Vertical movement check passes, *so horizontal is not checked*. Diagonal is checked.

7. Now change EV03 and EV05 to `layer=same`

| MoveRoute | Result |
| -- | -- |
| Lower Left | 1 1 1 0 0 1 0 0 |
| Upper Left | 1 0 1 1 0 0 1 0 |

Result: Verticals fail, so all 3 tiles checked

8. Delete the events

On the right edge of a non-looping map, setup the following events

| Tile | Tile |
| -- | -- |
| EV02 | EV01 |
| | EV03 |

All 3 events `trigger=parallel`

EV01 code is `SetMoveRoute: ThisEvent, lower right`
EV02 code is `Message "2"`
EV03 code is `Message "3"`

Now start a new game.

Result: "3" and then "2". Despite the fact that the target diagonal tile is invalid, vertical is still checked.

9. Now reorganize the events on the bottom edge of the map

On the right edge of a non-looping map, setup the following events

| Tile | Tile |
| -- | -- |
| EV02 | |
| EV01 | EV03 |

Now start a new game.

Result: "3" and then "2". Despite the fact that the target diagonal tile is invalid, horizontal is still checked.

10. Tile event self conflict check

Delete the events

Setup EV01 with `layer=below`, a TILE graphic (see below), custom move route `Move Upper Right`

Setup the map like this:

| Tile | Tile |
| -- | -- |
| | Player |
| EV01 | |

| TILE | Result |
| -- | -- |
| With Up direction blocked | Moves |
| With Right direction blocked | Moves |
| With Up and Right blocked | Blocked |

Result: self conflict check is done, and requires both directions to be blocked.

**Comment by fmatthew5876** [comment]
Test Cases 2 - Jumping
-----------------

Create EV01 with a custom move route `Jump, Lower Right, Land`

Setup these tiles:

| Tile | Tile |
| -- | -- |
| EV01 | |
| | Tile with up and left blocked |

Result: EV01 jumps onto the tile. Jumping ignores directional blocking.

2. Remove the tile

Create EV02 in this setup

| Tile | Tile |
| -- | -- |
| EV01 | |
| | EV02 |

Now test the various layers

| EV01 layer | EV02 layer | Result |
| -- | -- | -- |
| below | below | blocked |
| below | same | jumps |
| below | above | jumps |
| same | below | jumps |
| same | same | blocked |
| same | above | jumps |
| same | below | jumps |
| above | below | jumps |
| above | same | jumps |
| above | above | blocked |

3. Delete EV01

Change EV01 move route to `Jump, Land`

Place a blocking tile under EV01

Result: EV01 is able to jump in place.

3. Change EV01 `move_type=stationary`

Create EV02 as parallel with code `Msg: 2`
Create EV03 as parallel with code `Msg: 3`
Setup EV01 as parallel with code
```
Set EV03 to position of EV01
SetMoveRoute: This Event, Jump, Land
```

Result: "2", "3" - Jumping in place *does not* trigger other events to run!

4. Delete the events.

Setup EV01 with `layer=below`, and tile graphic that blocks the up direction, with custom move route `Jump, Up, Land`

Set the player above EV01

Result: EV01 jumps. Self conflict check is not done for jumping.

**Comment by fmatthew5876** [comment]
Test Cases 3 - Ship Tests
------------------------------

1. Setup EV01 to the left of the ship, on the grass.

Set EV01 custom move route `Right`

| EV01 layer | EV01 graphic | Result |
| -- | -- | -- |
| below | sprite | steps through |
| same | sprite | blocked |
| above | sprite | steps through |
| below | tile passable above | steps through |
| same |  tile passable above | blocked |
| above |  tile passable above | steps through |
| below | tile passable | steps through |
| same |  tile passable | blocked |
| above |  tile passable | steps through |
| below | tile impassable | blocked |
| same |  tile impassable | blocked |
| above |  tile impassable | steps through |


2. Change EV01 `move_type=stationary`, `trigger=paralel`, code `SetMoveRoute: Ship, Left`

Put the event and the ship in the water. EV01 to the left of the ship still.

| EV01 layer | EV01 graphic | Result |
| -- | -- | -- |
| below | sprite | steps through |
| same | sprite | blocked |
| above | sprite | steps through |
| below | tile passable above | steps through |
| same |  tile passable above | blocked |
| above |  tile passable above | steps through |
| below | tile passable | blocked |
| same |  tile passable | blocked |
| above |  tile passable | steps through |
| below | tile impassable | blocked |
| same |  tile impassable | blocked |
| above |  tile impassable | steps through |

3. Move the event away

Put a tile to the left of the ship as described:

| Upper Tile | Result |
| -- | -- |
| Passable Tile | Blocked |
| Impassable Tile | Blocked |
| Passable Above Tile | Steps Through |

4. Put EV01 to the left of the ship and set the `overlap_forbidden` flag

Result: Ignores the flag and steps

**Comment by fmatthew5876** [comment]
Test Cases 3 - Airhip Tests
------------------------------

1. Setup EV01 to the left of the airship, on the grass.

Set EV01 custom move route `Right`

| EV01 layer | EV01 graphic | Result |
| -- | -- | -- |
| below | sprite | steps through |
| same | sprite | blocked |
| above | sprite | steps through |
| below | tile passable above | steps through |
| same |  tile passable above | blocked |
| above |  tile passable above | steps through |
| below | tile passable | steps through |
| same |  tile passable | blocked |
| above |  tile passable | steps through |
| below | tile impassable | blocked |
| same |  tile impassable | blocked |
| above |  tile impassable | steps through |


2. Change EV01 `move_type=stationary`, `trigger=paralel`, code `SetMoveRoute: Airship, Left`

| EV01 layer | EV01 graphic | Result |
| -- | -- | -- |
| below | sprite | steps through |
| same | sprite | steps through |
| above | sprite | steps through |
| below | tile passable above | steps through |
| same |  tile passable above | steps through |
| above |  tile passable above | steps through |
| below | tile passable | steps through |
| same |  tile passable | steps through |
| above |  tile passable | steps through |
| below | tile impassable | steps through |
| same |  tile impassable | steps through |
| above |  tile impassable | steps through |

3. Move the event away

Put a tile to the left of the ship as described:

| Upper Tile | Result |
| -- | -- |
| Passable Tile | Steps Through |
| Impassable Tile | Steps Through |
| Passable Above Tile | Steps Through |

4. Put EV01 to the left of the airship and set the `overlap_forbidden` flag

Result: Ignores the flag and steps

5. Delete the events.

Setup this

| Tile | Tile |
| -- | -- |
| Airship | EV03 |
| EV01 | EV02 |

Set all events as `trigger=parallel`

EV01 `SetMoveRoute: Airship, Right`
EV02 `Message: 2`
EV03 `Message: 3`

Result: Airship moves right, "2", "3" - Airship movement does not trigger event update routines.

**Comment by fmatthew5876** [comment]
Test Cases 5 - Tile Events
-------------------------

1. Setup these events

| Tile | Tile |
| -- | -- |
| EV03 (Water) | EV01 (Grass) |
| | EV02 (Grass) |

Set EV01 to parallel with code `MoveRoute: This, Left`
Set EV02 to parallel with code `Msg: 2`
Set EV03 to parallel with code `Msg: 3`

Set EV03 `layer=below` and graphic to a passable tile

Result: EV01 steps left, "3", "2" - EV03 allows passable and updates before EV02

2. Change EV03's graphic to a passable above tile with `layer=below`

Result: EV01 is blocked, "3", "2" - EV03 blocks and updates before EV02

3. Change EV03's lower tile to grass

Change EV03's graphic to an impassable tile with `layer=below`

Result: EV01 is blocked, "3", "2" - EV03 blocks and updates before EV02


3. Delete the events

Create EV01 to the left of EV02.
Set EV01 custom move route `Move: Right`

Set EV01 to sprite graphic, passable tile, or passable above tile:

| EV01 layer | EV02 layer | EV02 graphic | Result |
| -- | -- | -- | -- |
| below | below | sprite | blocked |
| below | same | sprite | steps |
| below | above | sprite | steps |
| below | below | pass tile | blocked |
| below | same | pass tile | steps |
| below | above | pass tile | steps |
| below | below | impass tile | blocked |
| below | same | impass tile | steps |
| below | above | impass tile | steps |
| below | below | pass above tile | blocked |
| below | same | pass above tile | steps |
| below | above | pass above tile | steps |
| | | |
| same | below | sprite | steps |
| same | same | sprite | blocked |
| same | above | sprite | steps |
| same | below | pass tile | steps |
| same | same | pass tile | blocked |
| same | above | pass tile | steps |
| same | below | impass tile | blocked |
| same | same | impass tile | blocked |
| same | above | impass tile | steps |
| same | below | pass above tile | steps |
| same | same | pass above tile | blocked |
| same | above | pass above tile | steps |
| | | |
| above | below | sprite | steps |
| above | same | sprite | steps |
| above | above | sprite | blocked |
| above | below | pass tile | steps |
| above | same | pass tile | steps |
| above | above | pass tile | blocked |
| above | below | impass tile | blocked :exclamation: |
| above | same | impass tile | steps |
| above | above | impass tile | blocked |
| above | below | pass above tile | steps |
| above | same | pass above tile | steps |
| above | above | pass above tile | blocked |

4. Change EV01 to an impassable tile graphic

| EV01 layer | EV02 layer | EV02 graphic | Result |
| -- | -- | -- | -- |
| below | below | sprite | blocked |
| below | same | sprite | blocked |
| below | above | sprite | steps |
| below | below | pass tile | blocked |
| below | same | pass tile | blocked |
| below | above | pass tile | steps |
| below | below | impass tile | blocked |
| below | same | impass tile | blocked |
| below | above | impass tile | steps |
| below | below | pass above tile | blocked |
| below | same | pass above tile | blocked |
| below | above | pass above tile | steps |
| | | |
| same | below | sprite | steps |
| same | same | sprite | blocked |
| same | above | sprite | steps |
| same | below | pass tile | steps |
| same | same | pass tile | blocked |
| same | above | pass tile | steps |
| same | below | impass tile | blocked |
| same | same | impass tile | blocked |
| same | above | impass tile | steps |
| same | below | pass above tile | steps |
| same | same | pass above tile | blocked |
| same | above | pass above tile | steps |
| | | |
| above | below | sprite | steps |
| above | same | sprite | steps |
| above | above | sprite | blocked |
| above | below | pass tile | steps |
| above | same | pass tile | steps |
| above | above | pass tile | blocked |
| above | below | impass tile | blocked :exclamation: |
| above | same | impass tile | steps |
| above | above | impass tile | blocked |
| above | below | pass above tile | steps |
| above | same | pass above tile | steps |
| above | above | pass above tile | blocked |

**Comment by fmatthew5876** [comment]
Test Cases 6 - Airship Landing
---------------------------------

1. Can the airship land?

| Lower Tile | Upper Tile or Event | Result |
| -- | -- | -- |
| Landable | pass | yes |
| Landable | impass | no |
| Landable | pass above | no |
| Landable | Any event | no |
| Not Landable | pass | no |
| Not landable | impass | no |
| Not landable | pass above | no |
| Not landable | Any event | no |

**Comment by fmatthew5876** [comment]
Test Cases 7 - Tile Events blocking you from starting
--------------------

1. Setup these events:

| Tile | Tile | Tile | Tile |
| -- | -- | -- | -- |
| EV02 | EV01 | EV04 | EV03 |

Set EV02, EV03, EV04 as parallel, `layer=same`

EV01 as `layer=below`, graphic with a tile not passable on the right
EV02 parallel `SetEventLocation: This event to EV01; SetMoveRoute: This, Right`
EV03 parallel `Msg: 3`
EV04 parallel `Msg: 4`

Result: EV02 is stuck, "3", "4".

A tile event preventing you from starting to move aborts the loop early. We don't check collisions on any events.

**Comment by fmatthew5876** [comment]
@CherryDT

How does the `GetOnOffVehicle` event command work exactly? More specifically what is the timing?

Lets say EV01 is parallel and does a `GetOnOffVehicle` command. 

Will this command execute immediately right there in the intepreter? Forcing the player to collision check against events right then and there?

Or does it somehow set a hidden flag and get deferred until the player's update loop and then collision checked then?

**Comment by CherryDT** [comment]
I'm not sure, but I think it's handled immediately.

**Comment by fmatthew5876** [comment]
Test Cases 8 - processed flag
---------------------------------

1. Setup common parallel event 
```
Loop:
  OpenSaveMenu
```

Create EV01

| Save | player processed | boat processed | ship processed | airship processed | EV01 processed |
| -- | -- | -- | -- | -- | -- |
| 1 | 0 | 0 | 0 | 0 | 1 |
| 2 | 1 | 0 | 0 | 0 | 1 |

Result: Player doesn't update on first save. Vehicles not on map so never updated.

2. Now put all 3 vehicles on the map

| Save | player processed | boat processed | ship processed | airship processed | EV01 processed |
| -- | -- | -- | -- | -- | -- |
| 1 | 0 | 0 | 0 | 0 | 1 |
| 2 | 1 | 1 | 1 | 1 | 1 |

Result: Player and vehicles don't update on first save.

3. Now put EV01 to the left of the player, and set EV01 custom move route to `Right`

| Save | player processed | boat processed | ship processed | airship processed | EV01 processed |
| -- | -- | -- | -- | -- | -- |
| 1 | 1 | 0 | 0 | 0 | 1 |
| 2 | 1 | 1 | 1 | 1 | 1 |

Result: collision causes player to update on first save

4. Now put EV01 to the left of the boat

| Save | player processed | boat processed | ship processed | airship processed | EV01 processed |
| -- | -- | -- | -- | -- | -- |
| 1 | 0 | 1 | 0  | 0 | 1 |
| 2 | 1 | 1 | 1 | 1 | 1 |

Result: collision causes boat to update on first save


5. Now put EV01 to the left of the ship

| Save | player processed | boat processed | ship processed | airship processed | EV01 processed |
| -- | -- | -- | -- | -- | -- |
| 1 | 0 | 0 | 1 | 0 | 1 |
| 2 | 1 | 1 | 1 | 1 | 1 |

Result: collision causes ship to update on first save

6. Now put EV01 to the left of the airship

| Save | player processed | boat processed | ship processed | airship processed | EV01 processed |
| -- | -- | -- | -- | -- | -- |
| 1 | 0 | 0 | 0 | 1 | 1 |
| 2 | 1 | 1 | 1 | 1 | 1 |

Result: collision causes airship to update on first save

**Comment by fmatthew5876** [comment]
Test Cases 9 - Boat/Ship Disembark
------------------------------------

1. Setup these tiles:

| Tile | Event |
| Grass | Player |
| Water | Boat |
| Grass | Ship |
| Water | |

Start a new game and board the boat, face down, and hit ENTER to disembark

Result:
Player disembarks ontop of the ship. Normally the player is not allowed to step on the same tile as the boat or ship, even if they are on the same tile. But for disembark it is allowed.

This seems to indicate that vehicle disembark uses a different collision routine.

1. Setup these tiles:

| Tile | Event |
| Grass | Player |
| Water | Boat |
| Grass | EV01 with layer=same |
| Water | |

Setup EV02 with `trigger=action` and code `SetMoveRoute: Player, Through On`

Board the boat, try to move the boat out of the water, face down, and try to disembark

Result: Despite having the through flag set, the player is not allowed to disembark into an obstacle. Also, while boarding the vehicle, the players through flag is ignored when the vehicle moves.

3. Change EV02 code to
```
SetMoveRoute: Player, Through On
SetMoveRoute: Boat, Through On
```

Board the boat, try to move around, and then try to disembark into the obstacle

Result: With the boat's through flag set, now the boat is able to move anywhere. However the player is still prevented from disembarking onto obstacles.

4. Put the ship and airship in the water.

Board the board and try to step over the ship or airship

Result: Boat cannot step onto same tile as ship and airship

5. Disembark table

What is the player allowed to disembark onto?

| Tile | Event layer | Event graphic | Result |
| Blocked | | | No |
| pass | | | Yes |
| pass | below | sprite | Yes |
| pass | same | sprite | No |
| pass | above | sprite | Yes | 
| block | below | sprite | No |
| block | same | sprite | No |
| block | above | sprite | No | 
| pass | below | pass tile | Yes |
| pass | same | pass tile | No |
| pass | above | pass tile | Yes | 
| block | below | pass tile | Yes |
| block | same | pass tile | No |
| block | above | pass tile | No | 
| pass | below | pass above tile | Yes |
| pass | same | pass above tile | No |
| pass | above | pass above tile | Yes | 
| block | below | pass above tile | No |
| block | same | pass above tile | No |
| block | above | pass above tile | No | 
| pass | below | impass tile | No |
| pass | same | impass tile | No |
| pass | above | impass tile | Yes | 
| block | below | impass tile | No |
| block | same | impass tile | No |
| block | above | impass tile | No | 
| block | ship | ship | No |
| block | airship | airship | No |
| pass | ship | ship | Yes |
| pass | airship | airship | Yes |

6. Setup thes tiles


| Tile | Event |
| Grass | Player |
| Water | Boat |
| Grass | EV02 with layer=same |
| Grass | |

Setup EV01 as parallel
```
If boat is boarded:
  Wait 0.1s  
  SetMoveRoute; Player, Turn Down
  Wait 0.1s
  GetOnOffVehicle
  SetMoveRoute: EV02, Down
  EraseEvent
```

Result: EV02 moves and player *does not* disembark
 
7. Change EV01 to
Setup EV01 as parallel
```
If boat is boarded:
  Wait 0.1s  
  SetMoveRoute; Player, Turn Down
  Wait 0.1s
  SetMoveRoute: EV02, Down
  Wait 0.0s
  GetOnOffVehicle
  EraseEvent
```

Result: EV02 moves and player disembarks

Conclusions
--------------

Disembarking the ship is very similar to normal collision but there appears some differences:
* Events do not update out of order to move out of the way
* You can disembark onto other vehicles even when you normally cannot step over them.

**Comment by fmatthew5876** [comment]
Test Cases 10 - Tile events and through
------------------------------

1. Tile graphics and through

Setup EV01 as `trigger=action`
```
Transfer EV03 to E04
SetMoveRoute: *THROUGH*
```

Create EV03 and EV04 as `layer=below`. Put EV03 on a grass tile.

| Lower Tile | EV03 Graphic | EV03 Through | EV04 graphic | EV04 through | Result |
| -- | -- | -- | -- | -- | -- |
| pass | impass tile | 0 | impass tile | 0 | blocked |
| pass | impass tile | 0 | impass tile | 1 | blocked |
| pass | impass tile | 1 | impass tile | 0 | blocked |
| pass | impass tile | 1 | impass tile | 1 | pass |
| pass | pass tile | 0 | impass tile | 0 | blocked |
| pass | pass tile | 0 | impass tile | 1 | pass |
| pass | pass tile | 1 | impass tile | 0 | blocked |
| pass | pass tile | 1 | impass tile | 1 | pass |
| pass | impass tile | 0 | pass tile | 0 | pass |
| pass | impass tile | 0 | pass tile | 1 | blocked :question: |
| pass | impass tile | 1 | pass tile | 0 | pass |
| pass | impass tile | 1 | pass tile | 1 | pass |

2. Now put EV03 on a water tile

| Lower Tile | EV03 Graphic | EV03 Through | EV04 graphic | EV04 through | Result |
| -- | -- | -- | -- | -- | -- |
| blocked | pass tile | 0 | pass tile | 0 | pass |
| blocked | pass tile | 0 | pass tile | 1 | pass |
| blocked | pass tile | 1 | pass tile | 0 | pass |
| blocked | pass tile | 1 | pass tile | 1 | blocked |
| blocked | pass tile | 0 | impass tile | 0 | blocked |
| blocked | pass tile | 0 | impass tile | 1 | pass |
| blocked | pass tile | 1 | impass tile | 0 | blocked |
| blocked | pass tile | 1 | impass tile | 1 | blocked |
| blocked | impass tile | 0 | pass tile | 0 | pass |
| blocked | impass tile | 0 | pass tile | 1 | blocked :question: |
| blocked | impass tile | 1 | pass tile | 0 | pass |
| blocked | impass tile | 1 | pass tile | 1 | blocked |

Conclusion
------------

The through flag removes the event from tile consideration.

**Comment by fmatthew5876** [comment]
Test Cases 11 - Events collide against vehicle while boarded behavior.
-------------------

1. Setup EV01 as parallel with this code:
```
Wait 0.1s
SetMoveRoute: EV02, Skip, Right
SetMoveRoute: Player, Right
Erase Event
```

Setup EV02 as `layer=same` setup tiles like

| Tile | Tile | Tile |
| -- | -- | -- |
| EV02 (Grass) | Player (Grass) | (Grass) | 

Result: EV02 and player move right.

EV02 move route triggers player update to run and move the player.

2. Change EV01 to this:
```
Wait 0.1s
SetMoveRoute: EV02, Skip, Right
SetMoveRoute: Boat, Right
Erase Event
```
Now setup the tiles like this:

| Tile | Tile | Tile |
| -- | -- | -- |
| EV02 (Grass) | Boar (Grass) | (Water) | 

Result: EV02 and boat move right.

EV02 move route triggers boat update to run and move the player.

3. Change EV01 to this:
```
if boat is boarded:
  Wait 0.1s
  SetMoveRoute: EV02, Skip, Right
  SetMoveRoute: Boat, Right
  Erase Event
```

Board the boat.

Result: Boat moves, but EV02 does not

EV02 move route triggers boat update to run, but since the boat is boarded the move route is applied to the player. So the boat update routine does nothing, EV02 is blocked, and then the player moves, which moves the boat

Conclusion:
---------------

When vehicle is boarded, the player is removed from make way calculations. Other events collide against the vehicle and not the player.

**Comment by fmatthew5876** [comment]
Test Cases 12 - Boat / Ship Embark
----------------------------------------------

1. What prevents embarking the ship?

The ship cannot be embarked if certain conditions hold on the current tile.

| Tile | Event layer | Event graphic | Result |
| -- | -- | -- | -- |
| Passable | | | Yes |
| Not passable | | | No |
| Passable | same | ANY | yes |
| Passable | below | pass tile | yes |
| Passable | below | pass above tile | yes |
| Passable | below | impass tile | no |
| Passable | below | impass above tile | yes |
| Not Passable | below | pass tile | yes |
| Not Passable | below | pass above tile | no |
| Not Passable | below | impass tile | no |
| Not Passable | below | impass above tile | no |

Conclusion:
-----------

Embark does a current tile check (including event tiles) before allowing the action to happen.

**Comment by fmatthew5876** [comment]
Test Cases 13 - SyncWithPlayer behavior
-------------------

Set these tiles

| Tile | Tile |
| -- | -- |
| Player / Grass | |
| Boat / Water | EV02 / Grass |

Setup EV01 as parallel
```
If boat is driven
  Wait 0.4s
  SetMoveRoute: EV02, Left
  SetMoveRoute: Player, Left
  Loop:
    OpenSaveMenu
```

Board the boat

| Save | player stop count | player remaining step | boat stop count | boat remaining step | EV02 stop count | EV02 remaining step |
| -- | -- | -- | -- | -- | -- | -- |
| 1 | 0 | 224 | 0 | 224 | 65536 | 0 |
| 2 | 0 | 192 | 0 | 192 | 65536 | 0 |

On the first save, EV02 collides with the boat, causing it to update before Player. Despite this, RPG_RT still animates the boat movement properly.

**Comment by fmatthew5876** [comment]
Re-opening until these are covered by unit tests
