### ISSUE TITLE
Events with negative coordinates are rendered

### ISSUE THREAD

**Issue by elvissteinjr** [EasyRPG/Player#1676]
EasyRPG renders events with negative coordinates at map width + x and map height + y.

RPG_RT seems to only do this if the event's position is in the repeat direction of the map.
In those cases, the event is always passable and can't be interacted with in RPG_RT while it behaves normal as if it was positioned there in EasyRPG.

**Comment by fmatthew5876** [comment]
How do you actually produce an event with negative coordinates?

**Comment by elvissteinjr** [comment]
Set Event Place with variables containing negative values is one way.

This can be useful to get events out of the way when you for example have something that executes events in front of the Hero unconditionally.

In a practical example, I did use this years back in Stimme der Untoten/Stimme der Untoten 2. One of the events moved that way had a graphic and had only its position set back to the map when needed. 
While it might've been smarter to also have a switch to make that not render for sure, for now there's a event hanging around in the lower right corner of every map instead for these games when running in EasyRPG.

**Comment by fmatthew5876** [comment]
I checked and it works. SetEventLocation with negative values actually sets position chunks to negative.

If you set x=-1 RPG_RT will still render the rightmost 8 pixels.

If you set y=height, RPG_RT will still render the top half of the Sprite in the bottom row.

**Comment by elvissteinjr** [comment]
Might've worded it confusingly, but my main gripe is that EasyRPG always does it, while RPG_RT only does it when it gets in the way of repeating a map (i.e. X negative on h-repeat or Y negative on v-repeat). 

Such events are not rendered at all on non-repeating maps for example.
At least in RPG_RT 2000 v1.05 and RPG_RT 2003 v1.07.

**Comment by Ghabry** [comment]
the good news is that I didn't break this with my "Sprite clones" PR which fixes the rendering on looping maps because this codepath is only used on looping maps.
