### ISSUE TITLE
Fix Battle Console timings in 2k battles

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1677]
Our timings for the rm2k battle console messages are not frame accurate.

Cherry was nice enough to outline a method for extracting these timings from RPG_RT in #1568 

I've done this, and my findings are here:

Startup:
Slime appeared
Wait(4, 4) - Wait before text
Wait(30, 70) - Wait after first line

Slime appeared - first strike
Wait(4, 4) - Wait before text
Wait(30, 70) - Wait after first line
Wait(30, 70) - first strike msg

2 slimes appeared
Wait(4, 4) - Wait before text
Wait(8, 8) - Wait after first line
Wait(30, 70) - Wait after last line

Very long word wrapped lines
Wait(4, 4) - Wait before text
Wait(8, 8) - Wait after first line
Wait(8, 8) - 2nd line
Wait(8, 8) - 3rd line
Wait(30, 70) - Full page
Wait(4, 4) - Empty page
Wait(8, 8) - 1st line
Wait(30, 70) - 2nd line - done

Escape:
Multilines printed immediately
Wait(10,60)

Hero Attack - enemy none
Wait(4,4) - empty
Wait(20,40) - Attacks (text not on screen when wait called)
Wait(4,4) - next action?
Wait(4,4) - next action? (after critical maybe)
Wait(20,40) - Damage
Wait(0, 10) - post dmg
Wait(4, 4) - Enemy none action

Attack critical - enemy none
Wait(4,4) - empty
Wait(20,40) - Attacks (text not on screen when wait called)
Wait(4,4) - next action?
Wait(10,30) - critical
Wait(4,4) - next action?
Wait(20,40) - Damage
Wait(0, 10) - post dmg
Wait(4, 4) - enemy none

Enemy none - attack critical miss
Wait(4, 4) - Enemy nothing action
Wait(4, 4) - pre
Wait(20,40) - Attacks (text not on screen when wait called)
Wait(4,4) - delay
Wait(4,4) - 2nd delay likely intended for critical but still happens with no crit
Wait(20,60) - Dodge

Attack - Double crit
Wait(4, 4)
Wait(20, 40) Attakcs
Wait(4, 4)
Wait(10, 30) crtic
Wait(4, 4)
Wait(20, 40) damage
Wait(0, 10)
Wait(4, 4) Pre - attack msg shown
Wait(10, 30) crtic 2
Wait(4, 4)
Wait(20, 40) damage
Wait(0, 10)
Wait(4, 4) E1 none
Wait(4, 4) E2 none

Attack All 
Wait(4, 4) - Pre
Wait(20, 40) - Attack
Wait(4, 4)
Wait(10, 30) - Crit
Wait(4, 4)
Wait(20, 40) - Dmg
Wait(0, 10) - Post dmg
Wait(4, 4)
Wait(10, 30) - Crit 2
Wait(4, 4)
Wait(20, 40) - Dmg
Wait(0, 10) - Post dmg

Enemy none - defend
Wait(4, 4) - Enemy flash
Wait(4, 4)
Wait(20,60) - Defend message
Wait(4,4) - next action?
Wait(4,4) - next action?
Wait(20,60) - Dodge

Defend - enemy none
Wait(4, 4) - Pre
Wait(20, 60) - Defend message
Wait(4, 4) - Enemy nothing action

Defend - enemy none, enemy none
Wait(4, 4) - Pre
Wait(20, 60) - Defend
Wait(4, 4) - e1 none
Wait(4, 4) - e2 none

Enemy attack
Wait(4, 4) - Enemy flash
Wait(20, 40) - Attack
Wait(4, 4)
Wait(10, 30) - criti
Wait(4, 4)
Wait(20, 40) - damage
Wait(0, 10) - post damage
Wait(4, 4)
Wait(20, 60) - Player defend

Enemy dbl attack - player defend
Wait(4, 4)
Wait(20, 40) - attack
Wait(4, 4)
Wait(10, 30) - crit
Wait(4, 4)
Wait(20, 40) - dmg
Wait(0, 10) - post dmg
Wait(4, 4)
Wait(10, 30) crit
Wait(4, 4)
Wait(20, 40) -dmg
Wait(0, 10) -post dmg
Wait(4, 4)
Wait(20, 60) - hero defend

Enemy defend - hero defend
Wait(4, 4)
Wait(20, 60)
Wait(4, 4)
Wait(20, 60)

Enemy watch - hero defend
Wait(4, 4)
Wait(20, 60)
Wait(4, 4)
Wait(20, 60)

Enemy charge - hero defend
Wait(4, 4)
Wait(20, 60)
Wait(4, 4)
Wait(20, 60)

Enemy explode -
Wait(4, 4)
Wait(20, 60) - Self destruct msg
Wait(4, 4)
Wait(4, 4)
Wait(20, 40) - dmg
Wait(0, 10) - post dmg

Enemy escape
Wait(4, 4) - flash
Wait(36, 60) - escape msg

Hero attack causes 2 states
Wait(4, 4)
Wait(20, 40)
Wait(4, 4)
Wait(10, 30)
Wait(4, 4)
Wait(20, 40)
Wait(0, 10)
Wait(4, 4)
Wait(20, 60) - state 1 - Multiple states same line
Wait(4, 4)
Wait(20, 60) - state 2

Has state message - enemy
Wait(4, 4) - Flash occurs - is skipped if enemy has no algo
Wait(20, 60)

State healed - enemy
Wait(4, 4)
Wait(20, 60)

Hero attack and kill enemy
Wait(4, 4)
Wait(20, 40) - attack
Wait(4, 4)
Wait(10, 30) - crit
Wait(4, 4)
Wait(20, 40) - dmg
Wait(36, 60) - death
Wait(0, 10) - post dmg

Hero uses healing item
Wait(4, 4)
Wait(20, 60) - use item
Wait(4, 4)
Wait(20, 60) - heal msg

Hero uses healing item
Wait(4, 4)
Wait(20, 60) - use item
Wait(4, 4)
Wait(20, 60) - heal hp
Wait(4, 4)
Wait(20, 60) - heal mp

Hero uses healing item
Wait(4, 4)
Wait(20, 60) - use item
Wait(4, 4)
Wait(20, 60) - ally revived

Hero cures poison
Wait(4, 4)
Wait(20, 60) - hero is poisoned msg
Wait(4, 4)
Wait(20, 60) - use item
Wait(4, 4)
Wait(20, 60) - heal poison

Hero uses revive skill
Wait(4, 4)
Wait(20, 60) - skill msg
Wait(4, 4)
Wait(20, 60) - ally revived

Hero uses revive skill w double msg
Wait(4, 4)
Wait(20, 60) skill msg 1
Wait(20, 60) skill msg 2
Wait(4, 4)
Wait(20, 60) ally revived

Hero uses attack skill
Wait(4, 4)
Wait(20, 60) - skill msg
Wait(4, 4)
Wait(20, 40) - dmg
Wait(0, 10) - post effects

Hero uses skill to raise stat
Wait(4, 4)
Wait(20, 60) - skill msg
Wait(4, 4)
Wait(20, 60) - INT Up

Hero uses attack skill
Wait(4, 4)
Wait(20, 60) - skill msg
Wait(4, 4)
Wait(20, 40) - dmg
Wait(0, 10) - post dmg
Wait(4, 4)
Wait(20, 60) - mp
Wait(4, 4)
Wait(20, 60) - atk
Wait(4, 4)
Wait(20, 60) - def
Wait(4, 4)
Wait(20, 60) - agi
Wait(4, 4)
Wait(20, 60) - int
Wait(4, 4)
Wait(20, 60) - holy down
Wait(4, 4)
Wait(20, 60) - blind

Hero uses attack skill
Wait(4, 4)
Wait(20, 60) - skill msg
Wait(4, 4)
Wait(20, 60) - absorb hp
Wait(0, 10) - post dmg
Wait(4, 4)
Wait(20, 60) - absorb mp

Hero uses attack skill
Wait(4, 4)
Wait(20, 60) - skill msg
Wait(4, 4)
Wait(20, 60) - absorb hp
Wait(36, 60) - kill enemy
Wait(0, 10) - post dmg

Hero uses attack skill with no msg
Wait(4, 4)
Wait(20, 60) - waits for empty msg
Wait(4, 4)
Wait(20, 40) - dmg
Wait(36, 60) - kill
Wait(0, 10) -post

Hero uses kill skill
Wait(4, 4)
Wait(20, 60) - skill msg
Wait(36, 60) - death msg
Wait(4, 4)
Wait(20, 60) - Nothing??

Hero uses kill + dmg skill - damage was not lethal
Wait(4, 4)
Wait(20, 60) - skill msg
Wait(4, 4)
Wait(20, 40) - dmg
Wait(0, 10) - post dmg
Wait(36, 60) - kill state
Wait(4, 4)
Wait(20, 60) - ???

Hero uses kill + dmg skill - damage was lethal
Wait(4, 4)
Wait(20, 60) skill msg
Wait(4, 4)
Wait(20, 40) dmg
Wait(36, 60) death
Wait(0, 10) post dmg

Hero defends - enemy has no actions and state recovers with no message
Wait(4, 4)
Wait(20, 60) - hero defend
Wait(4, 4) - enemy flashes
Wait(20, 60) - enemy state recovered - no message

Hero defends - enemy has no actions but state with no "is active" message
Wait(4, 4)
Wait(20, 60) - hero defend
NOTE: Enemy never gets a turn and no delays!

Hero defends - enemy has no actions but state with "is active" message
Wait(4, 4)
Wait(20, 60) - hero defend
Wait(4, 4) - enemy flashes
Wait(20, 60) state is active message

Enemy attacks hero - no damage because of high defense
Wait(4, 4)
Wait(20, 40) - attack msg
Wait(4, 4)
Wait(10, 30) - crit
Wait(4, 4)
Wait(20, 40) - no damage message
Wait(0, 10) - post dmg wait

**Comment by CherryDT** [comment]
Just a guess - the "???" may be this:

![image](https://user-images.githubusercontent.com/6010463/54073167-92f69900-428c-11e9-9b56-4327e1c4a8b6.png)

**Comment by CherryDT** [comment]
I wonder what happens if you set these greyed-out values in the LDB file manually.

**Comment by fmatthew5876** [comment]
The already inflicted message doesn't wait if it's empty I believe?

I think it's actually "state inflicted". But death has a special case wait(36, 60).

I think it's a bug where all states inflicted have a Wait(20, 60). Death should be excluded since it was already printed.

You'll notice there is no phantom Wait(20, 60) when death is caused by damage.

**Comment by CherryDT** [comment]
Yes you are right. I verified it now and it looks like it's like this:

* Status is actually inflicted (infliction of state 1 always causes HP to drop to 0)
* If HP are zero (which is true now), the death display is done
* If HP are nonzero (which is false now), the status infliction display is done
* Wait(20, 60) (unconditionally)

**Comment by fmatthew5876** [comment]
Cherry, do you know why there is an extra Wait(0,10) after damage message is printed?

It seems to also happen after death if the damage is lethal

If damage not lethal
Wait(20,40) - dmg
Wait(0,10) - post dmg

If damage was lethal
Wait(20,40) - dmg
Wait(36,60 - death
Wait(0, 10) - post dmg

Is there something special that happens before that last Wait(0, 10) that they had to split it out this way?

**Comment by CherryDT** [comment]
Death (as you already discovered) and hit-induced state recovery are indicated in between.

**Comment by fmatthew5876** [comment]
Test Cases 1 - Physical attacks and states
------------------------------------

1. Setup Confuse and Provoke with 100% infliction, 100% healed by damage. Make a weapon that inflicts both Confuse and Provoke. Make Alex 1 in 1 Critical hit.

Setup a battle event on Turn 0, which inflicts Confuse and Provoke on the enemy.

Finally, attack the enemy with Alex

Wait(4,4)
Wait(20,40)
```
Alex Attacks
```
Wait(4,4)
Wait(10,30)
```
Alex Attacks
Alex Inflicted a Critical Hit!
```
Wait(4,4)
Wait(20,40)
```
Alex Attacks
Alex Inflicted a Critical Hit!
Slime took 50 damage!
```
Wait(4,4)
Wait(20,40)
```
Alex Attacks
Alex Inflicted a Critical Hit!
Slime took 50 damage!
Slime calmed down!
```
Wait(4,4)
```
Alex Attacks
Alex Inflicted a Critical Hit!
Slime took 50 damage!
```
Wait(20,40)
```
Alex Attacks
Alex Inflicted a Critical Hit!
Slime took 50 damage!
Slime came to their senses!
```
Wait(0,10)
Wait(4,4)
```
Alex Attacks
Alex Inflicted a Critical Hit!
```
Wait(20,60)
```
Alex Attacks
Alex Inflicted a Critical Hit!
Slime was Provoked!
```
Wait(4,4)
```
Alex Attacks
Alex Inflicted a Critical Hit!
```
Wait(20,60)
```
Alex Attacks
Alex Inflicted a Critical Hit!
Slime was confused!
```

**Comment by fmatthew5876** [comment]
Test Cases 2 - 2 weapons and state infliction rules
------------------

Create State X with rating 40, 100% infliction rate
Create State Y with rating 50, 100% infliction rate, with higher id than X
Create State Z with rating 40, 100% infliction rate, with higher id than Y
WeaponX with 100% inflict state X
WeaponY with 100% inflict state Y
WeaponZ with 100% inflict state Z

1. What happens when we attack slime with these weapons?

| Weapon1 | Weapon 2 | State inflicted message printed? |
| -- | -- | -- |
| X | Y | X, Y |
| X | Z | X, Z |
| Y | X | Y, X |
| Y | Z | Y |
| Z | X | X, Z |
| Z | Y | Y |

Conclusions:
-------------------

* For multiple weapons, states are applied in order.
* If S1.priority < S2.priority - 10, S1 is still applied and then immediately removed by S2
* If S1.priority > S2.priority - 10, S1 is applied, and then S2 is ignored since S1 super cedes it.

**Comment by fmatthew5876** [comment]
Test Cases 3 - 2 weapons and `reverse_state_effect` behavior
-----------------------

Create state X, 100% infliction rate
WeaponX with 100% inflict state X
WeaponY with 100% heal state X

1. What happens when we attack slime with these weapons?

| Weapon1 | Weapon2 | Slime has state? |
| -- | -- | -- |
| X | Y | No |
| Y | X | Yes |

Conclusion:
------------------

* States are applied first by state id and then by weapon slot.

**Comment by fmatthew5876** [comment]
Test Cases 4 - Skills state infliction
-------------------------------------------------

Create State X with rating 40, 100% infliction rate
Create State Y with rating 50, 100% infliction rate, with higher id than X
Create State Z with rating 40, 100% infliction rate, with higher id than Y

Create skill XY inflicts X and Y
Create skill XZ inflicts X and Z
Create skill YZ inflicts Y and Z
Create skill XYZ inflicts X, Y, and Z

1. Use the skill on slime

| Skill | Printed to console |
| -- | -- |
| XY | Inflict X, Inflict Y |
| XZ | Inflict X, Inflict Z |
| YZ | Inflict Y |
| XYZ | Inflict X, Inflict Y |

2. Create a turn 0 battle event which inflicts a state on slime. Use the skill on slime.

| Turn0 inflicts | Skill | Printed to console |
| -- | -- | -- |
| X | XY | Already X, Inflict Y |
| X | XZ | Already X, Inflict Z |
| X | YZ | Inflict Y |
| X | XYZ | Already X, Inflict Y |
| Y | XY | Already Y |
| Y | XZ | |
| Y | YZ | Already Y |
| Y | XYZ | Already Y |
| Z | XY | Inflict X, Inflict Y |
| Z | XZ | Inflict X, Already Z |
| Z | YZ | Inflict Y |
| Z | XYZ | Inflict X, Inflict Y |

**Comment by fmatthew5876** [comment]
Test Cases 5 - Physical skills
------------------------------------------

1. Create a skill with 10 physical, affect hp, and 100% inflict poison, confuse, and provoke
Create a turn 0 event which inflicts poison, confuse, and provoke on slime

Use the skill on slime

Result:
Provoke healed
Confuse healed
Already poisoned
Provoke inflicted
Confuse added

**Comment by fmatthew5876** [comment]
Test Cases 6 - Enemy state messages + actions
----------------

1. Turn 0 event adds poison, set only action to wait

Wait(4,4)
Wait(20,60)
```
Slime has Poison!
```
Wait(4,4)
Wait(20,60)
```
Slime is watching!
```


2. Turn 0 event adds poison, set only action to do nothing

Wait(4,4)
Wait(20,60)
```
Slime has Poison!
```
Wait(4,4)


3. Turn 0 event adds poison, no actions

Wait(4,4)
Wait(20,60)
```
Slime has Poison!
```

**Comment by fmatthew5876** [comment]
Test Cases 7 - enemies with no actions
---------------

1. Enemy with no actions

Result: Nothing happens, enemy does not flash and no wait

2. Enemy with no actions and a state with no message

Result: Nothing happens, enemy does not flash and no wait

**Comment by fmatthew5876** [comment]
Test Cases 8 - Self destruct and states
-----------------

1. Setup enemy with self destruct
Add turn 0 event to set confuse and provoke on the party

Wait(4,4)
Wait(20,60)
```
Monster Fish Exploded!
```
Wait(4,4)
Wait(4,4)
Wait(20,40)
```
Monster Fish Exploded!
Alex took 37 damage!
```
Wait(4,4)
Wait(20,40)
```
Monster Fish Exploded!
Alex took 37 damage!
Alex calmed down!
```
Wait(4,4)
```
Monster Fish Exploded!
Alex took 37 damage!
```
Wait(20,40)
```
Monster Fish Exploded!
Alex took 37 damage!
Alex came to their senses!
```
Wait(0,10)
