### ISSUE TITLE
Fix Battle Shake

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1678]
In battle 2k, the screen shakes when the player takes damage.

- [ ] Verify our shake is accurate

In Player we do ShakeOnce(5 power, 5 speed, 6 frames). I have no idea if this is accurate. @CherryDT how can we verify the correct shake parameters used for this?

- [x] Verify how this shake interacts with map shake

We use the same function as map shake, which could end up canceling map shake.

Run some experiments by triggering battles with an active shake on the map, figure out what `RPG_RT` does, and emulate it properly.

**Comment by CherryDT** [comment]
I think it was 3,5,8
And there is only one shake, so I think it overrides the map shake, although I don't know how it interacts with continuous shake in 2k3

**Comment by fmatthew5876** [comment]
I checked `RPG_RT` and player with a long shake followed by a battle.

The shake continues in the battle. Once an enemy hits the player, the enemy shake cancels the long shake. So we're compatible on this point.
