### ISSUE TITLE
Above tile events should be drawn below non-above tile events

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1683]
Issue summary:

- [x] Draw order of above and non-above tile events is wrong
- [x] Airship and shadow are drawn under above events while flying

Create EV01 as `layer=below` with a passable but not above tile graphic.
Create EV02 as `layer=below` with an above tile graphic (passable or not)

Setup another event to place EV01 and EV02 on the same tile.

In RPG_RT, EV01 is drawn ontop of EV02
In Player, EV02 is drawn ontop of EV01

**Comment by Ghabry** [comment]
What is a above tile? Do you mean star tile?
Does the same happen when 1 and 2 are swapped?

2k3e made some changes to make the render order of events more consistent. When there is sth rendering related Also check with older 2k3 versions if the result is  consient or random.

**Comment by fmatthew5876** [comment]
I mean star tiles.

I tested this with rm2ke.

Its broken the other way too.
If EV01 is above tile and EV02 is not

RPG_RT shows EV01 above EV02
Player shows EV02 above EV01

**Comment by fmatthew5876** [comment]
There are also graphical glitches with the airship.

In Player, events with `layer=above` are rendered overtop of the airship and its shadow while it is flying.

**Comment by Ghabry** [comment]
#1577 could be related

**Comment by fmatthew5876** [comment]
Test Cases 1 - Both Sprites
==============

Setup EV01 and EV02 as sprites - place them ontop of each other

| EV01 layer | EV02 layer | top |
| -- | -- | -- |
| below | below | EV02 |
| below | same | EV02 |
| below | above | EV02 |
| same | below | EV01 |
| same | same | EV02 |
| same | above | EV02 |
| above | below | EV01 |
| above | same | EV01 |
| above | above | EV02 |

**Comment by fmatthew5876** [comment]
Test Cases 1 - Both Tiles
==============

Setup EV01 and EV02 as below tiles - place them ontop of each other

| EV01 layer | EV02 layer | top |
| -- | -- | -- |
| below | below | EV02 |
| below | same | EV02 |
| below | above | EV02 |
| same | below | EV01 |
| same | same | EV02 |
| same | above | EV02 |
| above | below | EV01 |
| above | same | EV01 |
| above | above | EV02 |

**Comment by fmatthew5876** [comment]
Test Cases 3 - Tiles and Sprites
==============

Make EV01 a sprite and EV02 a below tile


| EV01 layer | EV02 layer | top |
| -- | -- | -- |
| below | below | EV02 |
| below | same | EV02 |
| below | above | EV02 |
| same | below | EV01 |
| same | same | EV02 |
| same | above | EV02 |
| above | below | EV01 |
| above | same | EV01 |
| above | above | EV02 |

Make EV01 a below tile and EV02 a sprite

| EV01 layer | EV02 layer | top |
| -- | -- | -- |
| below | below | EV02 |
| below | same | EV02 |
| below | above | EV02 |
| same | below | EV01 |
| same | same | EV02 |
| same | above | EV02 |
| above | below | EV01 |
| above | same | EV01 |
| above | above | EV02 |

**Comment by fmatthew5876** [comment]
Now I can't reproduce the tile issues I saw before.. Maybe I made some mistake?

**Comment by Ghabry** [comment]
For 2 events on the same position with same layer the order is undefined, in RPG2k3E it is based on the event ID.
