### ISSUE TITLE
DBZ Legend of Z: Charge UP percentage skill cost

### ISSUE THREAD

**Issue by OmegaMagnusDA** [EasyRPG/Player#1684]
Name of the game: **Dragon Ball Z: Legend of Z RPG**

Player platform: **Android** and possibly others

-Download **DBZ LOZ (No music version)** for quickest download (third option) https://gamejolt.com/games/dragon-ball-z-legend-of-z-rpg/145494

-**Save(s)**: https://drive.google.com/open?id=1zb7NObjqhmKu_hjwl-TZ45SeExRvO2la (see skill in menu and/or roam around current map to test in battle)
https://drive.google.com/open?id=1nnymRrmyPsXMfICy5NARPjVZQsACRH-o (save with higher party levels)

-**easyrpg_log.txt log file**: https://drive.google.com/open?id=1O7Hr7P-puoby0-YWZQHLB1pKCR2AKyHJ

**Issue in detail** and how to reproduce it:
Issue from #1374 is half fixed. Charge UP now gives players the right amount of KI (MP), in recent update 0.6, but the skill cost is still stuck at 1 for all characters at all levels (percentage skill costs). 

![image](https://user-images.githubusercontent.com/48193819/54091221-bb3cd100-433a-11e9-8859-f9bb552f4694.png)

**Comment by fmatthew5876** [comment]
This is caused by this bad line of code:
https://github.com/EasyRPG/Player/blob/master/src/game_battler.cpp#L424

It should be `Player::IsRPG2k3()` and not checking a specific version.

I have a different idea for a fix however..

**Comment by carstene1ns** [comment]
Hmm, this has been in there since 2011, way before we had different engine modes (2k3e did not exist).
