### ISSUE TITLE
Files not listed in the RTP replacement tables are not found

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1709]
This issue affects modified or unknown RTPs, e.g. games using Don's RTP extras (there are quite a few) and Don's RTP 1.32.

How to reproduce:

Add some file to the RTP with a custom name not in RTP tables, then use this asset from a game.

A simpler way to reproduce this is by installing Don's RTP and run run Don's Adventures game.

Possibly related with #1630.

**Comment by carstene1ns** [comment]
Yes, before we still searched through the RTP folder for unknown files. A proper fix is more complicated, but a quick solution is to move the for loop back out of the `rtp_name` check here:
https://github.com/EasyRPG/Player/blob/85a40f04540fff286817e830fd63db5ebdc6950b/src/filefinder.cpp#L214-L233

Issue originally reported by @rohkea in IRC.

**Comment by Ghabry** [comment]
yeah this was not intentional
