### ISSUE TITLE
Switching to mruby.

### ISSUE THREAD

**Issue by take-cheeze** [EasyRPG/Player#171]
As discussed in #167 there is many things before moving code to mruby.

The biggest issue is that to run mruby version equally as current version.
I have many issues to discuss and share about it so this will need another issue to open.
It needs more unit tests.

Second problem is the build system.
Currently I'm using clang/gcc toolchain to build it but some people want other toolchain such as visual studio.
There is people working on it(https://github.com/mruby/mruby/pull/1574) though it's update will be slow than the minirake based clang/gcc toolchain.
And current build system like cmake/autotools won't be supported too.

**Comment by fdelapena** [comment]
The repository fork was marked as archived, so assuming this issue is stalled (no changes in 8 years).
