### ISSUE TITLE
Spinning Events always use middle stepping frame

### ISSUE THREAD

**Issue by elvissteinjr** [EasyRPG/Player#1711]
This worked fine in 0.6 and is broken in the current continuous build. Most likely due to the Move Route refactors?

To reproduce, simply create an event with animation type set to spinning and the character graphic to be on the left or right stepping frame. In RPG_RT, it will display the chosen stepping frame, but in the current Player builds it will revert to the middle one.

**Comment by fmatthew5876** [comment]
Thank you for the bug report. It was indeed a regression from move routes PR.

This is fixed in  #1712
