### ISSUE TITLE
Confinium: Minigame input not working properly

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1731]
Reported via Android Reviews.
Not verified yet if fixed.

---
Please fill in the following fields before submitting an issue:

Name of the game: Confinium (OFF fangame)
https://xintetsu.itch.io/confinium

#### Player platform:
Android (0.6.0)

#### Describe the issue in detail and how to reproduce it:

Reporting a bug I experienced from a game called CONFINIUM (- ACT 1) wherein zone pluto, a certain minigame is played where you must fire at the "Trinity" with your airplane. My problem is that you require to use the Enter key and early on through when I try to tap the A or B key, I lose control of the game and can't use the directional pad or or the A and B key

**Comment by Mimigris** [comment]
> Reported via Android Reviews. Not verified yet if fixed.
> 
> Please fill in the following fields before submitting an issue:
> 
> Name of the game: Confinium (OFF fangame) https://xintetsu.itch.io/confinium
> 
> #### Player platform:
> Android (0.6.0)
> 
> #### Describe the issue in detail and how to reproduce it:
> Reporting a bug I experienced from a game called CONFINIUM (- ACT 1) wherein zone pluto, a certain minigame is played where you must fire at the "Trinity" with your airplane. My problem is that you require to use the Enter key and early on through when I try to tap the A or B key, I lose control of the game and can't use the directional pad or or the A and B key

Said issue seems to have been fixed in version 0.6.2 of the Player, though I can't confirm with which commit it was actually fixed.

If you still want to check by yourself, here's a savefile just before said minigame. Interact with the plane to start the minigame.
[conf-trinity-issue.zip](https://github.com/EasyRPG/Player/files/10946829/conf-trinity-issue.zip)
