### ISSUE TITLE
Return of Touhou Mother - Midi-Tick Regression

### ISSUE THREAD

**Issue by PyredSalsa** [EasyRPG/Player#1733]
**Platform:** Android

Battles seem to hang again whenever normal attacks are used in Return of Touhou Mother. Something may have regressed the midi-tick fix in issue #744, judging by the way the game hangs whenever I try to combo with regular attacks.

**Comment by Ghabry** [comment]
Technically that's not a regression, Midi ticks never worked properly.
Guess the new midi tick behaviour (which is still wrong) is just worse than the old approximation (but was also completely wrong) :D

**Comment by PyredSalsa** [comment]
Oh, huh. I always thought it was fixed, since it was working just fine on an older version on Android. I guess it just wasn't as much of an issue, then? At the very least, I don't remember bumping into the issue at all.

Mind you, this was also a year or two ago, so I may not be remembering things very clearly.
