### ISSUE TITLE
Unimplemented 2k3 Fog and Sandstorm weather effects

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1737]
We have not implemented 2k3 Fog and Sandstorm effects.

Overall effects
- [x] Fog Overlay effect
- [x] Sand Overlay effect
- [x] Sand particle effect

Fog & Sand Overlay features:
- [x] Implement a noise function to generate Fog and Sand texture
- [x] Correct colors for Fog
- [x] Correct colors for Sand
- [x] Set correct opacities for strengths
- [x] Verify correct speed for upper layer left movement
- [x] Verify speed for lower layer right? movement
- [x] Correct timing for slow up/down movement (appears random)
- [x] Correct up / down random selection for Y movement.
- [x] Affected by Tone

Sand Particle features:
- [x] Implement a "good enough" version
- [x] Correct rate of particle generation
- [x] Correct angle
- [x] Correct speed
- [x] Correct colors
- [x] Correct size (1 pixel wide, 2 pixels tall)
- [x] Affected by Tone

**Comment by fmatthew5876** [comment]
@CherryDT

Do you have the particle math for these? Also how they interact with `SaveScreen_pan_x` and `y`?

Even for rain and snow, it would be good to verify we're correct.

**Comment by fmatthew5876** [comment]
Here are some truecolor screenshots

![mist1](https://user-images.githubusercontent.com/1198466/58384954-95c57800-7fb7-11e9-9879-698917d52d4b.png)
![mist2](https://user-images.githubusercontent.com/1198466/58384955-965e0e80-7fb7-11e9-9eb0-64e7956abed4.png)
![mist3](https://user-images.githubusercontent.com/1198466/58384956-965e0e80-7fb7-11e9-81e7-13f3de5ffda5.png)


These are not enough to rip the texture. In medium or weak mist, you can see pretty obviously that they are 2 layers of texture going in opposite directions. I'm not sure how we can tease them out of RPG_RT.

**Comment by elsemieni** [comment]
I don't know if it helps but I tweaked the intensity value modifing hex values at copypasting Weather Options in clipboard. The last byte in the command is the intensity (where 0x0, 0x1 and 0x2 is weak, medium strong). I set fog intensity at the max possible value 0x7F (more than that RPG Maker refuses me to paste the command with a "Error loading from stream" error... delphi things for sure). This is the result:

![image](https://user-images.githubusercontent.com/1494687/69294094-a6af1900-0be9-11ea-9f08-fc4dc91e7922.png)

For the other hand, 0x7F for sanstorm makes RPG_RT crash. 0x2D is the maximum value here, with this result.

![image](https://user-images.githubusercontent.com/1494687/69297841-f04c3380-0bea-11ea-84e8-1a29b5674474.png)

Tell me if you need to know other combination values.

**Comment by fmatthew5876** [comment]
Do you have the 24 bit true color version of RPG_RT? That will give the most accurate representation.

**Comment by elsemieni** [comment]
These ones are taken with the same parameters, at RPG_RT 1.08 32bit patch, as told in chat room.

Fog at 0x7F
![image](https://user-images.githubusercontent.com/1494687/69300181-399f8180-0bf1-11ea-8855-a5c1692993d7.png)

Sandstorm at 0x2D 
![image](https://user-images.githubusercontent.com/1494687/69300234-55a32300-0bf1-11ea-9391-bd3be04ef1cc.png)

Behind that is just black (transparent tile, no backdrop). Anyways, with these parameters looks like the effects are opaque. (In fact any value higher than 0x2).

**Comment by elsemieni** [comment]
Update: Also if it helps, I leave gif of these animations with the last parameters and 32 bit RPG_RT.

![fog](https://user-images.githubusercontent.com/1494687/69300736-d7478080-0bf2-11ea-9298-d3e57fc22a3b.gif)
![sandstorm](https://user-images.githubusercontent.com/1494687/69300737-d7478080-0bf2-11ea-873f-08d9c2896f8b.gif)

**Comment by fmatthew5876** [comment]
Test Cases 1 - Fog timing
----------------------

Make this parallel event
```
Wait 0.0s
Weather effect: Fog Strong
Wait 0.0s
Weather effect: none
```

Result:
Fog flickers on and off the screen, and still moves at same speed as if it were steady.

Conclusions
----------------

Fog effect animates continuously even when its turned off. Maybe based on frame timer or other time?

**Comment by fmatthew5876** [comment]
Tests 2 - Fog and transitions
------------

1. EV01 parallel
```
Weather: Fog Strong
Fade Out
Fade In
```

Result: Fog moves while the transition animates!

![fade](https://user-images.githubusercontent.com/1198466/71196051-35509d80-225d-11ea-81b7-0ebc1a39841e.gif)

Conclusion
------------

* Fog appears to be rendered during 
* Fog animation state likely keyed off of frame counter

**Comment by fmatthew5876** [comment]
Heres a very interesting RPG_RT bug, Apply a screen shake and the fog layers shake differently and you can see each individual layer. :exclamation: 


Here there are obviously 2 layers and the back layer is much darker than the foreground one. 

![shake_sand](https://user-images.githubusercontent.com/1198466/71053840-d0daf480-211d-11ea-84cf-67de8b1ca0b5.png)

You can reproduce this and have time to look at it with this kind of event

```
Weather effect
Shake Screen 9, 1
Wait some time (adjust this till you get a good snapshot
Loop:
  Hide Screen center out
  Show Screen scroll right
```

**Comment by fmatthew5876** [comment]
Fog Overlay Colors
-------------

Fog layers, using true color RPG_RT and screen shake to extract them.

![truelayer](https://user-images.githubusercontent.com/1198466/71059414-d55cd880-2130-11ea-8c24-7beae7b12c97.png)
![truesand](https://user-images.githubusercontent.com/1198466/71187816-d59ec600-224d-11ea-8425-e916ccdd5956.png)


Looking at this, it's obvious there are 2 layers. 

For fog, the colors are all greyscale RGB values, so I list one channel in this table. 3 colors only. I list each of the 3 colors here:

| Layer | Weak | Mid | Strong | 3 | 4 |
| -- | -- | -- | -- | -- | -- |
| Back All Colors |  (29, 30, 36) | (58, 60, 64) | (87, 90, 96) | (58, 60, 64) | (58, 60, 64) |
| Front All Colors | (58, 60, 64) | (72, 75, 80) | (144, 150, 160) | (230, 240, 255) | (115,120, 128) |

For sand, we have yellow colors

| Layer | Weak | Mid | Strong | 3 |
| -- | -- | -- | -- | -- |
| Back Color1 |  (28, 28, 20) | (55, 55, 40) | (83, 83, 60) | (55, 55, 40) |
| Back Color2 |  (29, 29, 21) | (58, 58, 43) | (87, 87, 64) | (58, 58, 43) |
| Back Color3 |  (30, 30, 23) | (60, 60, 45) | (90, 90, 68) | (60, 60, 45) |
| Front Color1 | (55, 55, 40) | (69, 69, 50) | (138, 138, 100) | (220, 220, 160) |
| Front Color2 | (58, 58, 43) | (72, 72, 53) | (144, 144, 106) | (230, 230, 170) |
| Front Color3 | (60, 60, 45) | (75, 75, 56) | (150, 150, 113) | (240, 240, 180) |

For strength > 2 you have to hack the LSD file. At 3, we get full opacity. It looks like 4 and beyond are strange overflowing behavior.

Using screen captures from Player and gimp, I've determined the alpha values (in range of 0 to 255) are:

| Layer | Weak | Mid | Strong | 3 (hacked into LSD) |
| -- | -- | -- | -- | -- |
| Back | 32 | 64 | 96 | 64 |
| Front | 64 | 80 | 160 | 255 |

**Comment by fmatthew5876** [comment]
Fog overlay generation
-------------------------

Here is another discovery, the fog appears not be a texture, but instead some 16x16 procedurally generated noise.

I have a save game with strength=3 hacked in. I loaded the save 3 times and got 3 results:

![pat1](https://user-images.githubusercontent.com/1198466/71056345-e6085100-2126-11ea-861e-3a7d776be853.png)
![pat2](https://user-images.githubusercontent.com/1198466/71056346-e6085100-2126-11ea-8e5e-b3f7641f170e.png)
![pat3](https://user-images.githubusercontent.com/1198466/71056347-e6085100-2126-11ea-8636-a7a22bce8435.png)

The Fog Colors are:
* (230,230,230)
* (240,240,240)
* (255,255,255)

The Sand Colors are:
* (220,220,160)
* (230,230,170)
* (240,240,180)

**Comment by fmatthew5876** [comment]
Sand particle colors
-------------------------

There are 4 sand particles: white, red, yellow, and orange

The pixel values however appear to vary.

Here are some sand particle colors with strength=3

| Name | Color1 | Color2 | Color3 | Color 4 |
| -- | -- | -- | -- | -- |
| White | (252,252,233) | (251,251,233) | (249,249,222)  | (249,249,225) |
| Red | (250,75,62) | (252,77,64) | (251, 93, 76) | (249, 84, 68) |
| Yellow | (248, 248, 72) | (245, 245, 69) | (251, 251, 74) | (248, 248, 72) |
| Orange | (247, 190, 64) | (252, 195, 69) | (246, 191, 65) | (247, 190, 64) |

The particles get slightly darker at lower strength levels. Here are some samples

| Name | Weak | Mid | Strong | 3 |
| -- | -- | -- | -- | -- |
| White | (212,212,196) | (235, 235, 218 ) | (237, 237, 214) | (249,249,225) |
| Red | (207, 46, 40) | (221, 53, 45) | (239, 62, 52) | (249, 84, 68) |
| Yellow | (205, 205, 40) | (218, 218, 45) | (236, 236, 57) | (248, 248, 72) |
| Orange | (204, 151, 39) | (221, 164, 44) | (234, 178, 55) | (247, 190, 64) |

**Comment by Ghabry** [comment]
RPG Maker 2003 feature and full of bugs (animated during transitions??? and broken during shake). I see a pattern here

**Comment by fmatthew5876** [comment]
Some observations about sand particles

* They appear some small distance out from  (160,0)
* They increase speed as they move from the origin

**Comment by fmatthew5876** [comment]
I've verified that our fog noise function is RPG_RT accurate. RPG_RT just calls `Rand(0, 2)` for each pixel..

DynRPG address is `RPG_ScreenEffect::Create` at 004C2634
