### ISSUE TITLE
VD2 screen never stop shaking after cutscene

### ISSUE THREAD

**Issue by Tondorian** [EasyRPG/Player#1743]
Please fill in the following fields before submitting an issue:
#### Name of the game:
Vampires Dawn 2 - Ancient Blood
#### Player platform:
Windows, Linux, Android, ...
Tested on switch and windows x64

windows works fine
switch never stop shaking

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
[saveLog.zip](https://github.com/EasyRPG/Player/files/3059764/saveLog.zip)

#### Describe the issue in detail and how to reproduce it:
The screen start to shake in the cutscene but on my switch this effect never stops.
On the windows x64 build it works fine. 

Save 3 is dumped before the cutscene started yust walk down a bit and skip the dialogues
Save 2 is the one taken from switch after the cutscene is finished

**Comment by Tondorian** [comment]
I was not able to reproduce it on my switch twice. i guess it was some wired race conditon.
But save 2 is still broken

**Comment by fmatthew5876** [comment]
Could this be some kind of frame skipping bug? Do we do that on low power platforms like switch?

**Comment by Tondorian** [comment]
yes this bug happend on my switch but only once, maybe power was low but i do not remember if this might be the reason, i could not reproduce this with 3x speed so i guess it was an unlucky event.

**Comment by Ghabry** [comment]
Frame skipping only affects ``Draw`` but maybe you see something in one of the Draw functions that looks suspicious and should be in update instead.

**Comment by fmatthew5876** [comment]
Well one thing I see already is that game_screen Reset doesn't clear the shake chunks.

**Comment by fmatthew5876** [comment]
@Tondorian 

At which point in the cutscene does the continuous shake start? I played all the way through, walking down, up into the castle, and then back down the hills again when the hero tries to escape.

**Comment by fmatthew5876** [comment]
I found it, this is caused by the ShakeOnce command at the beginning of the cutscene.

Normally a 2k3 shake once looks like this:
```
0000: code=ShakeScreen(11050) indent=0 str="" params=[5 5 2 1 0]
```

But in this game, params size is only 4.
```
0084: code=ShakeScreen(11050) indent=0 str="" params=[5 5 2 0]
```

The bug is caused by an uninitialized read of `params[4]` which explains why it occurs randomly.

Maybe this game was originally 2k and then ported to 2k3?

**Comment by Tondorian** [comment]
> Maybe this game was originally 2k and then ported to 2k3?
The first game was a 2k game so it might be possible the dev used the old game as a base and changes to 2k3 later.
if it is related to #1668 i wonder why loading my "currupted" save is fixed by rpg_rt.exe 
i guess rpg_rp supports continuous shake?

**Comment by fmatthew5876** [comment]
How do you mean? I loaded your `Save02.lsd` in RPG_RT and it shakes.

**Comment by Tondorian** [comment]
oh i see the origiginal rpg_rt coninues the shaking but the 64bit version for better fullscreen support (https://downloads.brianum.de/vampiresdawn/RPG_RT64.exe) stops the shaking (also mentioned on the vd dl page)

**Comment by Ghabry** [comment]
That RPG_RT64.exe is some old EasyRPG Player version, not suitable for such tests obviously as the shaking wasn't saved before.

**Comment by Tondorian** [comment]
good to know as they do not give any credits and call it RPG_RT.
And even better to know i should avoid using it. thank you

**Comment by Ghabry** [comment]
I just checked, they replaced the startup logo and the exe logo which makes it less obvious.
Well that's not the proper way to ship GPLv3 based executables but you can see that it is EasyRPG Player by pressing F (fast forward) or F4 (look at the title bar) or by looking at a easyrpg_log.txt.

**Comment by Tondorian** [comment]
well i use easy rpg in most cases anyway so there is always a log file. my assumption was they use binaries from a more rescent version of rpgmaker 2003 and as 2000 and 2003 are quite simular it uses the harmony dll use the right battlesystem. i never thought they would use easyRPG without any comments.

**Comment by carstene1ns** [comment]
Just saying: Changing the startup logo currently counts as source code modification, also the GPL says they need to mark modified versions as such and ship the license… → We could sue them.

**Comment by Tondorian** [comment]
i am not quite sure if they even know they distribute a modified version … some member mentioned easyRPG and that he have no clue how the x64version of RPG_RT works and the mod did not commente anything that they are the same. But at least we might contact them and say they should link to the release page.

**Comment by fmatthew5876** [comment]
> 
> 
> Just saying: Changing the startup logo currently counts as source code modification, also the GPL says they need to mark modified versions as such and ship the license… → We could sue them.

Since when did rpg maker game devs care about copyright? Look at the assets in all these games! 🤣

**Comment by Ghabry** [comment]
Considering all the SNES Rips and commercial music I'm still impressed that there was by now not a single case of C&D against a RPG Maker game I'm aware of.
Not even in the German community where the copyright law is much more strict (no "fair use").

**Comment by Tondorian** [comment]
maybe #Neuland is the answer? i remember the time the downloads get deleted from most pages as they were forced to avoid problems. https://www.rpg-atelier.net/ for example.
