### ISSUE TITLE
VD2 crash while battleing the first boss on switch

### ISSUE THREAD

**Issue by Tondorian** [EasyRPG/Player#1747]
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
Vampires dawn 2 german (https://www.vampiresdawn.org/vd-2-ancient-blood/)
#### Player platform:
Switch
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
[easyrpg_log.zip](https://github.com/EasyRPG/Player/files/3084756/easyrpg_log.zip)

#### Describe the issue in detail and how to reproduce it:
On switch the battle on the bridge causes the game to crash after a some turns. In worst case the console also crashes.

**Comment by Ghabry** [comment]
the logfile indicates that this is a out of memory issue but some tracing (e.g. MSVC has a memory profiler) should happen to test if this isn't some kind of memory leak

**Comment by carstene1ns** [comment]
Hmm, I never played more than a few minutes, so might really be a bad memory leak in the GL additions.

**Comment by Tondorian** [comment]
sorry was not able to add more details on this. I played the game most of the time on switch and all the other battles works fine so far. 
The PC build uses ~42mb of ram in this battle,

**Comment by fmatthew5876** [comment]
This is strange, there doesn't appear anything special about this battle.

It has 1 battle event on Turn 0
```
If SW46:
  Change Enemy HP - 500
```

There is one enemy that uses the Bite skill # 280, and 2 normal attacks.

**Comment by Tondorian** [comment]
maybe it is how the battle animation in this game works.
This battle does not crash on android.

**Comment by Ghabry** [comment]
@Tondorian is this still an issue?

A reason could be that the filename contains umlauts.

The VFS branch with ZIP loading will likely solve this in that case. :/

**Comment by Tondorian** [comment]
Most likely yes, I wanted to try the new pull request but sadly there is no switch build available and I was too lazy to build the switch toolchain, yet. If I remember correctly there was an error message on a later build. Most likely it is an issue by Nintendos exFAT/FAT filesystem

**Comment by Ghabry** [comment]
there is a switch build. https://ci.easyrpg.org/job/player-switch/

I suggest you retry this once ZIP support is added because this works around any filesystem bugs

**Comment by Tondorian** [comment]
yes for the master tree there is a switch build but your zip-file support/filesystem rework PR comes without homebrew binary. And you asked for testers. I wanted to test it on a switch. I will try to build it for the switch later.

**Comment by Ghabry** [comment]
I requested a build here: https://ci.easyrpg.org/view/Pull%20Requests/job/player-switch-pr/
Will take a while... Also not sure if this will still work, not used since half a year xD

**Comment by Ghabry** [comment]
@Tondorian  this is now implemented in master.

Closing this as this is unfortunately not fixable by us.

A workaround is to put the game inside a ZIP archive and launch this one as a game. This works as of today #2455
