### ISSUE TITLE
VD2 reviving items in battle does not work

### ISSUE THREAD

**Issue by Tondorian** [EasyRPG/Player#1748]
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
VD2 

#### Player platform:
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
[easyrpg_log.zip](https://github.com/EasyRPG/Player/files/3087273/easyrpg_log.zip)
Ignore the logfile.

#### Describe the issue in detail and how to reproduce it:
Reviving items in battle heals 0 hp and the actor is still dead.
i am not sure if it is vd2 that is that much special but reviving items did not heal the dead actor.
Maybe vd2 is a very special case because vampires are not dead and only in "starre" while humans get a dead status.  
The item is called "Trank der Ewigkeit"

**Comment by Tondorian** [comment]
#1726 will fix this but the healed hp is shown as 0. rpg_rt for some reason shows -1.

**Comment by fmatthew5876** [comment]
Retested with latest version of #1726
