### ISSUE TITLE
Yume2kki: 3 GB memory usage in the Depths

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1755]
Start from map 559 and move through the door.

The problem is the Screen tone blit affecting 1000 events.

I already work on a patch for this, found multiple memory wastes in the Sprite class (not leaks, they are all deleted when the map changes).

**Comment by fmatthew5876** [comment]
I tried this map and it's unusably slow on my beefy desktop on linux. I've got an Intel Xeon and an Nvidia GTX 1080 and I get 0 fps!

I haven't looked carefully at your PR yet, but it seems to be the most obvious thing would be to not apply screen effects to sprites that aren't visible.

**Comment by Ghabry** [comment]
> I haven't looked carefully at your PR yet, but it seems to me the most obvious thing would be to not apply screen effects to sprites that aren't visible.

Yes this is one of the optimizations in my PR.
The 2nd is that equal effects are shared now across the same charsets. This way the effect is only calculated once.
