### ISSUE TITLE
Equipment inflict states test cases

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1770]
Test Cases 1 - Equip and remove + status counter
=============

1. Have an event inflict poison on an actor
2. Save your game - status value is 1
3. Finish a battle
4. Save your game - status value is >= 2
5. Equip an armor which inflicts point
6. Save your game - status value is 1
7. Finish a battle
8. Save your game - status value is >= 2
9. Unequip the armor
10. Poison is removed
11. Save your game - status value is 0

Conclusions
===========

* Equipping armor always resets status counter to 1
* Unequipping always removes the state, giving free infinite healing of states!
* State counter still grows during battle turns

**Comment by fmatthew5876** [comment]
Test Cases 2
==========

Create poison with priority 50, stun with priority 30, both persisting after battle

1. Armor removes states

* Have an event inflict stun
* Save your game -> stun status is 1
* Equip an armor which inflicts poison
* Save game -> Poison status is 1, stun is 0
* Remove poison armor
* Save game -> all states gone

2. Armor has low state, event / armor tries to remove

* Equip armor inflict stun
* Save game -> stun status is 1
* Have an event inflict poison
* Save game -> stun and poison status is 1
* Equip poison armor
* Save game -> stun and poison status is 1

**Comment by fmatthew5876** [comment]
Test Cases 3
=============
Setup confuse as battle only state

1. Battle States by equip

* Equip armor that inflicts confuse
* Save game -> No states
* Start a battle - actor is confused
* Actor attacks self -> stays confused
* Finish the battle
* Save game -> no states

2. Battle states by event

* Have event add confuse
* Save game -> actor is confused
* Start battle - actor is confused
* Finish Battle
* Save game -> no states

Conclusion
==========

* Equipment that inflicts states will not inflict battle states on the map
* Equipment battle states cleared after battle end
* Events can inflict battle states - they cleared after battle ends

**Comment by fmatthew5876** [comment]
Test Cases 4 - Healing Items and Skills
=================

1. Items

* Equip poison armor
* Try to use an antidote
* Menu doesn't allow usage

2. Skills

* Equip poison armor
* Try to use a skill which does not except cure poison 
* Skill is used, sound effect, mp consumed, but poison not healed

**Comment by fmatthew5876** [comment]
Test Cases 5 - events healing states
=============================

1. Events heal states

* Equip poison armor
* Have event heal poison
* Poison still inflicted

2. Events heal battle states

* Have event inflict confuse
* Actor is confused
* Equip confuse armor
* Actor is still confused
* Have event heal confuse
* Confuse is removed, despite having the armor equipped

3. HealAll

* Have event inflict confuse
* Equip confuse and poison armor
* Have event do RecoverAll: EntireParty
* Confuse and poison still inflicted!

4. Rest at inn


* Have event inflict confuse
* Equip confuse and poison armor
* Have event rest at inn
* Confuse and poison still inflicted!

Conclusions:
==========

* HealAll and Inn never remove equip states
* RemoveState command will remove battle equip states on the map!

**Comment by fmatthew5876** [comment]
Test Cases 6 - Death
===============

1. Death Armor

* Equip death armor
* Actor is dead
* Unequip death armor
* Actor is revived

2. Multiple states

* Equip death armor
* Equip poison armor
* Save game -> Both death and poison states are 1
* Walk around the map
* Screen flashes red from poison effect on dead actor :exclamation:
* Remove death armor
* Actor is poisoned

3. Multiple states again

* Equip poison armor
* Equip death armor
* Save game -> Both death and poison states are 1
* Walk around the map
* Screen flashes red from poison effect on dead actor :exclamation:
* Remove death armor
* Actor is poisoned

**Comment by fmatthew5876** [comment]
Test Cases 7 - Equip menu
==============

1. Poison

* Have an event add poison
* Equip poison armor
* remove poison armor without leaving equip menu
* Poison is healed

2. Death

* Equip death armor
* Remove death armor without leaving equip menu
* Actors hp is now 1, showing that they died and then revivied

**Comment by fmatthew5876** [comment]
Test Cases 8 - States that halve/ double stats

1. Half

* Go to to equipment
* Select an armor that inflicts state which halves stats
* Equip arrows reflect nothing
* Equip the armor
* Stats on the left immediately go to half

2. Double

* Same as half case

**Comment by fmatthew5876** [comment]
Test Cases 9 - Curse state
======================

1. Curse

* Equip an armor which inflicts a state with "fixed equipment"
* Right after equipped, unable to change equipment.

**Comment by Ghabry** [comment]
Test case 8 is fixed in my PR btw

**Comment by fmatthew5876** [comment]
Test Cases 10 - Full Recovery
=======================

1. Full Recover

* Equip an armor which inflicts a battle state such as confuse.
* Player is not confused
* Have an event do full recover
* Player is confused :exclamation: 

2. Inn

* Equip an armor which inflicts a battle state such as confuse.
* Player is not confused
* Rest at the Inn
* Player is confused :exclamation: 

Conclusions
==========

Full Recover and resting at the inn resets all equipment states, even battle ones!
