### ISSUE TITLE
Yume2kki: Music room broken, reports "Unknown Event 10005"

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1778]
Name of the game: Yume2kki

Download 108c JP from here: https://rmarchiv.tk/games/1905

#### Describe the issue in detail and how to reproduce it:

Fast forward through the intro, go to your PC, select Music.
Try to play anything, the console is spammed with 10005 (This Event) warnings.

This is not game breaking because the Music room is an optional bonus.

I think this happens because the event ID is lost (ID=0) upon map transition and the ThisEvent resolving breaks.

Setting this to 0.6.2 as I expect this to be fixed by #1742, just not verified yet because this PR breaks before even reaching the room :).

**Comment by fmatthew5876** [comment]
This doesn't happen in version 106, only 108

What looks like is happening here:

EV01 Page 4 in Map 620 calls it's own Page 1 multiple times.

Page1 does a `SetVehicleLocation(Party)` to hack teleport the party to Map 2, and the again back to Map620 (why???) :question: 

In Player, when this happens we do a full teleport, instead of the half broken one RPG_RT does.

This causes event_id chunk to be wiped out the first time `CallEvent(ThisEvent[1])` happens. The next time it gets called, player thinks its a common event and craps out.

I've confirmed that `CallEvent(ThisEvent)` is not supported by any version of RPG_RT after you teleport (the event id goes to 0)

**Comment by Ghabry** [comment]
We concluded that this is too much bug abuse and deleting the 2 lines seems to fix the code, so they are useless.

Keeping this open, while I try to report a bug to the game devs.

**Comment by Ghabry** [comment]
Maybe it's hacky enough to set the map_id of the current event to the target map at https://github.com/EasyRPG/Player/blob/master/src/game_interpreter.cpp#L1729 but I close this bug now as the discord chat decided: They don't care and will not escalate it to the Japanese devs.

**Comment by fmatthew5876** [comment]
Test Cases 1 - Invalid Events
==============

1. Setup Map1 EV01 action=trigger `SetVehicleLocation: 0, -1, -1`

Setup Map2 with no events

Result: Crash with invalid event id

2. Create EV02 on Map2

Result: Warps to other map.

**Comment by fmatthew5876** [comment]
Test Cases 2 - Pictures
==============

1. Setup Map1 EV01 action=trigger
```
Show Picture: Some pic
SetVehicleLocation: 0, -1, -1
```

Setup Map2 with EV01

Result: Warps to other map, picture is not cleared.

**Comment by fmatthew5876** [comment]
Test Cases 3 - Call events

1. Map1

EV01 `CallEvent 2, 1`
EV02 `VehicleTeleport Map2; Msg: A`

Map2

No Events

Result:

Teleports, "A", Crash with invalid event id

2. Map2 Create EV01

Teleports, "A"

3. Map1

EV02 `CallEvent 2, 1`
EV01 `VehicleTeleport Map2; Msg: A`

Map2

No Events

Result:

Teleports, "A", Crash with invalid event id

4. Map2 create EV01

Teleports, "A", Crash with invalid event id

5. Map2 delete EV01, create EV02


Teleports, "A"

Conclusion
=========

The event id at the base of the call stack must exist

**Comment by fmatthew5876** [comment]
Test Cases 4 - Common events
=======================

1. Map1
CE01 `msg: A`
EV01 `VehicleTeleport to Map2`

Map2 - no events

Result:
"A", Teleport works

Conclusion
=========

Common event goes at the base of the call stack, so base event_id check is ignored.

**Comment by Ghabry** [comment]
Not bisected yet but the 10005 warning is back -> Reopening

**Comment by Ghabry** [comment]
```
6f7fa28131e3e117d25b3eb34d4c8adc88e88bcb is the first bad commit
commit 6f7fa28131e3e117d25b3eb34d4c8adc88e88bcb
Author: Matthew **** <****>
Date:   Wed May 29 21:28:38 2019 -0400

    Fully support Asynchronous transitions
```
