### ISSUE TITLE
Text overlaps with face on teleport

### ISSUE THREAD

**Issue by pulsejet** [EasyRPG/Player#1781]
Please fill in the following fields before submitting an issue:
#### Name of the game:
Ahriman's Prophecy

#### Player platform:
Windows, Android (probably all)

#### Describe the issue in detail and how to reproduce it:
On displaying a message with a face to the left after teleporting from inside a common event, the face is displayed but the offset for the text gets unset for all except the first line. So the first line shows up with the proper offset but the rest of the text overlaps with the face.

**Comment by pulsejet** [comment]
Ugh, for some reason the game defines a bunch of parallel process common events the first statement for all of which is to reset the face graphic to nothing (along with other things below in a conditional). The fact that this does work with RPG_RT does indicate some deviation of behavior from the original implementation though.

**Comment by Ghabry** [comment]
No need to close this yet, as we behave different to RPG_RT we consider this a bug in our implementation, even if RPG_RTs behaviour is strange.

**Comment by fmatthew5876** [comment]
This appears more complicated to reproduce

@pulsejet Do you have a save game near where it happens in the example game?

**Comment by pulsejet** [comment]
I've isolated a minimal test case [here](https://drive.google.com/open?id=12EqMjC9BzjQrBkeVzmUMCnez-w6my_pb)  (RTP dependent, let me know if this is not okay)

Basically, all you need is is one event that the player can interact which has
```
SetFace (1)
ShowMessage (1)
Teleport (to another map)
SetFace (2)
ShowMessage (2)
```
and one parallel process common event with just 
```
SetFace (Erase)
```
The second line of message 2 should overlap with the face. Note that it's necessary to telepoprt to a _different_ map, not the one you're on right now.
