### ISSUE TITLE
Debug Saves and Erase Screen Issue

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1786]
In RPG_RT, you can only save from the main menu or the save menu. If you do an erase screen and then summon either of these, the erase screen is cancelled.

The result is that no "Screen Erased" chunk is ever written to LSD and probably doesn't exist.

Therefore, if you use the Player debug menu to save while the screen is erased, and then load your save, the screen will be shown.

To fix this, we could do any of the following:

1. There is a remote possibility such a chunk maybe exists and is supported in RPG_RT? Use the BingShan patch and do `Erase Screen; Save` and check if any new chunks are written to LSD. Verify the chunk is supported without the patch. If so we can add this chunk.

2. Add a custom screen erased chunk to LSD

3. Disable the debug menu when screen erased. This is similar to RPG_RT. RPG_RT doesn't block the debug menu, it allows use but the screen is still black effectively making it unusable.

4. Allow debug menu during screen erase, but disable saving.

**Comment by Ghabry** [comment]
Well you can also debug save during a battle.
It's called debug save for a reason.

Though if we ever add save anywhere via BingShan save (but properly, not this non-yielding save with temporaries destroyed) this chunk is useful.

**Comment by fmatthew5876** [comment]
We decided to allow debug save even in this case

**Comment by fmatthew5876** [comment]
Confirmed there is no screen erased LSD chunks in RPG_RT.
