### ISSUE TITLE
2k - Phantasia Gaiden issues with dual-wielding

### ISSUE THREAD

**Issue by NovemberJoy** [EasyRPG/Player#1789]
Name of the game: Phantasia Gaiden

Download: [Download from rpgmaker.net](https://rpgmaker.net/games/10890/downloads/10367/)

Player platform: Windows 10 Home 1713

 - [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/3242564/easyrpg_log.txt) The log of the player
- [Save file](https://drive.google.com/open?id=1LQazVXaqg8H7Yx5wwOKSMug7hez5TVy1)

Describe the issue in detail and how to reproduce it:
Load the provided savefile and check equipment of Wataru. He's supposed to be able to equip two weapons, but something stops him from being able to do so. Loading the game in RPG_RT causes his dual wielding to function perfectly again even after saving in EasyRPG.

**Comment by fmatthew5876** [comment]
I've uploaded the savegame directly to github for posterity. In the future, please upload a zip here as external hosting can disapear in the future.

[Save02.zip](https://github.com/EasyRPG/Player/files/3243798/Save02.zip)

@NovemberJoy 
Did you create this savegame from RPG_RT or Player?

The `SaveActor::two_weapon` chunk is missing from this save game. It looks like Player is reacting to its default value of 0, while RPG_RT is ignoring it entirely.

In rm2k, `two_weapon`, `lock_equipment`, `auto_battle`, and `super_guard` can never be changed. In rm2k3 they can only be changed when you change class.

So maybe these are all 2k3 specific `SaveActor` chunks which are never written or read by rm2k?

**Comment by fmatthew5876** [comment]
Test Cases 1 - Create actors
==========

Create an actor with 2 weapons, lock equipment, auto battle, and super guard

1. Create this actor in rm2k and save your game.

All LSD chunks missing

2. Create this actor in rm2k3 and save your game

All LSD chunks set to 1

**Comment by NovemberJoy** [comment]
[Save03.zip](https://github.com/EasyRPG/Player/files/3244130/Save03.zip)
Here's a save file made from a fresh start in EasyRPG. Dual-wielding functions.
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/3244133/easyrpg_log.txt)
Log file after a fresh start, loading and saving in RPG_RT, and loading in EasyRPG. Ability to wield two weapons was lost in EasyRPG after saving in RPG_RT.
