### ISSUE TITLE
RPG2k: Rendering order of enemies is wrong

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1791]
Wadanohara http://vgperson.com/games/wadanohara.htm

Go through the dialog and start the battle (should be ID 13). THe Z order of the enemies is wrong:

![Screenshot_20190602_135110-fs8](https://user-images.githubusercontent.com/1331889/58760838-9624bc80-853d-11e9-988c-12db9c34cd72.png)
![Screenshot_20190602_135120-fs8](https://user-images.githubusercontent.com/1331889/58760839-9624bc80-853d-11e9-9cf9-ea13cf9c3ca4.png)

[Save04.zip](https://github.com/EasyRPG/Player/files/3244754/Save04.zip)

Here is a save earlier in the dialog which works in RPG_RT:

[Save02.zip](https://github.com/EasyRPG/Player/files/3244758/Save02.zip)

**Save02 doesn't load in RPG\_RT**

**Comment by fmatthew5876** [comment]
So the Z order priority (front to back) is this:

1. Enemy Y coordinate - lower is in front
2. Enemy ID - lower id is in front
3. Actor Y coordinate - lower is in front (2k3)
4. Actor ID - lower id is in front (2k3)
