### ISSUE TITLE
COLORS: Lost Memories. Shows transitions while RPG_RT shows none

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1801]
#### Name of the game:
COLORS: Lost Memories ([download](https://rpgmaker.net/games/9973/))

#### Attach files (as a .zip archive or link them)
Savegame: [Save02.lsd.zip](https://github.com/EasyRPG/Player/files/3267486/Save02.lsd.zip)

#### Describe the issue in detail and how to reproduce it:
 - Interact with the mailbox or with the sign on the next map, a transition is shown which is not visible in RPG\_RT.
 - Between maps is a short black flicker which isn't in RPG\_RT

**Comment by fmatthew5876** [comment]
This is probably the same general issue as #1600 and #1445

**Comment by fmatthew5876** [comment]
Here are some transition visual glitches in hh3 after a battle:

![hh3](https://user-images.githubusercontent.com/1198466/59159926-624a1980-8a9e-11e9-9e55-abbbe7e04324.gif)

**Comment by fmatthew5876** [comment]
After fixing #1840 the lufia game also exhibits some of these flickering transition in during the first scene in the house.
