### ISSUE TITLE
HTML5: No Audio

### ISSUE THREAD

**Issue by Kikasuru** [EasyRPG/Player#1812]
#### Name of the game:
Universal (Tested with Test Game, Ib, Wadanohara, and Yume Nikki.)

#### Player platform:
HTML5 (Google Chrome & Opera)

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
Beginning of the game.
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
(Log shown is Yume Nikki's)
![image](https://user-images.githubusercontent.com/45546181/59296236-138db280-8c4b-11e9-840b-1474edfc2775.png)

#### Describe the issue in detail and how to reproduce it:
If the error does not arise, reload the page.
Error goes to [this page](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio)

**Comment by carstene1ns** [comment]
Works in Firefox, but not in Chrome it seems: https://easyrpg.org/play/master/?game=yume_nikki

**Comment by fdelapena** [comment]
As the page linked says, it's a recent policy change in Chrome.
Emscripten tracking bug: https://github.com/emscripten-core/emscripten/issues/6511

**Comment by Ghabry** [comment]
Calling ``Module.SDL2.audioContext.resume()`` after a while fixed it.
Maybe can be combined with a setTimeout: Try every second to enable audio playback until it succeeds.

**Comment by Ghabry** [comment]
patch:

``js
function enableAudio() {
  var audioTimeout = setTimeout(function() {
    Module.SDL2.audioContext.resume().then(function() {
      clearTimeout(audioTimeout);
    });
  }, 500);
}
enableAudio();
``
