### ISSUE TITLE
FF Endless Nova: Intro text dissapears too soon (post-0.6 Regression)

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1814]
#### Name of the game:
FF Endless Nova
https://rpgmaker.net/games/6256/downloads/5676/

#### Player platform:
Post 0.6 regression

#### Describe the issue in detail and how to reproduce it:

Start the game, there is a dialog in the intro, in master the text disappears too quickly, impossible to read it. In 0.6 it is fine.

**Comment by Ghabry** [comment]
Bisect says the offending commit is: a1030cf6b92d6becf5dd5497e1d51e40c618da98    wtf?! No idea how this commit can cause this.

This issue is not about 1 frame difference but ca. half a second difference in the text display time.

**Comment by Ghabry** [comment]
Well that one is interesting. The game uses \| & co. for text delaying and this code uses ``Player::GetFrames()`` to get the current delay.
Because I moved the Update call around this seems to cause a slightly change in numbers and breaks the code. (there is also no reason to use GetFrames here, a number that just counts down is good enough, will submit a patch)

**Comment by fmatthew5876** [comment]
There is also the RPG_RT frames chunk. Not sure if that would be better for game logic based timing stuff like this.

**Comment by Ghabry** [comment]
there is unfortunately no chunk which saves the messagebox wait time (you can't even save while a message box is visible), so it makes no difference here what you use for reference, you will still need an extra variable for counting.
