### ISSUE TITLE
King of Grayscale - 2k3 battles don't handle Agility accurately

### ISSUE THREAD

**Issue by NovemberJoy** [EasyRPG/Player#1820]
Name of the game: King of Grayscale

Download link: [https://rpgmaker.net/games/9835/downloads/9767/](Here)

Player platform:
Windows 10 Home 1709 64-bit

Attach files (as a .zip archive or link them)
 - [Save02.zip](https://github.com/EasyRPG/Player/files/3312846/Save02.zip)
 - [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/3312848/easyrpg_log.txt)

Describe the issue in detail and how to reproduce it:
Load the provided save and enter the battleground to the left. Attack the enemies provided with the standard Attack command. In EasyRPG, they're guaranteed to be defeated before they get a single turn unless you miss, while in RPG_RT they'll get at least one turn before dying.

**Comment by fmatthew5876** [comment]
I confirmed this is still broken in master and fixed by #2133 

However there is another unrelated issue where the actors sprites are not visible in the battle.
