### ISSUE TITLE
Captain Novolin RPG (2k3) - Crashes while trying to load panorama during intro

### ISSUE THREAD

**Issue by NovemberJoy** [EasyRPG/Player#1821]
Name of the game: Captain Novolin RPG

Download link: [Here](https://drive.google.com/open?id=1_0hS0zeV9QoAbik5LgERwGsPnFIAXB2N)

Player platform:
Windows 10 Home 1709 64-bit

Attach files (as a .zip archive or link them)
 - [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/3315647/easyrpg_log.txt)
- [Crash dump](https://github.com/EasyRPG/Player/files/3315648/Player_2019-06-21-12-57-05.zip)

Describe the issue in detail and how to reproduce it:
Start a new game and select either difficulty setting. During the intro, after the first couple of lines past the difficulty selection, it will crash before displaying a panorama every time.

**Comment by fmatthew5876** [comment]
This is caused by `Change Parallax Back` commands which set auto scrolling. Processing one of these causes a divide by 0 exception when updating the parallax BG.

Likely a 6.0 regression caused by moving Parallax update after the foreground interpreter but haven't verified.

Will fix.

**Comment by fmatthew5876** [comment]
Test Cases 1 - Panorama commands
=============================

Setup this event
```
Change Panorama: Horiz Loop (+1) Vert Loop (+1)
Loop:
  OpenSaveMenu
```

| Save | pan_x | pan_ y |
| -- | -- | -- |
| 1 | 20478 | 15358 |
| 2 | 20476 | 15356 |

**Comment by fmatthew5876** [comment]
Test Cases 2 - Preset panoramas
==========================

Setup the Map with cosmos panorama. Horiz scroll, auto, +1, vert scroll, auto, +1

1.    EV01 parallel

```
Loop:
  OpenSaveMenu
```

| Save | pan_x | pan_y |
| -- | -- | -- |
| 1 | 512 | 512 |
| 2 | 510 | 510 |

**Comment by Ghabry** [comment]
This crash affected 8 users on Android btw. :+1:
