### ISSUE TITLE
Ib: Interpreter hangs after picking the key from the red-eyed rabbit room

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1827]
#### Player platform:
Any

#### Attachment:
 - [savegame_and_log.zip](https://github.com/EasyRPG/Player/files/3365124/savegame_and_log.zip)

#### Describe the issue in detail and how to reproduce it:
 - Go to the left door to enter the red eyes room and trigger the event from the library placed on the left, Pick the key from the crashed rabbit, return to the previous room and try to cross the puppet to the other side. The interpreter will hang.

It seems the puppet event is not working properly. The animation is suspicious and you can impersonate it like a vehicle. I didn't check this with the RPG Maker editor or from RPG_RT to compare with, but it looks it's misbehaving and a possible regression. Note the most recent Ib version is 1.07, this one is based on the 1.05.

**Comment by fmatthew5876** [comment]
One bug I see is that you can't exit the red manikin in the down direction. This happens because there is an event there and somehow LSD chunk `layer == same` and so a collision check fails when trying to dismount. This happens even though the event has no active page.

**Comment by fmatthew5876** [comment]
I fixed the afore mentioned issue with #1828  but I'm still confused.

I do the following:

1. Enter the left room
2. Talk to the big rabbit picture and choose the first option
3. Talk to the left bookcase
4. Talk to the 2nd from below rabbit on the left
5. Key appears
6. Take the key
7. Exit the room

Now I can do one of the following:

1. Enter the puppet from the left. a cutscene starts, green vines cover the player, and the game hangs.
2. Try to step below the puppet. The player faces up, a cutscene appears to start, and the game hangs.

This occurs with both Player and RPG_RT. I had to copy in an english RPG_RT to get RPG Maker Editor to load the game. I couldn't get the original one to work in window mode which broke my linux setup and hung when I try to run it full screen.

**Comment by fdelapena** [comment]
According to some gameplays, no puppet appears there at all, so what it seems to be supposed to happen is between the blocked painting by the puppet and the player character, then it never happens because it blocks the route and the action never completes:

https://www.youtube.com/watch?v=dY5twkXQokw&t=18m50s

If RPG_RT shows the puppet, I suspect something is broken in the savegame. I'll ask for more info to the reporter if needed.

**Comment by Ghabry** [comment]
Just played until this place in the English translation: No Vehicle there, works for me.

**Comment by Ghabry** [comment]
also not happening in the brazilian version. Must be a corrupted savegame. Closing.
