### ISSUE TITLE
Witch's Heart: Bad performance in Lime's minigame

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1833]
#### Name of the game:
Witch's Heart (http://vgperson.com/games/witchheart.htm)

#### Attach files (as a .zip archive or link them)
[Save01.zip](https://github.com/EasyRPG/Player/files/3389663/Save01.zip)

#### Describe the issue in detail and how to reproduce it:
Enable the FPS counter.

Talk to Lime, and pay the 100 coins. Walk on one of the directional buttons, you will see a short hang and FPS drop. (best seen in debug build, goes down to 30 FPS here)

Thats a bug with the audio system, when using "--disable-audio" the lag is gone. Oh this maybe helps fixing the lag spikes in other games we never observed on PC, awesome.

**Comment by Ghabry** [comment]
SE files are completely decoded when being played and cached (the reason for this is to reduce CPU stress on slow systems, it e.g. solved stuttering when a game uses footstep sounds).
The problem here is basicly that the SE file played is very long, in that case we should fallback to streaming instead of caching I guess.
Determining when to stream instead of caching involved checking the length of the track which involves parsing the header as checking the filesize is misleading depending on the type of compression.

**Comment by Ghabry** [comment]
Was just told this also happens in "charlotte first chase". I think I know where this is, pretty early in the game, but can't provide a savegame right now.

**Comment by fdelapena** [comment]
Same problem reported at https://community.easyrpg.org/t/733
Also Pizus reported performance issues in his game (unreleased test case, available on demand).

**Comment by Ghabry** [comment]
I know where the problem is and at least for the audio systems that depend on GenericAudio I have a fix in the works.

Other performance observations:
- Using the lowest quality for speexdsp is twice as fast compared to normal quality. By now I didn't hear a difference (guess the audio samples are already bad enough xD)
- libsamplerate is much slower than speexdsp, should stick to speexdsp except when there is no other way (Aarch64).
