### ISSUE TITLE
Die Reise ins All: XO puzzle can't be solved (Tile substitution bug)

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1834]
Please fill in the following fields before submitting an issue:
#### Name of the game:
Die Reise ins All
https://rmarchiv.tk/games/50

#### Attach files (as a .zip archive or link them)
[Save01.zip](https://github.com/EasyRPG/Player/files/3390373/Save01.zip)

#### Describe the issue in detail and how to reproduce it:
Load the save, walk through the door (jump with enter) and walk on the XO-tiles, only the O are save.
When you walk the marked tile in the screenshot it will behave like a X and you fail.
Based on the events I think this is tile substitution related.

![screenshot_0-fs82-fs8](https://user-images.githubusercontent.com/1331889/61188538-e5075b00-a680-11e9-8f8d-feb04e724f19.png)

**Comment by Ghabry** [comment]
I marked it incorrectly, the problematic tile is the one below and when you open the editor this is the first one that is X by default when not substituted.

**Comment by Ghabry** [comment]
@fmatthew5876 
The solution seems to be changing

https://github.com/EasyRPG/Player/blob/caf789c74112f899099c0afaba92c59c00a21a8c/src/game_map.cpp#L720-L722

to
```cpp
if (chip_index >= 18 && chip_index <= 144 + 18)
```

But I let you handle this as I'm not sure if this is correct and I also have no idea why there is even the "18". I didn't write the tilemap code :/

**Comment by fmatthew5876** [comment]
The way we name our tile blocks looks all wrong:

![tiles](https://user-images.githubusercontent.com/1198466/61192395-074da880-a682-11e9-9103-252de53f148e.png)

There are 3 A tiles, 3 B tiles, and 12 C tiles. That's where this magic 18 offset comes from. There are `162 = 18 + 144` lower tiles in all.

Our constants are only `BLOCK_C`, `BLOCK_D`, `BLOCK_E`, and `BLOCK_F` which is doesn't match the help file. We invented "F" (which is fine), but what we call C, D, and E don't match the help file. We have no constants for A or B.
