### ISSUE TITLE
Lufia V: For the Savior softlock almost immediately after starting game

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [EasyRPG/Player#1840]
#### Name of the game:
Lufia V: For the Savior Part 1

#### Player platform:
PC & 3DS

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/3397906/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
After all of the intro videos, once you gain control of your character, going downstairs will cause the game to softlock with the music still playing. This issue does not happen when regularly launching the RPG_RT.exe, since I have completed the whole game this way already. I just wanted to replay this game on my 3DS, but this program isn't compatible with the game as it is now. The issue happens on both PC and my 3DS. I was told by the game developer that this game uses a few 'quick hacks' to run properly, so maybe tweaking this program a little can make it work properly. Hopefully this can be fixed soon.

**Comment by fmatthew5876** [comment]
Game Link: https://rpgmaker.net/games/4184/

Confirmed this is still broken in master.

When you walk down the stairs, the foreground interpreter gets stuck in a do nothing infinite loop on `Game_Message::message_waiting`.

Attached a save game created by debug menu.

[Save01.zip](https://github.com/EasyRPG/Player/files/3399214/Save01.zip)

**Comment by fmatthew5876** [comment]
Test Cases 1 - Message command delays
================================

EV01 parallel
```
ShowMessage: "\v[1] \v[2]"
```

EV02 parallel
```
Var[1] += 1
```

EV03 autostart
```
Var[2] += 1
```

Result:
"0 0"
"84 10"
"149 20"
"212 30"

**Comment by Ghabry** [comment]
There is only one plugin in the DynPlugins folder:
"Also if you see in the dynrpg folder you will see a strange plugin called NMBattlers.dll, it was a plugin made by my friend Dahrkael from spanish community, that disable the auto-reverse graphics when you start a battle using front side battle. " (Source: https://rpgmaker.net/forums/topics/12520/)

**Comment by gadesx** [comment]
NMBattlers.dll, of dynrpg disable the flip function on battle, because front battle view doesn't need the flip.
Delete the dll and try if work with player
