### ISSUE TITLE
Add release with asserts mode - Use for beta release.

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1841]
We should add a build mode which builds optimize release mode code but enables `assert()` and includes debug symbols. Use this for beta apk's. 

This should not slow down our code too much but will seriously help us find bugs, especially sources of crashes.

**Comment by Ghabry** [comment]
asserts should be already enabled on Android.
At least we don't define "-DNDEBUG" which is responsible for removing asserts.

**Comment by Ghabry** [comment]
and we collect debug symbols, they are available von Jenkins.

**Comment by fmatthew5876** [comment]
Well sounds like we already have asserts turned on for betas!
