### ISSUE TITLE
Vehicle Jump Glitch not supported

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1852]
Setup these horizontal tiles:

Tile | Event
-- | --
Water |  
Water | Ship
Grass |  
Grass | Touch Event
Grass | Player

Player Touch Event:
@> Set Move Route: Player, Freq8, Move Left
@> Wait: 0.0 seconds
@> Set Move Route: Ship, Freq8, Jump , Move Down, Land 
@> Get On/Off Vehicle

Move to the left and have some fun.
The glitch even continues when you leave and reenter the ship :)

Video:
[vehicle-jump.zip](https://github.com/EasyRPG/Player/files/3418760/vehicle-jump.zip)

**Comment by fmatthew5876** [comment]
I can't reproduce this in a test game. Is your code example correct?

Also the issue says vertical tiles, but these need to be setup horizontally left to right.

**Comment by Ghabry** [comment]
Attached a map, the place where you have to put the Ship has a visual indicator:
[Map0001.zip](https://github.com/EasyRPG/Player/files/4053112/Map0001.zip)

Yeah is is horizontal and the touch type is "Player touch". Sorry!

**Comment by CherryDT** [comment]
That glitch is hilarious. Learned something new again.

**Comment by fmatthew5876** [comment]
Ahh ok I didn't realize you had to walk around to reproduce it. Yeah I see it now. I don't have linux available this weekend so I can't easily check LSD chunks.

My suspicion is that somehow boarding the ship cancels it's move route but doesn't clear the jump flag. So the ship is permanently stuck as jumping and so all movement looks like that.

**Comment by fmatthew5876** [comment]
Here's another jump glitch

Make a trigger event with
```
SetMoveRoute: Jump, End Jump, Foward
```

Now trigger the event facing left, right, or up

Result:

The event will jump in place, the step down while facing the same direction.o

This happens because after a jump in place RPG_RT sets `direction` to down but does not change `sprite_direction`.

**Comment by fmatthew5876** [comment]
This is now implemented in #2208

**Comment by fmatthew5876** [comment]
Here is another glitchy but useful test case

| Tile | Event |
| -- | -- |
| Grass | Player |
| Grass | Ship |
| Water | Boat |

Ev01 Autostart
```
Set Airship location to ship location
Enter/Exit Vehicle
Enter/Exit Vehicle
```

Result: Hero boards the boat, on the same tile as the ship!

**Comment by fmatthew5876** [comment]
And another

| Tile | Event |
| -- | -- |
| 0 Grass | Player |
| 1 Grass | |
| 2 Grass | |
| 3 Grass | |

Ev01 parallel:
```
Wait 0.5s
Set Boat loation tile 1
Enter/Exit Vehicle
Set Boat loation tile 2
Enter/Exit Vehicle
Set Boat loation tile 3
Enter/Exit Vehicle
```

Result player warps to tile 3 and boards the boat there.
