### ISSUE TITLE
Multi-Game Save Importing

### ISSUE THREAD

**Issue by sorlok** [EasyRPG/Player#1854]
Hey all,

Some RPG Maker games allowed importing save files from previous versions (e.g., Legion Saga 1 -> Legion Saga 2) or were episodic (e.g., "The Way", Episodes 1->6). They accomplished this by asking players to copy save files from the old game's folder to the new game's folder, using a specific Map ID to synchronize the load.

I think it would be nice to have built-in support for this, since copying files around is not trivial on some platforms. I wrote some sample code to accomplish this:
https://github.com/sorlok/Player/commit/be26cd56b21d15ccd073bdc00a2a305937b6fbdf

This requires that a metadata file be added to the game folder with (a) the name of the folder containing the game to import from and (b) the ID of the map to use as a pivot point. If that file exists, it adds an "Import Save" option to the title screen:
https://i.postimg.cc/rpZ4fykx/easy-rpg-import-1.png

This menu option opens the regular "Continue Game" window on the import folder, and filters save files based on the map ID:
https://i.postimg.cc/HxJyRGYK/easy-rpg-import-2.png

The code functions, but is not release-quality; it's meant more as a discussion point on Importing. I was wondering if the Player developers were interested in supporting multi-game save importing (or were even aware that games did this), and if this approach seems like the right way or not.

**Comment by Ghabry** [comment]
Hello, currently is summer vacation time so don't expect too much feedback during the next weeks. :)

I only scrolled quickly through your code yet without giving any feedback on it but in general we accept enhancements when they can't break existing games.
At least the "Import Savegame" function is not visible in games that lack the special file, so it won't annoy in any other games.

I also wonder if instead of the Title scene maybe it fits better in the game browser (but extra work for platforms which have a custom game browser like Android e.g.)

**Comment by sorlok** [comment]
Thanks for the feedback! I'm thinking about your question regarding who provides the file; will get back to you on this.

What's the "Game Browser" you mentioned? I've only used the EasyRPG Player from the game folder directly...

Finally, two more questions: 
1) Is there a preferred data format for config files? I.e., XML or JSON or CSV, etc.
2) Is there any other per-game metadata that already exists in EasyRPG-land? (In other words, do I really need a dedicated file for this, or is there some other file I can add this to?)

Thanks!

**Comment by Ghabry** [comment]
> What's the "Game Browser" you mentioned
When you put the Player one level above the game folder a game listing will appear.

> Is there any other per-game metadata that already exists in EasyRPG-land?

Right now there is no specific config file available. Our editor isn't very advanced yet, that's why there wasn't a need yet to specify any type of config file.

**Comment by sorlok** [comment]
Ok, thanks. I'll work on the code and get back to you.

**Comment by sorlok** [comment]
I've created Pull Request https://github.com/EasyRPG/Player/pull/1860 with my first draft of the feature. First, some pictures:

1) The actual Folder name and Save File ID is now shown correctly, and save files that don't match the filter are not shown:
https://i.postimg.cc/NMpzMC85/easy-rpg-import-3.png
2) Scanning for valid save files can take some time, so a progress bar is shown:
https://i.postimg.cc/tRvcGfCc/easy-rpg-import-5.png
3) There is a vocabulary override in the metadata if you want to change the "Import Save" text on a per-game basis:
https://i.postimg.cc/CLZQhNRx/easy-rpg-import-4.png

Now, to get back to earlier discussion points:
1) Using the folder name is fragile, as you pointed out, since people might rename their games. Thus, I added a game "fingerprint" that checks things like the Game Name and the Map Name for specific Map IDs. Unfortunately, this means that we need to scan all folders in "../" when looking for saves to import, but on the flip side it's *much* more reliable now.
2) I structured the metadata so that it can appear either (a) in the Game directory or (b) one directory above. The metadata file can also list multiple games, so I provided "resources/shared/meta.json" as a sample file that people can drop into their game folder to get started.
3) Since EasyRPG doesn't have global metadata yet, I tried to structure "meta.json" so that other developers could add things to it, if they wanted to. For example, the Vocabulary overrides. (Or, if no-one else uses it, that's also fine. :)
4) The file scanning only works when GameFolder == SaveFolder, so (I think) android can't use it as-is. This is due to how fingerprinting works. In the future, I think Android (and maybe other systems) could add Importing to the Game Browser (as suggested), which should be pretty easy to do given the way the metadata file is structured.
5) In terms of maintaining the metadata file, I'm happy to add games to it as I find them in the wild. Developers may also choose to maintain their own files, since meta.json in the Game directory overrides the global meta.json. If we get really confident in the global meta.json, we can bake it into the binary, but I don't think that's required yet.

No rush looking at the Pull Request ---I realize everyone's on summer vacation. When you get a chance though, please let me know if anything needs changing (or if you want a rebase, etc.). Thanks!

**Comment by sorlok** [comment]
Closed (fixed) as of PR #1860
