### ISSUE TITLE
Cumbound: Protagonist not displayed in intro

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1857]
#### Name of the game:
Cumbound - The War against Gayass

https://gamejolt.com/games/CumboundGame/368156

#### Describe the issue in detail and how to reproduce it:

Start the game, you are asked some stuff. Go through the questions, after a while it shows a msg "You are more likely this guy... [...] Than this guy...".

In RPG\_RT characters walk in while this is shown but not in Player.

**Comment by fmatthew5876** [comment]
The intro map uses a chipset with an empty string chipset graphic. The first tile is an upper star tile which is above the event.

For some reason player renders this as black above the event and covers it, which is why you don't see it.

**Comment by Ghabry** [comment]
Likely related to #1577 . I will try to fix them for 0.6.2.
This fastblit stuff is a speed hack which saves one screen clear if not needed. Gives 3 FPS on the old 3ds. But i forgot to handle some corner cases.

About 2k3 pictures: this should work, there is code which scans for such pictures :)
