### ISSUE TITLE
Yume2kki: More Vehicle Teleport issues

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1861]
#### Name of the game:
Yume2kki

[save-log.zip](https://github.com/EasyRPG/Player/files/3478782/save-log.zip)

#### Player platform:
Master branch with Vehicle Teleport patch merged

#### Describe the issue in detail and how to reproduce it:
See attached logfile and save.

via Mail (machine translation):

Once you enter the dream world and pinch your cheeks and try to save on the PC screen, the message “Sound Room update check ...” will appear, an error will appear, and the game will be forcibly terminated.

A screenshot is attached.

![Screenshot_20190807-182605](https://user-images.githubusercontent.com/1331889/62655424-38a85400-b962-11e9-8967-4146ce73c402.png)

**Comment by fmatthew5876** [comment]
Sorry, but can you provide more detail on how to reproduce the bug using the save game? I tried a few things loading this save and don't see it.

**Comment by fmatthew5876** [comment]
Test Cases 1 - Vehicle teleports to other map
===========

* CE1: `Vehicle Teleport Map2`
* CE2: `Vehicle Teleport Map2, Loop: Wait 0.0s`
* Map1
    * EV01: `Vehicle Teleport Map2`
    * EV02: `Call EV01`
    * EV03: `Call CE01`
    * EV04: `Vehicle Teleport Map2`
    * EV05: `Call EV01`
    * EV06: `Call CE01`
* Map2:
    * EV01
    * EV02 
    * EV03

| Action | Result |
| -- | -- |
| CE2 | Teleports |
| EV01 | Teleports |
| EV02 | Teleports |
| EV03 | Teleports |
| EV04 | Crash |
| EV05 | Crash |
| EV06 | Crash |

Conclusion
---------------

This might be exposing another issues related to call stack `event_id` I need to investigate more.

**Comment by fmatthew5876** [comment]
Test Cases 2 - Vehicle teleports to other map with other commands
===========

* CE1: `Vehicle Teleport Map2, Msg: X`
* Map1
    * EV01: `Vehicle Teleport Map2, Msg: X`
    * EV02: `Call EV01`
    * EV03: `Call CE01`
    * EV04: `Call EV05`
    * EV05: `Vehicle Teleport Map2, Msg: X`
    * EV06: `Call EV01`
    * EV07: `Call CE01`
    * EV08: `Call EV05`
* Map2:
    * EV01
    * EV02 
    * EV03
    * EV04

| Action | Result |
| -- | -- |
| EV01 | Teleports, X |
| EV02 | Teleports, X |
| EV03 | Teleports, X |
| EV04 | Teleports, X |
| EV05 | Teleports, X, Crash |
| EV06 | Teleports, X, Crash |
| EV07 | Teleports, X, Crash |
| EV08 | Teleports, X, Crash |

Conclusion
---------------

The crash seems to happen when the event finishes. So maybe doing a vehicle teleport to and from with invalid events is ok.

**Comment by Ghabry** [comment]
I can't reproduce this crash o.O
But my yume2kki version is outdated, updating...
