### ISSUE TITLE
Yume2kki: Saving Audio tracks as favorite not working

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1864]
Not setting this to 0.6.2 milestone directly as this is not game breaking -> Lower priority.

#### Name of the game:
Yume2kki ゆめ２っき 0.109f

0.109g was just (2019-08-11) released, likely exposes the same problem.
You can load older savegames in newer versions, the game detects this.

#### Attach files (as a .zip archive or link them)
[yume2kkiaudio.zip](https://github.com/EasyRPG/Player/files/3490326/yume2kkiaudio.zip)

The savegame is loadable in both RPG\_RT and Player.

#### Describe the issue in detail and how to reproduce it:

Likely more vehicle teleport chaos?

1. At the Computer select "Music"
2. Start playing any song with "ENTER".
3. Press Shift to open the "memory mode" option (メモリ一登録). Confirm with Enter (する = Z)
4. It says that it is saved in slot 1: No.1に登録しました
5. Switch to a different song: and repeat from step 2. It saves in Slot 1 again. In RPG\_RT it saves in No.2 etc.

How to access the audio favourites:
1. Press ESCAPE
2. Select 演奏モッド (3rd option)
3. In EasyRPG Player this list is empty, in RPG\_RT it shows the by now saved songs.

Note: When you press enter on an empty field you input a number for the track ID and the subtrack ID, e.g. 1 and 1. THen the track is shown in the favourite list in EasyRPG but forgotten when you leave the mode via 演奏モッド (3rd option) again.

When you load a savegame that contains favourites they are not show in Player.

#### How to leave the music room:

1. In the menu go to page two (4th option): [1/2] ２ページ目
2. select the 3rd option: サウンドルーム分室から
3. Select the 1st option that says PC

**Comment by fmatthew5876** [comment]
This doesn't appear to use memorized BGM commands. It can't anyway as it saves multiple bgms.

It appears though whenever you do try to memorize a bgm using this, it does a vehicle teleport. So there could be some funky vehicle teleport side effect making this fail.

Given all the japanese, could use your help @Ghabry if you can study the code a bit more to understand what it's doing.

**Comment by Ghabry** [comment]
This sounds like a usage for the event tracer and a longer weekend night. Will see what I can figure out.

**Comment by Ghabry** [comment]
uuuuuuuugh, this took now some time but I think I tracked this crap down.

Based on lots of printf-debugging and eventtrace usage the reason should be:
Map620, EV1, Page1, has the code:
```
@> Conditional Branch: [うろつき]'s name is '演出_初期化'
@> Set Vehicle Location: , [0002:MAP0002現実部屋] (-001,-001)
@> Set Vehicle Location: , [0620:MAP0620 310_SR分室] (-001,-001)
@> Erase Picture: 1
```

```
Event tracer shows: (ID, Page, Line, Cmd)
E	1	5	3	12010
E	1	5	4	10850
E	1	1	5	10850 <- corrupted page number??? (EV1 on Map2 has only 1 page btw, could a failsafe)
E	1	5	6	11130
```

Problem is now that on Map2 is an autorun event (Event 1) and after a while invokes CE3 which does the cleanup. Player invokes thie event before VehicleTeleporting back, RPG\_RT does not as shown in the trace.

**Comment by fmatthew5876** [comment]
Thanks for investigating the root cause. This is not at all surprising.

Our code treats vehicle teleport kind of like a normal teleport. What we really need to do is make it a kind of async event, or maybe just literally swap out the map instantaneously somehow.

**Comment by fmatthew5876** [comment]
Is it always teleport other map, followed immediately by teleport to this map?

It finally occurs to me that they abuse this to do an instant reset the map event interpreters. That's also why they couldn't remove it even if they wanted to.

Another possibility is that we could detect this pattern and instead of doing 2 async map loads, we just reset the events on the current map.

**Comment by Ghabry** [comment]
I did now a full analyze of the game. VehicleTeleport is used on these maps:
```
Database
They are at various places:
<parameters>-1 0 2 9 7</parameters>
<parameters>-1 0 3 9 12</parameters>
<parameters>-1 0 620 -1 -1</parameters>
<parameters>-1 0 2 12 5</parameters>

Map0001.emu
These are next to each other:
<parameters>-1 0 620 0 0</parameters>
<parameters>-1 1 1 2 3</parameters>

Map0150.emu
They are at various places:
<parameters>-1 0 2 0 0</parameters>
<parameters>-1 0 150 7 5</parameters>

Map0191.emu
This case should be checked:
<parameters>-1 0 2 9 7</parameters>
One message command in-between
<parameters>-1 0 191 27 38</parameters>

Map0453.emu
I guess this is the second media player room.
At least they are not next to each other ;)
<parameters>-1 0 2 0 0</parameters>
<parameters>-1 0 453 0 0</parameters>
<parameters>-1 0 2 0 0</parameters>
<parameters>-1 0 453 0 0</parameters>
<parameters>-1 0 2 0 0</parameters>
<parameters>-1 0 453 0 0</parameters>
<parameters>-1 0 620 0 0</parameters>
<parameters>-1 0 453 0 0</parameters>
<parameters>-1 0 620 0 0</parameters>
<parameters>-1 0 453 0 0</parameters>
<parameters>-1 0 620 0 0</parameters>
<parameters>-1 0 453 0 0</parameters>

Map0620.emu
This bug report: (next to each other)
<parameters>-1 0 2 -1 -1</parameters>
<parameters>-1 0 620 -1 -1</parameters>
