### ISSUE TITLE
TMG (Three Magic Girl) v1.2: Distributing EXP in the Inn fails with "Call Event: Can't call page 0 of event 2"

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1865]
#### Name of the game:
TMG (Three Magic Girl) v1.2 (Warning: Hentai game)

https://vipkohaku.x.fc2.com/2015/entry86.html

To get the game click [ダウンロード(83.3MB)], then on the yahoobox page ensure all scripts are enabled and at the top-left is another [ダウンロード] button.

Extract the game with unar or any other application that supports shift-jis encoded zip files.

#### Attach files (as a .zip archive or link them)
[Save03.zip](https://github.com/EasyRPG/Player/files/3498654/Save03.zip)

#### Describe the issue in detail and how to reproduce it:
Walk upwards and talk to the owner of the Inn.

Select:
やどやにとまる → けいけんちをわける → はい → わてり → [Input 1]

The game reports "CallEvent: Can't call non-existant page 0 of event 2".
In RPG_RT with the same savegame it shows a pornographic picture and continues.

**Comment by Ghabry** [comment]
Noticable is that the game has the switch and variable list truncated to 1 entry.

The problematic call is on map ``event -> 001`` event 1, page 3, ``@> Call Event: Variable [0016][0017]`` on line 234

**Comment by Ghabry** [comment]
Likely a clamping problem.

Earlier code does

```
@> Change Parameters: [], Max MP - 999
@> Change Parameters: [], Max MP - 999
@> Change Parameters: [], Max MP + 999
```

The purpose is obviously to reset the value to 0.
But this behaviour should be verified for other Makers and versions. (game uses 2000)

**Comment by fmatthew5876** [comment]
So it looks like we should be clamping the `stat_mod` chunks and we don't. Just testing rm2k3 now I see it should clamp at `[-9999,9999]`. In player it goes on forever.
