### ISSUE TITLE
Performance Regressions in script heavy games

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1883]
Something has caused a performance regression in script heavy games.

- [x] もしもスマブラだったら (Wannabe Smash Bros.) http://viprpgsum15.webcrow.jp/sakuhin.html?71

- [ ] Frozen Triggers http://viprpg17kh.php.xdomain.jp/main/04_game.php?id=48

These games are currently unplayable in master with debug builds.

Looking at the graphs, these are performance bottlenecks in Frozen Triggers.

- [x] https://github.com/EasyRPG/Player/blob/0e05729f1c170e65800bfee487800c4e12e29683/src/cache.cpp#L128
    * Suggestion: Call `GetTicks()` once each frame and cache the value. Replace calls to `DisplayUI::GetTicks()` to the cached one
- [ ] https://github.com/EasyRPG/Player/blob/0e05729f1c170e65800bfee487800c4e12e29683/src/game_picture.cpp#L256
    * Suggestion: Cache / Reuse Picture Sprites
- [x] https://github.com/EasyRPG/Player/blob/0e05729f1c170e65800bfee487800c4e12e29683/src/game_picture.cpp#L253
    * Suggestion: Cache / Reuse Picture Sprites
- [ ] https://github.com/EasyRPG/Player/blob/aca489b85761d64d9d111589fe1848b16a18bc74/src/game_picture.cpp#L244
    * Calling `Bind()` allocates a `shared_ptr<int>`. In the case where the asset is already in the cache this is wasted. Provide an optimized code path which avoids allocating and throwing away these objects when the asset is already loaded in cache.

**Comment by fmatthew5876** [comment]
I just tested this commit https://github.com/EasyRPG/Player/commit/00ad8ab137261fff23559365ad50397a2d98ffcc and still see the issue.

This must have made it into 0.6.1?

**Comment by carstene1ns** [comment]
I have not followed development for some time, but built from master today and do not observe this.

**Comment by fmatthew5876** [comment]
What platfrom?

I'm testing this on linux. Ghabry also observed this while testing #1740.

**Comment by carstene1ns** [comment]
Hmm, might be my setup then.

**Comment by Ghabry** [comment]
When I use the debug builds of our Linux releases (The ones published on our website) I get:

0.5.4: 18 FPS - 34 FPS (has random lags)
0.6.0: 12 FPS - 20 FPS
0.6.1: 21 FPS - 30 FPS
nightly: 0 FPS - 1 FPS

But makes no sense to profile this yet (in release mode) until all interpreter PRs are merged.

**Comment by fmatthew5876** [comment]
Here is a CPU flame graph of a few frames of debug build Frozen Triggers

![ft](https://user-images.githubusercontent.com/1198466/65083674-282ec480-d977-11e9-9e22-61aaf02000b2.png)

**Comment by fmatthew5876** [comment]
Here is a flame graph in release build on Ubuntu Linux. In release mode, the game runs at a smooth 60fps on my system

![ftp](https://user-images.githubusercontent.com/1198466/65084428-2d8d0e80-d979-11e9-9c3e-edeb866d4033.png)

Still way too much time in `CommandShowPicture`.

**Comment by fmatthew5876** [comment]
Looking at the graphs, these are performance bottlenecks:
- [ ] 	https://github.com/EasyRPG/Player/blob/0e05729f1c170e65800bfee487800c4e12e29683/src/cache.cpp#L104
- [ ] https://github.com/EasyRPG/Player/blob/0e05729f1c170e65800bfee487800c4e12e29683/src/game_picture.cpp#L256
- [ ] https://github.com/EasyRPG/Player/blob/master/src/game_picture.cpp#L253


The solution to this could be to cache and reuse the picture sprites. That would speed up any game that attempts to build particle effects using pictures.

**Comment by fmatthew5876** [comment]
To generate these samples, you can do the following:

1. Start the game and go to the place where the game is slow
2. Mouse out of the game to pause it
3. Get the pid of `easyrpg-player`
4. Use perf to record some stack traces `perf record --call-graph dwarf -p PID`
5. Create the framegraph `perf script | ./FlameGraph/stackcollapse-perf.pl | ./FlameGraph/flamegraph.pl > out.svg`

**Comment by fmatthew5876** [comment]
Here are flame graphs for Smash Bros. On Ubuntu Linux:

Release, `master`

![smash_rel](https://user-images.githubusercontent.com/1198466/65086640-8c09bb00-d980-11e9-84fb-55923d209c2b.png)

Debug, `master`

![smash_dbg](https://user-images.githubusercontent.com/1198466/65086651-91ff9c00-d980-11e9-97be-d9f1edf30a86.png)

Release, 88a09809e215359562fe94a8f9ed20125836a4af (before #1884)
![smash_old](https://user-images.githubusercontent.com/1198466/65086811-37b30b00-d981-11e9-9b22-1dc3a4edd788.png)

**Comment by fmatthew5876** [comment]
I get 0 FPS in Smash Bros Debug build with 88a0980 
I get 60 FPS in Smash Bros Debug build with `master`.

So for me, #1884 fixed unplayable smash bros issue. I only have problems with Frozen Triggers now.

**Comment by Ghabry** [comment]
I recompiled now latest master and on Linux I get 0 FPS but on Windows I get 60 FPS in a release build (!).
So this must be unrelated to the Player and some library/driver issue.

Between 0.5.4 and master I also see no noticable difference in the profiler output.
