### ISSUE TITLE
Map cannot be read (Chinese RTP not supported)

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1888]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
http://www.mediafire.com/file/k0969lkmqqax6hu/2003_%25E5%25A4%25A9%25E4%25BD%25BF%25E8%259B%258B%25E7%25B3%2595_%25E6%259C%2588%25E8%2597%258D%25E5%2582%25B3%25E5%25A5%2587%25EF%25BC%25A9%25EF%25BC%25A9%25EF%25BD%259E%25E5%2592%2592%25E5%258D%25B0%25E6%2597%258F%25E5%2582%25B3%25E8%25AA%25AA.rar/file
This is the link to download
From the beginning, there is something that cannot be read. There is no way to play with small games.

**Comment by Ghabry** [comment]
It is possible that this is caused by a Chinese 2003 RTP translation we are not aware of.

I found a discussion about this here https://forum.gamer.com.tw/C.php?bsn=4918&snA=23783&page=2 and the linked "Protagonist4" (主角4) looks like a RTP asset.

When started via RPG_RT it also reports a missing 交通工具 which translates to "transportation".

**Comment by Ghabry** [comment]
Found it: https://sites.google.com/site/taiwanrpgplayer/rtp#TOC-RPG-Maker-2003-RTP-

see: RPG Maker 2003 RTP（中文） 

Install with ``env LC_ALL=zh_TW.utf8 wine RPG2003RTP-c.exe``. Should be added to our mapping table, then it will work :)

**Comment by s9060666** [comment]
> 找到它：[https](https://sites.google.com/site/taiwanrpgplayer/rtp#TOC-RPG-Maker-2003-RTP-)：[//sites.google.com/site/taiwanrpgplayer/rtp#TOC-RPG-Maker-2003-RTP-](https://sites.google.com/site/taiwanrpgplayer/rtp#TOC-RPG-Maker-2003-RTP-)
> 
> 請參閱：RPG Maker 2003 RTP（中文）
> 
> 安裝時`env LC_ALL=zh_TW.utf8 wine RPG2003RTP-c.exe`。應該添加到我們的映射表，然後它將工作:)

So... should I wait for you to update? Or I have other ways to fix it

**Comment by Ghabry** [comment]
If you don't want to wait:

1. Install RPG2003RTP-c.exe on your PC

Then, two possible solutions:

Solution 1:
- Copy the installed RPG2003RTP-c into 月藍傳奇2 but don't overwrite existing files

Solution 2:
- OR: Copy the installed RPG2003RTP-c into /easyrpg/rtp/2003 on your Android system

**Comment by s9060666** [comment]
I am waiting for repair

**Comment by Ghabry** [comment]
@s9060666 
This is fixed by now.

If you use Google Play Store you can receive it as a Beta update: https://play.google.com/apps/testing/org.easyrpg.player

Or use a Continuous build (bottom of the page) from https://easyrpg.org/player/downloads/

**Comment by s9060666** [comment]
@Ghabry 
I downloaded the latest version but it has not been fixed
