### ISSUE TITLE
Switch 9.0.0 compatibility requires recompile with latest libnx

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1894]
Switch Update 9.0.0 changed how HID is handled which breaks input in all homebrew. Solution is recompiling with latest libnx (which hopefully does not break our code :/).

Currently Atmosphere has a workaround to fix old homebrew but it will be removed in a later release.

**Comment by Ghabry** [comment]
@carstene1ns 
Guess this was resolved by #1999 too?

**Comment by carstene1ns** [comment]
Oh, right.
