### ISSUE TITLE
Emscripten: "It's now safe to turn off your browser" not shown

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1899]
When quitting web player is not displaying this message since some versions back.

**Comment by Ghabry** [comment]
this doesn't work anymore. Can be likely fixed by using ``addOnExit`` handler instead as suggested here https://github.com/emscripten-core/emscripten/issues/14940

**Comment by Ghabry** [comment]
``-s EXIT_RUNTIME`` works for me
