### ISSUE TITLE
Inn: When not having enough money "leave" is rendered as disabled

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1904]
0.6.1 regression.

Likely broken by the patch which disabled resetting the color when a new line starts.
Inn shares the same logic but for it the color must be reset :/

TEST CASES:

Test 1:
Stay: \c[1]Stay
Leave: Leave

Result:
Amount of money doesn't matter.
\c[1] overwrites the disabled text color.
Leave is drawn in **normal color** → Contrary to normal choices the color is always reset to default after "Stay" was rendered.

Test 2:
Stay: S\c[1]tay
Leave: Leave

Result:
When not enough money the S is drawn in disabled color, otherwise default color.

Test 3:
\c[2]Will you stay the night?
Stay: S\c[1]tay
Leave: Leave

Result:
The Stay in S is always drawn in default color, contrary to normal choices the color of the previous message is not inherited.

**Comment by fmatthew5876** [comment]
This appears a regression from #1751 

At first it looked easy, but the naive fix is to reintroduce the bug fixed by that issue.

**Comment by Ghabry** [comment]
yeah I already thought about a solution before merging your Inn PR and came to the same conclusion.

**Comment by fmatthew5876** [comment]
Test Cases 1 - Inn Text Color
------------------
Set the stay text to "\c[5]Stay"

1. Stay at the inn when you cannot afford

Result: "Stay" is red, "Leave" is normal color

2. Stay at the inn when you can afford

3. Call this event `Show Choices: "\c[5]Yes", "No"

Result: Yes and No are red

4. Change Stay message back to "Stay". Change Inn1 text to start with "\c[5]"

Result: 2 lines of inn text are red, stay and leave are standard colors

5. Prefix inn text with "\s[9]"

Inn text, stay, and leave are all slow.

Conclusion
---------------

All inn choices have an implicit color reset at the start
