### ISSUE TITLE
Game browser shows black text and black about window

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1907]
#### Player platform:
Only tested with the player-js version.

#### Attach files (as a .zip archive or link them)
![Black text](https://user-images.githubusercontent.com/174885/65392200-51f93a00-dd2f-11e9-9f52-d2fe2d31e31e.png)
![Black about](https://user-images.githubusercontent.com/174885/65392201-558cc100-dd2f-11e9-9a3e-ec96c16b67e4.png)

#### Describe the issue in detail and how to reproduce it:
Quick test: open a non-existent game from Emscripten port:
https://easyrpg.org/play/master/?game=404

**Comment by fmatthew5876** [comment]
For whatever reason this seems to be emscripten specific. I don't get this in linux.

**Comment by Ghabry** [comment]
The CACHE\_DEFAULT\_BITMAP is an embedded resource, doesn't go through the async handler.
