### ISSUE TITLE
Android: Play Store says we don't have 64bit support

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1911]
For normal updates the Play Store requires now that we have 64 bit support.

We have 64bit ARM library since 2 years but it seems that some build.gradle update is required, otherwise the automatic check won't detect it -_-

Not sure what the necessary change is but we must resolve this before 0.6.2.

**Comment by carstene1ns** [comment]
Since we have x86 support, we also need `x86_64`:
https://github.com/EasyRPG/Player/blob/064d3a83fff4c08792033d4122fbef773047062a/builds/android/app/src/main/jni/Application.mk#L5

(via https://developer.android.com/distribute/best-practices/develop/64-bit#build-with-64-bit)

**Comment by Ghabry** [comment]
oooh. I forgot about x86_64. Thanks. When we add another ABI we should also consider removing others.
``armeabi`` should be save to remove, newer NDK versions deprecated it.
But ``x86`` must be kept, we have 230 active devices that use this and ``x86_64`` compatible installs are "Not enough to measure" xD

**Comment by Ghabry** [comment]
This is now high priority because Google blocks APK updates:

"This release does not meet the 64-bit requirement of Google Play
The following APKs or app bundles are available on 64-bit devices, but only have native 32-bit code: 6449."

Will test if x86_64 fixes this. Others say that a gradle config options is missing.

**Comment by carstene1ns** [comment]
We should remove `armeabi` and replace it by `x86_64`.

**Comment by Ghabry** [comment]
That was the first I did locally xD
