### ISSUE TITLE
UBSan: Runtime errors found by -fsanitize=integer

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1912]
This is a clang only feature, not supported by gcc. Play any game with such a Player and just look how the log fills. You can combine integer with "address,undefined".
Here are all ubsan options available, maybe "nullability" is also interesting: https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html

The motivation to fix them is: This could miscompile on different compiler versions and WASM will trap when unsigned integer overflow happens. This can be mitigated with a compiler option but this trap handling makes the code slower. When we fix all of them the option could be disabled (assuming no external lib has the same issue :/)

```
/tmp/player/src/pixel_format.h:93:8: runtime error:
implicit conversion from type 'int' of value -16777216 (32-bit, signed) to type 'uint32_t' (aka 'unsigned int') changed the value to 4278190080 (32-bit, unsigned)

/tmp/player/src/exe_reader.cpp:69:23: runtime error:
unsigned integer overflow: 2388645280 + 2087911085 cannot be represented in type 'unsigned int'

/tmp/player/src/utils.cpp:369:17: runtime error:
negation of 16777216 cannot be represented in type 'uint32_t' (aka 'unsigned int')

/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../include/c++/9.1.0/bits/random.tcc:415:26: runtime error:
unsigned integer overf long'

/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../include/c++/9.1.0/bits/random.tcc:415:33: runtime error:
unsigned integer overf long'
```

Stuff in FmMidi, technically not our code, for completeness:
```
/tmp/player/src/midisynth.cpp:694:28: runtime error:
implicit conversion from type 'int' of value -3 (32-bit, signed) to type 'uint_least32_t' (aka 'unsigned int') changed the value to 4294967293 (32-bit, unsigned)

/tmp/player/src/midisynth.cpp:695:56: runtime error:
unsigned integer overflow: 2064 + 4294967293 cannot be represented in type 'unsigned int'

/tmp/player/src/midisynth.cpp:1277:40:runtime error: 
left shift of negative value -38

/tmp/player/src/midisynth.cpp:689:41:runtime error:
unsigned integer overflow: 4268880396 + 30062538 cannot be represented in type 'unsigned int'

/tmp/player/src/midisynth.cpp:695:39: runtime error:
unsigned integer overflow: 4268880396 + 30062538 cannot be represented in type 'unsigned int'
```

**Comment by fmatthew5876** [comment]
The `pixel_format` one can be fixed by changing the `1` constant on that line to `1u`.

The next 2 too deal with computing hashes and random numbers, both of which depend on unsigned overflow. I don't see how they can be fixed.

The last 2 are in the standard library.
