### ISSUE TITLE
Dhux Scar: Problem with transition in parallel process

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1913]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
Dhux Scar: https://rpgmaker.net/games/1492/downloads/1508/

#### Attach files (as a .zip archive or link them)
[Save14_dhux.zip](https://github.com/EasyRPG/Player/files/3643749/Save14_dhux.zip)

#### Describe the issue in detail and how to reproduce it:
"Leave the map to the right. Select Jehridan on the world map and press enter"

#### Simplified test case:
[Transition.zip](https://github.com/EasyRPG/Player/files/3643759/Transition.zip)

Expected: After toggling the switch you are moved to a new map.
What happens: Screen stays black, same map (_toggling the menu will fade in, is this another bug?_)

#### Online test:
https://easyrpg.org/play/master/?game=issue-1913

**Comment by Ghabry** [comment]
The relevant code is the parallel process with run condition "0001 ON"
```
Switch 0001 OFF
Hide Screen
Transfer Player
```

As we know the disabling of the switch will keep the parallel event running until the next yield, then it is destroyed. Because a Screen Hide is a blocking operation without return in RPG\_RT it won't yield the interpreter and Transfer will execute.

**Comment by fmatthew5876** [comment]
Test Cases 1 - parallel map events
-----------------------------

1. EV01 parallel page 1
```
Wait 0.0s
Sw1 on
Sw2 on
```

EV01 page 2 trigger activated by SW01
```
```

Result: Sw1 is on, Sw2 is off

**Comment by fmatthew5876** [comment]
Test Cases 2 - parallel common events
----------------------------

1. CE01 parallel Sw01
```
Sw1 off
Sw2 on
```

Start a new game and enable switch 1

Result: Sw1 off, Sw2 on

**Comment by fmatthew5876** [comment]
Test Cases 3 - parallel events 10k loop limit
----------------------------

1. EV01 parallel
```
Wait 0.0s
Loop:
  Var1 += 1
  If Var1 == 400:
    BreakLoop:
HideScreen
ShowScreen
Loop:
  Var2+=1
```

EV02 parallel
```
Wait 0.0s
Msg: \v[1] \v[2]
```

Result: 400, 2666

Conclusion
---------------

Loop index is not reset by async operations

**Comment by fmatthew5876** [comment]
Test Cases 6 - parallel map events - page flip flop
-----------------------------

1. EV01 parallel page 1 enabled by sw1
```
Sw1 off
Var1 +=1
Sw1 on
Var2 +=1
```

Start the game and turn on sw1

Result: Var1 is some positive value, Var2 is 0

Conclusion
---------------

Re-enabling the same page causes the interpreter to reset itself.

**Comment by fmatthew5876** [comment]
Test Cases 7 - parallel common events - enable flip flop
-----------------------------

1. CE01 parallel enabled by sw1
```
Sw1 off
Var1 +=1
Sw1 on
Var2 +=1
```

Start the game and turn on sw1

Result: Var1 is some positive value, Var2 == Var1

Var1 and 2 increments by 1 each frame.

Conclusion
---------------

Re-enabling the event does *not* cause the interpreter to yield.

**Comment by fmatthew5876** [comment]
Test Cases 6 - autostart map events - page flip flop
-----------------------------

1. EV01 autostart page 1 enabled by sw1
```
Sw1 off
Var1 +=1
Sw1 on
Var2 +=1
```

Start the game and turn on sw1

Result: Var1 is some positive value, Var2 == Var1

Var1 and 2 increments by 1 each frame.

Conclusion
---------------

Foreground interpreter does not yield when page changes.

**Comment by Ghabry** [comment]
sorry that was the wrong one :)
