### ISSUE TITLE
[minor] rename easyrpg_log.txt to easyrpg.log

### ISSUE THREAD

**Issue by pirate486743186** [EasyRPG/Player#1927]
No ones OCD gets triggered by this? >:P
(better leave it in the gitignore)

**Comment by fdelapena** [comment]
If our binary is called `easyrpg-player` or `Player` (`.exe`), it could be just called as the binary but with the .log suffix. This way if the executable is renamed by game developers, it could get a custom name.

----

By the way, a similar behavior exists for the .ini file for specific configurations. Quoting from the wiki:

> ### Behavior after renaming RPG_RT.exe
>
>When `RPG_RT.exe` is renamed, e.g.: `Game.exe`, the `GameTitle` will be read from `Game.ini` and `FullPackageFlag` will be read from `RPG_RT.ini`.
>
>Then, if you want to rename the executable and make the game RTP independent you need to have both `Game.ini` and `RPG_RT.ini` in the same folder with the corresponding parameters.

**Comment by pirate486743186** [comment]
.
