### ISSUE TITLE
Home crash

### ISSUE THREAD

**Issue by DuendeInexistente** [EasyRPG/Player#1929]
Easyrpg-Player: f5230a176ccc71392979b7e17bb8146a753da538
LibLCF: https://github.com/EasyRPG/liblcf/commit/47db42b6977e33591dc5ef1f7644844096d5a7bd

---
#### Player platform:
Ubuntu
#### Attach files (as a .zip archive or link them)
[save.zip](https://github.com/EasyRPG/Player/files/3801187/save.zip)

#### Describe the issue in detail and how to reproduce it:
Upon beginning a fight (ID 103) the game crashes. I tried running it with --no-audio, but it's having a segmentation fault no mater what I do. Triggering the battle manually in the debug menu does not cause this crash.
You can play from the uploaded savegame going up and evading the chasers, or simply use the teleport map to teleport to X30 Y10 (Or the other way around?) in map 145 and using the ghosts around the batter to trigger the battle.

**Comment by fmatthew5876** [comment]
That `save.zip` contains a Map file and a log file. Did you mean to upload saved game?

Please upload a save if you can, it will make it much easier to debug and fix this issue.

**Comment by DuendeInexistente** [comment]
[save.zip](https://github.com/EasyRPG/Player/files/3827748/save.zip)
Huh, weird, but here it is.

**Comment by fmatthew5876** [comment]
The crash is here:

```
#2  0x0000555555a2ad1d in Spriteset_Battle::FindBattler (this=0x0, battler=0x60d000093620) at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/spriteset_battle.cpp:105  
#3  0x0000555555a652e1 in BattleAnimationBattle::FlashTargets (this=0x612000272140, r=0, g=0, b=0, p=0)
    at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/battle_animation.cpp:328   
#4  0x0000555555a64346 in BattleAnimation::UpdateTargetFlash (this=0x612000272140) at
/home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/battle_animation.cpp:223          
#5  0x0000555555a62372 in BattleAnimation::Update (this=0x612000272140) at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/battle_animation.cpp:77                      
#6  0x0000555555a1f1fb in Sprite_Battler::Update (this=0x614000029a50) at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/sprite_battler.cpp:117                        
#7  0x0000555555a2aa59 in Spriteset_Battle::Update (this=0x60800045cd20) at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/spriteset_battle.cpp:94                     
#8  0x0000555555a2a338 in Spriteset_Battle::Spriteset_Battle (this=0x60800045cd20) at
/home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/spriteset_battle.cpp:69           
#9  0x0000555555889eff in Game_Battle::Init () at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/game_battle.cpp:67
#10 0x000055555599267c in Scene_Battle::Start (this=0x616000116a90) at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/scene_battle.cpp:90                              
#11 0x00005555556b2331 in Scene::MainFunction (this=0x616000116a90) at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/scene.cpp:98                                     
#12 0x0000555555664993 in Player::MainLoop () at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/player.cpp:227
#13 0x00005555556648a8 in Player::Run () at /home/matt/EasyRPG/hh3-rm2k/dev/easyrpg/Player/src/player.cpp:221
#14 0x0000555555663dba in main (argc=6, argv=0x7fffffffda38) at /home/matt/EasyRPG/hh3
```

Somehow, there is a `nullptr` in the battlers array which is definitely wrong.

**Comment by Ghabry** [comment]
RPG2k3 has two animation types for allies: The normal animated battler and a "battle animation" battler. This game seems to use battle animations but no idea why it crashes because there is a nullptr-check one line before.
This can be configured in the Battle 2 (or was it Animation 2?) tab.
