### ISSUE TITLE
The screen transition change command is omitted

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1931]
**Name of the game**: Super Crystal Hunter
**Player platform**: 0.6.1 Windows 10 x64
**Describe the issue in detail and how to reproduce it**:

In the system tab, the game has transitions configured as instantaneous. However, after a cinematics in an event in parallel process, the "Change Screen Transition: Transfer (Show), Fade In" command is applied, but Player continues to transition instantly.

https://i.ibb.co/qgspYM6/transicion-suavizada.png

**Comment by fmatthew5876** [comment]
I made an even with changes the screen transition then I teleported somewhere and it work as expected. Could we get a save game here too?

**Comment by fmatthew5876** [comment]
I don't see the bug here. In both player and RPG_RT, after the "Well Done" text, there is an instant transition out (which doesn't actually fade out), followed by a fade in.

In your picture, you're setting the Show Screen transition, not the Hide Screen one. Is this a game bug? Or am I missing something?

**Comment by Br4ssman** [comment]
I don't know if it is due to an odd behavior of RPG_RT, the idea there, is that the transition is noticed as little as possible when making the "sleight of hand" by exchanging the dummy event with the Player event.

I suppose that putting the command for that screen transition (even if from the system tab it is configured as an instant transition) and when making the transition on the same map, it does not notice a sudden transition, as happens in Player.

**Comment by Ghabry** [comment]
Can't see the problem either. Can you provide a video?

**Comment by Br4ssman** [comment]
Here: https://app.box.com/s/q0fu9pmhovwk1lvxugm1bzxyztxkcsh4

**Comment by Ghabry** [comment]
The difference I see is that in Player there is a short flash on the hero when the [i] fades in but in RPG_RT it isnt?

**Comment by Br4ssman** [comment]
Yeah, when changing the type of transition the teleport is shown in a smoother way, while in Player it occurs sharply

**Comment by fmatthew5876** [comment]
So this is related to some special behavior with instantaneous transition type.

This type is only selectable as a default transition type for hide screen. You can't invoke it directly from an event.

| Hide Screen | Action | Result |
| -- | -- | -- |
| Instantaneous | Teleport | Transition from old screen to new, with no black |
| Instantaneous | Cmd Hidet ; Cmd Show | Waits 32 frames :exclamation: , black, transition in |
| Cut Out | Teleport | Black, transition in |
| Cut Out | Cmd Hide, Cmd Show | Black, transition  in |

The bug :exclamation: is the behavior described in #1934
