### ISSUE TITLE
Instantaneous Screen Transition graphical bug

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#1934]
Change the default transition out to "Instantaneous" and default transition in to something else

Now make an event:
```
HideScreen: Default
ShowScreen: Default
```

In RPG_RT, the screen will instantly do the transition in effect from black. In Player, no visible effect is seen.

**Comment by Br4ssman** [comment]
It could be the same in https://github.com/EasyRPG/Player/issues/1931
