### ISSUE TITLE
Place selector breaks when loading the game

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1935]
**Name of the game**: Super Crystal Hunter
**Player platform**: Player 0.6.1, Win 10 x64
**Describe the issue in detail and how to reproduce it**:

In world map, press X/ESC to open contextual menu, press save game, then reboot game (or press X/ESC again to open menu and press retry to load game). You can't move through the diferent places in world map until press resume in contextual menu.

**Comment by fmatthew5876** [comment]
I also see the "List index has exceeded its valid range (0)." error which crashes RPG_RT when loading a Player saved game. Just start the example game, save in Player, load in RPG_RT and you'll hit it.

**Comment by fmatthew5876** [comment]
The list Index crash is fixed by https://github.com/EasyRPG/liblcf/pull/345 . Now onto the main issues here..

**Comment by fmatthew5876** [comment]
Fix for this is now included in #1942
