### ISSUE TITLE
Possible z-order event bug

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1937]
**Name of the game**: Super Crystal Hunter
**Player platform**: Player 0.6.1, Win10 x64
**Describe the issue in detail and how to reproduce it**:

Create 2 events.

One of them with the next commands in parallel process:

`
@> Set Move Route: [Jumper], Jump , Land
@> Wait: 0.1 seconds
`

The 2nd event will be the "Jumper" event, configured with:

- Priority: Same as character
- Animation Type: Fixed Graphic (in pattern frame- Right)

The video shows the error in Player 0.6.1
[z-index _error.zip](https://github.com/EasyRPG/Player/files/3831367/z-index._error.zip)

**Comment by Ghabry** [comment]
The jump value is considered in this line but it appears to be insufficient: https://github.com/EasyRPG/Player/blob/master/src/game_character.cpp#L114

The Z-Values should be checked and a suitable offset for "jumping" applied.
Question is whether the Z-value is always higher than the rest when jumping and if the jump direction (downwards or upwards tile) matters.

**Comment by fmatthew5876** [comment]
Our jumping code is actually pretty accurate

Here is a screenshot of 3 rows.

Each row from top to bottom the jumpers are: Above, Same, Below

RPG_RT:
![jump_RPG_RT](https://user-images.githubusercontent.com/1198466/69010440-cfa38580-092d-11ea-875f-3368f9781260.png)

Player:
![jump_Player](https://user-images.githubusercontent.com/1198466/69010442-d0d4b280-092d-11ea-8fec-515bfe6c2ec9.png)


Essentially the rule seems to be that a jumping event is a above all events on the same level as him. Player handles all of these correctly.

What it doesn't handle is the relation of the player event to jump same level events. Somehow the player gets rendered above.
