### ISSUE TITLE
Show Animation follows event

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1938]
**Name of the game**: Super Crystal Hunter
**Player platform**: Player 0.6.1, Win10 x64
**Describe the issue in detail and how to reproduce it**:

Create 2 events.
Event A in Parallel Process with:

`@> Set Move Route: [EventB], Wait, Jump , Land , Wait @> Wait: 0.5 seconds`

EventB: in Fixed graphic with pattern left and its priority as "same as character".
In its contents, put any command "Show animation" and interact with event Player.

Video showing all of that in Player 0.6.1:
[animation-follow-event.zip](https://github.com/EasyRPG/Player/files/3831430/animation-follow-event.zip)

**Comment by fmatthew5876** [comment]
In RPG_RT, animations will follow events as they move around, however the animation Y will ignore jump height.

In player we add the jump height, which is wrong.
