### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1939]
This is in general, using Player 0.6.1 for windows 10.

I note RPG_RT makes fade screen to black when press slot to load and fade out when the game is loaded (the black screen  remains between 1 - 2 sec), whereas Player makes load game immediately (sharply)

2 examples RPG_RT and Player.

[Player-load.zip](https://github.com/EasyRPG/Player/files/3832100/Player-load.zip)
[RPG_RT-load.zip](https://github.com/EasyRPG/Player/files/3832101/RPG_RT-load.zip)

**Comment by fmatthew5876** [comment]
The issue doesn't appear to be with the transitions, but the lack of the black screen delay between transitions. I don't know how many frames it lasts.

I also observe this with:

- [ ] New Game
- [ ] Load Game
- [ ] Return to Title Screen

**Comment by Ghabry** [comment]
you can try calling Player::FrameReset after the long taking function call.

**Comment by fmatthew5876** [comment]
Well I did a screen capture with simplevideorecorder on linux. It looks like it *might* be a delay of around 32 frames.
