### ISSUE TITLE
Clouds stick on screen after saving

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1943]
**Name of the game**: Super Crystal Hunter
**Player platform**: Player 0.6.1, Win10 x64
**Describe the issue in detail and how to reproduce it**:

Checking the good job in https://github.com/EasyRPG/Player/issues/1935 after save game, if the clouds of weather system are passing, they stick on the screen.

You can try it with the world map test game I sent in EasyRPG chat room.

video-bug:
[clouds_after_saving.zip](https://github.com/EasyRPG/Player/files/3857731/clouds_after_saving.zip)

**Comment by fmatthew5876** [comment]
Definitely something very wrong with move picture chunks. Save your game while a picture is moving in RPG_RT or Player and load in the other and it will be broken.

**Comment by Ghabry** [comment]
In the chat Br4ssman wrote that the clouds are RNG, better use a constant "--seed" for testing

**Comment by fmatthew5876** [comment]
@Br4ssman can you retest this one with #1953 ?

**Comment by Br4ssman** [comment]
When the clouds begin to pass, I save game, then load game and the clouds have disappeared, but the tint screen which causes the light get dim when the clouds pass is properly respected.

**Comment by fmatthew5876** [comment]
This is fixed now in #1953

**Comment by Br4ssman** [comment]
Yeah, it works.

Thanks.
