### ISSUE TITLE
Picture wave must be more accurate

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1946]
**Name of the game**: Super Crystal Hunter
**Player platform**: Player 0.6.1, Win10 x64
**Describe the issue in detail and how to reproduce it**:

I noted (from my last issue https://github.com/EasyRPG/Player/issues/1945) the wave doesn't make the same effect in Player, maybe for the same reason (new features from 2k3).

Check out the results in video:
https://app.box.com/s/dt7pwwyz4tlfkam534l1qf0ezdzoludt

Also I send you a small a test game with the picture and custom snowfall.
[wave_picture.zip](https://github.com/EasyRPG/Player/files/3862702/wave_picture.zip)

**Comment by fmatthew5876** [comment]
As shown in Player #1703 Test case 7,

The wave effect does a full cycle in 32 frames. From a simple test it looks like player is slower than RPG_RT.
