### ISSUE TITLE
Eternal Legends: Boss battle ends after 1st phase

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1998]
Can't be tested. Blocked by #1997

#### Name of the game: Eternal Legends
https://rmarchiv.tk/games/595 (use 2.27a)

The original bug report via IRC (thanks!) is about 2.26. Also available on rmarchiv.tk. Maybe test both versions if not reprocuable.

#### Attach files (as a .zip archive or link them)
[Save14_el.zip](https://github.com/EasyRPG/Player/files/3991393/Save14_el.zip)

#### Describe the issue in detail and how to reproduce it:

Walk to the right into the next room, defeat the first phase.
In RPG_RT the 2nd boss phase starts, in Player the fight is over :tada: 

There are also two other things noticable, not verified if they are in the original game:
 - There is some "piece of dirt" in the middle of the screen
 - One of the fades to the boss shows the old map.

**Comment by carstene1ns** [comment]
Maybe should be also tried against version 2.26 like in the original bug report.

**Comment by Ghabry** [comment]
More context: ID 241

The boss order is:
Phase 1: 3: Gott der Zerstörung
Phase 2: 2: Gott der Zerstörung
Phase 3: 1: Gott der Zerstörung

Relevant is only Page 1. When the enemy HP is 0-50% it will do a full heal "Selbstgeheilt" once, then the second time 0-50% is reached it executes:

```
@> Change Enemy State: [3:Gott der Zerstung], + [$o Tod] <-- All enemies dead here
@> Tint Screen: (120,0,0,100), @5.0s
@> Show Animation: [Bio], [1:Gott der Zerstung]
@> Play SE: 'Monster2', 100, 50, 50
@> Tint Screen: (200,200,0,100), @4.5s, Wait
@> Flash Screen: Once, (22,0,31,31), @1.0s, Wait
@> Shake Screen: Once, 5, 5, @0.2s, Wait
@> Show Animation: [Feuer], [3:Gott der Zerstung], Wait
@> Enemy Encounter: [2:Gott der Zerstung] <-- Next enemy spawns here
@> Tint Screen: (100,100,100,100), @1.8s, Wait
@> Control Switches: [4191:Phase1] = OFF
@> Control Switches: [4192:Phase2] = ON
@> Control Switches: [4190:Selbstgeheilt] = OFF
```

**Comment by fmatthew5876** [comment]
Things to verify:

- [ ] When all party dead and interpreter running
- [ ] When all enemies dead and interpreter running
- [ ] When all enemies not visible (but not dead) and interpreter running

Versions to check
- [ ] 2k3e
- [ ] 2ke
- [ ] 2k legacy

**Comment by fmatthew5876** [comment]
Test Cases 1
---------------------

Create a Battle where all enemies are invisible

1. Start the battle
Result: Win

2. Add a turn 0 event which activates an enemy
Result: Win

Conclusion
---------------

Events not run before first win / loss check.

**Comment by fmatthew5876** [comment]
Test Cases 2 - Death Scenarios
--------------------

Make a battle with 2 enemies, first visible, second not

1. Turn 0 event
```
Change HP Party -9999: Allow Death
TintScreen (200,100,100) 2.0s, Wait
```

Result: Tint, then game over


2. Turn 0 event
```
Change HP Enemy 1 -99999: Allow death
TintScreen (200,100,100) 2.0s, Wait
```

Result: Enemy 1 death animation, Tint, Win


3. Turn 0 event
```
Change HP Enemy 2 -99999: Allow death
TintScreen (200,100,100) 2.0s, Wait
```

Result: Enemy 2 visible, Enemy 2 death animation, Tint, Continue battle


4. Turn 0 event
```
Change HP Enemy 2 -99999: Allow death
Change HP Enemy 2 -99999: Allow death
TintScreen (200,100,100) 2.0s, Wait
```

Result: Enemy 2 visible, Enemy 1 & 2 death animations, Tint, Win

Conclusions
----------------

* Invisible enemies appear and death animate when killed by events
* Interpreter waits for events to finish before doing win/loss checks
