### ISSUE TITLE
Aëdemphia: Image BMP needs support for BITMAPCOREHEADER

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2016]
#### Attach files (as a .zip archive or link them)
Problematic bitmap:
[continentest.zip](https://github.com/EasyRPG/Player/files/4002983/continentest.zip)

#### Describe the issue in detail and how to reproduce it:
This happens on the world map but the real issue is our bitmap reader (image_bmp).

1. The size of the DIP header at offset 0Eh should be checked. We only support the Win32 BITMAPINFOHEADER which has a size of 40d but there are others
2. Here the size is 12d, which means it is a BITMAPCOREHEADER: https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapcoreheader

**Comment by carstene1ns** [comment]
Ok. So these really exist in the wild. :8ball:
(Good thing this game is not big already. Might bloat this up with some bitmaps)
