### ISSUE TITLE
Android: migrate from deprecated support library to AndroidX

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#2018]
https://developer.android.com/jetpack/androidx/migrate

**Comment by BlisterB** [comment]
I can watch for that, but preferably after my PR are processed (this seems to be a big subject, source for many conflicts and problems).

I'm discovering the topic but we will probably have to change the minimum API.
At the time I targeted API 14 (which was already overkilled at the time). It brought a lot of constraints but it will be the opportunity to do/redo a lot of nice things.

For information:

<img width="1125" alt="Capture d’écran 2020-07-03 à 10 59 55" src="https://user-images.githubusercontent.com/2387475/86452971-5b332080-bd1d-11ea-857a-b37113999a2b.png">
<img width="555" alt="Capture d’écran 2020-07-03 à 11 02 01" src="https://user-images.githubusercontent.com/2387475/86452979-5e2e1100-bd1d-11ea-9cc6-7c3bb5de10c2.png">

**Comment by BlisterB** [comment]
@fdelapena Do we have the distribution of Android versions using the app ?

**Comment by Ghabry** [comment]
@BlisterB right now we target API 15 as the NDK dropped support a while ago for older version.

**Comment by Ghabry** [comment]
@BlisterB in the ongoing approach of Google to make there Uis more crap it is not possible anymore in the Android console to plot more than 5 Android versions at once m(. In general they made all the statistic stuff really bad and hard to use... (and of course no CSV export)

Copy paste from the website:
```
Alle Android-Versionen | 20.908
-- | --
  | Android 9 | 6.706
  | Android 10 | 6.089
  | Android 8.0 | 1.719
  | Android 8.1 | 1.511
  | Android 7.0 | 1.365
  | Android 6.0 | 1.167
  | Android 7.1 | 751
  | Android 5.1 | 607
  | Android 4.4 | 513
  | Android 5.0 | 294
  | Android 4.2 | 93
  | Android 4.1 | 52
  | Android 4.3 | 19
  | Android 4.0.3 - 4.0.4 | 8
  | Android 2.3.3 - 2.3.7 | 4
```

**Comment by BlisterB** [comment]
@Ghabry Thank you for the information.

I've been able to migrate to AndroidX without too many problems. I didn't have to change the minimum API (currently set to 14).
