### ISSUE TITLE
Title screen dissapears + New game state not reset

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2023]
1. Start a game to the title screen
2. Enter the load game menu
3. Exit the load game menu
4. Start a new game
5. Quit the new game with F12 or "Return to Title" from the menu

The title image is missing from the title screen.

**Comment by fmatthew5876** [comment]
Turns out this issue is much more serious than just the title scene.

If you follow the steps above, and then start a new game, many of the game state doesn't get reset.

For example if in step (4) you bought a potion, then after step (5) you start a new game again, you'll have the potion in your inventory.

#2023 fixes this also

**Comment by carstene1ns** [comment]
> #2023 fixes this also

Wrong issue linked (self reference).
