### ISSUE TITLE
Tempo changes the Tone of MIDI songs

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#2029]
#### Describe the issue in detail and how to reproduce it:
Play a MIDI modifying the Tempo.
In RPG_RT, Tempo will change the speed of a song (if it is a MIDI file, if it is MP3 will change speed and Tone), but in Player change the speed and tone, like MP3 files.

**Comment by elsemieni** [comment]
This is only in fluidsynth-based builds (not nightly/jenkins builds), since tempo changes fluidsynth output (a stream). I assume this will not happen in FMMIDI/WildMIDI (however, instrument patches will be affected to this?)

**Comment by Ghabry** [comment]
WildMidi does not support tempo changes. It will always go through our resampler.

FmMidi and Fluidsynth work by making the time run faster. So this should sound similar to harmony? Needs a test when this is merged.

**Comment by fdelapena** [comment]
> FmMidi and Fluidsynth work by making the time run faster.

Yes, there is no pitch change in RPG_RT MIDIs,

**Comment by Ghabry** [comment]
Note that this is only fixed for Fluidsynth, FmMidi and any new Midi sequencer libraries (if contributed).

It is not fixed for WildMidi and is unlikely that it ever will be.

For WildMidi this would need a resampling that increases the speed while keeping the pitch (no idea how this is called, the Youtube playspeed feature and my Podcast app do this).
