### ISSUE TITLE
Characters freeze when using hidden channels

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#2038]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android 
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:Using the record I provided, the character presses the confirmation key and a dialogue appears, and the character freezes
https://drive.google.com/file/d/15Kz2gTy4SjQJIe17JUKmMruLQVdlkqZX/view?usp=drivesdk

**Comment by s9060666** [comment]
http://www.mediafire.com/download/k0969lkmqqax6hu/2003_%E5%A4%A9%E4%BD%BF%E8%9B%8B%E7%B3%95_%E6%9C%88%E8%97%8D%E5%82%B3%E5%A5%87%EF%BC%A9%EF%BC%A9%EF%BD%9E%E5%92%92%E5%8D%B0%E6%97%8F%E5%82%B3%E8%AA%AA.rar
This is the download link for the game

**Comment by fmatthew5876** [comment]
Move routes bug. Somehow an event is getting stuck on this code:

```
SetMoveRoute: Player(skip), Through On, Move Up
WaitForAllMovement
```

The player steps up, but the `WaitForAllMovement` command never finishes.

**Comment by fmatthew5876** [comment]
@s9060666 This looks like a bug in the game itself and not a bug in Player.

I am unable to run chinese RPG_RT.exe on my computer. Can you please confirm whether or not the bug still happens with RPG_RT.exe?

Finally, if you want to workaround the issue. You can walk down, exit the map, come back, and then open the secret door and it won't hang anymore.

**Comment by fmatthew5876** [comment]
Ok this is a real Player bug, the save game is messed up because it's already after the bug occurred.

To see the actual bug, do the following:

1. Load the save game
2. Walk down and exit the map
3. Set Variable35 = 5
4. Re-enter the map
5. A cutscene will play
6. Then you will regain control of the player on the map.

In RPG_RT, the Event 5 from the cutscene is near the top of the map wandering around. If you try to enter the secret cave, it works.

In Player, event 5 is stuck against the flowers still trying to walk down. If you try to enter the secret cave, the game hangs.

Somehow after the cutscene, the move route of the event doesn't get cleared. There is an event page change and several teleports so something is going wrong, causing the event to get stuck in the move route.

**Comment by fmatthew5876** [comment]
This looks related to the fix for #1261 
 
The end of the cutscene essentially has this
```
Teleport this map
Teleport other map
Teleport this map
```

The teleport other map command gets skipped over and never happens. As a result, the move route for the event is never cleared.

**Comment by fmatthew5876** [comment]
Test Cases 1 - Multiple teleports
--------------------------------

Map A with these events

EV01 parallel `Teleport Map1`
EV02 parallel `Teleport Map2`
EV03 autostart `Teleport Map3`
EV04 autostart `Teleport Map4`

Map B with these events

EV01 parallel `Wait 0.0s, Teleport Map1`
EV02 parallel `Wait 0.0s, Teleport Map2`
EV03 autostart `Teleport Map3`
EV04 autostart `Teleport Map4`

Map C with these events

EV01 Parallel `Wait 0.0s Teleport Map A`

Map D with these events

EV01 Autostart `Wait 0.0s Teleport Map A`

Map E with these events

EV01 Parallel `Wait 0.0s Teleport Map B`

Map F with these events

EV01 Autostart `Wait 0.0s Teleport Map B`

1. New game on mapA

Result: Game starts on map 2

2. New game on map B

Result: Game starts on map 3

3. New game on map C

Result: Starts on map C, teleports to map 2

4. New game on map D

Result: Starts on map D, teleports to map 2

4. New game on map E

Result: Starts on map E, teleports to map B, teleports to map 3

4. New game on map F

Result: Starts on map E, teleports to map B, teleports to map 3

**Comment by fmatthew5876** [comment]
Test Cases 2 - Multiple teleports
==============

Map B with these events

EV01 parallel `Wait 0.0s, Teleport Map1`
EV02 parallel `Wait 0.0s, Teleport Map2`
EV03 autostart `Teleport Map3`
EV04 autostart `Teleport Map4`

1
----
New game on map B

Result: Starts on map B, teleports to map 3

2
---
Start on Map D with EV01 Parallel `Teleport Map B`

Result: Starts on map B, teleports to map 3

3
---
Start on Map D with EV01 Parallel `Wait 0.0s Teleport Map A`

Result: Starts on map D, teleports to map B, teleports to map 3

4
---
Start on Map D with EV01 Autostart `Teleport Map A`

Result: Starts on map D, teleports to map B, teleports to map 3

**Comment by fmatthew5876** [comment]
Test Cases 3 - Multiple teleports
==============

Map C with these events

EV01 autostart `Teleport Map3`
EV02 autostart `Teleport Map4`

1
----
New game on map C

Result: Starts on map C, teleports to map 3

2
---
Start on Map D with EV01 Parallel `Teleport Map C`

Result: Starts on map C, teleports to map 3

3
---
Start on Map D with EV01 Parallel `Wait 0.0s Teleport Map C`

Result: Starts on map D, teleports to map C, teleports to map 3

4
---
Start on Map D with EV01 Autostart `Teleport Map C`

Result: Starts on map D, teleports to map C, teleports to map 3

**Comment by fmatthew5876** [comment]
Test Cases 4 - Multiple teleports - with transition in
==============

Map D with these events

EV01 parallel `ShowScreen; Var1+=1; Teleport Map1`
EV02 parallel `Var2 +=1; Teleport Map2`
EV03 autostart `Var3 +=1; Teleport Map3`
EV04 autostart `Var4 += 1; Teleport Map4`

1
---
New game on mapD

Result: Start on Map D, teleport map 2, Vars (1, 1, 0, 0)

2
---
Start on Map L with EV01 Parallel `Teleport Map A`

Result: Starts on map D, teleports to map 2, Vars (1, 1, 0, 0)

3
---
Start on Map L with EV01 Parallel `Wait 0.0s Teleport Map A`

Result: Starts on map L,  teleports to map D, teleports to map 2 Vars (1, 1, 0, 0)

4
---
Start on Map D with EV01 Autostart `Teleport Map A`

Result: Starts on map L, teleports to map D, teleports to map 2 ❕ , Vars (1, 1, 0, 0) ❕
