### ISSUE TITLE
Max level in menu with experience points / -------

### ISSUE THREAD

**Issue by gadesx** [EasyRPG/Player#2039]
With max level of character, in menu appears the experience points in player,
only ----- in RPG_RT

**Comment by gadesx** [comment]
https://i.postimg.cc/85yz19Sm/exp.png

**Comment by Ghabry** [comment]
That's a design decision I made because there is no reason to show cur exp as dashes because the value is known.
Maybe you love farming then you can know when the exp reach 999999 ;)

**Comment by Ghabry** [comment]
#2027 has a change for this. but as I said design decision this is open for discussion.

**Comment by fmatthew5876** [comment]
I noticed this and added it to #2027. But I don't have a strong opinion either way. I can see Ghabry point about keeping the numbers so obsessive gamers can always know how much exp they have.
