### ISSUE TITLE
Yume2kki: The second sound room doesn't work

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2049]
#### Name of the game:
Yume2kki 

#### Attach files
https://github.com/EasyRPG/Player/files/3490326/yume2kkiaudio.zip

* At the Computer select "Music"
* Press ESC to open the menu.
* Select ..... [1/2] (thats the last option)
* Select the 3rd option (サウンドルーム...)
* Select the 2nd option (... SR ...)

In 0.109f the Player will get stuck in an endless "Load music X%" loop.
In 0.111 the Player will get stuck at a blackscreen after the "Load music" loop.

**Comment by fmatthew5876** [comment]
I tried it with 0.111.

This looks like a transitions issue. If you use F9 to call the debug menu and then return, the screen is visible.

**Comment by Ghabry** [comment]
This game is the worst -_-

@CherryDT any idea if a transition of -1 does anything special?

**Comment by Ghabry** [comment]
Will also test your fix with 0.109f later.

**Comment by CherryDT** [comment]
It means "default from database"

**Comment by Ghabry** [comment]
Excellent, thanks for this information.

Now I wonder if there are more "secret" options like this hidden elsewhere for other commands... Time (or VipRPG ;)) will tell.

**Comment by Ghabry** [comment]
This also implies that our defaults for all the transition stuff in liblcf is wrong btw.

**Comment by fmatthew5876** [comment]
I suspected it was this after finishing last night. Will look into proper fixes for transition chunks

**Comment by fmatthew5876** [comment]
I did some test of this, the chunks do default to -1. There are also 2 interesting behaviors.

* These chunks are always present in the LSD file, even if defaulted to -1.
* If you change the transition to the same as the default, it goes to -1. 

So for example if you changed the fade in to "Random Blocks". If the default was "Fade In", the chunk would be set to 1. But if the default was "Random Blocks" the chunk would get -1.

**Comment by Ghabry** [comment]
The "Load music X%" loop which counts incorrectly (and downwards o.O) in 0.109f ends after waiting for a while and opens the room.
If somebody wants to file a bug for this feel free to do it, though is likely undocumented stuff again (and in 0.111 it works perfectly).
