### ISSUE TITLE
Variable lose its value when transfer Player as "Player Touch" event

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#2057]
**Name of the game**: Super Crystal Hunter
**Player platform**: Win10 x64
**Describe the issue in detail and how to reproduce it**:

The intro can be advanced until the next part (pressing Z/Enter key) or skip the entire intro (pressing X/Esc).
![imagen](https://user-images.githubusercontent.com/18174790/72680085-0de82d00-3ab6-11ea-827d-32aecce5a51e.png)

If you just advance the intro, you can't exit the old man's house until you talk with him. While the player press each "show choice" when talks with the old man, a variable add 1. When this variable is =3, then the player can exit from the house.

![tuto](https://user-images.githubusercontent.com/18174790/72680387-869cb880-3ab9-11ea-9b0a-4bf48d2946a1.PNG)

But, if you skip the entire intro the variable will be =3 directly and player can exit from the house without talking with old man.

![intro-skipped](https://user-images.githubusercontent.com/18174790/72680397-a8963b00-3ab9-11ea-8720-2af0b16fcbfe.PNG)

Well, all of that works on RPG_RT.
In Player, if you skip the intro, you can exit from the house, but if you back again, and talk the old man, then you cannot exit because it's like the variable has a different value than 3 or has been reset.

**Comment by Br4ssman** [comment]
Okay, forget that.

The issue was my fault, sorry.

**Comment by Ghabry** [comment]
This is nice to show that the Player is fairly advanced by now: We reach a level where game bugs are mistaken with Player bugs :)
