### ISSUE TITLE
Test suite crashes on Windows

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#2061]
in parse test.

**Comment by Ghabry** [comment]
I will update the jenkins job to get a "Build is unstable" reported when the unit tests fail. Lets see if this is possible with Batch...

**Comment by Ghabry** [comment]
Appears to work :+1:

**Comment by carstene1ns** [comment]
> I will update the jenkins job to get a "Build is unstable" reported when the unit tests fail. Lets see if this is possible with Batch...

If I remember correctly, I tested this too. :grinning:

**Comment by Ghabry** [comment]
yes you added it for macOS. I copied the solution from there :D
