### ISSUE TITLE
Rain and snow effects are slightly too strong

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2069]
1. Cause any strength level of rain or snow effect.
2. Take a screen grab of both RPG_RT and Player
3. Count the particles

You'll see nearly every time Player has more particles on the screen than RPG_RT. There also seems to be a bit more randomness in RPG_RT with how many particles are on the screen each frame. 

Our algorithm for how we spawn new particles needs to be tweaked.

The difference is most obvious at "Weak" strength levels.

**Comment by fmatthew5876** [comment]
Notes from Cherry on Discord about this one:

```
CherryToday at 5:04 PM
I believe it has some non-trivial thing where it uses 100 permanent particles which have a lifetime and position, and those are updated with some randomness.
I think the strength just controls how many of those particles are actually drawn

the particles are in the RPG::ScreenEffect structure in DynRPG (from PepsiOtaku's version)
however, the structure is bigger than what is declared in http://www.rewking.com/dynrpg/_screen_effect_8h_source.html

no guarantees but I think the particles start at offset 0x94
maybe I'm off by 4 or 8 bytes, you'll have to check.
it should be an array with 100 elements consisting of 3 integers each
so, 300 integers in total
so you can log them to a file every frame or whatever

struct Particle {
  int t;
  int x;
  int y;
};

Particle* particles = (Particle*)(((int)RPG::screen->screenEffect)+0x94);

// use particles[0...99]

something like that
again, I'm not 100% sure about the offset 0x94 here, so if you get weird data in the first or last particle or an access violation, adjust the offset a bit

I said the strength controls how many of those particles are actually drawn - but I think additionally it also affects the alpha used
(and the t affects alpha also, obviously.)

Our alphas for rain and sand are pretty close to perfect now, using screen captures
Rain and snow*
Sand is very strange. A lot of randomness
Thanks for all your help. With this and things before

I know the general idea is that t/x/y are initialized randomly on startup, and later on t is usually decremented if >0, and when it was 0 then only with a certain chance the particle is reinitialized (t being set back to some starting value (different per weather type), x/y being randomly set), otherwise nothing happens. x/y are modified every frame, with certain randomness as well.
the behavior is different for different weather types, obviously

you can access the internal image that is used for the weather "sprites" if needed (it is used in combination with some tint), it is an RPG::Image * 3 DWORDs before the particles array (so at +0x88 if my offset was right before)

it should be easy to determine if you log these particles over some time and then write some code to tell how you long particles stayed "dead", then you should be able to derive what random range was used
```

**Comment by fmatthew5876** [comment]
I found the weather data in DynRPG and put it here: https://github.com/fmatthew5876/dynrpg/blob/master/dynrpg/sdk/include/DynRPG/ScreenEffect.h#L114

I've been able to start dumping this information using `onFrame()` using event tracer.

More to come..

**Comment by fmatthew5876** [comment]
Fog
====

The fog effect is the most simple.

When fog is started, all the particles t,x, and y get random values. (range?)

Each frame x0 and x4 increment by 1. And that's all that happens.. All other fields remain constant. I guess these 2 values are somehow used as frame counters for the moving layers??

I can't find anything describing the random 1 pixel vertical movement that happens infrequently. :disappointed: 

Using DynRPG I was able to take advantage of the shake screen bug. I fixed the shake offset to a very large X value locking the shake time > 0. This lets us see exactly how long it takes the 16x16 texture to move left one full cycle and repeat itself. This also lets us get a much better look at the background fog layer. What I learned was that the back layer moves much faster than the front layer.

![flipfog](https://user-images.githubusercontent.com/1198466/78518946-cb1e2300-778f-11ea-9941-f0d9a77a3ea8.gif)

The front layer moves one pixel to the left every 16 frames. The back layer moves one pixel to the right every 8 frames.

**Comment by fmatthew5876** [comment]
Rain
====

TBD

Facts Known:
- [x] For all strength levels, particles 0 to 99 animate each frame

Unknown:
- [ ] How many particles active per strength level?
- [ ] Confirm how movement works
- [ ] Confirm death and generation

**Comment by fmatthew5876** [comment]
Sand
====

We can use the same trick as in rain and snow to see how many sand particles are visible. Note the first 2 particles are absent because they are used for the fog layers.

![sand_part](https://user-images.githubusercontent.com/1198466/78615211-de3bfc00-783e-11ea-967e-6c1e72be251f.png)
(Sand, Strong, all particles locked to t=80)

And for particle regeneration, this time counting streaks for all particles from 2 to 254

![sand_hist](https://user-images.githubusercontent.com/1198466/78616424-2c063380-7842-11ea-912d-74734ccbadc2.png)


- [x] Particles 0 and 1 operate the same as in fog
- [x] Each frame all particles 2 to 254 animate whether they are visible or not
- [x] Each frame, if `t > 0`, then `t -= 1`
- [ ] Each frame, if `t > 0`, then `x ??`
- [ ] Each frame, if `t > 0`, then `y ??`
- [x] Each frame when `t == 0`, the particle has a 10% change to regenerate
- [ ] When particles regenerate, they are set to `(80, rand(??,??), rand(??, ??)`. Note this means that the very first sand particles have shorter lifetimes than normal.
- [x] If the particle doesn't regenerate, it's x and y values stay constant
- [x] Weak: particles 2 to 127 are visible if `t > 0`
- [x] Med: particles 2 to 190 are visible if `t > 0`
- [x] Strong: particles 2 to 254 are visible if `t > 0`
- [ ] Colors?
- [ ] Padding fields used?

**Comment by fmatthew5876** [comment]
Sandstorm Particle generation
=======================

The last tricky business here is figuring out the algorithm that generates the x,y,ax, and ay values for each sandstorm particle.

So far I've sampled them from dynrpg and have a scatterplot.

x ranges from -189 to +189 (measured from the center of the screen)
y ranges 0 to 95
ax ranges (-2.0,2.0)
ay ranges (0.0, 2.0)

![sand_dist](https://user-images.githubusercontent.com/1198466/78742972-5aac0900-792b-11ea-9054-0fe618a4f4df.png)

**Comment by Ghabry** [comment]
Could you plot them again with transparency so we can see if the distribution for the "hourglass" and the triangle are completely random or also biased (darker/brighter spots)?

**Comment by fmatthew5876** [comment]
Here is the sandstorm particle assembly code

| Address | Hex | Asm | Comment |
| -- | -- | -- | -- |
| 004C30F6 | 837CFE 68 00             | cmp dword ptr ds:[esi+edi*8+68],0       | Check if t == 0
| 004C30FB | 0F85 CD000000            | jne rpg_rt.4C31CE                       |
004C3101 | B8 0A000000              | mov eax,A                               | A:'\n'
004C3106 | E8 49FFF3FF              | call rpg_rt.403054                      |
004C310B | 85C0                     | test eax,eax                            |
004C310D | 0F85 07010000            | jne rpg_rt.4C321A                       |
004C3113 | B8 7F000000              | mov eax,7F                              |
004C3118 | E8 37FFF3FF              | call rpg_rt.403054                      |
004C311D | 40                       | inc eax                                 |
004C311E | E8 C137FAFF              | call rpg_rt.4668E4                      |
004C3123 | DD1C24                   | fstp qword ptr ss:[esp],st(0)           |
004C3126 | 9B                       | fwait                                   |
004C3127 | B8 7F000000              | mov eax,7F                              |
004C312C | E8 23FFF3FF              | call rpg_rt.403054                      |
004C3131 | 40                       | inc eax                                 |
004C3132 | E8 8937FAFF              | call rpg_rt.4668C0                      |
004C3137 | DD5C24 08                | fstp qword ptr ss:[esp+8],st(0)         |
004C313B | 9B                       | fwait                                   |
004C313C | B8 50000000              | mov eax,50                              | 50:'P'
004C3141 | E8 0EFFF3FF              | call rpg_rt.403054                      |
004C3146 | 8BE8                     | mov ebp,eax                             |
004C3148 | 83C5 10                  | add ebp,10                              |
004C314B | C744FE 68 50000000       | mov dword ptr ds:[esi+edi*8+68],50      | Set t=80
004C3153 | 896C24 10                | mov dword ptr ss:[esp+10],ebp           |
004C3157 | DB4424 10                | fild st(0),dword ptr ss:[esp+10]        |
004C315B | DC0C24                   | fmul st(0),qword ptr ss:[esp]           |
004C315E | D80D 30324C00            | fmul st(0),dword ptr ds:[4C3230]        |
004C3164 | E8 07FAF3FF              | call rpg_rt.402B70                      |
004C3169 | 05 A0000000              | add eax,A0                              |
004C316E | 8944FE 6C                | mov dword ptr ds:[esi+edi*8+6C],eax     | Set x
004C3172 | 896C24 10                | mov dword ptr ss:[esp+10],ebp           |
004C3176 | DB4424 10                | fild st(0),dword ptr ss:[esp+10]        |
004C317A | DC4C24 08                | fmul st(0),qword ptr ss:[esp+8]         |
004C317E | E8 EDF9F3FF              | call rpg_rt.402B70                      |
004C3183 | 8944FE 70                | mov dword ptr ds:[esi+edi*8+70],eax     | Set y
004C3187 | C744FE 74 B4000000       | mov dword ptr ds:[esi+edi*8+74],B4      | Set alpha=180
004C318F | 33C0                     | xor eax,eax                             |
004C3191 | 8944FE 78                | mov dword ptr ds:[esi+edi*8+78],eax     | Set vx = 0
004C3195 | 8944FE 7C                | mov dword ptr ds:[esi+edi*8+7C],eax     | Set vx = 0
004C3199 | 33C0                     | xor eax,eax                             |
004C319B | 8984FE 80000000          | mov dword ptr ds:[esi+edi*8+80],eax     | Set vy = 0
004C31A2 | 8984FE 84000000          | mov dword ptr ds:[esi+edi*8+84],eax     | Set vy = 0
004C31A9 | DD0424                   | fld st(0),qword ptr ss:[esp]            |
004C31AC | D80D 30324C00            | fmul st(0),dword ptr ds:[4C3230]        |
004C31B2 | DD9CFE 88000000          | fstp qword ptr ds:[esi+edi*8+88],st(0)  | Set ax
004C31B9 | 9B                       | fwait                                   |
004C31BA | DD4424 08                | fld st(0),qword ptr ss:[esp+8]          |
004C31BE | D80D 30324C00            | fmul st(0),dword ptr ds:[4C3230]        |
004C31C4 | DD9CFE 90000000          | fstp qword ptr ds:[esi+edi*8+90],st(0)  | Set ay
004C31CB | 9B                       | fwait                                   |

**Comment by fmatthew5876** [comment]
Here is the algo in python, with plots

```
import random
import math



def part():
    eps = 1.0 / 128.0
    # FIXME: Handle inc 1 case
    r1 = random.uniform(eps, math.pi)
    c = math.cos(r1)
    r2 = random.uniform(eps, math.pi)
    s = math.sin(r2)
    d = random.randrange(16, 96)

    x = d * c * 2 + 160
    y = d * s

    ax = c * 2
    ay = s * 2
    return (x, y, ax, ay)

particles = [ part() for _ in range(0, 1000)]

x = [ p[0] for p in particles ]
y = [ p[1] for p in particles ]
ax = [ p[2] for p in particles ]
ay = [ p[3] for p in particles ]

plt.scatter(x,y)
plt.grid()
plt.show()

plt.scatter(ax, ay)
plt.grid()
plt.show()

plt.scatter(x,ax)
plt.grid()
plt.show()

plt.scatter(y, ay)
plt.grid()
plt.show()
```

![sand1](https://user-images.githubusercontent.com/1198466/78843100-dbbcdc00-79cf-11ea-95ce-75f44d3f8178.png)

![sand2](https://user-images.githubusercontent.com/1198466/78843108-e0819000-79cf-11ea-8a9a-d60927565724.png)

**Comment by CherryDT** [comment]
This is genuinely impressive.
