### ISSUE TITLE
Player crashes when exit

### ISSUE THREAD

**Issue by elsemieni** [EasyRPG/Player#2073]
#### Player platform: 
Tested on windows (at least)

#### Attach files (as a .zip archive or link them)

[coredump - Player_2020-03-03-16-39-23.zip](https://github.com/EasyRPG/Player/files/4283274/Player_2020-03-03-16-39-23.zip)

Tested with https://ci.easyrpg.org/view/Windows/job/player-win32/1083/ 

#### Describe the issue in detail and how to reproduce it:
Run player and close it. 
Seems like it's closing normally (does not hang before closing windows or anything). However, it leaves a coredump on folder, meaning it's crashing. 

Taking a look a bit at the coredump seems the problem is in https://github.com/EasyRPG/Player/blob/master/src/drawable_list.cpp#L64 , where evaluating this resulting as null (I can be wrong, maybe I got wrong sources, please check). 

A bit of screenshots of stack-trace for "link-saving" purposes. 
![image](https://user-images.githubusercontent.com/1494687/75813788-5bbbaa80-5d6f-11ea-9fea-abc469f9f1a7.png)
![image](https://user-images.githubusercontent.com/1494687/75813846-79890f80-5d6f-11ea-806b-70e30428c702.png)

**Comment by Ghabry** [comment]
This ``assert(local != nullptr);`` is triggered in Debug build.

There are other debug assertion problems in the Windows build btw:

text.cpp ``const auto end = &*text.end();`` <- This dereferences "end", not liked by MSVC

player.cpp
```cpp
escape_symbol = ReaderUtil::Recode("\\", enc);
escape_char = Utils::DecodeUTF32(Player::escape_symbol).front(); <-- This line
if (escape_symbol.empty()) {
  // Bad encoding
  Output::Debug("Bad encoding: %s. Trying next.", enc.c_str());
  continue;
}
<-- Must be moved after the if (the front() triggers an assert on empty strings)
```

**Comment by carstene1ns** [comment]
The `end()` dereferences are fixed in #2026.

**Comment by elsemieni** [comment]
I tested Jenkins build of #2026 (https://ci.easyrpg.org/job/player-win32-pr/4023/) . Gives me an assertion error at exiting (assuming jenkins PR builds are debug ones).

`Assertion failed: local != nullptr, file C:\Jenkins\workspace\player-win32-pr\src\drawable_mgr.h, line 42`

I don't know if it's correct behaivour or not, but anyways I leave it here if it's useful or not...

**Comment by carstene1ns** [comment]
@elsemieni it is the exact same assertion as above.

**Comment by fmatthew5876** [comment]
@elsemieni What is the exact set of steps used to start and "close" Player that reproduces this issue?

On linux I've tried exiting from the title screen menu and closing the window. The app exits cleanly in a debug build.

**Comment by elsemieni** [comment]
@fmatthew5876 The steps are:

- Start Player.
- Close in any way (by exit the game with exit command, or exit menu option, or closing the window/alt-f4).

Then, player "seems" to close normally, but a dump file appears in release, and an assertion failed occurs in debug. 

It's important to mention I just tested Windows (MSVC) builds. If you said in linux there's no crashes/assertion failures maybe is a more platform/compiler specific issue. Do you have a VM to test that build on Windows to check?

**Comment by fmatthew5876** [comment]
The location of the crash really doesn't point to a platform specific thing (although it could be). I do have windows machines I could test this on later.

My suspicion is static initialization order, which could be different on any compiler. Let me know if my PR fixes it for you.

**Comment by Ghabry** [comment]
Asan has a static init order checker. I wonder if it catches this
``ASAN_OPTIONS=check_initialization_order=true``
