### ISSUE TITLE
Marland [RPG2k]: Custom menu causes endless loop after save, possible race condition

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#2080]
#### Name of the game: Marland
Download: https://rmarchiv.tk/games/992

#### Describe the issue in detail and how to reproduce it:
> The game has a text box menue that is called via ESC in place of the standard menue.
> At the beginning of the game there is only a single option that you can select that then opens the standard menue.
> There you make a normal save via the option. Then you restart the game loading the newly made save game.
> In the RPG-RT the game restarts without any textbox and menue on the map. You can move your hero correctly.
> In the easyRPG version you start again with the text box menue over the map.
> When you try the cancel button the menue doesnt disappear but reappears again and cannot be quit,
> even when you enter the Standardmenue over the only available option in the menue.
>
> The bug did not occur in earlier versions of easyRPG. I only noticed the bug when I upgraded to the newer versions and loaded the newest save game up.
> So I think a version from maybe between Sepember to Dezember should not have this particular bug.

Bug reported over IRC.

Additional Info:
```
Map: 1
CE: 6, 7
Var: 29
Switch: 17
```

**Comment by fmatthew5876** [comment]
There is another issue. Start a new game and go through the initial dialogues.

As soon as you gain control of the main character, hit F9 and save. The game gets somehow stuck on the save men screen.

**Comment by fmatthew5876** [comment]
This is a major save game bug in liblcf fixed by https://github.com/EasyRPG/liblcf/pull/359

As for the debug menu issue, I am still investigating.

**Comment by carstene1ns** [comment]
👍
