### ISSUE TITLE
Missing RTP files

### ISSUE THREAD

**Issue by Kupo91** [EasyRPG/Player#2085]
#### Attach files (as a .zip archive or link them)
![Mc4HWE7N8wtihRH-cD3UFrbPy](https://user-images.githubusercontent.com/41426906/77911922-eff72f80-7291-11ea-9fdf-26dc0a75236d.png)
Downloadlink for the game: https://downloads.brianum.de/vampiresdawn/ds_original.zip

#### Describe the issue in detail and how to reproduce it:
Sorry in advance if I misunderstood this topic. I didn't have this issue with other games.
I just have read that EasyRPG uses its own RTP which is incomplete according to your website https://wiki.easyrpg.org/user/player/rtp
I followed the instructions and the game **works** with RTP2000.
I just thought you could add these files to your own RTP if you are allowed to

**Comment by Ghabry** [comment]
You mean the game works after you installed RTP 2000 normally? Then this is not a bug.

No we aren't allowed to distribute the RTP 2000 together with our RTP. This would be really useful if we could do it - Every user could skip a configuration step - but we are not allowed to do this.

**Comment by Kupo91** [comment]
Okay thank you. Then this can be closed

**Comment by Kupo91** [comment]
@Ghabry Ich muss doch nochmal nachfragen ^^
Ich hab dann das RTP2000, welches in eurem Wiki verlinkt ist installiert und dann ging es auch.
Aber nach 5 Minuten war ich an einer Stelle, wo doch wieder was gefehlt hat, trotz RTP:
![screenshot_0](https://user-images.githubusercontent.com/41426906/78175181-bd4c6300-745a-11ea-9402-0d1a33adfe25.png)
Gibt es noch andere RTPs, die man dafür installieren muss?

**Comment by Ghabry** [comment]
That's Don Miguel's RTP add-on. Unfortunately some games use this :(

**Comment by Ghabry** [comment]
More helpful answer: You can get the RTP at http://rpg2000.4players.de/index.php?inhalt=rpgmaker

I was just told that Don Miguels RTP translation (thats basicly the RTP most western games used before the official release, so VD and UiD use it) already contains the additional files you want ("Runtimepackage 1.0").
But some games also want "RTP Add-on V. 1.3".

So can just install it side-by-side with the official RTP. EasyRPG will detect both.

**Comment by Kupo91** [comment]
Thank you :) I googled him in the meantime and now I know the story behind his name. One of the first matches was a thread in your forum https://community.easyrpg.org/t/what-to-do-with-don-miguel-rtp-extras/44/12
Not sure if I understand it right - does this addon replace some original files?
Or do I really have two seperate RTPs if I install the official one and his addon?
How does EasyRPG know which one it needs for a game?

**Comment by Ghabry** [comment]
> How does EasyRPG know which one it needs for a game?

"Magic". Since Player 0.6.1 we scan all RTP folders and detect the type (you can see this in easyrpg_log.txt) and to get the game RTP, this is some heuristic.

All RTPs we know are stored in a huge table: https://github.com/EasyRPG/Player/tree/master/resources/rtp_table

Heuristic to get Game RTP. When the game wants to load a file:
1. Is the file in the game directory? No RTP logic.
2. If missing and a known RTP file:
- Scan our table and determine all RTPs that have that file, remember the RTP candidates
- When another RTP file is requested: Repeat the step until the RTP candidate list has only one RTP left, this is the game RTP (this usually happens after 1-3 files)
3. If missing and not a RTP file: Try to load the file from all RTP locations

And because we know the game RTP and the installed RTPs we can do A-to-B mappings between them. So when you have a Japanese game it will still work with Dons RTP, because we translate the filenames.

**Comment by Kupo91** [comment]
Great explanation, thanks a lot :)

**Comment by ZoruaLoL** [comment]
Hey I'm trying to run Gu-L on EasyRPG and have this exact problem, but I'm running it through RetroArch, how to fix?

**Comment by Ghabry** [comment]
Is this a general question about the RTP? The files must be in the libretro "code assets directory" or in the libretro "systems directory" in subdir rtp/2000 and rtp/2003.

**Comment by ZoruaLoL** [comment]
I have already placed the RTP files on the "systems" directory and it hasn't worked
![Screenshot 2024-09-24 112027](https://github.com/user-attachments/assets/893e3be9-cf0f-4dc2-a70e-9f9b4fbb714b)
![RPG_RT-240924-112312](https://github.com/user-attachments/assets/73716968-053b-473e-9f92-3d1398b14990)
![RPG_RT-240924-112320](https://github.com/user-attachments/assets/d886be74-2d5c-4891-aa68-2ce485cb4b69)
![RPG_RT-240924-112509](https://github.com/user-attachments/assets/f2e0f4d1-fc9b-40d3-9985-55bd3a9ddcda)


I have also tried to follow the [instructions on the PCGamingWiki](https://www.pcgamingwiki.com/wiki/Gu-L#Run_the_game_on_a_modern_non-japanese_PC) with the standalone Player and hasn't worked either, don't even think it's a locale issue.
