### ISSUE TITLE
The "Show FPS" Key (F2) doesn't work properly when there is lag

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2094]
Use a CPU intensive game like Frozen Triggers, then slowdown your CPU, e.g. with "sudo cpupower frequency-set -u 1G" (Reset with "cpupower frequency-set -u 5G". (5Ghz or the max val your CPU supports))

When it lags press F2, many times the FPS counter will not toggle.

**Comment by fmatthew5876** [comment]
Is it only FPS counter? Do other inputs also behave erratically?

I suspect (but not confirmed) it's this:
https://github.com/EasyRPG/Player/blob/master/src/player.cpp#L237

We only call `Player::UpdateInput()` once per frame, and when the game is slow we run lots of logical frames within a physical frame (up to 200ms). So perhaps your key press goes down and back up between calls to UpdateInput?

Needs more investigation.

**Comment by Ghabry** [comment]
> So perhaps your key press goes down and back up between calls to UpdateInput

Yeah this is exactly what happened. I moved the Event processing now into the Update function. This fixes the issue because events like key-down/key-up is now processed immediately.
