### ISSUE TITLE
Switch to using fmtlib for our logging

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2098]
We should change our `Output` logger to use fmtlib instead of legacy C style print()

https://github.com/fmtlib/fmt

fmtlib is coming in newer C++ standard library. Benefits for us are:

* More type safety in logging
* More flexibility in being able to log objects directly, including non null terminated strings
* In some cases fmtlib is even faster than printf

**Comment by Ghabry** [comment]
I also came to the conclusion a while ago that fmtlib would be one of the useful libraries for Player.

The problem is that this will be a required dependency - Must be added to the buildscripts:
https://github.com/EasyRPG/buildscripts/

**Comment by Ghabry** [comment]
fmtlib does also support positional arguments, useful for translations when we start to support this :)
