### ISSUE TITLE
Android: SDL2 update broke the rotation lock again

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2101]
We already got multiple bug reports that "Enforce Landscape" doesn't work anymore.

Can confirm this.

I hate Android. So many hours burned because the OS is crap.

**Comment by Ghabry** [comment]
Probably caused by "Fixed bug 4246 - Android: orientation between portrait<->landscape do" (?????)

https://github.com/spurious/SDL-mirror/commit/8cf14d63736964c2f2c7d8c8a17b045d49d9db78

**Comment by carstene1ns** [comment]
Looks like our "hint" is overwritten by SDL somewhere:
https://github.com/EasyRPG/Player/blob/master/builds/android/app/src/main/java/org/easyrpg/player/player/EasyRpgPlayerActivity.java#L116
Might be needed to use SDL instead or just patch it out.
