### ISSUE TITLE
すでに私たちは地獄のまっただ中でした: Battle: dummy enemies can attack in battle

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2102]
Via mail bug report.
Needs investigation. Sounds like a battle system (2000) bug.

#### Name of the game: すでに私たちは地獄のまっただ中でした

http://vipkohaku2011.web.fc2.com/entry/065.html

#### Attach files (as a .zip archive or link them)
[Save08.zip](https://github.com/EasyRPG/Player/files/4431292/Save08.zip)

The last played battles are 39 and 41.

#### Describe the issue in detail and how to reproduce it:
"Please fix the problem that dummy enemies (such as friends before they are called) can attack in battle."

**Comment by fmatthew5876** [comment]
Battles 39 and 41 have a yellow cat enemy 10 with actions:
* Normal Attack - 50
* Skill 57 - 100

The other 2 enemies that can show up are 8 and 9 cats, which all have rating 50 actions

**Comment by fmatthew5876** [comment]
I don't understand this one. Everything seem to be working. The yellow cat always uses his 100 rating skill. Is it some other battle?

**Comment by Ghabry** [comment]
More details: The problem is Battle 48. The Bird uses on first turn a skill that "Calls his friends".

Unfortunately I don't have RPG Maker set up on this PC yet and RPG_RT.exe also fails to run so I can't really tell you what is going on.

Educated guess: A "Target all enemies" skill hits invisible/escaped enemies.

**Comment by fmatthew5876** [comment]
> More details: The problem is Battle 48. The Bird uses on first turn a skill that "Calls his friends".
> 
> Unfortunately I don't have RPG Maker set up on this PC yet and RPG_RT.exe also fails to run so I can't really tell you what is going on.

The bird is enemy 48, he uses skill 66 which enabled switch 14, which enables a battle event that summons the other birds.

> Educated guess: A "Target all enemies" skill hits invisible/escaped enemies.

I suspect this is it. The hidden birds don't take any actions on the first round.
