### ISSUE TITLE
Change of System when loading the game

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#2111]
In the game we use 2 types of Systems:

- Blue is only for the main menu
- Brown for the rest of the game

This is so as not to break the synergy of each interface.

From the editor, we have configure the blue System as default, but once the player is in the introduction, we change to the brown System.

Here you can see for a moment how the type of System changes when loading the game:

https://youtu.be/zVx0KGCMsco?t=27

Thanks in advance.

**Comment by fmatthew5876** [comment]
This happens because the regular scene transition out occurs after loading the save game and replacing the currently active system graphic.
