### ISSUE TITLE
Refactor battler battle state

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2122]
Right now it's very difficult to understand for actors battle state vs non-battle state.

Collect all the battle state into a single `struct BattleState battle`. Then all accesses to this state start with `this->battle.foo`, and resetting the state is a single line `this->battle = {};` Refactoring this will help us ensure our battle state properly handled.

- [ ] Stat modifiers
- [ ] Attribute shifts
- [ ] Defend
- [ ] Charged
- [ ] Hidden?
- [ ] Turn number
- [ ] Last battle action?
- [ ] battle combo data?
- [ ] battle algo
- [ ] others?

**Comment by Ghabry** [comment]
Is this resolved by #2399 @fmatthew5876 ?
