### ISSUE TITLE
Saint Seiya Densetsu: Key Input not working in the "Improve" menu

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2140]
#### Name of the game:
Saint Seiya Densetsu

https://www.facebook.com/ssdensetsu

https://drive.google.com/file/d/1dfmpUiosqSALQm38dM7VWzkO8wa4XDK2/view

#### Attach files (as a .zip archive or link them)

[Save15.zip](https://github.com/EasyRPG/Player/files/4463698/Save15.zip)

#### Describe the issue in detail and how to reproduce it:

"Improve setting, in this NPC, don't work d-pad to select character, in PC this works well."

Reported via E-Mail

**Comment by fdelapena** [comment]
Can confirm. How to reproduce:

- After loading from the savegame, talk with the only static NPC.
- In the selection message box, select "> IMPROVE", then a grid selector will appear plus another message box.
- Select ">> ATK" or ">> DEF" (in ">> Other"). A cursor graphic will appear.

In RPG_RT it moves with arrow keys, but it does not in Player master.

**Comment by Ghabry** [comment]
Thats another obscure edge case with the key input Parameter length. But this is so strange that I need to do many more tests to figure out what is happening here.
There seems to be a 4th parameter length case that so obscure that it is even incorrectly displayed in the 2k3 editor.

**Comment by Ghabry** [comment]
Here some testing. 2k3 has the same behaviour for all versions. 2k gained new stuff with "Value!".

The D means that the "Direction flag" (Arg 2) is 1.

|  Bytes | 2kDon | 2kE              |                           2k3 |                 Param  |
|--------|-------|------------------|-------------------------------|------------------------|
|   5D   |  Dir  | Dir              | Dir                           |   42 1 1 1 0    |
|   5    |       |                  |                               |       |
|   6D   |  Dir  | Shift            | Dir,Num                       |    42 1 1 1 0 1   |
|   6    |       | Shift            | Num                           |       |
|   7D   |  Dir  | Shift,Down       | Dir,Num                       |   42 1 1 1 0 1 1 |
|   7    |       | Shift,Down       | Num                           |                           |
|   8D   |  Dir  | Shift,Down       | Dir,Num,Ops                   |   42 1 1 1 0 1 1 0    |
|   8    |       | Shift,Down       | Num,Ops                       |       |
|   9D   |  Dir  | Shift,Down       | Dir,Num,Ops                   |   42 1 1 1 0 1 1 0 0    |
|   9    |       | Shift,Down       | Num,Ops                       |       |
|   10D  |  Dir  | Down,Up,Shift    | Down,Up,Shift                 |   42 1 1 1 0 1 1 0 0 1    |
|   10   |       | Down,Up,Shift    | Down,Up,Shift                 |            |
|   11D  |  Dir  | Down,Up,Shift    | Down,Shift,Num,Ops            |   42 1 1 1 0 1 1 0 0 1 1    |
|   11   |       | Down,Up,Shift    | Down,Shift,Num,Ops            |       |
|   12D  |  Dir  | Down,Up,Shift    | Left,Down,Shift,Num,Ops       |  42 1 1 1 0 1 1 0 0 1 1 1     |
|   12   |       | Down,Up,Shift    | Left,Down,Shift,Num,Ops       |       |
|   13D  |  Dir  | Down,Up,Shift    | Left,Down,Right,Shift,Num,Ops |   42 1 1 1 0 1 1 0 0 1 1 1 1    |

**Comment by Ghabry** [comment]
The actually bug is not documented yet:
This game used a RPG2k3 <1.05 KeyInput (parameter list shorter than 10) and Player processed this like a 2k Value! command.
