### ISSUE TITLE
Unterwegs in Düsterburg: Choices displayed incorrectly

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2144]
#### Name of the game:
Unterwegs in Düsterburg

https://rmarchiv.tk/games/68

#### Describe the issue in detail and how to reproduce it:
Start the game. The first message box is already inproperly aligned.

**Comment by fmatthew5876** [comment]
This is fixed by #2026

**Comment by Ghabry** [comment]
Is it somehow possible to isolate the fix?

There is nothing special here, is just a 
```
@> Text:                Bewegungsgeschwindigkeit
 :         : 
@> Show Choices:                      Normal/                     Schnell
 : When [                     Normal]
  @> Set Move Route: Player, Speed Down
  @>
 : When [                     Schnell]
  @> Control Switches: [1407:GRANDY SCHNELL] = ON
  @>
 : Branch End
```
in a Parallel Process

**Comment by Ghabry** [comment]
This is a problem with empty line handling. They are completely skipped.

**Comment by Ghabry** [comment]
In the massive refactor you changed one check from "text.empty" to "line.empty" in the append code. This fixes it.

https://github.com/EasyRPG/Player/pull/2026/commits/eacb1ccecc12b2c8eaa8d02e29e65fafc5d5c59c#diff-1f67ea2ce884da948203c8b2ce8bb7d4R149

**Comment by Ghabry** [comment]
https://github.com/EasyRPG/Player/commit/eacb1ccecc12b2c8eaa8d02e29e65fafc5d5c59c#diff-1f67ea2ce884da948203c8b2ce8bb7d4R148-R152

![Screenshot_20200412_170149-fs8](https://user-images.githubusercontent.com/1331889/79072078-5858fe80-7cdf-11ea-8a4b-a33555b3af9c.png)
