### ISSUE TITLE
Battle 2k3: Misc issues

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2147]
- [x] Enemies update before actors

Start a battle with 1 actor and 1 enemy, both with the same AGI values. Then do an autobattle.

The enemies will attack first. This indicates that RPG_RT processes enemy actions before actors.

- [x] Actors don't animate run away when escape is performed

```
if (escapeAllowed )
  if (battler.mirrored )
      battler.x -= 6;
    else
      battler.x += 6;
  }
}
```

Looks like if you use a "Force Flee" event on the party on a battle where escape is not allowed, they may not run

- [x] Actors with a state restriction but full atb gauge (first strike etc..) are still able to take their turn.
    - [x] Test with recoverable and non-recoverable states

**Comment by Ghabry** [comment]
The CheckAllowEscape you have there looks like that useless "Escape" option in the command menu where you can select Fight and Auto Battle.
In 2k3 this escape option is usually disabled and you have to use the Escape from the actor command list.

It is only enabled when it is the first turn, you have first Strike or battle mode preemptive or sourround.

**Comment by fmatthew5876** [comment]
Making a separate post for escape

- [ ] When battle starts

```
  v2->fleeChance = 0;
```

- [ ] Rules for allowing escape at the option window

```
bool __usercall CheckAllowEscape@<al>(RPG_BattleData *a1@<eax>)
{
  return a1->escapeAllowed
      && !(*RPG::inventory)->numTurns
      && (a1->firstStrike || a1->encounterCondition == 1 || a1->encounterCondition == 3);
}
```

- [ ] Initial flee chance setting

```
  v23 = GetSumMonsterAgi();
  v22 = (double)v23 / (double)GetSumActorAgi((int)*RPG::inventory);
  v15 = intFromDouble(100.0 * v22);
  v16 = maxL(150 - v15, 100i64);
  v9->fleeChance = max64(v16, 0i64);
```


- [ ]  What happens when you escape from option window

`fleeChance` not checked, escape automatically succeeds

- [ ] Success check on actor escape command

```
  if ( RPG_RandExclusive(0x64u) < a1->fleeChance || v1->firstStrike )
```

- [ ] What happens if you fail

```
v1->fleeChance += 10;
```

- [ ] When battle ends

```
  v2->fleeChance = 0;
```
