### ISSUE TITLE
Still Mate: Hang when going for a Sail

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2155]
#### Name of the game:
Still Mate
https://www.freem.ne.jp/win/game/6673

#### Attach files (as a .zip archive or link them)
[StillMate_Save.zip](https://github.com/EasyRPG/Player/files/4478184/StillMate_Save.zip)

#### Describe the issue in detail and how to reproduce it:
Load the save, enter the port building (left of you).
Talk to the dude blocking the door.
You get a "Event 0 exceeded execution limit" hang. (in 0.6.1 it is Event 15 instead of 0)

**Comment by Ghabry** [comment]
The game hangs in
```
  @> Control Variables: [0781..0784] = Random No. (786...802)
  @> Conditional Branch: Variable [0781:一時変数] == Variable [0782:一時変数]
    @> Jump to Label: 44
    @>
```
By looking at this there is only one conclusion: There is a _new random number drawn for each variable in the range_.

So implementation wise the Control Variable event command likely executes the expression for obtaining the variable value once per loop. We just never noticed this because it remains constant for everything except the random number >.>
(also this sounds really slow to do)

**Comment by Ghabry** [comment]
Proof that this is refetched per loop in general:
```
@> Control Variables: [0004] = 10 
@> Control Variables: [0002] = 4 
@> Control Variables: [0010] = 42 
@> Control Variables: [0001..0005] = Variable ID [V[0002]]
```
So the initial value is "10" (because Var 2 points to 4), then the 10 is written in all variables and after a while Var 2 points to 10 which contains 42.

Result:
```
V1: 10
V2: 10
V3: 42
V4: 42
V5: 42
```

**Comment by fmatthew5876** [comment]
This is a great catch and one that could have gone not known forever.

For a user perspective it makes sense. If I ask for a range of random numbers it's not likely I'd want them all to be the same.

Probably we also have to fix this for the math operations too.

**Comment by Ghabry** [comment]
Because the other problematic range operation (src variable overlapping with destination range) was not fixed by the PR I will create another issue for this??

**Comment by fmatthew5876** [comment]
Oh I see, I misunderstood that part of it. 

I haven't checked, but RPG_RT must be doing this in a simple loop. I can prepare a fix for indirect variable lookups too. Either in the same PR or if it gets merged, a new one.

**Comment by Ghabry** [comment]
Not tested but I guess this will also break for direct variable access when the operation is not "set" but "add" etc. and the src is part of the range.

**Comment by fmatthew5876** [comment]
Here's another test case
```
Vars[1..4] = 1
Vars[1..4] += Var[2]
```

Result is "2 2 3 3"

So we need to re-evaluate it on the direct variable lookup too.
