### ISSUE TITLE
進めアレックス: Strange treasure chest appearing after defeating enemy

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2156]
#### Name of the game:
進めアレックス
https://w.atwiki.jp/vip_rpg/pages/133.html (click ダウンロード)

#### Attach files (as a .zip archive or link them)
[進めアレックスSave.zip](https://github.com/EasyRPG/Player/files/4478193/Save.zip)

#### Describe the issue in detail and how to reproduce it:
Load the save, fight the slime by smashing enter.
A treasure appears. It seems the treasure is a vehicle?
Expected: No treasure appears.

**Comment by Ghabry** [comment]
That must be a minor difference in how savegames are handled:
When I load the attached save in RPG2k3 the Treasure behaves as in Player.
When I save again with RPG2k3 and load this in RPG2k the same bug happens there.

**Comment by Ghabry** [comment]
I have no idea.
```
@> Control Variables: [0030] = This Event's X Coordinate
@> Control Variables: [0031] = This Event's Y Coordinate
@> Control Variables: [0032] = This Event's Map ID
@> Set Vehicle Location: Boat, Variable [0032][0030][0031]
```
When you run this in RPG2k the boat will not appear, in RPG2k3 it will.
When you save in RPG2k3 before executing this event and loading it in RPG2k the boat will appear.

**Comment by Ghabry** [comment]
RPG2k bug?
Asking for the Map ID of the event always returns 0 o.O

**Comment by CherryDT** [comment]
No... interesting.

**Comment by fmatthew5876** [comment]
We have a hack in our code which sets the event id to 0 when we save and replaces the 0 with the real map id when we load. I added this for RPG_RT compatibility.

I guess since events instantiated only for the current map RPG_RT decided never to populate the field?

**Comment by Ghabry** [comment]
2k decided this. 2k3 fixed it. (first time 2k3 is better :P)

**Comment by fmatthew5876** [comment]
> And 2k3 saves the map ID properly in the Save game. Guess your tests were 2k only?

I don't remember, but probably they were for this case.

This behavior is probably worth checking in older 2k3 versions also.

**Comment by fmatthew5876** [comment]
Actually it looks like I did handle this properly, but only for save games. I didn't know this affected other things.

https://github.com/EasyRPG/Player/blob/master/src/scene_save.cpp#L130
https://github.com/EasyRPG/Player/blob/master/src/game_event.cpp#L54

**Comment by Ghabry** [comment]
Tested in RPG2k3 1.0.3: Has the MapID bugfix already.
