### ISSUE TITLE
Android: My ActionRPG closes itself when I do a specific ability

### ISSUE THREAD

**Issue by IzzyGOsorio** [EasyRPG/Player#2162]
Name of the game: **Death Default - Action RPG Teaser RPG Maker 2003**

Player platform: **Android**

https://mega.nz/file/2qgnjJIY#YH6unWEBHEZCrRTUc9j38J3_nbnAnYpbdoi7HSQLTzM 29mb .rar file with the early version.

Hey there!, I downloaded EasyRPGPlayer for Android from PlayStore and I tested my game, however it closes itself when I do "DASH" ability (key 1 from keyboard) It is a Common Event in Parallel Process(you can find it as **0008:Dash** in the **Database**). I posted a teaser version that you can use for testing.

Thanks :)

**Comment by Ghabry** [comment]
Hello. Thanks for the report. I guess this is the sound effect crash which is already fixed but Google needs longer to review updates because of Corona. :/
Fortunately the update was just accepted, either wait until you receive it or update manually from the store and retest. Thanks :)

**Comment by Ghabry** [comment]
@IzzyGOsorio the mega archive is encrypted and needs a password

**Comment by IzzyGOsorio** [comment]
Sorry, I updated the link with the password :)

**Comment by Ghabry** [comment]
Thanks. This is already fixed. Please update to the latest version of the app.
