### ISSUE TITLE
Battle 2k: When an actor dies and is revived during the same turn the battle action is still executed

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2169]
Found this while finding ways to crash:

Create a page that does
```
Condition Sw1 on
Alex: State Dead +
Alex: State Dead -
```

Let Brian (must have higher AGI than Alex) invoke a Skill that enables Switch 1.

Expected:
- Only Brians Switch skill is activated
- [Turn End]

Player:
- Brian activates switch skill
- Alex will do it's action as if he never died
- [Turn End]

**Comment by fmatthew5876** [comment]
We should also verify whether setting and curing provoke and confuse changes the battle actions.

**Comment by rueter37** [comment]
Did some tests with RPG_RT and can confirm that when an actor or enemy gets a state added which has at least one restriction (no matter if no move, attack enemy party or attack ally party) his action gets stopped even if the state gets removed in the same event.
