### ISSUE TITLE
Regression: Deep 8: Pictures in opening sequence have wrong position

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2171]
#### Name of the game:
Deep 8
https://rmarchiv.tk/games/200
Recommend "2014-05-01 [ Demo - 1 ]". Is the oldest version but has less DynRPG & co.

#### Describe the issue in detail and how to reproduce it:
Start the game, fast forward through the landing sequence. When you can take over control over yours chars you will see some trees. You can already see that they look strange while scrolling and when you move down you can see that they are not properly aligned.

Didn't happen in 0.6.1!

Map "Vorszenario -> wald 1"
Relevant event is 239 at (19, 14). The Picture position happens once through this Event through reading the screen coordinates.
The reported coordinates are the same in both Player and RPG_RT so the problem must be somewhere else

**Comment by fmatthew5876** [comment]
screenshot of the differences

![pics](https://user-images.githubusercontent.com/1198466/80114638-ca3c0e00-8551-11ea-9ad1-aaf867aaa2b3.png)

**Comment by fmatthew5876** [comment]
So the bug is with pan screen and scroll with map pictures.

```
ShowPicture: X, Y scroll with map
Pan Screen
```

In RPG_RT the picture will stay where it is as the screen moves. In Player, the picture moves with the screen.
