### ISSUE TITLE
Missing battle animation in OFF

### ISSUE THREAD

**Issue by KKha-11** [EasyRPG/Player#2174]
---
#### Player platform:
Windows, Android.

#### Describe the issue in detail and how to reproduce it: Missing battle animation of the Add-Ons(the round thingy), usually it will charge forward to attack but when I play OFF in easyrpg, it doesn't show up.
Also the batter battle animation ( charge forward when attack) doesn't show up either
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4537335/easyrpg_log.txt)

**Comment by KKha-11** [comment]
Also the batter battle animation ( charge forward when attack) doesn't show up either

**Comment by Ghabry** [comment]
Missing charge forward sounds like CBA: #1269

**Comment by KKha-11** [comment]
> Missing charge forward sounds like CBA: #1269

Yes it does

**Comment by KKha-11** [comment]
> Missing charge forward sounds like CBA: #1269

Except the CBA in OFF for all weapons is the same

**Comment by Ghabry** [comment]
The missing CBA in OFF is already reported in #1277 . Closing this one as duplicate
