### ISSUE TITLE
OFF Missing battle background transparent and player must attack in turn

### ISSUE THREAD

**Issue by KKha-11** [EasyRPG/Player#2175]
#### Player platform:
Windows, ...
 

#### Describe the issue in detail :

- [x]  1. Missing battle background transition. When fighting Japhet will change background from pink to red, but when using EasyRPG background turn from pink to black 

- [x]  2. Characters attack in turn, usually when 'all characters' turn is refilled' we can choose any character to atttack first, but in easyRPG when that come I have to choose the batter first then the add-ons to attack

- [x]  3.  Normal: Allies and enimies' turn will automatically refill overtime no matter what. But in easyrpg, their  turns only refill when all members in the team have done attacking.

![image](https://user-images.githubusercontent.com/63910516/80335729-641bf780-887f-11ea-9b1c-6466e08f3c17.png)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4537591/easyrpg_log.txt)

**Comment by fmatthew5876** [comment]
ATB Active mode has some quirks.

In wait mode, ATB will only accumulate when you're in the party window. Which means you're waiting for your actors to be able to do something.

In Active mode, ATB will accumulate in every battle scene state except for the initial "Fight/Auto/Escape" window.
However, battlers will only attack when you're in the party window or an actors command window.

This means that while in items, skills, targeting enemies, or targeting allies, atb will accumulate but no battler will act until you exit out of those states.

**Comment by Ghabry** [comment]
> Missing battle background transition. When fighting Japhet will change background from pink to red, but when using EasyRPG background turn from pink to black

This is already fixed since 0.6.2. Everything is resolved. Closing :+1:
