### ISSUE TITLE
Half picture loading/transparence [Android][Switch][Battle][Pictures]

### ISSUE THREAD

**Issue by zell180** [EasyRPG/Player#2178]
#### Name of the game: 
Saint Seiya -Il Mito-

#### Player platform: 
Android, Switch

#### Describe the issue in detail and how to reproduce it: 
like in the attached video seems that picture loading or transparence is not sync, like the screen is orizontally half divided.

[error.zip](https://github.com/EasyRPG/Player/files/4548331/error.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4548459/easyrpg_log.txt)
![half1](https://user-images.githubusercontent.com/6542956/80587079-3d43f980-8a16-11ea-9ee3-aa020b772742.jpeg)
![half2](https://user-images.githubusercontent.com/6542956/80587084-3fa65380-8a16-11ea-94ae-94e567eb39a4.jpeg)

**Comment by Ghabry** [comment]
Thanks for the bug report :)

Can you tell me where to download this game?

On http://crystal74.altervista.org/ I only find a NDS version.

**Comment by mgentile-bit** [comment]
Can you write me in private?

**Comment by zell180** [comment]
> Thanks for the bug report :)
> 
> Can you tell me where to download this game?
> 
> On http://crystal74.altervista.org/ I only find a NDS version.

i write you on irc because i need to talk in pm.

**Comment by Ghabry** [comment]
Sure. Please send your messages to Ghabrz and not Ghabry.
Or use Twitter or mail to easyrpg easyrpg org

**Comment by Ghabry** [comment]
Received the game.
This is a regression, worked in 0.6.1.

Looks like a regression in this totally useless top-bottom transparency features in RPG2k3...

**Comment by Ghabry** [comment]
This was caused by 1b6b7d9

The following edge case was lost:

```cpp
// Corner case when 2k maps are used in 2k3 (pre-1.10) and don't contain this chunk
params.bottom_trans = param_size > 14 ? com.parameters[14] : params.top_trans;
```
