### ISSUE TITLE
Unnecessary window title updates

### ISSUE THREAD

**Issue by BSzili** [EasyRPG/Player#2179]
Currently Graphics::UpdateTitle() is called even when the window title doesn't change, when the FPS counter is not visible. SDL2 is supposed to catch this case, but doesn't due to an oversight. SDL_SetWindowTitle compares pointers, but then strdup's the string, so it will always call the underlying system functions:
https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_video.c#L1875
This could lead to some micro-stuttering on slow platforms in windowed mode. The impact is probably negligible, but it would be nice if this could be avoided.

**Comment by carstene1ns** [comment]
This is a really old bug. We assumed SDL would correctly handle this.
Fortunately it is relative easy to fix.

**Comment by fmatthew5876** [comment]
Even better if you store one buffer and `snprintf()` into it each time. SDL will never update the title! :)

**Comment by carstene1ns** [comment]
All that is left is to fix this in SDL. ;)
