### ISSUE TITLE
Provide a way to enable "UnlockPicPatch"

### ISSUE THREAD

**Issue by zell180** [EasyRPG/Player#2182]
#### Name of the game: 
Saint Seiya -Il Mito-

#### Player platform:
Android

#### Attach files (as a .zip archive or link them)
[video_error_and_save.zip](https://github.com/EasyRPG/Player/files/4557776/video_error_and_save.zip)

#### Describe the issue in detail and how to reproduce it:
When appear text during battle all animations stop. In 2k3 player this not happens.

**Comment by Ghabry** [comment]
Are these animations "Battle Animation" or "Picture"?

**Comment by zell180** [comment]
Picture managed by parallel process

**Comment by Ghabry** [comment]
Did you patch the original RPG Maker 2003 with a "Unlock Pic Patch"?
Afaik RPG Maker before the "Official English Release" always froze pictures when messages appear.

**Comment by zell180** [comment]
Yes we have used this 
[unlockpics.zip](https://github.com/EasyRPG/Player/files/4558029/unlockpics.zip)

**Comment by Ghabry** [comment]
Okay then this can't be properly supported right now.

Unfortunately there is currently no way overwrite the engine for a specific game permanently through a config file. We are working on such a feature but is not ready yet.

Until we have such a feature you can tell EasyRPG Player to use "RPG Maker 2003 English" by creating an empty file called "ultimate_rt_eb.dll" in the game directory.
Note that this will break "Split transparency" for pictures completely (where top and bottom half can have different transparency) as this questionable feature was removed.
