### ISSUE TITLE
Charset: Wrong facing direction 

### ISSUE THREAD

**Issue by zell180** [EasyRPG/Player#2183]
#### Name of the game:
Saint Seiya -Il Mito-

#### Player platform:
Android

#### Attach files (as a .zip archive or link them)
![95170714_254785425646180_8719222479228239872_n](https://user-images.githubusercontent.com/6542956/80708183-8619b200-8aeb-11ea-9aa2-cb446c3759ec.jpg)

#### Describe the issue in detail and how to reproduce it:
In this screen charset Marin (the girl) should watch Seiya (the boy) in down direction but during this scene the charset rotates automatically itself on right.
To test this part of game 
Start Game -> Select "Medio" -> Skip Intro -> Select "La Rinascita" and you will be there after the first intro scene :D

**Comment by Ghabry** [comment]
Good news: This is NO regression ;)

**Comment by Ghabry** [comment]
Here a testcase to reproduce this.
There are some messages, after a while the chara will look to the right. Then looks right while moving down. In RPG_RT faces downwards while moving down.

[issue-2183.zip](https://github.com/EasyRPG/Player/files/4560250/issue-2183.zip)

https://easyrpg.org/play/master/?game=issue-2183

**Comment by fmatthew5876** [comment]
This one is rather simple. RPG_RT resets the "direction fixed" flag on page change and player doesn't.

Much simpler test case:

EV01 page 1 with custom move route
```
Direction Fix On
Move right
Sw1 on
```

page 2, activiated by SW01
```
Move up
```

The event should move right while facing down, then move up while facing up

**Comment by fmatthew5876** [comment]
Move Route Page Change Test cases

For each of these EV01 has 2 pages, page 1 and page 2 activiatedby SW01

1. custom routes
--------------------

Page 1 Trigger custom move route freq 8 `Move Right, SW1 on: repeat`
Page 1 Trigger custom move route freq 8 `Move Up: repeat`

Result: Right, Up, 

2. custom routes
--------------------------

Page 1 Trigger custom move route freq 7 `Move Right, SW1 on: repeat`
Page 1 Trigger custom move route freq 7 `Move Up: repeat`

Result: Right Up

3. event routes
-----------------

Page 1 *
```
Set MoveRoute: This Event, Repeat, Right, SW1 on
WaitForAllMovement
```

Page 2 *
```
SetMoveRoute: This Event, Repeat, Up
```

Results:

| Page 1 | Page 2 | Result |
| -- | -- | -- |
| Autostart | Autostart | Right, Right :question:, Up |
| Autostart | Parallel | Right, Up |
| Parallel | Autostart | Right, Up |
| Parallel | Parallel | Right, Up |

Result: Right, Right :question:, Up


Player fails test 1 and the auto,auto case for 3

**Comment by zell180** [comment]
Behaviour seems not correct yet.
I attach a video of right behaviour on rpg maker.
[rpgmaker example.zip](https://github.com/EasyRPG/Player/files/4571560/rpgmaker.example.zip)

**Comment by fmatthew5876** [comment]
This is still broken, but now only in save games. It might explain why we saw issues testing.

Create an event with animation type fixed direction, facing down and movement type horizontal.

Start a new game in player, the event will walk horizontally while facing down. Save your game.

Load your game in Player, the event will continue to walk horizontally and face down.
Load your game in RPG_RT, the event will walk horizontally and face left or right!

The reason is that in Player we have both `IsFacingLocked()` which checks the flag, and `IsDirectionFixed()` which checks the animation type.

RPG_RT only uses the facing locked flag. When an event is setup with animation type, it will set or clear this flags. In move route code, when you say "direction fix off" RPG_RT has an if checking whether your animation type allows you to turn it off.

**Comment by zell180** [comment]
I've tested again and on this message charset turn right. Then everything it's ok.

![Screenshot_20200504-194921_EasyRPG Player](https://user-images.githubusercontent.com/6542956/80996639-729a7e00-8e40-11ea-9489-b5f218f77ca6.jpg)

**Comment by fmatthew5876** [comment]
Here's another bug in RPG_RT 2k3 related to this. ❗ In particular, I tested this with dynrpg version.

Make an event on map 6
```
Var[1] = This Event MapId
ChangeEventLocation(x, y)
Var[2] = This Event MapId
Msg: "\v[0] \v[1]"
```

Result: "6 0"

This also occurs with "SwapEventLocations" command. Both of these commands hard code the map id to 0.

We'll need to emulate this bug for correctness.
