### ISSUE TITLE
Wii: Time measurement with Platform_Clock::now is constant

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2186]
#### Player platform:
Wii

#### Describe the issue in detail and how to reproduce it:

The sleep_for 1s works excellent but the clock is not incrementing:

![Screenshot_20200501_174207-fs8](https://user-images.githubusercontent.com/1331889/80818301-331b2a00-8bd3-11ea-8248-a18b6f52ae08.png)

**Comment by fmatthew5876** [comment]
What does the `Game_Clock` line in the log file look like?

**Comment by Ghabry** [comment]
StdSteady steady=1 period=ns (1 / 1000000000)

**Comment by Ghabry** [comment]
libstdc++ implementation is here: https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/src/c%2B%2B11/chrono.cc#L42

But no idea which one devkitXXX is configured to use. No idea where you configure this.

**Comment by fmatthew5876** [comment]
We can try changing it to use `std::system_clock` for newlib ports.

**Comment by Ghabry** [comment]
How do you do this? Sorry but I'm always lost when I look in std_clock.h. I just see template foo and hard to read chrono code.

**Comment by fmatthew5876** [comment]
https://github.com/EasyRPG/Player/blob/master/src/std_clock.h#L27

**Comment by Ghabry** [comment]
The broken function must be ``clock_gettime``. The value is stuck.
With ``std::time`` and ``gettimeofday`` I get proper values.

There is also a discussion here that the function is broken: https://github.com/dborth/sdl-wii/issues/50

SDL-Wii implementation: https://github.com/dborth/sdl-wii/blob/master/SDL/src/timer/wii/SDL_systimer.c

Maybe some useful constants in here?
https://github.com/devkitPro/libogc/blob/master/gc/ogc/lwp_watchdog.h

**Comment by fmatthew5876** [comment]
Is it broken because of wii? Or because it's newlib?
