### ISSUE TITLE
Bizarre crash while loading ExFont

### ISSUE THREAD

**Issue by NovemberJoy** [EasyRPG/Player#2191]
Name of the game: Captain Novolin RPG

Player platform:
x86-64 Kubuntu 19.10

Attach files (as a .zip archive or link them)
[Download for the game that's not publicly hosted anywhere](https://drive.google.com/open?id=1_0hS0zeV9QoAbik5LgERwGsPnFIAXB2N)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4569112/easyrpg_log.txt)

Describe the issue in detail and how to reproduce it:
All I did was download the latest debug build of the Player and try to start the game from the selection menu. It crashed while loading, with the last message being about the ExFont.

**Comment by Ghabry** [comment]
I just got the last Linux debug build.
Works for me.

**Comment by carstene1ns** [comment]
@NovemberJoy You can try the OBS build instead. 
https://software.opensuse.org/download/package.iframe?project=home%3Aeasyrpg&package=easyrpg-player

**Comment by NovemberJoy** [comment]
@carstene1ns The OBS build successfully started up, and I also got the debug build to start up afterwards. I still don't know what the issue was, but I can only assume it was an issue with my system and not with the Player itself. With that in mind, I'm just going to close this.
