### ISSUE TITLE
[Diablo Lab] Map event enemies don't kill the player character

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2194]
The game demo seems unreleased, download url is provided via email.

Load savegame provided by the game download (slot 04) and follow the path as in the picture:

![Map0022-Save04](https://user-images.githubusercontent.com/174885/80931184-47972800-8d75-11ea-9d5f-40f54bba8727.png)

In RPG_RT, it works as expected (the player character dies and shows game over).

In Player, enemies don't kill the player character.

Note: after crossing the first bridge, there's a spare enemy event, just ignore it (this one makes damage, though). Also skip all random battles while walking.

Unrelated to this issue: tried to create a savegame in Player closer to the place ([Save15.zip](https://github.com/EasyRPG/Player/files/4572506/Save15.zip)), but RPG_RT crashes on load.

**Comment by Ghabry** [comment]
@fdelapena 
Is this the game I already mentioned there: https://github.com/EasyRPG/Player/pull/2158#issuecomment-623160016 ?

**Comment by fdelapena** [comment]
> Is this the game I already mentioned there: (...) ?

Yes, it is.

**Comment by Ghabry** [comment]
Okay but I didn't test the map you show. Only did the tutorial battle (first zombie)

**Comment by fmatthew5876** [comment]
Which bug report email subject line has this one?

**Comment by Ghabry** [comment]
Following this map path just spawns 3 zombies - The same as in the tutorial. So they use the same "Simulate Attack" code which was fixed by the Variance fix.
