### ISSUE TITLE
Different animation behaviour

### ISSUE THREAD

**Issue by zell180** [EasyRPG/Player#2198]
#### Name of the game:
Saint Seiya -Il Mito-

#### Player platform:
Android

#### Attach files (as a .zip archive or link them)
[rotation_comparison.zip](https://github.com/EasyRPG/Player/files/4577257/rotation_comparison.zip)

#### Describe the issue in detail and how to reproduce it:
Comet animation seems not has the same behaviour in EasyRPG.
To test this part of game
Start Game -> Select "Medio" -> Skip Intro -> Select "La Rinascita" and you will be there after the first intro scene :D

**Comment by fmatthew5876** [comment]
This is us incorrectly emulating an edge case. When a rotation is canceled on a picture, it'll continue rotating until it completes a full revolution.

Somehow we do the math and/or timing wrong and it shows up here.
