### ISSUE TITLE
Yume2kki: Music not looping?

### ISSUE THREAD

**Issue by purupurupuruin** [EasyRPG/Player#2199]
#### Name of the game:
Yume2kki Version 0.112
https://yume2kki.fandom.com/wiki/Downloads

(Here's the direct link the wiki provides to version 0.112 just in case: https://drive.google.com/file/d/14ChZTtNLzQEn2uQiwNns8icJsw__4Dxs/view)

#### Player platform:
Linux

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4583087/easyrpg_log.txt)
[2kki Save](https://github.com/EasyRPG/Player/files/4583088/save.zip)

#### Describe the issue in detail and how to reproduce it:
While playing I noticed some songs end almost instantly and don't loop, the most obvious example I found was Circuit Board's theme.

To reproduce:
Go to the music room and play track 103.
Compare with the version that can be heard on the wiki.
https://vignette.wikia.nocookie.net/yume2kki/images/2/25/Yeris_Coulomb_on_Board.ogg

(Apologies if this doesn't turn out to be a bug with EasyRPG.)

EDIT: Just tested the song in RPG_RT using a virtual machine (Just couldn't get WINE to work right.) and it loops properly.

**Comment by Ghabry** [comment]
Can you tell us if the audio file is a MIDI?

If yes this is a duplicate of #834

**Comment by purupurupuruin** [comment]
Just loaded the game with a different soundfont enabled, and the song changed so I know for sure it's a MIDI file, closing.
