### ISSUE TITLE
Yume2kki: Wind Tunnel panorama looks different

### ISSUE THREAD

**Issue by purupurupuruin** [EasyRPG/Player#2203]
#### Name of the game:
Yume2kki (Version 0.112 Unpatched)

#### Player platform:
Linux

#### Attach files (as a .zip archive or link them)
[Wind Tunnel debug save](https://github.com/EasyRPG/Player/files/4601603/WindTunnelSave.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4601590/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
When in Wind Tunnel, the background panorama has squiggly lines instead of being mostly black, and there are black lines visible, since this isn't a foggy area I don't think it's #2200.

EasyRPG Player:
![WindTunnel EasyRPG](https://user-images.githubusercontent.com/64451846/81450383-2c426900-9137-11ea-857f-fd878af81cd4.png)
RPG_RT:
![WindTunnel RPG_RT](https://user-images.githubusercontent.com/64451846/81450366-2482c480-9137-11ea-9d85-1b9aaf72802b.png)

To reproduce:
Load the provided save.
Or head to Wind Tunnel the normal way:
https://yume2kki.fandom.com/wiki/Wind_Tunnel

(Terribly sorry if this turns out to be a duplicate of another bug or it's just Player rendering pictures differently than RPG_RT like in #1249.)

**Comment by fmatthew5876** [comment]
So when I compare the 2, I see the starting position of the cloud thing is different.

**Comment by purupurupuruin** [comment]
Could it be related to #2195 then?

**Comment by purupurupuruin** [comment]
So after checking out Wind Tunnel with a patched true color RPG_RT, I noticed it looks exactly the same to Player:
![windtunnel with 24 bit patch](https://user-images.githubusercontent.com/64451846/116974191-90c4d500-ac72-11eb-8462-d0e8513e544b.png)
So, I'm guessing it was just #1249.. sorry for the duplicate!

Not to mention, actually looking in the files, the background looks like this:
![wataru haikei](https://user-images.githubusercontent.com/64451846/116974152-81458c00-ac72-11eb-94c1-90901442ce60.png)

The "squiggly lines" are present.

(The panorama being in a different position is probably just the panorama moving normally, or #2195 causing it's starting position to change or something)

Thankfully this (probably) isn't a bug then, since Wind Tunnel is removed in newer versions of 2kki.. it's a lot harder to investigate bugs that can only be reproduced in specific older versions.

Panorama starting position discussion stuff should be moved over to #2195 or some other bug.
