### ISSUE TITLE
Switch version resource loading fail (Simplified Chinese, Garbled file name)

### ISSUE THREAD

**Issue by YuliaS11** [EasyRPG/Player#2205]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
Nobita's Resident Evil G2 (Simplified Chinese)
#### Player platform:
Switch Homebrew

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
Images cannot be loaded (contain garbled characters as the original game included Japanese characters which are then garbled to operate with CN locale). Same game works perfectly on Windows.

**Comment by Ghabry** [comment]
This is unfortunately a bug in Nintendos SD card driver: for some reason Nintendo decided to interpret filenames as Japanese characters so anything that is not a-z or 0-9 fails to load.

Maybe one of the firmware reimplementations (e.g. Atmosphere) will fix this someday.

We also plan to fix this by allowing to launch games from zip archives. But this will take more time to finish. Stay tuned for the update.

**Comment by Ghabry** [comment]
Closing this as this is unfortunately not fixable by us.

A workaround is to put the game inside a ZIP archive and launch this one as a game. This works as of today #2455
