### ISSUE TITLE
Yume2kki: Shogi Board debug save difference

### ISSUE THREAD

**Issue by purupurupuruin** [EasyRPG/Player#2207]
#### Name of the game:
Yume2kki (Version 0.112 without hotfix patches)

#### Player platform:
Linux

#### Attach files (as a .zip archive or link them)
[shogiboarddebugsavebug.zip](https://github.com/EasyRPG/Player/files/4606975/shogiboarddebugsavebug.zip) 
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4606977/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
Since I was told any incompatibility with debug saves is a bug I decided to report this.
In Shogi Board, loading a debug save in Player or entering the area normally the map looks like this:
![shogiunbug](https://user-images.githubusercontent.com/64451846/81513727-53d43580-92df-11ea-9db4-085c7011144f.png)

However, loading a debug save made in Shogi Board in RPG_RT the area looks like this:
![shogibug](https://user-images.githubusercontent.com/64451846/81513726-533b9f00-92df-11ea-97a4-19aaf715c04a.png)
The flying shadows are all glitched looking.
To reproduce:
I attached 2 saves
Save 1 is immediately before Shogi Board, Save 2 is inside Shogi Board
Load the second save in both Player and RPG_RT, wander around the area to see the difference.
Then load the first save in RPG_RT and interact with the pit, Shogi Board looks normal, like when loading the second save in Player.

**Comment by Ghabry** [comment]
This is fixed by #2208 

When loading the attached Player save in #2208 the shadows look glitched the same way as in RPG_RT.
When saving again with #2208 Player and loading in RPG_RT the shadows look correct :+1:

Old savegames are "corrupted" and not fixed but switching the map solves it.
