### ISSUE TITLE
Problem about "batch" in variables

### ISSUE THREAD

**Issue by Soeufans** [EasyRPG/Player#2225]
Im creating my Game Legend of Heroen, to Rm2k3 and porting it with easyRPG

I found some bug, about the batches, if i put a number from a variable into a batch to IDV 0001 to 0001 it does not work properly.

Here is a example with an engine with showing numbers, with RM2k3 there is no problem, but with EasyRPG palyer does not work  as it should

[Caso raro.zip](https://github.com/EasyRPG/Player/files/4674011/Caso.raro.zip)

Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by elsemieni** [comment]
More information of the bug:

**Test case:**
@> Control Variables: [0001] = -1 
@> Control Variables: [0002] = 1234567 
@> Control Variables: [0001..0001] = Variable [0002]

**Expected output:**
v[0001] = 1234567

**Current output:**
v[0001] = 0 (seems it writes zero)

Tested with:
-Player master 1169 https://ci.easyrpg.org/view/Player/job/player-win32/1169/ 
-RPG_RT 1.12a

**Comment by fmatthew5876** [comment]
This is a regression from the previous range variable fix.

Fixed in #2227
