### ISSUE TITLE
Webplayer hangs on tab switching

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2228]
It seems to hang on tab switching since 0.6.2. In 0.6.1 does not seem to happen. Tested on Firefox and Chromium. It could be related with interpreter or music pause on losing focus like desktop does after switching to the new loop mechanism not required with the new llvm backend.

**Comment by Ghabry** [comment]
SDL emscripten sourcecode should be checked, maybe they added something

**Comment by Ghabry** [comment]
this is somehow fixed by ``SDL_SetHint(SDL_HINT_EMSCRIPTEN_ASYNCIFY, "0");``. shrug
