### ISSUE TITLE
Vehicle rendered in battle

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2235]
From Twitter: 

hello🙂 i found some minor problems in Dragon Fantasy 2 with RTP2000( https://cgp.space/GIGA/cgpmix1/index.html ). im using EasyRPG on Android, and compared to Windows env without emu. please add these to your issues to fix

![bad](https://user-images.githubusercontent.com/1198466/83315253-aae96e00-a1ec-11ea-83b9-dd058fc93060.png)
![good](https://user-images.githubusercontent.com/1198466/83315255-ac1a9b00-a1ec-11ea-8877-8480dc48ba33.png)

**Comment by fdelapena** [comment]
Attached files received via email.

[issue-2235.zip](https://github.com/EasyRPG/Player/files/4829325/issue-2235.zip)

**Comment by Ghabry** [comment]
Reported fixed.
Label changed to Event because this is a custom battle system.
