### ISSUE TITLE
Return of Touhou Mother Soflocks on Battle System on Android

### ISSUE THREAD

**Issue by Quix64** [EasyRPG/Player#2241]
Hello I'm new here and I just found an issue with Return of Touhou Mother at the begging on the Battle System, well the error is it when I start to battle with the very first enemy on the game, I don't know her name, well I can make a normal attack, but the rhythm combos doesn't work, and once I attack for the second time, the game softlocks, I'm using the Android version EasyRPG maker, and I'm still not sure how to fix this issue,

**Comment by fdelapena** [comment]
Hello, thank for your report. It seems to be the same bug as #1733.
There is a possible candidate fix for this issues. Please try with the following APK and give us feedback:
https://ci.easyrpg.org/job/player-android-pr/4001/artifact/builds/android/app/build/outputs/apk/EasyRpgPlayerActivity.apk

**Comment by Quix64** [comment]
Well the combos works now, thank you so much, but I have a question, are there going to be an individual patch to this to apply to the apk of easy rpg or any of their ports? Or this is going to be included on the next updates?

**Comment by fdelapena** [comment]
Thank you for the feedback. This change is likely to be applied on next updates, but it may take some weeks yet. It is suggested to keep a copy of that APK version just for that game in the meanwhile, as this particular MIDI ticks requirement for music synchronization is used by very few games. At first sight, there are only two 2 known non-Touhou games depending on this feature (and they are in Japanese only).
