### ISSUE TITLE
Unexpected character movement from custom route ending with a switch

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2255]
The route ends activating a switch and this switch makes an extra movement to the right, which does not happen in RPG_RT.

This currently happens at least in 0.6.2, 0.6.2.1 and master.
Tried with a #2208 continuous build but it seems unusable currently.

Kindly tested, reported and test case created by Pizus.

[routebug.zip](https://github.com/EasyRPG/Player/files/4835111/routebug.zip)

**Comment by fmatthew5876** [comment]
This is a bug with the map event refresh that happens after setting the switch.

The switch gets set, which messes up the event's move route data, then the Refresh() call returns back to the move route update function and it continues executing on bad move route data.

**Comment by fmatthew5876** [comment]
This is now fixed in #2208
