### ISSUE TITLE
UI and text offset observations, comparisons

### ISSUE THREAD

**Issue by Tayruu** [EasyRPG/Player#2264]
#### Player platform:
Windows, version 0.6.2.1
RPG Maker 2000 1.61 English release

#### Case studies
As I've observed sometimes some of the UI elements don't completely match RPG_RT's UI, I thought I'd go through and check for the differences at hand. It's not always full-proof because of the font differences, but I hope it's close enough to try and get things as close as possible.

**Title screen, main menu screen, party/actor battle menus**
- Scrolling stops at end of menu. In RPG_RT, holding down arrow scrolls endlessly.
- Scrolling might be _slightly_ too slow.

**Item screen**
(RPG_RT / EasyRPG / Overlap)
![](https://i.imgur.com/1ew9qJh.png)
- Item quantity indicator (":"/"x") unknown if offset
- Item quantity is -2px (compared to RPG_RT pos)
- Selector +4px too long
- Right-column elements -4px
  - This also causes subsequent values to be further offset

**Skills screen**
![](https://i.imgur.com/T9lcpx4.png)
- Same as above for skill elements
- HP in active actor bar -6px
  - This also affects subsequent values (current, "/", max)

**Equip screen**
![](https://i.imgur.com/kWS4l0y.png)
- Same as above
- ">" glyph +3px (though since this apparently changes for JP locale, dunno if this would be fiddly to match)
- Scrolling stops at end of equip slots. In RPG_RT, holding down arrow scrolls endlessly.

**Save screen**
![](https://i.imgur.com/AYHaKqA.png)
- Missing space between "File" and slot number.
- Missing scroll arrows
- Arrow key can be tapped at end of list to scroll to the other end. This behaviour doesn't happen in RPG_RT.

**End screen**
![](https://i.imgur.com/DuUPlOq.png)
Now *this* is a fun one. I was boggling as to why when testing my own game why there was extra space to the side of the header. On further testing, it seems that this text for whatever reason renders spaces smaller than in other places.
Compare a string with more spaces, to the text in a message box:
![](https://i.imgur.com/PGlKFCn.png)
![](https://i.imgur.com/FX1kwLY.png)

**Message box**
![](https://i.imgur.com/8VjIEgw.png)
- Selector +4px too long

**Shop screen**
![](https://i.imgur.com/MgLoO2y.png)
- Actor offset +4px downwards
- Equipment stat change icon animates 1-2-3-4-3-2, or something? In RPG_RT it animates 1-2-3-4
- Selling items likely has same offset problems as item/skill/equip screen
- No smooth scrolling (not in other menus?)

**Battle screen**
![](https://i.imgur.com/ac341lJ.png)
- State/ailment text -2px
- HP -16px?!
  - This also affects subsequent values (current, "/", max)
- MP -4px
- Skill and item menus likely have same offset errors as other cases

---

While testing the Player with my own project, I found text shadows weren't showing up. For a bit I wondered why this was, until I realised I had been performing some trickery with my system image.
![](https://i.imgur.com/TcvPTVt.png)
In this sample you can see a few oddities: the normal text's black frame, and the two other swatches being dots, this is because when experimenting with custom fonts in RPG_RT, I came to the following observations:
- Font glyphs are by default 6x12, they can be wider (up to 12x12), but will only render in the presence of another glyph, e.g. a space.
  - EXFONT is naturally exempt, as it takes two characters to render.
- The system font colours only refer to the bottom 12px square within the 16px swatches for text. The bg and shadow refer only to the top-left pixel.
- Transparency makes text transparent, but not the shadows.

To be fair, I imagine you might not want to match these behaviours exactly. It would be useful to allow creators to use the whole 16px square for shadows/background text if they wanted to say, make backgrounds a gradient, at all possible. Fonts also don't strictly have to be locked to 12x12px glyphs, but it might be important for accuracy's sake.

**Comment by carstene1ns** [comment]
First of all thank you for your detailed issue description!
- Some of your positioning issues ("selectables") have been tracked here before: #2216.
- Endless scroll should be easy to implement.
- The font shadow observation is really interesting, this is not documented properly.

We would be very happy, if  you could share a testcase!

**Comment by Tayruu** [comment]
A test case, for the testing of these various elements? Like this?
[easyrpg_ui_testcase01.zip](https://github.com/EasyRPG/Player/files/4893524/easyrpg_ui_testcase01.zip)

I did try searching around before posting this issue, but nothing jumped out at me. My hope at least is these comparisons are detailed enough to be useful.
... I'm not sure if there's any screens I missed. I didn't include some things like the main menu because there didn't appear to be any problems. Looking at that other thread though, I didn't test the Teleport menu.

**Teleport menu**
![](https://i.imgur.com/kVwfZLK.png)
- Selector is +4px too long
- Right column is -4px to the left

![](https://i.imgur.com/zNnDzKl.png)
- I neglected to check how the menus position the selector on the right column, but here it appears to be -4px to the left, lining up with the offset of the text.
   - ... okay yeah, the item menu's right side selector is 4px off too.
   - **General conclusion**: the two-column selector is globally 4px too long on the centre end - shifted to the left on the right side to compensate for its length.
- Extra curious is the order of the list is possibly reversed. New items are appended to the end in RPG_RT, and added to the start in EasyRPG.

**Comment by carstene1ns** [comment]
Teleport menu should be sorted, if not, this is a bug (may be fixed by #2254).

**Comment by carstene1ns** [comment]
End screen uses `Window_Help`, which uses half width spaces:
https://github.com/EasyRPG/Player/blob/7aa14f6b8a82ead168c6141fdad5b25bf46aa876/src/window_help.cpp#L49
Since this window is used by some other scenes, we need to make sure this does not break.

**Comment by carstene1ns** [comment]
About Save Scene: We align by 2 spaces, so 10 and above do not have it, we can just add a space:
https://github.com/EasyRPG/Player/blob/7aa14f6b8a82ead168c6141fdad5b25bf46aa876/src/window_savefile.cpp#L58

**Comment by Tayruu** [comment]
Re #1611: Oh wow, I never noticed that the help window spaces were half width compared to other cases in RPG_RT.
It doesn't, however, seem to be using half-width spaces in the End screen.

In RPG_RT: Help window uses 3px spaces, End header, messages, menus, use 6px spaces.
In EasyRPG: Help window and End header use 3px spaces.
![](https://i.imgur.com/bWeOxcS.png)

**Comment by Tayruu** [comment]
The save screen labels are aligned by **1.5** spaces in RPG_RT:
![image](https://user-images.githubusercontent.com/49263075/87308039-bf9c7e00-c56e-11ea-9baf-72a864dbdee6.png)

**Comment by Ghabry** [comment]
@rueter37 could you quickly summarize which issues in the first comment are NOT fixed yet?

**Comment by Ghabry** [comment]
same here, creating a new one for the scroll speed
