### ISSUE TITLE
Red/Green visual glitching with Monster hues

### ISSUE THREAD

**Issue by Tayruu** [EasyRPG/Player#2266]
#### Player platform:
Windows, Player 0.6.2.1

#### Issue
![image](https://user-images.githubusercontent.com/49263075/87318045-ea410380-c57b-11ea-9610-509d29ee3a0e.png)
If you set an RTP Slime enemy to have a red hue, specifically the third notch (swatch 7), it will cause them to render in a dissolve-blend-like effect with their original palette.

Upon further investigation, this issue possibly affects all Red/Green changes. Testing the same on "People3" (blue-haired NPC) and "DragonA" produces the same problem. It also happens with "Dark Elf" on swatch 8.
![image](https://user-images.githubusercontent.com/49263075/87318890-0e511480-c57d-11ea-97e2-f6f9e3a25aea.png)

#### Demonstration
The following images represent troops of slimes for each swatch, the first and last in a screen repeating a previous set.
RPG_RT:
![image](https://user-images.githubusercontent.com/49263075/87318100-faf17980-c57b-11ea-8e2d-5808370a638c.png)

Player:
![image](https://user-images.githubusercontent.com/49263075/87318081-f4fb9880-c57b-11ea-9121-f5b794ed7d76.png)

**Comment by Ghabry** [comment]
Thanks for the report. Looks like some integer overflow :/

**Comment by rueter37** [comment]
I have added a PR (#2323) which fixes this issue.
