### ISSUE TITLE
Large map tree sequence truncation prints null characters in logs

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2268]
#### Name of the game:
Dragon Ball Z RPG or any other with a large nested map tree path.

#### Player platform:
Any.

#### Attach files (as a .zip archive or link them)
 - The `easyrpg_log.txt` log file: [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4915220/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
The text log file contains null characters and some plain text readers/editors may fail to open it as it may be recognized as a binary file.

**Comment by carstene1ns** [comment]
The string is truncated after 4096 bytes.
We have manually cut this before fmtlib landed, so needs retesting:
https://github.com/EasyRPG/Player/blob/be726b244496bf24b98921472c5b15aa042da94b/src/output.cpp#L74-L75

**Comment by fdelapena** [comment]
Confirmed fixed by #2098
