### ISSUE TITLE
Issue in Pictures

### ISSUE THREAD

**Issue by Soeufans** [EasyRPG/Player#2273]
#### Player platform: Windows

Hello!

I'm using Picture Mapping in the Legend of Heroen, and i was creating some houses using pictures... so, when i add the new picture as a map, thats what happens:

Some pixels appaears misteriously from nothing when testing the game like this:

![001](https://user-images.githubusercontent.com/65864874/89333010-a5008500-d694-11ea-9855-a265aaa24a38.png)
![002](https://user-images.githubusercontent.com/65864874/89333015-a6ca4880-d694-11ea-992d-86a9c81cbd45.png)

And when taking a Screenshot, it looks perfect as it should be.

![screenshot_21](https://user-images.githubusercontent.com/65864874/89333109-ceb9ac00-d694-11ea-9c79-122f782c58bd.png)

**Comment by carstene1ns** [comment]
This could be a transparency issue, can you upload the used images?

**Comment by Soeufans** [comment]
Heloo! here they are

![Fargote Posada-02](https://user-images.githubusercontent.com/65864874/89764333-7d764600-daf4-11ea-896f-9cae4847532b.png)
![Fargote Posada-01](https://user-images.githubusercontent.com/65864874/89764336-7e0edc80-daf4-11ea-9501-f2dce4a39ec2.png)

**Comment by fdelapena** [comment]
Those pixels appear on (desktop) full screen mode, they seem to be smaller than the rpg maker pixel size, so they are likely scaling (to nearest) artifacts. They are pretty visible on 1920x1080 on my setup, but in a different way. They also appear in Android screenshots.

**Comment by Ghabry** [comment]
Yeah these are nearest scaling artifacts when the resolution is not a multiple of 320x240.
See #1366

**Comment by Soeufans** [comment]
Heres a Full screen screenshoot in a 1280x960 resolution, a multiple of 320x240

Also, these pixels appears at random, when it should be in the same line of pixels

![1280x960](https://user-images.githubusercontent.com/65864874/90263646-3a97d380-de50-11ea-8e5f-a59d58515f1a.png)

**Comment by Ghabry** [comment]
I checked the OpenGL Docs. For scaling with GL_LINEAR it does a weighted average of 4 pixels so what you show is to be expected it seems.

Don't think this is solvable without a custom shader 🙄🙈.

Pixman doesn't have this issue but is a much slower software renderer.

**Comment by Ghabry** [comment]
@Soeufans  please recheck with this build: https://ci.easyrpg.org/job/player-win64-pr/5025/

Also check fullscreen.

**Comment by Ghabry** [comment]
No feedback for almost a year.
This is likely fixed by now as SDL2 uses a bilinear render strategy now.
