### ISSUE TITLE
Jenkins: Player macOS master branch build job fails due to linking issues

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2303]
There's something odd in the Jenkins build job. The macOS pull request builder works without issues. Already tried to clean liblcf and Player workspace, but the issue still persists. @tyrone-sudeium mentioned it builds flawlessly on his Mac, too.

**Comment by Ghabry** [comment]
The linker error is for the unit tests. I added a workaround in #2232 but it only works for debug builds 🙈

**Comment by Ghabry** [comment]
On emscripten you get the same linker error in a release build:

```
error: undefined symbol: _ZNSt3__2lsIcNS_11char_traitsIcEENS_9allocatorIcEEEERNS_13basic_ostreamIT_T0_EES9_RKNS_12basic_stringIS6_S7_T1_EE (referenced by top-level compiled C/C++ code)
```
