### ISSUE TITLE
2k3 Battle: Player waits for animations, RPG_RT doesn't

### ISSUE THREAD

**Issue by NovemberJoy** [EasyRPG/Player#2335]
Name of the game: Captain Novolin RPG (under debug conditions)

Player platform:
Ubuntu 20.04 GNU/Linux

Game download:
- [Here.](https://drive.google.com/file/d/1_0hS0zeV9QoAbik5LgERwGsPnFIAXB2N/view?usp=sharing)

Attach files (as a .zip archive or link them)
 - [Save14.zip](https://github.com/EasyRPG/Player/files/5213907/Save14.zip)
 - [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/5213888/easyrpg_log.txt)

Describe the issue in detail and how to reproduce it:
Load the provided save file and walk into an enemy. Once Dreamer-001's turn comes, choose Brace (Defend). In RPG_RT, the battle continues while the animation plays, while Player waits until it finishes before continuing. This happens with other animations as well, but to a much lesser extent due to said animations not being anywhere near as long. For context, this character is usually under AI control, which never guards.

**Comment by fmatthew5876** [comment]
This game is a good test candidate for 2k3 battle system with battle animation sprites.

My suspicion here is how we generally wait for battle animations to finish. We probably only want to wait for normal battle animations and not sprite battle animations.

**Comment by rueter37** [comment]
In RPG_RT, it depends on the battle action. If an enemy starts a normal attack, the game doesn't wait for the battle animation, the damage is done immediately (You see the battle animation and the damage number appear at the same time). But if an enemy uses a skill, the game waits for the battle animation. And player actions always wait for the battle animation.
