### ISSUE TITLE
Title image disappears too early and system graphic changes on load

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2337]
1st bug:

Select "New Game". The title screen is black before the fadeout starts. In 0.6.2.2 this doesn't happen.

2nd bug:
Is a regression #2111 
Load a savegame that has an altered system graphic. The system graphic is already changed in the load menu before the fadeout happens. In 0.6.2.2 this doesn't happen.

**Comment by rueter37** [comment]
The second bug mentioned here has been resolved by #2456.
