### ISSUE TITLE
rm2k - Game shutdown after switch skill in a battle

### ISSUE THREAD

**Issue by cristiano-bistene** [EasyRPG/Player#2340]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

Hi! I'm developing a game in rpg maker 2000 and I use to test it in EasyRPG. 

About 2 days ago, while I was playing the game on my cel phone, during a battle event, I used a skill that is activated by a switch (it shows a battle animation) and the game just shutdown!

The most weird is that it wasn't happening before! Apparently It only happens when the player use a skill that is triggered by a switch during a battle. 

I'm not sure if it is being caused by some EasyRPG update, but I noticed that the program layout is a bit different and some days ago, this bug wasn't happening.. maybe it is.

I'd really apreciate if it could be give some attention to this.

Thanks.

**Comment by Ghabry** [comment]
@rueter37 @fmatthew5876 
I just checked the Android Play Console: There are lots of crashes in "IsReflected", so I guess that logic is broken.

Maybe was not that smart to backport the Reflect commits to stable. We will need a "Patch 3" soon... :|

**Comment by fmatthew5876** [comment]
Lesson learned: We should be much more conservative in stable patches.

**Comment by rueter37** [comment]
Added a PR (#2342) which should fix this.
