### ISSUE TITLE
Game "The doritos" 's Weapon glitch

### ISSUE THREAD

**Issue by Sangpotato** [EasyRPG/Player#2347]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game  #directory)
[Doritos.zip](https://github.com/EasyRPG/Player/files/5251249/Doritos.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/5251251/easyrpg_log.txt)

**Comment by fmatthew5876** [comment]
This looks to be the same as #1727
