### ISSUE TITLE
List of custom EasyRPG terms

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2362]
This issue is to create a list of all the hard coded strings in RPG_RT that we would like to add as customizable Terms as an easyrpg extension. The rule can follow `SaveActor::name`, in that the string defaults to `\x1` which means use the RPG_RT compatible default value.

We could also extend the RPG_RT defaults to use "advocate" or "2k3e" translations, depending on the engine version.

Menu Scene (#2473)
-------------

- [x] Item number separator
- [x] Skill cost separator
- [x] Equipment arrow
- [x] Status Screen Name
- [x] Status Screen Class
- [x] Status Screen Title
- [x] Status Screen Condition
- [x] Status Screen Frnt
- [x] Status Screen Back

Battle Scene (#2502)
-------------

- [x] 2k3 battle monster double attack notification
- [x] 2k3 battle monster defend notification
- [x] 2k3 battle monster observe notification
- [x] 2k3 battle monster charge up notification
- [x] 2k3 battle monster self-destruct notification
- [x] 2k3 message for back and pincer attack (default is no message)

**Comment by Ghabry** [comment]
The 2k3 battle notification for skill (currently is the skill name) should be also customizable (with placeholder support as in 2k)

**Comment by Tayruu** [comment]
I've edited things like these myself in my RPG_RT, so the ability to set them somehow without compiling my own Player would be neat. (Though I have some functions I'll need to custom compile anyway.)

Just missing the "-----/-----" of max EXP.

**Comment by Ghabry** [comment]
This --------/------- vs EXP/-------- could be also a configuration. But more a flag than a term.

--------------------

Or maybe we should just add the "Scene Push" event command I suggested, reimplement the entire Menu scene in RPG Maker Event script and then you can alter stuff by modifying event code ;))).

**Comment by rueter37** [comment]
The "Confirm" and "Redo" commands in the party order scene are hard coded as well.

**Comment by Ghabry** [comment]
@rueter37
I just saw this commit in liblcf: https://github.com/rueter37/liblcf/commit/cf01c364b07c974aa0fb3a0a13cbd69345202386
Can you PR this commit?
Looks like a good start for this feature.

**Comment by rueter37** [comment]
@Ghabry I have opened a [PR with the commit you mentioned](https://github.com/EasyRPG/liblcf/pull/414) now in liblcf.

**Comment by rueter37** [comment]
I think the `------/------` vs `EXP/------` on the last level should be a user preference. But my proposal here requires #2035 to be merged in.

**Comment by rueter37** [comment]
Don't get fooled by the text which says that my PR #2473 will close this issue. It is only a partial fix.

**Comment by rueter37** [comment]
Thanks for the pointer how to disable the autoclose! :+1:

**Comment by rueter37** [comment]
Since #2399 is merged in now we can take on the battle scene terms now. You can check out this [liblcf](https://github.com/rueter37/liblcf/tree/custom-terms-2) and [player](https://github.com/rueter37/Player/tree/custom-terms-2) branch which has got everything needed for battle scene terms and customizable battle notifications for skills in RPG Maker 2003 battles.

**Comment by Ghabry** [comment]
I see that you also added Placeholder support?

**Comment by rueter37** [comment]
Yes, to make the battle notifications for skills more useful (see [your comment](https://github.com/EasyRPG/Player/issues/2362#issuecomment-702377199)).
