### ISSUE TITLE
DynRPG Parser example small issues

### ISSUE THREAD

**Issue by elsemieni** [EasyRPG/Player#2377]
This is an small one. 
I'm studying the new DynRPG parser feature and I found some simple issues regarding dynrpg_easyrpg "plugin" in @easyrpg_output:

- In https://github.com/EasyRPG/Player/blob/9157ed1f71253539dd5ac54a5ac80d35e9cbc104/src/dynrpg_easyrpg.cpp#L31 seems the second argument expects an int, but as mentioned in the PR (https://github.com/EasyRPG/Player/pull/2282) it must be an string. In result, It will never execute and it always show a warning for incorrect data type usage.

- **_(I don't know if this is an issue or more like a undocumented behaivour)._** In the PR example ``@easyrpg_output Info, "Hello $1! Var5 is $2", World, V5`` the first parameter (without double quotes) it will parsed as "hello" (in lowercase, at least in Windows MSVC), not causing letting go into any of the following else-if's below in the code (as every possible option starts with a capital letter). I don't know if an string without quotes must be lower-cased or not. I tought my suggestion was correct the example, however, the example is in a PR... a place made for drafts and WIP stuff, so I don't know if it matters or not (just about the capital letter thing).

I think this is a low priority issue, since this is just an example of how parser works. However, it's always good to inform these sorts of things I guess :)

**Comment by Ghabry** [comment]
Yeah it must be a string. The idea here is a check for at least two arguments.
This was more of a sample function but would be super useful for the text plugin.

The result should be:
```
Hello world! Var 5 is 100.
```
World is lowercased because it is a token (no "") and V5 has the value 100
