### ISSUE TITLE
Battle: Enemy flash inconsistency

### ISSUE THREAD

**Issue by rueter37** [EasyRPG/Player#2388]
In RPG Maker 2000 battles the enemy flashes on its turn even if he has a state with a no move restriction. In RPG_RT this flash doesn't occur.

Edit: RPG Maker 2003 battles are affected as well.

**Comment by fmatthew5876** [comment]
Ok so I was incorrect in some my earlier comments in various threads. There actually are 2 different kinds of "do nothing"

RPG_RT has 2 enums `ActionKind` and `BasicAction`

https://github.com/fmatthew5876/DynRPG/blob/master/Action.h#L3

There is `AK_BASIC` basic, which means defer to one of the `BasicAction` values. And there is a basic action kind `BA_NONE` which is used when you add a "Do Nothing" action to an enemy move list.

The way RPG_RT works is to essentially do this:
```
SetMonsterFlash(31,31,31,10,10)
ProcessBattleStates() <- this can cause a wait if a message appears
If action.kind == `AK_NONE`
    SetMonsterFlash(31,31,31,0,0) <- Immediately cancels the flash
```

`AK_NONE` is used when the enemy action list is empty, or no action was valid to be selected, or there is not enough sp etc..

`AK_BASIC` / `BA_NONE` is only used when you put a "Do Nothing" action in the enemy action list.
