### ISSUE TITLE
RTP Detection fails in WSL on Windows

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2392]
If you have RTP installed on windows and run player from WSL, it fails to find the RTP.

I'm not sure if this is even fixable since WSL is trying to pretend to be linux.

**Comment by Ghabry** [comment]
WSL can be detected but getting the RTP paths from Windows requires reading the registry. I don't think that there is a WSL Api to do this.

As a workaround you can set ``RPG2K_RTP_PATH`` and ``RPG2K3_RTP_PATH`` manually to the RTP install on Windows (somewhere in ``/mnt/c``)

**Comment by CherryDT** [comment]
You _could_ spawn `reg.exe` (which should be in `PATH`) to read the path from registry. But I can't think of a good practical (non-academic) reason using EasyRPG this way in the first place so I'm not sure it's worth the hassle.

**Comment by carstene1ns** [comment]
I do not think this configuration makes sense to support.
An end user is very unlikely to use this and developers can use the environment variables.
