### ISSUE TITLE
CMake doesn't install bash completion scripts on Linux

### ISSUE THREAD

**Issue by akien-mga** [EasyRPG/Player#2396]
#### Name of the game:
n/a

#### Player platform:
Linux, packaging EasyRPG Player for Mageia

#### Attach files (as a .zip archive or link them)
n/a

#### Describe the issue in detail and how to reproduce it:
I'm packaging EasyRPG Player for the Mageia Linux distribution.

Since upgrading to 0.6.x and switching the buildsystem from autotools to CMake, the bash-completion script in `resources/unix/bash-completion/easyrpg-player` is no longer installed by `make install`.

I'd suggest making CMake install it on Linux as autotools used to.

**Comment by Ghabry** [comment]
Yeah that's an oversight. Thanks for the report :)

**Comment by Ghabry** [comment]
@akien-mga 
Do you know if there is any accepted standard convention in CMake to install the manpage?

Can already see the can of worms opening here because the manpage folder depends on the operating system...

**Comment by akien-mga** [comment]
Well this is about the bash completion file, which are typically installed in `/usr/share/bash-completion/completions/`. I don't know if that can depend on the distro, but bash-completion has a FAQ entry on this: https://github.com/scop/bash-completion/blob/master/README.md#faq

`pkg-config --variable=completionsdir bash-completion` can be used to query the system's bash-completion folder. Maybe there's a CMake way to query that easily. Otherwise I'd say hardcoding `CMAKE_INSTALL_PREFIX/share/bash-completion/completions/` and waiting to see if anyone complains is a good way to do it too :)

As for multiple operating systems, I guess it's uncommon to have bash on Windows, and macOS defaults to zsh IIRC. Might be good to look into whether Windows and macOS can consume bash-completion scripts when configured to use this shell, but otherwise making the installation of the script Linux-specific should also be OK IMO.

**Comment by Ghabry** [comment]
oh right bash completion. No idea why I researched manpages.

The FAQ also mentions a bundled CMake script file. Will see if I can get something working.

Yeah I will limit it to UNIX and make some testing on Apple. Makes no sense for Windows.
