### ISSUE TITLE
Encounters Ending Before They Can Start

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [EasyRPG/Player#2412]
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
- The `easyrpg_log.txt` log file (you can find it in the game directory)
[EasyRPG Player Issue Evidence.zip](https://github.com/EasyRPG/Player/files/5440681/EasyRPG.Player.Issue.Evidence.zip)
(Both are included in attached zip)

#### Describe the issue in detail and how to reproduce it:
After defeating the Near-Invicible claw, any subsequent encounter I get into causes the battle screen to flash up for a second before I just end up back in the overworld; essentially ending the encounter before it starts. I know this game has an instant win mechanic, but I'm pretty sure this is happening in situations that would not normally trigger it.
Also, while it's not strictly relevant, whenever a character learns PSI in this game, it tends to mess up the order of commands in the battle window so I'd like that looked at too.

**Comment by TheNamesGregoryAndounuts** [comment]
I should also add, this bug persists even after I close easyRPG and open it again.

**Comment by fmatthew5876** [comment]
@TheNamesGregoryAndounuts 

Sorry but I'm not familiar with this game. Could you please give more precise instructions how to get to the part that triggers the bug from the provided save game?

**Comment by TheNamesGregoryAndounuts** [comment]
Okay, first you're going to want to unzip this game after downloading it from here: https://www.dropbox.com/s/htqyk9qhtywpv8d/cogdispersonal.rar?dl=0 (because it can only be obtained in a very obscure location that can't be reached via googling alone). Then you want to open the game up in easy RPG, start a new game and play up until you reach Sataene. Once in Sataene, go south-west into the area with the green fog in it. Head to the most south-easily point of this map and walk around in the fog until you get an encounter with a  Near-Invicible claw. Win the fight, and then walk into another enemy to start an encounter. The encounter screen should  pop up for a second telling you what enemy you're fighting and pressing C on it should bring you back to the overworld with no battle taking place inbetween.

**Comment by fmatthew5876** [comment]
Do you have a save game in Satanae, near where the bug triggers?

**Comment by TheNamesGregoryAndounuts** [comment]
No. But I could make one for you.

**Comment by TheNamesGregoryAndounuts** [comment]
Hello?

**Comment by Ghabry** [comment]
Hu? I wrote a comment here yesterday but somehow it is not visible 🤔.

Sorry for the delay.
Your attached savegame is in the soundroom and I somehow can't leave the room. So is not usable.

I attempted to reproduce this yesterday but I will indeed need a save game that is before the bug happens.
Can you give us one?

Note that the level of the party must be <13 otherwise the auto victory event triggers.

**Comment by Ghabry** [comment]
This one is stale. I give @TheNamesGregoryAndounuts until April to respond before I close this one.

**Comment by TheNamesGregoryAndounuts** [comment]
Yeah, sorry about that. I haven't got round to it quite yet.

**Comment by Ghabry** [comment]
okay. I dont consider this stale anymore. Just respond whenever you find time :)

**Comment by fdelapena** [comment]
@TheNamesGregoryAndounuts in case of battle testing, please try the battle system rewrite continuous build version: https://ci.easyrpg.org/job/player-win64-pr/4488/artifact/bin/easyrpg_windows_x64-PR2399.zip

**Comment by TheNamesGregoryAndounuts** [comment]
Will do!

**Comment by TheNamesGregoryAndounuts** [comment]
Just a heads up, I don't know how but my save file seems to have been overwritten with the complete one that comes with the game so I'll be do this test starting a fresh game.

**Comment by Ghabry** [comment]
okay, remember that we need a savefile that is before the bug happens.

**Comment by fdelapena** [comment]
@TheNamesGregoryAndounuts the battle system rewrite branch has been merged in master, so you can test the version from the follow link anytime: https://ci.easyrpg.org/job/player-win64/lastSuccessfulBuild/artifact/bin/easyrpg_windows_x64.zip

**Comment by TheNamesGregoryAndounuts** [comment]
@Ghabry Actually, no need. I got up to the bit where to bug happened with the test version and it was patched! I think that's an issue closed, don't you?

**Comment by Ghabry** [comment]
okay, so no idea how this was fixed (bad for the blog post later :( ) but yes, this is an issue less.
Thank you for responding! :+1:
