### ISSUE TITLE
my problem is, easyrpg/games Not readable

### ISSUE THREAD

**Issue by kamisurri** [EasyRPG/Player#2415]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by Ghabry** [comment]
Can you be more specific?
Game, operating system etc. You didn't fill out the template at all

**Comment by kamisurri** [comment]
It is with the Android Program, I already uninstalled it and cleared cache,
but it keeps giving me an error, example: /Storage/emulated/0/easyrpg/games
it is not readable

I don't know how to fix it

**Comment by Ghabry** [comment]
Try uninstalling the app, then reinstall. It will ask you for permissions to read the "storage". you must confirm this prompt. Then it should work.

**Comment by carstene1ns** [comment]
I guess this has been solved by now.

**Comment by KevinX8** [comment]
I have the same issue and it's more than likely caused by Android 11's new forced scoped storage

**Comment by Ghabry** [comment]
k will reopen it and try to verify it in an Emulator. FU Android

@BlisterB I heard you love Android :P

**Comment by Ghabry** [comment]
Looks like one can opt-out via ``requestLegacyExternalStorage`` but is unclear how long this will work.

By default you can only read/write now the app scoped storage which is _terrible_ because _all_ the data in there is _deleted_ when uninstalling the app m(.

For accessing other stuff they recommend the MediaStore Api but this can only read files, not folders. So not even usable by us o_O

**Comment by KevinX8** [comment]
> Looks like one can opt-out via ``requestLegacyExternalStorage`` but is unclear how long this will work.
> 
> By default you can only read/write now the app scoped storage which is _terrible_ because _all_ the data in there is _deleted_ when uninstalling the app m(.
> 
> For accessing other stuff they recommend the MediaStore Api but this can only read files, not folders. So not even usable by us o_O

The mediaStore way is likely doable but in a horrific way where each file is added as readable, for now opting out is probably the best workaround.

**Comment by Ghabry** [comment]
``ACTION_OPEN_DOCUMENT_TREE`` looks like a solution. But needs VFS support first.
