### ISSUE TITLE
Battle2k3: Incorrect battler placement on party change

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2418]
Write a battle event which adds someone to your party. Use automatic placement.

In RPG_RT, when the battler is removed, the existing battlers don't change position. When a battler is added, all of the parties' positions are reset.

In Player, adding or removing has no effect.

**Comment by CherryDT** [comment]
There is actually an RPG_RT bug associated with this as well: https://rpgmaker.net/forums/topics/25621/?post=917771#post917771

In case of "manual" placement they move too far to the right when adding a party member.

> Ah I see, it's only on manual placement, and it's because Shinji Hamada seems to have done a mistake when copying the code for battler placement from the battle initialization to the party change and later updating it, apparently forgetting the second copy (and that, my dear children, is why you avoid duplicate code in the first place). There is normally an offset of 24 pixels if the character is in the front row, but due to this mistake this was only applied to part of the calculation and didn't affect actual placement, so characters would be positioned as if they all were in the back row.
> 
> There you go, I created a patch to fix it: https://cherryshare.at/f/OU31HP/RPG_RT_112a_fixbadactorpositiononpartychange.ips
