### ISSUE TITLE
LunarLux: Player character not visible in 0.6.2.3

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2419]
#### Player platform:
Any

#### Attach files (as a .zip archive or link them)
Not required, simple to reproduce in the initial playable map.

#### Describe the issue in detail and how to reproduce it:
Here's a savegame point near the beginning of the game:

![Captura de pantalla de 2020-11-07 16-46-09](https://user-images.githubusercontent.com/174885/98453480-2b5ab600-211f-11eb-999c-ac7ce4380258.png)

Save, then load from the savegame. The player character won't be visible after loading.

This issue is not reproducible in player master, so it's fixed. Adding this here for reference.

**Comment by Ghabry** [comment]
Well when it is fixed this can be tagged as 0.6.3 and closed I guess?
Thanks for the issue though, helps when writing the blog :+1:

**Comment by fdelapena** [comment]
Sure. Not checked which PR fixed it, but there are lots of fixes without specific game reports, so looks fine.
