### ISSUE TITLE
Android adds the function of dynamic compilation

### ISSUE THREAD

**Issue by android-1995** [EasyRPG/Player#2422]
#### Player platform:
 Android
#### Describe the issue in detail and how to reproduce it:
Hello, I want to modify org_easyrpg_player_player_EasyRpgPlayerActivity.cpp, but I don’t know how to compile the modified so, can you adds the function of dynamic compilation?
Thank you

**Comment by Ghabry** [comment]
you can use the buildscripts to recompile the Android Player: https://github.com/EasyRPG/buildscripts/tree/master/android
