### ISSUE TITLE
Sounds keep repeating deafening fast - rain, jump or whatever

### ISSUE THREAD

**Issue by ValnarLover** [EasyRPG/Player#2427]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
every rm2k/3 game

#### Player platform:
Android

#### Attach files (as a .zip archive or link them)
 - The `easyrpg_log.txt` log file (Here's a passage of the file:
 - EasyRPG Player 0.6.2)
[2020-12-16 00:02:39] Debug: Loaded Map Map0057.lmu
[2020-12-16 00:02:39] Debug: Tree: Shannar Hinrichtung < Shannar
[2020-12-16 00:02:41] Debug: Could not load soundfont.
[2020-12-16 00:02:41] Debug: WildMidi: Using /data/user/0/org.easyrpg.player/timidity/wildmidi.cfg as configuration file...
[2020-12-16 00:03:22] Debug: Loaded Map Map0058.lmu
[2020-12-16 00:03:22] Debug: Tree: Irrenhaus leer < Shannar Hinrichtung < Shannar

#### Describe the issue in detail and how to reproduce it:
E.g. When sth like rain starts, the sounds plays like crazy and I am forced to turn off the volume. Otherwise you can't enjoy the game.

**Comment by fdelapena** [comment]
Hello, thanks for the report.

Is it possible to get a recording on how audio performs? And the device brand, model and Android version used.

**Comment by Ghabry** [comment]
The rain is in general annoyingly loud even in RPG_RT.
So I cant conclude whether this is a bug for now.

**Comment by fdelapena** [comment]
Regarding volume, it might be related to this one (or even the same):
https://github.com/EasyRPG/Player/issues/2236#issuecomment-636392500

**Comment by Ghabry** [comment]
I'm pretty sure this is the same bug. So I will mark this as fixed by my next PR
