### ISSUE TITLE
Update to Android API 30 by November 2021

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2434]
> From November 2021, updates to existing apps will be required to target API level 30 or above

Woohoo -_-

- [x] **BLOCKER**: Load time of the Game Browser is beyond inacceptable
- [x] Select Game directory through SAF
- [x] Game launching through SAF including JNI layer
- [x] XYZ-Image through SAF in the Game Browser 
- [x] Game saving and log file writing
- [ ] Standalone mode (see also #2560)
- [x] BUG: RTP folder is created multiple times on startup
- [x] RTP support through SAF
- [x] Soundfont (FluidSynth) support through SAF
- [ ] Loading of SF2 from APK (half-way to standalone mode), see also #2560
- [x] When suspending the app while playing and resuming it crashes (some important Java handle destroyed?)
- [x] Bug Report feature

**Comment by fmatthew5876** [comment]
Reminder to undo #2433

**Comment by Ghabry** [comment]
Actually API30 will simply ignore the flag but good reminder to delete it.

**Comment by Ghabry** [comment]
Also a good opportunity to drop everything below Android 4.4.

Most devices older than 4.4 can't even use the internet anymore because they have no TLS 1.2 support.

As you can see there are less than 100 devices using 4.0 to 4.3:

4.4 is still used alot though, more than some newer Android versions o_O.

![Screenshot_20210118_183705-fs8](https://user-images.githubusercontent.com/1331889/104947772-8b41c880-59bc-11eb-943a-826d9bb56a90.png)

**Comment by Ghabry** [comment]
This lib is a good candidate for the SAF, abstracts most of the ugly stuff behind a typical Java File API.

https://github.com/K1rakishou/Fuck-Storage-Access-Framework

**Comment by Ghabry** [comment]
I just installed "oandbackupX", a new version of the oandbackup tool

It also uses a Storage Access Framework it seems (Folder Selector) and for the root folder and for Downloads it shows in a popup in the dir browser "This folder cannot be used for security reasons"

Also a "Create New Folder" Icon is displayed that allows me to create a backup folder. Convenient, this is needed for the Player :)

In general I recommend: Look at the first page of oandbackupx. Is a good way for "getting started" imo.

**Comment by Ghabry** [comment]
This is tracked in https://github.com/BlisterB/Player/tree/SAF  (not updated with my commits yet).

Will add a progress list to the top comment

**Comment by Ghabry** [comment]
@BlisterB 
We want to remove Timidity GUS stuff (it just sounds terrible...) and support Soundfonts instead.

Could you add a "Select Soundfont" button the Audio settings that opens a File Browser where users can pick "*.sf2" files?

I will handle the JNI part again (and we must still find a good SF2 for embedding into the APK)
