### ISSUE TITLE
2k3 level up message isn't shown (Regression?)

### ISSUE THREAD

**Issue by NovemberJoy** [EasyRPG/Player#2442]
Name of the game: 
Captain Novolin RPG

Player platform:
Ubuntu GNU/Linux 20.04, Funkey-OS 2.0.0

Game download:
[Here.](https://drive.google.com/file/d/1_0hS0zeV9QoAbik5LgERwGsPnFIAXB2N/view?usp=sharing)

Attach files (as a .zip archive or link them)
[Save01.zip](https://github.com/EasyRPG/Player/files/5849491/Save01.zip) (Just in case the Save01 with the game download isn't the right one.)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/5849494/easyrpg_log.txt)

Describe the issue in detail and how to reproduce it:
In the provided save file, walk to the right to the cutscene trigger and fight the battle given, wiping the battlefield clean with Missile Barrage. Once you do, assuming he survives, Capt Novolin will gain 22 EXP and a level, with the increase in his max HP visible upon the start of the next fight, but the "level up" message and raising of statistics won't occur during the victory messages.

**Comment by rueter37** [comment]
I can confirm that this is a regression. It is broken since the first release of version 0.6.2. Interestingly this remained unnoticed for a long time until @NovemberJoy noticed it. Well, I didn't notice the bug myself either.

**Comment by Ghabry** [comment]
Not worth to fix this upstream anymore because of the gigantic battle patch.

@fmatthew5876 

You must move these lines after the for-ChangeExp-Loop:
https://github.com/fmatthew5876/Player/blob/batalgo/src/scene_battle_rpg2k3.cpp#L1661-L1664

**Comment by fmatthew5876** [comment]
This needed an additional feature to force `Window_Message` to only have 1 line per page. I added the fix to #2399
