### ISSUE TITLE
Emscripten: shell file looks minified but also broken

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2446]
Somehow the index.html file in master breaks some elements, e.g. missing space in `<!doctype html>` or the meta viewport is messed with another meta tag:

![Captura de pantalla de 2021-01-27 11-16-21](https://user-images.githubusercontent.com/174885/106028091-23ad0c80-6091-11eb-9d47-c07ff9ccc114.png)

URL: https://easyrpg.org/play/master/

**Comment by Ghabry** [comment]
Maybe this helps https://github.com/emscripten-core/emscripten/issues/8547

Though is more a workaround.

Can be put in the CMakeLists

``-s MINIFY_HTML=0 ``
