### ISSUE TITLE
Add an --rtp-path flag override

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2448]
On test systems like WSL rtp detection fails. On other custom setups, one would want to just tell Player to use a specific RTP in a directory.

Add an `--rtp-path` command line flag to force the Player to use that path for it's RTP.

**Comment by carstene1ns** [comment]
We have environment variables for this. Since this is linux-ish, should be easy to use in WSL.

**Comment by fmatthew5876** [comment]
It would be good to add all the env vars  to `--help`

**Comment by Ghabry** [comment]
The documentation is in the manpage.

Though some common env cars could be documented in help

**Comment by fmatthew5876** [comment]
I get it, but if you just build a binary it would be convenient to have all docs built in. Another case is if a binary is shipped with a game with manages.

I see this as a convenience.
