### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [EasyRPG/Player#2462]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the
screenshots in fastlane. This is just one way that you can also add screenshots to the app view
if you can. If you added screenshots (then F-Droid is happy) and if you can't add any -> then
you can close the issue because it was only an info. Thank you that your app is available in
fdroid. Very much for your attention.

**Comment by Ghabry** [comment]
Hello.

The problem here is that we already have fastlane support but F-Droid only checks in the root of the repository. Our fastlane folders are in builds/android.

When f-droid allows configuring of the fastlane folder this can be easily fixed.

**Comment by fossdd** [comment]
Well, this isn't able. Fastlane's specification says that it has to be in the root. And it is also like this recommended. Fastlane isn't only for Android, we as F-Droid uses that, but you can also use that with `ios`.

**Comment by Ghabry** [comment]
Do we even have any conforming fastlane folder right now?

I only see this one and it is almost empty:
https://github.com/EasyRPG/Player/tree/master/builds/android/fastlane

I guess the screenshots of Google Play are not in the repo because they are huge and have a problematic license (the title screens shown are non-free).

**Comment by carstene1ns** [comment]
They are in the metadata folder:
https://github.com/EasyRPG/Player/tree/master/builds/android/metadata/en-US/images
