### ISSUE TITLE
PO parser returns "Parse error: Unterminated line: " on Windows line endings

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2463]
This issue is easy to get hit because LcfTrans.exe generates Windows line endings (CRLF) on .po files.
Player should support both line endings to improve translation experience. Note this is unrelated to the multiline "\n" symbol inside strings.

How to reproduce on UNIX-like operating systems: get a game, then use `lcftrans` from https://github.com/EasyRPG/Tools and then run `unix2dos` to `RPG_RT.ldb.po` file. [How to use lcftrans](https://community.easyrpg.org/t/support-for-accented-letters/913/4).

**Comment by Ghabry** [comment]
that should be an easy fix, we already have code for this, gimme a sec
