### ISSUE TITLE
libretro: ICU invalid encoding (mingw)

### ISSUE THREAD

**Issue by qacjava** [EasyRPG/Player#2470]
I use the RetroArch core downloader the "easyrpg_libretro.dll " for Windows's   RetroArch  and   "easyrpg_libretro.so" for Emuelec.
but this can't play all RPGMaker games.

Windows's   RetroArch show :
Invalid encoding : windows-936-2000.

or 

Invalid encoding : windows-936.

On Emuelec(RetroArch) , flash back cannot be opened

pls help me !

**Comment by Ghabry** [comment]
Where did you download the core?

**Comment by Ghabry** [comment]
Do you know from where the core downloader gets the core? Can you try one from Https://buildbot.libretro.com ?

**Comment by Ghabry** [comment]
And wow. The core is available since October and you are the first who reports a bug. A real success story xD

**Comment by qacjava** [comment]
Wow, I'm honored to thank you for your reply
But I download from The RetroArch core Downloader.
It can't be used. 
I also tried the URL download the new core but the problem remains
I really want to play RPGmaker on Emuelec

pls help me!

**Comment by qacjava** [comment]
![20210307014432](https://user-images.githubusercontent.com/24817655/110215838-d53c2a80-7ee6-11eb-97df-f06522c0a53e.png)
![20210307014516](https://user-images.githubusercontent.com/24817655/110215840-d66d5780-7ee6-11eb-8df8-c43282d856b6.png)

**Comment by Ghabry** [comment]
Will have to check this.
Can already tell you that we know this type of bug.

Can't comment on emuelec though

**Comment by qacjava** [comment]
![20210307014901](https://user-images.githubusercontent.com/24817655/110215964-657a6f80-7ee7-11eb-8540-06faca08ede6.png)

**Comment by qacjava** [comment]
Thank you for your prompt reply. Thank you very much

**Comment by Kupo91** [comment]
On lubuntu the latest core of buildbot works fine.
But on windows I have this issue, too

**Comment by Ghabry** [comment]
@qacjava this should be fixed now but I don't know when the core downloader receives updates. Please try in 24 hours. Thank you.

**Comment by Ghabry** [comment]
is not fixed, still invalid encoding error. Must be some broken interaction between mingw crosscompile and how the icu datafile works. :roll_eyes:

**Comment by Ghabry** [comment]
My bad. The ci run used an old cache ... Force assembly build did the trick again.
Will close this when the retest was a success.
