### ISSUE TITLE
Ara Fell: Not all states shown in Info box

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2487]
#### Name of the game: Ara Fell Remastered

This is a commercial game so I cannot link it.

Basicly RPG Maker 2003 shows states in a info box when you hover a target:

![Screenshot_20210316_204453-fs8](https://user-images.githubusercontent.com/1331889/111370853-019b3800-8699-11eb-99f5-dbc8fdea52e8.png)

Ara Fell uses this in a quite creative way: To show the enemy name and some metadata.

Player only shows IMMUNE.

![3-fs8](https://user-images.githubusercontent.com/1331889/111371417-a7e73d80-8699-11eb-9d83-81eea797e035.png)
![2-fs8](https://user-images.githubusercontent.com/1331889/111371418-a87fd400-8699-11eb-8178-6e0632246b64.png)
![1-fs8](https://user-images.githubusercontent.com/1331889/111371420-a87fd400-8699-11eb-9b80-24e755e66a97.png)

**Comment by rueter37** [comment]
As far as I know in RPG_RT the info box shows up to 5 states ordered by state priority. If two states have the same priority then that state with the higher editor ID "wins". 9 full space characters are reserved per state because the state name is allowed to have up to 8 characters.

**Comment by rueter37** [comment]
Dropping out from this one - it is too likely that I break the help window on trying to fix this issue.

**Comment by rueter37** [comment]
I have decided to take on this issue again. I have added a PR (#2492) now which should fix this.
