### ISSUE TITLE
Can't open ALL games: Invalid encoding ibm-5348_p100-1997

### ISSUE THREAD

**Issue by Deusmars23** [EasyRPG/Player#2488]
Hello,
some games work fine in Retroarch. Others don't and I get this error.

What should I do?
If someone has a build that works I would appreciate if he could upload it.

Thanks for your help, getting desperate here.

[](url)
![dsdgf](https://user-images.githubusercontent.com/80813501/111432016-c4689180-86fc-11eb-94f8-15ef1461a99a.png)

**Comment by Ghabry** [comment]
On which platform do you get the error?

**Comment by Deusmars23** [comment]
Windows 10

**Comment by Ghabry** [comment]
Hu? This should work now o_O.
When was the last time you updated via the core updater?

**Comment by Deusmars23** [comment]
I already did, but just to make sure I did again right now via the online updater. Same error.

Like I said: Some games do work, maybe it has something to do with the games that don't work being German games? German has a few additional letters like ä, ö, ü etc.. but that's just a guess. :/

**Comment by Ghabry** [comment]
okay for some reason the core was not updated on the core updater?

When I download the latest build from here:
https://git.libretro.com/libretro/easyrpg-libretro/-/jobs/204108 (click Download and put the dll in "cores") it works...

**Comment by Deusmars23** [comment]
Ok thanks, it works now. Btw: Is it possible to make it sound like in original? I noticed the audio quality really decreased and sounds more like a Gameboy game now.

**Comment by Ghabry** [comment]
Is the game using MIDI music and sounds more "electronic" now? (look for Mid files in the Music folder of the game)

For slightly better audio you can download WildMidi/Timidity from the RetroArch content downloader.

This is something we will solve in the next release, when we use the native MIDI player of Windows (like RPG_RT does).

**Comment by Deusmars23** [comment]
Yes it sounds electronic. Sorry I can't find WildMidi, could you tell again where exactly to download? Thanks for the help.

**Comment by Ghabry** [comment]
should be under "Content Downloader -> EasyRPG (or RPG Maker?) -> Wildmidi"

**Comment by Ghabry** [comment]
The cores should work tomorrow (when the core updater fetches the latest), figured it out.

The MIDI stuff is already tracked on other places. closing.
