### ISSUE TITLE
Unterwegs in Düsterburg: not loading (Unicode)

### ISSUE THREAD

**Issue by Deusmars23** [EasyRPG/Player#2491]
This very famous game doesn't open in Retroarch/EasyRPG Core and I get a red error screen :/

Name of the Game: Unterwegs in Düsterburg
Platform: Windows 10 64 bit, Retroarch 1.9, EasyRPG 0.6.2.3
Description: Red Screen with a simple "Error: EasyRPG will close now"

It works when I use the standalone EasyRPG player tough, just not with Retroarch.

However I prefer Retroarch because of the shaders . Would be nice if that function would be implemented into the EasyRPG-Player.

**Comment by Ghabry** [comment]
Why did you delete the issue template?
Your report lacks essential information e.g. the operating system you use

**Comment by Deusmars23** [comment]
My bad, I edited the missing information in.

**Comment by Ghabry** [comment]
When did you install the core? 
It should work since tonights update (core updater)

**Comment by Deusmars23** [comment]
It is fully updated. All other games work but this one doesn't.

**Comment by Ghabry** [comment]
Okay this sounds like a new problem then.

Can you try renaming the game folder from "Düsterburg" to "Duesterburg"?

**Comment by Deusmars23** [comment]
Ok it worked! Apparently that was the problem.
