### ISSUE TITLE
Game fails to read assets at random times.

### ISSUE THREAD

**Issue by axzxc1236** [EasyRPG/Player#2494]
Update 1: I saw the solution and I build the patched PKGBUILD for my self but I only have the time to play the game on next weekend.

---

Sorry, I didn't use continuous build, but I built from latest source (239686f) using easyrpg-player-git from AUR.

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
(This is a Chinese RPG game) [勇者特訓班](https://forum.gamer.com.tw/C.php?bsn=4918&snA=29683)

#### Player platform:
Linux (Arch Linux based distro)

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/6175414/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
I am now playing this RPG game with long play hours and at random times easyrpg will fail to load game assets... and then it's too late to save the game, if I tried to do so it will make easyrpg force close the game and end up losing progress.
![force quit screenshot](https://user-images.githubusercontent.com/3145859/111868040-ad52c980-89b2-11eb-88c6-54d338d5f3ee.png)
First it will show the message `Warning: Music not readable: xxxxx.mid` then I tries to get to menu by pressing X then I get the red screen that says `couldn't open image file.....  EasyRPG Player will close now.`
I couldn't figure out what is triggering this odd behavior (I mean I know it will get me red screen if I tried to open menu by pressing X, but I don't know why it fails to load game assets).... seconds before game was fine and the next second it isn't, if there is something I can do to provide more debug information I can do it.

**Comment by carstene1ns** [comment]
Could be memory related. Can you try getting the used ram?
```sh
free -hm
sudo pmap `pidof easyrpg-player`
```

**Comment by Ghabry** [comment]
Or we maybe leak file handles.
This is an interesting problem.

**Comment by Ghabry** [comment]
My educated guess by now are the error paths.
It could be that some libraries we use do not invoke the close callback on error.

**Comment by Ghabry** [comment]
@axzxc1236 
Two workarounds for now:
Apply this commit to your build and recompile: https://github.com/Ghabry/easyrpg-player/commit/73cbc9f888cc0f888b67b8cdd560f5b2f78eab1c

Or:
Install wildmidi and freepats-legacy from AUR.
Copy /usr/share/freepats/wildmidi-freepats.cfg to /etc/wildmidi/wildmidi.cfg
Rebuild the Player. (this does not leak the handle anymore because SDL mixer is bypassed)
