### ISSUE TITLE
Battle 2k3: The first enemy normal attack has a glitched battle animation

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2499]
Just do a BattleTest on a new game and wait for an enemy attack.

Is better visible when you replace the Hit A with a Sword A animation.

**Comment by rueter37** [comment]
I cannot reproduce this on current master, tested with two different battle animations.

**Comment by Ghabry** [comment]
Hm maybe this only works with maniac patch unarmed animation o_0.
Have to retest this

**Comment by Ghabry** [comment]
cannot reproduce anymore
