### ISSUE TITLE
Some map events not looking as usual in Touhou Mother

### ISSUE THREAD

**Issue by Fishaphrodite** [EasyRPG/Player#2504]
I had some nostalgia of Touhou Mother yesterday, and I built both liblcf and the player again yesterday night from source (master branch is the name I think), I decided to give it a shot again, however I saw some events were looking a bit off when interacting with them, it doesn't seem to be all of them (or maybe it doesn't happen in a new game?).

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Linux
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
 
 Save is the 5th slot, screenshot of how it looked before, and how it is now are included.
 
[Touhou_Mother_odd_mapevents.zip](https://github.com/EasyRPG/Player/files/6242080/Touhou_Mother_odd_mapevents.zip)

#### Describe the issue in detail and how to reproduce it:

Put the Save05.lsd in the game folder (or whatever save folder you're using), load it, let the hat finish his little dialogue, then go to the gift box on the right and interact with it from all possible angles, it'll "turn around" when you interact with it.

Also I suggest you don't go anywhere else, as this is a very end game save, so going in the door will spoil you.

How it was before
![EasyRPG-shouldbe](https://user-images.githubusercontent.com/49363070/113265019-f28cca80-92d3-11eb-882c-b4ebf38de8ec.png)

How it is now
![EasyRPG-what-it-is](https://user-images.githubusercontent.com/49363070/113265063-fc163280-92d3-11eb-9957-156b2e053a80.png)

**Comment by Ghabry** [comment]
Thanks! This looks indeed like a regression in the interpreter.
Some (rare) event facing edge case

**Comment by fmatthew5876** [comment]
I tried it in both RPG_RT and Player and get the same broken behavior. It's a simple "direction fix / inanimate" event. Copying it to a new game works properly.

Also if you walk down, there's an enemy walking around and it's sprite is all messed up. This also happens in RPG_RT.

There must be something wrong with this save game.

**Comment by Fishaphrodite** [comment]
That would explain why it didn't seem to happen on a new game, but only on saves, I don't know if the save code has changed since then.

Actually is there a way to check which version of the player was used to make said save? I assumed something new changed it, but it might have been a 2019 save based on the retroarch core at the time and that this has been fixed since, but didn't affect all versions of EasyRPG.

**Comment by Ghabry** [comment]
The save version is stored in easyrpg -> version when you convert it to XML.
When it itself by reloading the map (leave and re-enter) this is harmless and not a bug.

**Comment by Fishaphrodite** [comment]
I checked the version, it was made with the 610 version, I guess it came from the first playthrough I made, I'm going to close it as it is not really a bug (if it was, it'd be a bug with a former version not saving that part correctly and so not really anything related to current version). Sorry about that.

**Comment by Ghabry** [comment]
I just remembered a simpler way. When you load the save it will print the version used on the terminal and in the logfile
