### ISSUE TITLE
Support Simplified Chinese Name Input Scene

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2522]
(Still waiting for the mail response about this issue)

This breaks games that use the name input for passwords because the Simplified Chinese version appears to have full-width letters and numbers? But it could be also a custom per-game patch.

When this is figured out we can add a new page for Simplified Chinese :+1: .

Breaks:
- Buried Barry
- Ib

**Comment by Helloworld996** [comment]
The problem with input bug is not only the simplified Chinese version, but also the traditional Chinese version. 
Like burried barry is traditional Chinese in fact。I'm the B A who emailed you earlier.

this is buriedbarry simplified Chinese version:
https://drive.google.com/file/d/14K8XVMqUx61owxLm7O8oEV47RhECjKpD/view?usp=drivesdk

These are the four bug found:
https://drive.google.com/folderview?id=107iY1F2Y3UkI7vZi_Xf_N8Kfne24c_75

https://drive.google.com/folderview?id=1-weIAhjUbRyzr9tnhdtoh7Kzpu_6aI6q

This is what you needed before:
https://drive.google.com/folderview?id=1-weIAhjUbRyzr9tnhdtoh7Kzpu_6aI6q

If you need anything later, you can contact me to upload to Google Space. more detail you could read i sended emails.(from B A's email) 

Maybe I havn't give you any help.

**Comment by Ghabry** [comment]
Closing this one as a duplicate. All the relevant discussion is in #2656
