### ISSUE TITLE
No sound on standalone games

### ISSUE THREAD

**Issue by carlsonsantana** [EasyRPG/Player#2524]
#### Describe the issue in detail and how to reproduce it:
After compile a standalone game and start it, the audio doesn't work.

**Comment by fdelapena** [comment]
Hello, this is a "known" issue reported by some users that package standalone for Android, likely related on how settings are initialized. It seems related to bad defaults disabling audio when unset. The current workaround is forcing the setting from the command line, but a better solution is welcome.

**Comment by carlsonsantana** [comment]
I created the pull request "Enable sound on standalone game #2525" to enable the sound.
