### ISSUE TITLE
HTML 5 - Show Picture // Spritesheet

### ISSUE THREAD

**Issue by PoppyWorks** [EasyRPG/Player#2526]
Please fill in the following fields before submitting an issue:
#### Player platform:
HTML5

#### Attach files (as a .zip archive or link them)
![1](https://user-images.githubusercontent.com/38863347/117726705-93f91d00-b1ac-11eb-9b06-073f4a569875.png)
![2](https://user-images.githubusercontent.com/38863347/117726706-93f91d00-b1ac-11eb-9d31-3f83827a15af.png)
![3](https://user-images.githubusercontent.com/38863347/117726707-9491b380-b1ac-11eb-9195-9cf846f9a3fb.png)

#### Describe the issue in detail and how to reproduce it:
"show picture" has an issue in HTML5 when using the spritesheet setting. It will show the entire image file and not crop. This feature works correctly in the desktop executable.

This issue can be replicated across Firefox, Edge and Chrome. https://easyrpg.org/player/guide/webplayer/

Thank you

**Comment by Ghabry** [comment]
You must pass "?engine=rpg2k3e" in the address bar. There is currently no way to hardcode this.

The patch in #2520 (will be merged soon) will fix it.
