### ISSUE TITLE
Issues with battle system for standalone game

### ISSUE THREAD

**Issue by brinaa** [EasyRPG/Player#2527]
I was playing Grimm's Hollow v1.1 and I notice that there was some issue with the battle system. Every time I attack the enemy in the game, I'm supposed to gain SP but I don't. My SP remains 0 throughout the battle. I also noticed that the enemy called Jerry has a skill Protect which he still can cast even after his defeat, thus I can't attack the other enemies during battle because this skill, which protects them from player's attack. 

The battle system works fine when I played it through my computer (Windows OS) but it's doesn't fine when I run it on my retro console through EasyRPG.

**Comment by Ghabry** [comment]
Thanks for the report.

Can you download a continuous build of the player from our website and test if the bug is fixed there?

**Comment by brinaa** [comment]
> Thanks for the report.
> 
> Can you download a continuous build of the player from our website and test if the bug is fixed there?

**Comment by Ghabry** [comment]
I guess this counts as a yes.

The Player on your "retro console" uses likely a stable release (currently 0.6.2.3). The next stable release will be likely in July.
