### ISSUE TITLE
Grimm's Hollow: CBA sword incorrectly appears

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2534]
#### Name of the game: Grimm's Hollow (https://ghosthum.itch.io/grimms-hollow)

[GrimmsHollowSave.zip](https://github.com/EasyRPG/Player/files/6489869/GrimmsHollowSave.zip)

#### Describe the issue in detail and how to reproduce it:

Load the save and start the compat tutorial. When you do a normal attack a sword will incorrectly appear.

Initially reported to the core: https://github.com/libretro/easyrpg-libretro/issues/53

**Comment by Ghabry** [comment]
The Actor is "Lavender" and uses the weapon "Scythe".

The character animation is a "Battle Animation" and a Sword is configure in CBA. So honestly no idea why RPG_RT does not render it.

Are CBA weapons disabled for battle animation battlers?

**Comment by rueter37** [comment]
This is a good hint, will check this tomorrow.

**Comment by Ghabry** [comment]
Currently I'm unsure what happens here. I'm pretty sure initially I didn't see any CBA weapon but now I always get a CBA Weapon animation in the compat tutorial.

Have to check this further, by now this smells like some uninitialized memory stuff.

**Comment by Ghabry** [comment]
This is a game bug:
When the RTP is installed the problem happens. Looks like BattleWeapons, compared to basicly everything else, do not crash the engine when the file is missing. Instead it just renders _nothing_.

Will keep this open while I try to contact the game author.

**Comment by Ghabry** [comment]
Another user confirmed that I'm not crazy :laughing:  : https://github.com/libretro/easyrpg-libretro/issues/53#issuecomment-841894171

Closing this now. Author was contacted, nothing we can do here imo.

**Comment by Ghabry** [comment]
[Patch Available] Grimm's Hollow 1.2 was released which fixes the bug :+1:
