### ISSUE TITLE
CBA: Move towards enemy has wrong Z-Value.

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2539]
Just create a new project and give Zhak a Sword with "Move Towards" CBA animation.

Start a battle against monster group 1 and attack the top slime.

Expected: You are above the slime

What happens: You are below the slime.

**Comment by Ghabry** [comment]
@rueter37  any idea what is causing this?

**Comment by rueter37** [comment]
Unfortunately it's hard to tell without decompiling RPG_RT. One observation I made is that the Z-Value is temporarily raised when an actor moves toward an enemy and back. But I don't know how much the Z-Value is raised.
