### ISSUE TITLE
Controller issue in EasyRPG Libretro core - zelda awakening

### ISSUE THREAD

**Issue by dj5927** [EasyRPG/Player#2546]
In Zelda awakening the arrow keys do not work in some situations.
With the opening
Arrow keys are not recognized in the Enter Name and Set Items window.

Also, there is a problem with the expression of motion animation.

You can go somewhere else normally.

retroarch 1.9.3
0.6.2.3 core is in use.

In 0.6.1 there was no problem.

**Comment by Ghabry** [comment]
Thx for the report. Thats a problem with the engine detection.
The Zelda LA one is already known #2294 
Closing as duplicate.

**Comment by Ghabry** [comment]
Reopening this one, the linked "Duplicate" is emscripten-only stuff (no way to get the filesize).

This here is again a filesize-detection issue. (RPG_RT.exe is too small and no MP3 files)

**Comment by Ghabry** [comment]
This game uses RPG Maker 2003 1.04, so before "Major Updated" but has key input proc stuff that has 14 arguments, so "new stuff".

Best way here is to find old version of RPG Maker 2003  RPG_RT.exe and reverse engineer them to find when support for the newer KeyInputProc was added...

**Comment by Ghabry** [comment]
I rechecked this now:

This game uses RPG Advocate.

The RPG_RT has this logic (I omit the shared logic):

```cpp
  if (cmd_len > 5)
  {
    check_numbers = arg[5]
    check_operators = arg[6]
    input_time_var = arg[7]
    input_time = arg[8]
  }
```

Bogus in our code is the "if (param_size < 10 && com.parameters[2] != 0) {". This is not triggered for LA because the param_size is larger. So this should be addressed.

1.08 (have nothing older) has this logic. So for the newer versions our code seems to be slightly wrong.

```cpp
 if (cmd_len <= 10)
  {
    if (cmd_len <= 9)
    {
      if (cmd_len > 5 )
      {
        // < 1.05 support
        check_numbers = arg[5]
        check_operators = arg[6]
        input_time_var = arg[7]
        input_time = arg[8]
      }
    }
    else
    {
      // RPG2k 1.50 compatibility
      all_directions = 0
      shift = arg[5]
      down = arg[6]
      left = arg[7]
      right = arg[8]
      up = arg[9]
    }
  }
  else
  {
    // >= 1.05
    all_directions = 0
    check_numbers = arg[5]
    check_numbers = arg[5]
    check_operators = arg[6]
    input_time_var = arg[7]
    input_time = arg[8]
    shift = arg[9]
    down = arg[10]
    left = arg[11]
    right = arg[12]
    up = arg[13]
  }
```
