### ISSUE TITLE
Releases section shows as 0.6.2.3 but latest master git is 0.6.2?

### ISSUE THREAD

**Issue by christianhaitian** [EasyRPG/Player#2547]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
All
#### Player platform:
Windows, Linux, Android, ...
Linux
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
When building the latest master git, version presents as 0.6.2.  Releases show 0.6.2.3 is available as of 11 days ago as of the date this ticket creation.  Is this an error or am I missing something?

**Comment by Ghabry** [comment]
This is not an error, just confusing design:
The master branch stays on 0.6.2 until the next major version.
The stable branch has commits backported and the version bumped.
No idea how to make this less confusing. Some projects bump directly after the release but this is also not ideal.

Also 0.6.2.3 is already half a year old we just forgot to click the  "create release" button.

**Comment by christianhaitian** [comment]
Ok.  So if I want the latest and greatest features, which branch should I use?

**Comment by Ghabry** [comment]
Always master

We are currently a bit behind with new releases. Next one (0.7) will be in ca. 2 months

**Comment by christianhaitian** [comment]
Ok.  Thanks again!
