### ISSUE TITLE
Arrow keys doesn't work anymore

### ISSUE THREAD

**Issue by toaradev** [EasyRPG/Player#2555]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform: Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

Hi
I dont know how to make a bug report so bear with me, i plugged in a keyboard to play Ib on my android tv box cuz i was bored, after a few days i decided to finish the game already but then quickly realizes that the arrow keys dont move the player nor the selection, i was confused, the last time i played was after the newest update, my keyboard is set to the the default provided keyboard (Android AOSP) which is still the same version as before, i even downloaded gboard to see if that helps but no dice, i tried restarting the device, replugging my keyboard, all of which did nothing until i realize every other keys work except the arrow keys, any ideas?? The arrow keys also work outside of the game so my keyboard isnt broken

**Comment by toaradev** [comment]
Actually, i dont really know if google play store did update easyrpg until now

**Comment by Ghabry** [comment]
You are the first one reporting the usage of an actual keyboard at your Android device.

We never tried this to be honest but this sounds like a bug. You can move with WSAD as a workaround ;).

**Comment by toaradev** [comment]
Yea i know, i can move with the number keys too but its very awkward when i need to press x or z

**Comment by toaradev** [comment]
Looks like its not a bug on ur part, ive downloaded an older version even way back to 2018, the problem still persist, i dont remember changing any keyboard related settings but sorry for bothering! still trying to figure out wats causing this

**Comment by toaradev** [comment]
The keyboard magiclly fixed itself after a power cut, no idea what happened! before that though i did redownload gboard then set it as the default keyboard and just kinda leave it there, after i get my power back i figure i continue troubleshooting but the thing is working now i guess u just need to select gboard then reboot the device (i didnt reboot previously) ;)
