### ISSUE TITLE
EASYRPG_FS corrupted

### ISSUE THREAD

**Issue by krmbn0576** [EasyRPG/Player#2556]
Platform: Web(Emscripten)

After #2455 (more especially, [this commit](https://github.com/EasyRPG/Player/commit/d39d3ba05752173a3e1e5321bcec8c601e3d741c)) it is no longer possible to modify EASYRPG_FS. This is probably because it is mounted as soon as it is defined.

**Comment by Ghabry** [comment]
Oh you are right. And there is no way to set ``EASYRPG_FS`` before because we destroy the Module object:
https://github.com/EasyRPG/Player/blob/master/resources/emscripten/emscripten-pre.js#L3

I will revert parts of this commit. Thanks for the notification!
