### ISSUE TITLE
NumLock number keys do not work

### ISSUE THREAD

**Issue by krmbn0576** [EasyRPG/Player#2567]
Please fill in the following fields before submitting an issue:
#### Name of the game:
Yumenikki ( powered by EasyRPG Web Player )

#### Attach files (as a .zip archive or link them)
hosted by [atsumaru](https://game.nicovideo.jp/atsumaru/games/gm20856)

#### Describe the issue in detail and how to reproduce it:
NumLock number keys do not accept input. For example, we cannot use NumLock 9 to wake up from a dream. Instead, you can use the raw numeric keys (located between the function key and qwerty), but it is inconvenient.

**Comment by Ghabry** [comment]
kinda similiar to #1121
Is about the non-numbers like +, - etc. only accepting numpad input
