### ISSUE TITLE
Battle: Issue with text box being too big during battle

### ISSUE THREAD

**Issue by gameblabla** [EasyRPG/Player#2583]
#### Attach files (as a .zip archive or link them)
You can get a copy of the game here : [https://gitlab.com/gameblabla/gameblabla-releases/-/raw/master/files/Pokemon%20Stadium.zip?inline=false](https://gitlab.com/gameblabla/gameblabla-releases/-/raw/master/files/Pokemon%20Stadium.zip?inline=false)

The game was made using RPG Maker 2003 1.09b, the French translated version by Rabbi Bodom.
sha256 9d49bf777c25f53538d94bc92a9ec18f060132eea478aa4d534a9598be45a1cb  RPGMaker2003-Rabbi-Bodom.exe

#### Describe the issue in detail and how to reproduce it:
The text box seems to be bigger than it is supposed to be. This causes part of the player sprite to be hidden behind the text box compared to the RPG_RT.

![pokemon_easyrpg_2003_bug_bad](https://user-images.githubusercontent.com/8717966/125938198-ac9e288e-6e9f-460e-ac7d-922d24669880.png)

This is how it was defined in the editor (it uses manual placement) : 
![rpgmaker_settings_1](https://user-images.githubusercontent.com/8717966/125937480-40ce68f2-2cef-49b4-8fd5-ad4e38185e94.png)
![rpgmaker_settings_p2](https://user-images.githubusercontent.com/8717966/125937482-3a5c341a-f16f-4756-b9d3-182344feaa4d.png)

**Comment by rueter37** [comment]
This is because the small battle window feature is not implemented yet, see #2575.

**Comment by Ghabry** [comment]
Closing as duplicate. Thanks for reporting
