### ISSUE TITLE
Build failure after native midi out

### ISSUE THREAD

**Issue by krmbn0576** [EasyRPG/Player#2586]
Thanks for midi improvement #2302 and I would like to build, but error occurred.

```
-- Found the following ICU libraries:
--   i18n (required)
--   uc (required)
--   data (required)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- This means no API documentation is generated.
-- Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
CMake Error at CMakeLists.txt:707 (message):
  Invalid Audio Backend Auto

-- Configuring incomplete, errors occurred!
```

Is it because of [this commit](https://github.com/EasyRPG/Player/pull/2302/commits/f8979d012047c4aad4ab2950b8f6a03bbb006a42)?

**Comment by Ghabry** [comment]
You need a clean build directory or delete the CMakeCache.txt and the CMakeFiles/ folder.

**Comment by krmbn0576** [comment]
Thank you very much! worked fine 😇
