### ISSUE TITLE
Helen's Mysterious Castle inaccurate Title BGM volume

### ISSUE THREAD

**Issue by krmbn0576** [EasyRPG/Player#2587]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
[Helen's Mysterious Castle](https://store.steampowered.com/app/418190/Helens_Mysterious_Castle/)

#### Player platform:
Web, after #2302

#### Describe the issue in detail and how to reproduce it:
After #2302, the volume of Helen's Mysterious Castle Title BGM (RTP Church.mid) is too low. And oddly enough, the volume is very loud for a moment after I press the button to start the game.

**Comment by Ghabry** [comment]
CC @tyrone-sudeium 

Thanks. This sounds (no pun intended) like a regression.

For MIDI we switched from normal volume control to MIDI message based volume control, so is possible that we missed some edge case here.

**Comment by Ghabry** [comment]
Volume:

Using logarithmic everywhere doesn't work:

- For MidiOut the scale is linear, not logarithmic
- When I use MidiOut for linear it matches perfectly
- For Non-Midiout (Fluidsynth / FmMidi) something is wrong (too loud) but the Volume events go through. E.g. a "fade" works as expected.

-------

High Volume on "New Game":

Thats a bug in the fade code. I sets the Volume to 100 always.

**Comment by Ghabry** [comment]
Does not really fit in here but here is a fix for the 3DS so I do not forget to include it:

```cpp
diff --git a/src/platform/3ds/3ds_audio.cpp b/src/platform/3ds/3ds_audio.cpp
index 7ec56a5..40e5f06 100644
--- a/src/platform/3ds/3ds_audio.cpp
+++ b/src/platform/3ds/3ds_audio.cpp
@@ -195,7 +195,7 @@ void CtrAudio::SE_Play(Filesystem_Stream::InputStream stream, int volume, int pi
 		return;
 	}
 
-	std::unique_ptr<AudioDecoder> dec = cache->CreateSeDecoder();
+	auto dec = cache->CreateSeDecoder();
 	dec->SetPitch(pitch);
 
 	int frequency;
diff --git a/src/platform/3ds/3ds_audio.h b/src/platform/3ds/3ds_audio.h
index e282abb..1b645f9 100644
--- a/src/platform/3ds/3ds_audio.h
+++ b/src/platform/3ds/3ds_audio.h
@@ -53,7 +53,7 @@ public:
 	void UnlockMutex() const;
 
 	ndspWaveBuf bgm_buf[2];
-	std::unique_ptr<AudioDecoder> bgm_decoder;
+	std::unique_ptr<AudioDecoderBase> bgm_decoder;
 	LightEvent audio_event;
 
 private:
```

**Comment by carstene1ns** [comment]
Can pull into my recent pr.
