### ISSUE TITLE
RTP Shop 3.mid plays noisy

### ISSUE THREAD

**Issue by krmbn0576** [EasyRPG/Player#2588]
When I play the `Shop 3.mid` included in the 2000/2003 RTP, it sounds very bad. The reason is that the drum channel is being played as a piano. This happens both before and after #2302.

**Comment by Ghabry** [comment]
this will be likely fixed by https://github.com/EasyRPG/buildscripts/pull/111

And thanks, we were unable to find many files that have this drum vs. piano problem.

**Comment by Ghabry** [comment]
yes is indeed fixed by fluidsynth

**Comment by krmbn0576** [comment]
Fixed by EasyRPG/buildscripts#111 thx 😇
