### ISSUE TITLE
Yume2kki: Song playback speed incorrect

### ISSUE THREAD

**Issue by coinsandboins828626** [EasyRPG/Player#2590]
#### Name of the game:

Yume2kki (Recent version)

#### Player platform:

Windows

#### Attach files (as a .zip archive or link them)

[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/6844064/easyrpg_log.txt)
[Save01.zip](https://github.com/EasyRPG/Player/files/6844065/Save01.zip)

#### Describe the issue in detail and how to reproduce it:

While playing, I've noticed that certain songs do not have the correct playback speed that they normally would. Instead, they play at full speed, 100%, with no alterations. This usually applies to songs that usually would play at around 25% speed or lower. Example/How to reproduce: In the sound room, songs 127D, 329C, and 340A are all songs set to play at low speed, yet will experience the aforementioned bug.

Also, I've noticed that midi files do not react to speed changes at all, no matter what speed they are set to play at.
Example/How to reproduce: In the sound room, song 346B is a midi song set to play slightly lower than normal, yet plays at the regular file speed.

All of these errors do not persist when using the regular rpg maker, just to clarify. The linked save file has all of the example tracks unlocked in the sound room if you would like to reproduce quickly.

**Comment by Ghabry** [comment]
This is semi-fixed in the "continuous build":

Out-of-range Music values are now clamped instead of reset to default (you will get 50% now, still not 25% but closer)

Pitch changes for MIDI work since yesterday ;).

**Comment by coinsandboins828626** [comment]
Downloaded the continuous build and the issues seem to be fixed! There are some playback errors on that build but I'm aware it is in development and that they don't occur in the current stable release anyway.

**Comment by Ghabry** [comment]
Can you quickly list for us what you mean with playback errors?

To get MIDI working we had to rewrite huge parts of our audio code so it is possible that we broke stuff by accident.

Thanks!

**Comment by coinsandboins828626** [comment]
A couple of things I noticed during a short play session:
-Certain audio tracks had low volume (mostly midi) or were completely silent
-Sometimes the audio would cut out when entering certain areas
-Graveyard World's theme (in the music room, track 26), had its pitch changes sort of freak out and appear to be going above the amount they should.

**Comment by Ghabry** [comment]
> Certain audio tracks had low volume (mostly midi) or were completely silent

This is known

> Sometimes the audio would cut out when entering certain areas

This could be a known bug in our fade-out code, but we will check.

> Graveyard World's theme (in the music room, track 26), had its pitch changes sort of freak ou

This one is new to us.

We will try to fix them :)

**Comment by coinsandboins828626** [comment]
Sounds great, thank you!

**Comment by Ghabry** [comment]
wtf is this MIDI file?! This even gives audio glitches when I play it with fluidsynth.

Maybe @tyrone-sudeium wants to take a look. Is the MIDI expert here ;)

[ym2-19_kuruwasiimonohahaieguru.zip](https://github.com/EasyRPG/Player/files/6863559/ym2-19_kuruwasiimonohahaieguru.zip)

**Comment by tyrone-sudeium** [comment]
That is extremely cursed. But from a MIDI perspective, completely valid! Such extreme pitch bends so rapidly definitely sounds like it'll hit edge cases in various synthesizers. This MIDI file almost looks like the result of a fuzzer

**Comment by Ghabry** [comment]
Track 026 sounds "fine" (not for my ears but compared to Windows media Player) to me.

**Comment by Ghabry** [comment]
I used lcf2xml and some xpath foo now to find the used values. CC @rueter37 

Pitch values (Valid range is 50 to 150)

For sound effects (count | value):

```
  10366 100
   9918 150
   8951 50
   3323 90
   2857 110
   2494 60
   2090 70
   1800 80
   1218 120
    740 130
    397 140
    250 20  (!)
     10 30  (!)
      1 40  (!)
      1 10  (!)

```

For music (count | value)

```
   3536 100
   1150 50
    747 70
    692 60
    662 80
    462 90
    254 150
    150 110
    113 120
     98 130
     74 140
     43 40  (!)
     22 20  (!)
      9 13  (!)
      6 10  (!)
      5 25  (!)
      3 30  (!)
      1 37  (!)
      1 300 (!)
      1 14  (!)
```

I also found 2 BGMs that use a volume of 130 and 150%. Lets ignore this...
