### ISSUE TITLE
Savegame made with EasyRPG can contain invalid “battleanim_target” id and will crash RPG_RT.exe

### ISSUE THREAD

**Issue by florianessl** [EasyRPG/Player#2597]
#### Name of the game:
Sternenkindsaga (1.1.3)

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
[Sternenkindsaga - Version 1.1.3 - Saves.zip](https://github.com/EasyRPG/Player/files/6880809/Sternenkindsaga.-.Version.1.1.3.-.Saves.zip)

#### Describe the issue in detail and how to reproduce it:
(Original thread with more details can be found here: https://community.easyrpg.org/t/save-game-made-with-easyrpg-contains-invalid-battleanim-target-id-and-will-crash-rpg-rt-exe/992)

This seems to be caused by a map transition while a BattleAnimation is playing. A currently running BattleAnimation from a previous map might be saved into the .lsd with battleanim_active=T and the battleanim_target is set to an Event ID from the previous map. After loading the save, RPG_RT.exe will try to execute the animation on the given ID and will crash with “Invalid event specified” if no Event is found..
**Steps to reproduce:**
In Sternenkindsaga, enter the Map 0109 "Vorplatz" from the west and immediately go through the door north, go into the custom menu and save your game. If done quickly enough, this will create a corrupt save file which cannot be loaded in RPG_RT.exe. The game is trying to display the fountain animation inside with an event target that doesn't exist.

**Comment by Ghabry** [comment]
@fmatthew5876 

As the RPG_RT.exe internals expert:
Do you know anything about the behaviour of Battle Anims on map change?
Are they just set to 0?

**Comment by CherryDT** [comment]
`battleanim_active` is simply set to `false`.

**Comment by rueter37** [comment]
Would it be a possible fix for this issue to add `data.battleanim_active = false;` after [line 88 of game_screen.cpp](https://github.com/EasyRPG/Player/blob/master/src/game_screen.cpp#L88)?
