### ISSUE TITLE
Ineluki .link files are only supported for BGM's but not for SE's

### ISSUE THREAD

**Issue by florianessl** [EasyRPG/Player#2598]
#### Name of the game:
Any game with Inelukis MP3 patch (Sternenkindsaga uses it for SE's)

#### Player platform:
Any

#### Describe the issue in detail and how to reproduce it:
I guess this was an oversight when the MP3 patch was implemented:

Inelukis “link.wav” files work fine as BGM but any time a sound effect with the ending .link.wav is played, EasyRPG Player just states: _“Couldn’t play SE . Format not supported”_

**Comment by Ghabry** [comment]
Worked on a patch to implement this.

However I didn't check how Ineluki handles it internally so features like "loop" are not supported. I just pass it to the SE handler.
