### ISSUE TITLE
Add missing Chinese glyphs

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#260]
Currently, EasyRPG Player does not have proper Chinese font support .

Here is a game with texts in Traditional Chinese:
http://download.seesaa.jp/contents/win/ent/rgame/11279/

Note: .zip archives contain files with non-ascii encoding

**Comment by Ghabry** [comment]
According to the latest bug report there is also a lack of
0x9259 鉙
0x54C6 哆 tremble, shiver, shudder, quiver
0x78B4 碴 chipped edge of a container
0x76d4 盔 helmet; bowl; basin
0x9183 醃 marinate, pickle; salt
0x5ab3 媳 daughter-in-law
0x5b38 嬸 wife of father's younger brother

Guess we really need a hugher font ^^

Btw could we use unibit legal wise?

The comment states:
COMMENT "from X11 core fonts. The entire CJK Unified Ideographics (U4E00-U9FA5)"
COMMENT "and CJK Unified Ideographics Extension A(U3400-U4DB5) were replaced"
COMMENT "by high-quality glyphs from China National Standard GB19966-2005"
COMMENT "(public domain). Near a thousand of non-CJK characters were improved by"

[font.zip](https://github.com/EasyRPG/Player/files/373442/font.zip)

**Comment by Ghabry** [comment]
Can any lawyer tell me if rendering the font is a "document"?

"As a special exception, if you create a document which uses this
font, and embed this font or unaltered portions of this font into 
the document, this font does not by itself cause the resulting 
document to be covered by the GNU General Public License. This 
exception does not however invalidate any other reasons why the 
document might be covered by the GNU General Public License. If you 
modify this font, you may extend this exception to your version of 
the font, but you are not obligated to do so. If you do not wish to 
do so, delete this exception statement from your version."

**Comment by DBLobster** [comment]
WenQuanYi submitted "China National Standard GB19966-2005" glyphs to Unibit.
WenQuanYi Has 9pt(12x12) glyphs. Unibit has only 16x16.
I also has a problem: GPLv2+FE code in GPLv3 project is OK?

I make a fallback to WenQuanYi method.
#1058
