### ISSUE TITLE
The language auto recognition ability of the latest version is not as good as that of version 0.6.2.3. 

### ISSUE THREAD

**Issue by Helloworld996** [EasyRPG/Player#2604]
#### Name of the game:
nightmare game
#### Player platform:
Android
#### Attach files (as a .zip archive or link them)
the game download link:
https://drive.google.com/file/d/17EX6DkC1h2XNEa5d-1eF_1yTRgrXAQ9u/view?usp=drivesdk

This is the nightmare game new download address:
https://www.dropbox.com/s/40yxzl3bde5rq8w/nightmare%20game.zip?dl=0

#### Describe the issue in detail and how to reproduce it:

the bug reproduce video:
https://drive.google.com/file/d/10OZtqzRnIMFq-I4xlLoDdPLefSVYUzFm/view?usp=drivesdk

Errors are often identified and need to be switched manually. 
Then switching the language area will still prompt the problem that the picture can not be recognized.
(0.6.2.1314 also have this problem)
![Screenshot_2021-07-31-11-53-13-928_org easyrpg player](https://user-images.githubusercontent.com/58156832/127728337-8018c026-e415-45b6-96b4-97bbd24da9b4.jpg)
![Screenshot_2021-07-31-11-53-02-643_org easyrpg player](https://user-images.githubusercontent.com/58156832/127728474-d7db2adb-c2b3-4d08-a7ce-d553f53812a9.jpg)

**Comment by fdelapena** [comment]
Maybe is worth to add some filename strings to the encoding detection to improve the heuristics.
This is likely more a liblcf bug, the issue could be moved there later.

**Comment by Ghabry** [comment]
did anybody download the files? It says "Cannot download because it violates copyright" :/

**Comment by Ghabry** [comment]
@Helloworld996  the download link is broken

**Comment by Helloworld996** [comment]
> @Helloworld996 下载链接坏了

This is the nightmare game new download address:
https://www.dropbox.com/s/40yxzl3bde5rq8w/nightmare%20game.zip?dl=0

**Comment by Helloworld996** [comment]
> 有没有人下载文件？它说“无法下载，因为它违反了使用条款”：/

This is the nightmare game download address:
https://www.dropbox.com/s/40yxzl3bde5rq8w/nightmare%20game.zip?dl=0

**Comment by Ghabry** [comment]
This broke when we changed the Database from global to instance variable.

The best way to solve this is making a breaking change to the encoding detection API.
Also a good oportunity to replace the "load DB twice" logic with a "load once + ForEachString"
