### ISSUE TITLE
Wrong engine detected: Grave Spirit game control issues

### ISSUE THREAD

**Issue by Helloworld996** [EasyRPG/Player#2606]
#### Name of the game:
Grave Spirit
#### Player platform:
Android,PC
#### Attach files (as a .zip archive or link them)
English version
https://drive.google.com/file/d/11_nPPxKsfgJ-fgGwhn9bKT6S293LS4hR/view?usp=drivesdk

Chinese version
https://drive.google.com/file/d/11V7O9ySVz6sKHxjYq3Z8VNG0Grj1pF5M/view?usp=drivesdk

#### Describe the issue in detail and how to reproduce it: 
you could load save and find this problem
Grave spirit game whether in Chinese or English version, after getting the props birds, the automatic process will automatically exhale birds and the direction keys and the right can not be used. 
But the game is normal on PC. 
But PC's easyrpg has the same bug.
the reproduce videos:
https://drive.google.com/file/d/10ciDN7Sl_105x2G-MISiGx9_t4G6tU33/view?usp=drivesdk
https://drive.google.com/file/d/10k_bEPBOCyGXQmFQUnhNWRcMDz0VUMCd/view?usp=drivesdk

**Comment by Ghabry** [comment]
There are two problems here:

- The game is detected as 2000 but is a 2003 game.
- The "bird" is automatically spawned, this does not happen in RPG_RT (Interpreter bug?)
