### ISSUE TITLE
Inn: Harmony skips silence at the end of MIDIs

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2611]
#### Attach files (as a .zip archive or link them)

[POSADA.zip](https://github.com/EasyRPG/Player/files/6986970/POSADA.zip) (from the game [The Story Of Egroj](https://www.hellsoft.net/H5/component/remository/func-startdown/357/?Itemid=527)).

#### Describe the issue in detail and how to reproduce it:

The attached MIDI file contains an inn jingle with notes for around 4 seconds, but the total MIDI length is around 28 seconds because it contains a marker as a comment after around 28 seconds. It does not contain event loop (111).

![marker](https://user-images.githubusercontent.com/174885/129456027-b79214b7-a26a-4c10-836e-a5afd4f84347.png)

Harmony respects the silence on maps, but skips the silence on Inn.

Player does not skip silence for libfluidsynth and native MIDI on Inn.

Note: if the MIDI loops and the sequence does not end, it is a different issue, fixed since #2612.

- [ ] Check if Harmony sends some kind of event to the MIDI device. cc @tyrone-sudeium 
- [ ] Test behavior with MIDIs with 111 event loop.

Related: #2584

**Comment by Ghabry** [comment]
Does it fade in(n) directly after the 4 seconds?

What I can see is that there seems to be a time-out for how long the Inn BGM can play. Should be 10 or 20 seconds.

**Comment by Ghabry** [comment]
Imo your example here is the 10 second timeout.

Unfocus the window when the Inn music starts. When it is almost done do a refocus. There will be around ~9 seconds of silence.

**Comment by rueter37** [comment]
In RPG_RT if the inn BGM has a length of 10 seconds or more, the inn BGM always timeouts after 10 seconds.
