### ISSUE TITLE
arrow key error

### ISSUE THREAD

**Issue by Great1052** [EasyRPG/Player#2614]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

https://t.co/sYKZNoDsQT  -> link to download the game

#### Describe the issue in detail and how to reproduce it:

Arrow key do not work in menu. It doesn't move up or down, sand both side. I can't save the file or use items so I have to start it again from the beginning.

**Comment by toaranotdev** [comment]
Have you tried WASD instead? Also try using Gboard instead of whatever you had, and restart the device, i had a similiar problem before and that's how I actually fixed it :)

**Comment by Great1052** [comment]
> Have you tried WASD instead? Also try using Gboard instead of whatever you had, and restart the device, i had a similiar problem before and that's how I actually fixed it :)

Thank you for your help :) but I am using tablet to play the game so i can't (actually don't know how to) use WASD or Gborad :(...

**Comment by toaranotdev** [comment]
So the arrow keys is the plus thingy, I misunderstood, I assume you downloaded the Player on Google Play and I don't think this issue can be game specific. Perharps your touchscreen is broken...? A restart could be magical sometimes too :)

**Comment by Great1052** [comment]
> So the arrow keys is the plus thingy, I misunderstood, I assume you downloaded the Player on Google Play and I don't think this issue can be game specific. Perharps your touchscreen is broken...? A restart could be magical sometimes too :)

I tried using my bluetooth keyboard with rebooting my device, but only left arrow key worked (my touchscreen also recognized only left arrow key) 😂😂 And with left arrow key, still I can't save the game

**Comment by Ghabry** [comment]
Guess for your game the wrong engine version was detected and this breaks the key input :/
There is currently no way to fix this on Android. Sorry

**Comment by libraryofruina** [comment]
is there any way to fix this on pc?

**Comment by fdelapena** [comment]
Tested on Linux and it fails also for number keys (1, 2, 3) and it also fails on 3DS and PSVita (see #2811).

**Comment by fdelapena** [comment]
Confirmed it's an engine detection failure. It's a 2k3 game but lacks 2k3 game folders (possible 2k to 2k3 migration).

@libraryofruina a provisional solution for PC: add ` --engine rpg2k3v105` to the command line argument and it will work as intended.

**Comment by lens0021** [comment]
When the fix of this will be released? Adding `--engine rpg2k3v105` works for me also, but a general patch will be great.

**Comment by Ghabry** [comment]
It is fixed in the continuous build. You can get them at the bottom of the download page.

An official release (0.8) is planned soon
