### ISSUE TITLE
Incorrect handling of overflow

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2650]
Test case:

```
@> Control Variables: V[0001] = 9999999
@> Control Variables: V[0001] *= 300
```

This overflow a signed 32bit integer.

RPG_RT: 9999999
Player: -9999999

**Comment by Ghabry** [comment]
For MSVC... well.........

----------

For gcc and clang this is quite trivial, something like this (uses compiler intrinsics to create optimal code like checking the overflow flag of the CPU):

```
constexpr Var_t VarAdd(Var_t l, Var_t r) {
	Var_t res = 0;
	if (__builtin_add_overflow(l, r, &res)) {
		// FIXME: Determine if under- or overflow
		return std::numeric_limits<Var_t>::max();
	}
	return res;
}

constexpr Var_t VarSub(Var_t l, Var_t r) {
	Var_t res = 0;
	if (__builtin_sub_overflow(l, r, &res)) {
		// FIXME: Determine if under- or overflow
		return std::numeric_limits<Var_t>::max();
	}
	return res;
}

constexpr Var_t VarMult(Var_t l, Var_t r) {
	Var_t res = 0;
	if (__builtin_mul_overflow(l, r, &res)) {
		// FIXME: Determine if under- or overflow
		return std::numeric_limits<Var_t>::max();
	}
	return res;
}
```

**Comment by Ghabry** [comment]
MSVC could use "safeint.h", is part of the Windows SDK.

If you wonder why I want built-ins: SPEEEEEEEEEEEED. ;)

Better wait Post-0.7 for this because this needs not too old compilers.

**Comment by carstene1ns** [comment]
Since it is clamped later anyway, `return std::numeric_limits<Var_t>::max();` could be `return _max`;

https://github.com/EasyRPG/Player/blob/93d1f32dbded97acdfa9cb8211e6a6a942401463/src/game_variables.cpp#L90-L91

**Comment by Ghabry** [comment]
> Since it is clamped later anyway, `return std::numeric_limits<Var_t>::max();` could be `return _max`;
> 
> https://github.com/EasyRPG/Player/blob/93d1f32dbded97acdfa9cb8211e6a6a942401463/src/game_variables.cpp#L90-L91

Couldn't use this btw because the Op is a static function and has no access to the configured limits
