### ISSUE TITLE
Brave and Stinker 2: Graphic display bug

### ISSUE THREAD

**Issue by TVsJohn55** [EasyRPG/Player#2658]
#### Name of the game:
Brave and Stinker 2
#### Player platform:
Android
#### Attach files (as a .zip archive or link them)
https://mega.nz/file/mLZXSCII#-pHOIbB8nFfwR1fySpFAAruSIlWF-qMwhDw4o7JAwSE
https://mega.nz/file/bXBTUCQT#ajV9DRoXq0kT6VZfx5l2r9znB8Zs0thp_axkbI-IOcg
https://mega.nz/file/6b4QQS6D#btxYb-V2BMf4YT4GoQ6Ot1Mi5NiKL7vTLbt5fnRfwyQ

#### Describe the issue in detail and how to reproduce it:
When an enemy character appears on top of an enemy character during a battle, the graphic of the previous enemy character does not disappear.(Mirai Translation)

**Comment by TVsJohn55** [comment]
https://mega.nz/file/6b4QQS6D#btxYb-V2BMf4YT4GoQ6Ot1Mi5NiKL7vTLbt5fnRfwyQ

**Comment by Ghabry** [comment]
NSFW warning for that video. wtf is this xD

**Comment by Ghabry** [comment]
This is a Z-Layer problem. The 1st chara must be behind the 2nd.

**Comment by carstene1ns** [comment]
This needs testing now after #2819.

**Comment by Ghabry** [comment]
@TVsJohn55 the download links are invalid and I cannot find the game on the internet. Can you provide a download link again?

**Comment by Ghabry** [comment]
Closing as "Invalid" because the game cannot be found and the issue author is not responding after waiting for a year.
