### ISSUE TITLE
Yume 2kki: Certain music crackles/pops audibly when looping

### ISSUE THREAD

**Issue by Monocarpic3926** [EasyRPG/Player#2666]
#### Name of the game: 
Yume 2kki

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
![tut](https://user-images.githubusercontent.com/93298073/139178020-3eaa318c-dd43-4c7c-9a42-3bc8f3f35772.gif)
[music.zip](https://github.com/EasyRPG/Player/files/7430799/music.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/7430804/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
Certain music in the game audibly pops when it loops, compared with playing on RPG Maker 2000 where the same music, whilst still making a popping sound if listening carefully, is significantly quieter. Above is a GIF showing how to quickly get to two areas in the game where this occurs, with text of the music filenames appearing when in the area where that music plays. I've also included a zip file that contains the two different music examples - one that is a recording of the music taken in EasyRPG, then for comparison that same music recorded in RPG Maker, and then the original music files that both programs are reading from.

**Comment by Ghabry** [comment]
That is a bug in our resampler. When the resampler is off it sounds like in RPG_RT :/

The resampler is also lots of legacy code nobody touched in years...

**Comment by Monocarpic3926** [comment]
> That is a bug in our resampler. When the resampler is off it sounds like in RPG_RT :/
> 
> The resampler is also lots of legacy code nobody touched in years...

Thank you for the explanation. Is there an option to turn off the resampler? I checked the manual for relevant flags but the only flag I can find related to audio is one that looks like it just disables audio altogether.

**Comment by Ghabry** [comment]
You cannot disable the resampler because it ensures that everything plays at the correct samplerate (usually 48kHz). The tracks are 8kHZ which means they would normally play very fast without resampling.

**Comment by Monocarpic3926** [comment]
> You cannot disable the resampler because it ensures that everything plays at the correct samplerate (usually 48kHz). The tracks are 8kHZ which means they would normally play very fast without resampling.

That sucks, but that does make sense. Hopefully it gets fixed at some point because aside from this the game runs beautifully.

**Comment by Ghabry** [comment]
Imo the best solution is to refactor AudioDecoder + AudioResampler next and merging them into one class.

Don't think this is easily solvable right now because the interaction of AudioDecoder wrapped into Resampler is very complex. Especially since MIDI events were added.
