### ISSUE TITLE
Invalid Save Directory error for zipped games (Wii)

### ISSUE THREAD

**Issue by VannevarKush** [EasyRPG/Player#2668]
Name of the game:  All games that I tested
Player platform:  Wii
Screenshot of issue:  https://i.imgur.com/Ny9bS77.png
Describe the issue in detail and how to reproduce it:

Any zipped game I launch in EasyRPG Player for Wii, 0.7.0 or from the continuous build, will give me the above error message when I try to launch a game that is in a zip file: ("Invalid save directory sd:/apps/[easyRPG directory]/[game name].zip.save")

If I create the missing folder that is mentioned in the error, for example "311.zip.save", the game launches and runs nicely.  However when I manually create the save directory, that game is now listed twice in the game list, once for the zipped game and once for the save folder (which does not actually contain a game.)

I'm excited for this zip support feature because a large library takes up much less space on an SD card (even without compression, due to the many small files).  I'd be glad to help test it!!

**Comment by Ghabry** [comment]
No idea why create directory fails and ".save" folders are not filtered for you in the game browser 🤔 

Though we also never tested this feature on the Wii 😅

**Comment by Ghabry** [comment]
Btw @VannevarKush  you have a nice collection of games it seems!
Could you provide us with a list of all games you have? Maybe you have some that cannot be found on the internet anymore (we are collecting lost games and put them on www.rmarchiv.de :))

**Comment by VannevarKush** [comment]
No problem, here is the full list:

https://docs.google.com/document/d/1fXeqBpi9abjWddLGphybNh1VLdsgWeXwNO-IyG8KdG0/edit?usp=sharing


About a year ago I went on a deep dive downloading all the RPG Maker 2K/2K3 content I could find.  This list should have most of the English language contents of www.rmarchiv.de, it's an awesome site, by the way!  Lots of RPG Maker games that I didn't see anywhere else :)

I'd be glad to work with you to archive anything you don't already have.  So, hopefully I'll have a few things to contribute!

**Comment by Ghabry** [comment]
Thanks but you set the sharing settings wrong. Cannot access the document.

**Comment by VannevarKush** [comment]
My mistake, it should be fixed

**Comment by Ghabry** [comment]
In Dolphin Emu launching ZIPs works fine so this must be a problem with the absolute path that contains "sd:/"

**Comment by carstene1ns** [comment]
@VannevarKush: How do you launch the player? through hbc or some other loader? (e.g. wiiflow)
I remember libfat had problems then.

**Comment by Ghabry** [comment]
My educated guess is the following: The Make Directory is recursive by going from the lowest path to the highest:

First it will check whether "sd:" is a directory. If this returns false it will try to create a directory with this name and if this fails then the algorithm aborts. Could be a similiar problem on PSVita.

One could try checking if the first component ends on a ":" and simply skip it.

**Comment by VannevarKush** [comment]
> @VannevarKush: How do you launch the player? through hbc or some other loader? (e.g. wiiflow) I remember libfat had problems then.

I'm launching the player via HBC.  I should also add that I'm running it in the vWii on a Wii U.

**Comment by Ghabry** [comment]
@VannevarKush 

Could you test if this build fixes the problem for you? https://ci.easyrpg.org/job/player-wii-pr/3379/

**Comment by VannevarKush** [comment]
> @VannevarKush
> 
> Could you test if this build fixes the problem for you? https://ci.easyrpg.org/job/player-wii-pr/3380/

I've tested the build and it's working great so far!  Games are launching normally and the error message is gone.  Saving and loading also seems to be working fine.  Finally, the save directories are filtered out on the main menu.

Now I can save about 30 gigs on my SD card :)  Thanks for looking into this, and feel free to get in touch about that list of games if it's of interest!

**Comment by carstene1ns** [comment]
Thank you for testing!
