### ISSUE TITLE
Save or load problem on the Wii version when there picture involved 

### ISSUE THREAD

**Issue by Ccd-ToF** [EasyRPG/Player#2672]
[Bugged saves.zip](https://github.com/EasyRPG/Player/files/7449246/Bugged.saves.zip)

#### Player platform:
Wii

#### Attach files (as a .zip archive or link them)
 - There no log in the wii version or I didn't look well ? 

#### Describe the issue in detail and how to reproduce it:

I tried with several game and I might have found the cause: It seem the Wii version have a bug when it save a file when there picures  on the screen. I tried with 5 differents game, 3 of them had Picture on the screen and these 3 are the one with the bug. When I try to load those save, it only show a black screen, with sometime a picture on the middle. Those save files are not detected when I play the game with classic RPG Maker but they are when I load them with Easy RPG on PC or any other version. 

The bug dont happen with 3DS and PC Easy RPG version. 

Maybe the wii version struggle when it save a file with too much informations ?

**Comment by Ghabry** [comment]
Sounds like a problem with the endianess (a missing byteswap somewhere)

**Comment by Ghabry** [comment]
Recent gcc versions optimize away our byteswap because casting double to uint32 is undefined behaviour (strict aliasing). -_-

**Comment by Ghabry** [comment]
@Ccd-ToF 

Please try this boot.dol, it should fix your problem (when you change the map and save/load again)

[boot.dol.zip](https://github.com/EasyRPG/Player/files/7493042/boot.dol.zip)

**Comment by Ccd-ToF** [comment]
A big thank ! :D It worked !
