### ISSUE TITLE
10x fast forward not working (Wii)

### ISSUE THREAD

**Issue by VannevarKush** [EasyRPG/Player#2675]
Name of the game:  All games, and main menu
Player platform:  Wii
Describe the issue in detail and how to reproduce it: 

For the Wii version of easyRPG, it is possible to fast forward at 3x by holding down the minus button on the Wiimote.  Holding down the plus and minus buttons at the same time would fast forward at 10x in the previous version of easyRPG.

In the current version (continuous build), holding down plus and minus together does not fast forward at 10x.  However, holding down minus for 3x speed does work.

The 10x speed is especially useful on the main menu, because with a large number of games listed, it can be used to make the menu scroll faster.  As a side note, I noticed that in this version, easyRPG now loads much faster with many games in the menu.

**Comment by carstene1ns** [comment]
Okay, this was not checked when moving the key to <kbd>G</kbd> in #2544.
Fix is simple, we just need to replace `PLUS` with `FAST_FORWARD_PLUS` here:
https://github.com/EasyRPG/Player/blob/281be71fee034ea789308919b2a77c92b7446c20/src/platform/wii/wii_input_buttons.cpp#L32

https://github.com/EasyRPG/Player/blob/281be71fee034ea789308919b2a77c92b7446c20/src/platform/wii/wii_input_buttons.cpp#L49

**Comment by ttyborg** [comment]
I don't know, if I should open a new issue for this, but 10x fast forward is also missing on the Vita (or at least, I can't find it). 3x ff is bound to the triangle and it works fine.

**Comment by carstene1ns** [comment]
This is being worked on (configurable button layout), also for other platforms.
