### ISSUE TITLE
MIDI not working in the jenkins build of the Vita port. Expected?

### ISSUE THREAD

**Issue by webodan** [EasyRPG/Player#2700]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

I tried using the jenkins build found at https://ci.easyrpg.org/job/player-vita/lastSuccessfulBuild/artifact/build-vita/

---
Please fill in the following fields before submitting an issue:
#### Name of the game:

Paranormal Syndrome, midi shows "format not supported".

#### Player platform:
Windows, Linux, Android, ...

on ps vita

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

Just running the game after installing the vpk and the rtp files. wondering if jenkins just didn't compile midi into the program or if it's just that there's no midi support on vita.

**Comment by Ghabry** [comment]
MIDI should be supported.
Can you tell us where you get the error? Directly at one of the first maps?

**Comment by webodan** [comment]
> MIDI should be supported. Can you tell us where you get the error? Directly at one of the first maps?

Right after starting, after the girl in the intro speaks, there's a fade to black, then a MIDI track plays. Then it says format not supported on the top and the midi file does not play. It does play fine on Linux, i tried on several machines after making sure it compiled with MIDI support in. So it's something with the jenkins build I assume.

**Comment by webodan** [comment]
Whoops, turns out VitaShell didn't copy the files correctly, for some reason it sometimes leaves them as 0 byte files. So I mistook the "format not supported" error as if it didn't support MIDI (it happened to me before on Linux before compiling MIDI support into the player), but it was that the file was corrupted and it didn't read it, rather than "not supporting" the format. Sorry
