### ISSUE TITLE
Discussing the Logo / Splash Screen

### ISSUE THREAD

**Issue by jetrotal** [EasyRPG/Player#2701]
Hey! 
The current logo has some design issues with the player's native resolutions (320x240, 640x480, etc), some of they are:

![image](https://user-images.githubusercontent.com/45118493/143721867-f9492fe4-148a-4939-a648-01457c821400.png)

☝ The text has some strong anti-aliasing, which gives to the stretched image a jagged look and difficults the reading.

----------------
![image](https://user-images.githubusercontent.com/45118493/143721955-4fbf9f3d-8d20-4928-8261-b0775c6c30af.png)

☝ The colors are too similar and the Logo uses subtle gradient colors, this blurs the edges of each color when stretched, affecting the readabillity of the logo

----------------
![image](https://user-images.githubusercontent.com/45118493/143721829-6bd5b126-055f-4ccf-814e-c2ebc1092467.png)

☝ The whole thing looks too big, It uses too much of the borders space... 

Would be nice if we could keep all compact and neat, like the Old RM2K splash screens logos:

![image](https://user-images.githubusercontent.com/45118493/143722080-b4f321f9-ecb8-434b-99e7-16235eacc5c1.png) ![image](https://user-images.githubusercontent.com/45118493/143722093-3d439723-e551-4a4f-ba78-038cc87c3c3b.png)

---------------

So, I spent a day working on suggestions to use on the splash screen, they are inspired by those original 2000's logos:
![image](https://user-images.githubusercontent.com/45118493/143722176-aa7f1d9e-a701-4a9e-8dc5-3713eebfcefe.png) ![image](https://user-images.githubusercontent.com/45118493/143722197-7f9036e6-6c7f-4f1d-aef6-742d84a65a77.png)

The link to it: [EasyRPG LogosProposal.zip](https://github.com/EasyRPG/Player/files/7612482/EasyRPG.LogosProposal.zip)
It contains a Photoshop File with both designs, and two 8-bit png files aswell.

It also has those 2 Creative Commons fonts I used on it:
TinyUnicode - http://www.pentacom.jp/pentacom/bitfontmaker2/gallery/?id=468
Koubit001 - http://www.pentacom.jp/pentacom/bitfontmaker2/gallery/?id=265

--------------

The arts are optmized to deal with 256 colors in total:
![image](https://user-images.githubusercontent.com/45118493/143722321-29fae80d-7631-4184-8b13-8786258d0738.png)

----------------

I will also provide a HD version of it, but It works better at Icon Scale.
![image](https://user-images.githubusercontent.com/45118493/143722270-90d11dec-2d4b-4ce0-9507-b8dd412d50ea.png)

--------------

that's it, feel free to use or discard any of my feedbacks.
thanks in advance!

![x silly_animation](https://user-images.githubusercontent.com/45118493/143722433-705ebf48-6dce-4ff0-a0ad-0350fcc5fe5b.gif)

**Comment by jetrotal** [comment]
Some updates:
![image](https://user-images.githubusercontent.com/45118493/143730260-8f6f24a0-eff9-4dda-8feb-157f1401df0b.png) ![image](https://user-images.githubusercontent.com/45118493/143730273-3fc397c4-51f4-4bde-9f4a-b3612e593131.png)

Fdelapena asked for a way of making the engine's webaddress easier to read.

I changed the font and put it at the bottom corner of the frame.

After that, he suggested that these bottom text may have to be put dynamically, since the player run on 16:9 aspect ratio, cropping the splash screen.

----------------------


I'm uploading the new version of the logos here: [EasyRPG LogosProposal V2.zip](https://github.com/EasyRPG/Player/files/7612854/EasyRPG.LogosProposal.V2.zip)

![8bit-320x240-EasyRPG-A](https://user-images.githubusercontent.com/45118493/143730762-8aac80a2-6dda-4818-9df3-7b2f4675c9c4.png) ![8bit-320x240-EasyRPG-B](https://user-images.githubusercontent.com/45118493/143730763-c0dae96f-7706-41b9-9605-440baeeb5f02.png)

It uses 3 fonts under Creative Commons License:
TinyUnicode - http://www.pentacom.jp/pentacom/bitfontmaker2/gallery/?id=468
Koubit001 - http://www.pentacom.jp/pentacom/bitfontmaker2/gallery/?id=265
DRTC - http://www.pentacom.jp/pentacom/bitfontmaker2/gallery/?id=9667

**Comment by Ghabry** [comment]
I prefer the second version without that rectangle in RPG_RT still.

But now we need a way to render the version text on startup. Shouldn't be too hard. Just add another BDF font ;)

**Comment by Ghabry** [comment]
Converted TinyUnicode and DRTC to BDF Pixel Fonts.
This does not make them usable in the Player yet but is a start (also at the end we should only use one)

[TinyUnicode-16.txt](https://github.com/EasyRPG/Player/files/7824572/TinyUnicode-16.txt)

[DRTC-16.txt](https://github.com/EasyRPG/Player/files/7824575/DRTC-16.txt)

**Comment by Ghabry** [comment]
Agreed by jetrotal and if nobody else objects: Logo license is CC-BY-SA. That is an acceptable license for a logo. Though we will likely not sue anyone for not doing attribution... (sloppy journalists/blogger everywhere).

In the chat there was now a discussion about smaller versions like 16x16 or 32x32.

But what I would like to have additionally is a 640x480 version of both logos. In case we ever add a "high resolution" (totally HD xD) mode.

**Comment by Ghabry** [comment]
@jetrotal 

The logo has a strange 1 pixel RGB(13, 13, 13) around the corner. Please make this black. Otherwise this looks bad because this line is noticable in fullscreen mode.

**Comment by jetrotal** [comment]
> @jetrotal
> 
> The logo has a strange 1 pixel RGB(13, 13, 13) around the corner. Please make this black. Otherwise this looks bad because this line is noticable in fullscreen mode.

[EasyRPG.LogosProposal.V3.zip](https://github.com/EasyRPG/Player/files/9946910/EasyRPG.LogosProposal.V3.zip)

There you go, also added the svg logo for not losing it later

**Comment by jetrotal** [comment]
Converted the font files from .TTF to .FON

That may fix those glitch that happens when using BitfontMaker fonts with freetype: 
![image](https://user-images.githubusercontent.com/45118493/214672156-d37dd4f1-303e-42f5-beca-db2048246d7b.png)

[EasyRPG.LogosProposal.V4.zip](https://github.com/EasyRPG/Player/files/10503008/EasyRPG.LogosProposal.V4.zip)

**Comment by fdelapena** [comment]
Recompressed 8-bit PNG logos for slightly smaller executable binary size:

15175 -> 14213
![8bit-320x240-EasyRPG-A](https://user-images.githubusercontent.com/174885/224772839-27aff451-9215-4cd2-b93a-3a7d7ccd00cf.png)

7413 -> 6763
![8bit-320x240-EasyRPG-B](https://user-images.githubusercontent.com/174885/224772834-90287c78-7a23-4b78-a31a-49459b6d3433.png)
