### ISSUE TITLE
Blank screen in fullscreen mode

### ISSUE THREAD

**Issue by Animajosser** [EasyRPG/Player#2704]
#### Player platform:
Linux

#### Describe the issue in detail and how to reproduce it:
When running `./easyrpg-player`.
1. On Wayland: all I get is a blank screen.
2. On X.org: it retains what was displayed in the top-left rectangle of the screen, that appears to be a quarter of the screen in size. The mouse is bound to the top-left rectangle.

However when running `./easyrpg-player --window`, it works fine.

#### Info current setup
For this additional information is definitely required, but I have no idea where to get it.

I tried multiple resolutions, all had the same problem.
I tried multiple graphics cards (AMD and Nvidia), both had the same problem.
I tried both X.org and Wayland, both had the same problem.

System:
AMD Ryzen (Zen 3) CPU
AMD Radeon RX6000 GPU
Platform: Linux 5.15.8
Everything updated to the latest version

Here the Command Line-output (both terminated with Ctrl-C): 
```
$./easyrpg-player
Debug: EasyRPG Player 0.7.0 (git~27@df05ffb8, 2021-12-09) started
Debug: ==========================================================
Debug: Clock: StdSteady steady=true period=ns (1 / 1000000000)
Debug: Seeded the RNG with 1639668205.
Debug: CLI: 
Debug: SDL2: RendererInfo hw=true sw=false vsync=false
Debug: SDL2: Detected format (0) SDL_PIXELFORMAT_ARGB8888 : rank=(2)
Debug: SDL2: Detected format (1) SDL_PIXELFORMAT_ABGR8888 : rank=(2)
Debug: SDL2: Selected Pixel Format SDL_PIXELFORMAT_ARGB8888
^Ceasyrpg-player: src/filesystem.cpp:288: Filesystem_Stream::InputStream FilesystemView::OpenInputStream(StringView, std::ios_base::openmode) const: Assertion `fs' failed.
```
```
[1]    1449 abort (core dumped)  ./easyrpg-player
$ ./easyrpg-player --window
Debug: EasyRPG Player 0.7.0 (git~27@df05ffb8, 2021-12-09) started
Debug: ==========================================================
Debug: Clock: StdSteady steady=true period=ns (1 / 1000000000)
Debug: Seeded the RNG with 1639668348.
Debug: CLI: --window 
Debug: SDL2: RendererInfo hw=true sw=false vsync=false
Debug: SDL2: Detected format (0) SDL_PIXELFORMAT_ARGB8888 : rank=(2)
Debug: SDL2: Detected format (1) SDL_PIXELFORMAT_ABGR8888 : rank=(2)
Debug: SDL2: Selected Pixel Format SDL_PIXELFORMAT_ARGB8888
^C
```

**Comment by Ghabry** [comment]
@Animajosser 
Do you use the linux build from the Download section? This one is only for testing.

Better use the package offered by your distribution and if your distribution does not offer it use the ones from "Open Build Service" (OBS). You can also find them in the download section.

**Comment by carstene1ns** [comment]
Should be our test build, because of the version string. Last time I checked, our SDL was built without wayland support, so this explains at least this issue.

**Comment by myownfriend** [comment]
Just wanted to add that I'm experiencing the same issue but on a dual screen setup. It actually blanks out both screens but the cursor still shows. I initially  assumed it was a Mutter issue because the software showed up correctly in Gnome's overview but after reporting it to them they found it happened on other DEs as well.

The only difference in behavior that I got with X.org is that my mouse cursor was limited to a small section of the screen in Gnome's overview so I had to exit full screen to close the software.

The Open Build Service builds don't work for me because the most recent Fedora build offered is Fedora 32 which is nearly 2 years old. I'm on Fedora 36.

**Comment by Ghabry** [comment]
The Fedora build is outdated because it is packaged in the official fedora repositories since Fedora 31.

```bash
dnf install easyrpg-player
```

**Comment by myownfriend** [comment]
> The Fedora build is outdated because it is packaged in the official fedora repositories since Fedora 31.
> 
> ```shell
> dnf install easyrpg-player
> ```

Oops. My bad. That worked.

Thank you!

**Comment by Ghabry** [comment]
I fixed this now. Problem was that some X11 devel packages were missing. Main culprit is xrandr.

Installed the following packages on the server to fix it (And added to admindoc):

```
pipewire-devel wayland-devel libXi-devel libXcursor-devel libXinerama-devel libXfixes-devel libxkbcommon-devel libXrandr-devel
```

This does not add any fixed dependencies, they are all queried dynamic by SDL2.

Note that using that debug build is still discouraged. Only for testing. But at least fullscreen works now ;)
