### ISSUE TITLE
Libretro core version 0.7.0 on windows can't run Ruina.

### ISSUE THREAD

**Issue by ddspj23** [EasyRPG/Player#2718]
#### Name of the game:
Ruina(Chinese version)
#### Player platform:
Windows 10,libretro 1.9.14

#### Attach files (as a .zip archive or link them)
[Game file(packed into zip)](https://1drv.ms/u/s!AjPw3RbzBSiPm3ivmDHeQmbQz6x3)
#### Describe the issue in detail and how to reproduce it:
Game runs with no problem on easyrpg libretro core version 0.6.2.3,but can't even start on easyrpg libretro core version 0.7.0.(select RPG_RT.ldb file)
Warning shows "ZipFS:RPG_RT.ldb is not a valid archive."

**Comment by ddspj23** [comment]
I start game from cmd,and it displayed that RPG_RT.ldb is not a valid archive,which seems to be strange because the same game runs very well on the past versions and android build of libretro core.

**Comment by ddspj23** [comment]
And I found that if I directly start the game from zip file,the game could run with some error.

**Comment by Mimigris** [comment]
Just tested your issue on my RetroArch session on Windows 11 with the latest continuous Libretro core of the Player and I was unable to reproduce your issue (the game was launched correctly as intended).
I guess that it may have been fixed recently in the continuous build, or maybe I just don't have your issue on my side?
![image](https://user-images.githubusercontent.com/108797333/233872539-10ebe07a-01b6-438c-9319-0546a7c017b3.png)

**Comment by Ghabry** [comment]
no feedback and outdated
