### ISSUE TITLE
Not finding libfmt but libfmt-dev version 5.2.1 installed

### ISSUE THREAD

**Issue by Exarkuniv** [EasyRPG/Player#2719]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Linux
Raspberry Pi4/ Buster Debian 10

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game) N/A
 - The `easyrpg_log.txt` log file (you can find it in the game directory) N?A

#### Describe the issue in detail and how to reproduce it:

I took over for zerojay who had a script written for have this install on RetroPie and Raspberry's Pis. right not it does not work. it is failing when looking for ``libfmt``, which is installed with ``libfmt-dev version 5.2.1`` it will come up with a prompt for me to install 5.3 or higher, but i know from looking in the issues that you guys it allowed to build with older then 5.3 
i know that it is pulling the least build from GuitHub

**Comment by Ghabry** [comment]
Thanks for the report.

This happens in some build environments and we are not sure why (maybe related to crosscompiling?).

As a workaround you could use CMake as this is supported by fmt 5.2 natively.

**Comment by Exarkuniv** [comment]
thanks for the quick response. ill give that a try and report back

**Comment by Exarkuniv** [comment]
ok now that i have taken a better look at whats going. it is failing to find FMT when i run ``./configure --prefix=/usr --enable-fmmidi=fallback``
i dont even get to running ``cmake``

**Comment by carstene1ns** [comment]
You do not need to run the autoconf stuff when using cmake:
```
# clone Player repo / use release tarball
cmake . -DCMAKE_BUILD_TYPE=Release -DPLAYER_BUILD_LIBLCF=ON
cmake --build .
# move the 'easyrpg-player' executable where you want it
```

**Comment by Exarkuniv** [comment]
that seemed to work better. it did end up getting a error at the end, but im also getting some other things working weird on my end. so im going to redo my load and start from a clean image and ill report back

**Comment by Exarkuniv** [comment]
ok i did a clean image and tried it again i still get a error at the end

```
[ 98%] Linking CXX executable easyrpg-player
/usr/bin/ld: cannot find -lbcm_host
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/EasyRPG_Player_exe.dir/build.make:109: easyrpg-player] Error 1
make[1]: *** [CMakeFiles/Makefile2:193: CMakeFiles/EasyRPG_Player_exe.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by Ghabry** [comment]
This is a library used by the raspberry firmware. No idea honestly why this is pulled in as a dependency.

Could you attach the CMakeCache.txt ?

**Comment by carstene1ns** [comment]
I suspect it is needed by SDL. However, no idea how the build is invoked, as it should be present in the environment. There have been issues with arm64 version, but this should not matter here.

**Comment by Exarkuniv** [comment]
well i have downloaded both
``https://github.com/EasyRPG/Player.git`` and ``https://github.com/EasyRPG/liblcf.git``
```
    cd liblcf
    cmake . -DCMAKE_BUILD_TYPE=Release
    cmake --build .
    cmake --build . --target install
   
    cd ..
    cmake . -DCMAKE_BUILD_TYPE=Release -DPLAYER_BUILD_LIBLCF=ON
    cmake --build .
```
 CMakeCache.txt 

https://pastebin.com/YgzF9kr2

**Comment by Exarkuniv** [comment]
ok ill remove downloading and building liblcf now. 
and no i dont have ``libraspberrypi-dev`` and ``libraspberrypi-bin`` packges

**Comment by Ghabry** [comment]
I think this is a bug in our FindSDL2 file. The additional library dirs are not included.

My guess to solve this is:

https://github.com/EasyRPG/Player/blob/master/builds/cmake/Modules/FindSDL2.cmake#L269

Add two more lines here:

```
set_property(TARGET SDL2::SDL2 APPEND_STRING PROPERTY
 INTERFACE_INCLUDE_DIRECTORIES "${SDL2PC_STATIC_LIBRARY_DIRS}")
```

**Comment by Exarkuniv** [comment]
i did that and i get this
```
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "SDL2::SDL2main" includes non-existent path

    "/usr/include/SDL2/opt/vc/lib"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
and 
```
[  2%] Building CXX object CMakeFiles/EasyRPG_Player.dir/src/audio_midi.cpp.o
In file included from /home/pi/RetroPie-Setup/tmp/build/easyrpg-player/src/decoder_opus.h:22,
                 from /home/pi/RetroPie-Setup/tmp/build/easyrpg-player/src/audio_decoder.cpp:30:
/usr/include/opus/opusfile.h:110:11: fatal error: opus_multistream.h: No such file or directory
 # include <opus_multistream.h>
           ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by carstene1ns** [comment]
Looks like the directories have been wrongly concatenated.

**Comment by Exarkuniv** [comment]
is that something that i can change, or is it more on your end.
sorry for being kinda a burden. i know nothing when it comes to programming, 
i know enough to run commands, and thats about it

**Comment by Ghabry** [comment]
Read the CMake documentation again.

A list append is ``APPEND`` not ``APPEND_STRING``

**Comment by Exarkuniv** [comment]
changing that seemed to work. 
it at least finished compiling without a error.

**Comment by Exarkuniv** [comment]
yes it seems to be building and also launching now. 
i can get the menu at least. have not got any game files at the moment, but its good enough to close the issue
