### ISSUE TITLE
2k/3 defaults to --window, but player does not

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#2721]
Maybe @elsemieni can guide us better, but launching a game through a launcher app, the game came prepared for window mode (960x720), but the game launch the game in fullscreen.

I've could fix this with --window, that it was the goal.

All this happened under windows 10 x64.

Thanks in advance.

**Comment by fdelapena** [comment]
This is in fact the default since the 2k3 Steam release, not sure about 2k Steam.

**Comment by Ghabry** [comment]
This can be configured as a setting in #2730
