### ISSUE TITLE
Emscripten: API requirements between Player and Browser

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2722]
There is by now lots of interfacing between the Player and the Browser as part of the multiplayer projects.

I want to collect here what is currently used by the projects to unify this approach. Also with the goal to upstream some stuff.

@Gamizard @Flashfyre @CataractJustice  could you please contribute what kinds of callbacks you added?
In both direction: Webbrowser -> Player and Player -> Webbrowser

Also which callbacks you would like to have but did not implement

List:

- [x] Download Savegame (added by me in a branch as an enhancement for the File Scene, not merged yet)
- [x] Upload Savegame (added by me in a branch as an enhancement for the File Scene, not merged yet)
- [X] requesting a reset (added in my branch)
- [X] scene refreshing to ensure that stuff like "new savegame" becomes visible directly (added in my branch)

**Comment by CataractJustice** [comment]
List:

- Set player sprite (Used by "/spriteset" command)
- Get current room id

Callbacks for setting up switch sync (Currently used only by Yume Nikki for weather switch):
- Turn switch sync on/off
- Add/Remove switch from whitelist

Chat:
- Send chat message
- Update chat input caret (Used for interaction between hidden web browser input and in-game input)
- Update chat input text (Used for interaction between hidden web browser input and in-game input)
- Is chat focused
- Print info message in chat
- Print player message in chat
- Change nametag (Called by chat to send name through game socket)

**Comment by Ghabry** [comment]
Was told that what I want to do with embind is unsupported due to risk of stack corruption.

The only supported solutions are:

- Remove Asynchify OR
- Use the emscripten fiber API

**Comment by Ghabry** [comment]
Closing this as the initial API for emscripten is finalized
