### ISSUE TITLE
Confusion between Simplified Chinese and Japanese fonts.

### ISSUE THREAD

**Issue by lychees** [EasyRPG/Player#2724]
Hello EasyRPG Player team. We are a community of Chinese yumenikki fan games. Many of us like the idea of the multiplayer version, it brings a whole new experience. While working on translation those games and setup our own local multiplayer version, we found there are some mistake when displaying Chinese characters in EasyRPG.

Long story short, today in East Asia, the Chinese characters used in different regions are different. E.g. the Japanese language makes many of [their own Chinese characters](https://ja.wikipedia.org/wiki/%E5%92%8C%E8%A3%BD%E6%BC%A2%E5%AD%97) in history.

![image](https://user-images.githubusercontent.com/2507027/154346113-3ded5717-7332-4833-bfe6-dd7e4eb2942a.png)

Both Japanese and Chinese fonts appear in a same paragraph is not a good idea. Note that this bug only occurs in EasyRPG and did not reproduced in the original rpgmaker 2000 and 2003.

![S~NY{QG786F_{ A6DT(6H5S](https://user-images.githubusercontent.com/2507027/154346551-9d605bed-c987-4fef-ab66-06c22ee5315e.png)

![UPOA6DJEY`A{}YJM@TNRKWG](https://user-images.githubusercontent.com/2507027/154346524-3fddf4c7-923e-4fd7-a472-457ff95b9a5c.png)

We have successfully resolve the bug in our local multiplayer version, still need a few days to improvements the code in order to merge them to the master branch.

Regards.

**Comment by Ghabry** [comment]
Another longstanding problem is here that we make no difference between Font and Encoding.
So even if we would fix this then it would not work for your case because you cannot set the encoding to Chinese as it would not find the Japanese filenames anymore :/

Though if you compile this manually you can likely fix it on your own:
You want BITMAPFONT_WQY as the first font and not as the fallback font (see font.cpp)

**Comment by lychees** [comment]
> Though if you compile this manually you can likely fix it on your own: You want BITMAPFONT_WQY as the first font and not as the fallback font (see font.cpp)

Yes, I use this method in my local version.
I found that there are indeed [some functions in the player.h which can distinguish between encoding](https://github.com/EasyRPG/Player/blob/ff36dfd32318fae14300ed562f5690ab94dfaf1c/src/player.h#L209-L249).

Can we use them to check the encoding and to determine if we need to raise the priority of BITMAPFONT_WQY?
If the data filenames also has Japanese character, the user should specific the encoding in .ini file and cannot use Chinese encoding by default. I thought we don't need a perfect solution here to resolve this problem, but should be consistency with the original rpgmaker.

**Comment by Ghabry** [comment]
Well yeah using the encoding would be the fix I would propose.

I just suggested a quick workaround ^^.

#2656 is a problem because the Name Input can be patched in RPG_RT.exe. The Chinese games we received have at least 5 different name input scenes so this is not really solvable in a nice way...
