### ISSUE TITLE
Any plan to support OneShot original?

### ISSUE THREAD

**Issue by KoleckOLP** [EasyRPG/Player#2736]
yes issue happens in continuous builds as well.

### Name of the game: 
OneShot

### Player platform: 
Windows

### Attach files (as a .zip archive or link them)
![Player_CH6kZ9P6fJ](https://user-images.githubusercontent.com/22729896/155715497-86c9d73b-8133-4f34-b645-50d1fce30820.png)

[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/8141120/easyrpg_log.txt)

### Describe the issue in detail and how to reproduce it:
download the game: https://rpgmaker.net/games/6560/downloads/
start it in EasyRPG 
press start and you get the screen in the screenshot above

(My goal is to play this game on PS Vita,
is there a modded version of the game or EasyRPG that let's me to that?)

**Comment by carstene1ns** [comment]
On vita this is currently not possible. (you would need to rebase and compile the 20kdc fork)

We have no official plans to support it.

**Comment by Ghabry** [comment]
Sorry but this game uses a heavily modified version of RPG_RT.exe.

Supporting this is out of scope for this project.

There is a fork (https://github.com/20kdc/EasyRPG-Player-Fork-For-OneShot-Legacy) to support this. But it is unmaintained since 5 years, so likely not really an option.

**Comment by derric-young** [comment]
there have been attempted ports of oneshot 2014 to platforms such as the 3ds and wii before. if you want a ps vita. i recommend basing the ps vita port off of this here https://github.com/cmaster25/Oneshot-For-Wii
should be a good soultion
