### ISSUE TITLE
Translation: When switching the language ingame Autostart & Parallal CE are not (re)translated

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2754]
Probably caused by an optimisation in our code that prevents unloading and reloading the event code as this is a waste of resources. Needs a check if the language changed.

Reported by Jan (Deep 8).

Thank you!

**Comment by lychees** [comment]
I also have some error around these lines.

![image](https://user-images.githubusercontent.com/2507027/162563173-037543b7-5c08-4ae2-91ad-3def26eee0f6.png)

Delete these line can fix the above issue.

![image](https://user-images.githubusercontent.com/2507027/162564268-15ac4172-77f3-4898-9dcb-62edfe074edb.png)

**Comment by Ghabry** [comment]
Fixed in #2817 

@lychess That problem is unrelated to this bug. Please open a new one if this is still relevant.
