### ISSUE TITLE
Runic Cipher: segmentation fault when trying to load a new map

### ISSUE THREAD

**Issue by Dudemanguy** [EasyRPG/Player#2756]
#### Name of the game:
Runic Cipher

#### Player platform:
Artix Linux

#### Attach files (as a .zip archive or link them)
[Game Download](https://rpgmaker.net/games/1496/)
[Save Game Data, easyrpg log, and backtrace](https://0x0.st/oqzo.zip)

#### Describe the issue in detail and how to reproduce it:
In a nutshell, easyrpg-player always segfaults for me on a certain part of the game where it tries to load a new map. As far as I know, this only happens to me so I'm not sure how reproducible it is. With the game and the above save file, your character will be right on top of a city. Just go up to enter it. When you're in the city, keep going all the up to the top to go to the area where there's a boat. Then head right and talk to the person at the very end. Some dialogue will happen and what is supposed to happen is you get a little cutscene where you move a new map. However for me, easyrpg-player segfaults on this part.

**Comment by Ghabry** [comment]
The loaded map is not in the map tree (LMT).

Fixing this is not _that_ easy because we assume in alot of places that this cannot happen. That assumption worked for quite a long time...

**Comment by Dudemanguy** [comment]
So I recently got an updated LMT file from the author and now this no longer crashes. Does that just mean this is not an easyrpg-player bug and it's just that the game itself was bugged?

**Comment by Ghabry** [comment]
This is a game bug but the player shouldn't crash :)
