### ISSUE TITLE
How to Show Animation in cpp

### ISSUE THREAD

**Issue by lychees** [EasyRPG/Player#2759]
![image](https://user-images.githubusercontent.com/2507027/160970317-8c2022bd-9e79-4b8f-8425-5d67fe31104c.png)

I'd like to play an animation with some map event generated in the running time, as usual, first I create it in the editor, and trace the underlying logic of the code so that I can reuse it directly. But this time, just out of my curiosity, it seems that `commandShowAnimation()` is not included in [`Game_Interpreter::ExecuteCommand()`](https://github.com/EasyRPG/Player/blob/97fb076e0efb40a4843332a21c5a3492c699f781/src/game_interpreter.cpp#L363).

So how can I play an animation on my own?

**Comment by Ghabry** [comment]
The function is here: https://github.com/EasyRPG/Player/blob/b8b1bb2f1f1ce4606192499dd5309f00efc386fd/src/game_interpreter_map.cpp#L556-L576

And could you please ask such questions from now on in our forum? https://community.easyrpg.org/

These are not issues or feature requests so they do not belong in the issue tracker. Thanks!
