### ISSUE TITLE
Gencache cannot detect translated assets

### ISSUE THREAD

**Issue by lychees** [EasyRPG/Player#2771]
Hi, I am helping ynoproject to translate their games into Chinese. 
But there is some trouble for me with translated assets.
It works fine locally, but cannot display the translated pictures in web server(Text is fine).

![image](https://user-images.githubusercontent.com/2507027/164284505-e6cf832f-af46-4dd8-b1b5-5b60fd0bc6cf.png)

![image](https://user-images.githubusercontent.com/2507027/164284289-646f9567-7675-4962-a2a1-dd360a2c9a3c.png)

![image](https://user-images.githubusercontent.com/2507027/164285211-c28eb733-e79e-45f3-ba6d-a2c5ab6e0f07.png)

So I think there must be some problem with gencache,(But since ynoproject is fine, so the bug must in my side.)
I used the nightly build gencache tool in [CI](https://ci.easyrpg.org/job/tools-win32/).

Here it is: https://test.w3itch.io/game/141
You can download the zip files to check it out.

**Comment by Ghabry** [comment]
Solution is likely this https://github.com/EasyRPG/Tools/issues/65

Please reopen if it does not help

**Comment by lychees** [comment]
It works. Thanks.
