### ISSUE TITLE
Fullscreen locked on Ubuntu Linux 21 and Wayland

### ISSUE THREAD

**Issue by mvpcortes** [EasyRPG/Player#2772]
Hi!,

I running easyrpg with my old rpg maker 2k game. But it lock in fullscreen and i cannot change to another window or close the game.

I using Ubuntu Linux 21 with Wayland.

I thing wayland is the problem because it is new on Ubuntu system.

att,
---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by Ghabry** [comment]
Hello. Do you use the debug build from our website or the package from OBS? (Also available in our download section).

The debug build is not fully supporting everything. You must install from OBS

**Comment by mvpcortes** [comment]
HI,

I will try using this version.

Thanks!

**Comment by carstene1ns** [comment]
Another option is the snap: https://snapcraft.io/easyrpg-player

Please reopen, if there are further problems.
