### ISSUE TITLE
Harvest Moon - A new Life: Ineluki Key Patch keyboard support is not work in web browser.

### ISSUE THREAD

**Issue by lychees** [EasyRPG/Player#2778]
Demo: https://w3itch.io/game/219 

Stucked in this step:
![image](https://user-images.githubusercontent.com/2507027/166888047-025fd547-35ed-4190-b959-d047b9d3c543.png)

It works fine when running locally, you can press F or G to skip the intro.

**Comment by carstene1ns** [comment]
It does not enable the scripts, because they are not found it seems.

```
Ineluki: Processing script list autorun.script [index.js:1:14328](https://api.w3itch.io/player/index.js)
sound/keylist.script.wav not in index.json index.js:1:14328
sound/miditickoutput.script.wav not in index.json [index.js:1:14328](https://api.w3itch.io/player/index.js)
sound/keysupporton.script.wav not in index.json index.js:1:14328
DL Failure: ./sound/KeyList.script.wav [index.js:1:14328](https://api.w3itch.io/player/index.js)
DL Failure: ./sound/MidiTickOutput.script.wav index.js:1:14328
DL Failure: ./sound/KeySupportOn.script.wav [index.js:1:14328](https://api.w3itch.io/player/index.js)
music/(aus) not in index.json index.js:1:14328
DL Failure: Music/(AUS) [index.js:1:14328](https://api.w3itch.io/player/index.js)
Cannot find: Music/(AUS)
```

**Comment by lychees** [comment]
![image](https://user-images.githubusercontent.com/2507027/166902195-af6ee3d9-f955-4899-bd06-1344bbe3922e.png)

Oh, it works. Thanks very much, it turned out to be there is some alphabet case mismatch in autorun.script, where in Windows is not case sensitive but Linus is.

**Comment by Ghabry** [comment]
This is kinda a bug but it will only affect the web player because the wrong file is requested. Don't really want to fix an edge-case only happening in a single file of a patch. Can be manually fixed before deploying the game.

On Linux it will work because the actual named is afterwards passed into FindFile.
