### ISSUE TITLE
Automatic placement of battlers

### ISSUE THREAD

**Issue by Zegeri** [EasyRPG/Player#278]
This is a RM2k3 feature that must be implemented.
Party members are placed automatically if BattleCommands.placement is False, but enemies are placed automatically if Troop.auto_alignment is True.

Open problems concerning placement are the automatic placements for battle modes in 2k3, e.g. first attack, pincer, ...

**Comment by fdelapena** [comment]
Are battlers placed in x=0, y=0 in these cases? I've found some games with this behaviour.

**Comment by Ghabry** [comment]
I actually started working on this feature some weeks ago. But during summer I prefer being outside instead of coding :).
Won't be ready before September.

**Comment by Ghabry** [comment]
I implemented auto placement for normal attack now.
Manual placement should also work, but there are some games like OFF that have manual placement but the Y-coordinate is 0...
RPG2k3 places it correctly in mid-battle but no idea where it gets the info from, the automatic coordinate is also 0

**Comment by Ghabry** [comment]
This is now semi-fixed by #851 
Open problems concerning placement are the automatic placements for battle moes in 2k3, e.g. first attack, pincer, ...

**Comment by fmatthew5876** [comment]
Some notes about enemy placement in RPG_RT

Normal:
- [x] Enemies are placed as specified in editor

Initiative:
- [x] Enemies are placed as specified in editor
- [x] Enemies face left on start of battle, message, then they turn right

Surround:
- [x] Enemies are placed in a fixed column in the middle of the battle field
- [x] Odd numbered enemies (starting from 1) face left
- [x] Event numbered enemies (starting from 1) face right
- [ ] Unsure how Y positions are decided, seems to change often and not yet identifiable pattern
- [x] looks really ugly with many enemies, they all end up onto of on another.
- [x] With 1 actor, this behaves like an initiative battle 
    - [ ] Does the battle condition type change?
    - [x] Force Flee on party with "ignore if surrounded" works in this case
- [x] With 2 or more actors, it's a surround battle
- [x] If battle screen placement flag is "manual" behaves like Initiative
    - [ ] Does the battle condition type change?
- [x] If battle screen placement flag is "manual" this is disabled in battle test but not in event box

Back:
- [x] Enemies are placed as specified in editor, but flipped to the other side
- [x] Actors start facing left, then immediately turn around

Pincer:
- [x] Odd enemies on the right, even enemies on the left
- [x] Enemies automatically placed in order of id from top to bottom, and fixed Y positions
- [x] If only 1 enemy, behaves like back attack
   - [ ] Does battle condition type change?
   - [x] Force Flee on party with "ignore if surrounded" works in this case
- [x] If battle screen placement flag is "manual" behaves like Initiative
- [x] If battle screen placement flag is "manual" this is disabled in battle test but not in event box

**Comment by fmatthew5876** [comment]
Enemy initial visibility seems to affect placement.

Slime, Slime, Ocotous
![3_enemies](https://user-images.githubusercontent.com/1198466/79054351-0dbd8080-7c12-11ea-8a66-5e8fd946a39b.png)

Slime, Slime(hidden), octopus
Also: Slime, Octopus
![enemy_2_hidden](https://user-images.githubusercontent.com/1198466/79054352-11510780-7c12-11ea-9773-63da7fae7e0b.png)

Slime, Slime(hidden), ocotpus, after slime is shown
![after_shown](https://user-images.githubusercontent.com/1198466/79054354-144bf800-7c12-11ea-979a-d0c0ca0e897d.png)

 - [ ] Also investigate enemy transformation. How does different image size affect position? Does it clamp?

**Comment by fmatthew5876** [comment]
Important Memory Addresses
====================

Here is a list of useful addresses in DynRPG RPG_RT binary

* `004be8e0` - `InitBattle()` function

This is one of the main battle startup work horses.  It does:

1. Set hidden flags on monsters, including handling of `Troop::appear_randomly`
2. Changes `surround` to `initiative` if conditions not met
3. Changes `pincer` to `back` if conditions not met
4. Sets monster positions manual / automatic / surround / pincer
5. Sets monster mirrored flag (direction facing)
6. Initializes monster atb gauge. 

* `004beb9b` - `GetMonsterX()`
* `0047ff14` - `GetMonsterY()`

These functions compute the monster X and Y positions given the terrain, battle condition, and party formation.

* `4CC16C`  - table of 64 doubles for computing x position from grid
* `4CC36C`  - table of 64 doubles for computing y position from grid
* `4CC76C` - table of 64 ints for computing x position from grid



I uploaded my Ghidra project for DynRPG here:
https://github.com/fmatthew5876/dynrpg-apps/tree/master/ghidra

Ghidra handles `InitBattle()` very well, but totally fails on the `GetMonsterX()` and `GetMonsterY()`. Luckily it give me enough hints and context I was able to follow the assmebly in x64dbg.

**Comment by fmatthew5876** [comment]
Heres an interesting edge case with manual placement
![manual_place](https://user-images.githubusercontent.com/1198466/79079578-06fc3f80-7cde-11ea-81e1-b96e54a972df.png)

If you place actors to the left of all the enemies they will turn around.

**Comment by fmatthew5876** [comment]
Some code related to row operation
```
int __usercall UpdateBattlerFlashAndShake@<eax>(RPG_Actor *a1@<eax>)
{
  RPG_Actor *v1; // ebx
  int v2; // edi
  int v3; // esi
  double v4; // st7
  int v5; // edi
  int v6; // esi
  int v7; // ebp
  int v8; // eax
  int result; // eax

  v1 = a1;
  if ( a1->battler.flashTimer > 0 )
    --a1->battler.flashTimer;
  a1->battler.flashIntensity = a1->battler.flashIntensity
                             - a1->battler.flashIntensity / (double)(a1->battler.flashTimer + 1);
  v2 = a1->battler.shakeTimer;
  if ( v2 <= 0 )
  {
    a1->battler.shakeOffsetX = 0;
    result = 0;
    v1->battler.shakeOffsetY = 0;
  }
  else
  {
    v3 = 2 * a1->battler.shakeStrength + 1;
    v4 = doubleFromInt(4 * v2 * (LOBYTE(a1->battler.shakeSpeed) + 2));
    v5 = doubleToInt(v4 * (double)v3);
    v6 = v1->battler.shakeSpeed * v1->battler.shakeStrength / 4 + 1;
    v7 = v1->battler.shakeOffsetX;
    v8 = max(v6 + v1->battler.shakeOffsetX, v5);
    v1->battler.shakeOffsetX = max_0(v7 - v6, v8);
    result = 0;
    v1->battler.shakeOffsetY = 0;
    --v1->battler.shakeTimer;
  }
  return result;
}
```

**Comment by fmatthew5876** [comment]
Direction changes by action
------------------------------

As far as I can tell, after initial battle setup, monsters never change direction.

Actors will change direction when targeting a single monster with an attack or skill. The pseudocode looks like this:

```
if (mirrored && monster.x < actor.x) {
  mirrored = false;
} else if(!mirrored && monster.x > actor.x) {
  mirroed = true
}
```

Actors will not change direction on using a target all skill, or an action which targets another party member.

**Comment by carstene1ns** [comment]
Do not forget #1564, it may interfere here.

**Comment by fmatthew5876** [comment]
That flag appears to only affect battle animations, so it should be orthogonal to this. Also looking at disassembly around the mirrored flag, I don't see that flag being referenced at all.
