### ISSUE TITLE
easyrpg-player: error while loading shared libraries: liblcf.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 1262917464** [EasyRPG/Player#2783]
I tried to build a player, but running it after the build was complete printed an error.
I've checked liblcf.so.0,this file exists in /usr/local/lib64.

OS:Fedora 29

(Please excuse me if I write strange English)

**Comment by carstene1ns** [comment]
`/usr/local/lib(64)` is not in the default search path on fedora.

Next steps depend on your use-case:
 - You can either rebuild liblcf with the `--prefix=/usr` option (this is autotools, for cmake use `-DCMAKE_INSTALL_PREFIX:PATH=/usr`)
 - You can bundle liblcf with Player (use `-DPLAYER_BUILD_LIBLCF=ON` cmake option), this only works if you do not plan to use any liblcf tools.
 - You can add `/usr/local/lib64` to the search path, though I would not recommend this option (see https://stackoverflow.com/a/54412406)

**Comment by 1262917464** [comment]
Thank you. I solved it
