### ISSUE TITLE
Set Move Route with Wait for movement: Turn 90° behaviour difference

### ISSUE THREAD

**Issue by TrunXGIT** [EasyRPG/Player#2790]
When you talk to a NPC/Event it automatically changes its facing direction towards the player.
Now if you use the Set Move Route command to turn it 90° left or right it behaves differently.

On **RPG_RT.exe:** It changes its direction relative to the current (changed) facing direction
Example GIF:
![Turn90_rpgrt](https://user-images.githubusercontent.com/23344806/169695654-4c2d15db-5f9b-4744-bbcf-cb989efa26b2.gif)

On **Player.exe:** It changes its direction relative to its original facing direction before the player interacted with the Event.
Example GIF:
![Turn90_player](https://user-images.githubusercontent.com/23344806/169695665-12445068-057f-4b68-b88f-2fbb8b33fd91.gif)

Move Route that was used int the examples:
![SetMoveRouteTurn90](https://user-images.githubusercontent.com/23344806/169695700-60ebf77f-2fa0-4b8f-83f9-63e8fe6d72a0.png)
(I even tried out a manual "Turn toward Player" at the very beginning, but the behaviour stays the same in both cases.)

I assume this could be a critical bug desyncing the games from its intended behaviour in cut-scenes. Resulting in just a visually different behavior in best case and bringing the game to a complete halt in worst case (if the "Skip If Cannot Move" checkbox is not ticked).

**Comment by Ghabry** [comment]
You found an edge-case here :)

RPG_RT.exe has both Facing and Direction.

In Player talking to an Event only updates the Facing but the Turning uses the Direction.
Have to check in which cases this value is copied into Direction when talking to an event...

**Comment by Ghabry** [comment]
Checked the RPG_RT implementation of talking to an event and this matches with ours.

This means something else triggers that Direction update. Will need some work to figure this out :/

**Comment by Ghabry** [comment]
At least ``Turn 180°, Move Forward`` will use the original facing direction as Player does. (I used 180° as this needs less thinking xD)

So it could be related to the jumping

**Comment by Ghabry** [comment]
@TrunXGIT  I need more context. The Move Route executes exactly like in RPG_RT.

The problem is something else. Please send the entire project.

**Comment by TrunXGIT** [comment]
Added the above mentioned move route without the jumping to a NPC and also a NPC with 180° (walk three steps aways from player and come back) to the sample project:
[MoveRouteTurnExample.zip](https://github.com/EasyRPG/Player/files/8861464/MoveRouteTurnExample.zip)

All three NPCs behave different in rpg_rt.exe compared to player.exe.

Player.exe is still using the initial facing direction as the starting point before the player interacted with the NPC.

**Comment by Ghabry** [comment]
The difference is the "Wait for All Movement" command. When the command is missing it behaves like Player. o_O
