### ISSUE TITLE
No option to go into windowed mode at all! This applies to all games as-well 

### ISSUE THREAD

**Issue by N00dlesandwitch** [EasyRPG/Player#2799]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Macos

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by Fishaphrodite** [comment]
Use --window as an argument when launching it, or push alt+enter once it is launched. Unless you mean something else?

You could have filled the last part of the template to describe the exact problem to ensure it's not just what I'm describing.

**Comment by Ghabry** [comment]
Or press F4 to toggle between Window and Fullscreen

**Comment by carstene1ns** [comment]
Please reopen, if the problem persists.
