### ISSUE TITLE
Android: Check if SAF-Folders can be opened with fdopendir (+ Performance)

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2803]
We do this already for file reading so is worth checking. Could give a nice speedup compared to ``resolver.query``.

According to this stackoverflow post it should work until Android 10: https://stackoverflow.com/questions/69075070/android-11-saf-native-fdopendir-readdir-dont-show-full-files-list

So still a good fallback on older systems maybe? c1 reported terrible performance on his system.

**Comment by carstene1ns** [comment]
Interestingly enough, disabling RTP support makes loading nearly instant again, 3 seconds. RTP scanning adds over 20 seconds!

**Comment by Ghabry** [comment]
Not relevant anymore. #2804 solves the real problem.
