### ISSUE TITLE
WebPlayer throws multiple errors whenever something is typed on the Browser's Console.

### ISSUE THREAD

**Issue by jetrotal** [EasyRPG/Player#2806]
#### Name of the game:
Every Game.

#### Player platform:
WebPlayer(emscripten)

#### Attach files (as a .zip archive or link them)
Most recent builds of the WebPlayer
testing players from https://easyrpg.org/play/pr2779/
to https://easyrpg.org/play/master/

#### Describe the issue in detail and how to reproduce it:
Usually I use the Browser's Console to implement and debug stuff on the webplayer.

After updating it to a recent version, every time I type something on the console, it points to an generic error:
![image](https://user-images.githubusercontent.com/45118493/173125570-80cd13ef-f391-478f-a707-0e430aff89bf.png)

-----------------------------------

Looks like the errors are related to the list of variables that the console input generates...?

![image](https://user-images.githubusercontent.com/45118493/173125668-6096e31d-4188-4ced-9d8e-986e1c1ff677.png)

 - If I type ";" or "i" the error does not happens. 

 - When typing "i", if I move down to "If", it throws an error...

It seems like it happens whenever that list can't find a variable:

 - "i" does not produce an error, because the list points to a var named "i" on the page.

 - "M" produces an error, because the list points to "Map" which is a generic function.

 - "Mo" does not produces an error, it points to the var "Module".

-----------------------------------

The error happens before the wasm is loaded. Would it be exclusive to the index.js file?

maybe the console is walking through the entire index.js and hitting something problematic on that ?

---------------------------------- 

Right now, i'm using this dirty fix:
If the error is an order to check the console, it wont appear on the console, just on the status div. 

```javascript
Module.printErr = (...args)=>{
     if (args[0] === '[post-exception status] Exception thrown, see JavaScript console…') return;
        console.error(...args);
    }
```
Maybe adding a "dismiss" button on the status texts that appears on top could also help on this dirty fix.

------------------------

The root of the problem may be closer to this function, tho:
```javascript
window.addEventListener("error", ()=>{
    Module.setStatus("Exception thrown, see JavaScript console…");
    Module.setStatus = (text=>{
        if (text)
            Module.printErr(`[post-exception status] ${text}`)
    }
    )
}
);
```

I don't know what happened to make the window detect changes on the console input as errors...

Sam, from discord, is facing the same issues since he updated his repo:
https://github.com/ynoproject/ynoclient/commit/ae7a33d8d584ab1d3ca578b00a17be24c0d9260e

Maybe it is a good source to check diff at index.js...?

---------------------------

The issue seems harmless, nothing else on the player changes.
But it's very annoying to write code on the console, while it's throwing erros every time you type something.
Thanks in advance!

--------------------------

OK, update:

![image](https://user-images.githubusercontent.com/45118493/173132281-8c9fe64e-3cdc-44c5-81dc-647d48c3b891.png)
The error does not happen on the beta builds of chrome, it is a browser related error 😑

**Comment by carstene1ns** [comment]
Upstream bug, can be worked around (by checking `event.defaultPrevented`)

https://stackoverflow.com/a/72402135
