### ISSUE TITLE
Building Player on Windows

### ISSUE THREAD

**Issue by 1262917464** [EasyRPG/Player#2810]
Hi,I tried to build a player on Windows now,but got the following messages after run `cmake --build .`
[https://github.com/EasyRPG/Player/blob/master/docs/BUILDING.md](url)

`  EasyRPG_Player.vcxproj -> D:\Player-0.7.0\Player-0.7.0\Debug\EasyRPG_Player.lib
    正在创建库 D:/Player-0.7.0/Player-0.7.0/Debug/Player.lib 和对象 D:/Player-0.7.0/Player-0.7.0/Debug/Player.exp
LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe
.vcxproj]
EasyRPG_Player.lib(game_enemy.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArrayA
lloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(scene_save.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArrayA
lloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(scene_import.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArra
yAlloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(scene_file.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArrayA
lloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(game_interpreter_map.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf
::DBArrayAlloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxp
roj]
EasyRPG_Player.lib(game_event.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArrayA
lloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(game_vehicle.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArra
yAlloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(game_commonevent.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DB
ArrayAlloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(translation.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArray
Alloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(lcf_data.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArrayAll
oc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(game_character.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBAr
rayAlloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(game_interpreter.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DB
ArrayAlloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(player.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArrayAlloc
::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(filefinder.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArrayA
lloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(game_player.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArray
Alloc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
EasyRPG_Player.lib(game_map.obj) : error LNK2001: 无法解析的外部符号 "private: static unsigned int const * const lcf::DBArrayAll
oc::_empty_buf" (?_empty_buf@DBArrayAlloc@lcf@@0QBIB) [D:\Player-0.7.0\Player-0.7.0\EasyRPG_Player_exe.vcxproj]
D:\Player-0.7.0\Player-0.7.0\Debug\Player.exe : fatal error LNK1120: 1 个无法解析的外部命令 [D:\Player-0.7.0\Player-0.7.0\EasyRPG
_Player_exe.vcxproj]`

I don't know what happened and how to solve it.

**Comment by Ghabry** [comment]
Building on Windows is a bit more tricky. See here: https://github.com/EasyRPG/buildscripts/tree/master/windows

If you do not want to wait for the vcpkg build you can get a precompiled vcpkg from here: https://ci.easyrpg.org/view/Toolchains/job/toolchain-windows/

**Comment by 1262917464** [comment]
> Building on Windows is a bit more tricky. See here:https://github.com/EasyRPG/buildscripts/tree/master/windows
> 
> If you do not want to wait for the vcpkg build you can get a precompiled vcpkg from here:https://ci.easyrpg.org/view/Toolchains/job/toolchain-windows/

I have finished this.Now is the build exe error.

**Comment by Ghabry** [comment]
You executed ``cmake -DSHARED_RUNTIME=OFF -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=[VCPKG_PATH]\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug`` and get this error?

How did you compile liblcf? If you compile it manually you must add ``-DBUILD_SHARED_LIBS=OFF``. The DLL does not work on Windows.

Alternatively the easiest way is adding this to the Player CMake: ``-DPLAYER_BUILD_LIBLCF=ON``. Then Player will build liblcf for you.

**Comment by 1262917464** [comment]
I tried `-DBUILD_SHARED_LIBS=OFF,` it succeeded, thank you!
