### ISSUE TITLE
Andoird: FF strange behaviour

### ISSUE THREAD

**Issue by zell180** [EasyRPG/Player#2830]
Name of the game: indipendent from the game
Player platform: Android

Using Fast Forward (FF) on Android Player have strange behaviour, i use FF in mode "keep pressed" and:
1) if i push FF and keep it pressed and then i push UP, UP not work and RIGHT become UP (DOWN works well)
2)  if i push FF and keep it pressed if i push A,B or other button then FF stop work

**Comment by Ghabry** [comment]
Works for me. Thats all I can say about this. :/

Can hold FF, move upwards and at the same time open the menu. All works.
