### ISSUE TITLE
Add "Actor's name is (name)" as an element who can be translated

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2831]
---
#### Name of the game:
Yume 2kki, though it can happens for every games.

#### Player platform:
Windows, latest EasyRPG Build, po files generated with the latest lcftrans build.

Due to the fact that Actor's name is not a translatable element yet, things like this happens (example with Yume 2kki for the English translation):
![image](https://user-images.githubusercontent.com/108797333/185131309-cd0af2f7-8e15-42d4-b87b-f3ae80d201da.png)
In a loop, "Change Actor's name" is translated (so うろつき -> Urotsuki), but the loop is programmed to break only if the player's name is うろつき, and since it's not an element who can be translated, the loop will never end:
![image](https://user-images.githubusercontent.com/108797333/185131518-bc352929-319e-4e20-a573-46024c256d38.png)

General example if you want to try:
![image](https://user-images.githubusercontent.com/108797333/185135427-a56a65d3-0f22-4a29-9c75-7ab6e8e8570c.png)
With a loop like this, generate .po files for translation and replace Hello by anything.

**Comment by Ghabry** [comment]
Not really a feature request, more a corner case we missed. :/

Thanks for the report, this shouldn't be hard to fix.
