### ISSUE TITLE
EasyRPG Player fails to link

### ISSUE THREAD

**Issue by Derailedzack** [EasyRPG/Player#2834]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
N/A
#### Player platform:
Windows, Linux, Android, ...
Fedora 36
#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
```
make  all-am
make[1]: Entering directory '/home/shadowfoxy32/Downloads/player'
  CXXLD    easyrpg-player
/usr/bin/ld: error: /usr/local/lib/: read: Is a directory
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:2051: easyrpg-player] Error 1
make[1]: Leaving directory '/home/shadowfoxy32/Downloads/player'
make: *** [Makefile:1513: all] Error 2
[shadowfoxy32@fedora player]$ sudo make install
[sudo] password for shadowfoxy32: 
  CXXLD    easyrpg-player
/usr/bin/ld: error: /usr/local/lib/: read: Is a directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:2051: easyrpg-player] Error 1
```
#### Describe the issue in detail and how to reproduce it:
The EasyRPG fails to link
1. Build EasyRPG player
2. Run make
3. Observe linker error

**Comment by carstene1ns** [comment]
Can you please run `make V=1`, we need the whole linker command.
I suspect there is some stray string, that messes this up (e.g. from pkg-config or something).

**Comment by Derailedzack** [comment]
```
make  all-am
make[1]: Entering directory '/home/shadowfoxy32/Downloads/player'
[ -f .version-append ] || touch .version-append
echo "(2022-08-20)" | cmp -s .version-append - || echo "(2022-08-20)" > .version-append
[ -f .version-git ] || touch .version-git
./builds/autoconf/git-version.sh > .version-git-t
cmp -s .version-git .version-git-t && rm .version-git-t || mv .version-git-t .version-git
g++ -std=c++14 -fno-math-errno -I./src  -I/usr/include/pixman-1  -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread -I/usr/include/freetype2 -I/usr/include/libpng16  -I/usr/include/SDL2 -D_REENTRANT  -I/usr/include/libpng16      -I/usr/include/opus   -I/usr/include/opus       -pthread -g -O2   -o easyrpg-player src/platform/sdl/easyrpg_player-main.o libeasyrpg-player.a libplayer-version.a /usr/local/lib/ -lpixman-1  -lfreetype  -lharfbuzz  -pthread -lSDL2  -lpng16 -lz  -lz  -lmpg123  -lWildMidi  -lvorbisfile -lvorbis  -lopusfile  -lfmt  -lsndfile  -lxmp  -lspeexdsp    -lasound  -lpthread 
make[1]: Leaving directory '/home/shadowfoxy32/Downloads/player'
```

**Comment by Derailedzack** [comment]
I have liblcf installed in two different locations. One in /usr/ the other is in /usr/local/

**Comment by carstene1ns** [comment]
Did you specify the liblcf path manually? `-llcf` is missing from the command line, instead there is only the directory, where LD gets confused (link directories need `-L` option to work correctly).

Please post the output of `grep LCF_LIBS config.log` (in Player source directory).

**Comment by Derailedzack** [comment]
```
ac_cv_env_LCF_LIBS_set=set
ac_cv_env_LCF_LIBS_value=/usr/local/lib/
pkg_cv_LCF_LIBS=/usr/local/lib/
LCF_LIBS='/usr/local/lib/'
```

**Comment by carstene1ns** [comment]
You either need to correctly specify the option or let pkg-config handle that for you.
`LCF_CFLAGS="-I/usr/local/include" LCF_LIBS="-L/usr/local/lib -llcf" ./configure && make`
or `PKG_CONFIG_PATH=/usr/local ./configure && make`
