### ISSUE TITLE
AZERTY Keyboard support does not work for web versions

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2841]
Please fill in the following fields before submitting an issue:
#### Name of the game:
Easy RPG test games and several Yume Nikki type of game.

#### Player platform:
Windows, both test game from Easy RPG and YNO Project.

#### Describe the issue in detail and how to reproduce it:
Unlike playing with the .exe Easy RPG Player, Z and W key, A and Q (and probably some others I'm missing) are not reversed to match with a french keyboard. Not sure if it's done due to a technical limitation or not.

**Comment by Ghabry** [comment]
This is a bug in SDL that should be resolved soon https://github.com/libsdl-org/SDL/issues/2098#issuecomment-1263490770

**Comment by Ghabry** [comment]
The fix is in but we must wait now for the next SDL2 release (2.26). Hopefully comes in a month or two.

Then a recompile should fix it :)

**Comment by Ghabry** [comment]
Tested it now: Pressing Z on German keyboard gives Y (matching the scancode), so this is indeed fixed.
