### ISSUE TITLE
More video options.

### ISSUE THREAD

**Issue by CortexReaver** [EasyRPG/Player#2843]
As in title. Resolutions such as:
320x240 (the default one I believe), 640x480, 960x720 1280x960 and same for fullscreen (maybe?)

**Comment by carstene1ns** [comment]
Currently you can cycle through them with <kbd>F5</kbd> key.

Do you want to have this configurable (settings scene could handle this) or as command line option?

**Comment by CortexReaver** [comment]
A tab in start menu named "Video Options" with list of corresponding resolutions. Don't know yet about command line options, because I am more a "visual person".
If it remembers your choice everytime you restart the player - then you don't need them, otherwise yes. Ini file will work as well.

**Comment by CortexReaver** [comment]
I have some requests related to video options, but I don't want to create a mess in "issues" list.
Borderless window mode (by a key combination and as a checkbox in options) and "fit window to a current game resolution" (by a key combination).

**Comment by Ghabry** [comment]
I'm tagging this as fixed by #2730 

That PR will add features like remember the window position, if it is fullscreen or windowed and also has stuff like "scale to nearest integer resolution" etc.

**Comment by CortexReaver** [comment]
I'm tested nightly builds of RPG player and options are looking and working great, but it still needs a "fit\lock window proportions to a game area" option. So window proportions will be locked, disallowing you to stretch it horizontally wider then the game area itself (like in Wolf PRG engine).
