### ISSUE TITLE
[Feature request] Sound volume options.

### ISSUE THREAD

**Issue by CortexReaver** [EasyRPG/Player#2844]
Either a visual UI element represented as a slider, or command line option will work as long as it saves its state.
And if possible to make separate options for music and FX - would be really cool.

**Comment by jetrotal** [comment]
It's planned to be implemented on the next updates, more details here: #2730

![image](https://user-images.githubusercontent.com/45118493/189188645-f598888a-e7b3-4412-9e2d-be8e0b6440b4.png)
