### ISSUE TITLE
Can you increase the stat,health and ki  limited of easyrpg emulator 

### ISSUE THREAD

**Issue by Jackiechun63374** [EasyRPG/Player#2847]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by Ghabry** [comment]
Yes. The Player supports custom LDB database entries to modify these limits.

However there is no simple way to set them because our editor is still not ready :sweat_smile: 

You can use tools like ``lcf2xml`` to manually modify them. E.g. ``easyrpg_max_actor_hp`` is for setting the actor HP limit.
