### ISSUE TITLE
Support for Cherry's CommonThisEventPatch

### ISSUE THREAD

**Issue by SasikaAT** [EasyRPG/Player#2850]
Long time ago I abandoned my RPG Maker 2000 project, because it got pretty complex and I had to do the same edits hundreds of times in different very similar events sharing very big parts of code which was very demotivating.

Recently I came across @CherryDT CommonThisEventPatch for RPG Maker 2000, which would allow me to do said edits just once in a common event and then use that common event in all of the events that use the same code. So my motivation is back to continue and finish my RM2000 project that I started over 15 years ago.

Problem is that using the rpg_rt.exe on windows 10 (even the unpatched original one) is not a nice experience anymore as it judders a lot more (<30fps?) than back in Windows XP times.

EasyRPG is the solution for the judder problem! Thanks for this great cross platform interpreter! :)

Any chance that EasyRPG will support Cherrys ThisEvent Patch?
(Ideally without the need of the patched .exe being present as I want to avoid that the players start the wrong .exe by accident.)

Maybe check for a CommonThisEvent.dat file in the game directory to unlock that feature?

**Comment by Ghabry** [comment]
This is almost the same as #2766 . Closing this as dupe
