### ISSUE TITLE
ib恐怖美术馆中文汉化出现问题，输入键里缺少“深”和“之”

### ISSUE THREAD

**Issue by qymqsd97** [EasyRPG/Player#2851]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by Ghabry** [comment]
This is a known problem (see https://github.com/EasyRPG/Player/issues/2656). There is currently no fix for this. Sorry.

这是一个已知的问题（见https://github.com/EasyRPG/Player/issues/2656）。目前还没有解决这个问题的办法。对不起。
