### ISSUE TITLE
Use Android Audio Api

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#286]
Instead of SDL_Mixer the Audio API of Android could be used (with fallback to SDL_mixer for unsupported formats)

https://developer.android.com/guide/appendix/media-formats.html
Supports MP3, MIDI, Vorbis, PCM/Wave

Library for playback: (Needs Api Level 1, we are 9)
https://developer.android.com/reference/android/media/SoundPool.html

Supports Volume, Playback Rate and Left/Right Volume
Unsupported: Seek

**Comment by fdelapena** [comment]
Is this still worth to do after the latest backported wave patches?

**Comment by Ghabry** [comment]
Probably not. Closing.
