### ISSUE TITLE
Some players encounter a permament fast forward.

### ISSUE THREAD

**Issue by nahro1001** [EasyRPG/Player#2869]
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows
[FastForward_Exe_log.zip](https://github.com/EasyRPG/Player/files/10136005/FastForward_Exe_log.zip)

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game) -> No Savegame needed the eventing itself seems to be working A -ok
 - The `easyrpg_log.txt` log file (you can find it in the game directory) -> see attached zip

#### Describe the issue in detail and how to reproduce it:
It's hard to reproduce, one of my Beta Testers has reported that his EasyRPG Player is stuck on the x3 Fast Forward constantly. He can press the button to fast forward to x10, but the F key does not remove the state.

He has tried to reinstall and multiple restarts but it's just there - and I couldn't find any other precedence for me. I and another Beta Tester can play the game just fine with the executable provided.

Please let me know if more information is needed and I will gladly provide what I can.

**Comment by Ghabry** [comment]
My guess is a bogus gamepad ``Controller 0 (HJC Game GAMEPAD) added``

Try disconnecting it

**Comment by nahro1001** [comment]
I'll try as soon as the tester is awake again :D thanks! I missed this

**Comment by nahro1001** [comment]
Absolutely was the controller! Thank you <3
