### ISSUE TITLE
Support Custom Resolution

### ISSUE THREAD

**Issue by BlisterB** [EasyRPG/Player#2873]
Configuration:
- [x] Read the resolution to apply somewhere (ex. .ini like with Maniac Patch)

Menus:
- [x] Game Browser (should be fine with full stretch?)
- [x] Startup
- [x] Main Menu
- [x] Items
- [x] Skills
- [x] Equipment
- [x] Status
- [x] This dumb reorder scene nobody uses
- [x] Save/Load
- [x] Name input (Change Hero Name)
- [x] Debug
- [x] End Game
- [x] Shop

Battles:
- [x] Battle 2000
     - [X] UI
     - [x] Animation
     - [x] Background
     - [X] Monsters
     - [x] Cursor
- [x] Battle 2003
     - [X] UI
     - [x] Animation
     - [x] Background
     - [X] Monsters
     - [X] Heroes
     - [x] Cursor

Maps:
- [x] Map (Message Box & Gold)
- [x] Map (Screen Pan)
- [x] Map (Weather Effects)
- [x] Map (Correct Panorama rendering)
- [x] Map (Correct Picture offsetting)
- [x] Battle animations

Other : 
- [x] Weather: Check if density of particules is the same with rain/snow/sandstorm
- [x] A "legacy" mode could be implemented for centering picture in older games.
- [x] Add a vertical margin for MessageBox when height > 240 px

**Comment by BlisterB** [comment]
Looping Panoramas does seem to work
![image](https://user-images.githubusercontent.com/2387475/208268268-a1a40c70-f8d4-4788-927c-9650df53dc42.png)

**Comment by Ghabry** [comment]
@BlisterB Did you forget to update the checklist or is something still missing?

**Comment by BlisterB** [comment]
> It's all good 👍
