### ISSUE TITLE
Show Picture: Image invisible when map & battle layer are disabled

### ISSUE THREAD

**Issue by BlisterB** [EasyRPG/Player#2874]
I've migrated my project to EasyRPG, and I noticed that Show Picture are not displayed.

Here's an example:
- Start a new game
- A blue custom message box is displayed with RPG_RT, but not with Player (EasyRPG)

Please note that this problem is not linked with the widescreen support, as it also appears with base resolution.

The common event that trigger the Show Picture is "88 Affichetexte".

![image](https://user-images.githubusercontent.com/2387475/208321542-76c753fc-d8dd-40aa-9751-26133a142032.png)
![image](https://user-images.githubusercontent.com/2387475/208321618-64f2b44a-1afd-4f54-89c5-3a618fb9d65f.png)

A link to the game, you can find RPG_RT and Player (EasyRPG) inside:
https://e1.pcloud.link/publink/show?code=XZrz6YZvuWBKUQcYgJWvbbboMBvy50if41X

[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/10254712/easyrpg_log.txt)

**Comment by Ghabry** [comment]
The checkbox for "Show On Map" and for "Show On Battle" are unchecked so the Player does exactly this: It is invisible.

![image](https://user-images.githubusercontent.com/1331889/208322896-23ba74b7-5268-4364-925e-006a8b26905f.png)

Though seems that RPG_RT automatically changes the map layer to ``7`` in that case.

@CherryDT do you remember if you implemented a fail-safe here that resets the map layer to 7 when both map and battle layer are disabled (0)? Asking is faster than starting up the dissasembler xD.

**Comment by CherryDT** [comment]
I did but I don't remember if it's on 0/0 or on lower parameter count only.

**Comment by Ghabry** [comment]
well this one is simple, too:

```cpp
diff --git a/src/game_pictures.cpp b/src/game_pictures.cpp
index 82d52946..5163f0cc 100644
--- a/src/game_pictures.cpp
+++ b/src/game_pictures.cpp
@@ -205,6 +205,11 @@ bool Game_Pictures::Picture::Show(const ShowParams& params) {
        data.spritesheet_speed = params.spritesheet_speed;
        data.map_layer = params.map_layer;
        data.battle_layer = params.battle_layer;
+
+       if (data.map_layer == 0 && data.battle_layer == 0) {
+               data.map_layer = 7;
+       }
+
        data.flags.erase_on_map_change = (params.flags & 1) == 1;
        data.flags.erase_on_battle_end = (params.flags & 2) == 2;
        data.flags.affected_by_tint = (params.flags & 16) == 16;
```
