### ISSUE TITLE
[Documentation] Update Wiki for Windows/VS build to point at a forum post that's more up to date

### ISSUE THREAD

**Issue by silbinarywolf** [EasyRPG/Player#2877]
#### Describe the issue in detail and how to reproduce it:

For somebody like me with little experience in C or C++, compiling on Windows and trying to figure that side of things out can be a bit of a headache.

However, I was finally able to get things working by following this very simple and straight-forward guide here:
https://community.easyrpg.org/t/guide-how-to-build-easyrpg-player-on-windows/1174

I propose that the wiki be updated on this page to simply link to that guide as it's currently the first Google search result (at least for me)
https://wiki.easyrpg.org/development/compiling/player/windows/visual-studio

It would be arguably better for the guide to just live on that page IMO, but I'm requesting what I'm assuming is the lowest effort solution to helping folks get unstuck.

**Comment by carstene1ns** [comment]
We plan to deprecate the wiki and integrate such essential guides in the homepage.

Updated the page for now. Thank you for the heads up.
