### ISSUE TITLE
How to support new keyboard keys?

### ISSUE THREAD

**Issue by lychees** [EasyRPG/Player#2884]
How to add new keyboard keys and how to modify the keys for some functions? For example, I'm adding a fast forward play function like in a traditional Galgame player, usually this key corresponds to Left Ctrl, but there is no such key in the current list of constants.

![image](https://user-images.githubusercontent.com/2507027/215199446-b9f65382-b237-478a-b66a-bcbb03e760b0.png)

**Comment by Ghabry** [comment]
There is ``Keys::LCTRL`` which corresponds to left control.

To read this key directly you can use ``Input::IsRawKeyPressed`` or create a new ``Button`` and use ``Input::IsPressed``.

**Comment by lychees** [comment]
It works.
<code>
void Window_Message::WaitForInput() {
	if (Input::IsTriggered(Input::DECISION) ||
			Input::IsTriggered(Input::CANCEL) ||
			Input::IsRawKeyPressed(Input::Keys::LCTRL)) {
		SetPause(false);
	}
}
</code>
But it is not work for <code>Input::Keys::CTRL</code>, 
(I am afraid this is a bug, it might need some additianal check to handle this case.)

**Comment by Ghabry** [comment]
Hm ``CTRL`` and similar could be notified through a check in ``Input`` but this will likely break stuff like the upcoming remapping scene when one key triggers multiple presses.

I will likely remove ``CTRL`` completely and only use ``L/RCTRL``

**Comment by lychees** [comment]
Understood.
