### ISSUE TITLE
[Windows] Music (possibly MIDI) playback is garbled

### ISSUE THREAD

**Issue by DipeshAggarwal** [EasyRPG/Player#2888]
#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/10577673/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
As soon as you launch the game, the music plays and it sounda a bit garbled, like some noise has been added to it and also, it is a bit slowed,
Some of the UI sounds also suffer from the same sound garbling but most of the music plays fine.

Link to download the game: https://laxiuspower-shrine.rpg-board.net/t362-laxius-power-1-to-3-download-link

**Comment by Ghabry** [comment]
Do you use the continuous build? (available from the bottom of the download page)

Does this only affect Laxius Power or also other games?

Could you record some of the audio and upload it so we have a comparison of Player vs. RPG_RT? We are not aware of such audio issues yet, so this would be good to consider if this is a problem with your system or a general problem.

**Comment by DipeshAggarwal** [comment]
> Do you use the continuous build? (available from the bottom of the download page)

I used both the stable and the continous build.

> Does this only affect Laxius Power or also other games?

I only tried it on Laxius Power 1 and 2. Issue is in both the games.

> Could you record some of the audio and upload it so we have a comparison of Player vs. RPG_RT? We are not aware of such audio issues yet, so this would be good to consider if this is a problem with your system or a general problem.

I had a friend try it on their PC and it works fine for them so it could just be an issue with my system. Are there any steps I can take to debug the problem?

**Comment by DipeshAggarwal** [comment]
It fixed itself. I don't know how but when I installed Audacity to record my system audio, and launched the game, the sound started working perfectly.

Even after closing audacity, it's working.
