### ISSUE TITLE
Continuous build: Set Parallax not working as intended

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2889]
#### Name of the game:
EasyRPG Player Test Game 2000.

#### Player platform:
Windows, continuous build of EasyRPG Player (this issue is not present in version 0.7.0 or in the[ Online version of the TestGame](https://easyrpg.org/play/)).

#### Attach files (as a .zip archive or link them)
[Save01.zip](https://github.com/EasyRPG/Player/files/10611801/Save01.zip)

#### Describe the issue in detail and how to reproduce it:
![image](https://user-images.githubusercontent.com/108797333/216837364-44cde875-af3e-4793-bafd-9df8850bbe06.png)
![image](https://user-images.githubusercontent.com/108797333/216837461-3f762a82-fe5d-428d-ac55-4ecce38612bf.png)

If you are loading the savefile, just interact with the npc in front of you. Alternatively, you can manually go in _Map Events -> Panorama -> Panorama (looping map)_ and interact with the npc shown on the screenshots.

The panorama will be normal in the version 0.7.0 or in the RPG_RT, but seems to be moved a bit to north-west in the continuous builds.

I guess this may have been caused by the pull request #2714 though I can't confirm this.

**Comment by Ghabry** [comment]
@Mimigris 

Somehow I cannot reproduce this. Maybe I do something different because I just rush through your issues for an initial overview.

For me the Panorama is at the correct position.

Can you check if the engines match for you because the Panorama handling is different between 2k and 2k3.

(command line arg is ``--engine 2k``/``--engine 2k3``.

**Comment by Mimigris** [comment]
> Can you check if the engines match for you because the Panorama handling is different between 2k and 2k3.
> 
> (command line arg is `--engine rpg2k`/`--engine rpg2k3`.

I have the same result with the setting 2k, 2k3 or without it (it's not an issue with the command, the main menu has different items when I try to check 2k games with 2k3 settings and the opposite).
If you are trying from the Test Game, make sure to go on the looping map and not the default map for the Panorama test since it does not occur on the default map.

**Comment by Ghabry** [comment]
Reproduced it now: This is only broken when on the non-looping map no panorama is set.

When the non-looping has a panorama then on the looping the position is correct. o_O

**Comment by Ghabry** [comment]
I think it is enough to always reinit the Panorama when it is "nothing" initially:

```diff
diff --git a/src/spriteset_map.cpp b/src/spriteset_map.cpp
index a6f8c887b..fb9245717 100644
--- a/src/spriteset_map.cpp
+++ b/src/spriteset_map.cpp
@@ -144,11 +144,7 @@ void Spriteset_Map::ParallaxUpdated() {
 	std::string name = Game_Map::Parallax::GetName();
 	if (name != panorama_name) {
 		panorama_name = name;
-		if (name.empty()) {
-			panorama->SetBitmap(BitmapRef());
-			Game_Map::Parallax::Initialize(0, 0);
-		}
-		else {
+		if (!name.empty()) {
 			FileRequestAsync* request = AsyncHandler::RequestFile("Panorama", panorama_name);
 			request->SetGraphicFile(true);
 			request->SetImportantFile(true);
@@ -156,6 +152,11 @@ void Spriteset_Map::ParallaxUpdated() {
 			request->Start();
 		}
 	}
+
+	if (name.empty()) {
+		panorama->SetBitmap(BitmapRef());
+		Game_Map::Parallax::Initialize(0, 0);
+	}
 }
 
 void Spriteset_Map::SystemGraphicUpdated() {
```

but I have to retest everything to verify this doesn't break anything.
