### ISSUE TITLE
Question about dynrpg

### ISSUE THREAD

**Issue by th0rig** [EasyRPG/Player#2895]
#### Player platform: Android
I wonder if dynrpg possible in EasyRpg any plan to add DynRpg iin the future? Or this is something impossible to add? Game that use DynRpg for example is Final Fantasy Blackmoon Prophecy joiplay somehow support games that use umm Timeplay counter maybe that tell you how long you play the game i don't know if RpgMaker XP and UP still use DynRpg or they have different approach to achieve same feature. Btw tanks for tthe software

**Comment by Ghabry** [comment]
This is not a support forum. If you have question post them in our community: https://community.easyrpg.org/

In short: DynRPG support is not possible because we are not an emulator and DynRPG is very low level. So we are fundamentally incompatible to it.

**Comment by th0rig** [comment]
Thanks for the answer too bad if that not possible
