### ISSUE TITLE
Despoina softlocks when Blind Strike ability is used in Auto mode

### ISSUE THREAD

**Issue by wertercatt** [EasyRPG/Player#2896]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform: Wii
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log
[Save01.zip](https://github.com/EasyRPG/Player/files/10746412/Save01.zip)

[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/10746408/easyrpg_log.txt)
 file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
When a character uses 'Blind Strike' in battle after pressing Auto, the character just endlessly walks at the enemy with no animation playing. According to the developer, this isn't an issue they've seen before, so it's likely EasyRPG's issue. In the attached savefile, just walk into the glowing orbs and press 'Auto,' you should see the softlock relatively quickly.

**Comment by Ghabry** [comment]
EDIT: Looked at the wrong skill...

The problem is likely the Idle pose which results in an endless animation loop without considering the battler "idling":

![image](https://user-images.githubusercontent.com/1331889/221355088-941c785d-010e-4e86-b3f1-8da8b7c11034.png)

**Comment by Ghabry** [comment]
Getting rid of many small bugs :)

```diff
diff --git a/src/scene_battle_rpg2k3.cpp b/src/scene_battle_rpg2k3.cpp
index 5ecac8f20..bb8c4cbb9 100644
--- a/src/scene_battle_rpg2k3.cpp
+++ b/src/scene_battle_rpg2k3.cpp
@@ -2316,6 +2316,8 @@ Scene_Battle_Rpg2k3::BattleActionReturn Scene_Battle_Rpg2k3::ProcessBattleAction
 							action_state,
 							Sprite_Actor::LoopState_WaitAfterFinish);
 				}
+			} else {
+				sprite->SetAnimationLoop(Sprite_Actor::LoopState_DefaultAnimationAfterFinish);
 			}
 		}
 	}
```
