### ISSUE TITLE
How to add support to a new platform?

### ISSUE THREAD

**Issue by donmor** [EasyRPG/Player#2898]
#### Player platform:
loongarch64-unknown-linux-gnu, Arch Linux

#### Describe the issue in detail and how to reproduce it:

I managed to build liblcf and easyrpg-player on a new architecture in qemu. Both are version 0.7.0
- Download the two tarballs and extract them
- Patch the config.sub, adding a 'loong64 | loongarch64' line
- run `./configure --build=loongarch64-unknown-linux-gnu && make && make install` in liblcf and then easyrpg-player directory
- run `easyrpg-player` if /usr/local/bin is in $PATH.

Now I want yo know how to make a patch on the upstream repository so that we can simply `./configure && make && make install` on the new architecture, or for better, all future architectures running GNU/Linux respecting LSB.

**Comment by Ghabry** [comment]
Hi, I ran ``autoreconf -fi`` in the git repository using the latest Arch Linux and the ``config.guess`` contains support for ``loongarch64``.

So it seems autotools already supports this which means it will just work when we release the next tarball for 0.7.1 / 0.8.0.

**Comment by donmor** [comment]
Oh. That's really cool.

**Comment by Ghabry** [comment]
this will be fixed in the 0.8 tarball
