### ISSUE TITLE
Maniac Patch: Key Input Proc EX always 1

### ISSUE THREAD

**Issue by TitanKaempfer** [EasyRPG/Player#2899]
**Name of the game:** KeyInputEXProblem-Example
**Player platform:** Windows, continuous build of EasyRPG Player
**Issue:**
Currently working on a project and I'm always checking it's compability with the current EasyRPG builds. While working on the battle system, I noticed that maniac patch's Key Input Proc Ex always returns 1 to the variable assigned in EasyRPG, while it does not when run normally.

I included a small example project.
Just talk to the NPC (she activates the switch for a parallel process), and press "W" on the keyboard. In the normal .exe it will only show a message box when "W" is pressed, while EasyRPG will already start showing the message box, as soon as the switch is activated.

Download to the example game:
[KeyInputEXProblem-Example.zip](https://github.com/EasyRPG/Player/files/10817292/KeyInputEXProblem-Example.zip)

**Comment by Ghabry** [comment]
Hello.
You are right. The keystate was not correctly checked. This will be fixed in an update of the Player.

Patch for later:

```cpp
diff --git a/src/game_interpreter.cpp b/src/game_interpreter.cpp
index 8e95d804..5facf765 100644
--- a/src/game_interpreter.cpp
+++ b/src/game_interpreter.cpp
@@ -4236,8 +4236,8 @@ bool Game_Interpreter::CommandManiacKeyInputProcEx(lcf::rpg::EventCommand const&
                }
        } else if (operation == 2) {
                int key_id = ValueOrVariable(com.parameters[2], com.parameters[3]);
-               ManiacPatch::GetKeyState(key_id);
-               Main_Data::game_variables->Set(start_var_id, key_id ? 1 : 0);
+               bool key_state = ManiacPatch::GetKeyState(key_id);
+               Main_Data::game_variables->Set(start_var_id, key_state ? 1 : 0);
        } else {
                Output::Warning("Maniac KeyInputProcEx: Joypad not supported");
        }
```
