### ISSUE TITLE
Maximum value for variables is not correctly reset after exiting a Maniacs Patch game

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2909]
#### Name of the game:
A test project made with the Maniacs Patch (only requirement is that it should be made with said patch), and a game not made with the Maniacs Patch. 

#### Player platform:
Windows, latest continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
After exiting a game made by the Maniacs Patch, the maximum value of a variable (999 999/-999 999 for 2k games and 9 999 999/- 9 999 999 for 2k3 games) will incorrectly be kept as the one of the Maniacs Patch (2 147 483 647/-2 147 483 648). This can lead into issues if the game you try to play do calculations that lead to a variable over the original maximum/minimum value intended.

In this example on a 2k3 game not using the Maniacs Patch, I'm able to get a value over 9 999 999 by using said issue, since the maximum value intended is not applied.
![image](https://user-images.githubusercontent.com/108797333/222596882-edaf6e70-51b6-4584-a2f3-0469b2de8ce3.png)

**Comment by Ghabry** [comment]
Love to have simple bugs :)

needs a ``patch = 0`` at ``player.cpp:845`` because patches are never disabled...
