### ISSUE TITLE
Two-handed weapon didn't work out. The player can equip a shield and a two-handed weapon at the same time.

### ISSUE THREAD

**Issue by adms** [EasyRPG/Player#2911]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Mac, Linux(SteamDeck)

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
The two-handed weapon didn't work out. 
The player can equip a shield and a two-handed weapon at the same time.

**Comment by Ghabry** [comment]
did you use test this with the continuous build because that issue should be resolved already.

0.7 is a bit old by now and contains this bug.
