### ISSUE TITLE
Support for games of any language but not in Zip file.

### ISSUE THREAD

**Issue by adms** [EasyRPG/Player#2912]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Mac, Linux(Steamdeck)

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
The EasyRPG wiki claims "Support for games of any language" but is not 100% real.
Not including the game package as a Zip file. If the file name included the Chinese/Japanese character, it always makes unknown errors. Maybe using 7z instead of Zip will be better.

**Comment by Ghabry** [comment]
Due to how encoding guessing works this is not possible to do with 100% accuracy.

Can you provide some zip archives that fail for you?
