### ISSUE TITLE
Android: Multi-Touch broken on Android 13 and certain Samsung Devices

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#2915]
This is reported alot and I found issues documenting it in the Lemuroid repository (an app supporting libretro cores that is not RetroArch :heart: )

https://github.com/Swordfish90/Lemuroid

https://github.com/Swordfish90/Lemuroid/blob/96da5eddb8d2602adf8c82f57b34518e64a309c6/lemuroid-touchinput/src/main/java/com/swordfish/touchinput/radial/LemuroidTouchConfigs.kt#L131-L133

```java
        // Using standard MotionEvents.getX/Y() is broken on Samsung devices running Android 11,
        // but Android 13 broke MotionEvents.getRawX/Y() events in landscape mode for every device.
        val useRawTouchCoordinates = Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU
```

Relevant issues:

- https://github.com/Swordfish90/Lemuroid/issues/582
- https://github.com/Swordfish90/Lemuroid/issues/558
- https://github.com/Swordfish90/Lemuroid/issues/620

**Comment by Ghabry** [comment]
The real issue here is btw dynamic resolution scaling by Samsung. They run games at lower resolutions by default to give higher performance and to not break the games they fake the X/y coordinates of touch events.
But ui components are not repositioned so all the calculations are off 🤦

**Comment by hsoftxl** [comment]
what is "btw dynamic resolution"?

**Comment by fdelapena** [comment]
> what is "btw dynamic resolution"?

"btw" in that context means "By the way, "

The automatic resolution change is likely some sort of a battery optimization feature that could be disabled somewhere in settings. This is vendor specific and version specific, so can't tell where is this placed in devices.

**Comment by Ghabry** [comment]
This is not reproducible on a Samsung Galaxy A52 with Android 13.

Everything works fine.

Additionally got a report that Gamepads have a huge latency: Imo there is some noticable input lag that is not suitable for fast action games but RPGs are perfectly playable with it.

**Comment by Ghabry** [comment]
Recording of the issue:

Single touch works, multi touch behaves... interesting.

https://github.com/EasyRPG/Player/assets/1331889/0a1dbd5d-5b68-4b0a-a1a3-d219466cd63a

**Comment by Ghabry** [comment]
No idea how to fix the button mapping activity but this is not urgent.

However found a workaround for the touch-stuff:

When doing multitouch the app receives negative coordinates for X/Y. When I filter them the app starts receiving the correct coordinates. Then multitouch works. lol :shrug:
