### ISSUE TITLE
Buzzer sound is incorrectly partially played during the cursor sound after playing it

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2919]
#### Name of the game:
Test Game (included here), or a New Project with default settings from 2003.

#### Player platform:
Windows, tested with Player 0.7.0 and with the latest continuous builds.

#### Describe the issue in detail and how to reproduce it:
After playing the buzzer sound in a menu (Continue, item, shop, inn, load save, name input, settings menu... while not being able to do so), and then playing the cursor sound, the buzzer sound is incorrectly partially played during the cursor sound.
[Cursor-buzzer-sound-issue.zip](https://github.com/EasyRPG/Player/files/10956005/Cursor-buzzer-sound-issue.zip)

**Comment by Ghabry** [comment]
This must be some stale data in the audio buffer :/

Does not happen when playing a BGM.

**Comment by Ghabry** [comment]
This one is already fixed (Resolved it iirc in the settings PR)
