### ISSUE TITLE
[Enhancement] Games stop when switched to different window/put in background

### ISSUE THREAD

**Issue by DipeshAggarwal** [EasyRPG/Player#2925]
This is more of an annoyance, since it is the default RM behaviour, but when you switch to another window, game execution just stops.

Is there anyway an optional switch could be added to EasyRPG which allows the game to continue running when it is in background?

**Comment by Ghabry** [comment]
We have a settings scene since a few weeks so this is finally feasible to be added now.

And shouldn't be hard to add
