### ISSUE TITLE
I can't see the letters

### ISSUE THREAD

**Issue by alphadet** [EasyRPG/Player#2940]
#### Attach files (as a .zip archive or link them)
[bug.zip](https://github.com/EasyRPG/Player/files/11087110/bug.zip)

**Comment by Ghabry** [comment]
Thank you for the report. Sorry. That is a bug in our translation. I will update the app soon.

-------

ご報告ありがとうございます。申し訳ございません。それは私たちの翻訳にバグがあるのです。近日中にアプリを更新します。

**Comment by Ghabry** [comment]
There will be an update to the app in 24 hours.

The Japanese translation is incomplete and displays some text in English.

If you want help translating please visit:

https://translate.easyrpg.org/projects/easyrpg-player/android-app/

---------

24時間以内にアプリのアップデートが行われる予定です。

日本語訳が不完全なため、一部のテキストを英語で表示しています。

翻訳を手伝ってほしい場合は、こちらをご覧ください：

https://translate.easyrpg.org/projects/easyrpg-player/android-app/
