### ISSUE TITLE
Actor's name is... command for a game translated with lcftrans does not work correctly

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2942]
#### Name of the game:
Yume 2kki.

#### Player platform:
Windows, latest continuous build of the Player (the issue was "added" at least after the addition of the Settings menu, and likely with #2921).

#### Describe the issue in detail and how to reproduce it:
See issue #2831 for a partial in-game context.
Basically, the name of an actor X is changed to Y, and the game checks if the name of said actor is indeed Y with the conditional branch Actor's name is...
In a translation, the same thing should happen except that the name is changed to Z and checks for Z. Unfortunately, this check fails in the latest continuous build, and the conditional branch will tell you that this is incorrect while this is not the case.

Here's an example I've made on my side (original script, lines that should be translated and how, and the result that I get in-game while using the translation feature).
![image](https://user-images.githubusercontent.com/108797333/229344575-36f0be1d-1fde-4030-8e27-ef3d5dce9c4e.png)
![image](https://user-images.githubusercontent.com/108797333/229344579-38d7edb7-620a-4d99-8464-8bf9da4df999.png)
![image](https://user-images.githubusercontent.com/108797333/229344584-6f402ec1-1c54-405c-8815-06ade533ac5b.png)

**Comment by Ghabry** [comment]
this will be fixed before 0.8.0, forgot a single line again
