### ISSUE TITLE
Wait for Key Input does not work correctly if the game is set as a Maniac Patch game

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2946]
#### Name of the game:
EasyRPG Test Game 2003, with an EasyRPG.ini file set as "[Patch] Maniac =1" (The patch was successfully applied by looking at the variables).

#### Player platform:
Windows, latest continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
After setting the patch of the game as Maniac patch, the command Wait for Key Input seems to not be correctly handled. Instead of waiting for the user to press a key, it seems that the Player instead waits for ~1 second and completely ignores your key input.

**Comment by Ghabry** [comment]
hm I don't have this behaviour. The event only checks for numbers. Did you test with them?
