### ISSUE TITLE
RPG_RT Compatibility - Conditional Branch: Current BGM has completed a loop works on wav files while it should not

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2948]
#### Name of the game:
Yume 2kki version 0.120 patch 8 and more and also tested with the EasyRPG TestCase 2000.

#### Player platform:
Windows, version 0.7.0 and latest continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
The Conditional Branch _Current BGM has completed a loop_ is normally used to know if a track has looped or not. Curiously, it seems that the RPG_RT only works with midi and mp3 files and not with wav files, where EasyRPG also supports wav, leading to potential issues if a wav file triggers the conditional branch while it should not be the case. I think that the best solution would be to not support wav files if the game is not made with EasyRPG, and let this bug be present for non-EasyRPG games.

**Comment by Ghabry** [comment]
Haven't checked this yet but could it be that this abuses a behaviour from the web player (async loading) here?

Is the behaviour the same for the local Player?

**Comment by Ghabry** [comment]
- Map0619 mentions a EasyRPG performance optimisation. This one uses _Detection 1_ below.
- Map1075 talks about screen scroll, likely our lack of this out-of-bounds instant scroll thing
- Map1888 talks about incorrect tint (maybe because of 32 bit color buffer)?
- Map1901 and 1902 mention the teleport facing
- Map1991 to Map2000 write to a new EasyRPG variable alot using alot of technique. Uhm I need more time to investigate this.

Detection 1:

```
@> Transfer Player: [0005:MAP0005 夢ベランダ] (009,007), Up
@> Control Variables: [0052:環境 0=RPGRT,1=other] = 0 
@> Conditional Branch: Player is facing Up
  @> Control Variables: [0052:環境 0=RPGRT,1=other] = 1 
  @>
 : Branch End
```

**Comment by Ghabry** [comment]
In RPG_RT you arrive from Red Streetlight World directly at the first screenshot. In EasyRPG you arrive at the 2nd screenshot but it is full of chasers that bring you to the first

![screenshot_0](https://user-images.githubusercontent.com/1331889/231501208-0d3a632d-fecd-44ba-a691-f1c02623bb2e.png)

![screenshot_3](https://user-images.githubusercontent.com/1331889/231501214-1a934326-5fc4-4f8c-aa10-93cf2d5d87f3.png)

The Sugar Road one is different: In RPG_RT you reach this Chroma effect world (1st). In EasyRPG you are in a small room with some crazy moving color background (2nd).

![screenshot_1](https://user-images.githubusercontent.com/1331889/231501419-e95e7ae9-03d5-465c-8e5f-7f2ccfee5407.png)

![screenshot_4](https://user-images.githubusercontent.com/1331889/231501441-75fffd05-3cad-4bc0-a038-2af1479e62d9.png)

so I think "Chromatic Limbo" is unreachable from EasyRPG Player

**Comment by Ghabry** [comment]
quick test for mp3: Is really only broken for WAV. *shrug*
