### ISSUE TITLE
Yume 2kki - Playing an almost empty wav file breaks the audio of the Player

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2950]
#### Name of the game:
Yume 2kki version 0.120, patch 8 and more.

#### Player platform:
Windows, version 0.7.0 and latest continuous build of the Player.

#### Attach files (as a .zip archive or link them)
Music file related to the issue: [x[]_musi#00.zip](https://github.com/EasyRPG/Player/files/11180569/x._musi.00.zip)

#### Describe the issue in detail and how to reproduce it:
When playing this wav file as a Music in the Player, the audio of the Player will be broken and will just indefinitely play the sound effects played while this Music lasts ([see video here](https://cdn.discordapp.com/attachments/946771467360673832/1093593505349255208/brokenaudio.mp4) - note that it will download the video on your side). Important to note about this file is that it lasts 0.0 second and is 44 bytes with almost nothing in it, so it's likely related to that.

**Comment by Ghabry** [comment]
Actually we already have code for this. The error check was just incorrect xD
