### ISSUE TITLE
Show String Picture - System/image.png displays incorrect transparent color 

### ISSUE THREAD

**Issue by jetrotal** [EasyRPG/Player#2961]
Please fill in the following fields before submitting an issue:
#### Name of the game:
Maniacs - custom life bar using Show StringPic Tutorial: 
https://www.rmteka.pl/maniacs-patch-nie-gryzie-10-prosty-hud-wersja-alternatywna/

#### Player platform:
Windows 64x

#### Attach files (as a .zip archive or link them)
https://www.rmteka.pl/wp-content/uploads/2023/04/prosty-HUD-przez-show-string-picture.zip

#### Describe the issue in detail and how to reproduce it:

That's a weird one. In this tutorial, the user created a HP bar using show string Picture and a custom System Graphic background(the images from the ./system/something.png). 

In the image bellow there are 2 examples, one displays correctly the opacity of the image (RPG_RT),
and another shows the player interpreting the color-index-0 as black instead of transparent:

![image](https://user-images.githubusercontent.com/45118493/232593782-3ef71496-541e-45b5-8cad-75ef7124291a.png)
![image](https://user-images.githubusercontent.com/45118493/232593835-92f74fef-d46c-4716-b696-24400606bbb5.png)

-------------------------------------

their hack is basically avoiding the use a system graphic like this:
![image](https://user-images.githubusercontent.com/45118493/232595306-433f5fab-344c-449c-9c12-5984b6638a55.png)

and instead, using it like this:
![image](https://user-images.githubusercontent.com/45118493/232595391-8ef5e214-779f-42d2-b9e8-29178b7ef1b5.png)

**Comment by Ghabry** [comment]
wtf?

Why even use Show String Pic here. This is a Picture without text.

**Comment by florianessl** [comment]
Similar to both this and the other mentioned issues:
The blitting logic of the font renderer is taking information from outside of the indexed color gradient defined in the system graphic.
For comparison, here's how a big font is handled by both Maniacs & EasyRPG (font sizes do also differ)

Maniacs:
![rm2k3](https://github.com/EasyRPG/Player/assets/42896817/07be8b13-33b7-4f7a-884f-7c6e3f34664e)

EasyRPG:
![easyrpg](https://github.com/EasyRPG/Player/assets/42896817/760765db-573d-4680-8cac-220c36136e28)

System Graphic used:
![systemgraphic](https://github.com/EasyRPG/Player/assets/42896817/d4672b69-c255-4c1e-885a-41e062555528)

**Comment by Ghabry** [comment]
Thanks for the reminder. The system graphic is not scaled with the font graphic. Havn't implemented this yet.

**Comment by Ghabry** [comment]
Do not have VD2 on that PC so I used a brighter red and the font used by VD according to Makerpendium (Bloodfeast):

![grafik](https://github.com/EasyRPG/Player/assets/1331889/a2a962a9-9ec9-41ac-8e3c-df99e7a1a2d1)

**Comment by Ghabry** [comment]
@florianessl one more question about the scaling. In the example of you with the incorrect size. Is this also Bloodfeast? (and Player has different scale compared to RPG_RT)

**Comment by florianessl** [comment]
> @florianessl one more question about the scaling. In the example of you with the incorrect size. Is this also Bloodfeast? (and Player has different scale compared to RPG_RT)

This is also an unmodified version of Bloodfeast. Both examples use the same sizes for the font.

**Comment by Ghabry** [comment]
Reopening this because I have a better fix that doesn't regress OFF...
