### ISSUE TITLE
Maniacs "MovePicture" command: Origin doesn't work as expected

### ISSUE THREAD

**Issue by florianessl** [EasyRPG/Player#2963]
I'm putting together a custom screen using StringPictures with origin = "TopLeft".
When using the extended MovePicture command to create a "Fade In" effect the set origin value seems to be ignored (TopLeft, same X/Y as in initial ShowStringPicture) and as a result the picture moves to the upper left as if using the default "Center" origin..

Video of this happening:
https://user-images.githubusercontent.com/42896817/232777916-bccea607-764f-43dd-b319-7378650510a9.mp4

Let me know if I should put together a small sample project to recreate this issue.

**Comment by Ghabry** [comment]
I think I need a sample project here. My quick test matches the Maniac Patch behaviour.

**Comment by florianessl** [comment]
Tested this again in 2k3e and it works as expected. It seems this behavior only occurs when using the Maniac commands in 2K mode.
Sorry for the hassle. Here are sample projects for both engine types:
[ManiacStringPicBug.zip](https://github.com/EasyRPG/Player/files/11301472/ManiacStringPicBug.zip)

**Comment by Ghabry** [comment]
Did you put in EasyRPG.ini:

```ini
[Patch]
Rpg2k3Commands=1
```

The picture command is complex so the stuff is partially in 2k3 code.
