### ISSUE TITLE
Outotsu Yume, LanVodis - Invalid skill message is displayed on the title screen while it should not

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2977]
#### Name of the game:
[Outotsu Yume versions a-000, 0.00a, 0.00b and 0.00c](https://yume.wiki/unevendream/Downloads).

#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
When starting one of these games with the Player, an error is displayed on the title screen stating that `Actors 6 & 13 can't learn invalid skill 36`.
![screenshot_1](https://user-images.githubusercontent.com/108797333/234920739-d7503d99-7722-46bd-8e83-c61fe79de9e7.png)
This happens since these Actors are set to learn this skill at Level 1, but the maximum number possible for a skill in this game is 10, so this is a normal behaviour, but this check should be run when an actor in the party has an invalid skill which should not be possible here (your party should not exist on the title), so this message should not be displayed.
![image](https://user-images.githubusercontent.com/108797333/234921811-878c1117-8325-485b-871c-ccedceaf2421.png)
![image](https://user-images.githubusercontent.com/108797333/234921863-afa13235-d468-4d15-8140-03f2d7718143.png)

EDIT: From what I've tested, this issue is also present on the game [LanVodis](https://tunditur-unda.itch.io/lanvodis) by sraëka-lillian.

**Comment by jetrotal** [comment]
I'm having a similar issue with my map on Collective Unconscious game:
![image](https://github.com/EasyRPG/Player/assets/45118493/17949a35-eeb9-488c-93f6-f6d00a1a4ff2)

What I did was simply copy a map from a project to another. Now, every time I teleport, 
I get this error where the game tries to read `the older map ID as an actor`, and `the newer map ID as a skill`.

**Comment by Mimigris** [comment]
> I'm having a similar issue with my map on Collective Unconscious game: ![image](https://private-user-images.githubusercontent.com/45118493/313435512-17949a35-eeb9-488c-93f6-f6d00a1a4ff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzI0MTUsIm5iZiI6MTcxMDYzMjExNSwicGF0aCI6Ii80NTExODQ5My8zMTM0MzU1MTItMTc5NDlhMzUtZWViOS00ODhjLTkzZjYtZjZkMDBhMWE0ZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDIzMzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZDdlODhmYjkwNDdlMDAyOWMyNDQxYzAwN2FlMTUxMjI5YTg2MTNkYzM5YzIzYjVmYzRiODdhZTQyODQ0MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KEPrIcgDDw1BKlRohVwJ5h0pFUAMD24Glaa9byDW05g)
> 
> What I did was simply copy a map from a project to another. Now, every time I teleport, I get this error where the game tries to read `the older map ID as an actor`, and `the newer map ID as a skill`.

This is completely unrelated to this issue, nor is an issue of the Player: Collective Unconscious runs a common event to give a skill to an actor, with the skill in question having the same ID than the map you are currently in (this data is used to know if a player has visited a map or not). Since in the latest build they didn't planned that 1331 maps would be available, they didn't created 1331 skills, so their code is trying to add a skill that doesn't exist to an actor.

**Comment by Ghabry** [comment]
Weird way to do this. They could have just used switch e.g. 9000 + map_id 🤔

**Comment by Ghabry** [comment]
moving this to 0.8.1
just remembered that we already have code to sanitize this bad data even for skills. Though it doesnt appear to work https://github.com/EasyRPG/Player/blob/master/src/game_actor.cpp#L1333

**Comment by Ghabry** [comment]
Invalid skills learned during a level up (this also happens during startup) are now ignored (debug message only).
