### ISSUE TITLE
Problems with abnormal game runtime and abnormal game image display

### ISSUE THREAD

**Issue by Helloworld996** [EasyRPG/Player#2979]
#### Name of the game:
北极星；nehan2 -CHS（于2019.7.7改）
#### Player platform:
Android
#### Attach files (as a .zip archive or link them)

 北极星link：
https://drive.google.com/drive/mobile/folders/1xyCAkaUto9ZSNEGSdVXZY11ifHmfP32o

nehan2 -CHS（于2019.7.7改） link：
https://drive.google.com/file/d/1JLAYUFF72PvjcaTeb5VLP4CaUVz9PybU/view?usp=drivesdk

#### Describe the issue in detail and how to reproduce it:
北极星does not work properly and is shut down after an error is reported during operation. 
Display as shown in the following picture:
![Screenshot_2023-04-29-21-09-47-262_org easyrpg player](https://user-images.githubusercontent.com/58156832/235305421-8a5eacd6-1e73-4605-9e84-08213eff4df3.jpg)
![Screenshot_2023-04-29-21-09-51-497_org easyrpg player](https://user-images.githubusercontent.com/58156832/235305437-930f6a88-d02e-44ce-8c64-8ed4e6ad4612.jpg)

Nehan2 running picture background display is not normal, there are pixel blocks and some background images are not displayed. 
Make sure the resource is the full version. 
As shown in the picture below
![Screenshot_2023-04-29-21-12-04-288_org easyrpg player](https://user-images.githubusercontent.com/58156832/235305780-3b544746-4796-4315-87d2-90d5cdb85305.jpg)

**Comment by Ghabry** [comment]
you are using an outdated version of the Android app.

Use the latest from play store or the one from the bottom of the download page: https://easyrpg.org/player/downloads/#snapshot-android

Direct link: https://ci.easyrpg.org/downloads/android/EasyRpgPlayerActivity.apk

**Comment by Helloworld996** [comment]
I have also tried the latest version, and there is also this problem. 
Then I unloaded the old version of the trial.

**Comment by Helloworld996** [comment]
> 您使用的是过时版本的 Android 应用程序。
> 
> 使用 Play 商店或下载页面底部的最新版本：https://easyrpg.org/player/downloads/#snapshot-android
> 
> 直接链接：https://ci.easyrpg.org/downloads/android/EasyRpgPlayerActivity.apk

I have also tried the latest version, and there is also this problem. 
Then I unloaded the old version of the trial.

**Comment by Helloworld996** [comment]
> 您使用的是过时版本的 Android 应用程序。
> 
> 使用 Play 商店或下载页面底部的最新版本：https://easyrpg.org/player/downloads/#snapshot-android
> 
> 直接链接：https://ci.easyrpg.org/downloads/android/EasyRpgPlayerActivity.apk

I have tried versions 0.7.0-699 that also have this issue. Also prompt me to turn off the red screen

**Comment by Helloworld996** [comment]
@Ghabry 
I have tried versions 0.7.0-699 that also have this issue. Also prompt me to turn off the red screen

![Uploading Screenshot_2023-04-29-21-54-00-618_org.easyrpg.player.jpg…]()
![Screenshot_2023-04-29-21-56-48-071_org easyrpg player](https://user-images.githubusercontent.com/58156832/235306699-b8e500da-ea36-490d-acc7-47182224a632.jpg)

![Screenshot_2023-04-29-21-58-06-681_org easyrpg player](https://user-images.githubusercontent.com/58156832/235306712-5676cef8-047b-4d43-bce2-a364695e2701.jpg)

**Comment by Ghabry** [comment]
the "IDAT: Too far back" is unfortunately not solvable: This means that the PNG is corrupted and libpng refuses to read it for security reasons.

Yes, Windows can load it but we cannot change this behaviour.

The only solution here is to open the PNG in an image editor and to press save.

**Comment by Helloworld996** [comment]
> 不幸的是，“IDAT：太远了”无法解决：这意味着 PNG 已损坏并且 libpng 出于安全原因拒绝读取它。
> 
> 是的，Windows 可以加载它，但我们无法更改此行为。
> 
> 此处唯一的解决方案是在图像编辑器中打开 PNG，然后按保存。

![Screenshot_2023-04-29-21-54-00-618_org easyrpg player](https://user-images.githubusercontent.com/58156832/235307899-465f90c8-2061-4e0c-af88-d6ae2e6d8dc4.jpg)

There is also a red screen issue with the first game（北极星）, which still exists from 07.0—699. After the prompt, ask me to close it .

**Comment by Ghabry** [comment]
thanks this will be fixed in the next Android update in about a week
