### ISSUE TITLE
"Invisible" control codes counting towards overall length of text in String Pictures.

### ISSUE THREAD

**Issue by Goburinbro** [EasyRPG/Player#2987]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows x64 .8 continuous 

#### Attach files (as a .zip archive or link them)
![image](https://user-images.githubusercontent.com/86999721/236283565-400ec5e7-8e65-4eda-b3cd-670b27a35dbc.png)
![image](https://user-images.githubusercontent.com/86999721/236283636-8aac90df-9aab-487c-b94c-3d01fe7cee7d.png)
![image](https://user-images.githubusercontent.com/86999721/236284896-b675cbf5-cd54-4f08-b459-348190094cf0.png)

#### Describe the issue in detail and how to reproduce it:
Show String Picture seems to treat control codes as counting towards the overall displayed length of a string picture. The result is that certain issues with positioning may arise, or longer than intended text boxes when drawing a window with the text.

**Comment by Ghabry** [comment]
The code for not counting "color" is in but I forgot to assign the return value which breaks the skipping :sweat:
