### ISSUE TITLE
(3DS) Crashes When Loading Save

### ISSUE THREAD

**Issue by yerifes** [EasyRPG/Player#2988]
#### Name of the game: 
Wadanohara and the Great Blue Sea

#### Player platform: 
3DS

#### Attach files (as a .zip archive or link them)
Save - [Save01.zip](https://github.com/EasyRPG/Player/files/11402267/Save01.zip)
Log - [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/11402278/easyrpg_log.txt)
Crash Dump - [crash_dump_00000002.zip](https://github.com/EasyRPG/Player/files/11402283/crash_dump_00000002.zip)

#### Describe the issue in detail and how to reproduce it:
I was initially able to launch and play Wadanohara and the Great Blue Sea without issue. Now, whenever I try to load my save, it crashes. I've only had this issue with WATGBS so far, the only other game I've played using easyRPG for the 3DS is End Roll and that save loads just fine. The save loads on PC without issue. I'm using a Japanese New 3DS LL, I've also recreated this on an American New 3DS XL and experienced the same crash. I'm using the CIA version of the application.

![vOzeuO4A](https://user-images.githubusercontent.com/132623012/236351104-e0fcc1bf-3417-4213-a29f-e9b23f8203b7.jpg)

Thanks for your time!

**Comment by AmbrosiaEgg** [comment]
Vouching for the validity of this issue as a second victim.
