### ISSUE TITLE
Yume Nikki version 0.04 - Engine incorrectly detected as 2k instead of 2k3

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2990]
#### Name of the game:
[Yume Nikki version 0.04](https://tcrf.net/Proto:Yume_Nikki/Version_0.04).

#### Player platform:
Windows, 64 bits 0.8.0 version of the Player.

#### Describe the issue in detail and how to reproduce it:
When playing this version of the game with the Player, the menu will incorrectly have the Skills, Save and Equipment features, in addition to not being able to use the numpad keys to do actions (wake up, use effects).
![screenshot_7](https://user-images.githubusercontent.com/108797333/236609867-cf34a858-e3cc-4c18-ae5a-000df7a04ed9.png)

How the engine has been detected by the Player:
```
Debug: Loading game ゆめにっき
Debug: Analyzing RPG_RT PATH/TO/THE/GAME/Yume_Nikki_0.04/ゆめにっき0.04/RPG_RT.EXE
Debug: EXEReader: EXFONT resource found (DE 0xd1e48; 0xd52a0; len 0x2168)
Debug: ExFont loaded from RPG_RT
Debug: EXEReader: VERSIONINFO not found
Debug: RPG_RT information: version= logos=1 i386=true easyrpg=false
Debug: Engine configured as: 2k=true 2k3=false MajorUpdated=true Eng=false
```

**Comment by Ghabry** [comment]
Hm our detection code assumes that all versions of 2k3 have a version info block.

Either they really bundle a 2k RT here or we have a problem because this contains the same information you would expect from a 2k Value! Version

**Comment by Ghabry** [comment]
According to Kotatsu this is version 1.0 "The most buggy as hell version of RPG_RT you may ever encounter".

Hopefully there are not more games that bundle with 1.0 and are now misdetected...

**Comment by Ghabry** [comment]
Was just told about this nice table here: https://www.makerpendium.de/index.php/RPG_RT.exe

Another good metric is the size of the CODE segment. For 2k3 it is much larger than for 2k. So in case of "1 logo, no ver info" also check CODE size and it will work :)

**Comment by Mimigris** [comment]
Related: the game [Corrupted](https://ynfg.yume.wiki/Corrupted) is also incorrectly detected as a 2k game instead of a 2k3 game but does not use the same exe:

```
Analyzing RPG_RT PATH/TO/THE/GAME/RPG_RT.exe
Debug: EXEReader: EXFONT resource found (DE 0xde290; 0xe1720; len 0x2168)
Debug: ExFont loaded from RPG_RT
Debug: EXEReader: VERSIONINFO not found
Debug: RPG_RT information: version= logos=1 i386=true easyrpg=false
Debug: Engine configured as: 2k=true 2k3=false MajorUpdated=true Eng=false
```

This one may need more testing, Ghabry got this instead for example.

```
Debug: EXEReader: VERSIONINFO resource found (DE 0xde550; 0xe91c0; len 0x274)
Debug: RPG_RT information: version=1.0.8.0 logos=1 i386=true easyrpg=false
```
