### ISSUE TITLE
Recognize Maniac games that don't have an accord.dll file

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#2992]
#### Name of the games (feel free to add more):
- [3 AM Cathrath](https://ojosama.itch.io/cathrath)
- [Dollmaker and the 100 Alices](https://ojosama.itch.io/dollmaker)
- [LOTUS EATER PRINCESS Book I](https://ojosama.itch.io/lotuseater1)
- [LOTUS EATER PRINCESS Book 1 ½](https://ojosama.itch.io/lotuseater1half)
- [Lament - Incarnation of the Goddess](https://ojosama.itch.io/lament)
- [Prosty HUD string picture test](https://www.rmteka.pl/maniacs-patch-nie-gryzie-10-prosty-hud-wersja-alternatywna/)
- [THUNDER DRACO -The Ambition of the Hero Alex- (English translation)](https://catbox.moe/c/5f2g75)

#### Player platform:
Windows, 64 bits 0.8.0 version of the Player.

#### Describe the issue in detail and how to reproduce it:
Some maniac patch games do not come with an accord.dll file, which is used to detect if the game is a Maniac patch game or not in the Player (this can also be achieved by adding an EasyRPG.ini file and adding the key _Maniac=1_ in it). Due to this, these games are not properly detected and will not be able to behave like a Maniac patch game would do (extended commands and new commands will not work as intended). This can be manually solved by adding files to detect them but this is not really a thing that can be done for users just wanting to try these games not knowing the problem.
The detection could likely be done by analyzing the exe file of the game, or through a database containing entries of games like this if we go this way for some specific games.

An example of a broken game due to this, 3 AM Cathrath: a lot of texts will be missing due to no string picture commands working (the title screen and the menus will not be displayed correctly), in addition to not be able to work if a savefile is present in the folder of the game (a conditional branch requests the save 1 to be loaded in that case on startup, not possible without the maniac patch, and nothing is planned after).
![screenshot_3](https://user-images.githubusercontent.com/108797333/236668377-31031ed2-4a8e-4ccb-a66c-76da5a5b55d6.png)
![screenshot_4](https://user-images.githubusercontent.com/108797333/236668457-2aeb92c3-c18c-4988-85a8-b6c0eef3ff7f.png)

**Comment by Ghabry** [comment]
@Mimigris can you do the following for all of the RPG_RT.exe in these games:

Right Click -> Settings -> Details

![grafik](https://github.com/EasyRPG/Player/assets/1331889/7dd08391-e3fa-497f-a4c2-1bea107d1a67)

Then check if anything in the "Details" tab indicates Maniac Patch and what the string is. BingShan added it to the version info somewhere in later versions.

**Comment by Mimigris** [comment]
> @Mimigris can you do the following for all of the RPG_RT.exe in these games:
> 
> Right Click -> Settings -> Details
> 
> Then check if anything in the "Details" tab indicates Maniac Patch and what the string is. BingShan added it to the version info somewhere in later versions.

![image](https://github.com/EasyRPG/Player/assets/108797333/9d653b79-8232-438d-82e1-400a98b1e111)
From what I can see in the Details tab, the only differences that I could saw were the size of the files and the language of the executables (there's also the date but it's useless). Maybe this information is present somewhere else than in this tab?

It seems that I could find two different executable files for the Maniac Patch: the second one on the screen is taken from [Prosty HUD string picture test](https://www.rmteka.pl/maniacs-patch-nie-gryzie-10-prosty-hud-wersja-alternatywna/) (likely done with an older version of the patch) and the third one on the screen correspond to the others games (it seems that they are all the same executable and that they correspond to the latest public version of the Maniac Patch - The first one on the screen is just the latest version of 2k3 that was used to compare).

Also, not sure if you knew it, but it seems that the [accord.dll](https://www.makerpendium.de/index.php/Maniac_Patch) file is just used to support ogg files, explaining why some games don't have it at all (since it seems that the Maniac RPG_RT can work without it, you probably just need it if you have an ogg file to play in your game).

**Comment by Ghabry** [comment]
Ah so these are executables that use old versions of Maniac Patch.
I thought these are recent versions as they have a special version string.

In that case I don't see a simple way to detect it

**Comment by Ghabry** [comment]
actually. Better idea: You know this one line in the logs that has these information about "Analyzing RPG_RT", right? (with amount of logos etc.)

Can you provide the list for all the games? It should be something like "logos=0" and no ExFont found... that is already good enough for fingerprinting.

**Comment by Mimigris** [comment]
> actually. Better idea: You know this one line in the logs that has these information about "Analyzing RPG_RT", right? (with amount of logos etc.)

For [Prosty HUD string picture test](https://www.rmteka.pl/maniacs-patch-nie-gryzie-10-prosty-hud-wersja-alternatywna/):
```
Loading game Untitled
Debug: Analyzing RPG_RT Project1/RPG_RT.exe
Debug: EXEReader: EXFONT resource found (DE 0xfd720; 0x103760; len 0x2168)
Debug: ExFont loaded from RPG_RT
Debug: EXEReader: VERSIONINFO resource found (DE 0xfda10; 0x10f6bc; len 0x2ec)
Debug: RPG_RT information: version=1.1.2.1 logos=1 i386=true easyrpg=false
Debug: Engine configured as: 2k=false 2k3=true MajorUpdated=true Eng=true
```

Unfortunately this one has an exfont and has one logo detected, so I don't think that we can use this method.

Now, here's what I got for [3 AM Cathrath](https://ojosama.itch.io/cathrath) (I previously mentioned that the other executables were all the same so I didn't tried them, but if you really think it could not be the case feel free to request me to try them):
```
Loading game 3 AM Cathrach
Debug: Game does not need RTP (FullPackageFlag=1)
Debug: Cannot find: Font/ExFont
Debug: Cannot find: ./ExFont
Debug: Analyzing RPG_RT Cathrath/RPG_RT.exe
Debug: EXEReader: BITMAP not found.
Debug: EXEReader: VERSIONINFO resource found (DE 0x1541e8; 0x159f68; len 0x258)
Debug: RPG_RT information: version=1.1.2.1 logos=0 i386=true easyrpg=false
Debug: Unable to detect version from exe
Debug: Engine configured as: 2k=false 2k3=true MajorUpdated=true Eng=true
```
This one should be detectable if you use the logo and the exfont.

**Comment by Ghabry** [comment]
Okay so ``logos=0`` and ``version=1.1.2.1`` and ``NO BITMAP`` indicate a new version of Maniac Patch (a version with recompiled code instead of hacking the exe).

Versions based on a hacked 1.1.2.1 could be detected by looking at the size of the ``CHERRY`` segment (yes, really, but I knew that this exists :)).

```
Maniac Patch:

rpg_rt.exe.dat:     formato del fichero pei-i386

Secciones:
Idx Name          Size      VMA       LMA       File off  Algn
  0 CODE          000c9000  00401000  00401000  00000400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 DATA          00004200  004ca000  004ca000  000c9400  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  2 BSS           00000000  004cf000  004cf000  000cd600  2**2
                  CONTENTS
  3 .idata        00002a00  004d3000  004d3000  000cd600  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  4 .tls          00000000  004d6000  004d6000  000d0000  2**2
                  CONTENTS
  5 .rdata        00000200  004d7000  004d7000  000d0000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA, SHARED
  6 .reloc        0000d800  004d8000  004d8000  000d0200  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA, SHARED
  7 CHERRY        0001f000  004e6000  004e6000  000dda00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  8 .data         00000200  00505000  00505000  000fca00  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  9 .rsrc         00012d70  00506000  00506000  000fcc00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA, SHARED

Official 2k3 English:
RPG_RT.exe:     formato del fichero pei-i386

Secciones:
Idx Name          Size      VMA       LMA       File off  Algn
  0 CODE          000c9000  00401000  00401000  00000400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 DATA          00004200  004ca000  004ca000  000c9400  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  2 BSS           00000000  004cf000  004cf000  000cd600  2**2
                  CONTENTS
  3 .idata        00002a00  004d3000  004d3000  000cd600  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  4 .tls          00000000  004d6000  004d6000  000d0000  2**2
                  CONTENTS
  5 .rdata        00000200  004d7000  004d7000  000d0000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA, SHARED
  6 .reloc        0000d800  004d8000  004d8000  000d0200  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA, SHARED
  7 CHERRY        0000b800  004e6000  004e6000  000dda00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  8 .data         00000200  004f2000  004f2000  000e9200  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  9 .rsrc         00012da0  004f3000  004f3000  000e9400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA, SHARED
```
