### ISSUE TITLE
Variable Ops issue with Variable RAND arguments (Maniacs Patch)

### ISSUE THREAD

**Issue by Goburinbro** [EasyRPG/Player#2994]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, latest nightly, x64

#### Describe the issue in detail and how to reproduce it:
When using Variable Control, performing RANDOM operations with variables rather than constants does not behave as expected, and seems to be ignoring the variable designation entirely, treating it as though it were a constant.

The attached WEBM is a step-by-step walkthrough of a CBS damage formula that uses this, demonstrating the sharp difference between the RPG_RT handling, and the EasyRPG Player handling of the variable control.

![image](https://user-images.githubusercontent.com/86999721/236694309-dff75293-1504-456e-b41e-8620e3673cf0.png)
[EasyRPG Broken by legendary RAND.webm](https://user-images.githubusercontent.com/86999721/236694321-4c648e1a-2d14-47cc-915b-c5e52104f9fc.webm)

**Comment by Ghabry** [comment]
This appears to be bitfield stuff again:

Lower bits of Parameter 7 is for the 1st arg, upper bits (4 bit groups) is for 2nd arg
