### ISSUE TITLE
The Adventures of Meatball Dog - Invalid party member when starting a new game while not the case in the RPG_RT

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3008]
#### Name of the game:
[The Adventures of Meatball Dog](https://copper-wave.itch.io/meatball-dog-fan-game).

#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
When starting a new game in The Adventures of Meatball Dog in the Player, a warning message will be displayed stating that the invalid party members 2, 3 and 4 were removed. It does not happen in the RPG_RT where the game starts without issues.
![screenshot_5](https://github.com/EasyRPG/Player/assets/108797333/51c0d46e-a734-4bcc-a866-77461bbc8e31)

When checking the database of the game, it seems that only one actor exists and that only one actor is present in the initial party, making it a weird error.
![image](https://github.com/EasyRPG/Player/assets/108797333/7761de65-2fc9-4b30-8961-e9336371bf06)
![image](https://github.com/EasyRPG/Player/assets/108797333/85f6e205-6e50-4f7e-a1a5-9bb8d59018d5)

**Comment by Ghabry** [comment]
The editor is just really good in sanitizing the data.

At least the 2k one, the 2k3 crashes alot...

When you use lcf2xml you will see that the start party is defined with 4 members.

**Comment by CherryDT** [comment]
If you'd increase the max. actors number to >=4 in the database, you'd then see that in fact the other members are defined as starting members in the system tab.
