### ISSUE TITLE
GYTB crashes by loading badges "Attemting to write Exdata"

### ISSUE THREAD

**Issue by Aircool08** [EasyRPG/Player#3010]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
new 3ds xl / WIndows 11 pc

#### Describe the issue in detail and how to reproduce it:
When you start GYTB and attach my badges in the folder bdages, it will read every badge,
but then it will show "Attemting to write exdata" and then it crashes i dotn know what to do
[crash file and badges folder.zip](https://github.com/EasyRPG/Player/files/11488198/crash.file.and.badges.folder.zip)
can anyone help me

**Comment by Ghabry** [comment]
This doesn't sound like a player issue.. We don't use extdata

**Comment by Mimigris** [comment]
> When you start GYTB and attach my badges in the folder bdages, it will read every badge, but then it will show "Attemting to write exdata" and then it crashes i dotn know what to do [crash file and badges folder.zip](https://github.com/EasyRPG/Player/files/11488198/crash.file.and.badges.folder.zip) can anyone help me

Like Ghabry said, I don't really see how this is related to the Player itself. If this is an issue with GYTB, you may have a better luck to find a solution to your issue by asking directly to the GYTB repository that can be find here: https://github.com/MrCheeze/GYTB
