### ISSUE TITLE
Doesnt open on Wii Mini (DSI) Exception

### ISSUE THREAD

**Issue by DinisB** [EasyRPG/Player#3025]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
None

#### Player platform:
Windows, Linux, Android, ...
Wii

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
 -didnt come with one

#### Describe the issue in detail and how to reproduce it:
Opening the homebrew and launching it

**Comment by carstene1ns** [comment]
Is this with 0.8? Can you make a photo of the stack trace?

**Comment by DinisB** [comment]
Yes its with the 0.8 version, ill try to send a picture later.

**Comment by carstene1ns** [comment]
Closing this in favor of #3054.

The Wii port has some general problems currently, hoping to fix both in the same go.
