### ISSUE TITLE
Battle 2k3: damage popup not shown

### ISSUE THREAD

**Issue by jetrotal** [EasyRPG/Player#3031]
#### Name of the game:
 - Deluge and other games

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
Video Material - Deluge
https://cdn.discordapp.com/attachments/946771467360673832/1115708840642625576/DELUGE_by_riggy2k3_-_EasyRPG_Player_2023-06-06_14-27-44.mp4
Game recently created:
https://cdn.discordapp.com/attachments/946771467360673832/1115745422976233603/2023-06-06_17-53-15.mp4

#### Describe the issue in detail and how to reproduce it:

Riggy commented about this issue on Deluge and I did a Battle Test on different games with player 0.8.

After every attack, a game should display the damage value in a number popup over the attack target:
![image](https://github.com/EasyRPG/Player/assets/45118493/40b5c281-9a36-404f-adee-fcbfde2d7ac9)

but, for some reason those number don't appear on 0.8 battles:
![image](https://github.com/EasyRPG/Player/assets/45118493/efc6ae7c-2d16-4e59-b1b0-efc7d55ebff9)

video pointed above shows more cases where this happens.
(Didn't test on 2k battle yet).

**Comment by Ghabry** [comment]
Can this be tested using one of the builds of #3023 pr?

**Comment by jetrotal** [comment]
On my project it worked as intended. 

I shared this build with Riggy, but he commented his game still doesn't show the damage popup...
