### ISSUE TITLE
Opening or closing the menu has issues with keys pressed

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3037]
#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
When closing or opening the menu with the Decision or Menu key hold, the status of said key will reset and will be reused just after, while it should normally only get reset and not be able to be used until pressed again.

**Comment by Mimigris** [comment]
Just to give examples on some input issues that were brough due to #3020 , with the game Yume 2kki as an example:

- The game Yume 2kki has a time trial mode, accessible by holding Right and Shift when starting a new game. Thing is, due to the fact that now the inputs are cleared when starting a new game (this doesn't even match with the RPG_RT), said keys need to be hold just after starting the new game and cannot be hold before since they will just be ignored, making it a bit harder to enable.
- A debug feature in said game enabled by having the switch 1418 set to ON displays the coordinates of your character and some data related to how the game works. While said switch is ON, the info can be hidden by holding the Cancel/Menu key, and since the Cancel/Menu key opens the menu, you are expected to exit the menu by holding the key to hide the info (not the best design idea indeed but that's a debug feature and they didn't had a lot of other keys due to being a 2k game). Thing is, holding the cancel key on the menu to exit it and try to hide the info on the Player will instantly reopen the menu, making it almost impossible to hide said info this way.

**Comment by Ghabry** [comment]
imo best solution is to revert https://github.com/EasyRPG/Player/pull/3020/commits/7187b9ff6f396c0c694ef2754ad7a5b008e1437d

This brings another issue back but is better than breaking a game.
