### ISSUE TITLE
A changed Tileset should not be loaded from a save for non 2k3 English games

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3042]
#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
When loading a save for a game where the tileset was changed by using the command Change Tileset on the current map, the original tileset of the map should be used on load anyways EXCEPT for 2k3 English games where this data is correctly loaded. The data seems to be saved anyways but is just not loaded by the non 2k3 English games and this should also be supported as such since used in some games.

**Comment by Ghabry** [comment]
@CherryDT are you aware of this bug? I'm not aware of a fix by you.

**Comment by CherryDT** [comment]
See 1.12 changelog:
![Uploading Screenshot_2023-06-28-21-04-30-69_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by Ghabry** [comment]
ooh, missed this one. Thanks!

**Comment by Mimigris** [comment]
Hmmm, from what I've just tried on the continuous build, the issue seems to not be fixed (Saving with a changed tileset on a 2k game still loads the changed tileset while it should not), so I'm reopening it.

**Comment by Ghabry** [comment]
oooh. The tileset is not loaded?! I misread this. I thought the tile substitution is not loaded. This is what I fixed. >.>

**Comment by Mimigris** [comment]
> oooh. The tileset is not loaded?! I misread this. I thought the tile substitution is not loaded. This is what I fixed. >.>

Oh, sorry if i wasn't explicit enough when creating the issue. There was no issue with tile substitution (no save/load problem independently of the version of the engine), so it means that it will also have to be fixed.
