### ISSUE TITLE
Maniac: Move Picture command does not work correctly under specific conditions

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3078]
#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
In a map, a parallel process is used to continuously move a picture. It is done in three steps:
- The picture is displayed,
- The picture is moved for 0.5 seconds,
- And the script waits 0.5 seconds before returning to the first step and reinitializing where the picture is displayed.

![image](https://github.com/EasyRPG/Player/assets/108797333/14f829fc-1947-488c-a848-876a89cc3048)
![image](https://github.com/EasyRPG/Player/assets/108797333/bb1202b7-fb1b-4311-888a-f3c11bc4c6f1)

Currently when doing this with the continuous build of the Player while the game is considered as Maniac patch, the picture will stay at constant coordinates instead of being shown as moving (the move picture seems to be executed instantly instead of waiting, though the wait command does not seem to be ignored).

Here's a testcase: [MoveManiacIssue.zip](https://github.com/EasyRPG/Player/files/12507666/MoveManiacIssue.zip)
You should normally see the picture continuously move but this is not the case in the 0.8.0 EasyRPG maniac part. This issue was not present in version 0.7.0 when playing in Maniac mode, and is not present in the continuous build if the game is not set as Maniac.

Reported by Pizus on the EasyRPG blog and chat.

**Comment by Ghabry** [comment]
This wasn't broken before because "Duration from Variable" was just not implemented (but the timing was wrong because it took it as a constant)
