### ISSUE TITLE
Control Variables: Item 0 is Equipped should list the number of free equipment slots in your party

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3085]
#### Player platform:
Windows, 64 bits continuous build.

#### Describe the issue in detail and how to reproduce it:
When using the command Control Variables: Item 0 is Equipped, the RPG_RT will list the number of free equipment slots in your party. Currently EasyRPG does not support that and will always answer 0.

In an example here, I only have Alex in my party, and only two of the five equipment slots are used: the game answers 3 to this command.
![image](https://github.com/EasyRPG/Player/assets/108797333/0b386c5a-bb2b-4fa2-b384-66ee3bf08b6c)
![image](https://github.com/EasyRPG/Player/assets/108797333/feb49b2c-c9c6-4d62-b3a7-085066206d99)
![image](https://github.com/EasyRPG/Player/assets/108797333/dfa3c40d-da5f-4fd3-a31b-bbe70c373663)

**Comment by Ghabry** [comment]
This is only possible by external manipulation of the command (similiar to the "Vehicle Teleport" glitch).

I think this works because the command does no sanity checks and ID 0 is "no item" so checking for 0 counts the empty slots :D
