### ISSUE TITLE
Steamed Hams: Archive fails to open because of duplicated file

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3094]
#### Name of the game:
[Steamed Hams (...but it's RPG Maker 2003!)](https://lordbluerouge.itch.io/steamed-hams-but-its-rpgmaker2003).

#### Player platform:
Android, 64 bits continuous build.

#### Describe the issue in detail and how to reproduce it:
When trying to load a game that is stored in a folder with a conflicting name, like with Steamed Hams 2003, and that EasyRPG will not accept to launch it without unzipping it, trying to load it on the Android version will cause the app to exit, and reopening the app without resetting will bring the "this folder is not valid" message.
Adding a warning when trying to open the game when it cannot be opened directly on the Android game browser would be a good idea for cases like this.

**Comment by Ghabry** [comment]
Uhm. The bigger question is why it is crashing 😅

**Comment by Mimigris** [comment]
> Uhm. The bigger question is why it is crashing 😅

If you tried to open it without unzipping on the Windows version, those are the issues that would be displayed, so it's likely related to this.
![image](https://github.com/EasyRPG/Player/assets/108797333/5abce7cb-9c25-4cce-aca2-f485243477ea)

**Comment by Ghabry** [comment]
Oooh. It could be that a file can be multiple times in the zip archive (because files were replaced later) like we noticed with RTP assets in the lzh file .

**Comment by Ghabry** [comment]
Checked this again while finished the LZH support:

The archive contains a file "Steamed Hams 2003" which is the same as a folder name. No idea how this can happen (append to zip?) but the strategy "last file wins" also helps against this.
