### ISSUE TITLE
Maniac - Conditional Branch: Right after load is considered as false when loading a save from the load menu in Maniac, but is considered as true when doing so in EasyRPG

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3099]
#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
When using the Conditional Branch: Right after load in the Maniac Patch, it is considered as true right when used on startup or when loading a save that was done just before the conditional branch with the Load command. For some reason, the Maniac patch will not consider it as true if you loaded a save with the load menu and not with the load command, a bug that EasyRPG does not currently replicate.

**Comment by Ghabry** [comment]
Should this be really replicated? Imo a wrong implementation does not hurt here.

**Comment by Mimigris** [comment]
> Should this be really replicated? Imo a "wrong" implementation does not hurt here.

As long as it doesn't break games I think it can be kept as-is, similar to #3068 , it also make more sense to have it like that. I think it's still useful to have Maniac bugs or discrepancies be listed somewhere, similar to how we have one for RPG_RT bugs. Maybe it would make more sense to have everything of this kind on one issue?

**Comment by Ghabry** [comment]
please make this a comment here #1818
