### ISSUE TITLE
Settings: Incorrect input help text UwU

### ISSUE THREAD

**Issue by MikuChan03** [EasyRPG/Player#3104]
🎶 Hi 🎶

When watashi was using the new settings menu fow advanced stuffs, the title line was all wwong O.O
But aftew some weseawch, the pwoblem is wathew obvious.
In input_buttons.h, the kButtonHelp has 44 entwies, while InputButton and kButtonNames have only 42 (<- answew
to evewything ✨✨✨✨✨(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧✨✨✨✨✨)

The double entwies awe:
"Move up one page in menus",
"Move down one page in menus",
"Page up key",
"Page down key",

These awe all supposed to be fow
Input -> Key/Button mapping -> Engine -> Page Up
Input -> Key/Button mapping -> Engine -> Page Down

Miku wants to humbly suggest wemoving the latew two entwies, because only entwies in
Input -> Key/Button mapping -> Game
evew have the "key" suffix in the descwiption.

(Btw, what's the likelihood of none of these paths containing any 'w's ????)

This about fixie wixies the pwoblem xD
Bye! 💕

**Comment by jetrotal** [comment]
![image](https://github.com/EasyRPG/Player/assets/45118493/bb30c6f7-fafb-42ab-8f3c-fdc12bb55e61)

twanwkws fwow twew wepwowt
