### ISSUE TITLE
include-what-you-use

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#311]
This is related to EasyRPG/liblcf#118. For Player there are also some platform specific things, that iwyu can not deal with.
Analysis here: https://paste.xinu.at/wVmOJ/

---
The issue with the assertion failure is [fixed][1] in svn version, btw. Unfortunately it is unstable in other means.

[1]: https://code.google.com/p/include-what-you-use/issues/detail?id=150

**Comment by fdelapena** [comment]
There have been some cleanup at #505.

**Comment by carstene1ns** [comment]
Fair enough, the tool has been broken for me since then, so closing.
