### ISSUE TITLE
License might need games to be GPL if shipping EasyRPG, is that intended?

### ISSUE THREAD

**Issue by ell1e** [EasyRPG/Player#3119]
I'm not a lawyer so I could be wrong on all of this, but I've seen many discussions around such issues at least. As far as I know, when making a GPL infrastructure component that some other piece of software depends on, which EasyRPG being GPL licensed would be to games that depend on it, shipping that infrastructure component along with a release will then apparently, allegedly, IANAL, also require the piece of software depending on it to be GPL. If that is true, then one could only tell players to download and get EasyRPG separately to be on the safe side but not ship it, which obviously is a hurdle many players especially for commercial games won't be willing to put up with.

A simple solution would be e.g. the [Apache License 2](https://www.apache.org/licenses/LICENSE-2.0) which it seems like more clearly separates stuff from just using the interface and otherwise being separate, which would probably apply to games. Then again, I am not a lawyer, I can't really speak to any of this, but maybe you can find someone who is and ponder this problem.

(Unless it's intended of course that game developers don't ship EasyRPG right along to actually let people easily play their games of course!)

**Comment by Mimigris** [comment]
Hi, there is an issue open related to a license change (see #167 ) to avoid having the issues due to the current license that are problematic when publishing a game (eg. if a part of the engine is edited, it needs to be available, which is not compatible with the NDA code that would be used on a console or platforms that rely on editing the engine to include an API like Steam).
I have no idea if what you are fearing could be a thing here, but since the license change would solve it by using another license that is more free on this side, I think that it would not be a problem once changed, though for now it may be a gray area.

**Comment by ell1e** [comment]
MIT sounds nice and should probably be unproblematic (not that I'm allowed to speak on it anyway, since not a lawyer, but that is my completely uninformed thought). If any of my changes go in, I don't mind if  they're licensed as MIT, just to add that now since I just did a pull request.

**Comment by Ghabry** [comment]
Thanks for your constructive comment. I had a similiar discussion years ago with Ancurio (dev of mkxp, same idea as EasyRPG but for RPGXP) about this.

We also came to the conclusion that a game could be a "derived work" of the engine when the engine contains custom functionality used by the game.

This is another of many reasons why GPL just doesn't work if you are not going 100% open source. Any interaction of GPL with propreitary components is problematic.

Relicensing is planned soon (tm), the editor takes much longer than expected to release 😅 

The rest was already discussed in #167 so I would close this one here as a duplicate. Thanks for agreeing on relicensing. I put your name in that issue to track this better.

**Comment by Ancurio** [comment]
FYI there are at least a dozen GPL-compliant games using mkxp released on Steam, many of them with SteamAPI (achievements etc) supported:

https://store.steampowered.com/app/1182620/Impostor_Factory/
https://store.steampowered.com/app/420530/OneShot/
https://store.steampowered.com/app/335670/LISA_The_Painful/
https://store.steampowered.com/app/1488200/Symphony_of_War_The_Nephilim_Saga/

The way Steam features are used is via [steamshim](https://github.com/icculus/steamshim), which is GPL compliant as it uses a method [directly outlined in the license FAQ](https://www.gnu.org/licenses/gpl-faq.html#MereAggregation) (socket/pipe communication).

In 2021, I had an idea for a GPL modification similar to the LGPL, that would allow normally GPL-licensed software to run in environments where NDAs or other compilation restrictions are imposed not by the software author, but by the platform itself. I haven't been able to make progress on this front yet, but I plan on writing a detailed explanation on how this license would work, though to actually create it, I'd need to involve a lawyer.

**Comment by ell1e** [comment]
For what it's worth, I filed this post under the assumption that for many and possibly even the majority of games it *would* be possible to be licensed as GPL if the creator wanted to. But most game makers would be hesitant to, including myself, for various reasons so that would limit the reach of EasyRPG. At the end of the day, still your decision of course and there's no right or wrong.
