### ISSUE TITLE
Regression - the game She Awaits locks you in a wall when using the bed due to a move route being incorrectly processed in the continuous build

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3129]
#### Name of the game:
[She Awaits (version 0.02 or version 0.025c)](https://rayinpixels.itch.io/she-awaits-0025c).

#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
After starting a new game, use the bed in your room. Normally, the game should move you on it with a move route that disables collision, moves you right and reenables it, and then teleports you to another map.
![image](https://github.com/EasyRPG/Player/assets/108797333/3c87ef9b-f19e-4226-9e0b-94cd1deab352)
In the continuous build however, the move route is processed again on the new map, and since a wall is present on your right, the game locks you in a wall, making the game unplayable.
This issue was not present in the version 0.8.0 of the Player nor in a continuous build that I had from the 22th of October, so the regression must have likely occurred with the pull request #3120 .

**Comment by ell1e** [comment]
I'm downloading the game right now, I'll test and debug it immediately. My deepest apologies for possibly being responsible for this regression.

**Comment by ell1e** [comment]
I can reproduce the bug and I can confirm 7221769f8dbb5a696b559aa89b1feacda462c100 works and https://github.com/EasyRPG/Player/commit/a33e699a38d3efc886ccf3a70f434b52e6376716 is broken, making my change clearly the responsible one. I'm looking at it in the debugger right now.
