### ISSUE TITLE
The Shift and Debug Menu keys can be used to select a game in the game browser menu while they should not

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3139]
#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
In the game browser menu of the Player, the keys with the function Shift and Debug Menu (by default mapped to Shift and F9 respectively) can be used to select a game while hovering it (example picture of the menu).
![screenshot_0](https://github.com/EasyRPG/Player/assets/108797333/6c901d0e-bd3e-43c6-a59b-faf4c825d088)

Normally, only the Decision key (Space, Enter, Z...) should be able to be used for that. Note that those keys are only able to be used in said menu for selecting a game or for returning to the previous directory, not to select Settings or Exit, and that the function of the Debug Menu key works independently of if the Testplay Mode is active or not.

**Comment by Ghabry** [comment]
Ah this is what you mean. This is by design: It will launch the game in test play mode.

**Comment by Mimigris** [comment]
As mentioned, this is not a bug but a feature unlike what I thought, allowing you to launch the selected game in playtest mode even if it was not activated before. This was not properly documented so I've added it to the Button mapping page of the wiki: https://wiki.easyrpg.org/user/player/buttons#game-browser
Closing this since it's not an issue as such.
