### ISSUE TITLE
RM2K: Enemy AI may ignore behavior conditions, depending on attack pattern Ratings

### ISSUE THREAD

**Issue by zankplus** [EasyRPG/Player#3146]
Hi again. I was working on my own game and noticed that enemy attack patterns weren't behaving as expected. It seems that enemy AI will ignore conditions for behaviors if the rating is sufficiently high. For instance, in a fresh RM2K project, this Slime will Normal Attack about half the time even though the switch which that action depends on is turned off. This unexpected behavior seems to occur regardless of the exact condition type; I've observed it with unsatisfied Switch, Turn Count, and Group Size conditions, and I suspect it occurs with the others although I've only tested those three.

![image](https://github.com/EasyRPG/Player/assets/12615965/235ac277-5a11-43df-9e62-633f57950063)

However, it only seems to occur for certain Rating values. For 100 vs 50, 100 vs 25, and 100 vs 10, the enemy seems to consistently behave as expected. But for values like 100 vs 1, 100 vs 9, 20 vs 1, or 10 vs 5, I observed illegal behaviors. It appears to me that something about setting a Rating below 1 enables higher-rated actions to supersede it, even if their conditions aren't met... As far as I've tested, this behavior doesn't exist in RPG_RT.

This should be quick and simple to replicate for yourselves using the information provided, but let me know if you need me to post game files, videos, or player logs.

Thank you for all your hard work.

**Comment by Ghabry** [comment]
I'm surprised this wasn't found earlier. Invalid actions get internally a rating of 0. The possible actions are based on the valid with the highest rating (e.g. when 50 is highest possible then all valid actions in range [40, 50] are considered).

This bug happens for all ratings <= 10. Fix is simple. Will add this in a PR later.

```cpp
	if (max_prio) {
		for (auto& pr: prios) {
			if (pr > 0) {
				pr = std::max<int>(0, pr - max_prio + 10);
			}
		}
	}
```
