### ISSUE TITLE
Regression - Yume 2kki displays a warning message when waking up, and the Sound Room and wallpaper menus no longer work

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3161]
#### Name of the game:
Yume 2kki, version 0.121f (though any modern version should work).

#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
Either:
- Use the bed in Urotsuki's Room, then open the menu and wake up: this should display warning messages while it should not
![screenshot_207](https://github.com/EasyRPG/Player/assets/108797333/178123c4-42e1-4952-aeb1-922fede1bc2f)
- Go on the computer in Urotsuki's Room and open the Music (Sound Room) icon, or Tools then Wallpapers and try to see your list of wallpapers: the first one will display a warning message and bring you on a black screen instead of leading you to the Sound Room, while the latter will not open the wallpaper menu and will instead display that your wallpaper count is 0/0.

**Comment by Ghabry** [comment]
Thanks for the report. I bisected it and this one was dumb:

During the refactor for the Maniac stuff I deleted the accidentally deleted the line ``actor->SetName(ToString(com.string));`` from ``ChangeHeroName``.
