### ISSUE TITLE
Door textures are bugged in all games.

### ISSUE THREAD

**Issue by Pokemel** [EasyRPG/Player#3196]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Android12

#### Attach files (as a .zip archive or link them)
 - Probably every game

#### Describe the issue in detail and how to reproduce it:I downloaded easyRPG Player because I wanted to play games like nobita_hazard, nobita_hazard2, and 怪異症候群. When I actually played the games, the doors were like mosaics and bugged out. Because of that, I couldn't progress in the game and couldn't finish it. The app was up to date and the files didn't seem to be corrupted, and I've re-downloaded the games many times, but it didn't fix the _problem._

![Screenshot_20240314_235953_EasyRPG Player](https://github.com/EasyRPG/Player/assets/164508327/e53b2ded-6587-49c9-8761-bac571c64d56)

**Comment by Ghabry** [comment]
you havn't installed the RTP (Runtime Package). Place the assets from RTP2000 and RTP2003 in the "rtp" subdirectory in the easyrpg folder.
