### ISSUE TITLE
Events seems to reset when opening and closing Debug Menu.

### ISSUE THREAD

**Issue by jetrotal** [EasyRPG/Player#3210]
#### Name of the game: 
Scrolling Platform Prototype

#### Player platform:
Tested on Windows

#### Attach files (as a .zip archive or link them)
 https://qbk.itch.io/rm2k3-spp
 
#### Describe the issue in detail and how to reproduce it:
Every time I open and close the debug menu in test play, 
the game seems to restart its event list. 

In the case of the game attatched, the game resets some important variables and switches ( I guess this is related to how its events were made).

https://github.com/EasyRPG/Player/assets/1331889/064a2c11-e3db-4e2d-8b69-2de3af7d7dab

**Comment by Ghabry** [comment]
Cannot reproduce this.

I use the nightly from here and it doesn't port me back after opening the debug menu.

https://ci.easyrpg.org/view/Player/job/player-win64/

**Comment by jetrotal** [comment]
IT WAS ABORT EVENT FAULT:
![image](https://github.com/EasyRPG/Player/assets/45118493/441f686d-34fb-4b0e-a011-b4f1cb10bbe3)

Sorry about that non-issue. I never knew about this button.

Made me think about two other things:
A - I'd put this type of feature inside Debug Menu, instead of a key.
B - Would be nice if I had an alert about repeated keys through different inputs (it Could be an alert, or the places where repetition happens could flash yellow).

**Comment by jetrotal** [comment]
Ok, since abort event key is a thing from rpg rt, I'll create one just for the alert.
