### ISSUE TITLE
Witch's Heart Charlotte battle

### ISSUE THREAD

**Issue by Guselan** [EasyRPG/Player#3247]
Hello, there's a bug where a player cannot escape in the beginning of the chasing battle with Charlotte, on the first day.

#### Attach files (as a .zip archive or link them)
 - Charlotte L1
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by Ghabry** [comment]
Is that the sequence where you must run away?

To run you must hold the shift key while avoiding the obstacles. This is unfortunately a bit hard to do using touch.

**Comment by Ghabry** [comment]
Closing due to lack of feedback
