### ISSUE TITLE
Severe rubberbanding in Yume 2kki's platforming section (3D Underworld)

### ISSUE THREAD

**Issue by Desdaemon** [EasyRPG/Player#3254]
#### Name of the game:
Yume 2kki v0.124g
#### Player platform:
Tested on Windows 11, Emscripten (ynoengine fork)

#### Attach files (as a .zip archive or link them)
[Map1884.zip](https://github.com/user-attachments/files/16652798/Map1884.zip)

#### Describe the issue in detail and how to reproduce it:
Enter 3D Underworld (MAP1884, savefile loads directly into it). Heavy stuttering occurs throughout the map, and is especially severe when the player image is situated between tile boundaries. This issue is not observed on RPG_RT.

Suggested fix is to reset the jumping flag unconditionally for `Game_Player::MoveTo`:
```diff
diff --git a/src/game_player.cpp b/src/game_player.cpp
index 48091e96..f99e88e2 100644
--- a/src/game_player.cpp
+++ b/src/game_player.cpp
@@ -159,11 +159,12 @@ void Game_Player::MoveTo(int map_id, int x, int y) {

                // This Fixes an RPG_RT bug where the jumping flag doesn't get reset
                // if you change maps during a jump
-               SetJumping(false);
+
        } else {
                Game_Map::SetPositionX(GetSpriteX() - GetPanX());
                Game_Map::SetPositionY(GetSpriteY() - GetPanY());
        }
+       SetJumping(false);

        ResetGraphic();
 }
```
This bugfix was first introduced in 2a69065ec6138426c2b2a389ae6ca401f8763d6c which used to be applied unconditionally, albeit unintended and was relocated to its current location in b3d0505b5.

Some additional notes:
- There exist several other platforming areas with a similar gimmick, but the issue is most severely experienced here.
- While not fully understood, the map author uses the `SetVehicleLocation -1` and `SetMoveRoute` commands in a hot loop to simulate sub-tile scrolling. In the map, this is event ID 3 (":ﾄﾞｯﾄ単位スクロール").

A before and after of applying the diff:

https://github.com/user-attachments/assets/c249da68-899f-4484-bd3c-4417ffd16360

https://github.com/user-attachments/assets/7696707e-f20b-449a-b13f-48a4d0199fd9

**Comment by Desdaemon** [comment]
Additional observation: adding a check in `Game_Character::MoveTo` (without the diff) to not truncate remaining steps if jumping fixes the rubberbanding, but does not prevent the player location from being shifted every few moments.

```cpp
void Game_Character::MoveTo(int map_id, int x, int y) {
	data()->map_id = map_id;
	// RPG_RT does not round the position for this function.
	SetX(x);
	SetY(y);
	if (!IsJumping()) // if this line is added
	SetRemainingStep(0);
}
```

**Comment by Ghabry** [comment]
I was able to replicate this by doing two tight jumps combined with a SetVehicleLocation -1.

In the current Player the map is incorrectly scrolled.

Applying your suggestion fixes the scrolling _but_ the timing is now wrong: I put a save right after the start of the 2nd jump and it is now 4 frames later than in RPG_RT :shrug:

**Comment by Ghabry** [comment]
I will accept your patch for the special case "Vehicle = -1". I think the fix is incorrect but somehow fixes the issue.

Locking this to "Vehicle = -1" will only affect games that are jumping AND move the party with SetVehicleLocation around. So it fixes the flicker in Yume2kki and cannot really break other games until somebody wants to dig for hours into the code what is _really_ going on...
