### ISSUE TITLE
Yume 2kki - Graphical issue when updating events' page in Tomb of Velleities

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3256]
#### Name of the game:
Yume 2kki version 0.124h.

#### Player platform:
Windows, 64 bits continuous build of the player.

#### Describe the issue in detail and how to reproduce it:
Create a game, then once you can freely move, teleport to the map 1204 ([Tomb of Velleities](https://yume.wiki/2kki/Tomb_of_Velleities)) by using the playtest mode of the engine/debug mode of the game. There, wait a bit and look at the animation of the seaweed tiles: on RPG_RT, they are composed of two frames, and are events using the ChipSet tiles, having one page per frame which is changed each 0.4 second through the change of the variable 1 in a parallel process. Despite this, on EasyRPG, the tiles sometimes change to something else completely different which looks odd when looking at it.
Code of the parallel process (EV0004 at (2, 1)):
![image](https://github.com/user-attachments/assets/32b35aa3-cf95-448b-ac16-bc6e9f896a9d)

Example code of a seaweed tile having issues (EV0042 at (17, 14)):
![image](https://github.com/user-attachments/assets/8630082c-e368-43a5-b5d5-e6a922560d4b)
![image](https://github.com/user-attachments/assets/1056ba8a-20bd-4fa1-bdda-34fc1816dc50)

Video of the difference between RPG_RT and EasyRPG:

https://github.com/user-attachments/assets/33589d5a-120a-411e-aa3c-db37e863ea4d

Reported by the 2kki community, and video recorded by Desdaemon.

**Comment by Desdaemon** [comment]
Additional observation: the events animate normally as long as the player doesn't move, and starts behaving erratically after that:

https://github.com/user-attachments/assets/a78bc1a1-0dca-47d1-8837-4d5e48e1019e

**Comment by Desdaemon** [comment]
The cause is an improper use of a pointer as a cache key here: https://github.com/EasyRPG/Player/blob/68757ea396267f0526ce4243edaf2a3ff4b372be/src/cache.cpp#L457

Since there are no guarantees about which pointers are still live at any point, a cache key may mistakenly grab the bitmap of another unrelated sprite.
