### ISSUE TITLE
Webplayer: Load and Get Save Info commands don't put the game in wait before loading the assets required, leading to visual issues

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3271]
#### Player platform:
Webplayer.

#### Describe the issue in detail and how to reproduce it:
In a game set as using the Maniac patch, use the command Get Save Info to retrieve the FaceSet of a member of the party. If the save file gives you one and that the file hasn't been loaded in the past during the session, the graphic will not be loaded, and will not try to be displayed even after waiting. Ideal solution here would be to handle it like a Picture displayed with the Show Picture command.
In a similar case, loading a save file through the Load command will not load the graphic of the ChipSet of the new map unless it has already been loaded in the past, rendering the map all black until the map is reloaded, and waiting will not do anything about that. Ideal situation would be to put the game on halt until the ChipSet graphic is loaded here.

**Comment by Ghabry** [comment]
cannot reproduce the issue in ``GetSaveInfo``. It correctly creates the request here. This uses the same code as the normal picture showing code.

**Comment by Mimigris** [comment]
Did you made sure that the FaceSet in question was not loaded at all beforehand? In my case, it was about a game where the default party had no actor (so no FaceSet loaded), and the GetSaveInfo was used while the party hadn't changed at all either.

**Comment by Ghabry** [comment]
The other one was actually not the ChipSet not loading but the Player accessing a deleted map. (and the map was never replaced with the real one). Patch is coming.

In the web player this will not crash due to lack of memory protection in the WASM memory buffer.
