### ISSUE TITLE
Maniac: Get Save Info command doesn't set the transparent colour flag for FaceSets displayed through it

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3272]
#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
On a game set as a Maniac patch game, use the command Get Save Info on a valid save file which contains in the party a member whose FaceSet uses a transparent colour in it. After this, use a Move Picture command to make your FaceSet be displayed on screen. You should notice that the transparent colour will not be set as transparent in the Player (see the green on the picture), while it will properly be set as transparent on Maniac's side.
Left, RPG_RT Maniac, Right, EasyRPG. The four pictures are displayed through the command Get Save Info (also, ignore the fact that I used Niko for testing).
![image](https://github.com/user-attachments/assets/3d6cc324-721a-4e30-9ebf-70ae430dc90c)

**Comment by Ghabry** [comment]
Can you check what happens in MP when the FaceSet is loaded into a picture slot that already has a picture in it?

Try with a picture that has "Transparency" active and one without.

**Comment by Mimigris** [comment]
Doesn't seem to affect how the picture with Get Save Info is displayed (settings from the previous picture seems to be correctly overwritten by always the same settings in Maniac, which are the following from said picture minus the filename, cell position and picture slot)
![image](https://github.com/user-attachments/assets/6aea1c16-b014-4801-830e-ba0d40f71232)

**Comment by Ghabry** [comment]
hm then this was changed from the "original" Maniac Patch (the one with the patches directly applied to RPG_RT) which reused some of the data.
