### ISSUE TITLE
Regression: Entering in the bedroom in Yume 2kki's Nocturnal Grove displays a black screen

### ISSUE THREAD

**Issue by Mimigris** [EasyRPG/Player#3274]
#### Name of the game:
Yume 2kki (version 0.125 patch 8).

#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
Start a new game, then once you can move, try to reach [Nocturnal Grove](https://yume.wiki/2kki/Nocturnal_Grove)'s bedroom by following the directions provided on the wiki. Alternatively, once you can move, teleport to Map 1131, at the coordinates 102, 10. Once there, move right to enter in the bedroom. After a little fade in, the screen should turn black on the continuous build, while it should not in normal gameplay.
I tested this issue on the builds of #3251 and #3259 and this issue is present in 3259 but not in 3251, so I suspect said issue was brought as part of the changes done in 3259.

**Comment by Desdaemon** [comment]
Might be similar to a bug on ynoengine where the nametags were using cached sprite effects without a sprite ID, causing duplicates.

**Comment by Desdaemon** [comment]
Thank you, I'll try to compile and test this patch later today.

**Comment by Desdaemon** [comment]
The fix works for ynoengine, however since there are many places that might require a proper ID I've also opted to set a default ID based on the pointer value of the `BitmapRef`.
