### ISSUE TITLE
New buttons doesn't work on browser ported games

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#3280]
Related to: https://github.com/EasyRPG/Player/issues/3279

I've recently ported a new browser game with the recent files that @Ghabry pointed out to me as `data-key-code` is obsolete.
However, with `data-key-code` the button (1 in this case) used to work, now it does not.

I have tested it before and after the changes made to `updateTouchControlsVisibility` on different sessions and devices to check.

Link: https://netherwareentertainment.com/online/?game=powerchars

**Comment by Ghabry** [comment]
According to this testing website https://w3c.github.io/uievents/tools/key-event-viewer.html

The key is called ``Digit1`` for the ``1`` and ``Numpad1`` for the key on the Numpad. Both should work.

**Comment by Br4ssman** [comment]
Thanks,

it was that.
