### ISSUE TITLE
How To Use Options?

### ISSUE THREAD

**Issue by Janter1603** [EasyRPG/Player#3285]
I Don't Know How to use The Options In The Manual,

**Comment by Ghabry** [comment]
Sorry I do not understand what you mean with options.

**Comment by Janter1603** [comment]
> Sorry I do not understand what you mean with options.

https://wiki.easyrpg.org/user/player/command-line

**Comment by Ghabry** [comment]
this is not an issue. I will answer in the community (https://community.easyrpg.org/t/how-do-i-use-the-options-from-the-options-manual/1542)
