### ISSUE TITLE
StringPictures Glitch - Display Text gets confused whenever a stringPic has changes in its color:

### ISSUE THREAD

**Issue by jetrotal** [EasyRPG/Player#3287]
#### Attach files (as a .zip archive or link them)
[easyrpg_stringpic problem.zip](https://github.com/user-attachments/files/17607745/easyrpg_stringpic.problem.zip)

#### Describe the issue in detail and how to reproduce it:
I have a bunch of of string pictures attatched string variables:
![image](https://github.com/user-attachments/assets/af4c6480-fea0-43bc-adbf-6b0ae49bf2e2)

Everything should work fine with it. But whenever I manipulate the RGB colors of the string pictures, the text content gets all messed up:
![image](https://github.com/user-attachments/assets/e8e2ad9a-e9ef-44dc-8f21-3786ffefdac5)

Here's my RGB settings:
![image](https://github.com/user-attachments/assets/5b4f3569-c08f-4f6a-b634-27740dc403c2)

An .exe showcasing the issue was also included.

**Comment by Ghabry** [comment]
Sounds like another caching issue. I didn't think about string pictures and they do not have a filename...
