### ISSUE TITLE
Monsters not shown in the "The Observer" game

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#330]
[The Observer](http://www.hellsoft.net/descargas/juegos/rm-2000/completos/TheObserverF.7z) uses monster group battle commands to spawn all monsters in battle scene with some style.

Looks like battle interpreter is not supporting this yet, but battles are still playable with invisible monsters.

**Comment by fdelapena** [comment]
Test case:
https://easy-rpg.org/play/?game=ae&battle-test=1

**Comment by Ghabry** [comment]
In Observer it works. AE has a different interpreter problem. Opening a new issue to track this.
