### ISSUE TITLE
Maniacs - Player crashes when reading substring of non-existant string variable. 

### ISSUE THREAD

**Issue by elsemieni** [EasyRPG/Player#3305]
Tested on Player master.

Continuing reporting bugs from a WIP features, found other sort of issue, product of reading not-yet-defined string variables. 
It's quite simple:
When executing a string split from a non-existant string (Let's say T[0127] and T[128]for example) ....
```
@> Control String Variables: T[0128], Assign, Substring T[0127] from 1 (1 chars)
```
Or in TPC notation
```
t[128] .asg  .subs t[127], 1, 1
```
... , seems it tries to execute anyways. Using an index 0 seems to read zeros, but more bigger index makes player crash. 
Sure, I'm guessing here that doing string checking is more complicated rather than variables and switches, but seems that's the origin cause. 
Probably there will be more related bugs regarding out of bounds or non existant string variable (or other Maniacs related resource) reading out there.

**Comment by Ghabry** [comment]
Hm I extended the string var test now with out of bounds values and yeah I get lots of crashes and softlocks :sweat_smile: 

Also noticed that when using a negative index Maniacs seems to index from the back (like Python does).
