### ISSUE TITLE
Encoding Issue on Nintendo Switch Browser for Arabic and Polish Webpages

### ISSUE THREAD

**Issue by ishwarkatwe** [EasyRPG/Player#3315]
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Linux, Android, ... Nintendo Switch Browser

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

We am experiencing an issue with the Nintendo Switch browser when trying to load webpages in Arabic and Polish languages. The webpages display encoding problems, with text appearing garbled or incorrectly rendered.

Could you kindly assist in resolving this matter? Specifically, I would like to know if there are any browser settings or updates that can fix this encoding issue.

**Comment by Ghabry** [comment]
We are not a web browser, please call Nintendo about this matter.

Locking this issue as Spam. You get a :yellow_square: card (Warning) for this.
