### ISSUE TITLE
Android: No games found in storage path

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#332]
As reported at http://rpgmaker.net/forums/topics/11093/?post=564996#post564996

**Comment by fdelapena** [comment]
Maybe replacing:
```cpp
 path = Environment.getExternalStorageDirectory().getPath() + "/easyrpg/games";
```
with:
```cpp
path = Environment.getExternalStorageDirectory().getAbsolutePath() + "/easyrpg/games";
```

**Comment by Ghabry** [comment]
As reported at http://rpgmaker.net/forums/topics/11093/?post=611720#post611720 it was a Layer 8 problem
