### ISSUE TITLE
Passable upper layer tiles with "star" terrain attribute shows player and events character head

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#333]
Character's head is visible when it is in movement when walking in vertical, from up to down and from down to up when passing below "star" tiles.

Looks like RPG_RT always shows the whole player and charset-based events below star tiles (even when the "invisible" first upper tile is opaque in some tilesets).

[Test case](https://fran.cr/owncloud/index.php/s/MHE6leSXZcfoCH8/download) download available.

This also happens with events with character graphics moving around these star tiles.

**Comment by Ghabry** [comment]
It's possible that this was fixed by the looping maps stuff merged yesterday. Modified some Z-values.

**Comment by fdelapena** [comment]
Tested, works better: now the head is not visible when the character stops, but it is still visible when it is in movement when walking in vertical, from up to down and from down to up.
