### ISSUE TITLE
Support serif fonts when MS Mincho is selected in database or in game from command

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#352]
Currently shows the same sans-serif font and some games look better with serif based fonts in context, e.g. Yume Nikki.
Maybe requires updating Shinonome configuration.

**Comment by carstene1ns** [comment]
This seems directly related to #1143.

**Comment by fdelapena** [comment]
> This seems directly related to #1143.

Yes, but the PR does not fix the serif style. RM2000 and RMG2000 fonts are just different styles, but at least the sans serif version looks more like Gothic. @rohkea mentioned Shinonome Mincho does not include a serif version for Latin glyphs, then should be designed or import some free 6x12 serif font more similar to MS Mincho.

**Comment by carstene1ns** [comment]
Ah, ok... I thought this has been resolved with https://github.com/EasyRPG/Player/pull/1143/commits/0f30da5ca868f0ff407bfd00e743670468d1cdff.

**Comment by Ghabry** [comment]
Fixed by adding the tty0 font in #1143
