### ISSUE TITLE
Draw black content when there is no content by default

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#354]
This brings some transition bugs and transparency issues with system background color, e.g. when going to system menu and returning to empty map scenes will render the system background color. When transitioning to fade out will show the system background color, too.

**Comment by Ghabry** [comment]
Any idea if this got fixed already?

**Comment by fdelapena** [comment]
This bug is not happening currently, but it is now showing a white (?) background instead. It should be black. There shouldn't try to load an invalid empty-string named ChipSet warning, so a checkerboard shouldn't be displayed.
RPG_RT behaves different:
RPG_RT won't crash when System, GameOver, ChipSet and Title are undefined. Vehicle file reference can also be empty.
Player shouldn't try to load an empty string file for them. It should an empty black (or transparent?) bitmap in this case. Check the [current fix for System](https://github.com/EasyRPG/Player/blob/master/src/cache.cpp#L260-L269).

To reproduce this ([test case available](https://fran.cr/owncloud/index.php/s/9bA5PvibaVFMRCg/download)):
- Create new project
- Close project
- Remove RPG_RT.ldb
- Open project
- F8 (Database)
- Save
- F8 (Database)
- Set a System for easier navigation and (optionally) set some text strings.
- Save
- Test game

**Comment by Ghabry** [comment]
Is this fixed?

**Comment by fdelapena** [comment]
About the tileset: it is black as expected when unset now. :+1:
However, when the tileset is set but missing, the render is white instead of a checkerboard, but not important imo.
