### ISSUE TITLE
Map transition make wait the parallel process/auto event

### ISSUE THREAD

**Issue by gadesx** [EasyRPG/Player#356]
Problem: If you have a map, when you start and it haves in an event:
Change color: 0 0 0 0 (black) 0.0s wait.
When you play this map, in RPG Maker you don't see the map but in easy
only is processed when the animation of the transition is finished.

Test case added, start in "Test case 1 map"

http://dl.dropboxusercontent.com/u/22524283/temporal/Tests%20varios.rar

**Comment by fdelapena** [comment]
This issue seems to be fixed already.
