### ISSUE TITLE
Name scene should show upper 7 bit characters for current game encoding only

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#364]
Setting japanese glyphs for a non-japanese game will show mojibake after saving and loading due to encoding conversion.

Currently it lacks support for non-japanese encodings. Glyph list proposal for missing encodings are welcome.

**Comment by fdelapena** [comment]
Because name scene is game language aware, users from the same encoding might use their own proper name written in their own language (when game codepage allows it), even when the game is written in a different language. E.g. in Catalonia there are common names in Catalan (e.g. Vicenç, Lluïsa) and they speak both Catalan and Spanish and both are official in Catalonia. I think it is worth to have multiple hero name glyph pages (if needed) for each codepage to include them even when there aren't known games written in these specific languages.

For CP1252, I know at least:
- Spanish (ÁáÉéÍíÓóÚúÜüÑñ)
- Catalan (ÀàÉéÈèÍíÏïÓóÒòÚúÇç and middle dot · ) — e.g. "Apel·les", "Apol·lo", "Camil·la", "Priscil·la"...

**Comment by rohkea** [comment]
This is different for non-Latin scripts.

Names are adapted for each language and are not expected to contain letters not in the language (e.g. Tatar name Җәмилә/Cämilä would be written Джамиля/Džamilia in Russian and Джаміля/Džamilia in Belarusian; Russian named Тимур/Timur becomes Цімур/Cimur in Belarusian). It would be **extremely** strange to encounter Җ or Ә in Russian, or И in Belarusian text.

For Cyrillic script, ideally, the text input window should be dependent only on the language of the game.

**Comment by fdelapena** [comment]
We could use ICU language detection feature for liblcf in `reader_util.cpp` after line 129:

```c
    const char *language = ucsdet_getLanguage(match, &status);
```

This will return language ISO code for the detected language (where possible) or empty string if failed. The name scene could have all language pages for the current codepage and prioritize to show first the related glyphs from detected language. Having other glyph options for other languages may still worth because the language detection is not fully reliable by its nature.
