### ISSUE TITLE
Battle animation vertical center offset is not working

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#365]
Test case: run [Wadanohara and the Great Blue Sea](http://vgperson.com/games/wadanohara.htm) game with `--start-map-id 4` (Sea Witch)

Battle animation ID 132 (SeaWitchBlink) has the Y coordinate parameter value set as (centered).

![Without animation](https://cloud.githubusercontent.com/assets/174885/5155125/184e5e8a-723f-11e4-85c4-75aff27e250d.png)

![With animation](https://cloud.githubusercontent.com/assets/174885/5155129/35bed756-723f-11e4-92ed-08e11ad36a24.png)

**Comment by Ghabry** [comment]
Fixed by #574
