### ISSUE TITLE
Change HP battle command should be able to kill a battler

### ISSUE THREAD

**Issue by Zegeri** [EasyRPG/Player#380]
The battle commands Change Monster HP and Change Character HP can reduce any battler HP to zero, as long as the options "HP reduction can kill target" is checked in RM2k3 or "Impossible Death" is unchecked in RM2k. This should trigger a death animation.

**Comment by Ghabry** [comment]
Death anim still not working, but killing does.

**Comment by carstene1ns** [comment]
`Patch available`.
