### ISSUE TITLE
Player doesn't generate some window properties when started in full screen mode

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#383]
This makes some display issues at least on Linux and Windows 8.1 when switching to window mode.
Related: #179

**Comment by carstene1ns** [comment]
This one got mostly fixed by #792, the rest is `WontFix` (→ #179 - SDL2 specific bug) for now.
Maybe when we have another UI besides SDL someday this will not be an issue anymore.
IMO we could close this and reopen #179 instead.

**Comment by carstene1ns** [comment]
This one should be fixed by #1252.
