### ISSUE TITLE
Ib: segfault when trying to load a save from the eye drop room

### ISSUE THREAD

**Issue by MatthieuMB** [EasyRPG/Player#384]
In Ib when trying to put the eye drop in the eye a choice dialog is supposed to appear but is skipped. All I got was "um… Ib, what are you doing?" .Of course, the game is then unplayable.

I'm using last version of easyRPG, compiled from this repository with debian Gnu/Linux.

Also, there is a segfault when trying to load a save from the table of this room and only this room.

**Comment by fdelapena** [comment]
8cb3d84 has been merged into master.

**Comment by fdelapena** [comment]
@MatthieuMB. The savegame loaded and works for me here. I guess this got fixed somewhere. Please reopen if still not working for you.
