### ISSUE TITLE
Spell drain not implemented

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#397]
Spells draining magic from the target and giving it to the source don't work

Test case "Blut saugen" spell in Vampires Dawn:
> In this game the Vampires have the ability to suck blood in the battle (from an opponent which has blood), but after using the ability no blood is gained, so this attack is useless.

Reported by Darkztar

**Comment by CoreBerlin** [comment]
Is that Issue fixed allready? I just downloaded this EasyRPG Player and tried Vampires Dawn, but this issue "Blut saugen" is still not working

**Comment by Ghabry** [comment]
Fixed by #808
