### ISSUE TITLE
RPG2k Battle: Sometimes spells are casted again in the next round

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#400]
Sometimes (multi-target) spells are casted again when the next round starts before executing the new command.
No idea how this can happen, each Battler only has one slot for Battle actions o.O

> Sometimes (not always) the hero uses the ability from the last round before he executes the new order (a new one or the same). So it happens that the hero attacks twice in a round. 

Reported by Darkztar

**Comment by Darkztar** [comment]
Maybe this helps:
![screenshot_2015-01-27-17-58-09](https://cloud.githubusercontent.com/assets/10723704/5922862/3ae58dee-a64f-11e4-899a-c401ff001498.png)

It seems that the enemy casts the spell the second time, but also the enemy recieves the damage xD

**Comment by Ghabry** [comment]
I guess this got fixed already? Couldn't observe this behaviour anymore.
