### ISSUE TITLE
Vampires Dawn: Summoning creatures and transformations

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#402]
Vampires Dawn.
In this game you can summon a 4th character that temporary lasts for a few minutes.

> If the map screen changes (e.g. new room) so all summoned creatures like Golem and skeleton are summoned again. Also if the here is transformed in a wolf or a bat, so the transformation is done again. It seems not to take any resources.

Reported by Darkztar

**Comment by Darkztar** [comment]
I have to correct this bug report: 

Normally a summon should take blood and soulstones. Now it takes only Soulstones and no blood.

This is very heavy, because after each change of the map the summon is done again and you lose every time Soulstones.
