### ISSUE TITLE
Random crashes in battle

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#405]
Will try to get a memory dump from him.

> Sometimes the game crashes in the fight after the character takes or gets damage. It freezes and the game crashes.

Reported by Darkztar

**Comment by Darkztar** [comment]
Here is a save file and 2 dumps: uploaded.net/file/qkrpfg3b

**Comment by Ghabry** [comment]
Not relevant for this but the savegame doesn't load in RPG_RT, only in Player... I love that save format :/

**Comment by fdelapena** [comment]
I guess your map or db save count mismatches. Retry with a clean game version if apply. RPG_RT won't load it with different map save count.
