### ISSUE TITLE
Crash at start on Mac OS

### ISSUE THREAD

**Issue by BlisterBoy** [EasyRPG/Player#407]
Here is the error message :

Process:               EasyRPG_Player [15237]
Path:                  /Users/USER/Downloads/*/EasyRPG_Player.app/Contents/MacOS/EasyRPG_Player
Identifier:            EasyRPG_Player
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           EasyRPG_Player [15237]
User ID:               501

Date/Time:             2015-01-28 12:51:45.778 +0100
OS Version:            Mac OS X 10.10.1 (14B25)
Report Version:        11
Anonymous UUID:        58675858-6C36-FD67-C52A-3E0846618403

Sleep/Wake UUID:       F2C15999-440B-44C5-9EC4-DADADA89AEB0

Time Awake Since Boot: 8400 seconds
Time Since Wake:       4600 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/libiconv.2.dylib
  Referenced from: /Users/USER/Downloads/*/EasyRPG_Player.app/Contents/MacOS/EasyRPG_Player
  Reason: Incompatible library version: EasyRPG_Player requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0

Binary Images:
    0x7fff61d7d000 -     0x7fff61db3837  dyld (353.2.1) <4696A982-1500-34EC-9777-1EF7A03E2659> /usr/lib/dyld
    0x7fff970e3000 -     0x7fff971d5ff7  libiconv.2.dylib (42) <2A06D02F-8B76-3864-8D96-64EF5B40BC6C> /usr/lib/libiconv.2.dylib

Model: MacBookPro11,1, BootROM MBP111.0138.B11, 2 processors, Intel Core i5, 2.6 GHz, 8 GB, SMC 2.16f68
Graphics: Intel Iris, Intel Iris, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736453120
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.15.124.12.10)
Bluetooth: Version 4.3.1f2 15015, 3 services, 19 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500,28 GB
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2

**Comment by Ghabry** [comment]
Try updating your libiconv with brew

**Comment by fdelapena** [comment]
Looks like you have tried the cmake method which already supports OS X app bundle generation. Current autotools method lacks this feature yet and the generated binary needs to be executed from the terminal.

Maybe Player's CMakeLists.txt (which if I recall correctly builds liblcf and player in the same task) needs some updates to properly build and link liblcf with icu, which replaces iconv for automatic character encoding detection. I don't know why the binary is trying to use a different iconv dylib, probably it is using different installed headers when detected with cmake's find_package(). When icu is used, iconv shouldn't be a dependency.

**Comment by BlisterBoy** [comment]
Hello
Please excuse me I was trying the .app from the website ! I should have say
it !

I didn't used CMake I'm actually trying to build the Player with the wiki
description and having a problem with boost witch seems to not ne found.
I'll create a new ticket if I dont find the solution :).
Le 28 janv. 2015 16:48, "Francisco de la Peña" <notifications@github.com> a
écrit :
>
> Looks like you have tried the cmake method which already supports OS X
app bundle generation. Current autotools method lacks this feature yet and
the generated binary needs to be executed from the terminal.
>
> Maybe Player's CMakeLists.txt (which if I recall correctly builds liblcf
and player in the same task) needs some updates to properly build and link
liblcf with icu, which replaces iconv for automatic character encoding
detection. I don't know why the binary is trying to use a different iconv
dylib, probably it is using different installed headers when detected with
cmake's find_package(). When icu is used, iconv shouldn't be a dependency.

**Comment by fdelapena** [comment]
Hello, now makes sense, that app bundle package in downloads section has a few years old, your OS X version didn't exist then and looks like it is not compatible due to recent operating system library updates. This old app bundle package is not fully static and depends on an older system iconv, now unavailable on OS X 10.10.
