### ISSUE TITLE
[Proposal] Android armeabi, x86 and mips architecture support

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#413]
Though there are lesser devices using these CPU architectures there are some advantages:

- Cover all Android 2.3.3+ devices.
- Have more comprehensive reports on Google Play (prevent comments like 'game crashes on startup' unrelated with engine issues).
- Better ratings from non-`armeabi-v7a` users (more stars).

This feature can use a big APK or separated APKs. Google Play supports multiple APKs for the same app, making app downloading more lightweight.

**Comment by Ghabry** [comment]
X86 is solved. Can also add mips and armeabi easily if you want now. (only need to figure out the correct toolchain name ^^)
