### ISSUE TITLE
[Proposal] android:hardwareAccelerated="true" in AndroidManifest.xml

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#414]
Looks like since recent SDL versions and after adding some patch for the RGB565 bug looks safer to enable this option by default.

This attribute already placed by default into the <application> tag, on the default [SDL2 AndroidManifest.xml](https://hg.libsdl.org/SDL/file/tip/android-project/AndroidManifest.xml).

**Comment by Ghabry** [comment]
Already done here
https://github.com/EasyRPG/Player/blob/master/builds/android/src/org/easyrpg/player/EasyRpgPlayerActivity.java#L64
in a API10 friendly way

**Comment by fdelapena** [comment]
So the API10 won't support hardware accelerated if defined in the XML? Strange, even when SDL adds it to the manifest. And yes, existing hardware driver support is a shame.

**Comment by Ghabry** [comment]
I had it in the XML before. This resulted in a build error.

**Comment by fdelapena** [comment]
I've read building fails when the target is < API 10, but when building targetting 3.x or later it should even with minimun API supported is 10. Earlier builds weren't targetting API 12, maybe now builds.

**Comment by BlisterBoy** [comment]
Is this really supposed to increase performances ? For some tests I've set this option for the application, and the Player's Activity but it didn't increased the FPS in Aëdemphia (which have performance issues).

**Comment by Ghabry** [comment]
No, this flag is only to fix rendering errors on some devices (Hello, Android!).
The Player itself does 100% software rendering.

**Comment by BlisterBoy** [comment]
Okay ! God I love Android !

**Comment by carstene1ns** [comment]
Reading the comments this seems solved (even if API >10 only).
