### ISSUE TITLE
Regression: Warrior Saga game hangs on introduction scenes

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#422]
Test case: [Warrior Saga](http://rmaker.ru/games/Warrior_Saga.rar) introduction itself.

Walk until the end of the map on the right side, step across the world map then the cutscene will return to the previous map, where it will hang.

**Comment by Zegeri** [comment]
Run easyrpg player with `--start-map-id 5 --start-party 1 --start-position 72 169` and walk right to get to the game-breaking cutscene.
