### ISSUE TITLE
Android : Touch Control to reconsider ?

### ISSUE THREAD

**Issue by BlisterBoy** [EasyRPG/Player#438]
Hi everyone,
On my way to work on fix #437 and #288 I found that button management on the android port need to be totally reconsider.

For example, The EasyRPGPlayer Activity only draw the cross and the button, but the touch control is controller by an extern libraby.. But I didn't found anywhere where the code consider that the (x,y) position correspond to A, B or whatever button, this is just not handled by the android code, which is problematic.
This programming pattern create many problems, such as no possibility to modify a button location on another place, or add new buttons. And this makes the code hardly comprehensible (I took many days to understand the way this thing work).

My proposition (and I'm working on it) is to have a Button extending the View class : 
- :+1: The code would be clearer
- :+1: The button takes care of his own drawing (which is the way component should work on Android)
- :+1: The button takes care of touch event on its own bound
- :+1: The model will facilitate a Button Mapping System (which is part of my final plan mwahaha)
- :+1: It would be easier to debug the program, including this issue of course

**Comment by Ghabry** [comment]
It actually makes more sense to handle the touching in the c++ code (we do it in SdlUi::ProcessFingerEvent) because this code can be shared with other touch devices. E.g. Windows tablets, yes we don't do this yet but think about the feature.
Imo the problem is that the button rendering is not in the C++ code ;)

**Comment by BlisterBoy** [comment]
I understand your point. C++ dev is more portable and directly modify the core engine will have many advantages.

But for now the android port has some problems, the code is not clear and hardly understandable (please don't consider that as blame, the whole program is just amazing). As I'm an Android dev and there is no Window's Tablet port for now, I'm able to fix this issue, clear the code and provide a button mapping system (which is the most popular demand on the port).

If we adopt an OOP approach of the control button on the android port : 
:+1: The code will be **more modular**, more easily modifiable (compare to now)
:+1: **The port will quickly have a button mapping system**, which would interest a lot of people and would make the android port more attractive
:+1: The port will be **compatible with way more RPG Maker game** until a C++ developper add a button mapping system in the core engine (**and we don't know when such a developper would do that**)
:+1: If a C++ dev decide to program all of this in the core engine (in C++), it will just need some minutes to restore the way the program handled touch event before (because the code would be more clear and modular)

If I modify the android port in this way, I just see advantages, does it interest you ?

**Comment by Ghabry** [comment]
You make valid points.
If you feel more used to programming with Java implement the touch-code Android specific for now.
That will be the faster short-term solution and will make many users happy.

**Comment by BlisterBoy** [comment]
Thanks Ghabry :).

**Comment by Ghabry** [comment]
Take care that you only use functions that are available in Android API10. We compile against API12 for SDL2 joystick support but this is guarded with a check.
For everything else the code must work with API10.

**Comment by BlisterBoy** [comment]
Okay Ghabry, I've check and everything is alright with this API10 !

**Comment by BlisterBoy** [comment]
Hello guys !
I've almost terminated the button mapping building system ! 

But do you have a list of supported key ? I've search on the wiki but didn't found :/.

**Comment by Zegeri** [comment]
Like this?
https://github.com/EasyRPG/Player/blob/master/src/input_buttons.h#L30-L51

**Comment by BlisterBoy** [comment]
Omg such a dumb I am, thank you Zegeri !

**Comment by Ghabry** [comment]
just got an idea.
Instead of using the constants for the keys you can use the numeric value.

https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_NUMPAD_MULTIPLY

from
```
keyCode = KeyEvent.KEYCODE_NUMPAD_MULTIPLY;
```

to
```
// API 11: KeyEvent.KEYCODE_NUMPAD_MULTIPLY 
keyCode = 155
```
and so on

**Comment by BlisterBoy** [comment]
I also had this idea but I'm not 100% sure that this keycode is the same depending API version. Are you sure of this ?

**Comment by Ghabry** [comment]
Because you are just using this value to pass it to C++ (and don't do anything in Java with it) it should be save. If it doesnt work one of the 5% users will complain ;)

**Comment by BlisterBoy** [comment]
Haha I was thinking exactly the same. I have to finish another project, I'll do that today or tomorrow !

**Comment by BlisterBoy** [comment]
I'll open another issue with a list of improvement for the button mapping system
