### ISSUE TITLE
No support of accents in files names

### ISSUE THREAD

**Issue by BlisterBoy** [EasyRPG/Player#444]
Hi everyone,

I found that the system ignore ressources file including accent in its name.
Exemple : if a charset is named "Héros.png", a message "Image not Found : Charset/Héros" appears and the ressource is not displayed.
This is problem because a lot of French game (and I'm sure other region games) includes accent in file name.

**Comment by Ghabry** [comment]
Try again with Encoding forced to Western Europe

**Comment by BlisterBoy** [comment]
I've tested with the android GUI but the problem remains :/.

**Comment by Ghabry** [comment]
then please upload a test case (the game)

**Comment by fdelapena** [comment]
Is the file from the RTP? Does it exist in the game folder?

**Comment by BlisterBoy** [comment]
They exists in the Game Folder.
I'll do a test game today.

**Comment by BlisterBoy** [comment]
Plot twist : the problem was on the software I used to import my project : it doesn't support accent... Sorry for the time loss !
