### ISSUE TITLE
Hero names containing control commands are not interpreted

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#460]
The following command input selectable is shown under certain circumstances:

![captura de pantalla de 2015-04-25 13 13 59](https://cloud.githubusercontent.com/assets/174885/7381949/7149cd14-edc6-11e4-9843-fa2952a8d546.png)

**Comment by Ghabry** [comment]
Can you tell the map id where this happens?

**Comment by fdelapena** [comment]
[Save05.lsd.zip](https://github.com/EasyRPG/Player/files/61825/Save05.lsd.zip)

How to trigger: just press the decision key, it will open a menu with 4 options. The first two options will show options with control commands.

Another couple of bugs there:

- When pressing cancel key, it will show game menu. If you try the same with RPG_RT (this player savegame works with it), it won't show the custom game menu. It looks like some key status is not clean or whatever.

- In the Game Menu, the "End Game" asks for a confirmation, and the selectable bar has not the proper width (has the size when face is available), compated to RPG_RT, which has the full size.

**Comment by Ghabry** [comment]
This game uses an interesting technique:
It uses Hero names to generate strings. :O

The choice list contains
\N[15]\N[16] and this is substituted to "\C[4] whatever". So is basicly double substitution, wtf. This will need some code rewrite (the replaced hero name must be pushed back into the text-string, so the []-substitution applies again)

**Comment by Zegeri** [comment]
77af9cacdfca should fix this.

**Comment by carstene1ns** [comment]
Great, this also makes the code easier to read! (no more `call_depth`). One potential issue i see is the possibility of endless recursion, but I think we can neglect this possibility.

**Comment by Ghabry** [comment]
Yeah the endless recursion is a thing I wanted to test in RPG_RT to see what happens :D

**Comment by Zegeri** [comment]
Endless recursion was impossible in RPG_RT. If an actor's name is "\n[1]" or "\v[1]", the output will always be "[1]". If the name is "\v[\v[1]]" or "\n[\v[1]]", the output is "[[1]]". Separating the commands in two or more names won't change the result (e.g. if \n[1] is "\n[", and \n[2] is "\v[1]]" the output of \n[1]\n[2] is still "[[1]]").

So the patch doesn't replicate perfectly RPG_RT, but it extends the behaviour one would expect from these combined message commands,

**Comment by Ghabry** [comment]
Actually this regressed a bit:
![ribbonerr](https://cloud.githubusercontent.com/assets/1331889/18231606/038cf1f6-72be-11e6-9b7c-39d924cae87c.png)

**Comment by Ghabry** [comment]
The problem here is some oversight: The code doesn't distinguish between empty hero name and parse error.

Another problem is the handling of \\, this actually doesn't(!) escape the next command character m(
