### ISSUE TITLE
Savegames corrupted when using a custom encoding

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#465]
[Don's Adventures](https://github.com/EasyRPG/Player/pull/434#issuecomment-81306057) game saves corrupted savegame files when Encoding is set in RPG_RT.ini. Here is a [game download mirror](https://fran.cr/owncloud/index.php/s/BRFZiFA0DGzws7M/download) for testing the issue.

**Comment by Zegeri** [comment]
I'm getting the correct graphic. What RTP are you using? Is the incorrect graphic from the same charset or a different one?

**Comment by Ghabry** [comment]
There are some really bad z-layering issues (my fault) and the camera is wrong during the initial jump (whose fault?). But the boat is correct here.

**Comment by Zegeri** [comment]
The jump thing is my fault. It's been fixed in a25c9f252e.

**Comment by Ghabry** [comment]
And here is z 5d181f1c5eba8f72956c3a7d0a9be8bd62fb844d

**Comment by fdelapena** [comment]
Found the vehicle reason, the boat used in Don's Adventures is not the vehicle chipset, it uses a non-standard "crown5.png" file, added by Don Miguel. Because this file does not exist in the original RTP, there is a charset fallback. This is by design:

https://easy-rpg.org/wiki/development/rtp-database/2000-rtp#added-files

Edited the issue to mention only the savegame issue. Bumped the milestone.
