### ISSUE TITLE
KeyInputProc without wait should check whether the key is pressed

### ISSUE THREAD

**Issue by Zegeri** [EasyRPG/Player#467]
Make two parallel events with the following commands:
Event 1
```
KeyInputProc [0001:Input] with wait
ConditionalBranch: Variable [0001:Input] != 0
  Variable [0002:KeyInputWithWait] Add 1
Variable [0001:Input] Put 0
```
Event 2
```
KeyInputProc [0001:Input] without wait
ConditionalBranch: Variable [0001:Input] != 0
  Variable [0003:KeyInputDontWait] Add 1
Variable [0001:Input] Put 0
```

Start the game with RPG_RT.exe on TestPlay mode and hold the key for a second. This is what you should get:
![keyinput](https://cloud.githubusercontent.com/assets/4390703/7540146/8de92d82-f5ac-11e4-9360-120340cd3e77.png)
When the KeyInputProc doesn't wait, it checks whether the key is pressed, while the KeyInputProc with wait checks if the key has been triggered.

This causes the lack of walking animation in Link's Awakening for RPGMaker.

**Comment by fdelapena** [comment]
Maybe is related with this: In Wadanohara, in the first playable map there is a mirror, the Wadanohara face will appear only a few hundred milliseconds.

**Comment by Zegeri** [comment]
The mirror checks the action key button to close the reflection picture, but the event itself is triggered by the action key. The action that starts the event closes the picture.
