### ISSUE TITLE
Missing battle actions

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#480]
Implement missing _enemy_ battle actions:
- [x] Double Attack (2 normal attacks in a row)   **since 0.6**
- [x] Defend (double DEF until next turn)
- [x] SelfDestruct (destroy and deal damage (algorithm???))
- [x] Charge (pause this turn, next turn double damage)
- [x] Escape (leave battle)
- [x] Fix algorithm for Escape
- [x] Fix algorithm for Skill
- [x] SelfDestruct and Escape should not give the item

**Comment by rohkea** [comment]
Some time ago I've tried to understand the self-destruct algorithm (by setting different values, adding 10 slimes and performing many battles), here's what I've got: https://www.ethercalc.org/qpffnn7zle

ATK (values in the left column) are monster's attack, DEF (values in the top row) are hero's defense; the cell at the intersection of these is n-k, where n is min damage and k is max damage. The table was made usin RM2k version 1.05b.

I haven't figured out the algorithm yet, unfortunately. I'll can fill the table with mode data if this helps.

**Comment by Ghabry** [comment]
bugmenot was so kind to reverse it.
Is like a normal physical damage attack, but hits all with 100% success. Never crits.

**Comment by Ghabry** [comment]
Algorithm for SelfDestruct:
https://github.com/Ghabry/easyrpg-player/blob/battle/src/game_battlealgorithm.cpp#L844

**Comment by Ghabry** [comment]
bugmenot offered more algorithms :)

```
Flee Chance = 150 - [AGI(Enemies Average) / AGI(Heroes Average) x100]
```
Div and mul is float
+10 for each missed escape this battle

```
Skill Damage(Effect) =
(
BaseEffect
+ STR(user) x Phys.Influence /20
+ INT(user) x MagicInfluence /40
- DEF(target) x Phys.Influence /40
- INT(target) x MagicInfluence /80
)
x Phys.Attribute /100 x Magic.Attribute /100
+|- random[(SkillDamage x Variance/20)]

Note: random[0 .. (SkillDamage x Variance/10)+1] - (SkillDamage x Variance/20)
```

In case of negative attributdamage (only RPG2k3 has this) only the smaller attribute is considered because twice minus = plus.

Whole skill damage is integer calculation

**Comment by Albeleon** [comment]
#1373 Commit 2.24 implements NormalDual, enemies included, correctly at least for 2k. Needs testing in 2k3.

**Comment by fmatthew5876** [comment]
This is fixed in master. Self-Destrust and Escape not only don't give items, but they also don't give EXP or Gold either.

**Comment by Ghabry** [comment]
According to Git blame this was already implemented 3 years ago. wups.

Closing.
