### ISSUE TITLE
Event on "Below Characters" can't move below the Hero (but the hero can move on it)

### ISSUE THREAD

**Issue by BlisterBoy** [EasyRPG/Player#486]
Hello again :) !

Here is a bug a little related to #344 .
When a event is "Below Characters" the move system doesn't interpret it well.

2 cases : 
- If the hero moves on the event, the hero goes ON the event : good !
- But the event can't go below the hero, it's like they were on the same layer if the move comes from an event.

Here is a test game : 
https://drive.google.com/file/d/0BzyFBzg6Eyy5cUJFQ0Y3Zjg0SXM/view?usp=sharing
The blue girl try to go below the hero but can't, but the hero is abble to go on the girl.

This bug produces a lot of "dead lock" on games I've tested and french community also report me this.

**Comment by BlisterBoy** [comment]
Hello everyone !
Is someone working on this issue ? Lot of people report me this one (it causes dead locks on cut scene for example)

**Comment by Ghabry** [comment]
Not aware of any, development is currently a bit slow since 0.3.1

Same as every year. Summer (vacation) hole?
