### ISSUE TITLE
Emscripten: Downloading files with japanese names result in incorrect filenames on the virtual filesystem

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#487]
And this breaks Yume Nikki :(

Not sure if emscripten or our bug

**Comment by fdelapena** [comment]
Fixed by #508.

**Comment by fdelapena** [comment]
Emscripten added new readdir code, however it is not working yet and the monkey patch is not working anymore with current emscripten version.

**Comment by fdelapena** [comment]
Dowgraded Emscripten to work around the regression.
