### ISSUE TITLE
Support more keys for KeyInputProc

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#491]
It was suggested to support more than 0-9, Shift, NumPad.
Because keycodes are higher then the original return value of this event (highest is 29) it will probably not even break games ;).

**Comment by fmatthew5876** [comment]
This would need custom lsd chunks to save which keys events are waiting on.

**Comment by Ghabry** [comment]
With keyboard reading available in Ineluki and in Maniac Patch I consider this resolved when #2797 is merged. Any objections?
