### ISSUE TITLE
Use Open Build Service to provide GNU/Linux binary repositories

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#499]
The [Open Build Service](http://openbuildservice.org/) is a service provided by openSUSE to build automatically packages and repositories. This makes easy to deploy packages for multiple GNU/Linux distributions automatically.

We could use the [existing OBS instance](https://build.opensuse.org/) provided by opensuse.org or host our own. Because there are lots of distributions and architectures, we could consider using the existing at opensuse.org.

This will bring automated apt repositories for Debian, Ubuntu and such; yum repositories for fedora, etc.

- [x] Create `liblcf.spec` and `easyrpg-player.spec` files for RPM based distributions.
- [x] Create `liblcf.dsc` and `easyrpg-player.dsc` and other Debian control files for DEB based distributions.

**Comment by carstene1ns** [comment]
This is W.I.P. in [obs-config](https://github.com/EasyRPG/obs-config/blob/master/easyrpg-player/README.md) repository.

**Comment by Ghabry** [comment]
Is this resolved?

**Comment by fdelapena** [comment]
carstene1ns wanted to fix the debian 7 package yet, check the issue in the obs-config table.

**Comment by carstene1ns** [comment]
Well, i think this issue here can be closed as there are working packages yet
