### ISSUE TITLE
bug in wadanohara

### ISSUE THREAD

**Issue by pink5259** [EasyRPG/Player#501]
I found an error in wadanohara... In rainbow island I can't move at specific point T^T I hope you to fix it as fast as possible...

**Comment by fdelapena** [comment]
@pink5259 could you try again with a version from the [EasyRPG Player continuous builds](https://easy-rpg.org/player-downloads.html) downloads section?

**Comment by therusted** [comment]
it happens when jumping on a rock in rainbow isle,on that rock memoca says something if you are playing without easyrpg but with easyrpg you just cant move and memoca wont say anything
i hope that helps

**Comment by Zegeri** [comment]
6e51472 should fix this.

**Comment by Zegeri** [comment]
Run easyrpg-player with --start-map-id 279 --start-party 1 --start-position 6 13 and jump right to get to the problematic rock.

**Comment by fdelapena** [comment]
Verified and fixed remaining conversation for #331 in #542.
