### ISSUE TITLE
Some messages are not showing faceset

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#510]
Some text messages in Ahriman's Prophecy game with custom backgrounds are not respecting the face margin when displayed for some messages. This is not happening in other ports.

Test case: talk with the old woman in the first playable map at https://easy-rpg.org/play/?game=ahrimans_prophecy

**Comment by carstene1ns** [comment]
It seems Player is not displaying the faces at all now (tested with 0.3.2):
![screenshot](https://picload.org/image/prcpaca/2015-09-15-225413_642x503_scro.png)
