### ISSUE TITLE
Android: multiple users don't know about player configuration features

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#512]
### Missing configuration menu action button
According with Google Play comments feedback, users are not finding the configuration menu.

In this example (Android 4.2 tablet), the action bar is not displaying a burger icon. However, the menu button works (also works with 3.2), but because is not shown on screen it gets harder to get discovered:

![screenshot_2015-07-05-19-54-33](https://cloud.githubusercontent.com/assets/174885/8514644/59ee690c-2351-11e5-9a58-62acdc80331b.png)

### Missing per-game configuration button
Apart of this, the long tap for region (encoding) configuration per-game is clearly hidden and not intuitive. It could be an individual gear wheel or triple dot/burger or whatever (I am not familiar with Android conventions) on the right side for each game title row.

### Confusing storage path
Finally, another complain is the internal path shown as `/storage/emulated/0/...` on some devices. This can confuse the user which could try to generate this path from the operating system exposed storage root. It should simply display something like `/easyrpg/games` with some clarification, e.g.: "No games found in the /easyrpg/games folder in the storage root". Also, maybe having additional search paths for all available and readable/writable storage or convention/standard configuration places might be worth, apart of the storage root.

**Comment by BlisterBoy** [comment]
I used to like Android but this GUI mantra's modification breaks my balls xp.

"Missing configuration menu action button" --> We need to change all the code (GameBrowser extends from ListActivity)... And we don't...
The problem comes from the previous mantra, users used to click to button menu to know if something happen (yep, this is stupid). Old Android roms keep this mantra but newer will show the hamburger button. But everything works.
I can move GameBrowser from ListActivity to ActionBarActivity and adapt the code. It will be cleaner (and it will make me learn some things). But it will concern just 6% of android user, but it will be usefull for the next problem.

"Missing per-game configuration button" --> I agree with the explanation, this was something I was thinking. I'll study that. Btw have a different button mapping system for different game would be nice.

"Confusing storage path" --> This is the number one problem to solve. I'll do that and change all the way the app save information. I have to study how to store a variable different for each user (Android now provide multi user support).

**Comment by BlisterBoy** [comment]
But its weird that user in 4.2 do no see burger button. Unfortunately it seems that the problem comes from their rom. I'm reading the documentation, maybe something's related.

**Comment by fdelapena** [comment]
Yes, it is a custom rom. I will retry this week with emulator for all versions.

About mapping system per-game: maybe global button presets or an alternate shared or copyable between is worth, to

**Comment by BlisterBoy** [comment]
Hey guys, I thought to implement the possibility to change the directory of EasyRPG. This would solve the third problem.

But Android doesn't provide a file chooser, I was wondering if I could use this library :
http://www.codeproject.com/Articles/547636/Android-Ready-to-use-simple-directory-chooser-dial

The licence seems to be compatible with EasyRPG.

**Comment by fdelapena** [comment]
The license is not compatible with GPL:
https://en.wikipedia.org/wiki/Code_Project_Open_License

**Comment by BlisterBoy** [comment]
Ouch my bad that was totally dumb !
Okay so I'll change the empty directory message, and add a dialog box explaining how to use the program (displayed at the first launch and accessible in the menu), many users seems to not understand it.

**Comment by Ghabry** [comment]
I saw that many applications just ask for an file/folder chooser indent. E.g. ES File Explorer provides one and than use this as a picker instead of programming one by it's own.
This is just a gigantic design failure from android, no default chooser, srsly

**Comment by BlisterBoy** [comment]
Yep... I used to like Android but the more I learn about it, the more I want to leave it xpp.

**Comment by BlisterBoy** [comment]
Soooo, after a lot of reading and testing, here are my conclusions.
On standard 2.3 devices (API 10) there is no ActionBar. It's not shown. The user has to guess he has to click on the menu button. The ActionBar appears after API 15 (Android 4.0) and there is no problem with the hamburger icon.

3 possibilities :
- violent way : stop support API 10 (Action Bar is supported after API 11). Maybe too violent just for an icon haha.
- soft way : install the support library and use a defined theme.
- lazy way : don't mess the code for 5% of the users and let it this way. This case is not necessarily the bad way : it let the successive android's mantras as they are, and let the code clear.

Source : 
http://developer.android.com/guide/topics/ui/actionbar.html#Adding

This is your choice guys !
(My opinion : lazy way, but if you want the second way I'll do it !).

In any case :  only API 10 doesn't show an action bar with an hamburger icon. It definitely seems that the problem from the first picture comes from an incomplete rom.

**Comment by fdelapena** [comment]
IMO, if the cheapest yet compatible way is your 3rd way, then let's go. Android 2.3.3-2.3.6 users are very few according with stats and still will be supported.

**Comment by BlisterBoy** [comment]
Ookay :), so if Ghabry also confirm this, my next task will be to customize the way we interact with items in the game browser. I agree with your suggestion in the first post, I'll study if ListActivity permit the customization of item's view (please please please god of Android, make it possible xpppp).


Oh yes I forgot ! Can I rename some files in the android port ? The port start to be a little big and it had no convention at the beginning, this begin to be a bit messy (ex. all the classes not related are in the same package, the layout file of the Player is named "main.xml" etc.).

**Comment by Ghabry** [comment]
Or use a feature reduced game browser (like the current one) for the few API10 users and a nice one for API11.
You can alter the Android port as you want, I don't plan to touch it by myself anytime soon.

**Comment by BlisterBoy** [comment]
Okay thanks !
I didn't understand the "feature reduced game browser" though, I intended to modify the less possible your code and keep the list disposition.

If it's not possible... Well some ideas are passing through my mind :p. I'll make a custom browser, why not displaying games' title screen ^^.

**Comment by Ghabry** [comment]
I mean load an activity based on the API version. API10 gets only a simple file browser like we have currently (for the few users that still have this). And >=API11 gets the new, nice one.

**Comment by BlisterBoy** [comment]
Haa, ok !
I'll study that in the next days.

**Comment by BlisterBoy** [comment]
I solved the 3 problem :).

The code as been remade and it's now possible to pimp the item list :).
