### ISSUE TITLE
Missing U+2212 and U+301C glyphs

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#514]
Seems like SHIFT_JIS uses U+2212 glyph for the minus sign. It is currently missing from Shinonome.
Also, misses U+301C (wave dash) used in the change hero name scene).
Additionally, having a graphical representation of 0xFFFD (replacement character "�") would be nice to have, used to display wrong encoding conversion sometimes.

Seems to fail when rendering some Japanese titles in the game browser, which are already Unicode, at least for minus sign and wave dash.

## 
- [x] U+2212 (minus sign)
- [x] U+301C (wave dash)
- [x] 0xFFFD (replacement character "�")

**Comment by fdelapena** [comment]
It looks like U+2212 is not needed with the encoding change from ibm-943_P130-1999 to ibm-943_P15A-2003 for the minus sign, then only the U+301C is needed.

**Comment by DBLobster** [comment]
U_2212 in WenQuanYi

```
STARTCHAR U_2212
ENCODING 8722
SWIDTH 1000 0
DWIDTH 12 0
BBX 11 11 0 -1
BITMAP
0000
0000
0000
0000
0000
FE00
0000
0000
0000
0000
0000
ENDCHAR
```

May Like this:

```
BITMAP
............
............
............
............
............
....@@@@@@@.
............
............
............
............
............
ENDCHAR
```

**Comment by carstene1ns** [comment]
This one should be fixed since the wenquanyi addition. Or do we need to copy that minus sign over to shinonome?

**Comment by fdelapena** [comment]
This was reproduceable in the hero name input scene because this scene used Unicode directly without Shift JIS conversion as in the game browser scene test.

Thank you for the fix!
