### ISSUE TITLE
Message command \! displays the next glyph

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#515]
Test case: 
https://easy-rpg.org/play/?game=heros_realm
First playable conversation, after skipping credits.

**Comment by Ghabry** [comment]
Hero's Realm is not really suitable for emscripten because the startup takes ages ;)

**Comment by fdelapena** [comment]
This one seems to happen again :\

**Comment by Ghabry** [comment]
:(

**Comment by fdelapena** [comment]
Correction, it does not display the next glyph, it just skips the message (even worse).

**Comment by Ghabry** [comment]
This is unrelated to the bug. Opening a new one to make this more clear :)
