### ISSUE TITLE
Text in Battle

### ISSUE THREAD

**Issue by ravotd** [EasyRPG/Player#520]
In battle animations, the texts are truncated if they are too long

Low prio issue, will add examples when I next notice it

Player version 0.3, android

**Comment by Ghabry** [comment]
Is this still an issue?

**Comment by fdelapena** [comment]
If I recall correctly, this issue already happens in the original RPG Maker.
There is a feature in RPG Maker 2003 1.61 to wrap long lines, see #588.

**Comment by Ghabry** [comment]
@ravotd 
Ping?

**Comment by fdelapena** [comment]
Forgot to mention this: some texts in descriptions (used in the top one line) use a half-space (by the way, there is already an implemented "\" command to render this half space, if useful for reference), we are using normal text space (6px), which might bring this issue. This also affects some item descriptions in other window blocks, not only in battles.

**Comment by Ghabry** [comment]
Closing as invalid because we never got feedback...
