### ISSUE TITLE
events in battle not working

### ISSUE THREAD

**Issue by ravotd** [EasyRPG/Player#523]
Events in battle not working correctly

I don't know if it's all events or just some. Trigger on 'Tunr no. 0 X ? + 0 Turn' sometimes works, other times not.

example: unterwegs in Düsterburg, Ostmarken monster group 2Orks works (they are in map Krötenwald), monster group Tiger (in Tigerhöhle) doesn't work. (one can see if it works trough testing the battle and seeing if the monster attacks again right after being killed off)

version 0.3 on android

**Comment by Ghabry** [comment]
@ravotd Does this bug still exist in the latest version?

**Comment by BlisterBoy** [comment]
If Ennemies's test count is set to "0 + 1X", the event is launch at every enemi's turn (it should be launch just the first time)

**Comment by Ghabry** [comment]
No when it's 0 + 1X it must launch every turn because X is the turn.
Note that the RPG Maker 2003 official English translation got this wrong and placed the X at the wrong position.

**Comment by BlisterBoy** [comment]
Okay I was not aware of the translation problem but the problem remains : if Ennemies's test count is set to "0X + 1", the event is launch at every enemy's turn (it should be launch just the first time).
I've tested with EasyRPG and RPG Maker.
Would you like a test game ?

**Comment by Ghabry** [comment]
Really? Then the official version got this right 😂. Yeah a test case would be nice.

**Comment by BlisterBoy** [comment]
Here's the link :
https://drive.google.com/file/d/0BzyFBzg6Eyy5SVZDZC1vWnp5ZlU/view?usp=sharing

**Comment by ravotd** [comment]
Sorry, life is stressfull right now. Seems fixed to me in the newest version on the playstore right now. (Tested with UiD)

**Comment by BlisterBoy** [comment]
Hey you closed this issue but my testcase hasn't been solved :p.

**Comment by Ghabry** [comment]
Because this is used to track ravotds issue :P

**Comment by Ghabry** [comment]
Works for me, assigning to 0.5 milestone, probably resolved by the battle interpreter page fixes
