### ISSUE TITLE
The Gray Garden 1.08 menu call is not working

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#527]
The Gray Garden game added a custom menu when pressing the cancel key.
After the initial cutscene and game keys explanation, it enables this custom menu.

The first option should display the system menu, but it does not work. The second option however (save menu) works properly. I didn't test the third option behavior.

**Comment by ravotd** [comment]
If System Menu is disabled, Call System Menu won't work

**Comment by Ghabry** [comment]
That is trivial to fix, but don't have my Laptop till next week:

Move ```if (Game_System::GetAllowMenu()) {``` from line 232 to line 137.

**Comment by fdelapena** [comment]
As @Zegeri pointed in chat, system menu is still called from ProceedWithMovement.

`<zegeri> I think it should check IsRunning() instead of isWaiting().`

**Comment by fdelapena** [comment]
Fixed in #542.
