### ISSUE TITLE
Bug in Wadanohara: Battle against Sal

### ISSUE THREAD

**Issue by therusted** [EasyRPG/Player#529]
Hello
I found a bug in wadanohara,this time is in the battle against sal
when the battle was supposed to end the game window just closes making it impossible to end the battle
this battle is diferent from other battles,this one ends after a certain number of turns(or after sal said  everything he had to say,not sure)
i hope this bug gets fixed easly
hugs :D

**Comment by Ghabry** [comment]
Test case: https://easy-rpg.org/play/index-pr.html?game=wadanohara&battle-test=25
