### ISSUE TITLE
Android: create .nomedia file when creating /easyrpg folder in storage

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#531]
As commented by user feedback on Google Play, create an empty file called `.nomedia` in the /easyrpg folder to prevent the game asset indexing by Gallery and media players, as they are indexing the whole media storage and not only the standard folders, (Music, Pictures, Movies, etc.).
Yes, yet another shameful Android feature.

**Comment by BlisterBoy** [comment]
:O 
So this is possible ! I'm on it.
Yeah, another annoying features but this one is comprehensible ^^.
(I'll watch the button things)

**Comment by fdelapena** [comment]
Fixed by #532

**Comment by Ghabry** [comment]
That you cant select which folder should be indexed instead of opt-out really sucks.
E.g. I have cover images in my music folder and its not possible to hide them from the gallery without hidding all my music -.-
