### ISSUE TITLE
Android: back button in button mapping activity not working in some devices

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#536]
There is a comprehensive report by Inkuna in a [forum post](https://easy-rpg.org/forums/viewtopic.php?f=4&t=600) with Samsung :trollface: Galaxy Tab 4 and Android 5.0.2.

Seems like there is also a recent [comment](https://play.google.com/store/apps/details?id=org.easyrpg.player&hl=ru) in Google Play reporting the same issue. I could get device details from the Google Play developer console for this one if needed.

**Comment by Ghabry** [comment]
A neverending nightmare

**Comment by BlisterBoy** [comment]
![](http://www.starburstmagazine.com/images/nov2011/starburstkitano.jpg)

**Comment by fdelapena** [comment]
http://stackoverflow.com/questions/25831634/android-openoptionsmenu-does-nothing-in-kitkat
