### ISSUE TITLE
Ignore any existing 2nd half picture chunk in 2k3 1.10 English games

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#539]
Official English RPG Maker 2003 1.10 release removed the second half picture opacity feature. However, this change is backwards incompatible with older RPG Maker 2003 versions. Both in RPG_RT 1.09a and Player will show the 2nd half as opaque when unset when the 1st half is semitransparent.

![RPG Maker 2003 1.09a interpreter with screwed 2nd half opacity](https://cloud.githubusercontent.com/assets/174885/9416151/159d21c4-4801-11e5-94e4-e88670627c7e.png)

The solution for this is just ignore 2nd half opacity for pictures when the detected RPG Maker 2003 is the English 1.10 version. Just as RPG Maker 2000 behaves.

**Comment by CherryDT** [comment]
Starting with v1.12, the RM2k3 editor will save the transparency value in both parameters (top and what-has-been-bottom) to prevent issues like these in case somebody uses the new RM2k3 to edit old games (even though there will be a few other things breaking, starting with the different RTPs)
