### ISSUE TITLE
Some Bugs I've found

### ISSUE THREAD

**Issue by Mr-Karl** [EasyRPG/Player#541]
EasyRPG for android devices (tested on note 3):

- [x] Dark characters sprites at shop window.
- [x] Doesn't showing cursor in battles.
- [x] Wrong position/rendering of characters in battle.
- [x] It doesn't let you exchange/reorder characters at menu windows, when you choose ok it doesn't apply the changes.
- [x] It doesn't show pictures properly, can't show pictures allocated in folders inside "pictures" main folder though. (This problem isn't present at windows EasyRPG version) It's only shows pictures in main folder, had to move pictures to the main folder root to display missing images.
- [ ] Main game windows music is playing too fast.
- [x] It doesn't display the correct battle system selected, instead of that it shows the "Battle System A" as default. (I choose use Battle System C not A)
- [x] Getting random crashes from no where.

That's all for now... for the windows version, I did send a demo to fdelapena showing some bugs, he told he will test it this coming week.

**Comment by Zegeri** [comment]
The third bug is probably #278. About the crashes, could you tell us which games have that issue and approximately when do they crash.

**Comment by Mr-Karl** [comment]
The game is my own project in development (at least I'm trying to make it). I did send a test play showing some bugs fpr windows version to fdelapena, it doesn't have much to see, but you can check all bugs I reported in there, specially the missing pictures bug where the player isn't reading pictures allocated inside a sub folder at pictures main folder. In the windows version it's working but try to run it on Android and you will get missing pictures message with a blank background.

**Comment by fdelapena** [comment]
About battle styles and cursor they are not implemented yet.


> -It doesn't shows pictures properly, can't show pictures allocated in folders inside "pictures" main folder though. (This problem isn't present at windows EasyRPG version) It's only shows pictures in main folder, had to move pictures to the main folder root to display missing images.

This one bug happens because some patched RPG Maker editors allow to refer to asset subfolders using backslash as folder separator, e.g. "somesubfolder\someasset". This works OK on windows but fails at least on Android.


> -Main game windows music is playing too fast.

This one is may be related with #349. It is not implemented yet, as it is a bit tricky to solve and also SDL has some noisy bug in the resampler yet.


> -Getting random crashes from no where.

If crashes have some picture involved, there is a known issue with pictures, see #489 and #485.


> -Dark characters sprites at shop window.

Could you attach some screenshot? Are you using some color tone change / tint screen or similar somewhere?

**Comment by Mr-Karl** [comment]
You can check the dark sprites bug in the demo I did send to you. Same bug is present in bot versions droid/win. And yes.. I'm using permanent screen tints changes, because the day and night engine I made, it constantly change screen tones for every hour of the day. This event is set as parallel common event. "Check the demo"

**Comment by Ghabry** [comment]
All reported bugs except the music and the battle ones are fixed / have fixes pending.

**Comment by Ghabry** [comment]
Closing this generic one and opening a new issue for the remaining one.

**Comment by fdelapena** [comment]
> -Main game windows music is playing too fast.

Fixed since #873.
