### ISSUE TITLE
If an event calls a Common Event, EraseEvent shouldn't do anything

### ISSUE THREAD

**Issue by Zegeri** [EasyRPG/Player#548]
If an event A uses a CallEvent command on another event B with an EraseEvent command, it should remove B. This bug comes up when B is a common event. e990184f94 sets the caller's id as the id to erase. So, A gets deleted. This is not the same behaviour of RPG_RT, which would just ignore the EraseEvent because it's used by a Common Event.

This breaks the intro of Zelda Link's Awakening (Link sleeps forever). An event is destroyed prematurely because it calls a Common Event with an EraseEvent (for some reason).

**Comment by Ghabry** [comment]
Oh really? Can't believe it -.-

This change was to support ThisEvent in CommonEvents. English RPG2003 supports this and I thought this can't break anything because it just crashes in old versions.

But DeleteEvent handles this error silently compared to CallEvent... WTF.

**Comment by fdelapena** [comment]
Zelda Link's Awakening with RPG_RT 1.10 is not hanging in this scene, then an engine check might be unsafe for this.

**Comment by Ghabry** [comment]
Did you check if CallEvent in a CommonEvent with ThisEvent as target crashes?

**Comment by Ghabry** [comment]
No RPG2k engine (not even the english one) fixes ThisEvent.
But in RPG2k3 it should... will test as soon as I'm motivated to start steam ^^

**Comment by Zegeri** [comment]
I have an Event with just Call Event to Common Event 1. Common Event 1 has only EraseEvent.
I get the message error "An invalid event was specified" in both RPG2k3 and RPG2k3 1.10.

**Comment by Ghabry** [comment]
Oh I thought I read somewhere that Cherry added this... Okay, so nobody supports this then...

**Comment by fdelapena** [comment]
I guess that's a separated patch:
http://rpgmaker.net/forums/topics/16234/
