### ISSUE TITLE
Perhaps ShowPics still cause crashes! Tested on version 0.3 "Slime" for Win32

### ISSUE THREAD

**Issue by Mr-Karl** [EasyRPG/Player#549]
I tested this engine demo in EasyRPG Slime.. Its getting crashes at star point. The demo include an RPG_RT.exe modified with DYN just to use more than 50pictures. No others invasive mods are getting involved in this demo. Hellsoft´s RTP is needed to test play it.

Problem isnt present if you run it using RPG_RT.exe able to show at least more than 100 pictures!
RPG_RT.exe 1.08 used 

If your interested, heres the link to download the demo:
http://www.mediafire.com/download/rzo1kux18tqy7hr/FPview_MR_KARL_2015.rar

Ask to fdelapena about the specific RTP needed, he knows about it.

**Comment by Ghabry** [comment]
Dont use Slime release, use the continious builds from the bottom of the download page. These contain the latest changes until we release 0.3.1 (soon)

**Comment by fdelapena** [comment]
@Mr-Karl could you confirm if still crashes with the nightly build?

**Comment by fdelapena** [comment]
The 3D-like maze engine works for me without crashing with latest master code. Assuming it was tested with a previous build.
