### ISSUE TITLE
Replace deprecated auto pointers.

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#553]
The new GCC version yields the following warning:

```
warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
```

Affected files:
```
src/game_map.cpp
63:	std::auto_ptr<RPG::Map> map;

src/player.cpp
587:	std::auto_ptr<RPG::Save> save = LSD_Reader::Load(save_name, encoding);

src/scene_file.cpp
69:			std::auto_ptr<RPG::Save> savegame =
70-				LSD_Reader::Load(file, Player::encoding);
```

`unique_ptr` to the rescue?

http://stackoverflow.com/questions/2404115/is-auto-ptr-deprecated

**Comment by fdelapena** [comment]
This also affects liblcf, with it is not using C++11 or Boost headers. These warnings are propagated into Player.

**Comment by Zegeri** [comment]
Couldn't liblcf just return a raw pointer and let the applications use boost/std/qt's smart pointers?

**Comment by fdelapena** [comment]
> Couldn't liblcf just return a raw pointer and let the applications use boost/std/qt's smart pointers?

:+1:

**Comment by vinipsmaker** [comment]
> Couldn't liblcf just return a raw pointer and let the applications use boost/std/qt's smart pointers?

:-1:

Ownership should be clear from the beginning. Shouldn't liblcf be upgraded to support C++11?

**Comment by Ghabry** [comment]
this discussion was started before C++11 support was added.

I also vote for raw pointers because it's more flexible for the program using the lib.

**Comment by vinipsmaker** [comment]
> I also vote for raw pointers because it's more flexible for the program using the lib. (the program can use any smartptr it wants, as zegeri said)

Raw pointers are not more flexible, they're just more unclear (user need to read documentation or even source code to understand the ownership model underneath) and more error-prone (not exception-safe, user can forget to free the resource...).

Every use case of raw pointers can be handled with C++11 smart pointers. If you want to drop `unique_ptr` and use your own semantics in the special case, you can just [`release`](http://en.cppreference.com/w/cpp/memory/unique_ptr/release) and you're done. It's way cleaner and safer for the common case.
