### ISSUE TITLE
Battle animations that change the screen tone show black background for transparent pixels

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#554]
~~Not detected in battle scenes so far, only when used in map.~~
This bug affects multiple games. Needs a test case yet.

**Comment by scurest** [comment]
It happens in battle too, but it drove me _crazy_ trying to figure out why only some animations seemed to do it. It only happens if the animation has a tint effect! Using `PIXMAP_OP_OVER` [here](https://github.com/EasyRPG/Player/blob/master/src/bitmap.cpp#L888) will fix it. (Actually, why is that call needed in the first place?)

**Comment by Ghabry** [comment]
Do you get the same result without the call? Same for BlendBlit below.

**Comment by scurest** [comment]
I do. Deleting it from `BlendBlit` doesn't change this issue though. (It definitely goes through `ToneBlit`.)

**Comment by Ghabry** [comment]
well, then I guess it's okay to delete it, can be reintroduced later when it results in graphical issues.

**Comment by Ghabry** [comment]
The fix does not work, breaks the intro of Düsterburg.
Which means this issue must be reponed when my PR gets merged ^^

**Comment by scurest** [comment]
Does using `PIXMAN_OP_OVER` instead of `SRC` still break it?

**Comment by Ghabry** [comment]
Yes, already tried.

**Comment by scurest** [comment]
Oh, well then, oops. Heh :) Where exactly in Düsterburg is it?

**Comment by Ghabry** [comment]
The first screen you see when starting a New Game.
You see the 3 main heros (Dankwart, Grandy and Libra) as the background image.
That image was broken :)

**Comment by scurest** [comment]
You sure? It works with `OP_OVER` here...

(But yeah, that call goes through the `gray==128` case, so I can see why it's needed. In the `gray != 128` case, what I was thinking about was that it seems like either

1. every pixel in the source is either fully transparent or fully opaque; in this case every pixel [L888](https://github.com/EasyRPG/Player/blob/master/src/bitmap.cpp#L888) writes will be overwritten by the same saturation-adjusted pixel at [L930](https://github.com/EasyRPG/Player/blob/master/src/bitmap.cpp#L930), so the previous call is useless
2. some pixels are partially transparent; in this case, the pixels will be drawn both at L888 and L930, so the opacity of the image builds up too high

so I thought maybe the branch at [L887](https://github.com/EasyRPG/Player/blob/master/src/bitmap.cpp#L887) could be moved into an else case for the `gray != 128` branch. But unless somebody can back that up, I'd prefer just switching to `OP_OVER`, as long as that fixes it.)

**Comment by Ghabry** [comment]
You mean OP_OVER at line 888?

**Comment by scurest** [comment]
Yeah.

**Comment by Ghabry** [comment]
You are right, no idea what I did last time but it fixes it. Awesome.
