### ISSUE TITLE
Hide FPS by default

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#558]
FPS are shown by default in full screen and in the window title in window mode. When pressing F2 only alternates title and screen FPS displaying.

New behaviour proposal:

Windowed mode:
- Don't display FPS in title or in screen by default.
- F2 (show FPS): display FPS in title only. When switching to desktop full screen, don't display FPS in screen.

Desktop full screen mode:
- Don't display FPS in screen by default
- F2 (show FPS): display FPS in screen. When switching to windowed mode, display FPS in title only.

**Comment by carstene1ns** [comment]
:+1:
Maybe add some command line option (`--show-fps`) to set it's state (in combination with `--window` or `--fullscreen`).
