### ISSUE TITLE
The Sacred Tears TRUE: Invisible cursor in title scene

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#559]
[The Sacred Tears TRUE game demo](http://sacredtearstrue.com/demo) does not display the cursor part properly and it is completely invisible. This makes hard to select the proper option.

This might be the same problem as shown in the [El Libro](https://fran.cr/owncloud/index.php/s/IknfB7pb3hEm5D8/download) game title scene, where the System graphic window selectable sprite is not rendered properly.

**Comment by carstene1ns** [comment]
![shot](http://picload.org/image/pgpdigp/2015-09-03-210406_640x480_scro.png)

systemparty: ![systemparty](http://picload.org/image/pgpdigo/systemparty.png) systemparty2: ![systemparty2](http://picload.org/image/pgpdigc/systemparty2.png)

Some observations:
It seems to use the wrong system bitmap. If I simply switch the files, the border will be right, however the "coin thingy" blinks.

![switched](http://picload.org/image/pgpdilg/2015-09-03-211247_640x480_scro.png)
