### ISSUE TITLE
Screen shake not implemented

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#565]
That one seems tricky

**Comment by BlisterBoy** [comment]
With RPG_RT.exe, screen shakes is just the translation of the screen. If the screen shake to the left, there is a black rectangle at the right area : the screen is just transfered to the left and the right area of the map is not rendered. I don't like that comportment but it might be easier to implement.

**Comment by Ghabry** [comment]
In RPG_RT the map is rendered, except if the shake overlaps the map boundary

**Comment by scurest** [comment]
For the map screen, just adding `Main_Data::game_data.screen.shake_position` to `Game_Map::GetDisplayX` seems to work (the only problem I noticed was that if the map loops horizontally and has never scrolled horizontally before, there will black border as though it didn't loop. Once moving right or left, it seemed to work correctly.)

**Comment by fdelapena** [comment]
Talk with the slime in this [test case](https://fran.cr/owncloud/index.php/s/VO8eq8NudGsXZnG/download) to reproduce it.

**Comment by Ghabry** [comment]
For a map everything below the messagebox shakes.
For battle everything below the UI shakes.
