### ISSUE TITLE
"The game has no start location" error

### ISSUE THREAD

**Issue by BlisterBoy** [EasyRPG/Player#566]
Here's a weird bug.

- There is a start location
- It works with RPG_RT.exe
- Player says "The game has no start location"

Here is the project folder : 
https://drive.google.com/file/d/0BzyFBzg6Eyy5bFQwSjUxdGszdEU/view?usp=shari

**Comment by BlisterBoy** [comment]
(The .exe comes from Jenkins)

**Comment by Ghabry** [comment]
Doesn't work for me with RPG_RT.exe

**Comment by BlisterBoy** [comment]
Whut ? Does it crash for an non existing ressources ?

**Comment by Ghabry** [comment]
No, fails with "No start location"

**Comment by BlisterBoy** [comment]
Wtf I've tested again and I swear RPG_RT.exe works but EasyRPG Player doesn't.
That's crazy... I'll do some test tomorrow, I'm on Windows 10 and it seems that it's not possible to create a new project in "Program Files", maybe the 2 problems are related.

**Comment by Ghabry** [comment]
That could be a redirection to the VirtualStore.
RPG Maker 2000 is not marked as compatible for Vista, so writes to "Program files" are redirected and reads, too (when a write was redirected before).
But Player is Vista-compatible and sees the file in "Program files" only (no redirect)

**Comment by BlisterBoy** [comment]
You are right ! Damn, all those OS with their weird special features, I never had this one in 15 years o_o".
