### ISSUE TITLE
Battle: Autobattle hangs when fighting with OFF game enemy ID 8

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#572]
It works properly when doing normal fighting. The event interpreter hangs when the enemy should attack in his turn.
This battle with the 2nd boss contains multiple interpreter tabs with repeated messages. Probably 2k3 interpreter misbehaves (maybe related with #488).

**Comment by Ghabry** [comment]
Works for me, maybe same as #608 ?

**Comment by fdelapena** [comment]
I bet it was the same issue, let's close it for now.
