### ISSUE TITLE
Include guards on rtp_table_bom.h are different than what CMake outputs

### ISSUE THREAD

**Issue by scurest** [EasyRPG/Player#576]
Whenever I run CMake, I get this

    Player $ git diff
    Player $ cd ~/player_build/
    player_build $ cmake ~/Player
    === snip ===
    player_build $ cd ~/Player/
    Player $ git diff
    diff --git a/src/rtp_table_bom.h b/src/rtp_table_bom.h
    index 8b52184..b3dc257 100644
    --- a/src/rtp_table_bom.h
    +++ b/src/rtp_table_bom.h
    @@ -15,8 +15,8 @@
      * along with EasyRPG Player. If not, see <http://www.gnu.org/licenses/>.
      */
     
    -#ifndef _RTP_TABLE_BOM_H_
    -#define _RTP_TABLE_BOM_H_
    +#ifndef _RTP_TABLE_H_
    +#define _RTP_TABLE_H_
     
     #include <boost/assign/list_of.hpp>
     #include <map>

and then have to `git checkout src/rtp_table_bom.h` to fix my diff.

The CMakeList.txt looks like it just copies rtp_table.h to rtp_table_bom.h with a BOM, but the file in the repo has a different include guard, so I guess it didn't come from CMake.

**Comment by Ghabry** [comment]
This file was pending for deletion (and use rtp_table.h everywhere). The problem it tries to solve is that Visual Studio does not detect UTF-8 without BOM and inserts a BOM when you force the UTF-8 save.

**Comment by scurest** [comment]
Would it be a problem if I push the CMake-generated version?

**Comment by fdelapena** [comment]
Sure, I screwed the guard name when updating the file. This file is regenerated from the ruby script from the original rtp_table.h. Feel free to push it.

**Comment by scurest** [comment]
Cool.
