### ISSUE TITLE
The Sacred Tears TRUE: Characters move too slow when falling from roof in the intro cutscene

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#578]
This is the first part of the cutscene directly after beginning a new game

Demo: http://nyu-media.com/sacred-tears-true/

The LMT file is "encrypted", decryption code (Python):

```Python
#!/usr/bin/env python
import sys
with open("RPG_RT.lmt", "rb") as f:
    with open("RPG_RT.lmt2", "wb") as g:
        b = f.read(1)
        while b != b"":
            args = [chr(ord(b)-1 if ord(b)>0 else 255)]
            if (sys.version_info > (3, 0)):
                args.append("latin-1")
            _ = g.write(bytes(*args))
            b = f.read(1)
```

**Comment by Ghabry** [comment]
The reason is our well known "main_flag"-check in the Event interpreter. (line 227)

The game basicly does the following in a parallel process:
MoveEvent Frequency 8
MoveAll
Switch 1 On -> This results in Frequency 3 because of new page
MoveEvent Frequency 8
Wait 0.1 -> Here the map is refreshed and the actor gets freq 3 instead of 8 because the page switch happens now

@zegeri Can you remember which game broke when removing that line? I think one was directly at the beginning of Unterwegs in Düsterburg (no hero added) but I can't reproduce this behaviour anymore. Maybe some other change fixed this already and now refreshing from parallel is save?

**Comment by Zegeri** [comment]
Warrior Saga (#422).

**Comment by Ghabry** [comment]
Yeah, can reproduce the hang in Warrior Saga... So removing that check is still not save :/

**Comment by Zegeri** [comment]
Here's something interesting. Let's compare these three events, the pages with commands are run in parallel mode.

### Event A
Page 1 (no conditions) | Page 2 (Switch 1 is True)
 --------- | --------
 | Set Switch 1 to False
 | Set Switch 2 to True
Set manually Switch 1 to True.
Final Switch 2: False

### Event B
Page 1 (Switch 1 is True) |
--------- |
Set Switch 1 to False |
Set Switch 2 to True |
Set manually Switch 1 to True.
Final Switch 2: **True**

### Event C
Page 1 (no conditions) | Page 2 (Switch 1 is True)
--------- | -----
Set Switch 1 to True |
Set Switch 2 to True |
Final Switch 2: False

So it seems that it won't refresh the game map when the event's new page is null.

**Comment by Zegeri** [comment]
7ec8bd3fc0a97 emulates correctly this weird behaviour in this cases and should fix this.

**Comment by Ghabry** [comment]
Broken for me again :(
