### ISSUE TITLE
Mimicry Man: Message Window stays visible after closing

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#589]
![screenshot](https://picload.org/image/prcpacr/2015-09-15-221230_642x503_scro.png)

https://easy-rpg.org/play/?game=mimicry_man
Use the following choices: `Start` → `Start the game` → `No`

You can still play the game, for example navigate the custom menu (`left`, `right`), set a bait and change to item help view (`up`, `down`). The message stays.
It gets cleared when you change to item index (`shift`), it seems another choice window overwrites the old one then.

Another bug: You can not leave the item index. If you press `shift` again to close it, nothing happens only the sound plays.

Game download: http://www.vgperson.com/games/mimicryman.htm

**Comment by fdelapena** [comment]
About the window selectable not working: #538 (my recent comment about a possible regression with 485ee61).

**Comment by Zegeri** [comment]
Damn is this game addicting. These bugs are fixed in my branch *fixes*.
