### ISSUE TITLE
Weather graphic effect not persisting between maps

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#592]
Audio keeps playing but graphic is not working after teleporting.

[Test case](https://fran.cr/owncloud/index.php/s/VO8eq8NudGsXZnG/download) by Mr Karl: Talk with the NPC girl to trigger raining then teleport to the next map on the right.

**Comment by Zegeri** [comment]
551377b caused this regression.
>Stop weather effect on map change.
