### ISSUE TITLE
Windows: Switch to VS2015 compiler

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#595]
Is there any active developer besides me using Windows?

I would like to update the compiler from VS2010 to VS2015. This compiler adds (finally) C++11 support then we can switch away from C++03 and use all the nice features? :)

Any complains against this? VS2015 is freely available from
https://go.microsoft.com/fwlink/?LinkId=532606&clcid=0x407

This will kill the XP support, but I don't really care.

**Comment by Ghabry** [comment]
Support matrix: https://msdn.microsoft.com/en-us/library/hh567368.aspx
(Everything except SFINAE, no idea what that even is :D)

**Comment by Ghabry** [comment]
Actually VS2015 supports XP with target "v140_xp". But I will compile without XP support and wait for somebody to complain :P

**Comment by BlisterBoy** [comment]
I'm using mac os, so no problem for me :p. I doubt that many people uses XP, it's now very simple to get W10 (for DX12) for free, so...

**Comment by Ghabry** [comment]
Yeah, I will upgrade to Win10 in the next weeks. Together with a hardware upgrade, have to reinstall anyway ^^

**Comment by BlisterBoy** [comment]
(If you don't change your hard disc you can use the windows update ways, I've got no problem and it perfectly works with a pir*te version.)

**Comment by Ghabry** [comment]
Nope, I change the HDD to a SSD. ^^ Wanna feel the speed :D

**Comment by carstene1ns** [comment]
It is okay by me, Player does not work on my last XP installation anyways...

Exception C000001D (illegal instruction) on a Pentium III notebook from 2001.

**Comment by Ghabry** [comment]
That's because the release build uses the SSE2 instruction set.
