### ISSUE TITLE
Embric of Wulfhammer's Castle: Battle music does not play

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#600]
Like the title says, battle music does not seem to play at all in this game. Outside combat, the music works perfectly fine.

Steps to reproduce:
* Download game (portable version of the Deluxe edition) from http://aeresland.net/
* Download my savegame from http://www.heavylobster.com/files/Save03.lsd
* Take one step north to enter battle and you'll see that music stops playing.

**Comment by fdelapena** [comment]
Seems like #581 was not enough (or maybe the game is using a different way to play them, or memorized or inherited music maybe?).

**Comment by Ghabry** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/1331889/13556751/ee4e80cc-e3e1-11e5-9b55-ed417b17e1dd.png)
