### ISSUE TITLE
Embric of Wulfhammer's Castle: Savegame compatibility issue between EasyRPG and RPG_RT

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#602]
As far as I can see, in this particular game:

* EasyRPG can load saves from both EasyRPG and RPG_RT
* RPG_RT fails to load saves made with EasyRPG. An error message stating "Event script referenced a common event that does not exist." is given.

Steps to reproduce
* Download game (portable version of the Deluxe edition) from http://aeresland.net/ 
* Save the game using EasyRPG (if you want to skip the long-ish intro, you can download a existing savegame made with RPG_RT from http://www.heavylobster.com/files/Save03.lsd )
* Try to load the savegame using RPG_RT

**Comment by Siltala** [comment]
I re-tested this with the 0.4.1 release, and this seems to be working correctly now. :)

**Comment by carstene1ns** [comment]
Yes, should be fixed by #785.
