### ISSUE TITLE
Input key processing waiting until key pressed is not waiting for it on a parallel common event

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#604]
This is happenning in this game: [Monigote Fantasy](https://goo.gl/0zqBYz).

The trigger should happen with the shift key, but it is called even without pressing that key. The command is on a parallel common event.

The failing condition is met once the magic bag is provided after recruiting 3 heroes in the bar.
First, get the legendary sword, you will be the chosen one. Then talk with to King, then you will need to recruit 3 heroes in the bar, finally, try to leave the bar.

An old guy will give you a bag. When this bag gets possessed by the hero, the common event condition is met for that page, however it is expected to be called only when pressing the shift key, then it becomes into an infinite loop making the game unplayable.

By the way, this issue persists after pressing F12.

**Comment by Zegeri** [comment]
The problem is simple. Game_Interpreter_Map::CommandKeyInputProc() defaults check_down/left/right/up to true in RPG2k3 if they're missing in the parameters. They might have to default to false instead.

**Comment by Ghabry** [comment]
I wonder if this is also related with the random hangs in Sacred Tears True? #579

**Comment by fdelapena** [comment]
Setting else to false for lines 1512-1515 in game_interpreter_map.cpp prevents the automatic bag call, however shift key to call the bag does not seem to work.

**Comment by Zegeri** [comment]
It seems that it's using a RPG2k-Value KeyInputProc. Run with --engine rpg2k and it should work.

**Comment by fdelapena** [comment]
Thanks, confirmed it works properly as rpg2k.

Maybe there are differences in KeyInputProc between 2003 1.00-1.04 and 1.05-1.09a+.
Most RPG Maker 2000 Value 1.50 changes got implemented in 2003 1.05.
