### ISSUE TITLE
Battle: "victory" is always executed when multiple battle conditions are possible

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#606]
Condition branches can be "victory", "defeat" or "escape", however "victory" is always is being executed.

**Comment by Zegeri** [comment]
Could you please provide a test case for this? My tests are working correctly.

**Comment by Ghabry** [comment]
This one needs a test case

**Comment by fdelapena** [comment]
Maybe I was wrong and this happens on defeat instead of victory: #682

**Comment by fdelapena** [comment]
Closing for now, maybe the bug got fixed with #709.
