### ISSUE TITLE
Monigote Fantasy: Battle: Map encounters with an empty monster group

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#608]
Found in Monigote Fantasy, sometimes an empty battle appears and there is nobody to fight with. Escape is disabled, then the game gets into a deadlock. Happened in the first world map playable area. I can't specify where is this happening exactly (because of #607).
2190988 (#604 fix) needs to be merged from to go to the world map.
**Note:** with --engine rpg2k does not seem to happen.

Not tested but I guess the affected encounter area might contain some broken reference to removed battle groups. Or maybe not, the log was showing an encounter vs battler 123 and it works properly with BattleTest 123.

**Comment by Ghabry** [comment]
Hmmm, I'm sure that I tested 0 Actor and Enemy groups.
There must be something special about this one. Or I broke it :D

**Comment by Ghabry** [comment]
Besides that the MP3 music doesn't work because it uses 48kHz

**Comment by Ghabry** [comment]
The battle is not empty, the enemy just looks like a tree :P

**Comment by fdelapena** [comment]
Yeah, there is a battler shown as a tree, maybe the battler was really there but the enemy menu looked empty. The hang was happening anyways, thanks for the fix ^^.
