### ISSUE TITLE
Yume Nikki: Leaving NASU minigame does not work

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#618]
(NASU can be played at the gaming console in the starting room when awake)

Pressing ESC (or any other cancel button) should end NASU, but nothing happens.

**Comment by Zegeri** [comment]
It works well in my branch *fixes*, probably because 0c3fb4cb2cdc08.

**Comment by fdelapena** [comment]
If I recall correctly, to leave the game you needed to _hold_ the back button but not sure if this was the proper behaviour. Or maybe this was for some fangame.

**Comment by Zegeri** [comment]
Yeah, you have to hold the back button one second.

**Comment by Ghabry** [comment]
Okay closing as invalid. Just didn't know that. IN RPG_RT is same behaviour.

**Comment by Ghabry** [comment]
There are really a lot of bug reports that they can't leave NASU because there is no escape key... but B is the same as ESC for RPG_RT -.-
There was now even a guy who complained that ESC doesn't work to leave the chair in Yumes room. But to leave the chair you must face away from the desk and press A. WTF is wrong with the people.

**Comment by fdelapena** [comment]
The most popular Yume Nikki English translation shows "Press Esc", it should display "Hold Esc" instead. Other fangame translations are showing this text properly translated.
