### ISSUE TITLE
Use a better EasyRPG logo at startup

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#624]
The EasyRPG logo at startup is good and should be kept, as it clearly brands the application.

However, there are some minor flaws:
- The colors of the text logo are too dark
- The URL does not contain the `s` for secure access and has an additional, unneeded slash `/` at the end

Here is the current logo (as everybody knows it :grinning:):
![oldlogo](http://picload.org/image/paarolw/logo.png)
_I actually had to write an unxxd tool to extract it from source as-is._

And here is a quick mockup to address both issues:
![mockup](http://picload.org/image/paarocr/new_logo.png)
Do not mind the realignment, it was for testing purposes. Also the font may be a bit too big in comparison.

About the URL: Maybe drop the `http://` or `https://` altogether?
**web: easy-rpg.org**
About the two logos: Maybe drop the text logo and just use a fullscreen logo?

Here is another mockup:
![mockup2](http://picload.org/image/paarcda/new_logo2-fs8.png)

**Comment by BlisterBoy** [comment]
Your first mockup is really nice ;).

**Comment by vinipsmaker** [comment]
> About the URL: Maybe drop the `http://` or `https://` altogether?

If we're going to be pedantic, shouldn't we maintain the `/` at the end? I vote to remote the protocol prefix altogether.

The mockup I like the most is:

[![](https://camo.githubusercontent.com/833e8d13676d24b92b21d6ab92542309a2fb433b/687474703a2f2f7069636c6f61642e6f72672f696d6167652f706161726f63722f6e65775f6c6f676f2e706e67)](https://camo.githubusercontent.com/833e8d13676d24b92b21d6ab92542309a2fb433b/687474703a2f2f7069636c6f61642e6f72672f696d6167652f706161726f63722f6e65775f6c6f676f2e706e67)

**Comment by Ghabry** [comment]
Btw, I'm interested in 640x480 versions of these logos.

**Comment by Ghabry** [comment]
As an alternative: Use the original logo and remove the URL (it is displayed in the about tab of the game browser anyway.
And use the gained space to make the icon better :)

**Comment by fdelapena** [comment]
A text prefix like "Powered by [logo]" might be useful.

**Comment by BlisterBoy** [comment]
I agree with Ghabry : displaying the URL is kind of useless for a lot a reasons

**Comment by fdelapena** [comment]
Remote picture links in OP post are broken now.

Here's a splash logo proposal for 0.6.0:

[powered-by-easyrpg.svg.gz](https://github.com/EasyRPG/Player/files/2440394/powered-by-easyrpg.svg.gz)
[powered-by-easyrpg-fontless.svg.gz](https://github.com/EasyRPG/Player/files/2440396/powered-by-easyrpg-fontless.svg.gz)

![logo](https://user-images.githubusercontent.com/174885/46388036-306af280-c687-11e8-982e-c5fc850ff0b1.png)

[640x480 version](https://user-images.githubusercontent.com/174885/46388037-306af280-c687-11e8-9a4f-f6572854a7fd.png)

[logo.h.gz](https://github.com/EasyRPG/Player/files/2440408/logo.h.gz) (320x240)

**Comment by fdelapena** [comment]
Updated 320x240 variant with brighter colours for the text part:

![logo](https://user-images.githubusercontent.com/174885/52451158-7a675780-2b03-11e9-8740-8dda5bac21ed.png)

header: [logo.h.gz](https://github.com/EasyRPG/Player/files/2843147/logo.h.gz)
