### ISSUE TITLE
Ib: Interpreter hangs in the sketchbook bucket house

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#629]
[Savegame](https://fran.cr/owncloud/index.php/s/DL29cMyQI8ftdFy/download).

Go to the left path, enter to the vertically inverted house, go to the room on the left and take the blue bucket. When crossing back to the right room, Mary will enter, will ask for you, face left, face right an then the interpreter will hang.

**Comment by Zegeri** [comment]
[Here's an equivalent test game](https://dl.dropboxusercontent.com/u/30277047/LateMoveRoute.7z). You have to walk right through the bridge. There's a move route on the hero once he touches the bridge. In RPG_RT it'll start once he's on the bridge, while in EasyRPG it'll start after he has crossed it.

**Comment by fdelapena** [comment]
This might be related: In the game "Desolate City", the first map has a teleport in the stairs tile to go upstairs. In RPG_RT, the teleport starts before the user is able to cover the stairs tile. In Player the user can set over stairs, then teleports.
