### ISSUE TITLE
Grayscale PNGs with lesser than 8 bit depth display garbage with libpng 1.2

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#635]
This old issue is frequently reported by Google Play users issue and only seems to happen with current Android builds. It can be reproduced in emulators fortunately.

![captura de pantalla de 2015-10-17 23-11-29](https://cloud.githubusercontent.com/assets/174885/10562664/23837e5e-7525-11e5-87d9-f3003d464cff.png)
![captura de pantalla de 2015-10-17 23-17-37](https://cloud.githubusercontent.com/assets/174885/10562669/46b06036-7525-11e5-9a59-b8fea278ed8b.png)

**Comment by fdelapena** [comment]
The same issue might happen in desktop under certain circumstances, at least when trying a static build on my linux host (Fedora), but the same binary seems to work properly in other hosts. Removed the Android tag, however it happens mostly always (except in some real Android 3.2 device).

**Comment by carstene1ns** [comment]
This is related to a clash between different libpng versions. i.e. build and link player against 1.2, but freetype picks up 1.6 from system.

This 'Needs feedback' after @Ghabry updates the Android toolchain.

**Comment by carstene1ns** [comment]
Actually, libpng 1.6 seems not used at all, because it should prevent this by renaming all functions.

**Comment by fdelapena** [comment]
The following PNG image is 4-bit grayscale. It fails to render properly in Player with libpng 1.2.x:
![Title.png](https://cloud.githubusercontent.com/assets/174885/11823864/172cba36-a33c-11e5-90ea-53613d9a355c.png)

EXFONT is 1-bit grayscale and all grayscale PNGs lesser than 8 bit depth (1, 2 and 4 bit) are failing to render properly. It works as expected with libpng 1.6.x however.

**Comment by fdelapena** [comment]
![captura de pantalla de 2015-12-15 17-34-04](https://cloud.githubusercontent.com/assets/174885/11827474/10cb0eca-a352-11e5-876d-8becc3899a5f.png)

The APK from the pull request seems to work without needing to update libpng in the toolchain :+1:.
