### ISSUE TITLE
File finder ignores hidden files

### ISSUE THREAD

**Issue by OrdinaryMagician** [EasyRPG/Player#637]
I notice this in one of the endings in .flow, the player fails to find the ".flowbeet" music file. It's there, I can confirm it.

Maybe it just can't because it's a dotfile and as such it's considered hidden.

**Comment by fdelapena** [comment]
Thank you for the report. I guess the problem is filefinder.cpp line 557:
```cpp
if (ent->d_name[0] == '.') { continue; }
```
I'm not sure if dirent detects the current dir as ".", however in case of this, just by adding an additional string length check condition should be enough.

**Comment by Ghabry** [comment]
Only ignoring "." and ".." should be save

**Comment by fdelapena** [comment]
Hopefully fixed and ready to merge.

**Comment by OrdinaryMagician** [comment]
That looked like a pretty terrible catch-all, glad it's fixed now.
