### ISSUE TITLE
Terrain ID is not changing after changing lower layer chip with replace chip event command

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#638]
[Test case (for English RTP)](https://fran.cr/owncloud/index.php/s/0clxjg0POAypxrg/download), [Test case (for Japanese RTP)](https://dl.dropboxusercontent.com/u/99236147/Menantoka/zip/Testproject.zip).

Step over the tile on the left to verify the current terrain ID, then toggle the lever. RPG_RT updates the terrain ID, easyrpg-player does not.

Test case and report by [めふぃすと](https://twitter.com/viprpg_mephisto). Thanks!

**Comment by Ghabry** [comment]
We had such an issue already months ago.
That was I think Tetrix. With moving over/under a bridge. With Change Tile command to switch between Star tiles and below hero tiles.

**Comment by Ghabry** [comment]
foudn it #142
