### ISSUE TITLE
Emscripten: init SDL mixer frequency based on Web Audio API information

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#641]
This should prevent some well known audio playback noise issues because the Web Audio API does not allow to change this setting.

This can be performed by [Calling JavaScript from C/C++](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-call-javascript-from-native) and [related API functions](https://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#calling-javascript-from-c-c).

**Comment by carstene1ns** [comment]
untested patch:

```c++
#ifdef EMSCRIPTEN
int sampleRate = EM_ASM_INT_V({
var context;
try {
  context = new AudioContext();
} catch (e) {
  context = new webkitAudioContext();
}
return context.sampleRate;
});
#endif
```
