### ISSUE TITLE
Gauge hangs at beginning of new battle

### ISSUE THREAD

**Issue by MisterGrand** [EasyRPG/Player#652]
I spotted an issue during a test. Say I,m fighting Nine-Tail-fox. I beat him and it goes 
back to the map and the cutscene that was playing continues. The Event brings
another boss battle. (E.G, Kraken) Everything appears as it should but when the battle actually starts,
The hero's battle window freezes up. All you can do is move the cursor around but nothing happens when you push the select button. What is wrong? Also, Are you going to add weapons anytime soon?

**Comment by Ghabry** [comment]
Oh wow. A Wii user. That's cool.
We need more information:

- Name of the game
- ID of the battle (you can see the ID in easyrpg_log.txt in the game directory)
- Which weapons do you mean?

**Comment by MisterGrand** [comment]
Sorry for taking long. Well, it's not one of those games
from online. I just threw one together with 2003.
And the sort of weapons I mean are like swords and sheilds.
Maybe they do work but I can't see them in battle. They're graphics don't show. (Unless I have forgotten)

**Comment by Ghabry** [comment]
Could you upload the game somewhere?

**Comment by MisterGrand** [comment]
I don't think so..My internet is pretty slow and it might take a while.

**Comment by fdelapena** [comment]
If your connection is really slow, we only need maps (MapXXXX.lmu), database (RPG_RT.ldb) and maptree (RPG_RT.lmt), zip them all and upload it somewhere (sendspace, mega, etc.), no graphics are strictly required, they could be replaced if needed. A savegame in the proper place would be appreciated. We can't analyze the glitch with precision without at least a minimum test case or a detailed way to reproduce the issue.

**Comment by MisterGrand** [comment]
Here's the link. https://www.sendspace.com/filegroup/pmZ7BmkTfHNgwhmbLRmRg%2BFXREVgpIy%2BT5qUWStwgvi1BEprQ%2Bt6XSMCkyi%2BKTDItmVK5zExxVkVdi5WwRF0u2tKEjVKY09d0eHsj%2BVN6sRhyQR22jpCq3H2%2FrVj004E62Xek1T63q3GAeNnETZi3w

**Comment by carstene1ns** [comment]
Please use some tool to create an archive out of the files next time, so the folder structure is preserved.
http://s000.tinyupload.com/index.php?file_id=98874815345845897891

For the devs: The battles are `89` and `90`. The game uses the unofficial english 2k3 RTP.

**Comment by Ghabry** [comment]
Thanks, that's all we need.
We will investigate the issue and report back when we need more information (or have a fix)

**Comment by MisterGrand** [comment]
Did you ever test it? Did you see the glitch, too?

**Comment by Ghabry** [comment]
@MisterGrand the gauge hang in battles will be fixed and close this issue.

Please open another one for the "swords and sheilds." with a simple testcase.
