### ISSUE TITLE
のび太戦記ACE should wait until the music ends in the "EPISODE 1" cutscene title

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#655]
The hang appears after around a minute from the first cutscene (map ID 3), it will teleport to the next map (ID 2) which shows "EPISODE 1", plays some audio garbage (probably unrelated) in loop and there is no advance or keypress to skip this scene.

Direct access to the hang: `--start-map-id 2 --new-game`

[Game download](http://ux.getuploader.com/nobisenki/download/2/nobisenACE.zip). Click ini the "ダウンロード" button below the url to agree download terms. Remember to set proper encoding when unpacking the zip.

**Comment by Zegeri** [comment]
The interpreter gets stuck in this loop
```
Loop
  Branch if BGM has Played Once
    Play BGM "(OFF)"
    Break Loop
  EndIf
  Wait 0
EndLoop
```
This conditional state hasn't been implemented yet.

**Comment by fdelapena** [comment]
For a SDL_Mixer music loop check workaround, click the picture to play a video with a code example:

[![Music Loop Points With SDL_Mixer](https://img.youtube.com/vi/ewZFRA6z34Q/0.jpg)](https://www.youtube.com/watch?v=ewZFRA6z34Q)

**Comment by Ghabry** [comment]
zegeri fixed this one
