### ISSUE TITLE
Unterwegs in Düsterburg  - Endless Animation Loop when killing Sylvia

### ISSUE THREAD

**Issue by Soranela** [EasyRPG/Player#656]
When Entering Map-ID:0128  "Leeres Zimmer" while switch "Event:0941 is ON" you have to fight her, dankward needs aprox. 5 rounds to prepare his spell and after the dialogue the animation is loopding endlessly.

clip of said bug:
https://www.youtube.com/watch?v=Jns8ms3h7ns

![problem](https://cloud.githubusercontent.com/assets/15985419/11511563/189bb8f4-986a-11e5-87c8-9d24bea31537.jpg)

**Comment by Soranela** [comment]
![problem 1](https://cloud.githubusercontent.com/assets/15985419/11511855/a3df7d8c-986b-11e5-8a07-3c4dbc036872.jpg)

**Comment by Soranela** [comment]
Since it's an optional quest and you can leave the castle without finishing this task i'm currently at wahnfrieds schloss without encountering any bug that makes it impossbile to finish the game.

**Comment by fdelapena** [comment]
thank you @Soranela for the report. This bug has been fixed and can be verified by using easyrpg player nightly builds from the EasyRPG Player downloads section in the easy-rpg.org website.
