### ISSUE TITLE
Main player character will not move in Standstill/Stagnation Girl

### ISSUE THREAD

**Issue by Reverie920** [EasyRPG/Player#657]
When I was fiddling around with getting Standstill Girl to work with this player, it worked a bit oddly in the fact that every input was read, but the main player character would not move. I input one of the bonus passwords and the bonus character DID move when I input the directions. I exited that bonus and I still couldn't get the main player character to move. Everything else appears to work with the game thus far, it's just the main player character doesn't move with input.

**Comment by Ghabry** [comment]
Thanks for reporting, this bug is already known.

It is tracked under the (not so obvious name)
#626 "Single-frame move routes shouldn't block the playable character"
