### ISSUE TITLE
"Double tap a key" doesn't work

### ISSUE THREAD

**Issue by trotterdotp** [EasyRPG/Player#659]
Hello there,

I made a sample game to showcase one bug:
![Imgur](http://i.imgur.com/XmFYHN7.png)

In RPG_RT.exe:
->Double tap the keyboard should play a sound.

In Player.exe:
->Nothing happens.

[easyRPGdebugsamplegame.zip](https://github.com/EasyRPG/Player/files/52863/easyRPGdebugsamplegame.zip)

Thanks a lot for you work everybody.

**Comment by fdelapena** [comment]
thank you @trotterdotp for the report. This bug has been fixed and can be verified by using easyrpg player nightly builds from the EasyRPG Player downloads section in the easy-rpg.org website.

**Comment by trotterdotp** [comment]
That was so fast. You guys rules.
