### ISSUE TITLE
Freeze when entering a room  - event (mainstory)

### ISSUE THREAD

**Issue by Soranela** [EasyRPG/Player#665]
![screenshot_20151207-120448](https://cloud.githubusercontent.com/assets/15985419/11625373/d737e638-9cda-11e5-92fc-17a6ec95f6d8.png)
![screenshot_20151207-120456](https://cloud.githubusercontent.com/assets/15985419/11625379/deb9ecda-9cda-11e5-99c9-a5fb7ddc0a34.png)

**Comment by Soranela** [comment]
posted the pictures from my tablet, going to look for map>event>issue right now.. gimme a minute.

**Comment by Soranela** [comment]
Game: Unterwegs in Düsterburg > Map: "Grandys Zimmer" - ID:0245 
EV0010 - Remove "Wait for all Players Movement" will fix the bug.
seems like it's the same issues that caused the bug in grandy's home.

**Comment by Soranela** [comment]
Same bug from here.
https://github.com/EasyRPG/Player/issues/650

**Comment by Soranela** [comment]
![screenshot_20151207-125945](https://cloud.githubusercontent.com/assets/15985419/11626393/a2fdf6d4-9ce2-11e5-91bd-062a78048a40.png)

**Comment by Soranela** [comment]
Second Freezing Bug exactly here, it's in the same room, same event, Event ID: 0007 Page 4> Same bug with waiting for players movement "he walks into you, then joins your party" but it'll freeze.

**Comment by Soranela** [comment]
Same for Libra:Event:0008 > Page 3 :)

**Comment by Ghabry** [comment]
lol okay thanks for reporting them. That's a lot.
They will also make excellent test cases for later unit tests.

**Comment by Ghabry** [comment]
Btw you can easier figure out the map id by looking in the easyrpg_log.txt (in the game directory). Same for battler encounter.
