### ISSUE TITLE
Windows: Japanese and Korean locales can't find ./RPG_RT.ldb

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#673]
It seems to be an encoding issue when trying to find files with path separators in the string, crashing Player when Windows is configured with Japanese or Korean locales, which use a different directory separator (Yen an Won).

This happens always, and can't be solved by forcing the `--encoding` parameter.

To test this on Windows, follow this guide to change the locale:
http://windows.microsoft.com/en-us/windows/change-system-locale

You can check the easyrpg_log.txt also to verify the bad encoding output, even when opened as UTF-8.

**Comment by Ghabry** [comment]
This is a regression from my GameBrowser code merge.
