### ISSUE TITLE
Embric of Wulfhammer's Castle: Some items unusable in combat

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#679]
Several items that are usable in combat in RPG_RT are greyed out in EasyRPG for some reason and are thus unusable. As far as I can tell, all of these broken items are considered 'titles' by the game which work as equipment for a character but also can be directly used in combat.

Steps to reproduce:

* Download game ( http://aeresland.net/EmbricDELUXE_2.2.2.7z )
* Download my savegame from http://www.heavylobster.com/files/Save03.lsd 
* Take one step north to enter battle
* Select 'strategize', look at items, and scroll down. Items such as "Duchess Elstwhere" and "Outlaw Queen", among others, are greyed out and unusable, while in RPG_RT the same items are usable.
 
Note that you need latest git to get past bug #601 .

**Comment by Ghabry** [comment]
Yepp, these items are also Equipment. Guess nobody in our team ever noticed that these items are usable as Item skills. Needs some time to get this implemented ^^
