### ISSUE TITLE
Embric of Wulfhammer's Castle: Scripted event when losing a specific fight not working

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#682]
After losing a certain battle you may be familiar with by now, some scripted dialog occurs in the game  followed by the player being taken to another location. This is working fine with RPG_RT.
However, with EasyRPG this does not occur: upon losing the battle, you are taken to the title screen instead, which is definitely incorrect behavior.

Steps to reproduce:
* Download game ( http://aeresland.net/EmbricDELUXE_2.2.2.7z )
* Download my savegame from http://www.heavylobster.com/files/Save03.lsd
* Take one step north to enter combat
* Lose the battle somehow. On RPG_RT this works correctly, on EasyRPG it does not.

**Comment by Ghabry** [comment]
I lost the battle and I'm not taken to the title screen but to the castle

**Comment by Siltala** [comment]
Hmm. As far as I can tell, this seems to be working correctly for me also now. I suppose this was either fixed, or I was doing something else wrong when reporting this bug.

**Comment by fdelapena** [comment]
Thanks @Siltala. Probably was the same issue as #702.
