### ISSUE TITLE
Embric of Wulfhammer's Castle: Horse deattaches itself from carriage during intro scene

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#683]
This game's intro scene involves a carriage driven by a horse. With EasyRPG during said scene the horse suddenly gets deattached from the carriage and keeps moving while the carriage stops (which, by the way, is a rather amusing bug). This does not occur with RPG_RT.

Steps to reproduce the bug:
* Download game ( http://aeresland.net/EmbricDELUXE_2.2.2.7z )
* Download my savegame from http://www.heavylobster.com/files/Save08.lsd
* Keep pressing enter to get through the dialogue. Eventually, you will reach the carriage scene during which the bug will occur.

**Comment by Zegeri** [comment]
Notice that the deattaching of the horse is not actually a bug of easyrpg. If you wait long enough when the duchess says "Oh, the wine and shaking of the cart..." in RPG_RT, the horse will deattach itself from the carriage too. The issue is that the screen doesn't fade out after the duke responds the duchess' comment.

**Comment by Siltala** [comment]
Oh, you are correct, I had missed that somehow. Fixing #684 should probably fix that part as well, then. However, there are still other similar issues with the horse: Even after the screen fading out and back in, the horse remains deattached from the carriage, which is something that does not occur on RPG_RT even if you do wait long enough for the horse to deattach itself in the earlier scene. 
There are also issues with the horse in the first carriage scene during the intro; in this particular scene, the horse seems to be in the same position as the carriage (that is, next to the carriage rather than in front of it)
My savegame is past this particular scene; to see that one, simply begin a new game and go through some dialogue to get to the carriage scene.
