### ISSUE TITLE
Dyhortfight : Problem with "MoveEvent" command

### ISSUE THREAD

**Issue by BlisterBoy** [EasyRPG/Player#687]
Hi guys

There is a problem in the game Dyhortfight :
https://mega.nz/#!8wJWkRBQ!SN9LRNtxIZyHnkEAhx6RchvfNsTSZvy7uaTU-0MnUlU
 
- Start a new game
- Move 2 step up
RPG_RT : It moves the hero few setp upward 
EasyRPG : It moves the hero few step upward, and teleport him backward in a wall :/

**Comment by Zegeri** [comment]
This is another issue with the Touch Hero trigger.
