### ISSUE TITLE
Change Equipment comment doesn't work

### ISSUE THREAD

**Issue by BlisterBoy** [EasyRPG/Player#688]
Hello again :)

The "change equipment" command seems to not be implemented, here is a test case : 
https://drive.google.com/file/d/0BzyFBzg6Eyy5aFR5MlVLTUdUWms/view?usp=sharing

Just talk to the girl and she's supposed to make the hero equip a magic ring. Doesn't work with the Player

**Comment by Zegeri** [comment]
Ouch! 6cbe0fd3114

**Comment by BlisterBoy** [comment]
Hey, push dat fix, I'm stuck with to many powerful monsters in my play through hahaha
