### ISSUE TITLE
Embric of Wulfhammer's Castle: Golden frame at screen's edge missing

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#694]
In this particular game, RPG_RT renders a fancy golden frame around the edges of the game screen. This frame does not seem to be rendered at all by EasyRPG. The following two screenshots demonstrate the problem:

* http://heavylobster.com/pics/rpg_rt_frame.png shows a scene with RPG_RT. The golden frame around the edges is correctly shown.
* http://heavylobster.com/pics/easyrpg_frame.png shows the same scene with EasyRPG. The golden frame is missing.

Steps to reproduce:
* Download game ( http://aeresland.net/EmbricDELUXE_2.2.2.7z 
* Begin a new game. The lack of a frame will immediately be visible.

**Comment by carstene1ns** [comment]
This is simply not implemented yet, however the liblcf part is already done. 

RPG_RT.ldb
```xml
    <battletest_formation>0</battletest_formation>
    <battletest_condition>0</battletest_condition>
    <unknown_61>-1</unknown_61>
<!-- -->
    <show_frame>T</show_frame>
    <frame_name>C+S Frame2</frame_name>
<!-- -->
    <invert_animations>F</invert_animations>
    <show_title>T</show_title>
   </System>
```

RM2k3 `System2` Tab

![RM2k3](http://picload.org/image/wgrwawa/2015-12-25-115155_992x623_escr.png)

**Comment by Ghabry** [comment]
Ahh, that's the purpose of Frame. I always wondered why you would want to render a gigantic image around everything. :D
