### ISSUE TITLE
Embric of Wulfhammer's castle: Tile opacity broken

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#695]
While reporting another bug, I noticed that there seem to be problems with tile opacity in this game. These screenshots demonstrate the problem:

* http://heavylobster.com/pics/rpg_rt_frame.png shows a scene with RPG_RT.
* http://heavylobster.com/pics/easyrpg_frame.png shows the same building with EasyRPG.

Comparing the screenshots, one can see that the fire (top left) is not visible in EasyRPG. The staircase landing (top middle) and the doorway are also incorectly rendered.

Steps to reproduce:

* Download game ( http://aeresland.net/EmbricDELUXE_2.2.2.7z )
* Download my savegame from http://www.heavylobster.com/files/Save08.lsd

Upon loading the savegame, you should be in the scene shown in the screenshots.

**Comment by carstene1ns** [comment]
The events only appear opaque when a save is loaded, when you reach map 57 through the intro, they are transparent as they should.
Maybe `Game_Event::SetupFromSave` should set transparency as well.
