### ISSUE TITLE
Crash/Black screen when a game is launch on android 4.0.3

### ISSUE THREAD

**Issue by Mysterken** [EasyRPG/Player#699]
After the recent update 0.4.0-3 on android when i launch any game, the screen freeze 2 seconds and then turn into a black screen.
Before the update i could play my games normally without any problem.
Is it possible to fix it?

**Comment by carstene1ns** [comment]
We recently changed the toolchain, required libraries and such to support android x86 and arm devices. It might be related.
Can you give us a bit of information about your device? i.e. platform (arm or x86), android version, etc. Thanks!

**Comment by Mysterken** [comment]
Sure, well all i know is that im on a Asus Transformer TF101 and im using the 4.0.3 version of android

**Comment by Ghabry** [comment]
Can we get a stacktrace?
You must install ADB from the Android SDK on your Computer and on your phone enable "USB Debugging" in the developer Tools (to enable the Tools touch 10 times on the build number in the about Android Dialog).
Then connect your phone to the PC and run "adb logcat".

**Comment by Mysterken** [comment]
Ok i don't have a pc.
Guess i'll wait until next update :(
Damnit

**Comment by Ghabry** [comment]
Try a fresh reinstall of the App (Uninstall it and Install it). Sorry no idea what's going on, works on our devices :/
Do you get a "Player stopped working" error? In that case you can submit it to Google and we can take a look at it.

**Comment by Zegeri** [comment]
There must be a file called easyrpg_log.txt inside the folder of the game you were opening. It might have useful information. Could you upload it? Any website is ok (e.g. https://pantsu.cat/ ).

**Comment by Mysterken** [comment]
Ok i'll try both of your method

**Comment by Ghabry** [comment]
I can confirm that it ANRs on 4.0.3
Thx for the report. Will investigate...

**Comment by Mysterken** [comment]
Ok so i've already submitted the error and the file's link is here:

http://www.megafileupload.com/qI8M/easyrpg_log.txt

Hope it can help.

**Comment by Mysterken** [comment]
Btw thanks for the fast response ^^

**Comment by Ghabry** [comment]
Thanks for reporting... But I don't think we can fix this this year. And seems to be 4.0.3 exklusive :(

**Comment by Ghabry** [comment]
You can install an older version:
https://easy-rpg.org/jenkins/job/player-android/307/artifact/builds/android/bin/EasyRpgPlayerActivity.apk

**Comment by Mysterken** [comment]
Ok i'll try it thanks

**Comment by Mysterken** [comment]
Well it seems that i can play again so thanks ^^

**Comment by Ghabry** [comment]
@Mysterken 
The problem was resolved, you can go back to the Play Store version in a few hours.

**Comment by Mysterken** [comment]
I've just download the new version of easy rpg but it doesn't work

**Comment by Ghabry** [comment]
Okay that's hard to debug then, because it works on my device. Can you send another crash report to google play? Maybe I can guess the reason, but is probably impossible to figure out.

**Comment by Mysterken** [comment]
Well easyrpg doesn't really crash, when i launch any game it just send me
back on the main screen (where you choose a game)
So i can't send you a report.
But do you still have the old easyrpg version?
This one didn't crash but i've delete the apk file after download it.

**Comment by Ghabry** [comment]
Sorry we don't have that old APK anymore :(

The EasyRPG logo does not appear?

We need the logcat output to get a hint but you said that you don't have a PC... So we can't really help, sorry
