### ISSUE TITLE
Pom Gets Wi-Fi: Caterpillar system not working properly

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#703]
[Game](http://rpgmaker.net/games/5441/). [Savegame](https://fran.cr/owncloud/index.php/s/RJ3WQ6sD8jz2g2M/download).
This game has a caterpillar system (events following hero steps) not behaving as in RPG_RT. This makes the player movement hard to do because events are blocking the hero when trying to walk in horizontal axis. Also, the hero character is moving some frames faster than events following it.

**Comment by Zegeri** [comment]
This needs 2 things:
* After using Move Towards Player move command, if the event can't do any step, it must try in the same direction in the next frame. In particular, if the event is in the tile below the hero, it'll try to go upwards, but that way is blocked by the hero. No matter what direction the hero goes, the event will try first going upwards. This is not the way it works in RPG Maker XP.
* A repeating move route must not waste a frame resetting the move route.
