### ISSUE TITLE
OS X : Double click on the Player file doesn't find game

### ISSUE THREAD

**Issue by Medhoc** [EasyRPG/Player#705]
When we double click on the easyrpg-player file, it launch the game browser, which doesn't find any game.
We have to execute it with a terminal to launch the game or the game browser (which is abble to find games in this case).

**Comment by Ghabry** [comment]
The game browser finding only works when the browser is one directory above the games currently

**Comment by BlisterBoy** [comment]
There is a misunderstood, if the player is in a game folder, it launches the game browser (not the game) which found no game.
If the player is in a folder containing games, it launch the game browser which found no game.

In all cases, the Player seems to not detect games if we execute it via a double click.
But everything is fine when we execute it with a terminal.

**Comment by Ghabry** [comment]
Could you patch the player to output getcwd() on startup? And then give me the output for both cases (double click and console)

**Comment by carstene1ns** [comment]
The launcher (how is it called again, Finder?) will likely start in the home directory.
I actually had this problem the other way around when packaging mkxp.
It switches to the directory of the executable on startup to read configuration files and assets:
```c++
	/* set working directory */
	char *dataDir = SDL_GetBasePath();
	if (dataDir)
	{
		int result = chdir(dataDir);
		(void)result;
		SDL_free(dataDir);
	}
```
So when installed in `/usr/bin` this makes no sense :grinning:. However, this code might be useful here.

**Comment by BlisterBoy** [comment]
Ho nice ^^.

I've patched the Player as you asked me Ghabry. This is the result.
Execution with terminal :
```/Users/mehdi/Desktop/Dyhortfight2```

Execution by double click : 
```/Users/mehdi```

**Comment by fdelapena** [comment]
An OS X specific patch could compare user homedir with the getcwd, this hack probably will be reliable enough (it will fail to load /home/user/RPG_RT.ldb game directly).
The purpose of this condition is to prevent chdir when launched from command line from a different path.

**Comment by Ghabry** [comment]
Just got reminded of this. I don't like the SDL dependency but is a better short-term solution then trying to get the Objective C compiler working which is required for the MacOS API >.<

**Comment by Medhoc** [comment]
This works like a charm :).
