### ISSUE TITLE
Implement started using key branch condition

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#714]
It looks like this is the only remaining branch condition pending to be implemented.
This one is being used at least in Yume Nikki, according to [this forum post](https://easy-rpg.org/forums/viewtopic.php?f=4&t=615) report by evonture.

![pic_yume](https://cloud.githubusercontent.com/assets/174885/12204606/cb10e5d8-b5fa-11e5-8704-2099debcde6d.jpg)

The verbose warning introduced in 0.4.0 (7d03fe0) made the condition flag more visible when used.

**Comment by Ghabry** [comment]
Is also worth to check a savegame which field changed

**Comment by Ghabry** [comment]
Fixed by #736

**Comment by evonture** [comment]
Is this fix already in the Android continuous build?

**Comment by carstene1ns** [comment]
Yes, it is since build 323: https://easy-rpg.org/jenkins/job/player-android/323/

**Comment by evonture** [comment]
Thank you, I'll go with the #324 ;)
