### ISSUE TITLE
Event sprites are not being rendered on the left when their visibility is below half tile

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#716]
Video to understand the graphical glitch: https://fran.cr/nextcloud/index.php/s/vLt1uCm3H6aAQ6g
The first column shows people and doors disappearing in the left screen edge when the visible part is around lesser than 8 px (half tile). The WebM video could be reproduced at 0.5x speed for better checking. This is also easier to check in the Yume Nikki doors scene.

**Comment by carstene1ns** [comment]
Seems like you moved your owncloud URL ;-)

**Comment by fdelapena** [comment]
Fixed, thanks :)

**Comment by Ghabry** [comment]
Extremely noticable in Standstill Girl, too. Moving to 0.5.1, will try to find the reason ^^

**Comment by Ghabry** [comment]
This only happened on looping maps, see my commit for further explination
