### ISSUE TITLE
Player for the web: lacks timidity data in the distribution tarball

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#734]
This is nice to have to fix the port distribution and will require a small wiki documentation update.
It needs a Jenkins job update for player-js at least.

**Comment by Ghabry** [comment]
Cool would be 2 packages: One with and one without timidity. Saves loading time when someone doesn't need MIDI.

**Comment by carstene1ns** [comment]
This one can be closed for our official builds.
Player for the web uses FMMIDI exclusively now.

**Comment by Ghabry** [comment]
Tagging as "Invalid" because this issue doesn't apply anymore.
