### ISSUE TITLE
Player crashes when referencing a non-existent hero ID in map event command.

### ISSUE THREAD

**Issue by elsemieni** [EasyRPG/Player#735]
Test case avaiable:
http://elsemieni.net/rpgmaker/bug1.zip

Steps to reproduce the bug:

1.  Add a map event command that modify some hero attribute with a certain ID.
2. Lower the hero list size to a number below than ID.
3. The command now will reference a non-existent hero. Test it.

Expected behaivour (RPG_RT):
Shows an "Invalid hero ID error" window and it closes.

Actual behaivour (Tested on Player for Windows 64 bit build 310 ) 
Player crashes

This also can be a potential bug in another listed elements in game database (Animations, Tilesets, common events, etc), but I haven't tested it yet to say it fails with that too or not.

Thanks!

**Comment by Ghabry** [comment]
I bet this crashes basicly everywhere with almost any database item because we don't really do range checks ^^
