### ISSUE TITLE
Make target "test_filefinder" is broken

### ISSUE THREAD

**Issue by scurest** [EasyRPG/Player#738]
Running `make` or `make test_filefinder` with CMake's Makefile results in a broken target.

    $ make test_filefinder
    [ 52%] Built target liblcf
    [100%] Built target EasyRPG_Player_Static
    [100%] Building CXX object CMakeFiles/test_filefinder.dir/tests/filefinder.cpp.o
    /home/scurest/Player/tests/filefinder.cpp:10:34: error: no member named 'ProjectTree' in namespace 'FileFinder'
                    EASYRPG_SHARED_PTR<FileFinder::ProjectTree> const
                                       ~~~~~~~~~~~~^
    /home/scurest/Player/tests/filefinder.cpp:11:4: error: C++ requires a type specifier for all declarations
                            tree = FileFinder::CreateProjectTree(".");
                            ^
    /home/scurest/Player/tests/filefinder.cpp:11:23: error: no member named 'CreateProjectTree' in namespace 'FileFinder'
                            tree = FileFinder::CreateProjectTree(".");
                                   ~~~~~~~~~~~~^
    /home/scurest/Player/tests/filefinder.cpp:30:2: error: no member named 'Init' in namespace 'FileFinder'; did you mean 'Main_Data::Init'?
            FileFinder::Init();
            ^~~~~~~~~~~~~~~~
            Main_Data::Init
    /home/scurest/Player/src/main_data.h:44:7: note: 'Main_Data::Init' declared here
            void Init();
                 ^
    4 errors generated.
    CMakeFiles/test_filefinder.dir/build.make:62: recipe for target 'CMakeFiles/test_filefinder.dir/tests/filefinder.cpp.o' failed
    make[3]: *** [CMakeFiles/test_filefinder.dir/tests/filefinder.cpp.o] Error 1
    CMakeFiles/Makefile2:283: recipe for target 'CMakeFiles/test_filefinder.dir/all' failed
    make[2]: *** [CMakeFiles/test_filefinder.dir/all] Error 2
    CMakeFiles/Makefile2:295: recipe for target 'CMakeFiles/test_filefinder.dir/rule' failed
    make[1]: *** [CMakeFiles/test_filefinder.dir/rule] Error 2
    Makefile:273: recipe for target 'test_filefinder' failed
    make: *** [test_filefinder] Error 2

**Comment by Ghabry** [comment]
I guess this test is not used in Automake? Because this can't compile anymore since the FileFinder changes months ago.

**Comment by carstene1ns** [comment]
Yes, is disabled since nearly a year: https://github.com/EasyRPG/Player/commit/28d86a1f4ab0848a44198bdf632f3946ac3c8640#diff-c949f93d03f44a4217d7a138f9e2e54aR302

**Comment by Ghabry** [comment]
The Problem with this one is that it requires a game to pass.

**Comment by fdelapena** [comment]
> The Problem with this one is that it requires a game to pass.

Related (comments mentioning filefinder test requirements): #646

**Comment by fdelapena** [comment]
@scurest perhaps this particular test could be disabled in cmake at least for default target (just 'make') until the design for proper argument passing to tests is done, or the possibility about moving game-dependent tests to another repository to keep the player tarball cleaner.
I think keeping this issue open is worth also to track the equivalent issue in autotools.
