### ISSUE TITLE
background is not sprite.

### ISSUE THREAD

**Issue by hiro1986** [EasyRPG/Player#740]
Save&exit&save data load
 -> picture or background picture is not sprite.
 I met "Sirufeid kenbunroku".

**Comment by carstene1ns** [comment]
Which game? Please also provide the savegame used, if possible.

**Comment by fdelapena** [comment]
Thank you for the report, @hiro1986.

For developers:

The original game is "シルフェイド見聞録" ("Records of Silfade") by SmokingWOLF (SilverSecond), an award winning game made in RPG Maker 2000, part of [Silfade series](https://en.wikipedia.org/wiki/Silfade_series). There is a zip download in the official [game page](http://www.silversecond.net/contents/game/silfade_kenbun/) (by going to the Vector off-site download or just by clicking on the square link).

The silfade.zip is SHIFT_JIS encoded, it can be unpacked with ease with:

    unar silfade.zip

Run the game select the first option, then advance until a menu appears like this one:
![Capture 1](https://cloud.githubusercontent.com/assets/174885/12552873/d7cc929e-c339-11e5-925e-2c57c897cb13.png)


To save, press the cancel key or the right arrow to display remaining menu options and select the first of three available options, it will open the save menu scene:
![Capture 2](https://cloud.githubusercontent.com/assets/174885/12552889/ec7d481e-c339-11e5-95e9-e3cfa03f65f0.png)

The problem does not seem related with saving, but loading: The same operation with RPG_RT and loaded with Player also misbehaves (even worse, it loads an additional black band covering the menu), might be related with automatic/parallel event execution order processing from game load maybe.

How behaves after loading a savegame from Player:
![captura de pantalla de 2016-01-25 07-58-26](https://cloud.githubusercontent.com/assets/174885/12553117/2f1c5b1e-c33b-11e5-80e9-245f4c95b731.png)


How behaves after loading a savegame from RPG_RT:
![captura de pantalla de 2016-01-25 08-10-55](https://cloud.githubusercontent.com/assets/174885/12553129/3f20e07a-c33b-11e5-9af1-b97bd291d313.png)

**Comment by hiro1986** [comment]
Thx

I once more again tryed. But many time always happen.

I change the way of thinking,each to chapter save.

Complement like "velvet crown", "crimson cross"are  operate normally.

I feel a sense of doubt.

Thank you so much.and for your reply.

And sorry I used crazy English.

**Comment by Ghabry** [comment]
This one should be checked again after merging my PR with the save fixes

**Comment by fdelapena** [comment]
> This one should be checked again after merging my PR with the save fixes

Checked with the PR build, still happens.

**Comment by Ghabry** [comment]
Looks like the bug in ara fell nikki mentioned about the half-picture transparency

**Comment by carstene1ns** [comment]
Currently getting a read error when attempting to load a game save created with 0.5.1:
```easyrpg-player: src/reader_lcf.cpp:59: void LcfReader::Read(void*, size_t, size_t): Assertion `Read0(ptr, size, nmemb) == nmemb' failed.```

**Comment by carstene1ns** [comment]
This works for me by now (not tested with `RPG_RT` savegame, because I cannot create one easily).
Maybe @fdelapena can also test this again. 🥈

**Comment by fdelapena** [comment]
Works for me now, too. 🎉
