### ISSUE TITLE
Embric of Wulfhammer's Castle: Can't use equipped items in battle

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#745]
Bug #679 has now been correctly fixed in git (thanks for that! :) ) but upon trying out the latest git I noticed that there is still a related issue. If you actually have one of the titles equipped in this game, that particular title is still not usable in EasyRPG, which is not the case in RPG_RT. The exact problem is that the equipped title is not visible in the item menu.

Steps to reproduce:
* Download game from http://aeresland.net/EmbricDELUXE_2.2.2.7z
* Download my savegame from http://www.heavylobster.com/files/Save03.lsd
* Take one step north to enter battle
* Go to the items menu. The "Annointed One" item is not visible. If unequipped before emtering battle, it is visible and usable.

**Comment by Ghabry** [comment]
Equipped items appear in the item list in battle if they have skills... That was new to me :O
