### ISSUE TITLE
ICU data file needs Thai (874)

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#746]
windows-874-2000.cnv I guess?

**Comment by pureexe** [comment]
maybe some useful resource for thai language implementation.
[LibThai Project](http://linux.thai.net/projects/libthai) Many useful feature of thai implement with C language such as word breaking/character properties etc.

**Comment by Ghabry** [comment]
Thanks for that lib, though we don't plan to invest too much time in this.
Currently we only plan to update ICU and do #748 . So the rendering works correctly.

Word breaking and other parts of i18n are another can of worms which has no priority yet.

**Comment by pureexe** [comment]
ok, never mind. :D  
Thank you for implement thai font render support.

**Comment by fdelapena** [comment]
Just as a note, the ICU library supports line/word break and other character operations for multiple scripts already, including Thai, so libthai probably won't be needed in the future for these particular needs.

**Comment by pureexe** [comment]
Thank you for let me know.

**Comment by fdelapena** [comment]
@Ghabry the icudata has been updated to include windows-874-2000, it has been added while fixing #649, only needing to refresh the ICU build in toolchains.
