### ISSUE TITLE
Support Freetype+Harfbuzz

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#748]
Will be needed to handle complex scripts that use combining diacritic marks.

**Comment by fdelapena** [comment]
@pureexe do RPG Maker 2000/2003 Thai-scripted games exist? (Apart of your translation).
Because RPG Maker 2000 resolution is small, and Thai script for 6×12px width (half width) looks too small to display all diacritics, maybe is worth to break the half fixed width limitation of RPG_RT and use a variable width (or even 12×12px full width) in EasyRPG Player. However, if there exist games translated already, maybe they won't fit if they use too long lines (RPG Maker allows 50 half-width glyphs per line).

**Comment by pureexe** [comment]
For now, We don't have any Thai scripted game created with RPG Maker 2000/2003 yet.

but 12x12 is enough for display thai character.

this is yanderella with nearly correct thai language display.

![](http://www.mx7.com/i/664/JS8RXC.jpeg)

We use moded RM2000 font you can download it here.

https://www.dropbox.com/s/n6w75c3m0sv5c7n/rm2000.fon?dl=0

and run with this game file (this is test not full game so file just 4MB) http://www.mediafire.com/download/yz4yjzzeiqo9fdz/yanderella-thai-test.rar

**Comment by Ghabry** [comment]
Could you write this text normally here on github?
So we can see how the correct rendering should look like.

**Comment by pureexe** [comment]
กาลครั้งหนึ่งนานมาแล้ว
มีหญิงสาวสวยนามว่า ซินเดอเรลล่า

**Comment by Ghabry** [comment]
Okay by measuring I would say that we need at least 22 pixel of height to fit everything with something above (รั้) and below (ญิ) beautifully. Needs some testing if freetype can somehow squash this in less.

I think the long term solution for this is to modify the whole rendering code of the Player to render with more pixels...

**Comment by fdelapena** [comment]
@pureexe how readable do you consider this?

![test](https://cloud.githubusercontent.com/assets/174885/12767396/88c9943a-c9ce-11e5-9ac1-5c2664eb3f85.jpg)

It is just a font rendering test using a fixed width font (Arundina Sans Mono) using freetype+harfbuzz at 11 px height (with auto width), seems to fit exactly 6 px width as RPG_RT does, which is good.

**Comment by pureexe** [comment]
@fdelapena wow! pretty good.
it's 100% display correctly.

**Comment by whateverzone** [comment]
@fdelapena That's great! It seemed to display perfectly. Only that the fonts looked a bit blurry but that's not a big problem anyways. 

Thank you for showing that to us! 

We will looking forward to see RM2000/2003 to be able to support Thai perfectly.

**Comment by Ghabry** [comment]
@whateverzone 
I'm currently investigating ways to improve the rendering by using higher resolutions. This will result in great font rendering because doubling the resolution already gives 4 times the pixel.
But the blurry font is a good start. When a better rendering is implemented it will "just work" without any ingame changes :)

@fdelapena 
I would be interested in a screenshot without AA :D

**Comment by whateverzone** [comment]
@Ghabry Wow! Thank you for telling me that! 
I hope your investigation goes well. We really want to see RM2000/2003's games with Thai version and also translation works such as Ib, Wadanohara etc.

Thank you very much for helping us ^^.

**Comment by Ghabry** [comment]
Here some real rendering tests in the engine. Without harfbuzz, so the diacritics are wrong:

Normal resolution (1x / 320x240)
![screenshot_6](https://cloud.githubusercontent.com/assets/1331889/12869733/f4c111f2-cd27-11e5-8318-336f8a0338d1.png)

HiRes (2x / 640x480):
![screenshot_7](https://cloud.githubusercontent.com/assets/1331889/12869741/4dcd6ca0-cd28-11e5-9324-3769c89a960a.png)

**Comment by pureexe** [comment]
@Ghabry 
Can you make diacritics display correctly?

**Comment by Ghabry** [comment]
@pureexe
Not with the current codebase. But is of course possible to implement.
Just wanted to show you a real version so you can check how readable 1x and 2x is. Do you consider 1x readable?

**Comment by pureexe** [comment]
@Ghabry 
I confirmed 1x and 2x is readable font.

@whateverzone 
Do you think is it readable?

**Comment by whateverzone** [comment]
@pureexe Yes, I do.

**Comment by Ghabry** [comment]
Update for the Thai people. Working again on this, hope I can get some results soon ^^ (around November)

**Comment by pureexe** [comment]
Thank you for working on this again.

**Comment by whateverzone** [comment]
Hello! It's been a while. I just wondered if you are still working on this or not.

**Comment by Ghabry** [comment]
Yes, I finally made some progress :D. Though this is still not complete because I also have to rework the messagebox code which renders char-by-char and this won't work with harfbuzz.

![screenshot_20171029_215343](https://user-images.githubusercontent.com/1331889/32148219-d111ec82-bcf3-11e7-8729-691654ce7c15.png)

**Comment by Ghabry** [comment]
I think the 1bit-rendering looks better on that resolution:

![screenshot_20171029_230731](https://user-images.githubusercontent.com/1331889/32148958-1cb093f0-bcfe-11e7-801d-822c7aa6454c.png)

**Comment by Ghabry** [comment]
Works now in message boxes. Due to tecnical reasons (need to split at most \-command codes) the rendering gets worse as I can't render in one go. To fix this I would need to analyze the right part of the bounding box and crop the empty rows :/

![screenshot_20171030_191550](https://user-images.githubusercontent.com/1331889/32187989-d1d90bb0-bda6-11e7-9df3-4d83b2259491.png)

**Comment by Ghabry** [comment]
About the configuration. I don't want to support font-config or any font substitution now because have no idea how to use this and not worth the afford by now imo.

I would propose a configuration in the RPG_RT.ini:
```
[EasyRPG]
Font=Arial;12;Mincho;11
Font2=Verdana;11
```
The font depends on which Font is selected for the system graphic. When one font is not defined it uses the normal built-in one.

Assuming the System graphic Font is the 1st this will look in the "Font" folder of the game for Arial.ttf and Mincho.ttf and render Arial glyphs with size 12 and when a glyph is missing in the font it renders a Mincho glyph with size 11.

As a "flow chart":
```
           Missing              Missing           Missing
Arial 12pt -------> Mincho 11pt -------> built-in -------> <?>
```

**Comment by Ghabry** [comment]
WIP Harfbuzz branch: https://github.com/Ghabry/easyrpg-player/commits/harfbuzz

Wasn't that hard. Only lost two hours because I forgot to divide ``advance`` with ``64`` :facepalm:  . Not very intuitive because normal Freetype doesn't need this divide for ``advance`` :roll_eyes: 

Size calculation has some bugs and it doesn't work for the message box yet. The message box is hard to do because the text appears glyph by glyph and it has all this command processing etc.

Comparison (click to enlarge):

Left is w/o HB, Right is w/ HB

The Thai rendering of the stacked glyphs is correct now (trust me, I compared this with SDL_TTF and in Chrome ;))

![out](https://user-images.githubusercontent.com/1331889/200150627-4dda5d0c-3360-4e5d-a1b0-071873b019ff.png)

Spot the difference ;)  (look for ligatures and letters that are "moved under" other letters like e.g. in case of 'To')

![out2](https://user-images.githubusercontent.com/1331889/200150628-faa988f1-9efe-418a-af10-b0602fd103fa.png)

**Comment by Ghabry** [comment]
Added (Experimental) shaping support for Window Message. Even works properly for color codes etc. :)

![screenshot_12](https://user-images.githubusercontent.com/1331889/200167783-8dba255b-61e8-41a4-9eb4-e1a12d68535c.png)

**Comment by pureexe** [comment]
Looking good! 
Better late than never 😊
