### ISSUE TITLE
Android : migrate to Android Studio

### ISSUE THREAD

**Issue by BlisterB** [EasyRPG/Player#754]
Eclipse ADT is no longer supported by Google and it's becoming more and more problematic. 

Migrating to Android Studio will make the development easier (it provides a lot of official tools) and it will also bring the support of Gradle :) :
+ Developpement easier
+ We will be able to use libraries such as Android Support Libraries
+ It will be possible to make a better UI and use some cool features from API12+
+ Android Support library will be usefull to simplify the code (example: merging the 2 GameBrowsers)
+ Android Studio is the official IDE, we won't have to adapt the project anymore

For the moment, opening the projet with Android Studio doesn't work, there is some modification to do to the project to make the import possible. There is an online tutorial : 
http://developer.android.com/sdk/installing/migrate.html

I unfortunately encountered some problems following it and I have no time anymore until my futur holidays to work on the subject :[.

**Comment by carstene1ns** [comment]
I guess we can call this one "fixed" too.
