### ISSUE TITLE
F12 / end game should stop music and channels playback

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#756]
This is easy to reproduce when a game does not use music in the title scene, it will keep existing music and channels playing. In RPG_RT it will "play" silence.
This shouldn't be handled from the title scene because 2k3 1.11 can skip it, this should be handled in the end game.
Test with a 2k3 1.11 game skipping title scene and returning to a map without music: https://easy-rpg.org/play/?game=itwr

**Comment by carstene1ns** [comment]
This only applies to games which skip the title scene.
If the title scene is enabled, it will stop the music if it is empty.
