### ISSUE TITLE
CommandChangeClass not unsetting class correctly

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#759]
Basicly Game_Actor::SetClass needs

```
data.changed_class = class_id > 0
```

but I also dislike, that all the other logic is in Game_Interpreter and not in Game_Actor.
Have to check if something can be refactored.

**Comment by Ghabry** [comment]
Skill learning based on class isn't implemented, either.

**Comment by Ghabry** [comment]
"Add additional skills" option results in losing of skills that were added through event commands "Add Skill"

**Comment by carstene1ns** [comment]
proposed patch for "Add additional skills":
```patch
diff --git a/src/game_interpreter.cpp b/src/game_interpreter.cpp
index fae389a9..df578fa9 100644
--- a/src/game_interpreter.cpp
+++ b/src/game_interpreter.cpp
@@ -2497,25 +2497,26 @@ bool Game_Interpreter::CommandChangeClass(RPG::EventCommand const& com) { // cod
 
 	switch (skill_mode) {
 	case 0:
+		// No change
 		break;
 	case 1:
+		// Learn based on level (replace)
 		while (!actor->GetSkills().empty())
 			actor->UnlearnSkill(actor->GetSkills()[0]);
+
+		for (const RPG::Learning& learn : Data::classes[class_id - 1].skills) {
+			if (level >= learn.level)
+				actor->LearnSkill(learn.skill_id);
+		}
 		break;
 	case 2:
-	{
-		const RPG::Class& klass = Data::classes[class_id - 1];
-		while (!actor->GetSkills().empty())
-			actor->UnlearnSkill(actor->GetSkills()[0]);
-		std::vector<RPG::Learning>::const_iterator it;
-		for (it = klass.skills.begin(); it != klass.skills.end(); ++it) {
-			const RPG::Learning& learn = *it;
+		// Learn additionally (add)
+		for (const RPG::Learning& learn : Data::classes[class_id - 1].skills) {
 			if (level >= learn.level)
 				actor->LearnSkill(learn.skill_id);
 		}
 		break;
 	}
-	}
 
 	if (show && level > cur_lvl) {
 		// TODO
```

**Comment by carstene1ns** [comment]
Moving the rest of this issue to 0.5.3 milestone.

**Comment by Ghabry** [comment]
At least the following things are broken/wrong:

- Extra Whitespace between text and skill (only 2k3E?)
- Message shall be only printed when skill != "No change"
- Learn additional still gives skill lose in some cases :/
- Setting Class to (None) results in a warning and fails

**Comment by fmatthew5876** [comment]
Test Cases 1 - Equipment loss
----------------------

Try change class with no level change, no skill change, no parameter change

1. None to None
2. Hero A to None
3. None to Hero A
3. Hero A to Hero B

Result: Equipment always removed

**Comment by fmatthew5876** [comment]
Test Cases 2 - Skills
-------------------------

* Start Actor 1 at level 99 with class None, and Skill Fire I at level 1 and Skill Fire II at level 2.
* Class 1 with Skill Ice 1 at level 1 and Ice II at level 2.
* Class 2 with Skill Thunder 1 at level 1 and Thunder II at level 2.

Change to class None with:

| Level  | Skill | Skills |
| -- | -- | -- |
| NC | NC | Fire I, Fire II |
| NC | Reset | Fire I, Fire II |
| NC | Add | Fire I, Fire II |
| 1 | NC | Fire I, Fire II |
| 1 | Reset | Crash: "An invalid job was specified" :exclamation: | 
| 1 | Add | Crash: "An invalid job was specified" :exclamation: |

Change to class None, Level 1, No Skill change.
Then change to None with:

| Level  | Skill | Skills |
| -- | -- | -- |
| NC | NC | Fire I, Fire II |
| NC | Reset | Fire I, Fire II |
| NC | Add | Fire I, Fire II |
| 1 | NC | Fire I, Fire II |
| 1 | Reset | Fire I, Fire II :exclamation: | 
| 1 | Add | Fire I, Fire II :exclamation: |

1. Change None, No Ch

**Comment by fmatthew5876** [comment]
Test Cases 3 - Skills None to Class
======

* Start Actor 1 at level 99 with class None, and Skill Fire I at level 1 and Skill Fire II at level 2.
* Class 1 with Skill Ice 1 at level 1 and Ice II at level 2.
* Class 2 with Skill Thunder 1 at level 1 and Thunder II at level 2.

1
-----
Change to Class 1 with:

| Level  | Skill | Skills | Message |
| -- | -- | -- | -- |
| NC | NC | Fire I, Fire II | None |
| NC | Reset | Ice I, Ice II | level 99, skill learned |
| NC | Add | Fire I, Fire II, Ice I, Ice 2 | level 99, skill learned |
| 1 | NC | Fire I, Fire II | None |
| 1 | Reset | Ice 1 | skill learned |
| 1 | Add | Fire I, Fire II, Ice I |

2
----
Change to class Class 1, No Level Change, No Skill Change
Then change to Class 1 again with:

| Level  | Skill | Skills | Message |
| -- | -- | -- | -- |
| NC | NC | Fire I, Fire II | None |
| NC | Reset | Fire I, Fire II, Ice II :exclamation: | None |
| NC | Add | Fire I, Fire II, Ice I, Ice 2 | level 99, skill learned |
| 1 | NC | Fire I, Fire II | None |
| 1 | Reset | Fire I, Fire II :exclamation: : | |
| 1 | Add | Fire I, Fire II :exclamation: : I |

3
-----
Learn skill "Heal 1"
Change to Class1 with:

| Level  | Skill | Skills | Message |
| -- | -- | -- | -- |
| NC | NC | Heal I, Fire I, Fire II | None |
| NC | Reset | Ice I, Ice II | level 99, skill learned |
| NC | Add | Heal I, Fire I, Fire II, Ice I, Ice 2 | level 99, skill learned |
| 1 | NC | Heal I, Fire I, Fire II | None |
| 1 | Reset | Ice I | skill learned |
| 1 | Add | Heal I, Fire I, Fire II, Ice I |

Conclusion
========

* RPG_RT has bugs when a class changes to itself :exclamation:  @CherryDT

**Comment by fmatthew5876** [comment]
Test Cases 3 - Skills Class to Class
======

* Start Actor 1 at level 99 with class Class 1
* Class 1 with Skill Ice 1 at level 1 and Ice II at level 2.
* Class 2 with Skill Thunder 1 at level 1 and Thunder II at level 2.

First change actor 1

1
-----
Change to Class 1 with:

| Level  | Skill | Skills | Message |
| -- | -- | -- | -- |
| NC | NC | Fire I, Fire II | None |
| NC | Reset | Ice I, Ice II | level 99, skill |
| NC | Add | Fire I, Fire II, Ice I, Ice 2 | level 99, skill |
| 1 | NC | Fire I, Fire II | None |
| 1 | Reset | Ice 1 | skill learned |
| 1 | Add | Fire I, Fire II, Ice I |

2
----
Change to class Class 1, No Level Change, No Skill Change
Then change to Class 1 again with:

| Level  | Skill | Skills | Message |
| -- | -- | -- | -- |
| NC | NC | Fire I, Fire II | None |
| NC | Reset | Fire I, Fire II, Ice II :exclamation: | None |
| NC | Add | Fire I, Fire II, Ice I, Ice 2 | level 99, skill |
| 1 | NC | Fire I, Fire II | None |
| 1 | Reset | Fire I, Fire II :exclamation: |
| 1 | Add | Fire I, Fire II :exclamation: |

3
-----
Learn skill "Heal 1"
Change to Class1 with:

| Level  | Skill | Skills | Message |
| -- | -- | -- | -- |
| NC | NC | Heal I, Fire I, Fire II | None |
| NC | Reset | Ice I, Ice II | level 99, skill |
| NC | Add | Heal I, Fire I, Fire II, Ice I, Ice 2 | level 99, skill |
| 1 | NC | Heal I, Fire I, Fire II | None |
| 1 | Reset | Ice I | skill |
| 1 | Add | Heal I, Fire I, Fire II, Ice I |

Conclusion
========

* RPG_RT has bugs when a class changes to itself :exclamation:  @CherryDT

**Comment by fmatthew5876** [comment]
Test Cases 4 - EXP
=============


* Start Actor 1 at level 99 with class None and default exp curve

1
--------------

Add EXP to actor
Change class to None with:

| +EXP | Level | EXP |
| -- | -- | -- |
| 0 | NoChange | 382200 |
| 2000 | NoChange | 382200 :question: |
| 0 | 1 | 0 |
| 200 | 1 | 0 |

Conclusion
=========

Class change always resets EXP, even if level unchanged

**Comment by fmatthew5876** [comment]
Test Cases 5 - Params None to None
============================

* Start Actor 1 at level 2 with class None. All stats 50 at level 1, 100 at level 2.

Create an autostart event with 
```
Actor 1: MaxHP + 150
Actor 1: Max SP + 150
EraseEvent
```

1
-----
Change to None with:

| Level  | Param | HP | Max HP | SP | Max SP | Atk |
| -- | -- | -- | -- | -- | -- | -- |
| NC | NC | 100 | 250 | 100 | 250 | 100 |
| NC | Half | 100 | 125 | 100 | 125 | 50 |
| NC | Level | 100 | 100 :question: | 100 | 100 :question: | 100 |
| 1 | NC | 100 | 250 | 100 | 250 | 100 |
| 1 | Half | 100 | 125 | 100 | 125 | 50 |
| 1 | Level | 50 | 50 :question: | 50 | 50 :question: | 50 |


| Level | Param | Result |
| -- | -- | -- |
| NC | Level1 | Crash: "An invalid job was specified" |
| 1 | Level1 | Crash: "An invalid job was specified" |

2
-----
Change to None, no level change, no param change
Change to None again with:

| Level | Param | Result |
| -- | -- | -- |
| NC | Level1 | Crash: "An invalid job was specified" |
| 1 | Level1 | Crash: "An invalid job was specified" |

Conclusions
=========

* :exclamation: RPG_RT always crashes if you change from None to None with params to level 1
* :question: Any extra stat gains from events or items are wiped when you do "Change based on level"

**Comment by fmatthew5876** [comment]
Test Cases 5 - Params None to Class
============================

* Start Actor 1 at level 2 with class None. 

| Level | Hp | Sp | Atk | Def | Spi | Agi |
| -- | -- | -- | -- | -- | -- | -- |
| 1 | 300 | 300 | 150 | 75 | 120 | 40 |
| 2 | 400 | 400 | 225 | 275 | 50 |  1 |

Create an autostart event with 
```
Actor 1: MaxHP + 150
Actor 1: Max SP + 150
EraseEvent
```

1
-----
Change to Class 1 with:

| Level  | Param | HP | Max HP | SP | Max SP | Atk | Def | Spi | Agi |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| NC | NC | 100 | 250 | 100 | 250 | 100 | 100 | 100 | 100 |
| NC | Half | 100 | 125 | 100 | 125 | 50 | 50 | 50 | 50 |
| NC | Level1 | 100 | 300 | 100 | 300 | 150 | 75 | 120 | 40 |
| NC | Level | 100 | 400 | 100 | 400 | 225 | 275 | 50 | 1 |
| 1 | NC | 100 | 250 | 100 | 250 | 100 | 100 | 100 | 100 |
| 1 | Half | 100 | 125 | 100 | 125 | 50 | 50 | 50 | 50 |
| 1 | Half | 100 | 125 | 100 | 125 | 50 |
| 1 | Level1 | 100 | 300 | 100 | 300 | 150 | 75 | 120 | 40 |
| 1 | Level | 100 | 300 | 100 | 300 | 150 | 75 | 120 | 40 |

**Comment by fmatthew5876** [comment]
Test Cases 6 - LSD chunks
----------------------------------

| Start | Change | `class_id` |
| -- | -- | -- |
| None | | -1 |
| None | None | 0 |
| None | Hero A | 1 |
| Hero A | | -1 |
| Hero A  | None | 0 |
| Hero A | Hero A | 1 |

**Comment by Ghabry** [comment]
Uhm guess this explains why we haven't proper class change support yet 😅
