### ISSUE TITLE
Automatic scrolling background images sometimes jump

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#761]
Did not test this with RPG_RT, but it seems like a glitch:
![bg_jump](http://picload.org/image/rglwracd/bg_jump.gif)

Related: #314 and #455.

**Comment by Ghabry** [comment]
Yepp they jump at the map boundaries when the map is looping.

**Comment by fdelapena** [comment]
Note: it does not jump in map boundaries if the panorama has automatic scroll, then the jump position will vary.

**Comment by carstene1ns** [comment]
I have a patch for this, however i am not okay with the magic number `32` in there: https://github.com/carstene1ns/easyrpg-player/commit/4b0a8217ca41c921a4ecb51c2301d57720534617
Needs to be investigated, if it needs to be calculated like `distance * 4` or something :no_good:.

**Comment by carstene1ns** [comment]
Wow, I do not know what I am trying to achieve here, but this seems already been fixed by an unrelated commit. At least this does not happen anymore in current master.

**Comment by carstene1ns** [comment]
At least in *.flow* and *Yume Nikki* it can not be observed anymore.
However, in *Standstill Girl* in Shadeling Town (start map, just go to the hospital) it still happens. Reopening.

**Comment by scurest** [comment]
I think this is [this typo](https://github.com/EasyRPG/Player/blob/9ab6ac2a091d7778f57f5a08fa49610800b28a68/src/bitmap.cpp#L677)

    diff --git a/src/bitmap.cpp b/src/bitmap.cpp
    index e54fb610..307f4b35 100644
    --- a/src/bitmap.cpp
    +++ b/src/bitmap.cpp
    @@ -676,3 +676,3 @@ void Bitmap::TiledBlit(int ox, int oy, Rect const& src_rect, Bitmap const& src,
            if (ox >= src_rect.width)       ox %= src_rect.width;
    -       if (oy >= src_rect.height)      ox %= src_rect.height;
    +       if (oy >= src_rect.height)      oy %= src_rect.height;
            if (ox < 0) ox += src_rect.width  * ((-ox + src_rect.width  - 1) / src_rect.width);

**Comment by Ghabry** [comment]
looks like a candidate, obviously wrong 👍

**Comment by carstene1ns** [comment]
Good find, will test later today, if this fixes the issue in `Standstill Girl`. Going by the commit info, this bug has been present since 2012 at least... 😲

**Comment by Ghabry** [comment]
yeah this bug exists since looping maps were implemented because Yume Nikki needed them to be playable. :D

**Comment by carstene1ns** [comment]
confirmed fixed.
