### ISSUE TITLE
7thjojo: black screen after sleeping

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#769]
This issue happens in the first playable map after the long introduction, [this savegame](https://fran.cr/owncloud/index.php/s/4SUrp4FKiJt2OM5/download) is recommended to get into the place properly. It has been tested with the original Japanese version of the game. [Download site (DL white button link)](http://clayman.net/game/).

To trigger the issue, press action key in the bed and confirm (first selectable option).

This issue has been reported via Player for Android email twice by Jiro and by Sato.

**Comment by Ghabry** [comment]
okay just by taking a quick look I have no idea what's wrong
