### ISSUE TITLE
Not working on Samsung S6 Edge with Android 5.1

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#776]
Reported by multiple users. Black screen on startup. Not fixable because everybody of them ignores my offer to contact us :(

SAMSUNG!!!

**Comment by Ghabry** [comment]
Because DOTA is not available for Android we can't expect a patch soon.
Related SDL bug: https://bugzilla.libsdl.org/show_bug.cgi?id=3225

**Comment by BlisterBoy** [comment]
-___-. Something's telling me that it will be the same for their brand new Galaxy S7

**Comment by Ghabry** [comment]
@BlisterBoy . One guy respoded. Guess what: The layout editor does not work!!! m(

**Comment by fdelapena** [comment]
```
─▄▀▀▀▀▄─█──█────▄▀▀█─▄▀▀▀▀▄─█▀▀▄ 
─█────█─█──█────█────█────█─█──█ 
─█────█─█▀▀█────█─▄▄─█────█─█──█ 
─▀▄▄▄▄▀─█──█────▀▄▄█─▀▄▄▄▄▀─█▄▄▀ 

─────────▄██████▀▀▀▀▀▀▄
─────▄█████████▄───────▀▀▄▄
──▄█████████████───────────▀▀▄
▄██████████████─▄▀───▀▄─▀▄▄▄──▀▄
███████████████──▄▀─▀▄▄▄▄▄▄────█
█████████████████▀█──▄█▄▄▄──────█
███████████──█▀█──▀▄─█─█─█───────█
████████████████───▀█─▀██▄▄──────█
█████████████████──▄─▀█▄─────▄───█
█████████████████▀███▀▀─▀▄────█──█
████████████████──────────█──▄▀──█
████████████████▄▀▀▀▀▀▀▄──█──────█
████████████████▀▀▀▀▀▀▀▄──█──────█
▀████████████████▀▀▀▀▀▀──────────█
──███████████████▀▀─────█──────▄▀
──▀█████████████────────█────▄▀
────▀████████████▄───▄▄█▀─▄█▀
──────▀████████████▀▀▀──▄███
──────████████████████████─█
─────████████████████████──█
────████████████████████───█
────██████████████████─────█
────██████████████████─────█
────██████████████████─────█
────██████████████████─────█
────██████████████████▄▄▄▄▄█

─────────────█─────█─█──█─█───█
─────────────█─────█─█──█─▀█─█▀
─────────────█─▄█▄─█─█▀▀█──▀█▀
─────────────██▀─▀██─█──█───█
```

**Comment by BlisterBoy** [comment]
Wow, I'm curious to know what exactly doesn't work. Is it the menu that is absent ? Or the Layout system itself that doesn't work ?

Hmmm...
If it's the first one, maybe the support of API10 without using Android Support Library starts to be an obstacle (or worse : the simple use of API10). To many things changed since de API10 (especially this story of physic menu button paradigm), Samsung seems to force developper to design app for the newer mantra.

**Comment by Ghabry** [comment]
New info: The options menu doesn't open AT ALL. -.-

**Comment by Ghabry** [comment]
Samsung should stop pushing garbage software on premium phones...

**Comment by fdelapena** [comment]
Which API is currently the target when building? Maybe this should be bumped. The minimum API still could be 10.

**Comment by Ghabry** [comment]
12

**Comment by Ghabry** [comment]
Btw, the documentation for eglChooseConfig (the call that fails):

**EGL implementors are strongly discouraged, but not proscribed, from changing the selection algorithm used by eglChooseConfig.** m(

**Comment by Ghabry** [comment]
This looks interesting:

http://developer.samsung.com/remotetestlab/rtlDeviceList.action

I wonder if it costs money :O

**Comment by BlisterBoy** [comment]
Wow, nice!

**Comment by Ghabry** [comment]
Was able to reproduce it via that Samsung Lab. The only device affected is Samsung S6 Edge on 5.1. All other S6 devices work m(

What is not working:
Our shiny pop up menu (layout editor). It insta-closes. And the S6 has such a floating "..." button that you can move around. When you touch it that menu appears for a split second and dissapears.

Video output is black, no warning in logcat. Have to add some output to egl_getconfigs...

![unbenannt](https://cloud.githubusercontent.com/assets/1331889/13681726/efa06498-e6fe-11e5-9d52-3acb265e5245.png)

**Comment by Ghabry** [comment]
A user reported in an updated comment via Google Play that the video output works now on the S6 Edge :+1: . Samsung fixing bugs, I'm impressed. But the menu is still broken

**Comment by Ghabry** [comment]
This user reported again that the menu in the layout editor works now, too. WAT

**Comment by Ghabry** [comment]
Closing as invalid for now because it solved itself... will reopen when we have user reports again ^^'

**Comment by Medhoc** [comment]
Ghabry I think that some people are using not stable custom ROM. It was the
case the first time we heard about this kind of issues and I doubt that
Samsung do a lot of software update to fix those stuff.

Btw I want to do that damn new game browser, but I have like no free time
at all during my professional formation x_X.
