### ISSUE TITLE
Android: Unable to add enter/cancel/shift buttons in the layout editor

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#777]
This is happening at least with the Spanish translation, untested with other locales, verified at least in 4.4.4 and 5.0.1.

When selecting Enter (Z), Cancel (Esc and X) and Shift options, the system shows the toast with "Button not supported on this API" message (btw, this toast message text itself is not in the translation list).

**Comment by BlisterBoy** [comment]
This is weird, I'm sure it used to work. For me this problem happens with the Z/X buttons, but the Shift button works.
If nobody resolve it I'll have more free time in a month (bye bye college) and I'll study that.
Moreover I would like to slightly modify the system, add a transparent "magnet" grid to align buttons, and add the possibility to delete a button.

**Comment by Ghabry** [comment]
I will try to quickly provide a fix for this, the bonus is subject to @BlisterBoy and his french people ;)
