### ISSUE TITLE
Android: "Add a game folder" button is not translatable

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#778]

**Comment by carstene1ns** [comment]
https://github.com/EasyRPG/Player/blob/master/builds/android/res/layout/settings_activity.xml#L36
```patch
--- android:text="Add a game folder"
+++ android:text="@string/add_game_folder"
```

https://github.com/EasyRPG/Player/blob/master/builds/android/res/values/strings.xml#L61
```patch
+++<string name="add_game_folder">Add a game folder</string>
```

Cheers!
