### ISSUE TITLE
Android: Multiple users are unable to find how to add more buttons

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#779]
Despite the first nag documentation message dialog, there are multiple users taking their time to write complaints about this, so this is a UX issue which should be more obvious somehow.

**Comment by BlisterBoy** [comment]
If the french buddies success in migrating to Android Studio, the support of Gradle (and so Android Support Libraries) will provide more possibilities. It will be easier to make a more graphic interface.

A "gamepad" button in the action bar would be more comprehensive for those who doesn't want to check Preferences and like to complain.

**Comment by BlisterBoy** [comment]
I was thinking of something : did the user actually found the button layout system or they're just too lazy to looking for it ? 

Because if it's the first option, this is another problem : the back button doesn't call the menu.

**Comment by fdelapena** [comment]
I guess this issue is mostly fixed with the new layout :+1: 

However, it looks like (at least for me) the sandwich floating button didn't appear for me in existing button layouts, I had in previous versions an existing shift key in the default configuration and I wondered why the sandwich menu button was not appearing in my layout. Then, after doing a reset layout, it appeared. Maybe force adding it when undefined in old, existing layouts would be nice to keep previous Samsung users (even more) happier.

**Comment by fdelapena** [comment]
Ok, didn't see the option to add this button. Because people unable to access it probably didn't customize it they should see it after the update anyways, then covers all user cases, so this is done :tada:.
