### ISSUE TITLE
HOME (OFF fangame): crash while transitioning into boss battle

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#781]
This game crashes when fighting in map with enemy group id 77 (Butcher Burned).

[Game download](http://rpgmaker.net/games/6361/downloads/). [Savegame](https://github.com/EasyRPG/Player/files/149452/Save01.zip).

Reported by MJ via Android bug report email.

**Comment by Ghabry** [comment]
Heap is corrupted by libmad when decoding Home - Killer Instinct.mp3 (11025 hz)

**Comment by fdelapena** [comment]
As commented some days ago, libmad is OK, the problem seems to be in the infamous Mix_PlayMUS or maybe in dynamic_mp3 wrong buffer size when using AudioCVT in SDL_Mixer. When playing with 11025 setting in SDL audio initialization it does not crash.

**Comment by FelixTheJudge** [comment]
Heyo. Felix here, creator of HOME. So, What version of HOME are you playing?

**Comment by Ghabry** [comment]
Hey. We use the version from rpgmaker.net
It's not really an issue with your game but with the MP3 decoder we use. We will propse a solution soon ;)

**Comment by FelixTheJudge** [comment]
Okay, I was making sure. I found this notice through google so I wasn't sure what EasyRPG was until like today. xD

**Comment by Ghabry** [comment]
Haha. You are welcome xD
