### ISSUE TITLE
Battle: Display animation targeting whole group once instead of duplicating for each enemy

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#782]
In Düsterburg:
![Screenshot](http://picload.org/image/wccpopi/screenshot_9.png)
(Note the duplicated Grandy)

**Comment by Ghabry** [comment]
This is done via battle animations. But no idea why it shows the wrong ones...

**Comment by carstene1ns** [comment]
Yeah, also it works when there are actual animations while attacking.

**Comment by carstene1ns** [comment]
This is fixed by #905. However, the animation timings are not correct. In RPG_RT Julie's and Grandy's animation play simultaneously, in Player Grandy's starts first.

**Comment by carstene1ns** [comment]
[Not sure if I should close this, because the original issue is resolved. Letting it open because there is a minor graphical glitch yet]

**Comment by Ghabry** [comment]
you are right, the bug reported here is fixed. closing
