### ISSUE TITLE
Terrain settings for battles not correctly handled

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#789]
TestCase (Ara Fell):
[Save02.zip](https://github.com/EasyRPG/Player/files/153762/Save02.zip)

The battle displays the wrong background (it displays the one specified in "Set"). It should display the background from this screenshot:

![unbenannt](https://cloud.githubusercontent.com/assets/1331889/13444899/54f9d128-e009-11e5-8b04-4a76ae41468d.png)

**Comment by Tondorian** [comment]
mmh strange if i load your save game and startes battle it crashes (out of Bound ex) 
but on cancel and restart it shows the backgrounnd from screen ..
