### ISSUE TITLE
Pictures that "scroll with the map" are influenced by Pan

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#801]
Terminology info because this is still confusing for me: **This is wrong, see scurest comment**
From a Player perspective "Scroll with map" means that they stay at the same position of the viewport because from a code perspective they move with the map when it scrolls... I would have called this "Fixed to screen", whatever...

Anyway when the screen is panned via that evt command by some tiles the picture does not stay at the same position of the viewport but scrolls away.

**Comment by scurest** [comment]
Isn't it the other way? When "Scroll Picture with Map" is checked, the picture is fixed to the map and is supposed to move off the screen when the map scrolls or pans, but when it's unchecked, the picture is fixed to the screen? For me, Player and RPG_RT seem to do the same thing for both options when an event pans.

**Comment by Ghabry** [comment]
As I said, it's confusing to me... And of course I explained it wrong :(
Good find ^^

**Comment by scurest** [comment]
lol :) The function of some of these check boxes is incredibly opaque.

**Comment by Ghabry** [comment]
The Show Picture Dialog has another nice "Feature": When you don't set any effect (e.g. rotating) then RPG 2000 will ignore rotating & co. effects in Move Picture. But RPG 2003 won't :D.

But we couldn't find a game yet that breaks because of this (lucky!)

**Comment by carstene1ns** [comment]
> Player and RPG_RT seem to do the same thing for both options when an event pans in a simple test.

Does this mean it is not an issue anymore? Do we have a game as testcase?

**Comment by Ghabry** [comment]
Probably same problem as Yume Nikki spaceship scrolling... works for me
