### ISSUE TITLE
Emscripten: Update HTML shell file from newer releases

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#804]

**Comment by Ghabry** [comment]
I diffed the latest emscripten shell against ours and there isn't really anything new.

Except for this bugfix here: https://github.com/emscripten-core/emscripten/commit/1fc1c90941936c140827e101dce1576c60811c3d#diff-8fd398136d2435d1c53386be85f6ff73 
Maybe solves the keyboard focus issue we have in some browsers
