### ISSUE TITLE
Android: "horizontal" bug after returning into game from Google Launcher

### ISSUE THREAD

**Issue by Tondorian** [EasyRPG/Player#812]
If you "minimize" easyRPG in horizontal-orientation and go back into application. App shows only 5 pixels of gamescreen on upper part of screen.

I think application calculates displaysettings wrong. Perhabs it trys to render vertical mode.

**Comment by Ghabry** [comment]
This is too generic. Every android device has different bugs (hello, Samsung!)

Name of device and Android version please.

**Comment by BlisterBoy** [comment]
I know this bug, you just have to flip the screen to recalculate the screen displaying.
This should be easy to fix, forcing the app the recalculate the screen displaying when it comes back to "foreground" (onResume callback ?)
Ghabry you can assign me on this task, I finish my exam in 2 weeks and I fix it :).

**Comment by Tondorian** [comment]
Device: Samsung S4 
Android Version: 6.0.1

**Comment by Ghabry** [comment]
Samsung ~.~

@Tondorian 
Do you know someone with a Samsung S6 (Edge)? We need to debug a black screen issue on start up :(

**Comment by Tondorian** [comment]
No but will ask around,
But my parents got some sony devices 
s5 maybe ^^

**Comment by Ghabry** [comment]
Nope, is a S6 exclusive issue :(

**Comment by BlisterBoy** [comment]
@Tondorian : here is a little reminder of our friendly encounters with Samsung, it's actually funny to read:
https://github.com/EasyRPG/Player/issues/776
https://github.com/EasyRPG/Player/pull/567
https://github.com/EasyRPG/Player/issues/536
https://github.com/EasyRPG/Player/pull/533
https://github.com/EasyRPG/Player/pull/530
https://github.com/EasyRPG/Player/pull/392
https://github.com/EasyRPG/Player/issues/386

**Comment by Tondorian** [comment]
Using CyanogenMod... propably my device is not best for testing

**Comment by BlisterBoy** [comment]
Nope don't worry, your ROM is better than a Samsung rom. 
Your issue should be noticeable on every devices, I didn't already fix it because if I start to code for another thing that college stuff, I leave those college stuff xp.

**Comment by Ghabry** [comment]
Fixed by #817, wasn't auto closed >.<
