### ISSUE TITLE
Android : can't launch a game

### ISSUE THREAD

**Issue by FaithFeather** [EasyRPG/Player#813]
So, i've try to compile (and re-compile, here goes the lost hours of sleep), and it seems to work pretty nice. But, when i try to launch it on my phone (Samsung Galaxy Express, btw), i can't launch a game? So, i've got two things : 
The first one is a JSO reading error : 

`03-09 20:43:14.047: E/JSO reading(10529): Error reading the file /storage/sdcard0/easyrpg/games/TestGame-2000/easyrpg-pref.txt
03-09 20:43:14.047: E/JSO reading(10529): /storage/sdcard0/easyrpg/games/TestGame-2000/easyrpg-pref.txt: open failed: ENOENT (No such file or directory)`

Which seems pretty correct because... The text file doesn't exist. And that's funny because if i try with the current app downloaded from the store, there isn't any problem with the same game. 
The second one is a runtime error : 

`03-09 20:31:50.257: E/JSO reading(9588): Error reading the file /storage/sdcard0/easyrpg/games/BogossStory/BogossStory/easyrpg-pref.txt
03-09 20:31:50.518: E/AndroidRuntime(9588): FATAL EXCEPTION: main
03-09 20:31:50.518: E/AndroidRuntime(9588): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.easyrpg.player/org.easyrpg.player.player.EasyRpgPlayerActivity}: java.lang.NullPointerException
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2087)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2112)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.app.ActivityThread.access$700(ActivityThread.java:139)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1223)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.os.Looper.loop(Looper.java:137)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.app.ActivityThread.main(ActivityThread.java:4917)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at java.lang.reflect.Method.invoke(Method.java:511)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:997)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at dalvik.system.NativeStart.main(Native Method)
03-09 20:31:50.518: E/AndroidRuntime(9588): Caused by: java.lang.NullPointerException
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.view.ViewGroup.addView(ViewGroup.java:3248)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.view.ViewGroup.addView(ViewGroup.java:3231)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at org.easyrpg.player.player.EasyRpgPlayerActivity.onCreate(EasyRpgPlayerActivity.java:91)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.app.Activity.performCreate(Activity.java:5047)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2051)
03-09 20:31:50.518: E/AndroidRuntime(9588): 	... 11 more`

Sorry, that's ugly. So, the main problem seems to be in the add of a view in the layout when the game is launch, where the said view is null. So i tried to comment the lines that caused the bug and now i've got this : 

`Error: Couldn't load SDL2: findLibrary returned null`

So... Maybe an error in the compilation ? But i don't find it.
Any help/advice ?

**Comment by Tondorian** [comment]
Sounds as if dependencies are missing.
Try: https://easy-rpg.org/jenkins/view/Toolchains/job/android-toolchain/
you will also need: https://github.com/EasyRPG/liblcf

**Comment by Ghabry** [comment]
Thx for the report. Is the Galaxy Express ARM or x86?

**Comment by FaithFeather** [comment]
I've already the liblcf and the toolchain. And the GE is on ARM.

**Comment by Ghabry** [comment]
Could you provide us the apk you created?

**Comment by FaithFeather** [comment]
Np, here's the apk :

[EasyRpg_apk.zip](https://github.com/EasyRPG/Player/files/166013/EasyRpg_apk.zip)

**Comment by BlisterBoy** [comment]
Hmm... Are you able to launch a game Ghabry?

Yay, another incompatible Samsung device!

**Comment by Ghabry** [comment]
Black screens and hangs

**Comment by BlisterBoy** [comment]
I don't understand. 
It was okay with your personal device, but you are using the virtual machin you linked yesterday and it doesn't work, right ?

**Comment by Ghabry** [comment]
ignore the black screen post, wrong topic ^^' . I just took a look in the APK and looks okay lib wise. Havn't tried booting this linked apk

**Comment by BlisterBoy** [comment]
This is what I obtain when launching a game : 
https://drive.google.com/file/d/0BzyFBzg6Eyy5b254a2wxSVR4RlE/view?usp=sharing

I have a Sony Xperia Z3 compact (Snapdragon 891 I think it's the ARMv7-A plartform version)

NB : FaitFeather can run the Playstore version of EasyRPG without any problem, so it's not a Samsung problem.

**Comment by Ghabry** [comment]
You are right. I only checked for the existance of libsdl. libmain.so is the native code of the Player. Make sure you ran ndk-build for Player :D

**Comment by FaithFeather** [comment]
So, I tried again /o/. 
And looks like ndk-build doesn't work.

`In file included from jni/src/../../../../src/system.h:44:0,
                 from jni/src/../../../../src/graphics.h:24,
                 from jni/src/org_easyrpg_player_player_EasyRpgPlayerActivity.cpp:26:
jni/src/../../../../src/memory_management.h:23:28: fatal error: boost/config.hpp: No such file or directory
 #include <boost/config.hpp>
                            ^
compilation terminated.
make: *** [obj/local/armeabi-v7a/objs/main/org_easyrpg_player_player_EasyRpgPlayerActivity.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from jni/src/../../../../src/async_handler.cpp:25:0:
jni/src/../../../../src/async_handler.h:21:30: fatal error: boost/function.hpp: No such file or directory
 #include <boost/function.hpp>
                              ^
compilation terminated.
make: *** [obj/local/armeabi-v7a/objs/main/__/__/__/__/src/async_handler.o] Error 1`

**Comment by Ghabry** [comment]
I finally found the error in our toolchain build (hopefully).

Delete everything and start again using this repo:
https://github.com/EasyRPG/buildscripts/tree/master/android

**Comment by FaithFeather** [comment]
Np, i'll try and keep in touch :)

**Comment by BlisterBoy** [comment]
Congratulation, now go fix some issue, may the Baguette be with you!

**Comment by BlisterBoy** [comment]
Guess I'll stick to the Android port ^^.
