### ISSUE TITLE
skills in skillmenu does not consume sp

### ISSUE THREAD

**Issue by Tondorian** [EasyRPG/Player#816]
Skills which are available form main menu can be casted with out any sp cost

**Comment by Ghabry** [comment]
Which skill menu do you mean? Battle or Map? Which engine?

**Comment by Tondorian** [comment]
the map skille menu, i saw this issue on RPG2k

**Comment by Tondorian** [comment]
Maybe it's not a skill menu issue ... 
Spell "Blutheilung" consumes sp 
But "Fledermausmantel" does not

**Comment by Ghabry** [comment]
Is possible that I fixed this one, needs a test

**Comment by Ghabry** [comment]
Works for me

**Comment by Ghabry** [comment]
Just for clarification: This was not in the battle scene but the normal Skill scene in the menu.

Fledermausmantel uses a switch skill.
