### ISSUE TITLE
Support libmpg123 for MP3 playback

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#818]
By using this amazing library, we would get the following:

- **Plays broken MP3** created with broken tools using libLAME incorrectly, properly skips data until finding the first valid frame (compliant decoder), which would be a fix for #721.

- **Gapless playback loops** where possible (it even supports special LAME gapless tags if they exist)

- libmpg123 is **maintained** (libmad is dead from more than a decade and needs a bunch of patches) and packaged in popular distros.

- Because we need new code for this, it would **prevent noises or crashes** due to buffer issues in existing libmad's dynamic_mp3/Mix_PlayMusic code when resampling (#781, #677).

- Supports MPEG-1/2/2.5 without issues (SMPEG crashes with some 2/2.5). Also supports I/II/III layers like libmad (layer III is enough I guess).

- LGPLv2.1, this license is compatible with code combination (and therefore static linking) with GPLv3. With libmad was also fine because it is GPLv2+.

Below there is a test program to demonstrate how it plays files properly.

**Comment by BlisterBoy** [comment]
That would be really nice to avoid the noise problem :).

**Comment by Zegeri** [comment]
It could also add MP3 playback in the OpenAL backend (sndfile doesn't support it).

**Comment by Ghabry** [comment]
How can this be implemented for SDL2? Is there any API in SDL_(mixer) to inject additional audio?

**Comment by Zegeri** [comment]
Yes, Mix_HookMusic.

**Comment by fdelapena** [comment]
There are several examples about using SDL_MixAudio in the callback used by Mix_HookMusic.
This one uses libmad: [SDL_mad.c](https://github.com/nothan/SDL-utils/blob/master/SDL_mad.c)

**Comment by Ghabry** [comment]
Ah okay, that's great! I only checked the documentation of Mix_HookAudio and I had no idea what the purpose of that is.

**Comment by fdelapena** [comment]
By the way, the SDL_MixAudio thin is not needed at all in the callback. The documentation itself points about this and RPG Maker 2000/2003 don't allow to play 2 music streams at once as BGM / ME, probably we don't need to deal with custom mixing at all.

Other Mix_HookMusic examples which can be found in GitHub with a simple search show how the stereo stream is just interleaved PCM samples as usual, I guess libmpg123 would bring the stream in the proper form without needing to deal with interleaving.

**Comment by fdelapena** [comment]
Some initial code for testing, but plays mp3 damn fast yet :laughing:.
The stream does not stop yet, use ctrl+c.

```cpp
#include "SDL.h"
#include "SDL_mixer.h"
#include <mpg123.h>
#include <stdio.h>

int musicPlaying;
mpg123_handle *handle = NULL;
int err = MPG123_OK;

void musicFinished() {
	musicPlaying = 0;
}

void play_mp3(void *udata, Uint8 *stream, int len) {
	size_t buffer_size = 0;
	Uint8 *buffer = 0;
	size_t done = 0;

	(void)(udata); /* Unused yet, silence the compiler */
	buffer_size = 4096;
	buffer = malloc(buffer_size);

	do {
		err = mpg123_read(handle, buffer, buffer_size, &done);
		SDL_MixAudio(stream, buffer, len, SDL_MIX_MAXVOLUME);
	} while (len && err != MPG123_OK);

	done = len;
}

int main(int argc, char *argv[]) {
	if (argc < 2) {
		printf("Usage: %s filename.mp3\n", argv[0]);
		return 1;
	}

	SDL_Init(SDL_INIT_AUDIO);
	Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 2048);
	mpg123_init();

	handle = mpg123_new(NULL, &err);
	mpg123_format_none(handle);
	mpg123_format(handle, 44100, 2, MPG123_ENC_SIGNED_16);
	mpg123_open(handle, argv[1]);

	Mix_HookMusic(play_mp3, NULL);
	musicPlaying = 1;
	Mix_HookMusicFinished(musicFinished);

	while (musicPlaying) SDL_Delay(1000);

	Mix_Quit();
	SDL_Quit();
	return 0;
}
```

**Comment by fdelapena** [comment]
Because Mix_HookMusic seems to work properly, I'm going to try to integrate fmmidi (#752), too.

@Zegeri I'm not familiar with the OpenAL API, feel free to provide an equivalent implementation or a minimal test case to start with.

**Comment by Ghabry** [comment]
Very cool, and so simple :+1:

**Comment by fdelapena** [comment]
The Mix_HookMusic documentation says about pause and resume working, but refers to paused music in the native player before using the custom HookMusic player. After stopping the HookMusic and returning the control to the native player it would allow to resume the previous native music player paused. In short, we need to handle our own pause and resume too.

Apart of pause and resume and the obvious play/stop, we also will need to handle fade in/out, volume and set the corresponding status flags.

I've updated the code example, now it will loop music and will print a message when the song is looping (finished). Useful for loop and gapless tests (there are mp3 files with bad gaps).

Suggested MP3 file for loop testing: Monigote Fantasy's `"Music/Tiny Toon Adventures - Special.mp3"`, this one is short, looks fine and feels gapless.

**Comment by Ghabry** [comment]
Is really lazy from the SDL mixer developers to not support Pause and Resume.
Do you tell us that Fade in/out and volume are also not supported???

Shame that the RWOps Api is so limited (concerning using buffers, whole file must be decoded already).
Because then you could create a WAV stream in memory, point a RWOps to it and pass this through the WAV code of SDL ;)...

**Comment by Ghabry** [comment]
Just got an idea how to abuse RWOps to do this for us :P
Only need to emit a fake WAV header and the PCM file size (if it's possible to calculate this)

Will write some code later to test this :D

**Comment by fdelapena** [comment]
If you want to use RWOps, there is mpg123_open_fd() and other ways to load the file.

**Comment by carstene1ns** [comment]
:+1: for using the native library api instead of implementing even uglier workarounds than we have currently (ghabry stahp /meme). How about adding an additional `fade_volume` variable and use that while mixing, there is a function in sdl(_mixer) for that. Then we just need to take care of changing that variable and handling of pause and stop is also not really black magic.

**Comment by Ghabry** [comment]
Well as pointed out by fdelepena the Mixer API supports volume changes so my suggestion RWops is not necessary ;)

**Comment by Ghabry** [comment]
Same here @fdelapena or @carstene1ns.
Though slightly different: MP3 support in SDL is just broken, so I suggest enabling this by default when mpg123 was found, otherwise compile without it.

I need a way to detect mpg123 and a flag to disable it if somebody wants to enjoy smpeg2 or libmad, probably "--disable-mpg123".

Do you know how to print a summary at the end of the configure step like some libraries do?
A warning to maintainers that SDL mp3 support is of questionable quality when mpg123 is not found would be useful.

**Comment by fdelapena** [comment]
There is already a `--disable-mpg123` option, however it forces to disable it explicitly to fallback to SDL_mixer's libmad, otherwise it won't build. This is a temporal solution, though.

As commented with @carstene1ns some days ago, a proper way would be a final summary table when configure script ends, then show some warnings about what will happen if using libmad instead mpg123, otherwise we will get false positives from people not reading the discreet warnings appearing between lines.

Having a final summary is relevant, already happened with some users building Player and forgetting to install SDL2 devel libs and building with SDL1.2 instead, then complaining about wrong music speed.

For the optional dependency it is explained at https://autotools.io/autoconf/arguments.html in the section 3.2.

**Comment by carstene1ns** [comment]
:+1: for automagic dependencies and a summary table!

btw. I already added one for the [converter tools](https://github.com/EasyRPG/Tools/commit/c950b39431e6ddc1ec9993e18a9c97920b918c20#diff-67e997bcfdac55191033d57a16d1408aR28).
It is basically shell syntax and interpolates variables.
