### ISSUE TITLE
Attribute multipliers of conditions not implemented

### ISSUE THREAD

**Issue by Zekario** [EasyRPG/Player#820]
Title. In an RPG Maker game I'm making, I have skills that should inflict conditions. They don't work; if the skill only inflicts the condition, it always misses, if it does damage as well, it only does damage.

Attributes don't work either. If I want, for example, a Slime to be weak to Fire (A) and immune to Ice (E), using a skill/attack with that attribute won't cause a damage boost/deduction.

**Comment by fdelapena** [comment]
Hi Zekario, thanks for your report.

Could you try again with the "EasyRPG Player continuous builds" from the tabs in this site?
https://easy-rpg.org/player/downloads/

This version should work with conditions at least. Please confirm if it works for you, also with attributes.

**Comment by Ghabry** [comment]
Hey. Thx for the report.

Inflicting conditions got fixed yesterday but attribute multipliers are not implemented yet.

**Comment by Tondorian** [comment]
Yeah but this issue will make games harder.
Will try to fix this anyway :)

**Comment by Zekario** [comment]
@fdelapena @Ghabry I tried the continuous builds, and conditions do seem to work, but attribute multipliers don't.

Thanks for working on this!

**Comment by Ghabry** [comment]
The conditions are also lacking a bit but the basics work:
What is working is: "Sleep" conditions (turn is skipped), Autoheal of conditions after X turns and Poison (damage each turn).
Silence is not handled (you can still cast spells), same for "Damage is halfed". Have to open the RPG Maker 2003 editor to check what is missing.

**Comment by Tondorian** [comment]
- [x] Silence is not handled (you can still cast spells)
- [ ] "Damage is halfed"
- [ ] "Attributes"
