### ISSUE TITLE
Battle System: Remaining, not implemented stuff

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#821]
This is a meta bug to track the remaining battle stuff that is not implemented.
When fixing bugs please reference #821 in your pull request :)
- [x] Battle Action: Defend command: Not working at all in 2003, not sure about 2000. (Animation is wrong in 2003 but this only visual)
- [x] Actor: Dual Wield: "Equip Weapon with both hands". When doing a normal attack the attack animations of both weapons will play and the damage is the sum of both. Also needs testing if the Equipment Scene handles this **since 0.6**
- [x] Actor: Mighty Guard: "The effect of the [Defend] command will be doubled, further reducing received damage."
- [x] Actor: Element Guard: Multiplier for damage receiving
- [x] Skills: Ignore defense: "the specified stat will be reduced without applying the opponent's defence."
- [x] Skills: States. The 2nd non-default option (Heal instead of Inflict) is not handled. **since 0.6.1**
- [x] Skills: Attack Element is not respected
- [x] Skills: Reduce Resistance "If enabled, the resistance to the checked types in (14) of the target characters will decrease or increase by 1 stage." (so from C to D, or C to B)
- [x] Skills: MP cost based on percentage
- [x] Items: Two handed (needs changes to Equipment scene?) **since 0.6**
- [x] Items: MP cost (What is this? You can use Items as skills, maybe they mean this)
- [x] Items: Critical rate: We only handle the actor critical rate
- [x] Items: Effect: Preemptive Advantage during battle "Ignores agility and attacks at the beginning of the turn." **Partly, not for 2k** **full since 0.6**
- [x] Items: Effect: Attack twice at the same time " Each normal attack hits the enemy twice." **since 0.6**
- [x] Items: Effect: Attack all enemies at the same time "Each normal attack hits the entire troop."
- [x] Items: Effect: Ignore enemy dodge rate "Attack accuracy ignores the enemy's agility." **since 0.6**
- [x] Items: Effect: Player can't unequip. The equipment cannot be removed. (Needs a change to the Equipment scene)
- [x] Items: Attack element
- [x] Items: State handling: needs tests
- [x] Items (Weapons): The 2nd option (heal instead of inflict) for states **since 0.6**
- [x] Items (Other): The 2nd option (inflict instead of resist) for states **since 0.6.1**
- [x] Items: State Infliction % (is that handled???)
- [x] Items: Prevent Critical Hits "Enemy characters will not critically hit the wearer". **since 0.6**
- [x] Items: Increase dodge rate for physical attacks "Normal attacks dealt by enemy characters will miss more often."
- [x] Items: Half MP Cost " The MP cost required for skills will be halved."
- [x] Items: Negate Terrain damage "Damage from terrain will not be taken." **since 0.6**
- [x] Items: Player can't unequip "The equipment cannot be removed." - Equipment scene **since 0.6**
- [x] Enemies: [Normal Attacks Miss] "the accuracy level of the enemy character's normal attacks is reduced to 70% instead of the usual 90%. This does not affect other moves like skills."
- [x] Enemies: Elemental Rate
- [x] States: Accuracy modifier **since 0.6**
- [x] States: Recover when Hit X% Chance of Recovery
- [x] States: 100% Dodge "In battle, for as long as this state is active, opponent attacks will not hit (except for skills)." **since 0.6**
- [x] States: Reflect Magic "In battle, for as long as this state is active, skills used by the opponent will be reflected and deal damage to the user instead."
- [x] States: Fixed Equipment  "For as long as this state is active, weapons and equipment cannot be changed." - Needs change to equipment scene **since 0.6**
- [x] States: Actor Status (Double and Halved)
- ~~[x] System2: Flip assets if facing the other direction "Not documented in the help file m("~~ Moved to #1564

![actor](https://cloud.githubusercontent.com/assets/1331889/13790773/5b897caa-eaea-11e5-9cab-dd4cb3cc7517.png)

![elements](https://cloud.githubusercontent.com/assets/1331889/13790778/5ecf3f62-eaea-11e5-9289-4722ca988728.png)

![enemies](https://cloud.githubusercontent.com/assets/1331889/13790785/6472cf10-eaea-11e5-8508-4e85fa621d18.png)

![items](https://cloud.githubusercontent.com/assets/1331889/13790791/68640706-eaea-11e5-8565-149d02848eaf.png)

![shield](https://cloud.githubusercontent.com/assets/1331889/13790803/6fd7074a-eaea-11e5-9a2d-eb70ea055749.png)

![skills](https://cloud.githubusercontent.com/assets/1331889/13790812/76b5c83a-eaea-11e5-8ed6-4561d115c59c.png)

![states](https://cloud.githubusercontent.com/assets/1331889/13790815/7ab78072-eaea-11e5-90c8-35c49b75fecd.png)

**Comment by Tondorian** [comment]
> Enemies: [Normal Attacks Miss] "the accuracy level of the enemy character's normal attacks is reduced to 70% instead of the usual 90%. This does not affect other moves like skills."

is allready handled in master
`game_battlealgorithm.cpp` line 474

**Comment by Ghabry** [comment]
The following will be fixed by #905 

"Items: Effect: Preemptive Advantage during battle "Ignores agility and attacks at the beginning of the turn."

"Items: Half MP Cost " The MP cost required for skills will be halved."

**Comment by fdelapena** [comment]
Is the "enable combo" feature in this list? several games show around 5 warnings per second with this one

**Comment by MudarraP** [comment]
Not sure if this one has been taken into account in the current list, I'll try to explain in detail.
There are items which can be selected as "Special" type and can be attached to skills. In the example image, the skill "Rompe-Barrera" decreases the enemy defense (which in the beginning of the battle was increased with another skill). In easyRPG using the item does nothing (the usage message is shown, and that's all), so the battle remains impossible, because the enemy can get his defense stronger with his skill, but you can't decrease his defense using the item.

![mdo-item](https://cloud.githubusercontent.com/assets/20684234/17178071/467b4aa8-5414-11e6-8e9c-872ead92f791.PNG)

**Comment by carstene1ns** [comment]
> System2: Flip assets if facing the other direction "Not documented in the help file m("

if I remember correctly, this affects Pom gets WI-FI, in `RPG_RT` they turn around:
![flip](https://p.f4ke.de/Hxef3EQWcz.png)

**Comment by Ghabry** [comment]
"Skills: States. The 2nd non-default option (Heal instead of Inflict) is not handled." breaks the skill Zwiestrich in Wolfenhain.

**Comment by Ghabry** [comment]
Not worth opening an extra issue: "Change Battle Commands"
"if there are already 6 battle commands, the command to [Add] will be ignored."

**Comment by Albeleon** [comment]
#1373 The number after each issue refers to each commit inside this PR
"Actor: Dual Wield: "Equip Weapon with both hands". When doing a normal attack the attack animations of both weapons will play and the damage is the sum of both. Also needs testing if the Equipment Scene handles this"
3.19: Implemented in 2k battles. Needs testing in 2k3 battles and the Equipment Scene.

"Items: Effect: Attack twice at the same time " Each normal attack hits the enemy twice.""
2.24: Implemented in battle 2k. Needs testing in 2k3.

" Items: Effect: Ignore enemy dodge rate "Attack accuracy ignores the enemy's agility.""
Was partly implemented in #1259 but now in 3.19 is updated to consider both weapons.

" Items: Prevent Critical Hits "Enemy characters will not critically hit the wearer"."
3.18: Implemented.

"States: Accuracy modifier"
2.34: Implemented.

**Comment by Ghabry** [comment]
@fmatthew5876 
Could you take a look at this?

The current status should be the following (or pending a merge):

Implemented:

- Actor: Dual Wield: "Equip Weapon with both hands". When doing a normal attack the attack animations of both weapons will play and the damage is the sum of both. Also needs testing if the Equipment Scene handles this
- Items: Two handed (needs changes to Equipment scene?)
- Items: Effect: Ignore enemy dodge rate "Attack accuracy ignores the enemy's agility."
- Items: Negate Terrain damage "Damage from terrain will not be taken."
- States: Accuracy modifier

Not sure:
- Skills: States. The 2nd non-default option (Heal instead of Inflict) is not handled. (do we handle this?)
- Items: Effect: Attack twice at the same time " Each normal attack hits the enemy twice." (do we handle this?)
- Items: The 2nd option (heal instead of inflict) for states

Missing?:
- Items: Effect: Player can't unequip. The equipment cannot be removed. (Needs a change to the Equipment scene)
- Items: Player can't unequip "The equipment cannot be removed." - Equipment scene
- States: Fixed Equipment "For as long as this state is active, weapons and equipment cannot be changed." - Needs change to equipment scene

**Comment by fmatthew5876** [comment]
These are in master, please check them off.

 * Actor: Dual Wield: "Equip Weapon with both hands". When doing a normal attack the attack animations of both weapons will play and the damage is the sum of both. Also needs testing if the Equipment Scene handles this
 * Items: Two handed (needs changes to Equipment scene?)
 * Items: Effect: Ignore enemy dodge rate "Attack accuracy ignores the enemy's agility."
 * States: Accuracy modifier
 * Items: Negate Terrain damage "Damage from terrain will not be taken." (Note: I also tested the screen does not flash when entire party is protected)
 * Items: Effect: Attack twice at the same time " Each normal attack hits the enemy twice." (do we handle this?)

This is implemented for weapons. Need to check for armor that inflicts states.

* Items: The 2nd option (heal instead of inflict) for states

The rest need to be checked further and/or implemented.

**Comment by fmatthew5876** [comment]
>     * Items: Effect: Player can't unequip. The equipment cannot be removed. (Needs a change to the 
Equipment scene)

This is already in master

>     * Items: Player can't unequip "The equipment cannot be removed." - Equipment scene
>     * States: Fixed Equipment "For as long as this state is active, weapons and equipment cannot be changed." - Needs change to equipment scene

In #1562

**Comment by fmatthew5876** [comment]
>  Items: Effect: Preemptive Advantage during battle "Ignores agility and attacks at the beginning of the turn." Partly, not for 2k

This is fully implemented in 0.6

**Comment by fmatthew5876** [comment]
With #1726 this is finally done
