### ISSUE TITLE
Reviving a dead actor deadlocks the RPG2k3 battle system

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#824]
Using a heal skills that can cure dead people the battle system hangs when the now revived actors gets his turn.

Havn't tried reproducing this yet, reported via mail.

[Save01.zip](https://github.com/EasyRPG/Player/files/178580/Save01.zip)

**Comment by Tondorian** [comment]
Tryed it right now seems to been fixed. It works with items and spells.
