### ISSUE TITLE
Android: Can't launch games 

### ISSUE THREAD

**Issue by Souigetsu** [EasyRPG/Player#827]
Hi ! 
Since last update on C files (Player/src) , launching a game crashes the application , i tried to rebuild with and older saved version of src and it works fine. 

Any help ?

**Comment by fdelapena** [comment]
Hi, could you try the nightly APK to discard any issue?
https://easy-rpg.org/jenkins/job/player-android/lastSuccessfulBuild/artifact/builds/android/bin/EasyRpgPlayerActivity.apk

**Comment by Souigetsu** [comment]
The Nightly apk run like a charm

**Comment by fdelapena** [comment]
Then probably there is some issue in your local setup, did you clean previously built files before trying again?

**Comment by Souigetsu** [comment]
I erased the previous apk then ran the ./4_build_android_port.sh, it pulled the changes on Player/src (11 files changed all in the src directory )  , and builded with success.

**Comment by Ghabry** [comment]
logcat with stacktrace pls

**Comment by Souigetsu** [comment]
I just solved my problem... by simply cleaning rep and rerun again and again ...

I don't know why or how, thank's for the help tho, sorry for the issue  ^^'

**Comment by fdelapena** [comment]
Yeah, it happens... I guess the Android building system does not have a reliable timestamp system for rebuilding or refreshing required stuff. This happens with most building systems anyways (autools, maven, etc.)
