### ISSUE TITLE
Embric of Wulfhammer's Castle: Ingame note not correctly shown

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#831]
In this game, there is a paper note attached to a wall. In RPG_RT, interacting with it displays the note as an image overlayed over the game. In EasyRPG, the image is not shown at all.

* Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
* Savegame (made with EasyRPG) demonstrating the problem: https://www.heavylobster.com/files/Save01.lsd

The savegame is made right in front of the problematic note, you merely need to interact it to see the problem.

**Comment by carstene1ns** [comment]
For the devs: `Map0003`, `EV0001`:
![event](http://picload.org/image/wppdgro/20160319131535_396x138.png)
