### ISSUE TITLE
Embric of Wulfhammer's Castle: Sound effect repeating incorrectly [MIDI loop point]

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#834]
This game has a scene in which the Duchess goes to sleep. It is accompanied by a short sound effect, which in RPG_RT plays only once. In EasyRPG, however, the sound effect incorrectly constantly repeats itself.
- Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
- Savegame demonstrating the problem: https://www.heavylobster.com/files/Save02.lsd

To reproduce, load the save game and talk to Alice (immediately in front of the Duchess in the savegame)

Edit: added [MIDI loop test](https://github.com/EasyRPG/Player/files/3006572/midi-loop-test.zip) case and [online test](https://easyrpg.org/play/master/?game=issue-834) in Emscripten (with FMMIDI).

-----

See #2199

**Comment by carstene1ns** [comment]
At a first glance, we do it right here. The music is set to `item.mid` and nowhere stopped.
For the devs: `Map0082`, `EV0011` (Alice):
![event](http://picload.org/image/wpwgror/20160320102742_501x226.png)

**Comment by carstene1ns** [comment]
Okay, this midi has a loop point at the end of the file and so `RPG_RT` seems to play silence.
Midi info:
```
    Start:  2.181816 seconds
    End:    5.517040 seconds
    Length: 3.335224 seconds

    LOOPSTART:  6.517040 seconds
    LOOPLENGTH: 0.000000 seconds
```

**Comment by fdelapena** [comment]
> Okay, this midi has a loop point at the end of the file and so RPG_RT seems to play silence.

Is the midi loop set with a "111" MIDI event controller change?

Event details:

The event time corresponds to the loop start place when the song ends.
 0xB0   This is the event numeric ID (176 in decimal) meaning channel 1 Control mode change (aka controller change)
 0x6F   (111 in decimal), Undefined in standard control table (RPG Maker 2000/2003/XP specific)
 0x00   The third event byte looks unused for this controller.

RTP's Battle3.mid example: 98 00 (delta time PPQ, place to restart) B0 6F 00 (controller 111)

**Comment by carstene1ns** [comment]
Yep.

**Comment by fdelapena** [comment]
Added an isolated test case and emscripten link in the OP post.

**Comment by Ghabry** [comment]
Moving to 0.6.3 because of massive Midi work right now :).

This is partially fixed now (FmMidi only).

**Comment by Ghabry** [comment]
4 years and 5 months. One of the longest standing issues 🎉
