### ISSUE TITLE
Abilities deal like 10% of the DMG they dealt prior to this patch.

### ISSUE THREAD

**Issue by Soranela** [EasyRPG/Player#840]
Hey, just updated my EasyRPG Player on Android and and i'm currently playing unterwegs in düsterburg and all magical spells to 4-5 dmg instead of 90-120~

the patch notes said "fixed dmg bugs" ,, i didn't have any dmg bugs prior.

**Comment by Ghabry** [comment]
Can we have a savegame? Must compare this to RPG_RT.

Well, we really fixed damage bugs. During the last days under certain conditions Normal attack and Skills resulted in a damage of 0. Yours seem to be another.

**Comment by Soranela** [comment]
Yes 100% a Bug - save Game in Attachement:
Start the save file, climb up the rope, fight the first enemy called "Düsterschreck".
Uses "Libra"s Ability "Schockfrost" it will deal like 80-100 Dmg in RPG_RP and 5 DMG in EasyRPG.
Use "Dankwart"s "Stoßgebet" and it will deal like 120-140 DMG" Compared to EasyRPGs 10-15DMG.

**Comment by Soranela** [comment]
Here in ZIP.
[Save01.zip](https://github.com/EasyRPG/Player/files/181815/Save01.zip)

**Comment by Tondorian** [comment]
i think https://github.com/EasyRPG/Player/pull/838/commits/48a81316e16ed8c9fe01cfb957e677574d97586e fixed this issue

**Comment by Ghabry** [comment]
This is already included in the Android version :).  We push APKs often to Android to find more bugs.
