### ISSUE TITLE
Battle/2k3: actor placement is wrong

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#851]
![bug](http://picload.org/image/rgroiici/screenshot_1.png)
Game: "Space Funeral: EARTH BIRTH" (http://duckstapler.com/earthbirth.html)
To reproduce, run battle 41, either through battle test, or [attached save game](https://github.com/EasyRPG/Player/files/192647/Save02.zip).

Expected:
![RPG_RT](http://picload.org/image/wwcpocr/2016-03-29-015314_326x267_escr.png)

Issue reported by mail.

---
At first I thought this would be related to #278, but the actors have all coordinates set here.

**Comment by Ghabry** [comment]
RPG_RT has completely different HP in the screenshots. Is this a bug or did you use different savegames to create them?

**Comment by carstene1ns** [comment]
I have replaced the screenshot now. It was from battle test, whereas now both are from the savegame.

**Comment by Ghabry** [comment]
Wine emulates the glitchy font rendering that happens under Windows (when Cleartype is enabled) perfectly btw :+1:

**Comment by Ghabry** [comment]
By just moving the characters by 4 pixels in all directions I figured out the default values are (instead of 0):
```
battle_x: 220
battle_y: 120
```
This should be adjusted in liblcf

**Comment by Ghabry** [comment]
Reported as fixed since https://github.com/EasyRPG/liblcf/pull/178
