### ISSUE TITLE
IDAT: invalid distance too far back

### ISSUE THREAD

**Issue by lpis** [EasyRPG/Player#856]
__Name of the game__:Nepheshel

__Player platform__ (e.g. Windows, Linux, Android, ...):Android

__Attach files__ (as a .zip archive or link them):
[Nepheshel203.zip](https://github.com/EasyRPG/Player/files/201908/Nepheshel203.zip)
 - A savegame next to the problem (if it isn't at the beginning of the game)
 - The easyrpg_log.txt logfile (you can find it in the game directory)

__Describe the issue in detail and how to reproduce it__:
![screenshot_2016-03-17-12-28-16](https://cloud.githubusercontent.com/assets/18257069/14240876/6f65a36a-fa8b-11e5-92cc-5faecaf60249.png)

As soon as the file opened, this error (says "IDAT: invalid distance too far back") comes up and never work

**Comment by Ghabry** [comment]
Thanks. This looks like a problem with our PNG image parser. We will investigate.

**Comment by fdelapena** [comment]
I've tested the attached game on desktop and loads PNG images properly. There is a known bug at least between libpng 1.6.0 and 1.6.3 showing this message. Maybe the libpng version used in the toolchain is outdated.

**Comment by Ghabry** [comment]
I can reproduce the bug under Windows (same Version as libpng on Android)

**Comment by Ghabry** [comment]
And we can't really fix this because libpng calls the error handler and when our error handler returns libpng terminates the application m(

**Comment by fdelapena** [comment]
It works for me with libpng 1.6.18, maybe there is a bug in the most recent version.

**Comment by Ghabry** [comment]
ImagePNG needs some error handling (a bool return) so that the callee can draw a checkerboard e.g.

I just remembered how to work around the libpng Exit:
```
jmp_buf env;

static void on_png_error(png_structp, png_const_charp error_msg) {
	Output::Warning("%s", error_msg);
	longjmp(env, 1);
}

// beginning of ReadPNG
	int jmp_res = setjmp(env);
	if (jmp_res == 1) {
		return;
	}
```

\o/

**Comment by carstene1ns** [comment]
@lpis: While we unfortunately cannot make the original image work with our used library, it can at least be replaced by yourself locally:
[![default](https://cloud.githubusercontent.com/assets/4691314/15621268/17af6120-2460-11e6-8c32-4db0cb5f31b3.png)](https://p.f4ke.de/JBEP2VKTPQ-nepheshelsystem.zip)
The image links to a zip archive containing the fixed image, extract it into `Nepheshel203/System` overwriting the broken one and you should be able to play the game.

---

@Ghabry: While I think it is a good idea to draw the checkerboard for all other missing or broken images, using our own system image in this case is better yet. We ship it anyway and the worst thing that could happen is that the game texts/messages looks a bit ugly if the creator changed the colors too much (i.e. very dark vs. our shiny green). But even this is better than having no system image at all (mixed/chopped checkerboards everywhere).

**Comment by Ghabry** [comment]
Yeah, you are right. I forgot about the special case for "System"

**Comment by fdelapena** [comment]
> It works for me with libpng 1.6.18, maybe there is a bug in the most recent version.

Confirmed it happens here with 1.6.23, also affects libpng-dependent programs, such eog.

**Comment by fdelapena** [comment]
> Note that this will memleak on error but because this is error is so seldom I don't think this will really hurt.

@Ghabry the `setjmp` error handling leak could be mitigated by freeing png data if any, nullptr `info_ptr` if not null and calling `png_destroy_read_struct` if `png_ptr` is not null as usual, at least other software do this way in the error handler.

LGTM for the crash workaround and also a solution for this particular game, as currently there is an embedded fallback system graphics file as carstene1ns points :+1:.

**Comment by carstene1ns** [comment]
The double jump @Ghabry proposes is not necessary. Combined with @fdelapena's idea this will likely be memleak free.
