### ISSUE TITLE
Integrate 3DS port

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#863]
@Rinnegatamante wrote a nice Nintendo 3DS port which is mature enough for being integrated in the main codebase.

https://github.com/Rinnegatamante/easyrpg-player-3ds

Scheduling this for 0.4.2, so will happen this month. :)

**Comment by Ghabry** [comment]
@Rinnegatamante
The strange upstream crash was fixed in #865 :)

Can you tell me where to get libkhax? I only found random header files on github without a Makefile.
Is that lib still needed?

**Comment by Rinnegatamante** [comment]
You just have to compile libkhax with a makefile with a library as target. You can also use libkhax in my repository here: https://github.com/Rinnegatamante/lpp-3ds_libraries

**Comment by Ghabry** [comment]
Progress update: A script for deploying all dependencies via Jenkins will be finished today.

Branch merging will happing during the week depending on how busy I am.

**Comment by Ghabry** [comment]
The 3DS toolchain works now.

The commits of the 3DS code are cherry picked, I only need to add some final compile fixes because boost got removed and some Player code changed.
And make some adjustments to the Makefile because we have it in builds/3ds/Makefile.

**Comment by Ghabry** [comment]
This is solved now and only needs a website update and a blog post.
All files are available at: https://easy-rpg.org/jenkins/job/player-3ds/
