### ISSUE TITLE
Player needs to be updated for new libs

### ISSUE THREAD

**Issue by Zekario** [EasyRPG/Player#864]
I tried to run Player, but it didn't work. I couldn't reinstall it either, it fails to build.
Here's the error I get from trying to build it (viewing source might be better than the Markdown version):

/usr/bin/ld: warning: libicui18n.so.56, needed by /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.56, needed by /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.56, needed by /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `ucnv_close_56'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `ucsdet_detect_56'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `ucnv_fromUChars_56'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `ucsdet_getName_56'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `ucnv_toUChars_56'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `ucsdet_setText_56'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `ucnv_open_56'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `ucsdet_open_56'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `u_errorName_56'
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/liblcf.so: undefined reference to `ucsdet_close_56'
collect2: error: ld returned 1 exit status
Makefile:1523: recipe for target 'easyrpg-player' failed
make[1]: *** [easyrpg-player] Error 1

**Comment by carstene1ns** [comment]
Hi @Zekario, which version of the Player do you use? i.e. where did you download it or did you build it yourself?

**Comment by carstene1ns** [comment]
If you compile it yourself, you need to rebuild liblcf.

**Comment by fdelapena** [comment]
No reply so far, assuming this is fixed as it works for us.
