### ISSUE TITLE
Android : gradlew clean delete object files from the ndk-build

### ISSUE THREAD

**Issue by BlisterB** [EasyRPG/Player#867]
Problem with `gradlew clean`
This is not the same as ant clean. ant only deleted the java part of the build. gradlew also deleted the object files from the ndk-build which results in a full recompile everytime (waste of time :/)

Hint : 
http://stackoverflow.com/questions/21096819/jni-and-gradle-in-android-studio

**Comment by Ghabry** [comment]
guess this can be closed, we solved this by not calling "clean" anymore, still works as expected ^^
