### ISSUE TITLE
Text command messages in a row should share their message window

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#871]
Affected game: PeuterisGrey ([download](http://s000.tinyupload.com/index.php?file_id=35755637109549384388), [emscripten](https://easy-rpg.org/play/index-master.html?game=peuterisgrey))

In RPG_RT the intro produces some animation (like pressing backspace in a document):
http://p.f4ke.de/LIwlh2zaHw-peuteris-rpgrt.webm
While in Player the message window closes and opens multiple times
and the text gets written each time again:
http://p.f4ke.de/P2Bbh4Iios-peuteris-player.webm

Isolated testcase: [testcase_message.zip](https://github.com/EasyRPG/Player/files/233567/testcase_message.zip)

**Comment by Ghabry** [comment]
OKay that bug looks funny :D
