### ISSUE TITLE
Embric of Wulfhammer's Castle: (another) savegame compatibility EasyRPG <-> RPG_RT. Battler animation not saved

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#876]
While bug #602 was fixed a while back, upon testing of bug #875 I noticed that there's still issues with savegame compatibility between EasyRPG and RPG_RT in this game. To be more specific, RPG_RT crashes if you load an EasyRPG savegame and enter battle with it. RPG_RT gives the error message "Event script referenced a battle animation that does not exist."

* Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
* Example savegame made with EasyRPG (and liblcf) git:  https://www.heavylobster.com/files/Save07.lsd

To reproduce, walk towards the east to start the encounter after going through some dialogue (the 'Zhen die without explanation' option is fastest). RPG_RT will crash once the actual encounter begins.

**Comment by Ghabry** [comment]
FYI: This will not be fixable in old savegames. Just saving again will not fix it. For old savegames it will fix itself when the Event command "Change Class" is executed.
