### ISSUE TITLE
Order of updates of events that walk into each other is incorrect

### ISSUE THREAD

**Issue by Zegeri** [EasyRPG/Player#884]
Here's to document some really crazy behaviour in RPG_RT.
Imagine you have some events lined up. Each of them has a move route that makes them walk to the position of the event right next to it, like here:
![captura de pantalla_2016-05-02_20-23-35](https://cloud.githubusercontent.com/assets/4390703/14963484/24a16164-10a4-11e6-9f1f-924a9053f46d.png)
In RPG_RT, they all walk together nicely **without colliding into each other**. While in Player some of them will collide with the one right next to it for a frame and create enought space between them to walk. If the events have IDs 1, 2, 3 and 4 and they're in the map lined up horizontally in that order from left to right. Player will update first the event 1, that will try to walk right and collide with 2. 2 will collide with 3 and 3 with 4. 4 can walk, so it'll be slightly ahead of the rest of them. In the next frame, 3 gets slightly ahead of 1 and 2. And so on.
![captura de pantalla_2016-05-02_20-38-29](https://cloud.githubusercontent.com/assets/4390703/14963842/de73cf9a-10a5-11e6-85b7-9d92381f97b7.png)
(Image from Player. Up: From left to right, events 1, 2, 3, 4 collide as described. Down: From left to right, events 4, 3, 2, 1 don't collide)
Here's the interesting part, in RPG_RT it doesn't matter the order of events, they all walk always together. Ghabry's eventtracer is again useful to tell what's happening. Let's use the followind ordering of events: 2, 1, 4, 3. The tracer reports that the order of execution the move commands has been 1, 4, 3, 2. Weird, we expected 1, 2, 3, 4. After trying other permutations it can be deduced that **when an event checks the passability of a tile, it executes the move route of the events that are in that tile to see if they move out of the way**. So in that last example, 1 is causing 4 to update because he's in the way, which is causing 3 to update because he's in the way. 2 isn't blocking anyone, so he gets updated as soon the tree of updates that 1 leads ends.
![de](https://cloud.githubusercontent.com/assets/4390703/14964529/c6df6cba-10a8-11e6-9df2-0f25c046a1f0.png)
Crazy stuff.

[Download a test sample](https://dl.dropboxusercontent.com/u/30277047/TestEventsOrder.7z). This bug will be fixed when the two lines of events walk with the same spacing between them.

**Comment by Ghabry** [comment]
Wow, RPG_RT is really smart at this point. Very unexpected feature :o

**Comment by Zegeri** [comment]
Some notes:
* In RPG_RT, some variable must be used to make sure an event doesn't get updated twice. After some experiments with eventtracer, it seems that the DynRPG field Character::_unknown_74 is responsible for this. In [PepsiOtaku's fork](https://github.com/PepsiOtaku/DynRPG/blob/master/Character.h#L153), this variable was (erroneously) renamed to onMap.
* Notice that in Player, move routes and parallel interpreter are updated together (Game_Event::UpdateParallel). This still holds in this circumstances. In the last example, event 1 not only executes the move routes of event 4, but it also updates its interpreter if it's a parallel event.
* The hero might also get updated early by this mechanism. Because of this, events will be able walk to the hero's position at the same frame the player press a movement key. This is relevant for #703.

**Comment by scurest** [comment]
I notice Github has decided to make it extremely obvious that I had to `--amend` >_>

**Comment by fmatthew5876** [comment]
Does anyone have a copy of the test case saved on their computer? The link for this one no longer works.

**Comment by fmatthew5876** [comment]
Nevermind, I retested this with #1678 using the following array of events walking right

| Event | Event | Event | Event |
| -- | -- | -- | --|
| 1 | 2 | 3 | 4 |
| 8 | 7 | 6 | 5 |
| 10 | 9 | 12 | 11 |
| 13 | 16 | 15 | 14 |

All the events move right smoothly. No difference between Player and RPG_RT.
