### ISSUE TITLE
Regression: Music volume needs to be reset

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#888]
This issue happens at least in **Melon Journey** ([download](https://rpgmaker.net/games/4204/), [emscripten](https://easy-rpg.org/play/index-master.html?game=melon_journey)).

When you are about to enter any house, the music is set to fade out in 1 sec (by the door event).
The house maps have set their own music, but no event controlling the volume, so default should be used.

What happens is that the music volume gets lower every time you enter or leave a house, making it silent for the remaining game. This does not occur in 0.4.0.

Use this link to start in a house and do not have to play the introduction:
https://easy-rpg.org/play/index-master.html?game=melon_journey&start-map-id=19&start-party=1&start-position=9%209

(Note, that I have patched the game start on emscripten to not use that slow walking speed, because it is annoying^^)

**Comment by Ghabry** [comment]
This really feels like PKMN Blue before getting the bike
