### ISSUE TITLE
Ara Fell: Saving with RPG_RT in the KeyRoom and loading in EasyRPG doesn't place the key "below hero"

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#890]
In Ara Fell you can't pickup the key in the key room when you load a RPG_RT save in EasyRPG.
The key must be "below the hero" but it is "same Level" instead, making the game unplayable until reloading the room. The reason could be also that there is a 2nd event with "same Level" called "sparkle" above the key.
RPG_RT savegame is attached. [Save05.zip](https://github.com/EasyRPG/Player/files/254099/Save05.zip)

![unbenannt](https://cloud.githubusercontent.com/assets/1331889/15100256/2f1a2bc6-156d-11e6-8b06-b118099f1d92.png)

**Comment by Zegeri** [comment]
The reason is straightforward, we don't save or load the phasing mode (a.k.a. ghost mode or through mode) flag.

**Comment by Ghabry** [comment]
thx, I only checked for layering issues
