### ISSUE TITLE
もしもスマブラだったら: characters don't die when touching the bottom of the arena

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#892]
__Name of the game__: 	もしもスマブラだったら (Wannabe Smash Bros.)

__Download__: http://viprpgsum15.webcrow.jp/sakuhin.html?71

__Testcase__: https://easy-rpg.org/play/index-master.html?game=smashbros

__Describe the issue in detail and how to reproduce it__: ~~After the character select the game fails to find picture "hp_%". HTML5 only issue~~ Fixed at #894.
Characters don't die when touching the bottom of the arena.

![71](https://cloud.githubusercontent.com/assets/1331889/15214121/8f5148c2-184b-11e6-952e-f394d6564780.png)

**Comment by Ghabry** [comment]
Correction: The missing "hp_%" file is a web error. the % is not correctly encoded and apache responds with "bad request"

**Comment by Ghabry** [comment]
Player#894 fixes the HTML5 part.
Characters don't die when touching the bottom of the arena.

**Comment by fdelapena** [comment]
It also affects the top part of the arena sometimes. Enemies (and also the own player) can be sticked there (weird). However when jumping from there still can die.
