### ISSUE TITLE
Startup fails on systems with no audio device

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#902]
When running on a system with no audio device (e.g. Windows RDP session without audio forwarding) the start fails with ```DirectSoundCreate: No audio device found``` even when ```--disable-audio``` is passed.
Probably because this is a part of the normal SDL init process.

**Comment by carstene1ns** [comment]
Yes, this is because we always use the same initial flags for SDL, even if we additionally check for the subsystem in the sdl audio backend.
That being said, this is a one-line change to make it work.

**Comment by carstene1ns** [comment]
This is fixed now when passing `--disable-audio` flag.
