### ISSUE TITLE
Echoes of the Past: Some maps can't be left

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#903]
__Name of the game__: Echoes of the Past [(Download)](http://rpg2000.4players.de/index.php?inhalt=spiele2&action=suche&suche=Echoes%20of%20The%20Past)

__Attach files__ (as a .zip archive or link them): [Save02.zip](https://github.com/EasyRPG/Player/files/289599/Save02.zip)

__Describe the issue in detail and how to reproduce it__:
Load the attached Save02.lsd. You should be able to leave the map on the left and on the right side but this doesnt work as expected.
This works with a parallel process which compares the Player's X position against 0 and 21 and initiates a teleport when this condition is met.

The location is changed when the movement to the tile starts. Which results in the teleport starting at this moment:
![screenshot_1](https://cloud.githubusercontent.com/assets/1331889/15655516/293fad88-269e-11e6-9bc1-737cf0ada345.png)

The movement is then finished from this location on the new map which results in walking in the forest again (instead of standing on it when the teleport finished) resulting in the on-touch-trigger being executed and the forest is reentered :laughing: 
![screenshot_0](https://cloud.githubusercontent.com/assets/1331889/15655518/2ab8cd66-269e-11e6-8044-2b7ebd75be94.png)

**Comment by Ghabry** [comment]
Have to clarify this issue, because the explanation is wrong (should have tested it beforehand :D)

**Comment by Zegeri** [comment]
ef964313bb should fix this.
