### ISSUE TITLE
Battle: allied battlecharas using the same actor sprite

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#916]
__Name of the game__: El Heredero del Rey
__Player platform__: Any

This following issue seems to regress once again and can be reproduced in current master:

![The allied character is the same for all](https://cloud.githubusercontent.com/assets/174885/15309090/c6292484-1ba0-11e6-9966-c4513faaec6e.png)

**Comment by Ghabry** [comment]
Ugh, I'm sorry :(. Will fix it asap next week. Or any other dev this week :smile:

**Comment by Ghabry** [comment]
The reason must be  Game_Actor::GetBattleAnimationId returning 1. Good luck.

**Comment by scurest** [comment]
[Cause](https://github.com/EasyRPG/Player/commit/75bbf2c6b2529df7c69ba5971f9694afa306503f#diff-34f34f675ce52452da855f1469fc5421R957).

I'm guessing, by comparison to the rest of that commit, the necessary change is

    -               if (GetData().class_id > 0) {
    +               if (GetData().changed_class && GetData().class_id > 0) {

which does indeed fix it. Look okay, Ghabry?

**Comment by Ghabry** [comment]
Ah I think I know the real reason. The battle_animation field is only set when the class was changed at least once (that bool flag "class_changed"). So for the case that the class was preset you have to do a DB lookup in Data::classes. Or we just ignore the savegame field completely and look in the db only (the field can only be modifed by setting a class)

**Comment by Ghabry** [comment]
By looking at the database I observe that the characters have defaults settings for animations... I guess scurest suggestion is totally right ^^' . 2003 beaing stupid agian.

**Comment by Ghabry** [comment]
Okay by some testing I observed: The Class that you set under Actor/Hero in the database **doesn't matter at all.** 
It is displayed under "Status" but this is only a optical thing.

To get anything of the stuff under "Class" tab used you have to use the Change class event command... WAT.
This also means reverting to the start behaviour (optical "Status" and nothing else) is **not possible**.

**Comment by carstene1ns** [comment]
[Patch available]
