### ISSUE TITLE
Freeze while resizing the variable array multiple times

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#920]
**Name of the game**: thouhou alive 1.07 (東方ALIVE)

**Player platform**: Android (likely all)

**Describe the issue in detail and how to reproduce it**:

The variable array is endlessly increased by some event, making the game unresponsive.
Issue submitted by mail:

> A movie stops at a prolog by the illusion volume. Is this the bug?

Log excerpt:

```
[2016-07-03 18:17:28] Debug: Loading Map Map0557.lmu
[2016-07-03 18:17:28] Debug: Tree: VS魔理沙 < マヨヒガ城 < 幻想編Chapter1
[2016-07-03 18:17:57] Debug: Resizing variable array to 1101 elements.
[...]
[2016-07-03 18:23:46] Debug: Resizing variable array to 71587 elements.
```

**Comment by fdelapena** [comment]
It happens with both original or translated version.

[Game download](https://onedrive.live.com/?cid=F87EF6D0A3619382&id=F87EF6D0A3619382%21105) (Japanese, unpack with `unar`).
[Game download](http://www.mediafire.com/?twb96m5aqax9vde) (English translation by vgperson).

How to reproduce:

`easyrpg-player --start-map-id 557`

It starts after a couple of seconds, goes black screen, event with ID 0 exceeds execution limit a few times while increasing some array size elements.

Here after 71587 elements resizing it goes to the title screen.
With the vgperson's translated version it ends after 76587 elements.

**Comment by Ghabry** [comment]
Have a patch which makes the resizing more efficient (always reserve id + 1000) and the output less verbose (only 10 per run).

**Comment by Zegeri** [comment]
> Have a patch which makes the resizing more efficient (always reserve id + 1000) 

I'm not sure why would that be more efficient. This reallocates the vector every time, not once the capacity has been reached. This means that the whole vector could be reallocated 76587 times.

**Comment by Ghabry** [comment]
You are right, without checking ``capacity()`` the patch makes no sense at all.
