### ISSUE TITLE
Dhux Scar: hang after some messages while trying to move a cursor on map

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#929]
__Name of the game__: [Dhux's Scar](https://rpgmaker.net/games/1492/)

__Player platform__: Any, probably

__Attach files__:

* [Savegame](https://github.com/EasyRPG/Player/files/360109/Save01.lsd.zip)

__Describe the issue in detail and how to reproduce it__:

Walk to the right, then a navigation map will appear. It looks there are multiple events there, also displaying messages, which might mess with events in the wrong order or not stopping them which might be related somehow, but not tested.
There is a cursor over the forest, it should allow to be moved to left/right to select other places but it does not work. Menu is still accessible, though.

**Comment by Zegeri** [comment]
I'm getting a hang upon loading the save file.

**Comment by fdelapena** [comment]
Fixed link, sorry

**Comment by Zegeri** [comment]
bf902a3fc28d should fix this.
