### ISSUE TITLE
Events blocked after moving to places where other events left in the same switch

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#935]
Not sure what is happening, maybe is getting the forbid event overlap property from events were there previously ~~or something else related with event ID order or not updating overlap properties after moving the previous events in that place. Maybe this does not make sense even in RPG_RT, but this is working there~~. Event 0012 in the center top is moving the enemies to the edges.

A [test case](https://fran.cr/nextcloud/index.php/s/2k2ownFDpuYZ2p2/download?path=%2F&files=issue935.zip) kindly provided by Brassman is available for download.

How to reproduce: Move the player until the center of the map, an ambush will be triggered by moving the enemies to the map edges. In RPG_RT, events they will move, but not in Player.

**Comment by Zegeri** [comment]
You were on the right track. It's because of overlap forbidden.

9c4cf32 shoud fix this.
