### ISSUE TITLE
Calm Falls: custom menu system should block the main menu

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#940]
This one seems to be a `RPG_RT` quirk again. [Calm Falls game download](http://s000.tinyupload.com/index.php?file_id=09973221626269785361)

All tutorials I found that dealt with custom menu systems, will start in an initialization event to disable the main menu to use the custom one (i.e. [this](https://rpgmaker.net/tutorials/395/)). Using this event command: [`Main Menu Access: Forbid`](http://www.rpg-studio.org/wiki/images/e/ee/Rm2kDisableMenu.png)
This technique is used by most games out there in the wild.

Calm Falls does not use this event command, yet the custom menu system (managed by a automatic/parallel common event, that checks the keyinputproc) prevents the main menu in `RPG_RT`.
In `Player` the main menu opens after closing the custom one.

At first I thought the executable is patched, but also using a vanilla `RPG_RT` will not show the main menu.

**Comment by Ghabry** [comment]
The same happens (normal menu opens after closing custom) in vampires dawn btw

**Comment by Ghabry** [comment]
Actually. @zegeri commit changed the behaviour. Before, the menu-scene opened when you closed the scripted one (as carsten wrote), now the menu-scene opens WHEN you open the custom menu...

**Comment by carstene1ns** [comment]
This seems even worse if the custom menu is not accessible.

**Comment by Ghabry** [comment]
Well both menus open at the same time and you can use the custom after closing the normal.
