### ISSUE TITLE
Embric of Wulfhammer's Castle: Occasional segfault in --battle-test

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#950]
*    Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z

While messing with the --battle-test argument, I ended up finding a random segfault: occasionally when starting a new battle, Player instantly segfaults.

Terminal output and a backtrace obtained with gdb at http://pastebin.com/raw/1LftgHvE .

To reproduce, run Player with the arguments "--window --battle-test 5". Most of the time, Player starts up with no issues, but occasionally it segfaults basically instantly. Thus to reproduce the issue, I run Player, close it after waiting for a second or so, and repeat until the segfault occurs.

**Comment by Ghabry** [comment]
MSVC conveniently has range checks in the debug mode. The real crash is a out of range access at:

```
 	Playerd.exe!std::vector<RPG::Enemy,std::allocator<RPG::Enemy> >::operator[](unsigned int _Pos) Zeile 1236	C++
 	Playerd.exe!Game_Enemy::Transform(int new_enemy_id) Zeile 167	C++
 	Playerd.exe!Game_Enemy::Setup(int enemy_id) Zeile 34	C++
 	Playerd.exe!Game_Enemy::Game_Enemy(int enemy_id) Zeile 30	C++
 	Playerd.exe!std::_Ref_count_obj<Game_Enemy>::_Ref_count_obj<Game_Enemy><int const &>(const int & <_Args_0>) Zeile 901	C++
 	Playerd.exe!std::make_shared<Game_Enemy,int const &>(const int & <_Args_0>) Zeile 971	C++
>	Playerd.exe!Game_EnemyParty::Setup(int battle_troop_id) Zeile 45	C++
 	Playerd.exe!Scene_Battle::InitBattleTest() Zeile 186	C++
 	Playerd.exe!Scene_Battle::Start() Zeile 75	C++
 	Playerd.exe!Scene::MainFunction() Zeile 75	C++
 	Playerd.exe!Player::MainLoop() Zeile 262	C++
 	Playerd.exe!Player::Run() Zeile 257	C++
 	Playerd.exe!SDL_main(int argc, char * * argv) Zeile 35	C++
 	Playerd.exe!main_utf8(int argc, char * * argv) Zeile 126	C
 	Playerd.exe!main(int argc, char * * argv) Zeile 134	C
 	Playerd.exe!invoke_main() Zeile 64	C++
 	Playerd.exe!__scrt_common_main_seh() Zeile 255	C++
 	Playerd.exe!__scrt_common_main() Zeile 300	C++
 	Playerd.exe!mainCRTStartup() Zeile 17	C++
 	kernel32.dll!73f138f4()	Unbekannt
 	ntdll.dll!76f15de3()	Unbekannt
 	ntdll.dll!76f15dae()	Unbekannt
```

This battle contains an invalid enemy with an ID of 104.

**Comment by Ghabry** [comment]
In RPG_RT this battle fails with "Event referenced enemy that doesn't exist"
