### ISSUE TITLE
MIDI synth restarts every time the music changes

### ISSUE THREAD

**Issue by Wuerfel21** [EasyRPG/Player#951]
**Name of the game**: Any (I tried Vampires Dawn)

**Player platform** (e.g. Windows, Linux, Android, ...): Windows 64 bit

**Describe the issue in detail and how to reproduce it**:
Every time the music changes, I get a couple seconds of lag while my MIDI synth starts back up. I use Coolsoft Virtual MIDI Synth with a ~150MB Soundfont. The MIDI synth should be opened exactly once when the player starts(or alternatively when the first MIDI is played) and should stay open.  Almost all games that use MIDI do this.

**Comment by Ghabry** [comment]
This is a bug in the audio library we use (SDL2_mixer) and we are currently replacing it because it lacks features we need and has bugs that we can't fix by our own (like the one you mentioned).

The MIDI playback is not replaced yet on most platforms (including Windows) but it will happen in the upcoming months.
Looks like Coolsoft Virtual MIDI Synth uses sound fonts (sf2), support for them is possible.

**Comment by arromdee** [comment]
Would replacing MIDI playback allow MIDI on 3DS?

**Comment by carstene1ns** [comment]
@arromdee: SDL is not used on 3DS, but instead our own audio stuff. Yes, using it will allow MIDI playback, but we are currently still working on that.

**Comment by gadesx** [comment]
150MB Soundfont it's a lot of memory, I loaded some of that in FL studio and need some seconds to load all in ram.

**Comment by carstene1ns** [comment]
When we replace sdl_mixer with any other lib, we do not use the native windows midi anymore (besides when using e.g. portmidi). This means there will be no loading problem with this anymore, since fluidsynth or whatever will do this.

**Comment by fmatthew5876** [comment]
Slow midi performance is now causing frame skipping on windows with the new framerate code.

I noticed this when testing vehicle code and thought it was a logical bug when it was this.

To see the effect, set the ship BGM and then board the ship. If you use wav or OFF, the character will step onto the ship as normal in boarding. If you use midi, the character and the screen will pop onto the ship.

I observe this on my windows x64 desktop with modern hardware.

**Comment by Ghabry** [comment]
Assigning @tyrone-sudeium 

The hardware synth branch will solve this.

**Comment by Ghabry** [comment]
have a patch based on the native-synth branch that solves this by creating the Platform specific out device only once and then reusing it.
