### ISSUE TITLE
Embric of Wulfhammer's Castle: Parts of character portraits missing in battle

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#954]
While looking at the screenshots attached to bug #949 , I realized that Player does not seem to correctly render character portraits in battle; in particular, it looks as if they all are missing a rectangular piece in the top right corner in comparison to RPG_RT.

Screenshots for comparison:

Player:
![screenshot from 2016-07-25 20-10-15](https://cloud.githubusercontent.com/assets/2873449/17144682/43e1c7fe-5360-11e6-887d-6e0d6ecde72d.png)

RPG_RT:
![ghabry](https://cloud.githubusercontent.com/assets/2873449/17144696/4d6c9326-5360-11e6-8c2f-edd31d1f6178.png)

This problem can be reproduced in --battle-test, so no savegame should be necessary for this one. Game download at https://aeresland.net/EmbricDELUXE_2.2.2.7z

**Comment by Ghabry** [comment]
Looks like a bug in the rendering order. Will fix this one together with the other battle bug

**Comment by carstene1ns** [comment]
> bug in the rendering order
Either that or the `H` and `M` are rendered without transparency.

**Comment by Ghabry** [comment]
This also didn't affect Ara Fell because it used smaller face graphics which didn't touch the H/M overlay >.<
Good to have Embric for fixing the remaining issues :D
