### ISSUE TITLE
Embric of Wulfhammer's Castle: Duchess fails to follow Embric in the Anti-Paladin arc ending

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#955]
This ending has a scene in which the Duchess is supposed to head to Embric's room with him. However, this does not work correctly. 

Video demonstrating the issue can be seen at:
https://www.heavylobster.com/files/embric.mp4 (problem is visible starting at 0:22)

* Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
* Savegame: http://www.heavylobster.com/files/Save08.lsd

To reproduce, complete the battle against the Anti-Paladins. After some bits of dialogue, you'll reach the bugged scene.

**Comment by Ghabry** [comment]
Are there any "waiting" events colliding with each other? In that case it could be #937

**Comment by Siltala** [comment]
This bug seems to be random or has a non-obvious trigger, since it does not seem to occur every time for me.
Anyway, here is a video of the correct behavior: https://www.heavylobster.com/files/embric_working.mp4

It looks to me like in the broken case, after going upstairs the Duchess ends up one tile too many to the right, leading to her being blocked by an unpassable tile.

**Comment by Zegeri** [comment]
This is a bug in the game and can be reproduced in RPG_RT. To get this issue, rush through the dialogue until the Duchess says "Thank you all.". Wait until she's walking to the right like in the picture and then press the enter key.
![embric1](https://cloud.githubusercontent.com/assets/4390703/17313244/3bb01744-585a-11e6-85ae-47ee9a108dba.png)
The game will teleport the duchess to the new map after the message "Thank you all." ends. After the teleportation, she'll continue her movement to the right in both RPG_RT and EasyRPG. She'll end up in the tile she shouldn't be.
