### ISSUE TITLE
Call Inn with missing inn music hangs

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#956]
The Inn call command should behave in these cases with missing music files as in the (OFF) music case (instant fadeout+fadein). In player, it hangs however.

Test case: [inntest.zip](https://github.com/EasyRPG/Player/files/384271/inntest.zip).

Reported via email twice by 伊藤孝仁 and Tomoyuki Kashiwabara.

**Comment by Ghabry** [comment]
I guess this was also broken for the EmptyAudio case? Actually PlayedOnce has no return there, so you get something random oO
