### ISSUE TITLE
Embric of Wulfhammer's Castle: Carriage to Elstwhere moves too fast

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#959]
* Savegame: https://www.heavylobster.com/files/Save14.lsd
* Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z

During a traveling scene in this game, the carriage moves too fast in comparison to RPG_RT, leading to the scene looking.. odd.

Videos demonstrating the issue can be seen here:
* Player: https://www.heavylobster.com/files/broken_carriage.mp4 (broken)
* RPG_RT: https://www.heavylobster.com/files/working_carriage.mp4 (correct behavior)

To reproduce, load my savegame, talk to Grettel right in front of the duchess and choose to go to Elstwhere.

**Comment by carstene1ns** [comment]
btw. this is also a regression for the intro.

**Comment by Ghabry** [comment]
Maybe our characters are really moving 10% faster as the Yume Nikki Player claimed. Guess is a good idea to record all movements and compare the speed.
