### ISSUE TITLE
Embric of Wulfhammer's Castle: Equipped items with skills not correctly counted in inventory in battles

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#962]
This is probably the most trivial bug ever, but hey, it's still a bug! :P

If you have an item that has a skill equipped, enter combat and look at your inventory, the game reports you have 0x of said item. It is still usable, though. RPG_RT correctly reports that you do have 1x of said item.

Screenshot:
![screenshot_2](https://cloud.githubusercontent.com/assets/2873449/17193725/057df9da-545d-11e6-951b-3b60acfa2792.png)
- Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
- Savegame: http://www.heavylobster.com/files/Save08.lsd

**Comment by Ghabry** [comment]
Theres another bug here. When the item is equipped and in the inventory the item appears twice in the menu.
