### ISSUE TITLE
Embric of Wulfhammer's Castle: Post-credits scene incorrectly appears twice

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#963]
After finishing an ending and going through the game credits, you end up back ingame (unless you choose to quit) and a short post-credits scene follows. This works perfectly fine, if you skip the credits (press enter during credits), but if you actually wait all the way to the end before going back ingame, after said post-credits scene the game actually asks if you want to skip the credits again, though they aren't even rolling anymore, after which it does a second post-credits scene. This doesn't happen with RPG_RT.

Videos illustrating the problem (spoilers!!!):
* Correct behavior, as seen after skipping credits: https://www.heavylobster.com/files/working_credits.mp4
* Broken behavior after going through the credits: https://www.heavylobster.com/files/broken_credits.mp4

* Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
* Savegame: https://www.heavylobster.com/files/Save09.lsd

To reproduce, load the savegame, talk to Scheherazade right in front of the Duchess, choose 'Girls night out tonight' and watch the shortest ending ingame by far. As far as I could tell, all endings have the issue, though.

**Comment by Zegeri** [comment]
bb95079e785 should fix this.
