### ISSUE TITLE
3DS crash on Moby Housekeeper

### ISSUE THREAD

**Issue by arromdee** [EasyRPG/Player#964]
__Name of the game__: Moby Housekeeper

__Player platform__: 3DS, .cia version  (Edit: Using the continuous build)

__Describe the issue in detail and how to reproduce it__:  Load the game Moby Housekeeper from https://rpgmaker.net/games/23/ .  Play it on a 3DS (I used the English translated RTP--using a Japanese RTP is problematic because of the FAT32 on the SD card).  Start a new game, see the E rating screen, then it either crashes or locks up.  It does not do this on a PC.
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/391667/easyrpg_log.txt)

**Comment by carstene1ns** [comment]
This game uses mp3 music, so this is likely the same issue as #910.
Can you try renaming/removing the `Music` folder to be sure?

**Comment by arromdee** [comment]
That does seem to be it; renaming the Music folder fixes it.

**Comment by Ghabry** [comment]
Closing as duplicate then
