### ISSUE TITLE
Battle 2k3: Support the random enemy troops option that is hidden in the context menu

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#987]
No idea which chunk this is but RPG2k3 has a feature that when enabled randomizes the monster party:

![screenshot_20160811_215759](https://cloud.githubusercontent.com/assets/1331889/17602846/c19a02be-600e-11e6-9d21-de3d395929a1.png)

Assuming a monster party consists of monster 1, 2 and 3 any combination of that available monsters can appear in the battle

**Comment by Ghabry** [comment]
Moving this to 0.5.2 because with the chunk identified this is trivial to implement (Candidate function: Game_EnemyParty::Setup).
Things to test in 2k3:
 - Are such monster just hidden (equivalent to right click monster -> hide) and can be brought on the battle with an event command?
 - Is the "monster hidden" flag respected?

@CherryDT do you know any game that uses this feature? I still havn't found any 😢 .

**Comment by rohkea** [comment]
> Are such monster just hidden (equivalent to right click monster -> hide) and can be brought on the battle with an event command?

Just tested this: yes, they are hidden, and can be brought to the battle with an event command.

> Is the "monster hidden" flag respected?

Yes. Only non-hidden monsters are randomized. Hidden monsters are not affected by this option. If you have a monster party with 4 hidden and 1 non-hidden monsters, this option will do nothing.

**Comment by rohkea** [comment]
I’ve found a game using this feature: a Japanese game Default of Default+ ([description](http://www.freem.ne.jp/win/game/13721), [download](http://www.freem.ne.jp/dl/win/13721)). Monster groups 3, 4, 5, 41, 46, 79, 107, 108 are random.

**Comment by Ghabry** [comment]
A bit late but I just parsed the entire rmarchiv to find a usage for this @rygos 

- Super Pokemon Eevee Edition uses it alot (20 times)
- Oracle of Tao only once
- Alex adventures 4 times
