### ISSUE TITLE
PS Vita: Crash when SE channels are exhausted

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#992]
This happens because SE_Play does not check if there are any free channels.

Could be e.g. fixed by initializing a Semaphore to se channel count (7?) and then aquiring the Semaphore at the beginning of SE thread-for-loop and releasing it at the end of the for-loop.

The main thread could check this semaphore and when it is 0 (= would block) issue a Output::Warning and ignore that SE (like the SDL audio version does).

**Comment by Rinnegatamante** [comment]
A game where this could be easily reproduced for testing?

**Comment by carstene1ns** [comment]
![the_amount_of_SE_is_too_damn_high](https://p.f4ke.de/htpS2CFHNo.png)
-
1. Use Ib ver. 107 (english)
2. Use this savegame https://upload.af/yjgc88juhaml 
3. Go into the separation room and inspect the painting.
4. ???
5. PROFIT

**Comment by Ghabry** [comment]
[se-crash.zip](https://github.com/EasyRPG/Player/files/417026/se-crash.zip)

Here is an artificial test.

**Comment by Ghabry** [comment]
I only accept patches that show 493 "No free channels available" warnings in the 500 SE testcase ;)
